---
permalink: switch-cisco-3232c/cn5596-complete-migration.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: Vous pouvez utiliser des switchs Cisco Nexus 3232C en tant que switchs de cluster dans votre cluster AFF ou FAS. 
---
= Effectuez votre migration de 5596 switchs vers des switchs 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Procédez comme suit pour finaliser la migration des switchs Nexus 5596 vers des switchs Nexus 3232C.

.Étapes
. Vérifier que les commutateurs de cluster appropriés sont surveillés :
+
`system cluster-switch show`

+
.Montrer l'exemple
[%collapsible]
====
[listing]
----
cluster::> system cluster-switch show

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                          cluster-network    10.10.1.103      NX3232C
     Serial Number: FOX000001
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

C2                          cluster-network    10.10.1.104      NX3232C
     Serial Number: FOX000002
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

2 entries were displayed.
----
====
. Si vous avez supprimé la création automatique de cas, réactivez-la en appelant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.Et la suite ?
link:../switch-cshm/config-overview.html["Configurer la surveillance de l'état des commutateurs"].
