---
permalink: switch-cisco-3232c/cn5596-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: Avant de configurer les commutateurs Cisco Nexus 3232c, consultez un aperçu du processus et de la nomenclature. 
---
= Exigences de migration
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Les commutateurs Cisco Nexus 3232C peuvent être utilisés comme commutateurs de cluster dans votre cluster AFF ou FAS . Les commutateurs de cluster vous permettent de créer des clusters ONTAP avec plus de deux nœuds.

[NOTE]
====
La procédure nécessite l'utilisation à la fois des commandes ONTAP et des commandes des commutateurs Cisco Nexus série 3000 ; les commandes ONTAP sont utilisées sauf indication contraire.

====
Pour plus d'informations, voir :

* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Commutateurs Ethernet Cisco"^]
* link:http://hwu.netapp.com["Hardware Universe"^]




== Configuration requise Cisco Nexus 5596

Les commutateurs du cluster utilisent les ports suivants pour les connexions aux nœuds :

* Nexus 5596 : ports e1/1-40 (10 GbE)
* Nexus 3232C : ports e1/1-30 (10/40/100 GbE)


Les commutateurs du cluster utilisent les ports de liaison inter-commutateurs (ISL) suivants :

* Nexus 5596 : ports e1/41-48 (10 GbE)
* Nexus 3232C : ports e1/31-32 (40/100 GbE)


Lelink:https://hwu.netapp.com/["_Hardware Universe_"^] contient des informations sur le câblage pris en charge pour les commutateurs Nexus 3232C :

* Les nœuds dotés de connexions de cluster 10 GbE nécessitent des câbles de dérivation à fibre optique QSFP vers SFP+ ou des câbles de dérivation en cuivre QSFP vers SFP+.
* Les nœuds avec connexions de cluster 40/100 GbE nécessitent des modules optiques QSFP/QSFP28 compatibles avec des câbles à fibre optique ou des câbles à connexion directe en cuivre QSFP/QSFP28.


Les commutateurs du cluster utilisent le câblage ISL approprié :

* Début : Nexus 5596 (SFP+ vers SFP+)
+
** 8 câbles à connexion directe SFP+ fibre ou cuivre


* Solution provisoire : passage du Nexus 5596 au Nexus 3232C (adaptateur QSFP vers 4xSFP+)
+
** 1 câble de dérivation fibre optique ou cuivre QSFP vers SFP+


* Final : Nexus 3232C vers Nexus 3232C (QSFP28 vers QSFP28)
+
** 2 câbles à connexion directe QSFP28 en fibre optique ou en cuivre


* Sur les commutateurs Nexus 3232C, vous pouvez faire fonctionner les ports QSFP/QSFP28 en modes Ethernet 40/100 Gigabit ou Ethernet 4 x10 Gigabit.
+
Par défaut, il existe 32 ports en mode Ethernet 40/100 Gigabit.  Ces ports Ethernet 40 Gigabit sont numérotés selon une convention de nommage par paires.  Par exemple, le deuxième port Ethernet 40 Gigabit est numéroté 1/2.

+
Le processus de changement de configuration de 40 Gigabit Ethernet à 10 Gigabit Ethernet est appelé _breakout_ et le processus de changement de configuration de 10 Gigabit Ethernet à 40 Gigabit Ethernet est appelé _breakin_.

+
Lorsque vous divisez un port Ethernet 40/100 Gigabit en 10 ports Ethernet Gigabit, les ports résultants sont numérotés selon une convention de nommage à 3 tuples.  Par exemple, les ports de dérivation du deuxième port Ethernet 40/100 Gigabit sont numérotés 1/2/1, 1/2/2, 1/2/3 et 1/2/4.

* Sur le côté gauche des commutateurs Nexus 3232C se trouvent 2 ports SFP+, appelés 1/33 et 1/34.
* Vous avez configuré certains ports des commutateurs Nexus 3232C pour fonctionner à 10 GbE ou 40/100 GbE.
+
[NOTE]
====
Vous pouvez configurer les six premiers ports en mode 4x10 GbE en utilisant le `interface breakout module 1 port 1-6 map 10g-4x` commande.  De même, vous pouvez regrouper les six premiers ports QSFP+ de la configuration de dérivation en utilisant le `no interface breakout module 1 port 1-6 map 10g-4x` commande.

====
* Vous avez effectué la planification, la migration et lu la documentation requise sur la connectivité 10 GbE et 40/100 GbE des nœuds aux commutateurs de cluster Nexus 3232C.
* Les versions ONTAP et NX-OS prises en charge dans cette procédure sont disponibles à l'adresse suivante :link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Commutateurs Ethernet Cisco"^] .


.À propos des exemples utilisés
Les exemples de cette procédure décrivent le remplacement des commutateurs Cisco Nexus 5596 par des commutateurs Cisco Nexus 3232C.  Vous pouvez utiliser ces étapes (avec des modifications) pour d'autres commutateurs Cisco plus anciens (par exemple, 3132Q-V).

La procédure utilise également la nomenclature suivante pour les commutateurs et les nœuds :

* Les résultats des commandes peuvent varier en fonction des différentes versions d' ONTAP.
* Les commutateurs Nexus 5596 à remplacer sont *CL1* et *CL2*.
* Les commutateurs Nexus 3232C destinés à remplacer les commutateurs Nexus 5596 sont *C1* et *C2*.
* *n1_clus1* est la première interface logique de cluster (LIF) connectée au commutateur de cluster 1 (CL1 ou C1) pour le nœud *n1*.
* *n1_clus2* est le premier LIF de cluster connecté au commutateur de cluster 2 (CL2 ou C2) pour le nœud *n1*.
* *n1_clus3* est la deuxième LIF connectée au commutateur de cluster 2 (CL2 ou C2) pour le nœud *n1*.
* *n1_clus4* est la deuxième LIF connectée au commutateur de cluster 1 (CL1 ou C1) pour le nœud *n1*.
* Le nombre de ports 10 GbE et 40/100 GbE est défini dans les fichiers de configuration de référence (RCF) disponibles sur lelink:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Téléchargement du fichier de configuration de référence du commutateur réseau en cluster Cisco"^] .
* Les nœuds sont *n1*, *n2*, *n3* et *n4*.


Les exemples de cette procédure utilisent quatre nœuds :

* Deux nœuds utilisent quatre ports d'interconnexion de cluster 10 GbE : *e0a*, *e0b*, *e0c* et *e0d*.
* Les deux autres nœuds utilisent deux ports d'interconnexion de cluster 40 GbE : *e4a* et *e4e*.
+
Lelink:https://hwu.netapp.com/["_Hardware Universe_"^] liste les ports de cluster réels sur vos plateformes.



.Scénarios abordés
Cette procédure couvre les scénarios suivants :

* Le cluster commence avec deux nœuds connectés et fonctionnant dans deux commutateurs de cluster Nexus 5596.
* Le commutateur de cluster CL2 doit être remplacé par C2 (étapes 1 à 19) :
+
** Le trafic sur tous les ports du cluster et les LIF sur tous les nœuds connectés à CL2 est migré vers les premiers ports du cluster et les LIF connectés à CL1.
** Débranchez le câblage de tous les ports du cluster sur tous les nœuds connectés à CL2, puis utilisez un câblage de dérivation compatible pour reconnecter les ports au nouveau commutateur de cluster C2.
** Débranchez le câblage entre les ports ISL entre CL1 et CL2, puis utilisez un câblage de dérivation compatible pour reconnecter les ports de CL1 à C2.
** Le trafic sur tous les ports du cluster et les LIF connectés au C2 sur tous les nœuds est rétabli.


* Le commutateur de cluster CL2 doit être remplacé par C2.
+
** Le trafic sur tous les ports de cluster ou LIF sur tous les nœuds connectés à CL1 est migré vers les seconds ports de cluster ou LIF connectés à C2.
** Débranchez le câblage de tous les ports du cluster sur tous les nœuds connectés à CL1 et reconnectez-le, à l'aide d'un câblage de dérivation pris en charge, au nouveau commutateur de cluster C1.
** Débranchez le câblage entre les ports ISL entre CL1 et C2, et reconnectez-le à l'aide d'un câblage compatible, de C1 à C2.
** Le trafic sur tous les ports du cluster ou les LIF connectés à C1 sur tous les nœuds est rétabli.


* Deux nœuds FAS9000 ont été ajoutés au cluster, avec des exemples illustrant les détails du cluster.


.Quelle est la prochaine étape ?
link:cn5596-prepare-to-migrate.html["Préparez-vous à la migration"].
