---
permalink: switch-cisco-3232c/concept-migrate-a-cn1610-switch-to-a-cisco-nexus-3232c-cluster-switch.html 
sidebar: sidebar 
keywords: migrate, cn1610 switch, cisco nexus 3232c cluster 
summary: Vous devez connaître certaines informations de configuration, connexions de ports et exigences de câblage lorsque vous remplacez des switchs de cluster CN1610 par des switchs de cluster Cisco Nexus 3232C. 
---
= Migrez un switch CN1610 vers un switch de cluster Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez connaître certaines informations de configuration, connexions de ports et exigences de câblage lorsque vous remplacez des switchs de cluster CN1610 par des switchs de cluster Cisco Nexus 3232C.

Les commutateurs du cluster prennent en charge les connexions de nœud suivantes :

* NetApp CN1610 : ports 0/1 à 0/12 (10 GbE)
* Cisco Nexus 3232C : ports e1/1-30 (40 ou 100 ou 4 x 10 GbE)


Les commutateurs de cluster utilisent les ports ISL (Inter-switch Link) suivants.

* NetApp CN1610 : ports 0/13 à 0/16 (10 GbE)
* Cisco Nexus 3232C : ports 1/31-32 (100 GbE)


[NOTE]
====
Vous devez utiliser des câbles de dérivation 4x10G sur le switch de cluster Cisco Nexus 3232C.

====
Le tableau suivant présente les connexions de câblage requises à chaque étape lors de la transition des switchs NetApp CN1610 vers les switchs de cluster Cisco Nexus 3232C :

|===
| Étape | Description | Câbles requis 


 a| 
Initiale
 a| 
CN1610 à CN1610 (SFP+ à SFP+)
 a| 
4 câbles à connexion directe en fibre optique ou cuivre SFP+



 a| 
Transition
 a| 
CN1610 à 3232C (QSFP à SFP+)
 a| 
1 câbles QSFP et 4 SFP+ à fibre optique ou cuivre



 a| 
Final
 a| 
3232C à 3232C (QSFP à QSFP)
 a| 
2 câbles à connexion directe cuivre ou fibre optique QSFP

|===
Vous devez avoir téléchargé les fichiers de configuration de référence applicables (CFR). Le nombre de ports 10 GbE et 40/100 GbE est défini dans les CFR disponibles sur le https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Téléchargement du fichier de configuration de référence du commutateur réseau en cluster Cisco®"^] page.

Les versions ONTAP et NX-OS prises en charge dans cette procédure sont répertoriées sur le link:https://mysupport.netapp.com/NOW/download/software/cm_switches/.html["Page commutateurs Ethernet Cisco"^].

Les versions ONTAP et FASTPATH prises en charge lors de cette procédure sont répertoriées sur le link:http://support.netapp.com/NOW/download/software/cm_switches_ntap/.html["Page des commutateurs NetApp CN1601 et CN1610"^].
