---
permalink: switch-cisco-3232c/concept-migrate-from-a-two-node-switchless-cluster-to-a-cluster-with-cisco-nexus-3232c-cluster-switches.html 
sidebar: sidebar 
keywords: migrate, two-node cluster, switchless, cisco nexus 3232c 
summary: Lorsque vous migrez un cluster sans commutateur à deux nœuds vers un cluster avec des switchs de cluster Cisco Nexus 3232C, vous devez connaître certaines informations de configuration, de connexions de ports et de câblage. 
---
= Migrer d'un cluster sans commutateur à 2 nœuds vers un cluster avec des switchs de cluster Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous migrez un cluster sans commutateur à deux nœuds vers un cluster avec des switchs de cluster Cisco Nexus 3232C, vous devez connaître certaines informations de configuration, de connexions de ports et de câblage.

Le link:http://mysupport.netapp.com/NOW/download/software/cm_switches/.html["Page commutateurs Ethernet Cisco"^] Possède des informations sur les versions ONTAP et NX-OS prises en charge dans cette procédure.

Vous devez disposer des éléments suivants avant de lancer le processus de migration :

* Ports disponibles pour les connexions des nœuds
+
Les commutateurs de cluster utilisent les ports ISL (Inter-Switch Link) e1/31-32. -

* Câbles appropriés pour les connexions du cluster :
+
** Les nœuds équipés de connexions de cluster 10 GbE requièrent des modules optiques QSFP avec des câbles à fibre optique dérivation ou des câbles QSFP avec des câbles de dérivation en cuivre SFP+.
** Les nœuds équipés de connexions en cluster 40/100 GbE nécessitent des modules optiques QSFP/QSFP28 avec des câbles à fibre optique ou des câbles à connexion directe en cuivre QSFP/QSFP28.
** Les commutateurs de cluster nécessitent des câbles ISL appropriés : 2 câbles à connexion directe en fibre ou en cuivre QSFP28.


+
[NOTE]
====
Voir la link:https://hwu.netapp.com/["_Hardware Universe_"^] Pour plus d'informations sur le câblage des systèmes avec des switchs Nexus 3232C.

====

