---
permalink: switch-cisco-3232c/configure-reqs-3232c.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: Vous pouvez utiliser des commutateurs Cisco Nexus 3232C comme commutateurs de cluster dans votre cluster AFF ou FAS . 
---
= Configuration requise pour les commutateurs Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour l'installation et la maintenance du commutateur Cisco Nexus 3232C, assurez-vous de consulter les exigences de configuration et de réseau.



== Exigences de configuration

Pour configurer votre cluster, vous avez besoin du nombre et du type appropriés de câbles et de connecteurs de câbles pour vos commutateurs.  Selon le type de commutateur que vous configurez initialement, vous devez vous connecter au port console du commutateur avec le câble console fourni ; vous devez également fournir des informations réseau spécifiques.



== Exigences réseau

Vous avez besoin des informations réseau suivantes pour toutes les configurations de commutateurs :

* Sous-réseau IP pour le trafic du réseau de gestion
* Noms d'hôte et adresses IP pour chacun des contrôleurs de système de stockage et tous les commutateurs applicables
* La plupart des contrôleurs de système de stockage sont gérés via l'interface e0M en se connectant au port de service Ethernet (icône de clé). Sur les systèmes AFF A800 et AFF A700 , l'interface e0M utilise un port Ethernet dédié.


Se référer à https://hwu.netapp.com["Hardware Universe"^] pour obtenir les dernières informations.

.Quelle est la prochaine étape
Après avoir confirmé vos exigences de configuration, vous examinez le link:required-documentation-3232c.html["documentation requise"].
