---
permalink: switch-cisco-3232c/install-rcf-software-3232c.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 3232c 
summary: 'SSH est une exigence lors de l"utilisation des fonctionnalités de Cluster Switch Health Monitor (CSHM) et de collecte de journaux. Pour activer SSH sur les commutateurs de cluster Cisco 3232c, vous générez d’abord les clés SSH, puis vous activez SSH.' 
---
= Installez le fichier de configuration de référence (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous installez le fichier de configuration de référence (RCF) après avoir configuré les commutateurs Nexus 3232C pour la première fois.

.Avant de commencer
Vérifiez les installations et connexions suivantes :

* Une sauvegarde actuelle de la configuration du commutateur.
* Un cluster parfaitement fonctionnel (aucune erreur dans les journaux ni problème similaire).
* Le RCF actuel.
* Une connexion console au commutateur est nécessaire lors de l'installation du RCF.


.À propos de cette tâche
La procédure nécessite l'utilisation à la fois des commandes ONTAP et des commandes des commutateurs Cisco Nexus série 3000 ; les commandes ONTAP sont utilisées sauf indication contraire.

Aucune liaison inter-commutateurs opérationnelle (ISL) n'est nécessaire pendant cette procédure. Ceci est intentionnel car les changements de version RCF peuvent affecter temporairement la connectivité ISL. Pour permettre des opérations de cluster sans interruption, la procédure suivante migre tous les LIF de cluster vers le commutateur partenaire opérationnel tout en exécutant les étapes sur le commutateur cible.

Assurez-vous de terminer la procédure danslink:prepare-install-cisco-nexus-3232c.html["Préparez-vous à installer NX-OS et RCF"] , puis suivez les étapes ci-dessous.



== Étape 1 : Installez le RCF sur les commutateurs

. Connectez-vous pour commuter cs2 en utilisant SSH ou en utilisant une console série.
. Copiez le RCF sur le bootflash du commutateur cs2 à l'aide de l'un des protocoles de transfert suivants : FTP, TFTP, SFTP ou SCP. Pour plus d'informations sur les commandes Cisco , consultez le guide approprié dans le https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Guide de référence des commandes NX-OS Cisco Nexus série 3000"^] .
+
.Afficher un exemple
[%collapsible]
====
Cet exemple montre comment TFTP est utilisé pour copier un RCF dans la mémoire flash de démarrage du commutateur cs2 :

[listing, subs="+quotes"]
----
cs2# *copy tftp: bootflash: vrf management*
Enter source filename: *Nexus_3232C_RCF_v1.6-Cluster-HA-Breakout.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. Appliquez le RCF précédemment téléchargé à la mémoire flash de démarrage.
+
Pour plus d'informations sur les commandes Cisco , consultez le guide approprié dans le https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Guide de référence des commandes NX-OS Cisco Nexus série 3000"^] .

+
.Afficher un exemple
[%collapsible]
====
Cet exemple montre le fichier RCF `Nexus_3232C_RCF_v1.6-Cluster-HA-Breakout.txt` en cours d'installation sur le commutateur cs2 :

[listing, subs="+quotes"]
----
cs2# *copy Nexus_3232C_RCF_v1.6-Cluster-HA-Breakout.txt running-config echo-commands*
----
====
+
[NOTE]
====
Assurez-vous de lire attentivement les sections *Notes d'installation*, *Notes importantes* et *bannière* de votre RCF. Vous devez lire et suivre ces instructions pour garantir la configuration et le fonctionnement corrects du commutateur.

====
. Examinez la sortie de la bannière à partir de `show banner motd` commande.  Vous devez lire et suivre les instructions figurant dans la section *Remarques importantes* pour assurer la configuration et le fonctionnement corrects du commutateur.
. Vérifiez que le fichier RCF est bien la version la plus récente correcte :
+
`show running-config`

+
Lorsque vous vérifiez le résultat pour vous assurer que vous avez le RCF correct, vérifiez que les informations suivantes sont correctes :

+
** La bannière RCF
** Paramètres du nœud et du port
** Personnalisations
+
Le résultat varie en fonction de la configuration de votre site.  Vérifiez les paramètres du port et consultez les notes de version pour connaître les modifications spécifiques à la version de RCF que vous avez installée.



. Réappliquez les personnalisations précédentes à la configuration du commutateur.  Se référer àlink:cabling-considerations-3232c.html["Examiner les considérations relatives au câblage et à la configuration"] pour plus de détails sur les modifications supplémentaires nécessaires.
. Enregistrez les détails de configuration de base dans le `write_erase.cfg` fichier sur la mémoire flash de démarrage.
+
[NOTE]
====
Assurez-vous de configurer les éléments suivants : * Nom d'utilisateur et mot de passe * Adresse IP de gestion * Passerelle par défaut * Nom du commutateur

====
+
`cs2# show run | section "switchname" > bootflash:write_erase.cfg`

+
`cs2# show run | section "hostname" >> bootflash:write_erase.cfg`

+
`cs2# show run | i "username admin password" >> bootflash:write_erase.cfg`

+
`cs2# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`cs2# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

. Lors de l'installation de RCF version 1.12 et ultérieures, exécutez les commandes suivantes :
+
`cs2# echo "hardware access-list tcam region racl-lite 512" >> bootflash:write_erase.cfg`

+
`cs2# echo "hardware access-list tcam region qos 256" >> bootflash:write_erase.cfg`

+
Consultez l'article de la base de connaissances https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Comment effacer la configuration d'un commutateur d'interconnexion Cisco tout en conservant la connectivité à distance"^] pour plus de détails.

. Vérifiez que le `write_erase.cfg` Le fichier est rempli comme prévu :
+
`show file bootflash:write_erase.cfg`

. Émettre le `write erase` commande pour effacer la configuration enregistrée actuelle :
+
`cs2# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. Copiez la configuration de base précédemment enregistrée dans la configuration de démarrage.
+
`cs2# *copy bootflash:write_erase.cfg startup-config*`

. Redémarrer le commutateur cs2 :
+
`cs2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Répétez les étapes 1 à 12 sur le commutateur cs1.
. Connectez les ports de cluster de tous les nœuds du cluster ONTAP aux commutateurs cs1 et cs2.




== Étape 2 : Vérifiez les connexions du commutateur

. Vérifiez que les ports du commutateur connectés aux ports du cluster sont *actifs*.
+
`show interface brief | grep up`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show interface brief | grep up*
.
.
Eth1/1/1      1       eth  access up      none                    10G(D) --
Eth1/1/2      1       eth  access up      none                    10G(D) --
Eth1/7        1       eth  trunk  up      none                   100G(D) --
Eth1/8        1       eth  trunk  up      none                   100G(D) --
.
.
----
====
. Vérifiez que l'ISL entre cs1 et cs2 est fonctionnel :
+
`show port-channel summary`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/31(P)   Eth1/32(P)
cs1#
----
====
. Vérifiez que les LIF du cluster sont revenues à leur port d'origine :
+
`network interface show -role cluster`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
            Logical            Status     Network            Current             Current Is
Vserver     Interface          Admin/Oper Address/Mask       Node                Port    Home
----------- ------------------ ---------- ------------------ ------------------- ------- ----
Cluster
            cluster1-01_clus1  up/up      169.254.3.4/23     cluster1-01         e0d     true
            cluster1-01_clus2  up/up      169.254.3.5/23     cluster1-01         e0d     true
            cluster1-02_clus1  up/up      169.254.3.8/23     cluster1-02         e0d     true
            cluster1-02_clus2  up/up      169.254.3.9/23     cluster1-02         e0d     true
            cluster1-03_clus1  up/up      169.254.1.3/23     cluster1-03         e0b     true
            cluster1-03_clus2  up/up      169.254.1.1/23     cluster1-03         e0b     true
            cluster1-04_clus1  up/up      169.254.1.6/23     cluster1-04         e0b     true
            cluster1-04_clus2  up/up      169.254.1.7/23     cluster1-04         e0b     true
8 entries were displayed.
cluster1::*>
----
====
+
Si des LIFS de cluster ne sont pas revenus à leurs ports d'origine, rétablissez-les manuellement :
`network interface revert -vserver <vserver_name> -lif <lif_name>`

. Vérifiez que le cluster est sain :
+
`cluster show`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
cluster1-01          true    true          false
cluster1-02          true    true          false
cluster1-03          true    true          true
cluster1-04          true    true          false
4 entries were displayed.
cluster1::*>
----
====




== Étape 3 : Configurez votre cluster ONTAP

NetApp recommande d'utiliser System Manager pour configurer de nouveaux clusters.

System Manager fournit un flux de travail simple et facile pour la configuration et l'installation du cluster, y compris l'attribution d'une adresse IP de gestion de nœud, l'initialisation du cluster, la création d'un niveau local, la configuration des protocoles et l'approvisionnement du stockage initial.

Se référer à https://docs.netapp.com/us-en/ontap/task_configure_ontap.html["Configurer ONTAP sur un nouveau cluster avec System Manager"] pour les instructions d'installation.

.Quelle est la prochaine étape ?
Une fois le RCF installé, vous pouvez link:configure-ssh-keys.html["vérifier la configuration SSH"].
