---
permalink: switch-cisco-3232c/migrate-from-two-node-switchless-cluster.html 
sidebar: sidebar 
keywords: migrate, two-node cluster, switchless, cisco nexus 3232c 
summary: 'Si vous disposez d"un cluster sans commutateur à deux nœuds, vous pouvez migrer sans interruption vers un cluster commuté à deux nœuds comprenant des commutateurs réseau de cluster Cisco Nexus 3232C.' 
---
= Migrez d'un cluster sans commutateur à deux nœuds vers un cluster avec des commutateurs de cluster Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous disposez d'un cluster sans commutateur à deux nœuds, vous pouvez migrer vers un cluster avec commutateur à deux nœuds qui comprend des commutateurs de réseau de cluster Cisco Nexus 3232C. Cette procédure s'effectue sans interruption.



[[review-requirements]]
== Exigences de révision

.Avant de commencer
Vérifiez les installations et connexions suivantes :

* Des ports sont disponibles pour les connexions des nœuds. Les commutateurs du cluster utilisent les ports de liaison inter-commutateurs (ISL) e1/31-32.
* Vous disposez des câbles appropriés pour les connexions du cluster :
+
** Les nœuds dotés de connexions de cluster 10 GbE nécessitent des modules optiques QSFP avec des câbles de dérivation en fibre optique ou des câbles de dérivation en cuivre QSFP vers SFP+.
** Les nœuds dotés de connexions de cluster 40/100 GbE nécessitent des modules optiques QSFP/QSFP28 pris en charge avec des câbles à fibre optique ou des câbles à connexion directe en cuivre QSFP/QSFP28.
** Les commutateurs de cluster nécessitent le câblage ISL approprié : 2 câbles QSFP28 à fibre optique ou en cuivre à connexion directe.


* Les configurations sont correctement mises en place et fonctionnent.
+
Les deux nœuds doivent être connectés et fonctionner dans une configuration de cluster sans commutateur à deux nœuds.

* Tous les ports du cluster sont en état de fonctionnement.
* Les commutateurs de cluster Cisco Nexus 3232C sont pris en charge.
* La configuration réseau du cluster existant est la suivante :
+
** Une infrastructure de cluster Nexus 3232C redondante et pleinement fonctionnelle sur les deux commutateurs
** Les dernières versions de RCF et NX-OS sur vos commutateurs
** Connectivité de gestion sur les deux commutateurs
** Accès console aux deux commutateurs
** Toutes les interfaces logiques du cluster (LIF) à l'état *actif* sans avoir été migré
** Personnalisation initiale du commutateur
** Tous les ports ISL sont activés et câblés




.À propos des exemples
Les exemples de cette procédure utilisent la nomenclature suivante pour les commutateurs et les nœuds :

* Commutateurs de cluster Nexus 3232C, C1 et C2.
* Les nœuds sont n1 et n2.


Les exemples de cette procédure utilisent deux nœuds, chacun utilisant deux ports d'interconnexion de cluster 40 GbE, e4a et e4e. Le link:https://hwu.netapp.com/["Hardware Universe"^] contient des détails sur les ports de cluster de vos plateformes.

* n1_clus1 est la première interface logique de cluster (LIF) à être connectée au commutateur de cluster C1 pour le nœud n1.
* n1_clus2 est le premier LIF de cluster à être connecté au commutateur de cluster C2 pour le nœud n1.
* n2_clus1 est le premier LIF de cluster à être connecté au commutateur de cluster C1 pour le nœud n2.
* n2_clus2 est le deuxième LIF de cluster à être connecté au commutateur de cluster C2 pour le nœud n2.
* Le nombre de ports 10 GbE et 40/100 GbE est défini dans les fichiers de configuration de référence (RCF) disponibles à link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Téléchargement du fichier de configuration de référence du commutateur réseau en cluster Cisco®"^].


[NOTE]
====
La procédure nécessite l'utilisation à la fois des commandes ONTAP et des commandes des commutateurs Cisco Nexus 3000 Series Switches ; les commandes ONTAP sont utilisées sauf indication contraire.

====


[[step-1-display-and-migrate-physical-and-logical-ports]]
== Étape 1 : Affichez et migrez les ports physiques et logiques

. Si AutoSupport est activé sur ce cluster, supprimez la création automatique de cas en envoyant un message AutoSupport :
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ représente la durée de la fenêtre de maintenance en heures.

+
[NOTE]
====
Le message AutoSupport notifie le support technique de cette tâche de maintenance afin que la création automatique de tickets soit désactivée pendant la période de maintenance.

====
. Déterminez l'état administratif ou opérationnel de chaque interface de cluster :
+
.. Afficher les attributs du port réseau :
+
`network port show -role cluster`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -
4 entries were displayed.
----
====
.. Afficher les informations relatives aux interfaces logiques et à leurs nœuds d'origine désignés :
+
`network interface show -role cluster`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ---
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true

4 entries were displayed.
----
====
.. Vérifiez que la détection de cluster sans commutateur est activée à l'aide de la commande de privilège avancé :
+
`network options detect-switchless-cluster show``

+
.Afficher un exemple
[%collapsible]
====
La sortie dans l'exemple suivant montre que la détection de clusters sans commutateur est activée :

[listing, subs="+quotes"]
----
cluster::*> *network options detect-switchless-cluster show*
Enable Switchless Cluster Detection: true
----
====


. Vérifiez que les RCF appropriés et l'image appropriée sont installés sur les nouveaux commutateurs 3232C et effectuez les personnalisations de site nécessaires, telles que l'ajout d'utilisateurs, de mots de passe et d'adresses réseau.
+
Vous devez préparer les deux commutateurs dès maintenant. Si vous devez mettre à niveau le logiciel RCF et le logiciel image, vous devez suivre ces étapes :

+
.. Accédez à la page _Cisco Ethernet Switches_ sur le site de support NetApp.
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Commutateurs Ethernet Cisco"^]

.. Notez votre commutateur et les versions logicielles requises dans le tableau de cette page.
.. Téléchargez la version appropriée de RCF.
.. Cliquez sur *CONTINUER* sur la page *Description*, acceptez le contrat de licence, puis suivez les instructions sur la page *Download* pour télécharger le RCF.
.. Téléchargez la version appropriée du logiciel image.
+
link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Téléchargement du fichier de configuration de référence pour les commutateurs réseau de cluster et de gestion Cisco"^].



. Cliquez sur *CONTINUER* sur la page *Description*, acceptez le contrat de licence, puis suivez les instructions sur la page *Download* pour télécharger le RCF.
. Sur les commutateurs Nexus 3232C C1 et C2, désactivez tous les ports orientés vers le nœud C1 et C2, mais ne désactivez pas les ports ISL e1/31-32.
+
Pour plus d'informations sur les commandes Cisco, reportez-vous aux guides répertoriés dans le link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Series Références des commandes NX-OS"^].

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre la désactivation des ports 1 à 30 sur les commutateurs d'interconnexion de cluster Nexus 3232C C1 et C2 à l'aide d'une configuration prise en charge dans RCF `NX3232_RCF_v1.0_24p10g_24p100g.txt` :

[listing, subs="+quotes"]
----
C1# copy running-config startup-config
[########################################] 100% Copy complete.
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# shutdown
C1(config-if-range)# exit
C1(config)# exit
C2# copy running-config startup-config
[########################################] 100% Copy complete.
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# exit
----
====
. Connectez les ports 1/31 et 1/32 sur C1 aux mêmes ports sur C2 en utilisant un câblage pris en charge.
. Vérifiez que les ports ISL sont opérationnels sur C1 et C2 :
+
`show port-channel summary`

+
Pour plus d'informations sur les commandes Cisco, reportez-vous aux guides répertoriés dans le link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Series Références des commandes NX-OS"^].

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre la commande Cisco `show port-channel summary` utilisée pour vérifier que les ports ISL sont opérationnels sur C1 et C2 :

[listing, subs="+quotes"]
----
C1# *show port-channel summary*
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)        s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
      Port-
Group Channel      Type   Protocol  Member Ports
-------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)

C2# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)        s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------

Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. Afficher la liste des appareils voisins sur le commutateur.
+
Pour plus d'informations sur les commandes Cisco, reportez-vous aux guides répertoriés dans le link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Series Références des commandes NX-OS"^].

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre la commande Cisco `show cdp neighbors` utilisée pour afficher les périphériques voisins sur le commutateur :

[listing, subs="+quotes"]
----
C1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,                   s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C2                 Eth1/31        174    R S I s     N3K-C3232C  Eth1/31
C2                 Eth1/32        174    R S I s     N3K-C3232C  Eth1/32
Total entries displayed: 2
C2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,                   s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C1                 Eth1/31        178    R S I s     N3K-C3232C  Eth1/31
C1                 Eth1/32        178    R S I s     N3K-C3232C  Eth1/32
Total entries displayed: 2
----
====
. Afficher la connectivité des ports du cluster sur chaque nœud :
+
`network device-discovery show`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant illustre la connectivité des ports de cluster affichée pour une configuration de cluster sans commutateur à deux nœuds :

[listing, subs="+quotes"]
----
cluster::*> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    n2                  e4a              FAS9000
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    n1                  e4a              FAS9000
            e4e    n1                  e4e              FAS9000
----
====
. Migrez les LIF n1_clus1 et n2_clus1 vers les ports physiques de leurs nœuds de destination :
+
`network interface migrate -vserver _vserver-name_ -lif _lif-name_ source-node _source-node-name_ -destination-port _destination-port-name_`

+
.Afficher un exemple
[%collapsible]
====
Vous devez exécuter la commande pour chaque nœud local comme indiqué dans l'exemple suivant :

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver cluster -lif n1_clus1 -source-node n1
-destination-node n1 -destination-port e4e*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus1 -source-node n2
-destination-node n2 -destination-port e4e*
----
====




[[step-2-shut-down-the-reassigned-lifs-and-disconnect-the-cables]]
== Étape 2 : Mettez hors tension les LIF réaffectées et déconnectez les câbles

. Vérifiez que les interfaces du cluster ont bien été migrées :
+
`network interface show -role cluster`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre que le statut « Is Home » pour les LIF n1_clus1 et n2_clus1 est devenu « false » après la fin de la migration :

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4e     false
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4e     false
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
 4 entries were displayed.
----
====
. Fermez les ports de cluster pour les LIF n1_clus1 et n2_clus1, qui ont été migrés à l'étape 9 :
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.Afficher un exemple
[%collapsible]
====
Vous devez exécuter la commande pour chaque port comme indiqué dans l'exemple suivant :

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4a -up-admin false*
cluster::*> *network port modify -node n2 -port e4a -up-admin false*
----
====
. Vérifiez la connectivité des interfaces du cluster distant :


[role="tabbed-block"]
====
.ONTAP 9.9.1 et versions ultérieures
--
Vous pouvez utiliser le `network interface check cluster-connectivity` commande permettant de lancer une vérification d'accessibilité pour la connectivité du cluster, puis d'afficher les détails :

`network interface check cluster-connectivity start`et `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*REMARQUE :* Attendez quelques secondes avant d’exécuter le programme. `show` commande pour afficher les détails.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.Toutes les versions ONTAP
--
Pour toutes les versions ONTAP , vous pouvez également utiliser `cluster ping-cluster -node <name>` commande pour vérifier la connectivité :

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1        e4a    10.10.0.1
Cluster n1_clus2 n1        e4e    10.10.0.2
Cluster n2_clus1 n2        e4a    10.10.0.3
Cluster n2_clus2 n2        e4e    10.10.0.4
Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293 Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s) RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
--
====
. [[étape 4]] Déconnectez le câble de e4a sur le nœud n1.
+
Vous pouvez vous référer à la configuration en cours d’exécution et connecter le premier port 40 GbE sur le commutateur C1 (port 1/7 dans cet exemple) à e4a sur n1 en utilisant un câblage pris en charge pour les commutateurs Nexus 3232C.





[[step-3-enable-the-cluster-ports]]
== Étape 3 : Activer les ports du cluster

. Débranchez le câble de e4a sur le nœud n2.
+
Vous pouvez vous référer à la configuration en cours et connecter e4a au prochain port 40 GbE disponible sur C1, port 1/8, en utilisant un câblage compatible.

. Activez tous les ports orientés vers le nœud sur C1.
+
Pour plus d'informations sur les commandes Cisco, reportez-vous aux guides répertoriés dans le link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Series Références des commandes NX-OS"^].

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre l'activation des ports 1 à 30 sur les commutateurs d'interconnexion de cluster Nexus 3232C C1 et C2 à l'aide de la configuration prise en charge dans RCF `NX3232_RCF_v1.0_24p10g_26p100g.txt` :

[listing, subs="+quotes"]
----
C1# *configure*
C1(config)# *int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30*
C1(config-if-range)# *no shutdown*
C1(config-if-range)# *exit*
C1(config)# *exit*
----
====
. Activez le premier port de cluster, e4a, sur chaque nœud :
+
`network port modify -node _node-name_ -port _port-name_ -up-admin true`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4a -up-admin true*
cluster::*> *network port modify -node n2 -port e4a -up-admin true*
----
====
. Vérifiez que les clusters sont opérationnels sur les deux nœuds :
+
`network port show -role cluster`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -

4 entries were displayed.
----
====
. Pour chaque nœud, rétablissez toutes les LIFs d'interconnexion de cluster migrées :
+
`network interface revert -vserver cluster -lif _lif-name_`

+
.Afficher un exemple
[%collapsible]
====
Vous devez rétablir chaque LIF sur son port d'attache individuellement, comme indiqué dans l'exemple suivant :

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver cluster -lif n1_clus1*
cluster::*> *network interface revert -vserver cluster -lif n2_clus1*
----
====
. Vérifiez que toutes les interfaces réseau locales (LIF) sont désormais rétablies sur leurs ports d'attache :
+
`network interface show -role cluster`

+
La  `Is Home`colonne doit afficher une valeur de `true` pour tous les ports listés dans la colonne  `Current Port`. Si la valeur affichée est  `false`, le port n’a pas été rétabli.

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====




[[step-4-enable-the-reassigned-lifs]]
== Étape 4 : Activer les LIF réaffectées

. Afficher la connectivité des ports du cluster sur chaque nœud :
+
`network device-discovery show`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    C1                  Ethernet1/7      N3K-C3232C
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    C1                  Ethernet1/8      N3K-C3232C
            e4e    n1                  e4e              FAS9000
----
====
. Migrez clus2 vers le port e4a sur la console de chaque nœud :
+
`network interface migrate cluster -lif _lif-name_ -source-node _source-node-name_ -destination-node _destination-node-name_ -destination-port _destination-port-name_`

+
.Afficher un exemple
[%collapsible]
====
Vous devez migrer chaque LIF vers son port d'attache individuellement, comme indiqué dans l'exemple suivant :

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver cluster -lif n1_clus2 -source-node n1
-destination-node n1 -destination-port e4a*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus2 -source-node n2
-destination-node n2 -destination-port e4a*
----
====
. Arrêtez les ports d’interconnexion de cluster clus2 LIF sur les deux nœuds :
+
`network port modify`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre que les ports spécifiés sont définis sur  `false`, ce qui désactive les ports sur les deux nœuds :

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4e -up-admin false*
cluster::*> *network port modify -node n2 -port e4e -up-admin false*
----
====
. Vérifiez l'état du cluster LIF :
+
`network interface show`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4a     false
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4a     false
4 entries were displayed.
----
====
. Débranchez le câble de e4e sur le nœud n1.
+
Vous pouvez vous référer à la configuration en cours et connecter le premier port 40 GbE du commutateur C2 (port 1/7 dans cet exemple) à e4e sur le nœud n1, en utilisant le câblage approprié pour le modèle de commutateur Nexus 3232C.

. Débranchez le câble de e4e sur le nœud n2.
+
Vous pouvez vous référer à la configuration en cours et connecter e4e au prochain port 40 GbE disponible sur C2, port 1/8, en utilisant le câblage approprié pour le modèle de commutateur Nexus 3232C.

. Activez tous les ports orientés vers les nœuds sur C2.
+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre l'activation des ports 1 à 30 sur les commutateurs d'interconnexion de cluster Nexus 3132Q-V C1 et C2 à l'aide d'une configuration prise en charge dans RCF `NX3232C_RCF_v1.0_24p10g_26p100g.txt` :

[listing, subs="+quotes"]
----
C2# *configure*
C2(config)# *int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30*
C2(config-if-range)# *no shutdown*
C2(config-if-range)# *exit*
C2(config)# *exit*
----
====
. Activez le deuxième port de cluster, e4e, sur chaque nœud :
+
`network port modify`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre comment le deuxième port de cluster e4e est activé sur chaque nœud :

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4e -up-admin true*
cluster::*> *network port modify -node n2 -port e4e -up-admin true*s
----
====
. Pour chaque nœud, rétablissez toutes les LIFs d'interconnexion de cluster migrées : `network interface revert`
+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre les LIF migrées qui sont rétablies sur leurs ports d'origine.

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver Cluster -lif n1_clus2*
cluster::*> *network interface revert -vserver Cluster -lif n2_clus2*
----
====
. Vérifiez que tous les ports d'interconnexion de cluster sont désormais revenus à leurs ports d'origine :
+
`network interface show -role cluster`

+
La  `Is Home`colonne doit afficher une valeur de `true` pour tous les ports listés dans la colonne  `Current Port`. Si la valeur affichée est  `false`, le port n’a pas été rétabli.

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. Vérifiez que tous les ports d'interconnexion de cluster sont dans l' `up`état :
+
`network port show -role cluster`

. Afficher les numéros de port du commutateur de cluster par lesquels chaque port de cluster est connecté à chaque nœud : `network device-discovery show`
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1          /cdp
            e4a    C1                  Ethernet1/7      N3K-C3232C
            e4e    C2                  Ethernet1/7      N3K-C3232C
n2          /cdp
            e4a    C1                  Ethernet1/8      N3K-C3232C
            e4e    C2                  Ethernet1/8      N3K-C3232C
----
====
. Afficher les commutateurs de cluster découverts et surveillés :
+
`system cluster-switch show`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *system cluster-switch show*

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                          cluster-network    10.10.1.101      NX3232CV
Serial Number: FOX000001
Is Monitored: true
Reason:
Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
Version Source: CDP

C2                          cluster-network     10.10.1.102      NX3232CV
Serial Number: FOX000002
Is Monitored: true
Reason:
Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
Version Source: CDP 2 entries were displayed.
----
====
. Vérifiez que la détection de cluster sans commutateur a changé l’option de cluster sans commutateur en désactivé :
+
`network options switchless-cluster show`

. Vérifiez la connectivité des interfaces du cluster distant :


[role="tabbed-block"]
====
.ONTAP 9.9.1 et versions ultérieures
--
Vous pouvez utiliser le `network interface check cluster-connectivity` commande permettant de lancer une vérification d'accessibilité pour la connectivité du cluster, puis d'afficher les détails :

`network interface check cluster-connectivity start`et `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*REMARQUE :* Attendez quelques secondes avant d’exécuter le programme. `show` commande pour afficher les détails.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.Toutes les versions ONTAP
--
Pour toutes les versions ONTAP , vous pouvez également utiliser `cluster ping-cluster -node <name>` commande pour vérifier la connectivité :

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1        e4a    10.10.0.1
Cluster n1_clus2 n1        e4e    10.10.0.2
Cluster n2_clus1 n2        e4a    10.10.0.3
Cluster n2_clus2 n2        e4e    10.10.0.4
Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s) RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
--
====
. [[étape 16]] Si vous avez désactivé la création automatique de dossiers, réactivez-la en envoyant un AutoSupport message :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.Quelle est la prochaine étape ?
link:../switch-cshm/config-overview.html["Configurer la surveillance de l'état du commutateur"].
