---
permalink: switch-cisco-3232c/migrate-from-switchless-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: Avant de configurer les commutateurs Cisco Nexus 3232c, consultez un aperçu du processus et de la nomenclature. 
---
= Exigences de migration
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Si vous disposez d'un cluster sans commutateur à deux nœuds, vous pouvez migrer vers un cluster commuté à deux nœuds comprenant des commutateurs réseau de cluster Cisco Nexus 3232C. Il s’agit d’une procédure non perturbatrice.

.Avant de commencer
Vérifiez les installations et connexions suivantes :

* Des ports sont disponibles pour les connexions des nœuds.  Les commutateurs du cluster utilisent les ports de liaison inter-commutateurs (ISL) e1/31-32.
* Vous disposez des câbles appropriés pour les connexions du cluster :
+
** Les nœuds dotés de connexions de cluster 10 GbE nécessitent des modules optiques QSFP avec des câbles de dérivation en fibre optique ou des câbles de dérivation en cuivre QSFP vers SFP+.
** Les nœuds dotés de connexions de cluster 40/100 GbE nécessitent des modules optiques QSFP/QSFP28 compatibles avec des câbles à fibre optique ou des câbles à connexion directe en cuivre QSFP/QSFP28.
** Les commutateurs de cluster nécessitent le câblage ISL approprié :
+
*** 2 câbles à connexion directe en fibre optique ou en cuivre QSFP28.




* Les configurations sont correctement mises en place et fonctionnent correctement.
+
Les deux nœuds doivent être connectés et fonctionner dans une configuration de cluster sans commutateur à deux nœuds.

* Tous les ports du cluster sont en état de fonctionnement.
* Les commutateurs de cluster Cisco Nexus 3232C sont pris en charge.
* La configuration réseau du cluster existant est la suivante :
+
** Une infrastructure de cluster Nexus 3232C redondante et pleinement fonctionnelle sur les deux commutateurs
** Les dernières versions de RCF et NX-OS sur vos commutateurs
** La connectivité de gestion sur les deux commutateurs
** Accès console aux deux commutateurs
** Toutes les interfaces logiques du cluster (LIF) à l'état *actif* sans avoir été migrées
** Personnalisation initiale de l'interrupteur
** Tous les ports ISL sont activés et câblés.




.À propos des exemples utilisés
Les exemples de cette procédure utilisent la nomenclature suivante pour les commutateurs et les nœuds :

* Commutateurs de cluster Nexus 3232C, *C1* et *C2*.
* Les nœuds sont *n1* et *n2*.


Les exemples de cette procédure utilisent deux nœuds, chacun utilisant deux ports d'interconnexion de cluster 40 GbE *e4a* et *e4e*.  Lelink:https://hwu.netapp.com/["_Hardware Universe_"^] contient des informations sur les ports de cluster sur vos plateformes.

* *n1_clus1* est la première interface logique de cluster (LIF) à être connectée au commutateur de cluster *C1* pour le nœud *n1*.
* *n1_clus2* est la première interface LIF du cluster à être connectée au commutateur de cluster *C2* pour le nœud *n1*.
* *n2_clus1* est la première interface LIF du cluster à être connectée au commutateur de cluster *C1* pour le nœud *n2*.
* *n2_clus2* est la deuxième interface LIF du cluster à connecter au commutateur de cluster *C2* pour le nœud *n2*.
* Le nombre de ports 10 GbE et 40/100 GbE est défini dans les fichiers de configuration de référence (RCF) disponibles sur le https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Téléchargement du fichier de configuration de référence du commutateur réseau en cluster Cisco"^] page.


[NOTE]
====
La procédure nécessite l'utilisation à la fois des commandes ONTAP et des commandes des commutateurs Cisco Nexus série 3000 ; les commandes ONTAP sont utilisées sauf indication contraire.

====
.Quelle est la prochaine étape ?
link:migrate-from-switchless-prepare-to-migrate.html["Préparez-vous à la migration"].
