---
permalink: switch-cisco-3232c/migrate-from-switchless-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: Avant de configurer des commutateurs Cisco Nexus 3232c, consultez un aperçu du processus et de la nomenclature. 
---
= Conditions requises pour la migration
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Si vous disposez d'un cluster sans switch à 2 nœuds, vous pouvez migrer vers un cluster avec switch à 2 nœuds qui inclut des switchs réseau de cluster Cisco Nexus 3232C. Cette procédure ne fonctionne pas sans interruption.

.Avant de commencer
Vérifiez les installations et les connexions suivantes :

* Les ports sont disponibles pour les connexions de nœuds. Les commutateurs de cluster utilisent les ports ISL (Inter-Switch Link) e1/31-32.
* Vous disposez de câbles appropriés pour les connexions du cluster :
+
** Les nœuds équipés de connexions de cluster 10 GbE requièrent des modules optiques QSFP avec des câbles à fibre optique dérivation ou des câbles QSFP avec des câbles de dérivation en cuivre SFP+.
** Les nœuds équipés de connexions de cluster 40/100 GbE requièrent des modules optiques QSFP/QSFP28 pris en charge avec des câbles à fibre optique ou des câbles à connexion directe en cuivre QSFP/QSFP28.
** Les commutateurs de cluster nécessitent le câblage ISL approprié :
+
*** 2 câbles QSFP28 à connexion directe en cuivre ou fibre.




* Les configurations sont correctement configurées et opérationnelles.
+
Les deux nœuds doivent être connectés et fonctionner dans un cluster à 2 nœuds sans commutateur.

* Tous les ports de cluster sont à l'état *up*.
* Le switch de cluster Cisco Nexus 3232C est pris en charge.
* La configuration réseau en cluster existante comporte les éléments suivants :
+
** Infrastructure de cluster Nexus 3232C redondante et entièrement fonctionnelle sur les deux switchs
** Les dernières versions de RCF et de NX-OS sur vos commutateurs
** Connectivité de gestion sur les deux commutateurs
** Accès à la console aux deux commutateurs
** Toutes les interfaces logiques (LIF) de cluster sont à l'état *up* sans avoir été migrées
** Personnalisation initiale du commutateur
** Tous les ports ISL sont activés et câblés




.A propos des exemples utilisés
Les exemples de cette procédure utilisent la nomenclature des commutateurs et des nœuds suivante :

* Switchs de cluster Nexus 3232C, *C1* et *C2*.
* Les noeuds sont *n1* et *n2*.


Les exemples de cette procédure utilisent deux nœuds, chacun utilisant deux ports d'interconnexion de cluster 40 GbE *e4a* et *e4e*. link:https://hwu.netapp.com/["_Hardware Universe_"^]La contient des informations sur les ports de cluster sur vos plateformes.

* *N1_clus1* est la première interface logique de cluster (LIF) à être connectée au commutateur de cluster *C1* pour le nœud *n1*.
* *N1_clus2* est la première LIF de cluster à être connectée au commutateur de cluster *C2* pour le nœud *n1*.
* *N2_clus1* est la première LIF de cluster à être connectée au commutateur de cluster *C1* pour le nœud *n2*.
* *N2_clus2* est la deuxième LIF de cluster à connecter au commutateur de cluster *C2* pour le nœud *n2*.
* Le nombre de ports 10 GbE et 40/100 GbE est défini dans les fichiers de configuration de référence disponibles sur le https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Téléchargement du fichier de configuration de référence du commutateur réseau en cluster Cisco®"^] page.


[NOTE]
====
La procédure nécessite l'utilisation des commandes ONTAP et des commutateurs Cisco Nexus 3000 ; les commandes ONTAP sont utilisées sauf indication contraire.

====
.Et la suite ?
link:migrate-from-switchless-prepare-to-migrate.html["La préparation à la migration"].
