---
permalink: switch-cisco-3232c/migrate-requirements-3232c.html 
sidebar: sidebar 
keywords: migrate, cn1610 switch, cisco nexus 3232c cluster 
summary: Vous devez prendre en compte certaines informations de configuration, les connexions de ports et les exigences de câblage lorsque vous remplacez des commutateurs de cluster CN1610 par des commutateurs de cluster Cisco Nexus 3232C. 
---
= Exigences de migration pour les commutateurs de cluster Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de migrer vers les commutateurs de cluster Cisco Nexus 3232C, examinez les informations de configuration, les connexions de ports et les exigences de câblage.



[[cn1610-migrate-requirements]]
== Exigences de migration CN1610

Les commutateurs du cluster prennent en charge les connexions de nœuds suivantes :

* NetApp CN1610 : ports 0/1 à 0/12 (10 GbE)
* Cisco Nexus 3232C : ports e1/1-30 (40 ou 100 ou 4x10GbE)


Les commutateurs du cluster utilisent les ports de liaison inter-commutateurs (ISL) suivants.

* NetApp CN1610 : ports 0/13 à 0/16 (10 GbE)
* Cisco Nexus 3232C : ports 1/31-32 (100GbE)


[NOTE]
====
Vous devez utiliser des câbles de dérivation 4x10G sur le commutateur de cluster Cisco Nexus 3232C.

====
Le tableau suivant présente les connexions de câblage nécessaires à chaque étape de la transition des commutateurs NetApp CN1610 vers les commutateurs de cluster Cisco Nexus 3232C :

|===
| Étape | Description | Câbles nécessaires 


 a| 
Initial
 a| 
CN1610 à CN1610 (SFP+ à SFP+)
 a| 
4 câbles SFP+ à connexion directe en fibre optique ou en cuivre



 a| 
Transition
 a| 
CN1610 à 3232C (QSFP à SFP+)
 a| 
1 câble de dérivation QSFP et 4 câbles de dérivation SFP+ à fibre optique ou en cuivre



 a| 
Final
 a| 
3232C à 3232C (QSFP à QSFP)
 a| 
2 câbles à fibre optique ou à connexion directe en cuivre QSFP

|===
Vous devez avoir téléchargé les fichiers de configuration de référence (RCF) applicables. Le nombre de ports 10 GbE et 40/100 GbE est défini dans les RCF disponibles sur le link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Téléchargement du fichier de configuration de référence du commutateur réseau en cluster Cisco®"^].

Les versions ONTAP et NX-OS prises en charge dans cette procédure sont répertoriées à link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Commutateurs Ethernet Cisco"^].

Les versions ONTAP et FASTPATH prises en charge dans cette procédure sont répertoriées à link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 et CN1610 Commutateurs"^].



[[cn5596-requirements]]
== Exigences CN5596

Les commutateurs du cluster utilisent les ports suivants pour les connexions aux nœuds :

* Ports e1/1-40 (10 GbE) : Nexus 5596
* Ports e1/1-30 (10/40/100 GbE) : Nexus 3232C
+
** Les commutateurs du cluster utilisent les ports de liaison inter-commutateurs (ISL) suivants :


* Ports e1/41-48 (10 GbE) : Nexus 5596
* Ports e1/31-32 (40/100 GbE) : Nexus 3232C
+
** Le link:https://hwu.netapp.com/["Hardware Universe"^] contient des informations sur le câblage pris en charge pour les commutateurs Nexus 3232C :


* Les nœuds dotés de connexions de cluster 10 GbE nécessitent des câbles de dérivation à fibre optique QSFP vers SFP+ ou des câbles de dérivation en cuivre QSFP vers SFP+.
* Les nœuds avec des connexions de cluster 40/100 GbE nécessitent des modules optiques QSFP/QSFP28 pris en charge avec des câbles à fibre optique ou des câbles à connexion directe en cuivre QSFP/QSFP28.
+
** Les commutateurs du cluster utilisent le câblage ISL approprié :


* Début : Nexus 5596 (SFP+ vers SFP+)
+
** 8 câbles SFP+ à connexion directe en fibre ou en cuivre


* Interim : Nexus 5596 vers Nexus 3232C (QSFP vers 4xSFP+ break-out)
+
** 1x câble de dérivation fibre optique ou cuivre QSFP vers SFP+


* Final : Nexus 3232C vers Nexus 3232C (QSFP28 vers QSFP28)
+
** 2 câbles à connexion directe QSFP28 en fibre optique ou en cuivre
+
*** Sur les commutateurs Nexus 3232C, vous pouvez faire fonctionner les ports QSFP/QSFP28 en modes Ethernet 40/100 Gigabit ou 4 x10 Gigabit Ethernet.
+
Par défaut, il y a 32 ports en mode Ethernet 40/100 Gigabit. Ces ports Ethernet 40 Gigabit sont numérotés selon une convention de nommage à 2 éléments. Par exemple, le deuxième port Ethernet 40 Gigabit est numéroté 1/2. Le processus de modification de la configuration d’Ethernet 40 Gigabit à Ethernet 10 Gigabit est appelé _breakout_ et le processus de modification de la configuration d’Ethernet 10 Gigabit à Ethernet 40 Gigabit est appelé _breakin_. Lorsque vous divisez un port Ethernet 40/100 Gigabit en ports Ethernet 10 Gigabit, les ports résultants sont numérotés selon une convention de nommage à 3 éléments. Par exemple, les ports issus de la division du deuxième port Ethernet 40/100 Gigabit sont numérotés 1/2/1, 1/2/2, 1/2/3 et 1/2/4.

*** Sur le côté gauche des commutateurs Nexus 3232C se trouvent 2 ports SFP+, appelés 1/33 et 1/34.
*** Vous avez configuré certains ports des commutateurs Nexus 3232C pour fonctionner à 10 GbE ou 40/100 GbE.
+
[NOTE]
====
Vous pouvez configurer les six premiers ports en mode 4x10 GbE à l'aide de la  `interface breakout module 1 port 1-6 map 10g-4x` commande. De même, vous pouvez regrouper les six premiers ports QSFP+ de la configuration de répartition à l'aide de la  `no interface breakout module 1 port 1-6 map 10g-4x` commande.

====
*** Vous avez effectué la planification, la migration et lu la documentation requise sur la connectivité 10 GbE et 40/100 GbE des nœuds aux commutateurs de cluster Nexus 3232C.
*** Les versions ONTAP et NX-OS prises en charge dans cette procédure se trouvent à link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Commutateurs Ethernet Cisco"^].





