---
permalink: switch-cisco-3232c/required-documentation-3232c.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: 'Consultez la documentation nécessaire à l"installation et à la maintenance des commutateurs de cluster Cisco Nexus 3232C.' 
---
= Examinez les exigences de documentation pour les commutateurs de cluster Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Consultez la documentation relative aux commutateurs et aux contrôleurs requise pour configurer les commutateurs de cluster Cisco Nexus 3232C et les intégrer dans un cluster ONTAP.



[[switch-documentation]]
== Documentation Switch

Pour configurer les commutateurs Cisco Nexus 3232C, vous aurez besoin de la documentation suivante de link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html["Prise en charge des commutateurs Cisco Nexus 3000 Series"^].

[cols="1,2"]
|===
| Titre du document | Description 


 a| 
_Guide d'installation matérielle de la série Nexus 3000_
 a| 
Fournit des informations détaillées sur les exigences du site, les caractéristiques du matériel de commutation et les options d'installation.



 a| 
_Guides de configuration logicielle des commutateurs Cisco Nexus 3000 Series Switch_ (choisissez le guide correspondant à la version de NX-OS installée sur vos commutateurs)
 a| 
Fournit les informations de configuration initiale du commutateur dont vous avez besoin avant de pouvoir configurer le commutateur pour un fonctionnement ONTAP .



 a| 
_Guide de mise à niveau et de rétrogradation du logiciel NX-OS pour la série Cisco Nexus 3000_ (choisissez le guide correspondant à la version de NX-OS installée sur vos commutateurs)
 a| 
Fournit des informations sur la manière de rétrograder le commutateur vers un logiciel de commutateur compatible ONTAP , si nécessaire.



 a| 
_Index principal du guide de référence des commandes Cisco Nexus 3000 Series NX-OS_
 a| 
Fournit des liens vers les différentes références de commandes fournies par Cisco.



 a| 
_Référence des MIB Cisco Nexus 3000_
 a| 
Décrit les fichiers Management Information Base (MIB) pour les commutateurs Nexus 3000.



 a| 
_Référence des messages système NX-OS Nexus 3000 Series_
 a| 
Décrit les messages système pour les commutateurs Cisco Nexus 3000 series, ceux qui sont informatifs et d'autres qui peuvent aider à diagnostiquer les problèmes liés aux liaisons, au matériel interne ou au logiciel système.



 a| 
_Notes de version Cisco Nexus 3000 Series NX-OS (choisissez les notes correspondant à la version de NX-OS installée sur vos commutateurs)_
 a| 
Décrit les fonctionnalités, les bugs et les limitations de la série Cisco Nexus 3000.



 a| 
Informations réglementaires, de conformité et de sécurité pour les Cisco Nexus 6000, Cisco Nexus 5000 Series, Cisco Nexus 3000 Series et Cisco Nexus 2000 Series
 a| 
Fournit des informations sur la conformité aux normes internationales, la sécurité et les réglementations relatives aux commutateurs de la série Nexus 3000.

|===


[[ontap-systems-documentation]]
== Documentation des systèmes ONTAP

Pour configurer un système ONTAP, vous avez besoin des documents suivants pour votre version du système d'exploitation.

[cols="1,2"]
|===
| Nom | Description 


 a| 
Instructions d'installation et de configuration spécifiques à la manette
 a| 
Ce document décrit la procédure d'installation du matériel NetApp .



 a| 
link:https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9"^]
 a| 
Fournit des informations détaillées sur tous les aspects des versions ONTAP .



 a| 
link:https://hwu.netapp.com["Hardware Universe"^]
 a| 
Fournit des informations sur la configuration et la compatibilité du matériel NetApp .

|===


[[rail-kit-and-cabinet-documentation]]
== documentation du kit de rails et de l'armoire

Pour installer un commutateur Cisco 3232C dans une armoire NetApp, reportez-vous à la documentation matérielle suivante.

[cols="1,2"]
|===
| Nom | Description 


 a| 
link:https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["Armoire système 42U, guide profond"^]
 a| 
Décrit les FRU associées à l'armoire système 42U et fournit des instructions de maintenance et de remplacement des FRU.



 a| 
link:install-cisco-nexus-3232c.html["Installez un commutateur Cisco Nexus 3232C dans une armoire NetApp"^]
 a| 
Décrit comment installer un commutateur Cisco Nexus 3232C dans une armoire NetApp à quatre montants.

|===