---
permalink: switch-cisco-3232c/setup_worksheet_3232c.html 
sidebar: sidebar 
keywords: cable worksheet, Cisco NX 3232C 
summary: 'Si vous souhaitez documenter les plates-formes prises en charge, vous devez remplir la fiche de câblage vierge en utilisant l"exemple de fiche de câblage rempli comme guide. Chaque switch peut être configuré en tant que seul port 100 GbE, 40 GbE ou 4 ports 10 GbE.' 
---
= Fiche de câblage Cisco Nexus 3232C complète
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour documenter les plates-formes prises en charge, téléchargez le PDF de cette page et remplissez la fiche de câblage.

L'exemple de fiche technique de câblage fournit des exemples d'attributions de ports recommandées entre les commutateurs et les contrôleurs. La fiche blanche fournit un modèle que vous pouvez utiliser pour configurer votre cluster.

Chaque switch peut être configuré en tant que seul port 100 GbE, 40 GbE ou 4 ports 10 GbE.



== Exemple de fiche de câblage

L'exemple de définition de port sur chaque paire de commutateurs est le suivant :

[cols="1, 1, 1, 1"]
|===
2+| Commutateur de cluster A 2+| Commutateur de cluster B 


| Port du commutateur | Utilisation du nœud et du port | Port du commutateur | Utilisation du nœud et du port 


 a| 
1
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE
 a| 
1
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE



 a| 
2
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE
 a| 
2
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE



 a| 
3
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE
 a| 
3
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE



 a| 
4
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE
 a| 
4
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE



 a| 
5
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE
 a| 
5
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE



 a| 
6
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE
 a| 
6
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE



 a| 
7
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE
 a| 
7
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE



 a| 
8
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE
 a| 
8
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE



 a| 
9
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE
 a| 
9
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE



 a| 
10
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE
 a| 
10
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE



 a| 
11
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE
 a| 
11
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE



 a| 
12
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE
 a| 
12
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE



 a| 
13
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE
 a| 
13
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE



 a| 
14
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE
 a| 
14
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE



 a| 
15
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE
 a| 
15
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE



 a| 
16
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE
 a| 
16
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE



 a| 
17
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE
 a| 
17
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE



 a| 
18
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE
 a| 
18
 a| 
4 nœuds 10 GbE/40 x 25 GbE ou 100 GbE



 a| 
19
 a| 
Nœud 40 Gbit/s/100 GbE 19
 a| 
19
 a| 
Nœud 40 Gbit/s/100 GbE 19



 a| 
20
 a| 
Nœud 40 Gbit/s/100 GbE 20
 a| 
20
 a| 
Nœud 40 Gbit/s/100 GbE 20



 a| 
21
 a| 
Nœud 40 Gbit/s/100 GbE 21
 a| 
21
 a| 
Nœud 40 Gbit/s/100 GbE 21



 a| 
22
 a| 
Nœud 40 Gbit/s/100 GbE 22
 a| 
22
 a| 
Nœud 40 Gbit/s/100 GbE 22



 a| 
23
 a| 
Nœud 40 Gbit/s/100 GbE 23
 a| 
23
 a| 
Nœud 40 Gbit/s/100 GbE 23



 a| 
24
 a| 
Nœud 40 Gbit/s/100 GbE 24
 a| 
24
 a| 
Nœud 40 Gbit/s/100 GbE 24



 a| 
25 à 30
 a| 
Réservé
 a| 
25 à 30
 a| 
Réservé



 a| 
31
 a| 
ISL 100 GbE vers le port 31 du commutateur B
 a| 
31
 a| 
ISL 100 GbE vers le port 31 du commutateur A



 a| 
32
 a| 
ISL 100 GbE vers le port 32 du commutateur B
 a| 
32
 a| 
ISL 100 GbE vers le port 32 du commutateur A

|===


== Feuille de câblage vierge

Vous pouvez utiliser la fiche de câblage vide pour documenter les plateformes prises en charge en tant que nœuds dans un cluster. La section _connexions de cluster prises en charge_ du https://hwu.netapp.com["Hardware Universe"^] définit les ports de cluster utilisés par la plateforme.

[cols="1, 1, 1, 1"]
|===
2+| Commutateur de cluster A 2+| Commutateur de cluster B 


| Port du commutateur | Utilisation du nœud/port | Port du commutateur | Utilisation du nœud/port 


 a| 
1
 a| 
 a| 
1
 a| 



 a| 
2
 a| 
 a| 
2
 a| 



 a| 
3
 a| 
 a| 
3
 a| 



 a| 
4
 a| 
 a| 
4
 a| 



 a| 
5
 a| 
 a| 
5
 a| 



 a| 
6
 a| 
 a| 
6
 a| 



 a| 
7
 a| 
 a| 
7
 a| 



 a| 
8
 a| 
 a| 
8
 a| 



 a| 
9
 a| 
 a| 
9
 a| 



 a| 
10
 a| 
 a| 
10
 a| 



 a| 
11
 a| 
 a| 
11
 a| 



 a| 
12
 a| 
 a| 
12
 a| 



 a| 
13
 a| 
 a| 
13
 a| 



 a| 
14
 a| 
 a| 
14
 a| 



 a| 
15
 a| 
 a| 
15
 a| 



 a| 
16
 a| 
 a| 
16
 a| 



 a| 
17
 a| 
 a| 
17
 a| 



 a| 
18
 a| 
 a| 
18
 a| 



 a| 
19
 a| 
 a| 
19
 a| 



 a| 
20
 a| 
 a| 
20
 a| 



 a| 
21
 a| 
 a| 
21
 a| 



 a| 
22
 a| 
 a| 
22
 a| 



 a| 
23
 a| 
 a| 
23
 a| 



 a| 
24
 a| 
 a| 
24
 a| 



 a| 
25 à 30
 a| 
Réservé
 a| 
25 à 30
 a| 
Réservé



 a| 
31
 a| 
ISL 100 GbE vers le port 31 du commutateur B
 a| 
31
 a| 
ISL 100 GbE vers le port 31 du commutateur A



 a| 
32
 a| 
ISL 100 GbE vers le port 32 du commutateur B
 a| 
32
 a| 
ISL 100 GbE vers le port 32 du commutateur A

|===