---
permalink: switch-cisco-3232c/setup_worksheet_3232c.html 
sidebar: sidebar 
keywords: cable worksheet, Cisco NX 3232C 
summary: 'Si vous souhaitez documenter les plates-formes prises en charge, vous devez remplir la fiche de câblage vierge en utilisant l"exemple de fiche de câblage rempli comme guide. Chaque switch peut être configuré en tant que seul port 100 GbE, 40 GbE ou 4 ports 10 GbE.' 
---
= Fiche de câblage Cisco Nexus 3232C complète
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour documenter les plates-formes prises en charge, téléchargez le PDF de cette page et remplissez la fiche de câblage.

L'exemple de fiche technique de câblage fournit des exemples d'attributions de ports recommandées entre les commutateurs et les contrôleurs. La fiche blanche fournit un modèle que vous pouvez utiliser pour configurer votre cluster.

Chaque switch peut être configuré en tant que seul port 100 GbE, 40 GbE ou 4 ports 10 GbE.



== Exemple de fiche de câblage

L'exemple de définition de port sur chaque paire de commutateurs est le suivant :

[cols="1, 1, 1, 1"]
|===
2+| Commutateur de cluster A 2+| Commutateur de cluster B 


| Port du commutateur | Utilisation du nœud et du port | Port du commutateur | Utilisation du nœud et du port 


 a| 
1
 a| 
Nœud 4 x 10 G/40 G/100 G
 a| 
1
 a| 
Nœud 4 x 10 G/40 G/100 G



 a| 
2
 a| 
Nœud 4 x 10 G/40 G/100 G
 a| 
2
 a| 
Nœud 4 x 10 G/40 G/100 G



 a| 
3
 a| 
Nœud 4 x 10 G/40 G/100 G
 a| 
3
 a| 
Nœud 4 x 10 G/40 G/100 G



 a| 
4
 a| 
Nœud 4 x 10 G/40 G/100 G
 a| 
4
 a| 
Nœud 4 x 10 G/40 G/100 G



 a| 
5
 a| 
Nœud 4 x 10 G/40 G/100 G
 a| 
5
 a| 
Nœud 4 x 10 G/40 G/100 G



 a| 
6
 a| 
4 x 10 G/40 G/100 Gnode
 a| 
6
 a| 
4 x 10 G/40 G/100 Gnode



 a| 
7
 a| 
Nœud 4 x 10 G/40 G/100 G
 a| 
7
 a| 
Nœud 4 x 10 G/40 G/100 G



 a| 
8
 a| 
Nœud 4 x 10 G/40 G/100 G
 a| 
8
 a| 
Nœud 4 x 10 G/40 G/100 G



 a| 
9
 a| 
Nœud 4 x 10 G/40 G/100 G
 a| 
9
 a| 
Nœud 4 x 10 G/40 G/100 G



 a| 
10
 a| 
Nœud 4 x 10 G/40 G/100 G
 a| 
10
 a| 
Nœud 4 x 10 G/40 G/100 G



 a| 
11
 a| 
Nœud 4 x 10 G/40 G/100 G
 a| 
11
 a| 
Nœud 4 x 10 G/40 G/100 G



 a| 
12
 a| 
Nœud 4 x 10 G/40 G/100 G
 a| 
12
 a| 
Nœud 4 x 10 G/40 G/100 G



 a| 
13
 a| 
Nœud 4 x 10 G/40 G/100 G
 a| 
13
 a| 
Nœud 4 x 10 G/40 G/100 G



 a| 
14
 a| 
Nœud 4 x 10 G/40 G/100 G
 a| 
14
 a| 
Nœud 4 x 10 G/40 G/100 G



 a| 
15
 a| 
Nœud 4 x 10 G/40 G/100 G
 a| 
15
 a| 
Nœud 4 x 10 G/40 G/100 G



 a| 
16
 a| 
Nœud 4 x 10 G/40 G/100 G
 a| 
16
 a| 
Nœud 4 x 10 G/40 G/100 G



 a| 
17
 a| 
Nœud 4 x 10 G/40 G/100 G
 a| 
17
 a| 
Nœud 4 x 10 G/40 G/100 G



 a| 
18
 a| 
Nœud 4 x 10 G/40 G/100 G
 a| 
18
 a| 
Nœud 4 x 10 G/40 G/100 G



 a| 
19
 a| 
40G/100G nœud 19
 a| 
19
 a| 
40G/100G nœud 19



 a| 
20
 a| 
40G/100G nœud 20
 a| 
20
 a| 
40G/100G nœud 20



 a| 
21
 a| 
40G/100G nœud 21
 a| 
21
 a| 
40G/100G nœud 21



 a| 
22
 a| 
40G/100G nœud 22
 a| 
22
 a| 
40G/100G nœud 22



 a| 
23
 a| 
40G/100G nœud 23
 a| 
23
 a| 
40G/100G nœud 23



 a| 
24
 a| 
40G/100G nœud 24
 a| 
24
 a| 
40G/100G nœud 24



 a| 
25 à 30
 a| 
Réservé
 a| 
25 à 30
 a| 
Réservé



 a| 
31
 a| 
100G ISL vers le port 31 du commutateur B.
 a| 
31
 a| 
100G ISL pour commuter Un port 31



 a| 
32
 a| 
100G ISL vers le port 32 du commutateur B.
 a| 
32
 a| 
100G ISL pour commuter Un port 32

|===


== Feuille de câblage vierge

Vous pouvez utiliser la fiche de câblage vide pour documenter les plateformes prises en charge en tant que nœuds dans un cluster. La section _connexions de cluster prises en charge_ du https://["Hardware Universe"^] définit les ports de cluster utilisés par la plateforme.

[cols="1, 1, 1, 1"]
|===
2+| Commutateur de cluster A 2+| Commutateur de cluster B 


| Port du commutateur | Utilisation du nœud/port | Port du commutateur | Utilisation du nœud/port 


 a| 
1
 a| 
 a| 
1
 a| 



 a| 
2
 a| 
 a| 
2
 a| 



 a| 
3
 a| 
 a| 
3
 a| 



 a| 
4
 a| 
 a| 
4
 a| 



 a| 
5
 a| 
 a| 
5
 a| 



 a| 
6
 a| 
 a| 
6
 a| 



 a| 
7
 a| 
 a| 
7
 a| 



 a| 
8
 a| 
 a| 
8
 a| 



 a| 
9
 a| 
 a| 
9
 a| 



 a| 
10
 a| 
 a| 
10
 a| 



 a| 
11
 a| 
 a| 
11
 a| 



 a| 
12
 a| 
 a| 
12
 a| 



 a| 
13
 a| 
 a| 
13
 a| 



 a| 
14
 a| 
 a| 
14
 a| 



 a| 
15
 a| 
 a| 
15
 a| 



 a| 
16
 a| 
 a| 
16
 a| 



 a| 
17
 a| 
 a| 
17
 a| 



 a| 
18
 a| 
 a| 
18
 a| 



 a| 
19
 a| 
 a| 
19
 a| 



 a| 
20
 a| 
 a| 
20
 a| 



 a| 
21
 a| 
 a| 
21
 a| 



 a| 
22
 a| 
 a| 
22
 a| 



 a| 
23
 a| 
 a| 
23
 a| 



 a| 
24
 a| 
 a| 
24
 a| 



 a| 
25 à 30
 a| 
Réservé
 a| 
25 à 30
 a| 
Réservé



 a| 
31
 a| 
100G ISL vers le port 31 du commutateur B.
 a| 
31
 a| 
100G ISL pour commuter Un port 31



 a| 
32
 a| 
100G ISL vers le port 32 du commutateur B.
 a| 
32
 a| 
100G ISL pour commuter Un port 32

|===