---
permalink: switch-cisco-3232c/setup_worksheet_3232c.html 
sidebar: sidebar 
keywords: cable worksheet, Cisco NX 3232C 
summary: Remplissez la fiche de câblage pour les commutateurs de cluster Cisco Nexus 3232C afin de documenter les connexions de ports et les configurations de plateforme prises en charge. 
---
= Complétez la fiche de câblage Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Remplissez la fiche de câblage pour les commutateurs de cluster Cisco Nexus 3232C afin de documenter les connexions de ports et les configurations de plateforme prises en charge.

La fiche de câblage type fournit des exemples d'affectations de ports recommandées entre les commutateurs et les contrôleurs.  La feuille de calcul vierge fournit un modèle que vous pouvez utiliser pour configurer votre cluster.

Chaque commutateur peut être configuré comme un seul port 100GbE, un port 40GbE ou 4 ports 10GbE.



[[sample-cabling-worksheet]]
== Exemple de feuille de câblage

La définition des ports d'exemple sur chaque paire de commutateurs est la suivante :

[cols="1, 1, 1, 1"]
|===
2+| Commutateur de cluster A 2+| Commutateur de cluster B 


| Port de commutation | Utilisation des nœuds et des ports | Port de commutation | Utilisation des nœuds et des ports 


 a| 
1
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE
 a| 
1
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE



 a| 
2
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE
 a| 
2
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE



 a| 
3
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE
 a| 
3
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE



 a| 
4
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE
 a| 
4
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE



 a| 
5
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE
 a| 
5
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE



 a| 
6
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE
 a| 
6
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE



 a| 
7
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE
 a| 
7
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE



 a| 
8
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE
 a| 
8
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE



 a| 
9
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE
 a| 
9
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE



 a| 
10
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE
 a| 
10
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE



 a| 
11
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE
 a| 
11
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE



 a| 
12
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE
 a| 
12
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE



 a| 
13
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE
 a| 
13
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE



 a| 
14
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE
 a| 
14
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE



 a| 
15
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE
 a| 
15
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE



 a| 
16
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE
 a| 
16
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE



 a| 
17
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE
 a| 
17
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE



 a| 
18
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE
 a| 
18
 a| 
4x10GbE/4x25GbE ou nœud 40/100GbE



 a| 
19
 a| 
Nœud 40G/100GbE 19
 a| 
19
 a| 
Nœud 40G/100GbE 19



 a| 
20
 a| 
Nœud 20 40G/100GbE
 a| 
20
 a| 
Nœud 20 40G/100GbE



 a| 
21
 a| 
Nœud 21 40G/100GbE
 a| 
21
 a| 
Nœud 21 40G/100GbE



 a| 
22
 a| 
Nœud 22 40G/100GbE
 a| 
22
 a| 
Nœud 22 40G/100GbE



 a| 
23
 a| 
Nœud 23 40G/100GbE
 a| 
23
 a| 
Nœud 23 40G/100GbE



 a| 
24
 a| 
Nœud 24 40G/100GbE
 a| 
24
 a| 
Nœud 24 40G/100GbE



 a| 
25 à 30
 a| 
Réservé
 a| 
25 à 30
 a| 
Réservé



 a| 
31
 a| 
Liaison ISL 100GbE vers le port 31 du commutateur B
 a| 
31
 a| 
Liaison ISL 100GbE vers le port 31 du commutateur A



 a| 
32
 a| 
Liaison ISL 100GbE vers le port 32 du commutateur B
 a| 
32
 a| 
Liaison ISL 100GbE vers le port 32 du commutateur A

|===


[[blank-cabling-worksheet]]
== Feuille de câblage vierge

Vous pouvez utiliser la feuille de câblage vierge pour documenter les plateformes prises en charge en tant que nœuds dans un cluster.  La section _Connexions de cluster prises en charge_ de https://hwu.netapp.com["Hardware Universe"^] définit les ports du cluster utilisés par la plateforme.

[cols="1, 1, 1, 1"]
|===
2+| Commutateur de cluster A 2+| Commutateur de cluster B 


| Port de commutation | Utilisation des nœuds/ports | Port de commutation | Utilisation des nœuds/ports 


 a| 
1
 a| 
 a| 
1
 a| 



 a| 
2
 a| 
 a| 
2
 a| 



 a| 
3
 a| 
 a| 
3
 a| 



 a| 
4
 a| 
 a| 
4
 a| 



 a| 
5
 a| 
 a| 
5
 a| 



 a| 
6
 a| 
 a| 
6
 a| 



 a| 
7
 a| 
 a| 
7
 a| 



 a| 
8
 a| 
 a| 
8
 a| 



 a| 
9
 a| 
 a| 
9
 a| 



 a| 
10
 a| 
 a| 
10
 a| 



 a| 
11
 a| 
 a| 
11
 a| 



 a| 
12
 a| 
 a| 
12
 a| 



 a| 
13
 a| 
 a| 
13
 a| 



 a| 
14
 a| 
 a| 
14
 a| 



 a| 
15
 a| 
 a| 
15
 a| 



 a| 
16
 a| 
 a| 
16
 a| 



 a| 
17
 a| 
 a| 
17
 a| 



 a| 
18
 a| 
 a| 
18
 a| 



 a| 
19
 a| 
 a| 
19
 a| 



 a| 
20
 a| 
 a| 
20
 a| 



 a| 
21
 a| 
 a| 
21
 a| 



 a| 
22
 a| 
 a| 
22
 a| 



 a| 
23
 a| 
 a| 
23
 a| 



 a| 
24
 a| 
 a| 
24
 a| 



 a| 
25 à 30
 a| 
Réservé
 a| 
25 à 30
 a| 
Réservé



 a| 
31
 a| 
Liaison ISL 100GbE vers le port 31 du commutateur B
 a| 
31
 a| 
Liaison ISL 100GbE vers le port 31 du commutateur A



 a| 
32
 a| 
Liaison ISL 100GbE vers le port 32 du commutateur B
 a| 
32
 a| 
Liaison ISL 100GbE vers le port 32 du commutateur A

|===
.Quelle est la prochaine étape
Une fois vos feuilles de travail sur le câblage terminées, vous pouvez link:install-switch-3232c.html["installer le commutateur"].
