---
permalink: switch-cisco-3232c/task-steps-to-replace-a-cisco-nexus-3232c-storage-switch.html 
sidebar: sidebar 
keywords: replace, cisco nexus, 3232c storage switch 
summary: Vous pouvez remplacer un switch de stockage Cisco Nexus 3232C défectueux et non disruptive en exécutant une séquence de tâches spécifique. 
---
= Étapes de remplacement d'un switch de stockage Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez remplacer un switch de stockage Cisco Nexus 3232C défectueux et non disruptive en exécutant une séquence de tâches spécifique.

La configuration réseau existante doit présenter les caractéristiques suivantes :

* La page des commutateurs Ethernet Cisco présente les dernières versions de RCF et NX-OS sur vos commutateurs.
* La connectivité de gestion doit exister sur les deux commutateurs.
+
[NOTE]
====
Assurez-vous que toutes les étapes de dépannage ont été effectuées pour vérifier que votre commutateur doit être remplacé.

====


Les caractéristiques du switch Cisco Nexus 3232C de remplacement doivent être les suivantes :

* La connectivité du réseau de gestion doit fonctionner.
* L'accès à la console au commutateur de remplacement doit être en place.
* Vous devez charger l'image appropriée du système d'exploitation RCF et NX-OS sur le commutateur.
* La personnalisation initiale du commutateur doit être terminée.


*Résumé de la procédure :*

* *Confirmer que le commutateur à remplacer est S2 (étapes ,1-,5)*
* *Débrancher les câbles du commutateur S2 ,(Étape 6)*
* *Rebrancher les câbles sur le commutateur NS2 (étape ,7)*
* *Vérifiez toutes les configurations de périphériques sur le commutateur NS2 (étapes ,8-,10)*
* Cette procédure remplace le second switch de stockage Nexus 3232C S2 par le nouveau switch 3232C NS2.
* Les deux nœuds sont le nœud1 et le nœud2.


.Étapes
. [[one]]si AutoSupport est activé sur ce cluster, supprimez la création automatique de dossiers en invoquant un message AutoSupport :
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_ représente la durée de la fenêtre de maintenance en heures.

+
[NOTE]
====
Le message AutoSupport informe le support technique de cette tâche de maintenance de sorte que la création automatique de dossier soit supprimée lors de la fenêtre de maintenance.

====
. Vérifier l'état de santé des ports du nœud de stockage pour s'assurer qu'il existe une connexion au commutateur de stockage S1 :
`storage port show -port-type ENET`
+
[listing]
----
storage::*> storage port show -port-type ENET
                                      Speed                     VLAN
Node               Port Type  Mode    (Gb/s) State    Status      ID
------------------ ---- ----- ------- ------ -------- --------- ----
node1
                   e3a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
node2
                   e3a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
----
. Vérifiez que le commutateur de stockage S1 est disponible :
`network device-discovery show`
+
[listing]
----
storage::*> network device-discovery show
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- ----------------
node1/cdp
            e3a    S1                        Ethernet1/1       NX3232C
            e4a    node2                     e4a               AFF-A700
            e4e    node2                     e4e               AFF-A700
node1/lldp
            e3a    S1                        Ethernet1/1       -
            e4a    node2                     e4a               -
            e4e    node2                     e4e               -
node2/cdp
            e3a    S1                        Ethernet1/2       NX3232C
            e4a    node1                     e4a               AFF-A700
            e4e    node1                     e4e               AFF-A700
node2/lldp
            e3a    S1                        Ethernet1/2       -
            e4a    node1                     e4a               -
            e4e    node1                     e4e               -
----
. Exécutez le
`show lldp neighbors` commande sur le commutateur de travail pour confirmer que vous pouvez voir les deux nœuds et tous les tiroirs :
`show lldp neighbors`
+
[listing]
----
S1# show lldp neighbors
Capability codes:
  (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
  (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID               Local Intf      Hold-time  Capability  Port ID
node1                   Eth1/1          121        S           e3a
node2                   Eth1/2          121        S           e3a
SHFGD2008000011         Eth1/5          121        S           e0a
SHFGD2008000011         Eth1/6          120        S           e0a
SHFGD2008000022         Eth1/7          120        S           e0a
SHFGD2008000022         Eth1/8          120        S           e0a
----
. [[5]]vérifier les ports du tiroir dans le système de stockage :
`storage shelf port show -fields remote-device,remote-port`
+
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port

shelf  id  remote-port  remote-device
-----  --  -----------  -------------
3.20   0   Ethernet1/5  S1
3.20   1   -            -
3.20   2   Ethernet1/6  S1
3.20   3   -            -
3.30   0   Ethernet1/7  S1
3.20   1   -            -
3.30   2   Ethernet1/8  S1
3.20   3   -            -
----
. [[six]]retirez tous les câbles reliés au commutateur de stockage S2.
. [[sept]]rebrancher tous les câbles sur le commutateur de remplacement NS2.
. [[huit]]vérifier à nouveau l'état de santé des ports du nœud de stockage :
`storage port show -port-type ENET`
+
[listing]
----
storage::*> storage port show -port-type ENET
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ------------ ---
node1
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
node2
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
----
. Vérifier que les deux commutateurs sont disponibles :
`network device-discovery show`
+
[listing]
----
storage::*> network device-discovery show
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  --------
node1/cdp
            e3a    S1                        Ethernet1/1       NX3232C
            e4a    node2                     e4a               AFF-A700
            e4e    node2                     e4e               AFF-A700
            e7b    NS2                       Ethernet1/1       NX3232C
node1/lldp
            e3a    S1                        Ethernet1/1       -
            e4a    node2                     e4a               -
            e4e    node2                     e4e               -
            e7b    NS2                       Ethernet1/1       -
node2/cdp
            e3a    S1                        Ethernet1/2       NX3232C
            e4a    node1                     e4a               AFF-A700
            e4e    node1                     e4e               AFF-A700
            e7b    NS2                       Ethernet1/2       NX3232C
node2/lldp
            e3a    S1                        Ethernet1/2       -
            e4a    node1                     e4a               -
            e4e    node1                     e4e               -
            e7b    NS2                       Ethernet1/2       -
----
. [[10]]vérifier les ports du tiroir dans le système de stockage :
`storage shelf port show -fields remote-device,remote-port`
+
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf id remote-port remote-device
----- -- ----------- -------------
3.20  0  Ethernet1/5 S1
3.20  1  Ethernet1/5 NS2
3.20  2  Ethernet1/6 S1
3.20  3  Ethernet1/6 NS2
3.30  0  Ethernet1/7 S1
3.20  1  Ethernet1/7 NS2
3.30  2  Ethernet1/8 S1
3.20  3  Ethernet1/8 NS2
----
. Si vous avez supprimé la création automatique de cas, réactivez-la en appelant un message AutoSupport :
`system node autosupport invoke -node * -type all -message MAINT=END`

