---
permalink: switch-cisco-3232c/upgrade-rcf-software-3232c.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 3232c 
summary: 'SSH est une exigence lors de l"utilisation des fonctionnalitﾃｩs de Cluster Switch Health Monitor (CSHM) et de collecte de journaux. Pour activer SSH sur les commutateurs de cluster Cisco 3232c, vous gﾃｩnﾃｩrez d窶兮bord les clﾃｩs SSH, puis vous activez SSH.' 
---
= Mettez ﾃ jour votre fichier de configuration de rﾃｩfﾃｩrence (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous mettez ﾃ jour votre version RCF lorsque vous disposez d'une version existante du fichier RCF installﾃｩe sur vos commutateurs opﾃｩrationnels.

.Avant de commencer
Assurez-vous d'avoir les ﾃｩlﾃｩments suivantsﾂ:

* Une sauvegarde actuelle de la configuration du commutateur.
* Un cluster parfaitement fonctionnel (aucune erreur dans les journaux ni problﾃｨme similaire).
* Le RCF actuel.
* Si vous mettez ﾃ jour votre version RCF, vous avez besoin d'une configuration de dﾃｩmarrage dans RCF qui reflﾃｨte les images de dﾃｩmarrage souhaitﾃｩes.
+
Si vous devez modifier la configuration de dﾃｩmarrage pour qu'elle reflﾃｨte les images de dﾃｩmarrage actuelles, vous devez le faire avant de rﾃｩappliquer le RCF afin que la version correcte soit instanciﾃｩe lors des prochains redﾃｩmarrages.




NOTE: Aucune liaison inter-commutateurs opﾃｩrationnelle (ISL) n'est nﾃｩcessaire pendant cette procﾃｩdure. Ceci est intentionnel car les changements de version RCF peuvent affecter temporairement la connectivitﾃｩ ISL. Pour garantir le fonctionnement non perturbateur du cluster, la procﾃｩdure suivante migre toutes les LIF du cluster vers le commutateur partenaire opﾃｩrationnel tout en exﾃｩcutant les ﾃｩtapes sur le commutateur cible.


CAUTION: Avant d'installer une nouvelle version du logiciel du commutateur et des RCF, vous devez effacer les paramﾃｨtres du commutateur et effectuer une configuration de base.  Vous devez ﾃｪtre connectﾃｩ au commutateur via la console sﾃｩrie ou avoir conservﾃｩ les informations de configuration de base avant d'effacer les paramﾃｨtres du commutateur.



== ﾃ液ape 1ﾂ: Prﾃｩparer la mise ﾃ niveau

. Afficher les ports du cluster sur chaque nﾅ砥d qui sont connectﾃｩs aux commutateurs du clusterﾂ:
+
`network device-discovery show`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  --------
cluster1-01/cdp
            e0a    cs1                       Ethernet1/7       N3K-C3232C
            e0d    cs2                       Ethernet1/7       N3K-C3232C
cluster1-02/cdp
            e0a    cs1                       Ethernet1/8       N3K-C3232C
            e0d    cs2                       Ethernet1/8       N3K-C3232C
cluster1-03/cdp
            e0a    cs1                       Ethernet1/1/1     N3K-C3232C
            e0b    cs2                       Ethernet1/1/1     N3K-C3232C
cluster1-04/cdp
            e0a    cs1                       Ethernet1/1/2     N3K-C3232C
            e0b    cs2                       Ethernet1/1/2     N3K-C3232C
cluster1::*>
----
====
. Vﾃｩrifiez l'ﾃｩtat administratif et opﾃｩrationnel de chaque port du cluster.
+
.. Vﾃｩrifiez que tous les ports du cluster sont opﾃｩrationnels et en bon ﾃｩtatﾂ:
+
`network port show 窶途ole cluster`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -role cluster*
Node: cluster1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0d       Cluster      Cluster          up   9000  auto/100000 healthy false
Node: cluster1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0d       Cluster      Cluster          up   9000  auto/100000 healthy false
8 entries were displayed.
Node: cluster1-03
   Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
Node: cluster1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
cluster1::*>
----
====
.. Vﾃｩrifiez que toutes les interfaces du cluster (LIF) sont connectﾃｩes au port d'accueilﾂ:
+
`network interface show -role cluster`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
            Logical            Status     Network           Current      Current Is
Vserver     Interface          Admin/Oper Address/Mask      Node         Port    Home
----------- ------------------ ---------- ----------------- ------------ ------- ----
Cluster
            cluster1-01_clus1  up/up     169.254.3.4/23     cluster1-01  e0a     true
            cluster1-01_clus2  up/up     169.254.3.5/23     cluster1-01  e0d     true
            cluster1-02_clus1  up/up     169.254.3.8/23     cluster1-02  e0a     true
            cluster1-02_clus2  up/up     169.254.3.9/23     cluster1-02  e0d     true
            cluster1-03_clus1  up/up     169.254.1.3/23     cluster1-03  e0a     true
            cluster1-03_clus2  up/up     169.254.1.1/23     cluster1-03  e0b     true
            cluster1-04_clus1  up/up     169.254.1.6/23     cluster1-04  e0a     true
            cluster1-04_clus2  up/up     169.254.1.7/23     cluster1-04  e0b     true
8 entries were displayed.
cluster1::*>
----
====
.. Vﾃｩrifiez que le cluster affiche les informations pour les deux commutateurs du clusterﾂ:
+
`system cluster-switch show -is-monitoring-enabled-operational true`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs1                         cluster-network    10.233.205.92    NX3232C
     Serial Number: FOXXXXXXXGS
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(4)
    Version Source: CDP
cs2                         cluster-network    10.233.205.93    NX3232C
     Serial Number: FOXXXXXXXGD
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(4)
    Version Source: CDP
2 entries were displayed.
----
====


. Dﾃｩsactiver la restauration automatique sur les LIF du cluster.
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----




== ﾃ液ape 2 : Configurer les ports

. Sur le commutateur de cluster cs2, dﾃｩsactivez les ports connectﾃｩs aux ports de cluster des nﾅ砥ds.
+
[listing, subs="+quotes"]
----
cs2> *enable*
cs2# *configure*
cs2(config)# *interface eth1/1/1-2,eth1/7-8*
cs2(config-if-range)# *shutdown*
cs2(config-if-range)# *exit*
cs2# *exit*
----
+

CAUTION: Veillez ﾃ dﾃｩsactiver *tous* les ports du cluster connectﾃｩs afin d'ﾃｩviter tout problﾃｨme de connexion rﾃｩseau. Consultez l'article de la Knowledge Base link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Node_out_of_quorum_when_migrating_cluster_lif_during_switch_OS_upgrade["Nﾅ砥d hors quorum lors de la migration de l'interface logique du cluster pendant la mise ﾃ niveau du systﾃｨme d'exploitation du commutateur"^] pour plus de dﾃｩtails.

. Vﾃｩrifiez que les ports du cluster ont basculﾃｩ vers les ports hﾃｩbergﾃｩs sur le commutateur de cluster cs1. Cela peut prendre quelques secondes.
+
`network interface show -role cluster`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
            Logical           Status     Network            Current       Current Is
Vserver     Interface         Admin/Oper Address/Mask       Node          Port    Home
----------- ----------------- ---------- ------------------ ------------- ------- ----
Cluster
            cluster1-01_clus1 up/up      169.254.3.4/23     cluster1-01   e0a     true
            cluster1-01_clus2 up/up      169.254.3.5/23     cluster1-01   e0a     false
            cluster1-02_clus1 up/up      169.254.3.8/23     cluster1-02   e0a     true
            cluster1-02_clus2 up/up      169.254.3.9/23     cluster1-02   e0a     false
            cluster1-03_clus1 up/up      169.254.1.3/23     cluster1-03   e0a     true
            cluster1-03_clus2 up/up      169.254.1.1/23     cluster1-03   e0a     false
            cluster1-04_clus1 up/up      169.254.1.6/23     cluster1-04   e0a     true
            cluster1-04_clus2 up/up      169.254.1.7/23     cluster1-04   e0a     false
8 entries were displayed.
cluster1::*>
----
====
. Vﾃｩrifiez que le cluster est sainﾂ:
+
`cluster show`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  -------
cluster1-01          true    true          false
cluster1-02          true    true          false
cluster1-03          true    true          true
cluster1-04          true    true          false
4 entries were displayed.
cluster1::*>
----
====
. Si vous ne l'avez pas dﾃｩjﾃ fait, enregistrez une copie de la configuration actuelle du commutateur en copiant le rﾃｩsultat de la commande suivante dans un fichier texteﾂ:
+
`show running-config`

. Enregistrez tout ajout personnalisﾃｩ entre les ﾃｩlﾃｩments actuels `running-config` et le fichier RCF utilisﾃｩ (tel qu'une configuration SNMP pour votre organisation).
. Enregistrez les dﾃｩtails de configuration de base dans le `write_erase.cfg` fichier sur la mﾃｩmoire flash de dﾃｩmarrage.
+
[NOTE]
====
Assurez-vous de configurer les ﾃｩlﾃｩments suivantsﾂ: * Nom d'utilisateur et mot de passe * Adresse IP de gestion * Passerelle par dﾃｩfaut * Nom du commutateur

====
+
`cs2# show run | section "switchname" > bootflash:write_erase.cfg`

+
`cs2# show run | section "hostname" >> bootflash:write_erase.cfg`

+
`cs2# show run | i "username admin password" >> bootflash:write_erase.cfg`

+
`cs2# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`cs2# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

. Lors de la mise ﾃ niveau vers la version 1.12 de RCF et les versions ultﾃｩrieures, exﾃｩcutez les commandes suivantesﾂ:
+
`cs2# echo "hardware access-list tcam region racl-lite 512" >> bootflash:write_erase.cfg`

+
`cs2# echo "hardware access-list tcam region qos 256" >> bootflash:write_erase.cfg`

. Vﾃｩrifiez que le `write_erase.cfg` Le fichier est rempli comme prﾃｩvuﾂ:
+
`*show file bootflash:write_erase.cfg*`

. ﾃ盈ettre le `write erase` commande pour effacer la configuration enregistrﾃｩe actuelleﾂ:
+
`cs2# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. Copiez la configuration de base prﾃｩcﾃｩdemment enregistrﾃｩe dans la configuration de dﾃｩmarrage.
+
`cs2# *copy bootflash:write_erase.cfg startup-config*`

. Redﾃｩmarrez le commutateur cs2ﾂ:
+
`cs2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Une fois l'adresse IP de gestion ﾃ nouveau accessible, connectez-vous au commutateur via SSH.
+
Vous devrez peut-ﾃｪtre mettre ﾃ jour les entrﾃｩes du fichier host relatives aux clﾃｩs SSH.

. Copiez le fichier RCF dans la mﾃｩmoire bootflash du commutateur cs2 en utilisant l'un des protocoles de transfert suivants : FTP, TFTP, SFTP ou SCP. Pour plus d'informations sur les commandes Cisco, reportez-vous au guide appropriﾃｩ dans le link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Guide de rﾃｩfﾃｩrence des commandes NX-OS Cisco Nexus sﾃｩrie 3000"^].
+
.Afficher un exemple
[%collapsible]
====
Cet exemple montre comment TFTP est utilisﾃｩ pour copier un RCF dans la mﾃｩmoire flash de dﾃｩmarrage du commutateur cs2ﾂ:

[listing, subs="+quotes"]
----
cs2# *copy tftp: bootflash: vrf management*
Enter source filename: *Nexus_3232C_RCF_v1.6-Cluster-HA-Breakout.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. Appliquez le RCF prﾃｩcﾃｩdemment tﾃｩlﾃｩchargﾃｩ ﾃ la mﾃｩmoire flash de dﾃｩmarrage.
+
Pour plus d'informations sur les commandes Cisco, reportez-vous au guide appropriﾃｩ dans le link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Guide de rﾃｩfﾃｩrence des commandes NX-OS Cisco Nexus sﾃｩrie 3000"^].

+
.Afficher un exemple
[%collapsible]
====
Cet exemple montre le fichier RCF `Nexus_3232C_RCF_v1.6-Cluster-HA-Breakout.txt` en cours d'installation sur le commutateur cs2ﾂ:

[listing, subs="+quotes"]
----
cs2# *copy Nexus_3232C_RCF_v1.6-Cluster-HA-Breakout.txt running-config echo-commands*
----
====
+
[CAUTION]
====
Assurez-vous de lire attentivement les sections *Notes d'installation*, *Notes importantes* et *banniﾃｨre* de votre RCF. Vous devez lire et suivre ces instructions pour garantir la configuration et le fonctionnement corrects du commutateur.

====
. Vﾃｩrifiez que le fichier RCF est bien la version la plus rﾃｩcente correcteﾂ:
+
`show running-config`

+
Lorsque vous vﾃｩrifiez le rﾃｩsultat pour vous assurer que vous avez le RCF correct, vﾃｩrifiez que les informations suivantes sont correctesﾂ:

+
** La banniﾃｨre RCF
** Paramﾃｨtres du nﾅ砥d et du port
** Personnalisations
+
Le rﾃｩsultat varie en fonction de la configuration de votre site.  Vﾃｩrifiez les paramﾃｨtres du port et consultez les notes de version pour connaﾃｮtre les modifications spﾃｩcifiques ﾃ la version de RCF que vous avez installﾃｩe.



. Rﾃｩappliquez les personnalisations prﾃｩcﾃｩdentes ﾃ la configuration du commutateur.  Se rﾃｩfﾃｩrer ﾃlink:cabling-considerations-3232c.html["Examiner les considﾃｩrations relatives au cﾃ｢blage et ﾃ la configuration"] pour plus de dﾃｩtails sur les modifications supplﾃｩmentaires nﾃｩcessaires.
. Aprﾃｨs avoir vﾃｩrifiﾃｩ que les versions RCF et les paramﾃｨtres du commutateur sont corrects, copiez le fichier running-config dans le fichier startup-config.
+
Pour plus d'informations sur les commandes Cisco, reportez-vous au guide appropriﾃｩ dans le link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Guide de rﾃｩfﾃｩrence des commandes NX-OS Cisco Nexus sﾃｩrie 3000"^].

+
[listing]
----
cs2# copy running-config startup-config [########################################] 100% Copy complete
----
. Redﾃｩmarrez le commutateur cs2.  Vous pouvez ignorer les ﾃｩvﾃｩnements ﾂｫ ports de cluster hors service ﾂｻ signalﾃｩs sur les nﾅ砥ds pendant le redﾃｩmarrage du commutateur.
+
[listing, subs="+quotes"]
----
cs2# *reload*
This command will reboot the system. (y/n)?  [n] *y*
----
. Vﾃｩrifiez l'ﾃｩtat des ports du cluster.
+
.. Vﾃｩrifiez que les ports e0d sont opﾃｩrationnels et fonctionnels sur tous les nﾅ砥ds du clusterﾂ:
+
`network port show -role cluster`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -role cluster*
Node: cluster1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
Node: cluster1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
Node: cluster1-03
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0d       Cluster      Cluster          up   9000  auto/100000 healthy false
Node: cluster1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0d       Cluster      Cluster          up   9000  auto/100000 healthy false
8 entries were displayed.
----
====
.. Vﾃｩrifiez l'ﾃｩtat du commutateur ﾃ partir du cluster (cela peut ne pas afficher le commutateur cs2, car les LIF ne sont pas hﾃｩbergﾃｩes sur e0d).
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-01/cdp
            e0a    cs1                       Ethernet1/7       N3K-C3232C
            e0d    cs2                       Ethernet1/7       N3K-C3232C
cluster01-2/cdp
            e0a    cs1                       Ethernet1/8       N3K-C3232C
            e0d    cs2                       Ethernet1/8       N3K-C3232C
cluster01-3/cdp
            e0a    cs1                       Ethernet1/1/1     N3K-C3232C
            e0b    cs2                       Ethernet1/1/1     N3K-C3232C
cluster1-04/cdp
            e0a    cs1                       Ethernet1/1/2     N3K-C3232C
            e0b    cs2                       Ethernet1/1/2     N3K-C3232C
cluster1::*> system cluster-switch show -is-monitoring-enabled-operational true
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- -----
cs1                         cluster-network    10.233.205.90    N3K-C3232C
     Serial Number: FOXXXXXXXGD
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(4)
    Version Source: CDP
cs2                         cluster-network    10.233.205.91    N3K-C3232C
     Serial Number: FOXXXXXXXGS
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(4)
    Version Source: CDP
2 entries were displayed.
----
====
+
[NOTE]
====
Vous pouvez observer la sortie suivante sur la console du commutateur cs1 en fonction de la version RCF prﾃｩcﾃｩdemment chargﾃｩe sur le commutateur 2020 Nov 17 16:07:18 cs1 %$ VDC-1 %$ %STP-2-UNBLOCK_CONSIST_PORTﾂ: Dﾃｩblocage du port port-channel1 sur VLAN0092. Cohﾃｩrence du port restaurﾃｩe. 17 nov. 2020 16:07:23 cs1 %$ VDC-1 %$ %STP-2-BLOCK_PVID_PEERﾂ: Blocage du port-channel1 sur VLAN0001. VLAN homologue incohﾃｩrent. 17 nov. 2020 16:07:23 cs1 %$ VDC-1 %$ %STP-2-BLOCK_PVID_LOCALﾂ: Blocage du port-channel1 sur VLAN0092. VLAN local incohﾃｩrent.

====


+

NOTE: Il peut falloir jusqu'ﾃ 5 minutes pour que les nﾅ砥ds du cluster soient signalﾃｩs comme ﾃｩtant en bonne santﾃｩ.

. Sur le commutateur de cluster cs1, dﾃｩsactivez les ports connectﾃｩs aux ports de cluster des nﾅ砥ds.
+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant utilise la sortie d'exemple d'interface de l'ﾃｩtape 1ﾂ:

[listing, subs="+quotes"]
----
cs1(config)# *interface eth1/1/1-2,eth1/7-8*
cs1(config-if-range)# *shutdown*
----
====
. Vﾃｩrifiez que les LIF du cluster ont migrﾃｩ vers les ports hﾃｩbergﾃｩs sur le commutateur cs2. Cela peut prendre quelques secondes.
+
`network interface show -role cluster`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
            Logical            Status     Network            Current             Current Is
Vserver     Interface          Admin/Oper Address/Mask       Node                Port    Home
----------- ------------------ ---------- ------------------ ------------------- ------- ----
Cluster
            cluster1-01_clus1  up/up      169.254.3.4/23     cluster1-01         e0d     false
            cluster1-01_clus2  up/up      169.254.3.5/23     cluster1-01         e0d     true
            cluster1-02_clus1  up/up      169.254.3.8/23     cluster1-02         e0d     false
            cluster1-02_clus2  up/up      169.254.3.9/23     cluster1-02         e0d     true
            cluster1-03_clus1  up/up      169.254.1.3/23     cluster1-03         e0b     false
            cluster1-03_clus2  up/up      169.254.1.1/23     cluster1-03         e0b     true
            cluster1-04_clus1  up/up      169.254.1.6/23     cluster1-04         e0b     false
            cluster1-04_clus2  up/up      169.254.1.7/23     cluster1-04         e0b     true
8 entries were displayed.
cluster1::*>
----
====
. Vﾃｩrifiez que le cluster est sainﾂ:
+
`cluster show`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health   Eligibility   Epsilon
-------------------- -------- ------------- -------
cluster1-01          true     true          false
cluster1-02          true     true          false
cluster1-03          true     true          true
cluster1-04          true     true          false
4 entries were displayed.
cluster1::*>
----
====
. Rﾃｩpﾃｩtez les ﾃｩtapes 4 ﾃ 19 sur le commutateur cs1.
. Activer la restauration automatique sur les LIF du cluster.
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert true*
----




== ﾃ液ape 3ﾂ: Vﾃｩrifier la configuration rﾃｩseau et l窶凖ｩtat du cluster

. Vﾃｩrifiez que les ports du commutateur connectﾃｩs aux ports du cluster sont *actifs*.
+
`show interface brief | grep up`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show interface brief | grep up*
.
.
Eth1/1/1      1       eth  access up      none                    10G(D) --
Eth1/1/2      1       eth  access up      none                    10G(D) --
Eth1/7        1       eth  trunk  up      none                   100G(D) --
Eth1/8        1       eth  trunk  up      none                   100G(D) --
.
.
----
====
. Vﾃｩrifiez que l'ISL entre cs1 et cs2 est fonctionnelﾂ:
+
`show port-channel summary`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/31(P)   Eth1/32(P)
cs1#
----
====
. Vﾃｩrifiez que les LIF du cluster sont revenues ﾃ leur port d'origineﾂ:
+
`network interface show -role cluster`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
            Logical            Status     Network            Current             Current Is
Vserver     Interface          Admin/Oper Address/Mask       Node                Port    Home
----------- ------------------ ---------- ------------------ ------------------- ------- ----
Cluster
            cluster1-01_clus1  up/up      169.254.3.4/23     cluster1-01         e0d     true
            cluster1-01_clus2  up/up      169.254.3.5/23     cluster1-01         e0d     true
            cluster1-02_clus1  up/up      169.254.3.8/23     cluster1-02         e0d     true
            cluster1-02_clus2  up/up      169.254.3.9/23     cluster1-02         e0d     true
            cluster1-03_clus1  up/up      169.254.1.3/23     cluster1-03         e0b     true
            cluster1-03_clus2  up/up      169.254.1.1/23     cluster1-03         e0b     true
            cluster1-04_clus1  up/up      169.254.1.6/23     cluster1-04         e0b     true
            cluster1-04_clus2  up/up      169.254.1.7/23     cluster1-04         e0b     true
8 entries were displayed.
cluster1::*>
----
====
+
Si des LIFS de cluster ne sont pas revenus ﾃ leurs ports d'origine, rﾃｩtablissez-les manuellementﾂ:
`network interface revert -vserver _vserver_name_ -lif _lif_name_`

. Vﾃｩrifiez que le cluster est sainﾂ:
+
`cluster show`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
cluster1-01          true    true          false
cluster1-02          true    true          false
cluster1-03          true    true          true
cluster1-04          true    true          false
4 entries were displayed.
cluster1::*>
----
====
. Vﾃｩrifiez la connectivitﾃｩ des interfaces du cluster distantﾂ:


[role="tabbed-block"]
====
.ONTAP 9.9.1 et versions ultﾃｩrieures
--
Vous pouvez utiliser le `network interface check cluster-connectivity` commande pour dﾃｩmarrer une vﾃｩrification d'accessibilitﾃｩ pour la connectivitﾃｩ du cluster, puis afficher les dﾃｩtailsﾂ:
`network interface check cluster-connectivity start` et `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*REMARQUEﾂ:* Attendez quelques secondes avant d窶册xﾃｩcuter le programme. `show` commande pour afficher les dﾃｩtails.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source              Destination         Packet
Node   Date                       LIF                 LIF                 Loss
------ -------------------------- ------------------- ------------------- -----------
cluster1-01
       3/5/2022 19:21:18 -06:00   cluster1-01_clus2   cluster1-02_clus1   none
       3/5/2022 19:21:20 -06:00   cluster1-01_clus2   cluster1-02_clus2   none
.
.
cluster1-02
       3/5/2022 19:21:18 -06:00   cluster1-02_clus2   cluster1-01_clus1   none
       3/5/2022 19:21:20 -06:00   cluster1-02_clus2   cluster1-01_clus2   none
.
.
cluster1-03
.
.
.
.
cluster1-04
.
.
.
.
----
--
.Toutes les versions ONTAP
--
Pour toutes les versions ONTAP , vous pouvez ﾃｩgalement utiliser le
`cluster ping-cluster -node <name>` commande pour vﾃｩrifier la connectivitﾃｩ :
`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is cluster1-03
Getting addresses from network interface table...
Cluster cluster1-03_clus1 169.254.1.3 cluster1-03 e0a
Cluster cluster1-03_clus2 169.254.1.1 cluster1-03 e0b
Cluster cluster1-04_clus1 169.254.1.6 cluster1-04 e0a
Cluster cluster1-04_clus2 169.254.1.7 cluster1-04 e0b
Cluster cluster1-01_clus1 169.254.3.4 cluster1-01 e0a
Cluster cluster1-01_clus2 169.254.3.5 cluster1-01 e0d
Cluster cluster1-02_clus1 169.254.3.8 cluster1-02 e0a
Cluster cluster1-02_clus2 169.254.3.9 cluster1-02 e0d
Local = 169.254.1.3 169.254.1.1
Remote = 169.254.1.6 169.254.1.7 169.254.3.4 169.254.3.5 169.254.3.8 169.254.3.9
Cluster Vserver Id = 4294967293
Ping status:
............
Basic connectivity succeeds on 12 path(s)
Basic connectivity fails on 0 path(s)
................................................
Detected 9000 byte MTU on 12 path(s):
    Local 169.254.1.3 to Remote 169.254.1.6
    Local 169.254.1.3 to Remote 169.254.1.7
    Local 169.254.1.3 to Remote 169.254.3.4
    Local 169.254.1.3 to Remote 169.254.3.5
    Local 169.254.1.3 to Remote 169.254.3.8
    Local 169.254.1.3 to Remote 169.254.3.9
    Local 169.254.1.1 to Remote 169.254.1.6
    Local 169.254.1.1 to Remote 169.254.1.7
    Local 169.254.1.1 to Remote 169.254.3.4
    Local 169.254.1.1 to Remote 169.254.3.5
    Local 169.254.1.1 to Remote 169.254.3.8
    Local 169.254.1.1 to Remote 169.254.3.9
Larger than PMTU communication succeeds on 12 path(s)
RPC status:
6 paths up, 0 paths down (tcp check)
6 paths up, 0 paths down (udp check)
----
--
====
.Quelle est la prochaine ﾃｩtape ?
Aprﾃｨs avoir mis ﾃ niveau votre RCF, vous pouvezlink:configure-ssh-keys.html["vﾃｩrifier la configuration SSH"] .
