---
settings:
  name: Install and maintain
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  pdf:
    zip-level: 1
    zip-filename: ontap-systems-switches-pdfs.zip
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentation Switch pour les systèmes de stockage ONTAP
    url: "/index.html"
  - title: Notes de version
    entries:
    - title: Nouveautés concernant les commutateurs
      url: "/whats-new.html"
    - title: Fin du support
      url: "/eoa-switches.html"
  - title: Commencer
    entries:
    - title: Découvrez les commutateurs des systèmes ONTAP
      url: "/get-started/learn-switch-concept.html"
    - title: Démarrage rapide
      url: "/get-started/get-up-and-running.html"
  - title: Commutateurs de systèmes AFX
    url: "/afx/index.html"
    entries:
    - section: switch-cisco-9808
    - section: switch-cisco-9332d-gx2b
    - section: switch-cisco-9364d-gx2a
  - title: Commutateurs de cluster
    url: "/cluster/index.html"
    entries:
    - section: switch-bes-53248
    - section: switch-cisco-9336c-fx2
  - title: Commutateurs de stockage
    url: "/storage/index.html"
    entries:
    - section: switch-cisco-9336c-fx2-storage
  - title: Commutateurs partagés
    url: "/shared/index.html"
    entries:
    - section: switch-cisco-9336c-fx2-shared
      pdf-filename: commutateur-cisco-9336c-fx2-stockage
  - title: Surveiller l'état du commutateur
    url: "/cshm/index.html"
    entries:
    - section: switch-cshm-configure
    - section: switch-cshm-monitor
    - section: switch-cshm-log-collection
  - title: Interrupteurs de fin de disponibilité
    url: "/eoa/index.html"
    entries:
    - section: switch-nvidia-sn2100
    - section: switch-nvidia-sn2100-storage
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: ONTAP hardware systems
  repo: ontap-systems-family
