---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, switches, fas, aff systems 
summary: Découvrez les nouveaux commutateurs pour les systèmes FAS et AFF . 
---
= Quoi de neuf pour les commutateurs
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveaux commutateurs pour les systèmes de stockage ONTAP. Pour plus d'informations sur les commutateurs, consultez link:https://hwu.netapp.com/Switch/Index["Hardware Universe"^].



[[july-2026]]
== Juillet 2026



[[new-cisco-nexus-9808-switch-for-afx-2k]]
=== Nouveau commutateur Cisco Nexus 9808 pour AFX 2K

Les nouveaux commutateurs Cisco 9808 se connectent aux nœuds du contrôleur AFX 2K avec les baies de stockage. Ce nouveau commutateur vous permet de créer des clusters ONTAP comportant plus de deux nœuds. Des protocoles avancés sont utilisés pour optimiser les performances. La conception repose sur le marquage VLAN avec plusieurs chemins réseau, ainsi que sur des configurations de renouvellement technologique, afin de garantir un fonctionnement continu et une mise à niveau aisée.

Ce sont des commutateurs Cisco 400GbE à 36 ports avec 1 module superviseur, 7 modules Fabric et 4 unités d'alimentation (PSU) (X-N9K-C9808-B1-A) prenant en charge ONTAP 9.19.1 et versions ultérieures.



[[2025-releases]]
== Versions 2025

.Octobre 2025
[%collapsible]
====
.Commutateurs Cisco Nexus 9332D-GX2B et 9364D-GX2A pour AFX 1K
Les commutateurs Cisco 9364D-GX2A et Cisco 9332D-GX2B permettent de créer des clusters ONTAP comportant plus de deux nœuds. Des protocoles avancés sont utilisés pour optimiser les performances. La conception repose sur le marquage VLAN avec plusieurs chemins réseau, ainsi que sur des configurations de renouvellement technologique, afin de garantir un fonctionnement continu et une mise à niveau aisée.

Ce sont des commutateurs Cisco 400GbE à 32 ports et 64 ports (X190300-CS-PI, X190300-PE et X190310-CS-PI) prenant en charge ONTAP 9.17.1 et versions ultérieures.

Le nouveau système de stockage NetApp AFX offre une solution désagrégée conçue pour répondre aux exigences rigoureuses des charges de travail NAS et S3 hautes performances, notamment les applications d'IA/ML. Les systèmes AFX proposent des fonctionnalités spécialisées pour les clients nécessitant un stockage de fichiers et d'objets évolutif et à haut débit.

====
.Mai 2025
[%collapsible]
====
.Commutateur de stockage Cisco Nexus 9336C-FX2-T
Il s'agit de commutateurs de stockage Cisco 12 ports 10/25/40/100GbE (X190212-CS-PE et X190212-CS-PI) compatibles avec ONTAP 9.10.1 et versions ultérieures. Ils prennent en charge les configurations de stockage 100GbE (stockage connecté au commutateur).

====


[[2023-release]]
== Version 2023

.Mai 2023
[%collapsible]
====
.Cisco Nexus 9336C-FX2-T commutateur de cluster
Il s'agit de commutateurs de cluster Cisco 12 ports 10/25/40/100GbE (X190212-CS-PE et X190212-CS-PI) prenant en charge ONTAP 9.10.1 et versions ultérieures. Ils prennent en charge les configurations de cluster 10/25/40/100GbE.

====


[[2022-release]]
== Version 2022

.Octobre 2022
[%collapsible]
====
.Commutateur NVIDIA SN2100
Le NVIDIA SN2100 est un commutateur NVIDIA à 16 ports 100GbE (X190006-PE et X190006-PI) qui vous permet de créer des clusters ONTAP avec plus de deux nœuds, prenant en charge ONTAP 9.10.1 et versions ultérieures. Il s'agit d'un commutateur d'interconnexion de cluster et de stockage NVIDIA SN2100, incluant la prise en charge des configurations IP MetroCluster.

====


[[2021-release]]
== Version 2021

.Mai 2021
[%collapsible]
====
.Commutateur Cisco Nexus 9336C-FX2
Le Cisco Nexus 9336C-FX2 est un commutateur Cisco à 36 ports 100GbE (X190200-CS-PE et X190200-CS-PI). Il prend en charge une infrastructure partagée (cluster, haute disponibilité et stockage connecté au commutateur) sur la même paire de commutateurs Cisco Nexus 9336C-FX2, y compris la prise en charge des configurations IP MetroCluster, compatible avec ONTAP 9.9.1 et versions ultérieures.

====


[[2019-release]]
== Version 2019

.Mai 2019
[%collapsible]
====
.Commutateur Broadcom BES-53248
Le commutateur Broadcom BES-53248 (X190005 et X190005R) prend en charge les contrôleurs AFF/FAS avec des ports 10/25GbE et 40/100GbE, et prend en charge ONTAP 9.8 et versions ultérieures.

====
.Mars 2019
[%collapsible]
====
.Commutateurs de cluster et de stockage Cisco Nexus 3232C
Le commutateur Cisco Nexus 3232C est un commutateur Cisco à 36 ports 100 GbE (X190200) et un commutateur Cisco à 32 ports 100 GbE (X190100 et X190100R). Le commutateur de stockage Cisco Nexus 3232C prend en charge les connexions aux baies de disques NS224 NVMe des systèmes de stockage AFF et ASA suivants :

* AFF A800/ AFF ASA A800
* AFF A700/ AFF ASA A700
* AFF A400/ AFF ASA A400


Ils prennent en charge ONTAP 9.8 et versions ultérieures.

====