---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, switches, fas, aff systems 
summary: Découvrez les nouveaux commutateurs pour les systèmes FAS et AFF . 
---
= Quoi de neuf pour les commutateurs
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveaux commutateurs pour les systèmes FAS et AFF .  Pour plus d'informations sur les commutateurs, consultez le https://hwu.netapp.com/Switch/Index["Hardware Universe NetApp"^] .



== Nouvelle prise en charge des commutateurs

[cols="25h,~,~"]
|===
| Interrupteurs | Description | Disponible dès le début 


 a| 
Commutateur Cisco 32 ports 400 GbE (X190300-CS-PI et X190300-PE)
 a| 
Prise en charge du commutateur intra-cluster/HA/stockage Cisco 9332D-GX2B.
 a| 
ONTAP 9.17.1



 a| 
Commutateur Cisco 64 ports 400 GbE (X190310-CS-PI)
 a| 
Prise en charge du commutateur intra-cluster/HA/stockage Cisco 9364D-GX2A.
 a| 
ONTAP 9.17.1



 a| 
Commutateur de cluster et de stockage Cisco Nexus 9336C-FX2-T à 12 ports 10/25/40/100GbE (X190212-CS-PE et X190212-CS-PI)
 a| 
Prend en charge les configurations de cluster 10/25/40/100GbE et les configurations de stockage 100GbE (stockage connecté au commutateur).
 a| 
ONTAP 9.10.1



 a| 
Commutateur de cluster et de stockage Cisco Nexus 9336C-FX2-T à 12 ports 10/25/40/100GbE (X190212-CS-PE et X190212-CS-PI)
 a| 
Prend en charge les configurations de cluster 10/25/40/100GbE et les configurations de stockage 100GbE (stockage connecté au commutateur).
 a| 
ONTAP 9.10.1



 a| 
Commutateur NVIDIA 16 ports 100GbE (X190006-PE et X190006-PI)
 a| 
Prise en charge du commutateur d'interconnexion de cluster et du commutateur de stockage NVIDIA SN2100, y compris la prise en charge des configurations IP MetroCluster .
 a| 
ONTAP 9.10.1



 a| 
Commutateur Cisco 36 ports 100GbE (X190200-CS-PE et X190200-CS-PI)
 a| 
Prend en charge une infrastructure partagée (Cluster, HA et stockage connecté au commutateur) sur la même paire de commutateurs Cisco Nexus 9336C-FX2, y compris la prise en charge des configurations IP MetroCluster .
 a| 
ONTAP 9.9.1



 a| 
Commutateur Cisco 36 ports 100GbE (X190200-CS-PE et X190200-CS-PI), (X190210-FE-PE et X190210-FE-PI)
 a| 
Le commutateur d'interconnexion de cluster et le commutateur de stockage Cisco Nexus 9336C-FX2 prennent en charge les systèmes de stockage AFF et ASA , ainsi que la connectivité des données frontales.
 a| 
ONTAP 9,8



 a| 
Commutateur Broadcom BES-53248 (X190005 et X190005R)
 a| 
Prise en charge du commutateur d'interconnexion de cluster Broadcom BES-53248 pour les contrôleurs AFF/ FAS avec des ports 10/25GbE et 40/100GbE.
 a| 
ONTAP 9,8



 a| 
Commutateur Cisco 100GbE à 36 ports (X190200) et commutateur Cisco 100GbE à 32 ports (X190100 et X190100R)
 a| 
Prise en charge du commutateur de stockage Cisco Nexus 3232C pour la connexion des baies de disques NVMe NS224 aux systèmes de stockage AFF et ASA :

* AFF A800/ AFF ASA A800
* AFF A700/ AFF ASA A700
* AFF A400/ AFF ASA A400
* AFF A320

 a| 
ONTAP 9,8

|===