---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, switches, fas, aff systems 
summary: En savoir plus sur les nouveaux switchs pour les systèmes FAS et AFF. 
---
= Nouveautés pour les commutateurs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En savoir plus sur les nouveaux switchs pour les systèmes FAS et AFF. Pour plus d'informations sur le commutateur, reportez-vous à la https://hwu.netapp.com/Switch/Index["NetApp Hardware Universe"^].



== Nouveau support de commutateur

[cols="25h,~,~"]
|===
| Commutateurs | Description | Disponible au début 


 a| 
Commutateur NVIDIA 100 GbE à 16 ports (X190006-PE et X190006-PI)
 a| 
Prise en charge du commutateur d'interconnexion de cluster NVIDIA SN2100 et du commutateur de stockage, y compris la prise en charge des configurations MetroCluster IP.
 a| 
ONTAP 9.10.1



 a| 
Commutateur Cisco 100 GbE à 36 ports (X190200-CS-PE et X190200-CS-PI)
 a| 
Prise en charge d'une infrastructure partagée (cluster, haute disponibilité et stockage DAS) sur la même paire de commutateurs Cisco Nexus 9336C-FX2, y compris la prise en charge des configurations MetroCluster IP.
 a| 
ONTAP 9.9.1



 a| 
Commutateur Cisco 100 GbE à 36 ports (X190200-CS-PE et X190200-CS-PI), (X190210-FE-PE et X190210-FE-PI)
 a| 
Prise en charge des commutateurs de stockage et des commutateurs d'interconnexion de cluster Cisco Nexus 9336C-FX2 pour les systèmes de stockage AFF et ASA, ainsi que pour la connectivité des données front-end.
 a| 
ONTAP 9.8



 a| 
Commutateur Broadcom BES-53248 (X190005 et X190005R)
 a| 
Prise en charge du commutateur d'interconnexion de cluster Broadcom BES-53248 pour les contrôleurs AFF/FAS avec ports 10 GbE et 40 GbE.
 a| 
ONTAP 9.8



 a| 
Commutateur Cisco 100 GbE à 36 ports (X190200) et commutateur Cisco 100 GbE à 32 ports (X190100 et X190100R)
 a| 
Prise en charge des switchs de stockage Cisco Nexus 3232C pour la connexion des tiroirs de disques NVMe NS224 avec les systèmes de stockage AFF et ASA :

* AFF A800/AFF ASA A800
* ASA AFF A700/AFF A700
* AFF A400/AFF ASA A400
* AFF A320

 a| 
ONTAP 9.8

|===