---
permalink: switch-nvidia-sn2100/components-sn2100-cluster.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Si vous souhaitez créer des clusters ONTAP avec plus de deux nœuds, vous aurez besoin de deux commutateurs réseau de cluster compatibles.  Vous pouvez utiliser des commutateurs de gestion supplémentaires, qui sont optionnels. 
---
= Composants et références des commutateurs NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour l'installation et la maintenance du commutateur NVIDIA SN2100, assurez-vous de consulter la liste des composants et les références du boîtier et du kit de rails.



== Détails du cabinet

Vous installez le commutateur NVIDIA SN2100 (X190006) dans l'armoire à commutateur double/simple NVIDIA avec les supports standard fournis avec le commutateur.



== Détails du kit de rails

Le tableau suivant répertorie la référence et la description des aiguillages et des kits de rails SN2100 :

[cols="1,2"]
|===
| Numéro de pièce | Description 


 a| 
X190006-PE
 a| 
Commutateur de cluster, NVIDIA SN2100, 16 ports 100 GbE, PTSX



 a| 
X190006-PI
 a| 
Commutateur de cluster, NVIDIA SN2100, 16PT 100GbE, PSIN



 a| 
X-MTEF-KIT-D
 a| 
Kit de rails, double commutateur NVIDIA côte à côte



 a| 
X-MTEF-KIT-E
 a| 
Kit de rails, interrupteur unique NVIDIA à faible profondeur

|===

NOTE: Consultez la documentation NVIDIA pour plus de détails. https://docs.nvidia.com/networking/display/sn2000pub/Installation["installation de votre kit d'aiguillage et de rail SN2100"^] .

.Quelle est la prochaine étape ?
Une fois que vous avez confirmé vos composants et leurs références, vous pouvez consulter le link:required-documentation-sn2100-cluster.html["documentation requise"].
