---
permalink: switch-nvidia-sn2100/configure-reqs-sn2100-cluster.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: 'Pour l"installation et la maintenance du commutateur NVIDIA SN2100, assurez-vous de consulter toutes les exigences et la documentation recommandée.' 
---
= Configuration requise pour les commutateurs NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour l'installation et la maintenance du commutateur NVIDIA SN2100, assurez-vous de consulter toutes les exigences de configuration.



== Conditions d'installation

Si vous souhaitez créer des clusters ONTAP avec plus de deux nœuds, vous aurez besoin de deux commutateurs réseau de cluster compatibles.  Vous pouvez utiliser des commutateurs de gestion supplémentaires, qui sont optionnels.

Vous installez le commutateur NVIDIA SN2100 (X190006) dans l'armoire à commutateur double/simple NVIDIA avec les supports standard fournis avec le commutateur.

Pour les consignes de câblage, voirlink:cabling-considerations-sn2100-cluster.html["Examiner les considérations relatives au câblage et à la configuration"] .



== Prise en charge ONTAP et de Linux

Le commutateur NVIDIA SN2100 est un commutateur 10/25/40/100GbE fonctionnant sous Cumulus Linux.  Le commutateur prend en charge les éléments suivants :

* ONTAP 9.10.1P3 et versions ultérieures
+
Le commutateur SN2100 prend en charge les applications de cluster et de stockage dans ONTAP 9.10.1P3 et versions ultérieures sur différentes paires de commutateurs.

* Versions du système d'exploitation Cumulus Linux (CL)
+
** Certaines versions de CL sont qualifiées et prises en charge par NetApp.  Pour obtenir des informations à jour sur la compatibilité, veuillez consulter lelink:https://mysupport.netapp.com/site/info/nvidia-cluster-switch["Informations sur les commutateurs Ethernet NVIDIA"^] la page ou lalink:https://hwu.netapp.com["Hardware Universe NetApp"^] .
** Pour télécharger le logiciel SN2100 Cumulus depuis le NVIDIA, vous devez disposer d'identifiants de connexion pour accéder au portail d'assistance aux entreprises de NVIDIA.  Consultez l'article de la base de connaissances https://kb.netapp.com/onprem/Switches/Nvidia/How_To_Register_With_NVIDIA_For_Enterprise_Support_Portal_Access["Comment s'inscrire auprès de NVIDIA pour accéder au portail d'assistance aux entreprises"^] .




* Vous pouvez installer Cumulus Linux lorsque le commutateur exécute Cumulus Linux ou ONIE.


.Quelle est la prochaine étape ?
Après avoir examiné les exigences de configuration, vous pouvez confirmer votre link:components-sn2100-cluster.html["composants et numéros de pièces"].
