---
permalink: switch-nvidia-sn2100/configure-reqs-sn2100-cluster.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: 'Pour l"installation et la maintenance du commutateur NVIDIA SN2100, vérifiez toutes les conditions et la documentation recommandée.' 
---
= Configuration requise pour les switchs NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour l'installation et la maintenance des switchs NVIDIA SN2100, vérifiez toutes les exigences de configuration.



== Conditions requises pour l'installation

Si vous souhaitez créer des clusters ONTAP avec plus de deux nœuds, vous devez prendre en charge deux commutateurs de réseau de clusters. Vous pouvez utiliser des commutateurs de gestion supplémentaires, qui sont facultatifs.

Vous installez le commutateur NVIDIA SN2100 (X190006) dans l'armoire de commutateur NVIDIA double/simple avec les supports standard fournis avec le commutateur.

Pour connaître les instructions de câblage, reportez-vous à la section link:cabling-considerations-sn2100-cluster.html["Examinez les considérations relatives au câblage et à la configuration"].



== Prise en charge de ONTAP et Linux

Le commutateur NVIDIA SN2100 est un commutateur 10/25/40 GbE exécutant Cumulus Linux. Le commutateur prend en charge les éléments suivants :

* ONTAP 9.10.1P3.
+
Le commutateur SN2100 sert les applications de stockage et de cluster dans le ONTAP 9.10.1P3 sur différentes paires de commutateurs.

* Version du système d'exploitation Cumulus Linux (CL).
+
Pour télécharger le logiciel SN2100 Cumulus de NVIDIA, vous devez disposer d'informations de connexion pour accéder au portail de support d'entreprise de NVIDIA. Consultez l'article de la base de connaissances https://kb.netapp.com/onprem/Switches/Nvidia/How_To_Register_With_NVIDIA_For_Enterprise_Support_Portal_Access["Comment s'inscrire auprès de NVIDIA pour accéder au portail de support de l'entreprise"^].
Pour plus d'informations sur la compatibilité actuelle, reportez-vous au https://mysupport.netapp.com/site/info/nvidia-cluster-switch["Commutateurs Ethernet NVIDIA"^] page d'informations.

* Vous pouvez installer Cumulus Linux lorsque le commutateur exécute Cumulus Linux ou ONIE.

