---
permalink: switch-nvidia-sn2100/install-hardware-sn2100-cluster.html 
sidebar: sidebar 
keywords: switches hardware installation 
summary: Installez le matériel du commutateur de cluster NVIDIA SN2100 en suivant la documentation de NVIDIA. 
---
= Installez le matériel pour le commutateur de cluster NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Installez le matériel du commutateur de cluster NVIDIA SN2100 en suivant la documentation de NVIDIA. L'installation matérielle est la première étape avant de configurer le commutateur pour le fonctionnement en cluster.

Suivez ces étapes pour installer et configurer vos commutateurs SN2100. Consultez la documentation NVIDIA pour obtenir des instructions détaillées.

.Étapes
. Examinerlink:configure-reqs-sn2100-cluster.html["exigences de configuration"] .
. Suivez les instructions dans le link:https://networking-docs.nvidia.com/sn2000hw/latest["Guide d'installation de la NVIDIA Switch"^].


.Quelle est la prochaine étape ?
Une fois votre matériel installé, vous pouvezlink:cabling-considerations-sn2100-cluster.html["revoir le câblage et la configuration"] exigences.
