---
permalink: switch-nvidia-sn2100/install_cabling_config_considerations_sn2100.html 
sidebar: sidebar 
keywords: sn2100 SN2100 cabling setup, sn2100 switches configuration, cumulus linux os 
summary: 'Avant de configurer votre commutateur NVIDIA SN2100, consultez les informations suivantes :' 
---
= Considérations relatives au câblage et à la configuration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de configurer votre commutateur NVIDIA SN2100, consultez les informations suivantes :

. Seules les connexions optiques sont prises en charge sur les switchs SN2100 avec carte réseau X1151A, carte réseau X1146A ou ports 100GbE intégrés. Par exemple :
+
.. AFF A800 sur les ports e0a et e0b
.. AFF A320 sur les ports e0g et e0h


. Lorsqu'une carte QSA est utilisée pour se connecter aux ports intégrés de cluster Intel sur une plate-forme, toutes les liaisons ne s'allument pas.
+
Exemples de plateformes : FAS2750, AFF A300, FAS8200 (All 10G) et AFF A250 (25G).

+
Pour résoudre ce problème, procédez comme suit :

+
.. Pour Intel 10G, définissez manuellement la vitesse de liaison swp1s0-3 sur 10000 et désactivez la négociation automatique
.. Pour Chelsio 25G, définissez manuellement la vitesse de liaison swp2s0-3 sur 25000 et désactivez la négociation automatique
+

NOTE: Utiliser les ports 40/100G non arraché à l'aide de 10G/25G QSA. N'insérez pas l'adaptateur QSA sur les ports configurés pour l'arrachage.



. En fonction de l'émetteur-récepteur dans le port du commutateur, vous devrez peut-être régler la vitesse du port du commutateur sur une vitesse fixe. Si vous utilisez des ports de dérivation 10G et 25G, assurez-vous que la négociation automatique est désactivée et que la vitesse du port est définie sur le commutateur. Par exemple :
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ net add int swp1s3 link autoneg off && net com
--- /etc/network/interfaces     2019-11-17 00:17:13.470687027 +0000
+++ /run/nclu/ifupdown2/interfaces.tmp  2019-11-24 00:09:19.435226258 +0000
@@ -37,21 +37,21 @@
     alias 10G Intra-Cluster Node
     link-autoneg off
     link-speed 10000  *<---- port speed set*
     mstpctl-bpduguard yes
     mstpctl-portadminedge yes
     mtu 9216

auto swp1s3
iface swp1s3
     alias 10G Intra-Cluster Node
-    link-autoneg off
+    link-autoneg on
     link-speed 10000 *<---- port speed set*
     mstpctl-bpduguard yes
     mstpctl-portadminedge yes
     mtu 9216

auto swp2s0
iface swp2s0
     alias 25G Intra-Cluster Node
     link-autoneg off
     link-speed 25000 *<---- port speed set*
----

