---
permalink: switch-nvidia-sn2100/install-onie-mode-sn2100-cluster.html 
sidebar: sidebar 
keywords: install cumulus onie mode, sn2100 SN2100 switches setup, cumulus linux, onie mode 
summary: 'Le système d"exploitation Cumulus Linux (CL) peut être installé lorsque le commutateur exécute Cumulus Linux ou ONIE.' 
---
= Installez Cumulus Linux en mode ONIE
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez cette procédure pour installer le système d'exploitation Cumulus Linux (CL) lorsque le commutateur est en mode ONIE.


NOTE: Le système d'exploitation Cumulus Linux (CL) peut être installé lorsque le commutateur exécute ONIE ou Cumulus Linux (voir link:install-cumulus-mode-sn2100-cluster.html["Installer en mode Cumulus"]).

.Description de la tâche
Vous pouvez installer Cumulus Linux à l'aide de l'environnement d'installation en réseau ouvert (ONIE) qui permet la détection automatique d'une image du programme d'installation réseau. Cela facilite le modèle de système de sécurisation des commutateurs avec un choix de systèmes d'exploitation, comme Cumulus Linux. La façon la plus simple d'installer Cumulus Linux avec ONIE est avec la découverte HTTP locale.


NOTE: Si votre hôte est compatible IPv6, assurez-vous qu'il exécute un serveur Web. Si votre hôte est compatible IPv4, assurez-vous qu'il exécute DHCP en plus d'un serveur Web.

Cette procédure explique comment mettre à niveau Cumulus Linux une fois que l'administrateur a démarré dans ONIE.

.Étapes
[role="tabbed-block"]
====
.Cumulus Linux 4.4.3
--
. Téléchargez le fichier d'installation de Cumulus Linux dans le répertoire racine du serveur Web. Renommez ce fichier : `onie-installer`.
. Connectez votre hôte au port Ethernet de gestion du commutateur à l'aide d'un câble Ethernet.
. Mettez l'interrupteur sous tension.
+
Le commutateur télécharge le programme d'installation de l'image ONIE et démarre. Une fois l'installation terminée, l'invite de connexion Cumulus Linux s'affiche dans la fenêtre du terminal.

+

NOTE: Chaque fois que Cumulus Linux est installé, l'intégralité de la structure du système de fichiers est effacée et reconstruite.

. Redémarrez le commutateur SN2100 :
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *sudo reboot*
----
. Appuyez sur la touche *Esc* de l'écran GNU GRUB pour interrompre le processus de démarrage normal, sélectionnez *ONIE* et appuyez sur *entrée*.
. Sur l'écran suivant, sélectionnez *ONIE: Install OS*.
. Le processus de détection du programme d'installation ONIE exécute la recherche de l'installation automatique. Appuyez sur *entrée* pour arrêter temporairement le processus.
. Lorsque le processus de détection est arrêté :
+
[listing, subs="+quotes"]
----
ONIE:/ # *onie-stop*
discover: installer mode detected.
Stopping: discover...start-stop-daemon: warning: killing process 427:
No such process done.
----
. Si le service DHCP fonctionne sur votre réseau, vérifiez que l'adresse IP, le masque de sous-réseau et la passerelle par défaut sont correctement attribués :
+
`ifconfig eth0`

+
[listing, subs="+quotes"]
----
ONIE:/ # *ifconfig eth0*
eth0   Link encap:Ethernet  HWaddr B8:CE:F6:19:1D:F6
       inet addr:10.233.204.71  Bcast:10.233.205.255  Mask:255.255.254.0
       inet6 addr: fe80::bace:f6ff:fe19:1df6/64 Scope:Link
       UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
       RX packets:21344 errors:0 dropped:2135 overruns:0 frame:0
       TX packets:3500 errors:0 dropped:0 overruns:0 carrier:0
       collisions:0 txqueuelen:1000
       RX bytes:6119398 (5.8 MiB)  TX bytes:472975 (461.8 KiB)
       Memory:dfc00000-dfc1ffff

ONIE:/ # *route*
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface

default         10.233.204.1    0.0.0.0         UG    0      0      0   eth0
10.233.204.0    *               255.255.254.0   U     0      0      0   eth0
----
. Si le schéma d'adressage IP est défini manuellement, procédez comme suit :
+
[listing, subs="+quotes"]
----
ONIE:/ # *ifconfig eth0 10.233.204.71 netmask 255.255.254.0*
ONIE:/ # *route add default gw 10.233.204.1*
----
. Répétez l'étape 9 pour vérifier que les informations statiques sont correctement saisies.
. Installez Cumulus Linux :
+
[listing]
----
# onie-nos-install http://<web-server>/<path>/cumulus-linux-4.4.3-mlx-amd64.bin
----
+
[listing, subs="+quotes"]
----
ONIE:/ # *route*

  Kernel IP routing table

  ONIE:/ # *onie-nos-install http://_<web-server>/<path>_/cumulus-linux-4.4.3-mlx-amd64.bin*

  Stopping: discover... done.
  Info: Attempting http://10.60.132.97/x/eng/testbedN,svl/nic/files/cumulus-linux-4.4.3-mlx-amd64.bin ...
  Connecting to 10.60.132.97 (10.60.132.97:80)
  installer            100% |*******************************|   552M  0:00:00 ETA
  ...
  ...
----
. Une fois l'installation terminée, connectez-vous au commutateur.
+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
. Vérifiez la version de Cumulus Linux : `net show version`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show version*
NCLU_VERSION=1.0-cl4.4.3u4
DISTRIB_ID="Cumulus Linux"
DISTRIB_RELEASE=*4.4.3*
DISTRIB_DESCRIPTION=*"Cumulus Linux 4.4.3”*
----


--
.Cumulus Linux 5.x.
--
. Téléchargez le fichier d'installation de Cumulus Linux dans le répertoire racine du serveur Web. Renommez ce fichier : `onie-installer`.
. Connectez votre hôte au port Ethernet de gestion du commutateur à l'aide d'un câble Ethernet.
. Mettez l'interrupteur sous tension.
+
Le commutateur télécharge le programme d'installation de l'image ONIE et démarre. Une fois l'installation terminée, l'invite de connexion Cumulus Linux s'affiche dans la fenêtre du terminal.

+

NOTE: Chaque fois que Cumulus Linux est installé, l'intégralité de la structure du système de fichiers est effacée et reconstruite.

. Redémarrez le commutateur SN2100 :
+
[listing]
----
cumulus@cumulus:mgmt:~$ sudo reboot
.
.
GNU GRUB version 2.06-3
+-------------------------------------------------------------------------+
| Cumulus-Linux GNU/Linux                                                 |
| Advanced options for Cumulus-Linux GNU/Linux                            |
| ONIE                                                                    |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
+-------------------------------------------------------------------------+
----
. Appuyez sur la touche Echap de l'écran GNU GRUB pour interrompre le processus de démarrage normal, sélectionnez ONIE et appuyez sur entrée.
+
[listing]
----
.
.
Loading ONIE ...

GNU GRUB version 2.02
+-------------------------------------------------------------------------+
| ONIE: Install OS                                                        |
| ONIE: Rescue                                                            |
| ONIE: Uninstall OS                                                      |
| ONIE: Update ONIE                                                       |
| ONIE: Embed ONIE                                                        |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
+-------------------------------------------------------------------------+
----
+
Sélectionnez ONIE: *Installer OS.*

. Le processus de détection du programme d'installation ONIE exécute la recherche de l'installation automatique. Appuyez sur *entrée* pour arrêter temporairement le processus.
. Lorsque le processus de détection est arrêté :
+
[listing, subs="+quotes"]
----
ONIE:/ # *onie-stop*
discover: installer mode detected.
Stopping: discover...start-stop-daemon: warning: killing process 427:
No such process done.
----
. Configurez l'adresse IP, le masque de sous-réseau et la passerelle par défaut :
+
`ifconfig eth0`

+
[listing, subs="+quotes"]
----
ONIE:/ # *ifconfig eth0*
eth0   Link encap:Ethernet  HWaddr B8:CE:F6:19:1D:F6
       inet addr:10.233.204.71  Bcast:10.233.205.255  Mask:255.255.254.0
       inet6 addr: fe80::bace:f6ff:fe19:1df6/64 Scope:Link
       UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
       RX packets:21344 errors:0 dropped:2135 overruns:0 frame:0
       TX packets:3500 errors:0 dropped:0 overruns:0 carrier:0
       collisions:0 txqueuelen:1000
       RX bytes:6119398 (5.8 MiB)  TX bytes:472975 (461.8 KiB)
       Memory:dfc00000-dfc1ffff
ONIE:/ #
ONIE:/ # *ifconfig eth0 10.228.140.27 netmask 255.255.248.0*
ONIE:/ # *ifconfig eth0*
eth0   Link encap:Ethernet HWaddr B8:CE:F6:5E:05:E6
       inet addr:10.228.140.27 Bcast:10.228.143.255 Mask:255.255.248.0
       inet6 addr: fd20:8b1e:b255:822b:bace:f6ff:fe5e:5e6/64 Scope:Global
       inet6 addr: fe80::bace:f6ff:fe5e:5e6/64 Scope:Link
       UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
       RX packets:18813 errors:0 dropped:1418 overruns:0 frame:0
       TX packets:491 errors:0 dropped:0 overruns:0 carrier:0
       collisions:0 txqueuelen:1000
       RX bytes:1339596 (1.2 MiB) TX bytes:49379 (48.2 KiB)
       Memory:dfc00000-dfc1ffff
ONIE:/ # *route add default gw 10.228.136.1*
ONIE:/ # *route*
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface

default         10.228.136.1    0.0.0.0         UG    0      0      0   eth0
10.228.136.1    *               255.255.248.0   U     0      0      0   eth0
----
. Installez Cumulus Linux 5.4 :
+
`# onie-nos-install http://<web-server>/<path>/cumulus-linux-5.4-mlx-amd64.bin`

+
[listing, subs="+quotes"]
----
ONIE:/ # *route*

  Kernel IP routing table

  ONIE:/ # *onie-nos-install http://_<web-server>/<path>_/cumulus-linux-5.4-mlx-amd64.bin*

  Stopping: discover... done.
  Info: Attempting http://10.60.132.97/x/eng/testbedN,svl/nic/files/cumulus-linux-5.4-mlx-amd64.bin ...
  Connecting to 10.60.132.97 (10.60.132.97:80)
  installer            100% |*******************************|   552M  0:00:00 ETA
  ...
  ...
----
. Une fois l'installation terminée, connectez-vous au commutateur.
+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
. Vérifiez la version de Cumulus Linux : `nv show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
operational         applied              description
------------------- -------------------- ---------------------
hostname            cumulus              cumulus
build               Cumulus Linux 5.4.0  system build version
uptime              6 days, 13:37:36     system uptime
timezone            Etc/UTC              system time zone
----
. Créez un nouvel utilisateur et ajoutez cet utilisateur à la `sudo` groupe. Cet utilisateur ne prend effet qu'après le redémarrage de la session console/SSH.
+
`sudo adduser --ingroup netedit admin`

+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser --ingroup netedit admin*
[sudo] password for cumulus:
Adding user 'admin' ...
Adding new user 'admin' (1001) with group `netedit' ...
Creating home directory '/home/admin' ...
Copying files from '/etc/skel' ...
New password:
Retype new password:
passwd: password updated successfully
Changing the user information for admin
Enter the new value, or press ENTER for the default
Full Name []:
Room Number []:
Work Phone []:
Home Phone []:
Other []:
Is the information correct? [Y/n] *y*

cumulus@sw1:mgmt:~$ *sudo adduser admin sudo*
[sudo] password for cumulus:
Adding user `admin' to group `sudo' ...
Adding user admin to group sudo
Done.
cumulus@sw1:mgmt:~$ *exit*
logout
Connection to 10.233.204.71 closed.

[admin@cycrh6svl01 ~]$ ssh admin@10.233.204.71
admin@10.233.204.71's password:
Linux sw1 4.19.0-cl-1-amd64 #1 SMP Cumulus 4.19.206-1+cl4.4.1u1 (2021-09-09) x86_64
Welcome to NVIDIA Cumulus (R) Linux (R)

For support and online technical documentation, visit
http://www.cumulusnetworks.com/support

The registered trademark Linux (R) is used pursuant to a sublicense from LMI, the exclusive licensee of Linus Torvalds, owner of the mark on a world-wide basis.
admin@sw1:mgmt:~$
----
. Ajoutez des groupes d'utilisateurs supplémentaires auxquels l'utilisateur admin peut accéder `nv` commandes :
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *sudo adduser admin nvshow*
     [sudo] password for cumulus:
     Adding user `admin' to group `nvshow' ...
     Adding user admin to group nvshow
     Done.
----
+
Voir https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-54/System-Configuration/Authentication-Authorization-and-Accounting/User-Accounts/["Comptes d'utilisateur NVIDIA"^] pour en savoir plus.



--
====
.Et la suite ?
Après avoir installé Cumulus Linux en mode ONIE, vous pouvezlink:install-rcf-sn2100-cluster.html["installer le script du fichier de configuration de référence (RCF)"] .
