---
permalink: switch-nvidia-sn2100/install_setup_sn2100_switches_overview.html 
sidebar: sidebar 
keywords: sn2100 SN2100 switches setup, sn2100 SN2100 switches install, cumulus linux 
summary: Le commutateur NVIDIA SN2100 est un commutateur Ethernet 10/25/40/100 GbE exécutant Cumulus Linux. Le commutateur SN2100 sert les applications de stockage et de cluster dans ONTAP 9.10.1 sur différentes paires de switchs. 
---
= Installer et configurer les switchs NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le commutateur NVIDIA SN2100 est un commutateur Ethernet 10/25/40/100 Go exécutant Cumulus Linux. Le commutateur SN2100 sert les applications de stockage et de cluster dans le ONTAP 9.10.1P3 sur différentes paires de commutateurs.

Le système d'exploitation Cumulus Linux (CL) peut être installé lorsque le commutateur exécute Cumulus Linux ou ONIE. Pour cette version, Cumulus Linux version 4.4.2 est pris en charge.


NOTE: Les procédures utilisent ici l'utilitaire NCLU (Network Command Line Utility) qui est une interface de ligne de commande qui garantit que Cumulus Linux est entièrement accessible à tous. La commande net est l'utilitaire wrapper que vous utilisez pour exécuter des actions à partir d'un terminal.


IMPORTANT: Lorsque vous utilisez des câbles de dérivation pour 10G et 25G, assurez-vous que la négociation automatique est désactivée et que la vitesse du port est difficilement définie sur le commutateur. Voir link:install_cabling_config_considerations_sn2100.html["Considérations relatives au câblage et à la configuration"^] pour plus d'informations.
