---
permalink: switch-nvidia-sn2100/migrate-2n-switched-sn2100-cluster.html 
sidebar: sidebar 
keywords: two-node switchless cluster environments,migrating to a two-node switched NVIDIA SN2100 cluster environment,switchless cluster environments,NVIDIA SN2100 switches 
summary: 'Si vous disposez déjà d"un environnement en cluster sans commutateur à deux nœuds, vous pouvez migrer vers un environnement de cluster avec commutateur à deux nœuds à l"aide de commutateurs NVIDIA SN2100, ce qui vous permet d"évoluer au-delà de deux nœuds du cluster.' 
---
= Migrez vers un cluster à deux nœuds avec commutateurs de cluster NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous disposez déjà d'un environnement en cluster sans commutateur à deux nœuds, vous pouvez migrer vers un environnement de cluster avec commutateur à deux nœuds à l'aide de commutateurs NVIDIA SN2100, ce qui vous permet d'évoluer au-delà de deux nœuds du cluster.

La procédure que vous utilisez dépend de votre présence de deux ports cluster-network dédiés sur chaque contrôleur ou d'un port de cluster unique sur chaque contrôleur. Le processus documenté fonctionne pour tous les nœuds utilisant des ports optiques ou Twinax, mais il n'est pas pris en charge sur ce commutateur si les nœuds utilisent des ports RJ45 10GBASE-T intégrés pour les ports cluster-network.



== Examen des conditions requises

.Configuration à 2 nœuds sans commutateur
Assurez-vous que :

* La configuration sans commutateur à 2 nœuds est correctement configurée et fonctionnelle.
* Les nœuds exécutent ONTAP 9.10.1P3 et version ultérieure.
* Tous les ports de cluster sont à l'état *up*.
* Toutes les interfaces logiques (LIF) de cluster sont à l'état *up* et sur leurs ports de base.


.Configuration des commutateurs de cluster NVIDIA SN2100
Assurez-vous que :

* Les deux commutateurs disposent d'une connectivité réseau de gestion.
* Il y a un accès à la console aux commutateurs du cluster.
* Les connexions de nœud à nœud NVIDIA SN2100 et de commutateur à commutateur utilisent des câbles Twinax ou fibre optique.
+

IMPORTANT: Voir link:cabling-considerations-sn2100-cluster.html["Examinez les considérations relatives au câblage et à la configuration"] pour mises en garde et autres détails. Le https://["Hardware Universe - commutateurs"^] contient également plus d'informations sur le câblage.

* Les câbles ISL (Inter-Switch Link) sont connectés aux ports swp15 et swp16 sur les deux commutateurs NVIDIA SN2100.
* La personnalisation initiale des deux commutateurs SN2100 est terminée, de sorte que :
+
** Les commutateurs SN2100 exécutent la dernière version de Cumulus Linux
** Les fichiers de configuration de référence (RCFs) sont appliqués aux commutateurs
** Toute personnalisation de site, telle que SMTP, SNMP et SSH, est configurée sur les nouveaux commutateurs.
+
Le https://["Hardware Universe"^] contient les informations les plus récentes sur les ports de cluster réels de vos plates-formes.







== Migrer les commutateurs

.À propos des exemples
Les exemples de cette procédure utilisent la nomenclature de commutateurs et de nœuds du cluster suivante :

* Les noms des commutateurs SN2100 sont _sw1_ et _sw2_.
* Les noms des SVM du cluster sont _node1_ et _node2_.
* Les noms des LIFS sont respectivement _node1_clude1_ et _node1_clus2_ sur le nœud 1 et _node2_clum1_ et _node2_clum2_ sur le nœud 2.
* Le `cluster1::*>` l'invite indique le nom du cluster.
* Les ports de cluster utilisés dans cette procédure sont _e3a_ et _e3b_.
* Les ports de dérivation prennent le format suivant : swp[port]s[port de dérivation 0-3]. Par exemple, quatre ports de dérivation sur swp1 sont _swp1s0_, _swp1s1_, _swp1s2_ et _swp13_.




=== Étape 1 : préparer la migration

. Si AutoSupport est activé sur ce cluster, supprimez la création automatique de dossiers en invoquant un message AutoSupport : `system node autosupport invoke -node * -type all -message MAINT=xh`
+
où _x_ représente la durée de la fenêtre de maintenance en heures.

. Modifiez le niveau de privilège en avancé, en saisissant `y` lorsque vous êtes invité à continuer : `set -privilege advanced`
+
L'invite avancée (`*>`) s'affiche.





=== Étape 2 : configurer les ports et le câblage

. Désactivez tous les ports orientés nœuds (et non les ports ISL) sur les nouveaux commutateurs sw1 et sw2 du cluster.
+
Vous ne devez pas désactiver les ports ISL.

+
.Montrer l'exemple
[%collapsible]
====
Les commandes suivantes désactivent les ports node-face sur les commutateurs sw1 et sw2 :

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*

cumulus@sw2:~$ *net add interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
====
. Vérifier que l'ISL et les ports physiques de l'ISL entre les deux commutateurs SN2100 sw1 et sw2 sont en service sur les ports swp15 et swp16 :
+
`net show interface`

+
.Montrer l'exemple
[%collapsible]
====
L'exemple suivant montre que les ports ISL sont active sur le commutateur sw1 :

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface*

State  Name       Spd   MTU    Mode        LLDP         Summary
-----  ---------  ----  -----  ----------  -----------  -----------------------
...
...
UP     swp15      100G  9216   BondMember  sw2 (swp15)  Master: cluster_isl(UP)
UP     swp16      100G  9216   BondMember  sw2 (swp16)  Master: cluster_isl(UP)
----
+ l'exemple suivant montre que les ports ISL sont activés sur le commutateur sw2 :

+

[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name       Spd   MTU    Mode        LLDP         Summary
-----  ---------  ----  -----  ----------  -----------  -----------------------
...
...
UP     swp15      100G  9216   BondMember  sw1 (swp15)  Master: cluster_isl(UP)
UP     swp16      100G  9216   BondMember  sw1 (swp16)  Master: cluster_isl(UP)
----
====
. Vérifier que tous les ports du cluster sont bien :
+
`network port show`

+
Chaque port doit s'afficher `up` pour `Link` et en bonne santé pour `Health Status`.

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show*

Node: node1

                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2

                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

----
====
. Vérifier que toutes les LIFs de cluster sont opérationnelles :
+
`network interface show`

+
Chaque LIF de cluster doit afficher la valeur true pour `Is Home` et avoir un `Status Admin/Oper` de `up/up`.

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
----
====
. Désactiver la fonction de revert automatique sur les LIFs du cluster :
+
`network interface modify -vserver Cluster -lif * -auto-revert false`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   false
          node1_clus2   false
          node2_clus1   false
          node2_clus2   false

----
====
. Débranchez le câble du port du bloc d'instruments e3a sur le nœud1, puis connectez e3a au port 3 du commutateur du bloc d'instruments sw1, à l'aide du câblage approprié pris en charge par les commutateurs SN2100.
+
Le https://["Hardware Universe - commutateurs"^] contient plus d'informations sur le câblage.

. Débranchez le câble du port du bloc d'instruments e3a sur le nœud2, puis connectez e3a au port 4 du commutateur du bloc d'instruments sw1, à l'aide du câblage approprié pris en charge par les commutateurs SN2100.
. Sur le commutateur sw1, activez tous les ports orientés nœud.
+
.Montrer l'exemple
[%collapsible]
====
La commande suivante active tous les ports node-face sur le switch sw1 :

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net del interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
====
. Sur le commutateur sw1, vérifiez que tous les ports sont en service :
+
`net show interface all`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface all*

State  Name      Spd   MTU    Mode       LLDP            Summary
-----  --------- ----  -----  ---------- --------------- --------
...
DN     swp1s0    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s1    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s2    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s3    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s0    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s1    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s2    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s3    25G   9216   Trunk/L2                   Master: br_default(UP)
UP     swp3      100G  9216   Trunk/L2    node1 (e3a)    Master: br_default(UP)
UP     swp4      100G  9216   Trunk/L2    node2 (e3a)    Master: br_default(UP)
...
...
UP     swp15     100G  9216   BondMember  swp15          Master: cluster_isl(UP)
UP     swp16     100G  9216   BondMember  swp16          Master: cluster_isl(UP)
...
----
====
. Vérifier que tous les ports du cluster sont bien :
+
`network port show -ipspace Cluster`

+
.Montrer l'exemple
[%collapsible]
====
L'exemple suivant montre que tous les ports du cluster apparaissent sur les nœuds 1 et sur le nœud 2 :

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

----
====
. Afficher des informations relatives à l'état des nœuds du cluster :
+
`cluster show`

+
.Montrer l'exemple
[%collapsible]
====
L'exemple suivant affiche des informations sur la santé et l'éligibilité des nœuds du cluster :

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

----
====
. Déconnectez le câble du port du cluster e3b sur le nœud1, puis connectez e3b au port 3 du commutateur sw2 du cluster, en utilisant le câblage approprié pris en charge par les commutateurs SN2100.
. Déconnectez le câble du port du cluster e3b sur le nœud2, puis connectez e3b au port 4 du commutateur sw2 du cluster, en utilisant le câblage approprié pris en charge par les commutateurs SN2100.
. Sur le commutateur sw2, activez tous les ports orientés nœud.
+
.Montrer l'exemple
[%collapsible]
====
Les commandes suivantes permettent d'activer les ports orientés nœud sur le commutateur sw2 :

[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net del interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
====
. Sur le commutateur sw2, vérifiez que tous les ports sont en service :
+
`net show interface all`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface all*

State  Name      Spd   MTU    Mode       LLDP            Summary
-----  --------- ----  -----  ---------- --------------- --------
...
DN     swp1s0    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s1    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s2    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s3    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s0    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s1    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s2    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s3    25G   9216   Trunk/L2                   Master: br_default(UP)
UP     swp3      100G  9216   Trunk/L2    node1 (e3b)    Master: br_default(UP)
UP     swp4      100G  9216   Trunk/L2    node2 (e3b)    Master: br_default(UP)
...
...
UP     swp15     100G  9216   BondMember  swp15          Master: cluster_isl(UP)
UP     swp16     100G  9216   BondMember  swp16          Master: cluster_isl(UP)
...
----
====
. Sur les deux commutateurs sw1 et sw2, vérifier que les deux nœuds ont chacun une connexion à chaque commutateur :
+
`net show lldp`

+
.Montrer l'exemple
[%collapsible]
====
L'exemple suivant montre les résultats appropriés pour les deux commutateurs sw1 et sw2 :

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1              e3a
swp4       100G   Trunk/L2    node2              e3a
swp15      100G   BondMember  sw2                swp15
swp16      100G   BondMember  sw2                swp16

cumulus@sw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1              e3b
swp4       100G   Trunk/L2    node2              e3b
swp15      100G   BondMember  sw1                swp15
swp16      100G   BondMember  sw1                swp16
----
====
. Affiche des informations sur les périphériques réseau détectés dans votre cluster :
+
`net device-discovery show -protocol lldp`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface     Platform
----------- ------ ------------------------- ------------  ----------------
node1      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp3          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp3          -
node2      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp4          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4          -
----
====
. Vérifier que tous les ports du cluster sont bien :
+
`network port show -ipspace Cluster`

+
.Montrer l'exemple
[%collapsible]
====
L'exemple suivant montre que tous les ports du cluster apparaissent sur les nœuds 1 et sur le nœud 2 :

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e3a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e3a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/10000 healthy  false

----
====




=== Étape 3 : réaliser la procédure

. Activer la fonction de revert automatique sur toutes les LIFs du cluster :
+
`net interface modify -vserver Cluster -lif * -auto-revert true`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *net interface modify -vserver Cluster -lif * -auto-revert true*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
----
====
. Vérifiez que toutes les interfaces s'affichent `true` pour `Is Home`:
+
`net interface show -vserver Cluster`

+

NOTE: Cette opération peut prendre une minute.

+
.Montrer l'exemple
[%collapsible]
====
L'exemple suivant montre que toutes les LIFs sont up sur le nœud1 et celui du nœud2, ainsi que celui-ci `Is Home` les résultats sont vrais :

[listing, subs="+quotes"]
----
cluster1::*> *net interface show -vserver Cluster*

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e3b     true

----
====
. Vérifiez que les paramètres sont désactivés :
+
`network options switchless-cluster show`

+
.Montrer l'exemple
[%collapsible]
====
La sortie FALSE dans l'exemple suivant montre que les paramètres de configuration sont désactivés :

[listing, subs="+quotes"]
----
cluster1::*> *network options switchless-cluster show*
Enable Switchless Cluster: *false*
----
====
. Vérifiez l'état des membres du nœud sur le cluster :
+
`cluster show`

+
.Montrer l'exemple
[%collapsible]
====
L'exemple suivant affiche des informations sur la santé et l'éligibilité des nœuds du cluster :

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. Vérifiez que le réseau de cluster dispose d'une connectivité complète :
+
`cluster ping-cluster -node node-name`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node1*
Host is node1
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)

Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====
. Activez la fonction de collecte des journaux du contrôle de l'état du commutateur Ethernet pour collecter les fichiers journaux relatifs au commutateur à l'aide des commandes :
+
`system switch ethernet log setup-password` et `system switch ethernet log enable-collection`

+
.. Entrez : `system switch ethernet log setup-password`
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*sw1*
*sw2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *sw1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *sw2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
====
.. Suivi par : `system switch ethernet log enable-collection`
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*>
----
====


+

NOTE: Si l'une de ces commandes renvoie une erreur, contactez le support NetApp.

. Lancez la fonction de collecte du journal du commutateur :
+
`system switch ethernet log collect -device *`

+
Attendez 10 minutes, puis vérifiez que la collecte de journaux a réussi à l'aide de la commande :

+
`system switch ethernet log show`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log show*
Log Collection Enabled: true

Index  Switch                       Log Timestamp        Status
------ ---------------------------- -------------------  ---------    
1      sw1 (b8:ce:f6:19:1b:42)      4/29/2022 03:05:25   complete   
2      sw2 (b8:ce:f6:19:1b:96)      4/29/2022 03:07:42   complete
----
====
. Rétablissez le niveau de privilège sur admin :
+
`set -privilege admin`

. Si vous avez supprimé la création automatique de cas, réactivez-la en appelant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`


