---
permalink: switch-nvidia-sn2100/replace-sn2100-switch-storage.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nvidia, switch, cluster, network, nondisruptive, procedure, ndu, replace a nvidia sn2100 cluster switch - nvidia SN2100 
summary: 'Remplacement d"un commutateur de stockage NVIDIA SN2100 défectueux en procédure \(NDU\) sans interruption.' 
---
= Remplacement d'un commutateur de stockage NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lors du remplacement des commutateurs de stockage NVIDIA SN2100, vous devez connaître certaines informations de configuration, les connexions des ports et les exigences de câblage.

.Avant de commencer
Vous devez vérifier que les conditions suivantes sont présentes avant d'installer le logiciel Cumulus et les RCFs sur un commutateur de stockage NVIDIA SN2100 :

* Votre système peut prendre en charge les switchs de stockage NVIDIA SN2100.
* Vous devez avoir téléchargé les CFR applicables.
* Le http://["Hardware Universe"^] fournit des détails complets sur les ports pris en charge et leurs configurations.


.Description de la tâche
La configuration réseau existante doit présenter les caractéristiques suivantes :

* Assurez-vous que toutes les étapes de dépannage ont été effectuées pour vérifier que votre commutateur doit être remplacé.
* La connectivité de gestion doit exister sur les deux commutateurs.
+

NOTE: Assurez-vous que toutes les étapes de dépannage ont été effectuées pour vérifier que votre commutateur doit être remplacé.



Les caractéristiques du commutateur NVIDIA SN2100 de remplacement doivent être les suivantes :

* La connectivité du réseau de gestion doit fonctionner.
* L'accès à la console au commutateur de remplacement doit être en place.
* L'image appropriée du système d'exploitation FCR et Cumulus doit être chargée sur le commutateur.
* La personnalisation initiale du commutateur doit être terminée.


.Récapitulatif de la procédure
Cette procédure remplace le deuxième commutateur de stockage NVIDIA SN2100 sw2 par le nouveau commutateur NVIDIA SN2100 nsw2. Les deux nœuds sont le nœud1 et le nœud2.

Étapes à suivre :

* Vérifier que le commutateur à remplacer est sw2.
* Débrancher les câbles du commutateur sw2.
* Rebrancher les câbles sur le commutateur nsw2.
* Vérifiez toutes les configurations de périphérique sur le commutateur nsw2.


.Étapes
. Si AutoSupport est activé sur ce cluster, supprimez la création automatique de dossiers en invoquant un message AutoSupport :
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_ représente la durée de la fenêtre de maintenance en heures.

. Définissez le niveau de privilège sur avancé, en entrant *y* lorsque vous êtes invité à continuer : `set -privilege advanced`
. Vérifier l'état de santé des ports du nœud de stockage pour s'assurer qu'il existe une connexion au commutateur de stockage S1 :
+
`storage port show -port-type ENET`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage 100    enabled  online      30
node2
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage 100    enabled  online      30
cluster1::*>
----
====
. Vérifier que le commutateur de stockage sw1 est disponible :
`network device-discovery show`
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show protocol lldp*
Node/      Local Discovered
Protocol   Port	 Device (LLDP: ChassisID)  Interface   Platform
--------   ----  -----------------------   ---------   ---------
node1/lldp
           e3a   sw1 (b8:ce:f6:19:1b:42)   swp3        -
node2/lldp
           e3a   sw1 (b8:ce:f6:19:1b:42)   swp4        -
cluster1::*>
----
====
. Exécutez le
`net show interface` commande sur le commutateur de travail pour confirmer que vous pouvez voir les deux nœuds et tous les tiroirs :
`net show interface`
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e3a)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e3a)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
====
. Vérifiez les ports shelf dans le système de stockage :
`storage shelf port show -fields remote-device, remote-port`
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device, remote-port*
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   swp3          sw1
3.20    1   -             -
3.20    2   swp4          sw1
3.20    3   -             -
3.30    0   swp5          sw1
3.20    1   -             -
3.30    2   swp6          sw1
3.20    3   -             -
cluster1::*>
----
====
. Retirer tous les câbles reliés au commutateur de stockage sw2.
. Rebranchez tous les câbles au commutateur de remplacement nsw2.
. Vérifier à nouveau l'état de santé des ports du nœud de stockage :
`storage port show -port-type ENET`
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
node1
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage 100    enabled  online      30
node2
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage 100    enabled  online      30
cluster1::*>
----
====
. Vérifier que les deux commutateurs sont disponibles :
`net device-discovery show`
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show protocol lldp*
Node/     Local Discovered
Protocol  Port  Device (LLDP: ChassisID)  Interface	  Platform
--------  ----  -----------------------   ---------   ---------
node1/lldp
          e3a  sw1 (b8:ce:f6:19:1b:96)    swp1        -
          e7b  nsw2 (b8:ce:f6:19:1a:7e)   swp1        -
node2/lldp
          e3a  sw1 (b8:ce:f6:19:1b:96)    swp2        -
          e7b  nsw2 (b8:ce:f6:19:1a:7e)   swp2        -
cluster1::*>
----
====
. Vérifiez les ports shelf dans le système de stockage :
`storage shelf port show -fields remote-device, remote-port`
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device, remote-port*
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     swp3            sw1
3.20    1     swp3            nsw2
3.20    2     swp4            sw1
3.20    3     swp4            nsw2
3.30    0     swp5            sw1
3.20    1     swp5            nsw2
3.30    2     swp6            sw1
3.20    3     swp6            nsw2
cluster1::*>
----
====
. Activez la fonction de collecte des journaux du moniteur d'intégrité du commutateur Ethernet pour collecter les fichiers journaux relatifs au commutateur à l'aide des deux commandes suivantes : `system switch ethernet log setup-password` et `system switch ethernet log enable-collection`
+
Entrez : `system switch ethernet log setup-password`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*sw1*
*nsw2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *sw1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *nsw2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
====
+
Suivi par : `system switch ethernet log enable-collection`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system  switch ethernet log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*>
----
====
+

NOTE: Si l'une de ces commandes renvoie une erreur, contactez le support NetApp.

. Lancez la fonction de collecte du journal du commutateur : `system switch ethernet log collect -device *`
+
Attendez 10 minutes, puis vérifiez que la collecte de journaux a réussi à l'aide de la commande : `system switch ethernet log show`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log show*
Log Collection Enabled: true

Index  Switch                       Log Timestamp        Status
------ ---------------------------- -------------------  ---------    
1      sw1 (b8:ce:f6:19:1b:42)      4/29/2022 03:05:25   complete   
2      nsw2 (b8:ce:f6:19:1b:96)     4/29/2022 03:07:42   complete
----
====
. Rétablissez le niveau de privilège sur admin : `set -privilege admin`
. Si vous avez supprimé la création automatique de cas, réactivez-la en appelant un message AutoSupport :
`system node autosupport invoke -node * -type all -message MAINT=END`

