---
permalink: switch-nvidia-sn2100/required-documentation-sn2100-cluster.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: 'Consultez la documentation nécessaire à l"installation et à la maintenance des commutateurs de cluster NVIDIA SN2100.' 
---
= Consultez les exigences de documentation pour les commutateurs de cluster NVIDIA SN2100.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Consultez la documentation relative aux commutateurs et aux contrôleurs nécessaire pour configurer les commutateurs de cluster NVIDIA SN2100 et les paramétrer dans un cluster ONTAP.

[cols="1,2"]
|===
| Fonction | Description 


 a| 
link:https://networking-docs.nvidia.com/sn2000hw/latest["Guide d'installation de la NVIDIA Switch"^]
 a| 
Ce document explique comment installer vos commutateurs NVIDIA SN2100.



 a| 
link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2876580["Guide de câblage pour étagère de disque NVMe NS224"^]
 a| 
Vue d'ensemble et illustrations montrant comment configurer le câblage des baies de disques.

|===


[[ontap-systems-documentation]]
== Documentation des systèmes ONTAP

Pour configurer un système ONTAP, vous avez besoin des documents suivants pour votre version du système d'exploitation.

[cols="1,2"]
|===
| Nom | Description 


 a| 
Instructions d'installation et de configuration spécifiques à la manette
 a| 
Ce document décrit la procédure d'installation du matériel NetApp .



 a| 
link:https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9"^]
 a| 
Fournit des informations détaillées sur tous les aspects des versions ONTAP .



 a| 
link:https://hwu.netapp.com/["Hardware Universe"^]
 a| 
Permet de confirmer le matériel pris en charge, comme les commutateurs de cluster et les câbles, pour votre modèle de plateforme.

|===