---
permalink: switch-nvidia-sn2100/reset-switch-sn2100.html 
sidebar: sidebar 
keywords: SN2100 reset switch to factory defaults, SN2100 switches configuration, efos 
summary: Avant de configurer votre commutateur Cisco Nexus SN2100, consultez les informations suivantes. 
---
= Réinitialiser le commutateur de cluster SN2100 aux paramètres d'usine par défaut
:allow-uri-read: 


[role="lead"]
Pour réinitialiser le commutateur de cluster SN2100 aux paramètres d'usine :

* Pour Cumulus Linux 5.10 et versions antérieures, vous appliquez l'image Cumulus.
* Pour Cumulus Linux 5.11 et versions ultérieures, vous utilisez le `nv action reset system factory-default` commande.


.Description de la tâche
* Vous devez être connecté au commutateur à l'aide de la console série.
* Vous devez avoir le mot de passe root pour accéder aux commandes sudo.



NOTE: Pour plus d'informations sur l'installation de Cumulus Linux, consultezlink:configure-software-overview-sn2100-cluster.html["Workflow d'installation logicielle pour les switchs NVIDIA SN2100"] .

.Étapes
[role="tabbed-block"]
====
.Cumulus Linux 5.10 et versions antérieures
--
. Depuis la console Cumulus, téléchargez et mettez en file d'attente l'installation du logiciel du commutateur avec la commande `onie-install -a -i` suivi du chemin d'accès au fichier du logiciel du commutateur, par exemple :
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo onie-install -a -i http://<web-server>/<path>/cumulus-linux-5.10.0-mlx-amd64.bin*
----
. L'installateur démarre le téléchargement.  Tapez *y* lorsque vous êtes invité à confirmer l'installation lorsque l'image est téléchargée et vérifiée.
. Redémarrez le commutateur pour installer le nouveau logiciel.
+
`sudo reboot`

+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo reboot*
----
+

NOTE: Le commutateur redémarre et entre dans l'installation du logiciel du commutateur, ce qui prend un certain temps.  Une fois l'installation terminée, le commutateur redémarre et reste à l'état `log-in` rapide.



--
.Cumulus Linux 5.11 et versions ultérieures
--
. Pour réinitialiser le commutateur aux paramètres d'usine et supprimer tous les fichiers de configuration, les fichiers système et les fichiers journaux, exécutez :
+
`nv action reset system factory-default`

+
Par exemple :

+
[listing, subs="+quotes"]
----
cumulus@switch:~$ *nv action reset system factory-default*

This operation will reset the system configuration, delete the log files and reboot the switch.
Type [y] continue.
Type [n] to abort.
Do you want to continue? [y/n] *y*
----


Voir le NVIDIA https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-511/Installation-Management/Factory-Reset/["Réinitialisation d'usine"^] documentation pour plus de détails.

--
====