---
permalink: switch-nvidia-sn2100/setup-install-cshm-file.html 
sidebar: sidebar 
keywords: 'install, applicable, configuration, file, cluster, switch, health, monitor, ontap, install the cluster switch health monitor (csm) configuration file for SN2100 switches' 
summary: 'Vous pouvez utiliser cette procédure pour installer le fichier de configuration approprié pour la surveillance de l"état des commutateurs de cluster NVIDIA SN2100.' 
---
= Installez le fichier de configuration du moniteur d'état du commutateur Ethernet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour configurer la surveillance de l'état des commutateurs Ethernet sur les commutateurs Ethernet NVIDIA , suivez cette procédure.

Ces instructions s'appliquent si les commutateurs NVIDIA X190006-PE et X190006-PI ne sont pas correctement détectés, ce qui peut être vérifié en exécutant la commande suivante : `system switch ethernet show` et en vérifiant si la mention *AUTRE* apparaît pour votre modèle.  Pour identifier le modèle de votre commutateur NVIDIA , trouvez le numéro de pièce à l'aide de la commande `nv show platform hardware` pour NVIDIA CL 5.8 et versions antérieures ou `nv show platform` pour les versions ultérieures.

[NOTE]
====
Ces étapes sont également recommandées si vous souhaitez que la surveillance de l'état et la collecte des journaux fonctionnent comme prévu lors de l'utilisation de NVIDIA CL 5.11.x avec les versions ONTAP suivantes.  Bien que la surveillance de l'état de santé et la collecte des journaux puissent fonctionner sans ces étapes, leur respect garantit un fonctionnement correct.

* 9.10.1P20, 9.11.1P18, 9.12.1P16, 9.13.1P8, 9.14.1, 9.15.1 et les versions correctives ultérieures


====
.Avant de commencer
* Assurez-vous que le cluster ONTAP est opérationnel.
* Activez SSH sur le commutateur pour utiliser toutes les fonctionnalités disponibles dans CSHM.
* Effacer `/mroot/etc/cshm_nod/nod_sign/` répertoire sur tous les nœuds :
+
.. Entrez dans le shell du nœud :
+
`system node run -node <name>`

.. Passer aux privilèges avancés :
+
`priv set advanced`

.. Listez les fichiers de configuration dans le `/etc/cshm_nod/nod_sign` annuaire.  Si le répertoire existe et contient des fichiers de configuration, il affiche la liste des noms de fichiers.
+
`ls /etc/cshm_nod/nod_sign`

.. Supprimez tous les fichiers de configuration correspondant à vos modèles de commutateurs connectés.
+
En cas de doute, supprimez tous les fichiers de configuration des modèles pris en charge listés ci-dessus, puis téléchargez et installez les fichiers de configuration les plus récents pour ces mêmes modèles.

+
`rm /etc/cshm_nod/nod_sign/<filename>`

.. Vérifiez que les fichiers de configuration supprimés ne se trouvent plus dans le répertoire :
+
`ls /etc/cshm_nod/nod_sign`





.Étapes
. Téléchargez le fichier zip de configuration du moniteur d'état du commutateur Ethernet en fonction de la version ONTAP correspondante.  Ce fichier est disponible à partir de https://mysupport.netapp.com/site/info/nvidia-cluster-switch["Commutateurs Ethernet NVIDIA"^] page.
+
.. Sur la page de téléchargement du logiciel NVIDIA SN2100, sélectionnez *Fichier CSHM NVIDIA*.
.. Sur la page Attention/À lire absolument, cochez la case pour accepter.
.. Sur la page du contrat de licence utilisateur final, cochez la case pour accepter et cliquez sur *Accepter et continuer*.
.. Sur la page de téléchargement des fichiers CSHM Nvidia, sélectionnez le fichier de configuration approprié.  Les fichiers suivants sont disponibles :




[role="tabbed-block"]
====
.ONTAP 9.15.1 et versions ultérieures
--
* MSN2100-CB2FC-v1.4.zip
* MSN2100-CB2RC-v1.4.zip
* X190006-PE-v1.4.zip
* X190006-PI-v1.4.zip


--
.ONTAP 9.11.1 à 9.14.1
--
* MSN2100-CB2FC_PRIOR_R9.15.1-v1.4.zip
* MSN2100-CB2RC_PRIOR_R9.15.1-v1.4.zip
* X190006-PE_PRIOR_9.15.1-v1.4.zip
* X190006-PI_PRIOR_9.15.1-v1.4.zip


--
====
. [[étape 2]]Téléchargez le fichier zip approprié sur votre serveur Web interne.
. Accédez aux paramètres du mode avancé depuis l'un des systèmes ONTAP du cluster.
+
`set -privilege advanced`

. Exécutez la commande de configuration du moniteur d'état du commutateur.
+
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet configure-health-monitor*
----
. Vérifiez que la sortie de la commande se termine par le texte suivant pour votre version ONTAP :


[role="tabbed-block"]
====
.ONTAP 9.15.1 et versions ultérieures
--
Le fichier de configuration a été installé pour la surveillance de l'état du commutateur Ethernet.

--
.ONTAP 9.11.1 à 9.14.1
--
SHM a installé le fichier de configuration.

--
.ONTAP 9.10.1
--
Le package CSHM téléchargé a été traité avec succès.

--
====
En cas d'erreur, contactez le support NetApp .

. [[step6]]Attendez jusqu'à deux fois l'intervalle d'interrogation du moniteur d'état du commutateur Ethernet, déterminé en exécutant `system switch ethernet polling-interval show` , avant de passer à l'étape suivante.
. Exécutez la commande `system switch ethernet configure-health-monitor show` sur le système ONTAP et assurez-vous que les commutateurs du cluster sont détectés avec le champ surveillé défini sur *Vrai* et le champ du numéro de série n'affichant pas *Inconnu*.
+
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet configure-health-monitor show*
----



NOTE: Si votre modèle affiche toujours *AUTRE* après l'application du fichier de configuration, contactez le support NetApp .

Voir le https://docs.netapp.com/us-en/ontap-cli/system-switch-ethernet-configure-health-monitor.html["configuration-santé-surveillance du commutateur Ethernet du système"^] commande pour plus de détails.

.Quelle est la prochaine étape ?
Une fois le fichier CSHM installé, vous pouvezlink:../switch-cshm/config-overview.html["configurer la surveillance de l'état du commutateur"] .
