---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-storage/components-9336c-storage.html 
keywords: shared storage cluster switch 
summary: 'À partir d" ONTAP 9.9.1, vous pouvez utiliser les commutateurs Cisco Nexus 9336C-FX2 pour combiner les fonctionnalités de stockage et de cluster dans un scénario de commutateur partagé.' 
---
= Composants et références des commutateurs de stockage Cisco Nexus 9336C-FX2 et 9336C-FX2-T
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour l'installation et la maintenance des commutateurs de stockage Cisco Nexus 9336C-FX2 et 9336C-FX2-T, assurez-vous de consulter la liste des composants et des numéros de pièces.

Le tableau suivant répertorie le numéro de pièce et la description des commutateurs de stockage, des ventilateurs et des alimentations 9336C-FX2 et 9336C-FX2-T :

[cols="1,2"]
|===
| Numéro de pièce | Description 


 a| 
X190200-CS-PE
 a| 
Commutateur de grappe, N9336C 36 points PTSX 10/25/40/100G



 a| 
X190200-CS-PI
 a| 
Commutateur de cluster, N9336C 36 broches PSIN 10/25/40/100G



 a| 
X190212-CS-PE
 a| 
Commutateur de groupe, N9336C 12 points (9336C-FX2-T) PTSX 10/25/40/100G



 a| 
X190212-CS-PI
 a| 
Commutateur de cluster, N9336C 12 broches (9336C-FX2-T) PSIN 10/25/40/100G



 a| 
SW-N9K-FX2-24P-UPG
 a| 
Licence SW Cisco 9336CFX2 POD 24 ports



 a| 
X190210-FE-PE
 a| 
N9K-9336C, ETP, PTSX, 36PT 10/25/40/100GQSFP28



 a| 
X190210-FE-PI
 a| 
N9K-9336C, ETP, PSIN, 36PT 10/25/40/100GQSFP28



 a| 
X190002
 a| 
Kit d'accessoires X190001/X190003



 a| 
X-NXA-PAC-1100W-PE2
 a| 
Alimentation N9K-9336C AC 1100W - Sortie d'air latérale



 a| 
X-NXA-PAC-1100W-PI2
 a| 
Alimentation N9K-9336C AC 1100W - Entrée d'air côté port



 a| 
X-NXA-FAN-65CFM-PE
 a| 
N9K-9336C 65 CFM, débit d'air d'échappement côté bâbord



 a| 
X-NXA-FAN-65CFM-PI
 a| 
N9K-9336C 65 CFM, débit d'air d'admission côté bâbord

|===


== Licences Cisco Smart pour les ports 9336C-FX2-T uniquement

Pour activer plus de 12 ports sur votre commutateur de stockage Cisco Nexus 9336C-FX-T, vous devez acheter une licence Cisco Smart.  Les licences Cisco Smart sont gérées via des comptes Cisco Smart.

. Créez un nouveau compte Smart, si nécessaire. Voir https://id.cisco.com/signin/register["Créer un nouveau compte Smart"^] pour plus de détails.
. Demander l'accès à un compte Smart existant. Voir https://id.cisco.com/oauth2/default/v1/authorize?response_type=code&scope=openid%20profile%20address%20offline_access%20cci_coimemberOf%20email&client_id=cae-okta-web-gslb-01&state=s2wvKDiBja__7ylXonWrq8w-FAA&redirect_uri=https%3A%2F%2Frpfa.cloudapps.cisco.com%2Fcb%2Fsso&nonce=qO6s3cZE5ZdhC8UKMEfgE6fbu3mvDJ8PTw5jYOp6z30["Demander l'accès à un compte Smart existant"^] pour plus de détails.



NOTE: Une fois votre licence Smart achetée, installez le RCF approprié pour activer et configurer les 36 ports disponibles.

.Quelle est la prochaine étape
Une fois que vous avez confirmé vos composants et leurs références, vous pouvez consulter le link:required-documentation-9336c-storage.html["documentation requise"].
