---
permalink: switch-cisco-9336c-fx2-storage/configure-switch-overview-9336c-storage.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch 
summary: 'Présentation de l"installation et de la configuration des commutateurs de stockage Cisco Nexus 9336C-FX2' 
---
= Présentation de l'installation et de la configuration des commutateurs de stockage Cisco Nexus 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le commutateur de stockage Cisco Nexus 9336C-FX2 fait partie de la plateforme Cisco Nexus 9000 et peut être installé dans une armoire système NetApp. Les commutateurs de stockage vous permettent d'acheminer des données entre les serveurs et les baies de stockage d'un réseau de stockage (SAN).



== Présentation de la configuration initiale

Pour configurer initialement un commutateur Cisco Nexus 9336C-FX2 sur les systèmes exécutant ONTAP, procédez comme suit :

. link:setup-worksheet-9336c-storage.html["Remplir la fiche de câblage"].
. link:install-9336c-storage.html["Poser le commutateur"].
. link:setup-switch-9336c-storage.html["Configurer le commutateur"].
. link:install-switch-and-passthrough-panel-9336c-storage.html["Installez le commutateur dans l'armoire NetApp"].
+
En fonction de votre configuration, vous pouvez installer le commutateur Cisco Nexus 9336C-FX2 et le panneau d'intercommunication dans une armoire NetApp avec les supports standard inclus avec le commutateur.

. link:install-nxos-overview-9336c-storage.html["Préparez-vous à installer NX-OS et RCF"].
. link:install-nxos-software-9336c-storage.html["Installez le logiciel NX-OS"].
. link:install-nxos-rcf-9336c-storage.html["Installez le fichier de configuration RCF"].
+
Installer le FCR après avoir configuré pour la première fois le commutateur Nexus 9336C-FX2. Vous pouvez également utiliser cette procédure pour mettre à niveau votre version RCF.





== Informations supplémentaires

Avant de commencer l'installation ou la maintenance, vérifiez les points suivants :

* link:configure-reqs-9336c-storage.html["Configuration requise"]
* link:components-9336c-storage.html["Composants et références"]
* link:required-documentation-9336c-storage.html["Documentation requise"]
* link:smart-call-9336c-storage.html["Configuration requise pour le service d'appel intelligent"]

