---
permalink: switch-cisco-9336c-fx2-storage/configure-switch-overview-9336c-storage.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch 
summary: 'Présentation de l"installation et de la configuration des commutateurs de stockage Cisco Nexus 9336C-FX2' 
---
= Présentation de l'installation et de la configuration des commutateurs de stockage Cisco Nexus 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le commutateur Cisco Nexus 9336C-FX2 fait partie de la plateforme Cisco Nexus 9000 et peut être installé dans une armoire système NetApp. Le Nexus 9336C-FX2 est un commutateur Ethernet qui permet de basculer les données entre les contrôleurs et les tiroirs disques.



== Présentation de la configuration initiale

Pour configurer initialement un commutateur Cisco Nexus 9336C-FX2 sur les systèmes exécutant ONTAP, procédez comme suit :

. link:setup-worksheet-9336c-storage.html["Remplir la fiche de câblage"].
. link:install-9336c-storage.html["Poser le commutateur"].
. link:setup-switch-9336c-storage.html["Configurer le commutateur"].
. link:install-switch-and-passthrough-panel-9336c-storage.html["Installer le commutateur dans une armoire NetApp"].
. link:install-nxos-overview-9336c-storage.html["Préparez-vous à installer NX-OS et RCF"].
. link:install-nxos-software-9336c-storage.html["Installez le logiciel NX-OS"].
. link:install-rcf-software-9336c-storage.html["Installez le fichier de configuration RCF"].




== Informations supplémentaires

Avant de commencer l'installation ou la maintenance, vérifiez les points suivants :

* link:configure-reqs-9336c-storage.html["Configuration requise"]
* link:components-9336c-storage.html["Composants et références"]
* link:required-documentation-9336c-storage.html["Documentation requise"]
* link:smart-call-9336c-storage.html["Configuration requise pour le service d'appel intelligent"]

