---
permalink: switch-cisco-9336c-fx2-storage/configure-software-overview-9336c-storage.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch 
summary: Présentation de la configuration logicielle des commutateurs de stockage Cisco Nexus 9336C-FX2 
---
= Workflow d'installation du logiciel pour les commutateurs de stockage Cisco Nexus 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour installer et configurer le logiciel d'un commutateur de stockage Cisco Nexus 9336C-FX2, effectuez la procédure suivante :

. link:install-nxos-overview-9336c-storage.html["Préparez l'installation ou la mise à niveau de NX-OS et RCF"].
+
Le logiciel Cisco NX-OS et les fichiers RCF (Reference Configuration Files) doivent être installés sur les switchs de stockage Cisco Nexus 9336C-FX2.

. link:install-nxos-software-9336c-storage.html["Installez ou mettez à niveau le logiciel NX-OS"].
+
Téléchargez et installez ou mettez à niveau le logiciel NX-OS sur le commutateur de stockage Cisco Nexus 9336C-FX2.

. link:install-rcf-software-9336c-storage.html["Installez ou mettez à niveau le fichier de configuration RCF"].
+
Installez ou mettez à niveau le fichier RCF après avoir configuré pour la première fois le switch de stockage Cisco Nexus 9336C-FX2. Vous pouvez également utiliser cette procédure pour mettre à niveau votre version RCF.


