---
permalink: switch-cisco-9336c-fx2-storage/install-9336c-storage.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, storage, management, network, switches, set up the switches - cisco nexus 9336c-fx2 
summary: Si vous ne disposez pas déjà des informations de configuration et de la documentation requises, vous devez rassembler ces informations avant de configurer vos commutateurs réseau de stockage et de gestion. 
---
= Installer les commutateurs de stockage 9336C-FX2 et 9336C-FX2-T
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez cette procédure pour installer les commutateurs de stockage Cisco Nexus 9336C-FX2 et 9336C-FX2-T.

.Avant de commencer
Assurez-vous d'avoir les éléments suivants :

* Accès à un serveur HTTP, FTP ou TFTP sur le site d'installation pour télécharger les versions NX-OS et le fichier de configuration de référence (RCF) applicables.
* Version NX-OS applicable, téléchargée depuis https://software.cisco.com/download/home["Téléchargement de logiciels Cisco"^] page.
* Licences applicables, informations sur le réseau et la configuration, et câbles.
* Complétélink:setup-worksheet-9336c-storage.html["fiches de câblage"] .
* Fichiers RCF de réseau de stockage et de gestion NetApp applicables téléchargés depuis le site de support NetApp à  http://mysupport.netapp.com/["monsupport.netapp.com"^].
+
Tous les commutateurs de réseau de stockage et de gestion Cisco sont livrés avec la configuration d'usine standard Cisco. Ces commutateurs disposent également de la version actuelle du logiciel NX-OS, mais les RCF ne sont pas chargés.

* Documentation requise pour le commutateur. Voirlink:required-documentation-9336c-storage.html["Documents requis"] pour plus d'informations.


.Étapes
. Installez les commutateurs réseau et de gestion ainsi que les contrôleurs.
+
[cols="1,2"]
|===
| Si vous installez votre... | Alors... 


 a| 
Cisco Nexus 9336C-FX2 dans une armoire système NetApp
 a| 
Voirlink:install-switch-and-passthrough-panel-9336c-storage.html["Installer le commutateur dans l'armoire NetApp"] pour obtenir les instructions d'installation du commutateur dans une armoire NetApp .



 a| 
Équipement dans une baie de télécommunications
 a| 
Consultez les procédures fournies dans les guides d'installation du matériel de commutation et les instructions d'installation et de configuration de NetApp .

|===
. Câblez les commutateurs réseau et de gestion aux contrôleurs en utilisant les feuilles de câblage complétées.
. Mettez sous tension les commutateurs réseau, les commutateurs du réseau de gestion et les contrôleurs.


.Quelle est la prochaine étape ?
Vous pouvez, si vous le souhaitez, link:install-switch-and-passthrough-panel-9336c-storage.html["installer un commutateur Cisco Nexus 9336C-FX2 dans une armoire NetApp"]. Sinon, allez à link:setup-switch-9336c-storage.html["configurer le commutateur"].
