---
permalink: switch-cisco-9336c-fx2-storage/install-rcf-software-9336c-storage.html 
sidebar: sidebar 
keywords: install rcf, cisco switches, storage 
summary: Vous pouvez installer le RCF après avoir configuré pour la première fois le commutateur de stockage Nexus 9336C-FX2. Vous pouvez également utiliser cette procédure pour mettre à niveau votre version RCF. 
---
= Installez le fichier de configuration de référence
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous installez le fichier de configuration de référence (RCF) après avoir configuré les commutateurs de stockage Nexus 9336C-FX2 et 9336C-FX2-T pour la première fois.

Consultez l'article de la base de connaissanceslink:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Comment effacer la configuration d'un commutateur d'interconnexion Cisco tout en conservant la connectivité à distance"^] pour plus d'informations lors de l'installation de votre RCF.

.Avant de commencer
Vérifiez les installations et connexions suivantes :

* Une connexion console au commutateur.  La connexion à la console est facultative si vous disposez d'un accès distant au commutateur.
* Les commutateurs s1 et s2 sont mis sous tension et la configuration initiale du commutateur est terminée (l'adresse IP de gestion et SSH sont configurés).
* La version NX-OS souhaitée a été installée.
* Les ports de stockage du nœud ONTAP et les ports des baies de stockage ne sont pas connectés.




== Étape 1 : Installez le RCF sur les commutateurs

. Connectez-vous au commutateur s2 à l'aide de SSH ou d'une console série.
. Copiez le RCF dans la bootflash du switch s2 en utilisant l'un des protocoles de transfert suivants : FTP, TFTP, SFTP ou SCP.
+
Pour plus d'informations sur les commandes Cisco , consultez le guide approprié dans le https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Guide de référence des commandes NX-OS Cisco Nexus série 9000"^] .

+
.Afficher un exemple
[%collapsible]
====
Cet exemple montre TFTP utilisé pour copier un RCF dans la bootflash sur le commutateur s2 :

[listing, subs="+quotes"]
----
s2# *copy tftp: bootflash: vrf management*
Enter source filename: *NX9336C-FX2-RCF-v1.13-1-Storage.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. Appliquez le RCF précédemment téléchargé à la mémoire flash de démarrage.
+
Pour plus d'informations sur les commandes Cisco , consultez le guide approprié dans le https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Guide de référence des commandes NX-OS Cisco Nexus série 9000"^] .

+
.Afficher un exemple
[%collapsible]
====
Cet exemple montre le RCF `NX9336C-FX2-RCF-v1.13-1-Storage.txt` en cours d'installation sur le commutateur s2 :

[listing]
----
s2# copy NX9336C-FX2-RCF-v1.13-1-Storage.txt running-config echo-commands
----
====
. Examinez la sortie de la bannière à partir de `show banner motd` commande.  Vous devez lire et suivre ces instructions pour garantir la configuration et le fonctionnement corrects du commutateur.
+
.Afficher un exemple
[%collapsible]
====
[listing]
----
s2# show banner motd

**********************************************************
* NetApp Reference Configuration File (RCF)
*
* Switch    : NX9336C-FX2
* Filename  : NX9336C-FX2-RCF-v1.13-1-Storage.txt
* Date      : 05-22-2025
* Version   : v1.13
*
* Port Usage : Storage configuration
* Ports  1-36: 100GbE Controller and Shelf Storage Ports
*
* IMPORTANT NOTES
*
* Interface port-channel999 is reserved to identify the version of this file.
**********************************************************
----
====
. Vérifiez que le RCF est bien la version la plus récente correcte :
+
`show running-config`

+
Lorsque vous vérifiez le résultat pour vous assurer que vous avez le RCF correct, vérifiez que les informations suivantes sont correctes :

+
** La bannière RCF
** Paramètres du nœud et du port
** Personnalisations
+
Le résultat varie en fonction de la configuration de votre site.  Vérifiez les paramètres du port et consultez les notes de version pour connaître les modifications spécifiques à la version de RCF que vous avez installée.



. Enregistrez tout ajout personnalisé entre les éléments actuels `running-config` fichier et le fichier RCF utilisé.
. Après avoir vérifié que les versions RCF et les paramètres du commutateur sont corrects, copiez le `running-config` fichier au `startup-config` déposer.
+
[listing]
----
s2# copy running-config startup-config [########################################] 100% Copy complete
----
. Redémarrez le switch s2.
+
`s2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Répétez les étapes 1 à 8 sur le commutateur s1.
. Connectez les ports de stockage des nœuds et les ports des baies de stockage de tous les nœuds dans le cluster ONTAP aux commutateurs s1 et s2.




== Étape 2 : Vérifier les connexions du commutateur

. Vérifiez que les ports du commutateur sont *up*.
+
`show interface brief`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
s1# *show interface brief | grep up*
mgmt0  --           up     _<mgmt ip address>_                       1000    1500
Eth1/11         1       eth  trunk  up      none                     100G(D) --
Eth1/12         1       eth  trunk  up      none                     100G(D) --
Eth1/13         1       eth  trunk  up      none                     100G(D) --
Eth1/14         1       eth  trunk  up      none                     100G(D) --
Eth1/15         1       eth  trunk  up      none                     100G(D) --
Eth1/16         1       eth  trunk  up      none                     100G(D) --
Eth1/17         1       eth  trunk  up      none                     100G(D) --
Eth1/18         1       eth  trunk  up      none                     100G(D) --
Eth1/23         1       eth  trunk  up      none                     100G(D) --
Eth1/24         1       eth  trunk  up      none                     100G(D) --
Eth1/25         1       eth  trunk  up      none                     100G(D) --
Eth1/26         1       eth  trunk  up      none                     100G(D) --
Eth1/27         1       eth  trunk  up      none                     100G(D) --
Eth1/28         1       eth  trunk  up      none                     100G(D) --
Eth1/29         1       eth  trunk  up      none                     100G(D) --
Eth1/30         1       eth  trunk  up      none                     100G(D) --
----
====
. Vérifiez que les ports de stockage du nœud et les ports du châssis de stockage se trouvent dans leurs VLAN corrects à l'aide des commandes suivantes :
+
`show vlan brief`

+
`show interface trunk`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
s1# *show vlan brief*

VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Po999
30   VLAN0030                         active    Eth1/1, Eth1/2, Eth1/3, Eth1/4
                                                Eth1/5, Eth1/6, Eth1/7, Eth1/8
                                                Eth1/9, Eth1/10, Eth1/11
                                                Eth1/12, Eth1/13, Eth1/14
                                                Eth1/15, Eth1/16, Eth1/17
                                                Eth1/18, Eth1/19, Eth1/20
                                                Eth1/21, Eth1/22, Eth1/23
                                                Eth1/24, Eth1/25, Eth1/26
                                                Eth1/27, Eth1/28, Eth1/29
                                                Eth1/30, Eth1/31, Eth1/32
                                                Eth1/33, Eth1/34, Eth1/35
                                                Eth1/36

s1# *show interface trunk*

-----------------------------------------------------
Port          Native  Status        Port
              Vlan                  Channel
-----------------------------------------------------
Eth1/1        1       trunking      --
Eth1/2        1       trunking      --
Eth1/3        1       trunking      --
Eth1/4        1       trunking      --
Eth1/5        1       trunking      --
Eth1/6        1       trunking      --
Eth1/7        1       trunking      --
Eth1/8        1       trunking      --
Eth1/9        1       trunking      --
Eth1/10       1       trunking      --
Eth1/11       1       trunking      --
Eth1/12       1       trunking      --
Eth1/13       1       trunking      --
Eth1/14       1       trunking      --
Eth1/15       1       trunking      --
Eth1/16       1       trunking      --
Eth1/17       1       trunking      --
Eth1/18       1       trunking      --
Eth1/19       1       trunking      --
Eth1/20       1       trunking      --
Eth1/21       1       trunking      --
Eth1/22       1       trunking      --
Eth1/23       1       trunking      --
Eth1/24       1       trunking      --
Eth1/25       1       trunking      --
Eth1/26       1       trunking      --
Eth1/27       1       trunking      --
Eth1/28       1       trunking      --
Eth1/29       1       trunking      --
Eth1/30       1       trunking      --
Eth1/31       1       trunking      --
Eth1/32       1       trunking      --
Eth1/33       1       trunking      --
Eth1/34       1       trunking      --
Eth1/35       1       trunking      --
Eth1/36       1       trunking      --

--------------------------------------------------------------------------------
Port          Vlans Allowed on Trunk
--------------------------------------------------------------------------------
Eth1/1        30
Eth1/2        30
Eth1/3        30
Eth1/4        30
Eth1/5        30
Eth1/6        30
Eth1/7        30
Eth1/8        30
Eth1/9        30
Eth1/10       30
Eth1/11       30
Eth1/12       30
Eth1/13       30
Eth1/14       30
Eth1/15       30
Eth1/16       30
Eth1/17       30
Eth1/18       30
Eth1/19       30
Eth1/20       30
Eth1/21       30
Eth1/22       30
Eth1/23       30
Eth1/24       30
Eth1/25       30
Eth1/26       30
Eth1/27       30
Eth1/28       30
Eth1/29       30
Eth1/30       30
Eth1/31       30
Eth1/32       30
Eth1/33       30
Eth1/34       30
Eth1/35       30
Eth1/36       30

--------------------------------------------------------------------------------
Port          Vlans Err-disabled on Trunk
--------------------------------------------------------------------------------
Eth1/1        none
Eth1/2        none
Eth1/3        none
Eth1/4        none
Eth1/5        none
Eth1/6        none
Eth1/7        none
Eth1/8        none
Eth1/9        none
Eth1/10       none
Eth1/11       none
Eth1/12       none
Eth1/13       none
Eth1/14       none
Eth1/15       none
Eth1/16       none
Eth1/17       none
Eth1/18       none
Eth1/19       none
Eth1/20       none
Eth1/21       none
Eth1/22       none
Eth1/23       none
Eth1/24       none
Eth1/25       none
Eth1/26       none
Eth1/27       none
Eth1/28       none
Eth1/29       none
Eth1/30       none
Eth1/31       none
Eth1/32       none
Eth1/33       none
Eth1/34       none
Eth1/35       none
Eth1/36       none

--------------------------------------------------------------------------------
Port          STP Forwarding
--------------------------------------------------------------------------------
Eth1/1        none
Eth1/2        none
Eth1/3        none
Eth1/4        none
Eth1/5        none
Eth1/6        none
Eth1/7        none
Eth1/8        none
Eth1/9        none
Eth1/10       none
Eth1/11       30
Eth1/12       30
Eth1/13       30
Eth1/14       30
Eth1/15       30
Eth1/16       30
Eth1/17       30
Eth1/18       30
Eth1/19       none
Eth1/20       none
Eth1/21       none
Eth1/22       none
Eth1/23       30
Eth1/24       30
Eth1/25       30
Eth1/26       30
Eth1/27       30
Eth1/28       30
Eth1/29       30
Eth1/30       30
Eth1/31       none
Eth1/32       none
Eth1/33       none
Eth1/34       none
Eth1/35       none
Eth1/36       none

--------------------------------------------------------------------------------
Port          Vlans in spanning tree forwarding state and not pruned
--------------------------------------------------------------------------------
Eth1/1        Feature VTP is not enabled
none
Eth1/2        Feature VTP is not enabled
none
Eth1/3        Feature VTP is not enabled
none
Eth1/4        Feature VTP is not enabled
none
Eth1/5        Feature VTP is not enabled
none
Eth1/6        Feature VTP is not enabled
none
Eth1/7        Feature VTP is not enabled
none
Eth1/8        Feature VTP is not enabled
none
Eth1/9        Feature VTP is not enabled
none
Eth1/10       Feature VTP is not enabled
none
Eth1/11       Feature VTP is not enabled
30
Eth1/12       Feature VTP is not enabled
30
Eth1/13       Feature VTP is not enabled
30
Eth1/14       Feature VTP is not enabled
30
Eth1/15       Feature VTP is not enabled
30
Eth1/16       Feature VTP is not enabled
30
Eth1/17       Feature VTP is not enabled
30
Eth1/18       Feature VTP is not enabled
30
Eth1/19       Feature VTP is not enabled
none
Eth1/20       Feature VTP is not enabled
none
Eth1/21       Feature VTP is not enabled
none
Eth1/22       Feature VTP is not enabled
none
Eth1/23       Feature VTP is not enabled
30
Eth1/24       Feature VTP is not enabled
30
Eth1/25       Feature VTP is not enabled
30
Eth1/26       Feature VTP is not enabled
30
Eth1/27       Feature VTP is not enabled
30
Eth1/28       Feature VTP is not enabled
30
Eth1/29       Feature VTP is not enabled
30
Eth1/30       Feature VTP is not enabled
30
Eth1/31       Feature VTP is not enabled
none
Eth1/32       Feature VTP is not enabled
none
Eth1/33       Feature VTP is not enabled
none
Eth1/34       Feature VTP is not enabled
none
Eth1/35       Feature VTP is not enabled
none
Eth1/36       Feature VTP is not enabled
none
----
====
+

NOTE: Pour plus de détails sur l'utilisation des ports et des VLAN, reportez-vous à la section bannière et notes importantes de votre RCF.





== Étape 3 : Configurez votre cluster ONTAP

NetApp recommande d'utiliser System Manager pour configurer de nouveaux clusters.

System Manager offre un flux de travail simple et facile pour la configuration et l'installation du cluster, notamment l'attribution d'une adresse IP de gestion de nœud, l'initialisation du cluster, la création d'un niveau local, la configuration des protocoles et la mise en service du stockage initial.

Allez à https://docs.netapp.com/us-en/ontap/task_configure_ontap.html["Configurer ONTAP sur un nouveau cluster avec System Manager"] pour les instructions d'installation.

.Quelle est la prochaine étape ?
Une fois votre RCF installé, vous pouvezlink:configure-ssh-keys.html["vérifier la configuration SSH"]
