---
permalink: switch-cisco-9336c-fx2-storage/install-nxos-overview-9336c-storage.html 
sidebar: sidebar 
keywords: cisco, nx-os, software, reference, configuration, file, rcf, install, fx2, cluster, switch, install nx-os software and rcfs on cisco nexus 9336-fx2 cluster switches - cisco nexus 9336x-fx2 
summary: 'Le logiciel Cisco NX-OS et les fichiers de configuration de référence (RCF) doivent être installés sur les commutateurs de cluster Cisco Nexus 9336C-FX2.' 
---
= Préparez-vous à installer ou à mettre à niveau le logiciel NX-OS et RCF.
:allow-uri-read: 


[role="lead"]
Avant d’installer le logiciel NX-OS et le fichier de configuration de référence (RCF), suivez cette procédure.

.À propos des exemples
Les exemples de cette procédure utilisent la nomenclature suivante pour les commutateurs et les nœuds :

* Les noms des deux commutateurs Cisco sont s1 et s2.
* Les noms des nœuds sont cluster1-01 et cluster1-02.


.À propos de cette tâche
La procédure nécessite l'utilisation des commandes ONTAP et des commandes des commutateurs Cisco Nexus série 9000 ; les commandes ONTAP sont utilisées sauf indication contraire.

.Étapes
. Si AutoSupport est activé, supprimez la création automatique de cas en envoyant un message AutoSupport : `system node autosupport invoke -node * -type all -message MAINT=xh`
+
où x représente la durée de la fenêtre de maintenance en heures.

+

NOTE: Le message AutoSupport notifie le support technique de cette tâche de maintenance afin que la création automatique de tickets soit désactivée pendant la période de maintenance.

. Passez au niveau de privilège avancé en saisissant *y* lorsque vous êtes invité à continuer :
+
[source, cli]
----
set -privilege advanced
----
+
L'invite avancée(`*>` ) apparaît.

. Afficher combien d'interfaces sont configurées dans chaque nœud pour chaque commutateur :
+
[source, cli]
----
network device-discovery show -protocol lldp
----
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-02/lldp
            e5a    s1                        Eth1/2            N9K-C9336C
            e3b    s2                        Eth1/2            N9K-C9336C
cluster1-01/lldp
            e5a    s1                        Eth1/1            N9K-C9336C
            e3b    s2                        Eth1/1            N9K-C9336C
.
.
----
====
. Vérifiez l'état administratif ou opérationnel de chaque port de stockage de nœud et de chaque port de baie de stockage.
+
.. Afficher les attributs du port de stockage du nœud :
+
[source, cli]
----
storage port show
----
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
cluster1-02

               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -

.
.
----
====
.. Afficher les attributs du port du shelf de stockage :
+
[source, cli]
----
storage shelf port show
----
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. Vérifiez que la surveillance de l'état du commutateur (CSHM) est activée pour le commutateur afin que les commutateurs soient surveillés :
+
[source, cli]
----
system switch ethernet show
----
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet show*
  Switch            Type               Address          Model
  ----------------- ------------------ ---------------- ---------------
  s1                storage-network    1.2.3.4          N9K-C9336C-FX2
     Serial Number: FFFXXXXXXX1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2                storage-network    2.3.4.5          N9K-C9336C-FX2
     Serial Number: FEEXXXXXXX2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====




.Quelle est la prochaine étape ?
Une fois que vous avez préparé l'installation du logiciel NX-OS et de RCF, vous pouvez link:install-nxos-software-9336c-storage.html["installer ou mettre à niveau le logiciel NX-OS"].
