---
sidebar: sidebar 
permalink: switch-cisco-9336c-shared/9336c_install_nx-os_software_and_reference_configuration_files_@rcfs@.html 
keywords: rcfs, nx-os, install 
summary:  
---
= Installer le logiciel NX-OS et les fichiers RCFs (Reference Configuration Files)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/




==== Installez le logiciel NX-OS et RCF sur un commutateur de cluster Cisco Nexus 9336C- FX2

Le logiciel Cisco NX-OS et le fichier RCF (Reference Configuration File) doivent être installés sur les commutateurs de cluster Cisco Nexus 9336C-FX2.

.Avant de commencer
Les conditions suivantes doivent être réunies avant d'installer le logiciel NX-OS et RCF sur le commutateur de cluster :

* Le cluster doit fonctionner parfaitement (il ne doit y avoir aucune erreur dans les journaux ou d'autres problèmes similaires).
* Vous devez avoir vérifié ou défini la configuration de démarrage souhaitée dans la FCR pour qu'elle reflète les images de démarrage souhaitées si vous installez uniquement NX-OS et que vous gardez la version actuelle de RCF.
* Si vous devez modifier la configuration de démarrage pour qu'elle reflète les images de démarrage actuelles, vous devez le faire avant de réappliquer la FCR de sorte que la version correcte soit instanciée lors des prochains redémarrages.
* Vous devez disposer d'une connexion de console au commutateur, obligatoire lors de l'installation de la FCR.
* Vous devez avoir consulté le tableau de compatibilité des commutateurs sur la page des switchs Ethernet Cisco pour les versions ONTAP, NX-OS et RCF prises en charge. Voir https://["Commutateurs Ethernet Cisco"] pour en savoir plus.
* Il peut y avoir des dépendances de commande entre la syntaxe de la commande dans la FCR et celle trouvée dans les versions de NX-OS.
* Vous devez vous être référé aux guides de mise à niveau et de logiciels appropriés disponibles sur le site Web de Cisco pour obtenir une documentation complète sur les procédures de mise à niveau et de mise à niveau des commutateurs Cisco Nexus 9000 Series. Voir https://["Commutateurs Cisco Nexus 9000 Series"] pour en savoir plus.
* Vous devez avoir la FCR actuelle.




===== Configuration initiale

Les exemples de cette procédure utilisent deux nœuds. Ces nœuds utilisent deux ports d'interconnexion de cluster 100 GbE e3a et e3b, comme par contrôleur A400. Voir la https://["Hardware Universe"] pour vérifier les ports de cluster appropriés sur vos plates-formes.


NOTE: Les sorties de la commande peuvent varier en fonction des différentes versions d'ONTAP.

Les exemples de cette procédure utilisent la nomenclature des commutateurs et des nœuds suivante :

* Les noms des deux commutateurs Cisco sont _cs1_ et _cs2_.
* Les noms de nœud sont _cluster1-01_ et _cluster1-02_.
* Les noms de LIF de cluster sont _cluster1-01_clum1_ et _cluster1-01_clus2_ pour cluster1-01 et _cluster1-02_clum1_ et _cluster1-02_clum2_ pour cluster1-02.
* L'invite cluster1:*> indique le nom du cluster.



NOTE: La procédure nécessite l'utilisation des commandes ONTAP et des commutateurs Cisco Nexus 9000 ; les commandes ONTAP sont utilisées sauf indication contraire.

.Étapes
. [[step1]]si AutoSupport est activé sur ce cluster, supprimez la création automatique de dossiers en invoquant un message AutoSupport : `system node autosupport invoke -node * -type all -message MAINT=x h`
+
Où x représente la durée de la fenêtre de maintenance en heures.



. [[step2]]définissez le niveau de privilège sur avancé, en entrant y lorsque vous êtes invité à continuer :
`set -privilege advanced`
+
L'invite avancée (*>) apparaît.

. [[step3]]affiche le nombre d'interfaces d'interconnexion de cluster configurées dans chaque nœud pour chaque commutateur d'interconnexion de cluster :
`network device-discovery show -protocol cdp`


[listing]
----
cluster1:: network device-discovery show -protocol cdp
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-02/cdp
            e3a    cs1                       Eth1/2            N9K-C9336C
            e3b    cs2                       Eth1/2            N9K-C9336C
cluster1-01/cdp
            e3a    cs1                       Eth1/1            N9K-C9336C
            e3b    cs2                       Eth1/1            N9K-C9336C
4 entries were displayed.
----
. [[step4]]Vérifiez le statut administratif ou opérationnel de chaque interface de cluster :
+
.. Afficher les attributs des ports réseau :
`network port show –ipspace Cluster`




[listing]
----
cluster1::*> network port show -ipspace Cluster
Node: cluster1-02
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy

Node: cluster1-01
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy
4 entries were displayed.

----
. Afficher les informations relatives aux LIFs :
`network interface show - vserver Cluster`


[listing]
----
cluster1::*> network interface show -vserver Cluster
        Logical            Status     Network            Current    Current Is
Vserver Interface          Admin/Oper Address/Mask       Node        Port   Home
------- ------------------ ---------- ------------------ ----------- ------ ----
Cluster
        cluster1-01_clus1  up/up      169.254.209.69/16  cluster1-01  e3a   true
        cluster1-01_clus2  up/up      169.254.49.125/16  cluster1-01  e3b   true
        cluster1-02_clus1  up/up      169.254.47.194/16  cluster1-02  e3a   true
        cluster1-02_clus2  up/up      169.254.19.183/16  cluster1-02  e3b   true
4 entries were displayed.
----
. [[step5]]Envoyez un ping aux LIF de cluster distantes :
`cluster ping-cluster -node node-name`


[listing]
----
cluster1::*> cluster ping-cluster -node cluster1-02
Host is cluster1-02
Getting addresses from network interface table...
Cluster cluster1-01_clus1 169.254.209.69 cluster1-01     e3a
Cluster cluster1-01_clus2 169.254.49.125 cluster1-01     e3b
Cluster cluster1-02_clus1 169.254.47.194 cluster1-02     e3a
Cluster cluster1-02_clus2 169.254.19.183 cluster1-02     e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)

Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
. [[step6]]Vérifiez que la commande auto-revert est activée sur toutes les LIFs du cluster :
`network interface show - vserver Cluster -fields auto-revert`


[listing]
----
cluster1::*> network interface show -vserver Cluster -fields auto-revert
          Logical
Vserver   Interface            Auto-revert
--------- ––––––-------------- ------------
Cluster
          cluster1-01_clus1    true
          cluster1-01_clus2    true
          cluster1-02_clus1    true
          cluster1-02_clus2    true
4 entries were displayed.
----
. [[step7]]activez la fonction de collecte des journaux du moniteur d'intégrité des commutateurs Ethernet pour la collecte des fichiers journaux relatifs aux commutateurs, à l'aide des commandes suivantes :
+
** `system switch ethernet log setup-password`
** `system switch ethernet log enable-collection`




[listing]
----
cluster1::*> system switch ethernet log setup password
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
cs1
cs2
cluster1::*> system switch ethernet log setup-password
Enter the switch name: cs1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y
Enter the password: <enter switch password>
Enter the password again: <enter switch password>
cluster1::*> system switch ethernet log setup-password
Enter the switch name: cs2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y
Enter the password: <enter switch password>
Enter the password again: <enter switch password>
cluster1::*> system  switch ethernet log enable-collection
Do you want to enable cluster log collection for all nodes in the cluster? {y|n}: [n] y
Enabling cluster switch log collection.
cluster1::*>
----

NOTE: Si l'une de ces commandes renvoie une erreur, contactez le support NetApp.



==== Installez le logiciel NX-OS sur un commutateur de cluster Cisco Nexus 9336C- FX2

Vous pouvez utiliser cette procédure pour installer le logiciel NX-OS sur le commutateur de cluster Cisco Nexus 9336C-FX2.

.Étapes
. [[step1]]Connectez le commutateur de cluster au réseau de gestion.
. [[step2]]utilisez le `ping` Commande permettant de vérifier la connectivité au serveur hébergeant le logiciel NX-OS et le FCR.
+
Cet exemple vérifie que le commutateur peut atteindre le serveur à l'adresse IP `172.19.2.1`:



[listing]
----
cs2# ping 172.19.2.1
Pinging 172.19.2.1 with 0 bytes of data:
Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. [[step3]]copiez le logiciel NX-OS et les images EPLD sur le commutateur Nexus 9336C-FX2.


[listing]
----
cs2# copy sftp: bootflash: vrf management
Enter source filename: /code/nxos.9.3.5.bin
Enter hostname for the sftp server: 172.19.2.1
Enter username: user1
Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/nxos.9.3.5.bin  /bootflash/nxos.9.3.5.bin
/code/nxos.9.3.5.bin  100% 1261MB   9.3MB/s   02:15
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.
cs2# copy sftp: bootflash: vrf management
Enter source filename: /code/n9000-epld.9.3.5.img
Enter hostname for the sftp server: 172.19.2.1
Enter username: user1
Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/n9000-epld.9.3.5.img  /bootflash/n9000-epld.9.3.5.img
/code/n9000-epld.9.3.5.img  100%  161MB   9.5MB/s   00:16
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.
----
. [[step4]]Vérifiez la version en cours d'exécution du logiciel NX-OS :
`show version`


[listing]
----
cs2# show version
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2020, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.
Software
  BIOS: version 08.38
  NXOS: version 9.3(4)
  BIOS compile time:  05/29/2020
  NXOS image file is: bootflash:///nxos.9.3.4.bin
  NXOS compile time:  4/28/2020 21:00:00 [04/29/2020 02:28:31]
Hardware
  cisco Nexus9000 C9336C-FX2 Chassis
  Intel(R) Xeon(R) CPU E5-2403 v2 @ 1.80GHz with 8154432 kB of memory.
  Processor Board ID FOC20291J6K
  Device name: cs2
  bootflash:   53298520 kB
Kernel uptime is 0 day(s), 0 hour(s), 3 minute(s), 42 second(s)
Last reset at 157524 usecs after Mon Nov  2 18:32:06 2020
  Reason: Reset Requested by CLI command reload
  System version: 9.3(4)
  Service:
plugin
  Core Plugin, Ethernet Plugin
Active Package(s):

cs2#
----
. [[step5]]installez l'image NX-OS.



NOTE: L'installation du fichier image entraîne son chargement à chaque redémarrage du commutateur.

[listing]
----
cs2# install all nxos bootflash:nxos.9.3.5.bin
Installer will perform compatibility check first. Please wait.
Installer is forced disruptive
Verifying image bootflash:/nxos.9.3.5.bin for boot variable "nxos".
[####################] 100% -- SUCCESS
Verifying image type.
[####################] 100% -- SUCCESS
Preparing "nxos" version info using image bootflash:/nxos.9.3.5.bin.
[####################] 100% -- SUCCESS
Preparing "bios" version info using image bootflash:/nxos.9.3.5.bin.
[####################] 100% -- SUCCESS
Performing module support checks.
[####################] 100% -- SUCCESS
Notifying services about system upgrade.
[####################] 100% -- SUCCESS
Compatibility check is done:
Module  bootable       Impact     Install-type  Reason
------  --------  --------------- ------------  ------
  1       yes      disruptive         reset     default upgrade is not hitless
Images will be upgraded according to following table:
Module   Image    Running-Version(pri:alt                New-Version         Upg-
                                                                             Required
------- --------- -------------------------------------- ------------------- ------------
  1      nxos     9.3(4)                                 9.3(5)              yes
  1      bios     v08.37(01/28/2020):v08.23(09/23/2015)  v08.38(05/29/2020)  yes
Switch will be reloaded for disruptive upgrade.
Do you want to continue with the installation (y/n)?  [n] y
Install is in progress, please wait.
Performing runtime checks.
[####################] 100% -- SUCCESS
Setting boot variables.
[####################] 100% -- SUCCESS
Performing configuration copy.
[####################] 100% -- SUCCESS
Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS
Finishing the upgrade, switch will reboot in 10 seconds.
----
. [[step6]]] Vérifiez la nouvelle version du logiciel NX-OS après le redémarrage du commutateur :
`show version`


[listing]
----
cs2# show version
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2020, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.
Software
  BIOS: version 05.33
  NXOS: version 9.3(5)
  BIOS compile time:  09/08/2018
  NXOS image file is: bootflash:///nxos.9.3.5.bin
  NXOS compile time:  11/4/2018 21:00:00 [11/05/2018 06:11:06]
Hardware
  cisco Nexus9000 C9336C-FX2 Chassis
  Intel(R) Xeon(R) CPU E5-2403 v2 @ 1.80GHz with 8154432 kB of memory.
  Processor Board ID FOC20291J6K
  Device name: cs2
  bootflash:   53298520 kB
Kernel uptime is 0 day(s), 0 hour(s), 3 minute(s), 42 second(s)
Last reset at 277524 usecs after Mon Nov  2 22:45:12 2020
  Reason: Reset due to upgrade
  System version: 9.3(4)
  Service:
plugin
  Core Plugin, Ethernet Plugin
Active Package(s):
----
. [[step7]]mettre à niveau l'image EPLD et redémarrer le commutateur.


[listing]
----
cs2# show version module 1 epld
EPLD Device                     Version
---- -------------------------- -------
MI   FPGA                        0x7
IO   FPGA                        0x17
MI   FPGA2                       0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
cs2# install epld bootflash:n9000-epld.9.3.5.img module 1
Compatibility check:
Module      Type        Upgradable  Impact      Reason
------  -------------- ------------ ----------- -------
     1      SUP        Yes          disruptive  Module Upgradable
Retrieving EPLD versions... Please wait.
Images will be upgraded according to following table:
Module  Type   EPLD              Running-Version   New-Version  Upg-Required
------- ------ ----------------- ----------------- ------------ ------------
     1  SUP    MI FPGA           0x07              0x07         No
     1  SUP    IO FPGA           0x17              0x19         Yes
     1  SUP    MI FPGA2          0x02              0x02         No
The above modules require upgrade.
The switch will be reloaded at the end of the upgrade
Do you want to continue (y/n) ?  [n] y
Proceeding to upgrade Modules.
Starting Module 1 EPLD Upgrade
Module 1 : IO FPGA [Programming] : 100.00% (     64 of      64 sectors)
Module 1 EPLD upgrade is successful.
Module   Type  Upgrade-Result
-------- ----- --------------
     1   SUP   Success
EPLDs upgraded.
Module 1 EPLD upgrade is successful.
----
. [[step8]]après le redémarrage du commutateur, reconnectez-vous et vérifiez que la nouvelle version de EPLD a été chargée avec succès.


[listing]
----
cs2# show version module 1 epld
EPLD Device                     Version
---- -------------------------- --------
MI   FPGA                        0x7
IO   FPGA                        0x19
MI   FPGA2                       0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
----


==== Installez le FCR sur un commutateur de cluster Cisco Nexus 9336C- FX2

Vous pouvez installer la FCR après la première configuration du commutateur de cluster Nexus 9336C-FX2. Vous pouvez également utiliser cette procédure pour mettre à niveau votre version RCF sur votre commutateur de cluster.

.Description de la tâche
Les exemples de cette procédure utilisent la nomenclature des commutateurs et des nœuds suivante :

* Les noms des deux commutateurs Cisco sont `cs1` et `cs2`.
* Les noms de nœud sont `cluster1-01`, `cluster1-02`, `cluster1-03`, et `cluster1-04`.
* Les noms LIF de cluster sont `cluster1-01_clus1`, `cluster1-01_clus2`, `cluster1-02_clus1`, `cluster1-02_clus2`, `cluster1-03_clus1`, `cluster1-03_clus2`, `cluster1-04_clus1`, et `cluster1-04_clus2`.
* L'invite cluster1:*> indique le nom du cluster.



NOTE: La procédure nécessite l'utilisation des commandes ONTAP et des commutateurs Cisco Nexus 9000 ; les commandes ONTAP sont utilisées sauf indication contraire.

.Étapes
. [[step1]]affiche les ports de cluster sur chaque nœud connecté aux commutateurs du cluster :
`network device-discovery show`


[listing]
----
cluster1::*> network device-discovery show
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  --------
cluster1-01/cdp
            e3a    cs1                       Ethernet1/7       N9K-C9336C
            e0d    cs2                       Ethernet1/7       N9K-C9336C
cluster1-02/cdp
            e3a    cs1                       Ethernet1/8       N9K-C9336C
            e0d    cs2                       Ethernet1/8       N9K-C9336C
cluster1-03/cdp
            e3a    cs1                       Ethernet1/1/1     N9K-C9336C
            e3b    cs2                       Ethernet1/1/1     N9K-C9336C
cluster1-04/cdp
            e3a    cs1                       Ethernet1/1/2     N9K-C9336C
            e3b    cs2                       Ethernet1/1/2     N9K-C9336C
cluster1::*>
----
. [[step2]]Vérifiez l'état administratif et opérationnel de chaque port du cluster.
. [[step3]]vérifier que tous les ports du cluster sont à l'état actif :
`network port show –role cluster`


[listing]
----
cluster1::*> network port show -role cluster
Node: cluster1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0d       Cluster      Cluster          up   9000  auto/100000 healthy false
Node: cluster1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0d       Cluster      Cluster          up   9000  auto/100000 healthy false
8 entries were displayed.
Node: cluster1-03

                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false
Node: cluster1-04
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e0a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/100000 healthy  false
cluster1::*>
----
. [[step4]]vérifier que toutes les interfaces de cluster (LIFs) sont sur le port de home Port :
`network interface show -role cluster`


[listing]
----
cluster1::*> network interface show -role cluster
        Logical            Status     Network         Current      Current Is
Vserver Interface          Admin/Oper Address/Mask    Node         Port    Home
------- ------------------ ---------- --------------- ------------ ------- ----
Cluster
        cluster1-01_clus1  up/up     169.254.3.4/23   cluster1-01  e3a     true
        cluster1-01_clus2  up/up     169.254.3.5/23   cluster1-01  e0d     true
        cluster1-02_clus1  up/up     169.254.3.8/23   cluster1-02  e3a     true
        cluster1-02_clus2  up/up     169.254.3.9/23   cluster1-02  e0d     true
        cluster1-03_clus1  up/up     169.254.1.3/23   cluster1-03  e3a     true
        cluster1-03_clus2  up/up     169.254.1.1/23   cluster1-03  e3b     true
        cluster1-04_clus1  up/up     169.254.1.6/23   cluster1-04  e3a     true
        cluster1-04_clus2  up/up     169.254.1.7/23   cluster1-04  e3b     true
8 entries were displayed.
cluster1::*>
----
. [[step5]]Vérifiez que le cluster affiche les informations des deux commutateurs de cluster :
`system cluster-switch show -is-monitoring-enabled-operational true`


[listing]
----
cluster1::*> system cluster-switch show -is-monitoring-enabled-operational true
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- -----
cs1                         cluster-network    10.233.205.90    N9K-C9336C
     Serial Number: FOCXXXXXXGD
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
cs2                         cluster-network    10.233.205.91    N9K-C9336C
     Serial Number: FOCXXXXXXGS
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
cluster1::*>
----
. [[step6]]Désactiver la fonction de restauration automatique sur les LIFs du cluster.


[listing]
----
cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert false
----
. [[step7]]sur le commutateur de cluster cs2, arrêtez les ports connectés aux ports de cluster des nœuds.


[listing]
----
cs2(config)# interface eth1/1/1-2,eth1/7-8
cs2(config-if-range)# shutdown
----
. [[step8]]Vérifiez que les LIFs de cluster ont migré vers les ports hébergés sur le commutateur de cluster cs1. Cette opération peut prendre quelques secondes :
`network interface show -role cluster`


[listing]
----
cluster1::*> network interface show -role cluster
        Logical           Status     Network          Current      Current  Is
Vserver Interface         Admin/Oper Address/Mask     Node         Port     Home
------- ----------------- --------- ---------------- ------------- ------- ----
Cluster
        cluster1-01_clus1 up/up     169.254.3.4/23   cluster1-01   e3a     true
        cluster1-01_clus2 up/up     169.254.3.5/23   cluster1-01   e3a     false
        cluster1-02_clus1 up/up     169.254.3.8/23   cluster1-02   e3a     true
        cluster1-02_clus2 up/up     169.254.3.9/23   cluster1-02   e3a     false
        cluster1-03_clus1 up/up     169.254.1.3/23   cluster1-03   e3a     true
        cluster1-03_clus2 up/up     169.254.1.1/23   cluster1-03   e3a     false
        cluster1-04_clus1 up/up     169.254.1.6/23   cluster1-04   e3a     true
        cluster1-04_clus2 up/up     169.254.1.7/23   cluster1-04   e3a     false
8 entries were displayed.
cluster1::*>
----
. [[step9]]vérifier que le cluster fonctionne correctement :
`cluster show`


[listing]
----
cluster1::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  -------
cluster1-01          true    true          false
cluster1-02          true    true          false
cluster1-03          true    true          true
cluster1-04          true    true          false
4 entries were displayed.
cluster1::*>
----
. [[étape10]]nettoyez la configuration sur le commutateur cs2 et effectuez une configuration de base.
+
.. Nettoyez la configuration. Cette étape nécessite une connexion de console au commutateur.




[listing]
----
cs2# write erase
Warning: This command will erase the startup-configuration.
Do you wish to proceed anyway? (y/n)  [n] y
cs2# reload
This command will reboot the system. (y/n)?  [n] y
cs2#
----
. Effectuer une configuration de base du contacteur.


. [[step11]]Copier la FCR dans le bootflash du commutateur cs2 à l'aide de l'un des protocoles de transfert suivants : FTP, TFTP, SFTP ou SCP. Pour plus d'informations sur les commandes Cisco, reportez-vous au guide approprié dans le https://["Guides de référence des commandes Cisco Nexus série 9000 NX-OS"].
+
Cet exemple montre que TFTP est utilisé pour copier une FCR dans le bootflash sur le commutateur cs2.



[listing]
----
cs2# copy tftp: bootflash: vrf management
Enter source filename: Nexus_9336C_RCF_v1.6-Cluster-HA-Breakout.txt
Enter hostname for the tftp server: 172.22.201.50
Trying to connect to tftp server...Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
. [[step12]]appliquez la FCR précédemment téléchargée sur bootflash. Pour plus d'informations sur les commandes Cisco, reportez-vous au guide approprié dans le https://["Guides de référence des commandes Cisco Nexus série 9000 NX-OS"].
+
Cet exemple montre le fichier RCF `Nexus_9336C_RCF_v1.6-Cluster-HA-Breakout.txt` en cours d'installation sur le commutateur cs2.



[listing]
----
cs2# copy Nexus_9336C_RCF_v1.6-Cluster-HA-Breakout.txt running-config echo-commands
----
. [[step13]]examinez la sortie de la bannière à partir du `show banner motd` commande. Vous devez lire et suivre ces instructions pour vous assurer que la configuration et le fonctionnement du commutateur sont corrects.


[listing]
----
cs2# show banner motd
***************************************************************************
* NetApp Reference Configuration File (RCF)
*
* Switch   : Nexus N9K-C9336C-FX2
* Filename : Nexus_9336C_RCF_v1.6-Cluster-HA-Breakout.txt
* Date     : 10-23-2020
* Version  : v1.6
*
* Port Usage:
* Ports  1- 3: Breakout mode (4x10G) Intra-Cluster Ports, int e1/1/1-4,
* e1/2/1-4, e1/3/1-4
* Ports  4- 6: Breakout mode (4x25G) Intra-Cluster/HA Ports, int e1/4/1-4,
* e1/5/1-4, e1/6/1-4
* Ports  7-34: 40/100GbE Intra-Cluster/HA Ports, int e1/7-34
* Ports 35-36: Intra-Cluster ISL Ports, int e1/35-36
*
* Dynamic breakout commands:
* 10G: interface breakout module 1 port <range> map 10g-4x
* 25G: interface breakout module 1 port <range> map 25g-4x
*
* Undo breakout commands and return interfaces to 40/100G configuration in
* config mode:
* no interface breakout module 1 port <range> map 10g-4x
* no interface breakout module 1 port <range> map 25g-4x
* interface Ethernet <interfaces taken out of breakout mode>
* inherit port-profile 40-100G
* priority-flow-control mode auto
* service-policy input HA
* exit
*
***************************************************************************
----
. [[step14]]vérifier que le fichier RCF est la bonne version plus récente :
`show running-config`
+
Lorsque vous vérifiez que la sortie est correcte, vérifiez que les informations suivantes sont correctes :

+
** La bannière RCF
** Les paramètres du nœud et du port
** Personnalisations
+
Le résultat varie en fonction de la configuration de votre site. Vérifiez les paramètres des ports et reportez-vous aux notes de version pour voir si des modifications spécifiques à la FCR que vous avez installée.



. Après avoir vérifié que les versions de RCF et les paramètres de commutateur sont corrects, copiez le fichier running-config dans le fichier startup-config.
+
Pour plus d'informations sur les commandes Cisco, reportez-vous au guide approprié dans le https://["Guides de référence des commandes Cisco Nexus série 9000 NX-OS"].



[listing]
----
cs2# copy running-config startup-config [########################################] 100% Copy complete
----
. [[step16]]redémarrer le commutateur cs2. Vous pouvez ignorer les événements “panne des ports de cluster” signalés sur les nœuds pendant le redémarrage du commutateur.


[listing]
----
cs2# reload
This command will reboot the system. (y/n)?  [n] y
----
. [[step17]]appliquez la même FCR et sauvegardez la configuration en cours d'exécution pendant une seconde fois.


[listing]
----
cs2# copy Nexus_9336C_RCF_v1.6-Cluster-HA-Breakout.txt running-config echo-commands
cs2# copy running-config startup-config [########################################] 100% Copy complete
----
. [[step18]]vérifier l'état de santé des ports du cluster sur le cluster.
+
.. Vérifier que les ports e0d fonctionnent correctement sur tous les nœuds du cluster :
`network port show -role cluster`




[listing]
----
cluster1::*> network port show -role cluster
Node: cluster1-01
                                                                   Ignore
                                             Speed(Mbps)  Health   Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Oper   Status   Status
------- --------- ---------------- ---- ---- ------------ -------- ------
e3a     Cluster   Cluster          up   9000 auto/100000  healthy  false
e3b     Cluster   Cluster          up   9000 auto/100000  healthy  false

Node: cluster1-02
                                                                   Ignore
                                              Speed(Mbps)  Health  Health
Port    IPspace   Broadcast Domain Link MTU   Admin/Oper   Status  Status
------- --------- ---------------- ---- ----- ------------ -------- ------
e3a    Cluster   Cluster          up   9000  auto/100000  healthy  false
e3b    Cluster   Cluster          up   9000  auto/100000  healthy  false

Node: cluster1-03
                                                                   Ignore
                                              Speed(Mbps) Health   Health
Port   IPspace    Broadcast Domain Link MTU   Admin/Oper  Status   Status
------ ---------- ---------------- ---- ----- ----------- -------- ------
e3a    Cluster    Cluster          up   9000  auto/100000 healthy  false
e0d    Cluster    Cluster          up   9000  auto/100000 healthy  false

Node: cluster1-04
                                                                   Ignore
                                              Speed(Mbps) Health   Health
Port   IPspace    Broadcast Domain Link MTU   Admin/Oper  Status   Status
------ ---------- ---------------- ---- ----- ----------- -------- ------
e3a    Cluster      Cluster        up   9000  auto/100000 healthy  false
e0d    Cluster      Cluster        up   9000  auto/100000 healthy  false
8 entries were displayed.
----
. Vérifiez l'état du commutateur depuis le cluster (il se peut que le commutateur cs2 n'affiche pas, car les LIF ne sont pas homeed sur e0d).


[listing]
----
cluster1::*> network device-discovery show -protocol cdp
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-01/cdp
            e3a    cs1                       Ethernet1/7       N9K-C9336C
            e0d    cs2                       Ethernet1/7       N9K-C9336C
cluster01-2/cdp
            e3a    cs1                       Ethernet1/8       N9K-C9336C
            e0d    cs2                       Ethernet1/8       N9K-C9336C
cluster01-3/cdp
            e3a    cs1                       Ethernet1/1/1     N9K-C9336C
            e3b    cs2                       Ethernet1/1/1     N9K-C9336C
cluster1-04/cdp
            e3a    cs1                       Ethernet1/1/2     N9K-C9336C
            e3b    cs2                       Ethernet1/1/2     N9K-C9336C
cluster1::*> system cluster-switch show -is-monitoring-enabled-operational true
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- -----
cs1                         cluster-network    10.233.205.90    NX9-C9336C
     Serial Number: FOCXXXXXXGD
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
cs2                         cluster-network    10.233.205.91    NX9-C9336C
     Serial Number: FOCXXXXXXGS
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
2 entries were displayed.
----

NOTE: Vous pouvez observer la sortie suivante sur la console des commutateurs cs1 en fonction de la version RCF précédemment chargée sur le commutateur.

[listing]
----
2020 Nov 17 16:07:18 cs1 %$ VDC-1 %$ %STP-2-UNBLOCK_CONSIST_PORT: Unblocking port port-channel1 on VLAN0092. Port consistency restored.
2020 Nov 17 16:07:23 cs1 %$ VDC-1 %$ %STP-2-BLOCK_PVID_PEER: Blocking port-channel1 on VLAN0001. Inconsistent peer vlan.
2020 Nov 17 16:07:23 cs1 %$ VDC-1 %$ %STP-2-BLOCK_PVID_LOCAL: Blocking port-channel1 on VLAN0092. Inconsistent local vlan.
----
. [[step19]]sur le commutateur de cluster cs1, arrêtez les ports connectés aux ports de cluster des nœuds. L'exemple suivant utilise la sortie d'exemple d'interface de l'étape 1 :


[listing]
----
cs1(config)# interface eth1/1/1-2,eth1/7-8
cs1(config-if-range)# shutdown
----
. [[step20]]vérifier que les LIFs du cluster ont migré vers les ports hébergés sur le commutateur cs2. Cette opération peut prendre quelques secondes :
`network interface show -role cluster`


[listing]
----
cluster1::*> network interface show -role cluster
        Logical            Status      Network         Current      Current Is
Vserver Interface          Admin/Oper  Address/Mask    Node         Port    Home
------- ------------------ ----------- --------------- ------------ ------- ----
Cluster
        cluster1-01_clus1  up/up       169.254.3.4/23   cluster1-01   e0d  false
        cluster1-01_clus2  up/up       169.254.3.5/23   cluster1-01   e0d   true
        cluster1-02_clus1  up/up       169.254.3.8/23   cluster1-02   e0d  false
        cluster1-02_clus2  up/up       169.254.3.9/23   cluster1-02   e0d   true
        cluster1-03_clus1  up/up       169.254.1.3/23   cluster1-03   e3b  false
        cluster1-03_clus2  up/up       169.254.1.1/23   cluster1-03   e3b   true
        cluster1-04_clus1  up/up       169.254.1.6/23   cluster1-04   e3b  false
        cluster1-04_clus2  up/up       169.254.1.7/23   cluster1-04   e3b   true
8 entries were displayed.
cluster1::*>
----
. [[step21]]vérifier que le cluster fonctionne correctement :
`cluster show`


[listing]
----
cluster1::*> cluster show
Node                 Health   Eligibility   Epsilon
-------------------- -------- ------------- -------
cluster1-01          true     true          false
cluster1-02          true     true          false
cluster1-03          true     true          true
cluster1-04          true     true          false
4 entries were displayed.
cluster1::*>
----
. [[step22]]Répétez les étapes 7 à 14 de l'interrupteur cs1.
. Activez la fonction de revert automatique sur les LIFs du cluster.


[listing]
----
cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert True
----
. [[step24]]redémarrer le commutateur cs1. Vous pouvez ainsi déclencher des LIF de cluster afin de rétablir leur port de départ. Vous pouvez ignorer les événements “panne des ports de cluster” signalés sur les nœuds pendant le redémarrage du commutateur.


[listing]
----
cs1# reload
This command will reboot the system. (y/n)?  [n] y
----
. [[step25]]Vérifiez que les ports du commutateur connectés aux ports du cluster sont bien connectés.


[listing]
----
cs1# show interface brief | grep up
.
.
Eth1/1/1      1       eth  access up      none                   100G(D) --
Eth1/1/2      1       eth  access up      none                   100G(D) --
Eth1/7        1       eth  trunk  up      none                   100G(D) --
Eth1/8        1       eth  trunk  up      none                   100G(D) --
.
.
----
. [[step26]]vérifier que l'ISL entre cs1 et cs2 est fonctionnel :
`show port-channel summary`


[listing]
----
cs1# show port-channel summary
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)        Eth1/36(P)
cs1#
----
. [[step27]]vérifier que les LIFs du cluster ont rétabli leur port de départ :
`network interface show -role cluster`


[listing]
----
cluster1::*> network interface show -role cluster
        Logical            Status     Network           Current     Current Is
Vserver Interface          Admin/Oper Address/Mask      Node        Port    Home
------- ------------------ ---------- ----------------- ----------- ------- ----
Cluster
        cluster1-01_clus1  up/up      169.254.3.4/23    cluster1-01  e0d   true
        cluster1-01_clus2  up/up      169.254.3.5/23    cluster1-01  e0d   true
        cluster1-02_clus1  up/up      169.254.3.8/23    cluster1-02  e0d   true
        cluster1-02_clus2  up/up      169.254.3.9/23    cluster1-02  e0d   true
        cluster1-03_clus1  up/up      169.254.1.3/23    cluster1-03  e3b   true
        cluster1-03_clus2  up/up      169.254.1.1/23    cluster1-03  e3b   true
        cluster1-04_clus1  up/up      169.254.1.6/23    cluster1-04  e3b   true
        cluster1-04_clus2  up/up      169.254.1.7/23    cluster1-04  e3b   true
8 entries were displayed.
cluster1::*>
----
. [[step28]]vérifier que le cluster fonctionne correctement :
`cluster show`


[listing]
----
cluster1::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
cluster1-01          true    true          false
cluster1-02          true    true          false
cluster1-03          true    true          true
cluster1-04          true    true          false
4 entries were displayed.
cluster1::*>
----
. [[step29]]Envoyez un ping aux interfaces de cluster distantes pour vérifier la connectivité :
`cluster ping-cluster -node local`


[listing]
----
cluster1::*> cluster ping-cluster -node local
Host is cluster1-03
Getting addresses from network interface table...
Cluster cluster1-03_clus1 169.254.1.3 cluster1-03 e3a
Cluster cluster1-03_clus2 169.254.1.1 cluster1-03 e3b
Cluster cluster1-04_clus1 169.254.1.6 cluster1-04 e3a
Cluster cluster1-04_clus2 169.254.1.7 cluster1-04 e3b
Cluster cluster1-01_clus1 169.254.3.4 cluster1-01 e3a
Cluster cluster1-01_clus2 169.254.3.5 cluster1-01 e0d
Cluster cluster1-02_clus1 169.254.3.8 cluster1-02 e3a
Cluster cluster1-02_clus2 169.254.3.9 cluster1-02 e0d
Local = 169.254.1.3 169.254.1.1
Remote = 169.254.1.6 169.254.1.7 169.254.3.4 169.254.3.5 169.254.3.8 169.254.3.9
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 12 path(s)
Basic connectivity fails on 0 path(s)

Detected 9000 byte MTU on 12 path(s):
    Local 169.254.1.3 to Remote 169.254.1.6
    Local 169.254.1.3 to Remote 169.254.1.7
    Local 169.254.1.3 to Remote 169.254.3.4
    Local 169.254.1.3 to Remote 169.254.3.5
    Local 169.254.1.3 to Remote 169.254.3.8
    Local 169.254.1.3 to Remote 169.254.3.9
    Local 169.254.1.1 to Remote 169.254.1.6
    Local 169.254.1.1 to Remote 169.254.1.7
    Local 169.254.1.1 to Remote 169.254.3.4
    Local 169.254.1.1 to Remote 169.254.3.5
    Local 169.254.1.1 to Remote 169.254.3.8
    Local 169.254.1.1 to Remote 169.254.3.9
Larger than PMTU communication succeeds on 12 path(s)
RPC status:
6 paths up, 0 paths down (tcp check)
6 paths up, 0 paths down (udp check)
----


==== Installez le FCR sur un commutateur de stockage Cisco Nexus 9336C-FX2

Les fichiers RCF (Reference Configuration File) peuvent être mis à niveau sur les commutateurs de stockage Cisco Nexus 9336C-FX2.

.Avant de commencer
Les conditions suivantes doivent exister avant de mettre à niveau la FCR sur le commutateur de stockage :

* Le commutateur doit fonctionner entièrement (il ne doit pas y avoir d'erreurs dans les journaux ni de problèmes similaires).
* Vous devez avoir vérifié ou défini les variables de démarrage souhaitées dans la FCR pour qu'elles reflètent les images de démarrage souhaitées si vous installez uniquement NX-OS et que vous gardez la version actuelle de RCF.
* Si vous devez modifier les variables de démarrage pour qu'elles reflètent les images de démarrage actuelles, vous devez le faire avant de réappliquer la FCR de sorte que la version correcte soit instanciée lors des prochains redémarrages.
* Vous devez avoir dirigé les guides de mise à niveau et de logiciels appropriés disponibles sur le site Web de Cisco pour obtenir une documentation complète sur les procédures de mise à niveau et de mise à niveau vers une version antérieure du stockage Cisco. Voir https://["Commutateurs Cisco Nexus 9000 Series"] pour en savoir plus.
* Le nombre de ports 100 GbE est défini dans les fichiers de configuration de référence disponibles sur le https://["Commutateurs Ethernet Cisco"] page.




===== Récapitulatif de la procédure

. Vérifier l'état de santé des commutateurs et des ports (étapes 1 à 4)
. Téléchargez l'image NX-OS sur le commutateur Cisco st2 et redémarrez (étapes 5 à 8).
. Copier le FCR sur le commutateur Cisco st2 (étapes 9 à 12)
. Vérifier à nouveau l'état d'intégrité des commutateurs et des ports (étapes 13 à 15)
. Répétez les étapes 1 à 1-15 pour le commutateur Cisco st1.



NOTE: Les sorties de la commande peuvent varier en fonction des différentes versions d'ONTAP.

Les exemples de cette procédure utilisent la nomenclature des commutateurs et des nœuds suivante :

* Les noms des deux commutateurs de stockage sont _st1_ et _st2_.
* Les nœuds sont _node1_ et _node2_.



NOTE: La procédure nécessite l'utilisation des commandes ONTAP et des commutateurs Cisco Nexus 9000 ; les commandes ONTAP sont utilisées sauf indication contraire.

.Étapes
. Si AutoSupport est activé sur ce cluster, supprimez la création automatique de dossiers en invoquant un message AutoSupport : `system node autosupport invoke -node * -type all - message MAINT=xh`
+
Où x représente la durée de la fenêtre de maintenance en heures.

. Vérifier que les commutateurs de stockage sont disponibles :
`system switch ethernet show`


[listing]
----
storage::*> system switch ethernet show
Switch                    Type               Address          Model
------------------------- ------------------ ---------------- ---------------
st1
                          storage-network    172.17.227.5     NX9-C9336C
      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
st2
                          storage-network    172.17.227.6     NX9-C9336C
      Serial Number: FOC220443LZ
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
2 entries were displayed.
storage::*>
----
. [[step3]]vérifier que les ports du nœud sont opérationnels et en bon état :
`storage port show -port-type ENET`


[listing]
----
storage::*> storage port show -port-type ENET
                                   Speed                            VLAN
Node     Port   Type    Mode       (Gb/s)     State     Status        ID
------- ------- ------- ---------- ---------- --------- ----------- -----
node1
        e3a     ENET    storage    100        enabled   online         30
        e3b     ENET    storage      0        enabled   offline        30
        e7a     ENET    storage      0        enabled   offline        30
        e7b     ENET    storage    100        enabled   online         30
node2
        e3a     ENET    storage    100        enabled   online         30
        e3b     ENET    storage      0        enabled   offline        30
        e7a     ENET    storage      0        enabled   offline        30
        e7b     ENET    storage    100        enabled   online         30
----
. [[step4]]vérifier l'absence de problèmes de câblage et de commutateur de stockage au niveau du cluster :
`system health alert show -instance`


[listing]
----
storage::*> system health alert show -instance
There are no entries matching your query.
----
. [[step5]]Télécharger l'image NX-OS pour changer st2.
. Installez l'image système de manière à ce que la nouvelle version soit chargée la prochaine fois que le commutateur st2 est redémarré. Le commutateur est redémarré en 10 secondes avec la nouvelle image comme indiqué dans la sortie suivante :


[listing]
----
st2# install all nxos bootflash:nxos.9.3. 5.bin
Installer will perform compatibility check first. Please wait.
Installer is forced disruptive
Verifying image bootflash:/nxos.9.3.4.bin for boot variable "nxos".
[####################] 100% -- SUCCESS
Verifying image type.
[[####################] 100% -- SUCCESS
Preparing "nxos" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS
Preparing "bios" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS
Performing module support checks.
[####################] 100% -- SUCCESS
Notifying services about system upgrade.
[####################] 100% -- SUCCESS
Compatibility check is done:
Module  bootable  Impact  Install-type  Reason
------    --------   ----- --------   ------------   ---- --
     1        yes      disruptive         reset  default upgrade is not hitless
Images will be upgraded according to following table:
Module Image        Running-Version(pri:alt)               New-Version  Upg
                                                                        Required
------ --------  ---------------------------------------  ------------  --------
 1     nxos                                     9.3(3)          9.3(4)       yes
 1     bios      v08.37(01/28/2020):v08.23(09/23/2015)   v08.38(05/29/2020)   no
Switch will be reloaded for disruptive upgrade.
Do you want to continue with the installation (y/n)? [n] y
input string too long
Do you want to continue with the installation (y/n)? [n] y
Install is in progress, please wait.
Performing runtime checks.
[####################] 100% -- SUCCESS
Setting boot variables.
[####################] 100% -- SUCCESS
Performing configuration copy.
[####################] 100% -- SUCCESS
Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS
Finishing the upgrade, switch will reboot in 10 seconds.
st2#
----
. [[step7]]Enregistrer la configuration.
+
Vous êtes invité à redémarrer le système comme indiqué dans l'exemple suivant :



[listing]
----
st2# copy running-config startup-config
[########################################] 100% Copy complete.
st2# reload
This command will reboot the system. (y/n)? [n] y
----
. [[step8]]Vérifiez que le nouveau numéro de version NX-OS est sur le commutateur.


[listing]
----
st2# show version
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Upgrading a Cisco Nexus 9336C Storage Switch 6
Upgrading a Cisco Nexus 9336C storage switch
Copyright (C) 2002-2020, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source. This software is provided "as is," and unless otherwise stated, there is no warranty, express or implied, including but not limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0 or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
.
Software
 BIOS: version 08.38
 NXOS: version 9.3(5)
 BIOS compile time: 05/29/2020
 NXOS image file is: bootflash:///nxos.9.3. 5.bin
 NXOS compile time: 4/28/2020 21:00:00 [04/29/2020 02:28:31]
Hardware
 cisco Nexus9000 C9336C Chassis (Nexus 9000 Series)
 Intel(R) Xeon(R) CPU E5-2403 v2 @ 1.80GHz with 8154432 kB of memory.
 Processor Board ID FOC20291J6K
 Device name: S2
 bootflash: 53298520 kB
Kernel uptime is 0 day(s), 0 hour(s), 3 minute(s), 42 second(s)
Last reset at 157524 usecs after Mon Nov 2 18:32:06 2020
           Reason: Reset due to upgrade
   System version: 9.3(5)
   Service:
plugin
   Core Plugin, Ethernet Plugin
   Active Package(s):
st2#
----
. [[step9]]copiez le commutateur RCF on st2 sur le commutateur bootflash à l'aide de l'un des protocoles de transfert suivants : FTP, HTTP, TFTP, SFTP ou SCP.
+
Pour plus d'informations sur les commandes Cisco, reportez-vous au guide approprié dans le https://["Guides de référence des commandes Cisco Nexus série 9000 NX-OS"].

+
L'exemple suivant montre que HTTP est utilisé pour copier une FCR sur le commutateur bootflash on st2 :



[listing]
----
st2# copy http://172.16.10.1//cfg/Nexus_9336C_RCF_v1.6-Storage.txt bootflash: vrf management
% Total % Received % Xferd   Average   Speed  Time   Time   Time
Current
   Dload     Upload  Total Spent   Left
Speed
 100    3254          100     3254      0       0     8175    0 --:--:-- --:--:-- --:--:–
8301
Copy complete, now saving to disk (please wait)...
Copy complete.
st2#
----
. [[step10]]appliquer la FCR précédemment téléchargée sur le bootflash :
`copy bootflash`.
+
L'exemple suivant montre le fichier RCF `Nexus_9336C_RCF_v1.6-Storage.txt` en cours d'installation sur l'interrupteur st2 :



[listing]
----
st2# copy Nexus_9336C_RCF_v1.6-Storage.txt running-config echo-commands
----
. [[step11]]Vérifiez que le fichier RCF est la bonne version plus récente :
`show running-config`
+
Lorsque vous vérifiez que la sortie est correcte, vérifiez que les informations suivantes sont correctes :

+
** La bannière RCF
** Les paramètres du nœud et du port
** Personnalisations
+
Le résultat varie en fonction de la configuration de votre site. Vérifiez les paramètres des ports et reportez-vous aux notes de version pour voir si des modifications spécifiques à la FCR que vous avez installée.

+
*Important:* dans la sortie de la bannière du `show banner motd` Commande, vous devez lire et suivre les instructions de la section *NOTES IMPORTANTES *pour assurer la configuration et le fonctionnement corrects du commutateur.





[listing]
----
st2# show banner motd
******************************************************************************
*NetApp Reference Configuration File (RCF)
*
*Switch : Nexus N9K-C9336C-FX2
*Filename : Nexus_9336C_RCF_v1.6-Storage.txt
* Date : 10-23-2020
*Version  : v1.6
*
*Port Usage: Storage configuration
*Ports 1-36: 100GbE Controller and Shelf Storage Ports
*
*IMPORTANT NOTES*
*- This RCF utilizes QoS and requires TCAM re-configuration, requiring RCF
*to be loaded twice with the Storage Switch rebooted in between.
*
*- Perform the following 4 steps to ensure proper RCF installation:
*
*(1) Apply RCF first time, expect following messages:
*- Please save config and reload the system...
*- Edge port type (portfast) should only be enabled on ports...
*- TCAM region is not configured for feature QoS class IPv4 ingress...
*
*(2) Save running-configuration and reboot Cluster Switch
*
*(3) After reboot, apply same RCF second time and expect following messages:
*- % Invalid command at '^' marker
*- Syntax error while parsing...
*
*(4) Save running-configuration again
******************************************************************************
st2#
----
. [[step12]]après avoir vérifié que les versions du logiciel et les paramètres du commutateur sont corrects, copiez le fichier running-config dans le fichier startup-config du commutateur st2.
+
Pour plus d'informations sur les commandes Cisco, reportez-vous au guide approprié dans le https://["Guides de référence des commandes Cisco Nexus série 9000 NX-OS"].

+
L'exemple suivant montre le `running-config` le fichier a été copié dans le `startup-config` fichier :



[listing]
----
st2# copy running-config startup-config
[########################################] 100% Copy complete.
----
. [[step13]]vérifier à nouveau que les commutateurs de stockage sont disponibles après le redémarrage :
`system switch ethernet show`


[listing]
----
storage::*> system switch ethernet show
Switch                       Type               Address          Model
---------------------------- ------------------ ---------------- ---------------
st1
                            storage-network     172.17.227.5     NX9-C9336C
     Serial Number: FOC221206C2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
st2
                            storage-network      172.17.227.6    NX9-C9336C
     Serial Number: FOC220443LZ
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
2 entries were displayed.
storage::*
----
. [[step14]]vérifier que les ports du switch sont opérationnels et en bon état après le redémarrage :
`storage port show -port-type ENET`


[listing]
----
storage::*> storage port show -port-type ENET
                                   Speed                            VLAN
Node    Port    Type    Mode       (Gb/s)      State     Status       ID
------- ------- ------- ---------- ----------- --------- --------- -----
node1
        e3a     ENET    storage           100   enabled   online       30
        e3b     ENET    storage             0   enabled   offline      30
        e7a     ENET    storage             0   enabled   offline      30
        e7b     ENET    storage           100   enabled   online       30
node2
        e3a     ENET    storage           100   enabled   online       30
        e3b     ENET    storage             0   enabled   offline      30
        e7a     ENET    storage             0   enabled   offline      30
        e7b     ENET    storage           100   enabled   online       30
----
. [[step15]]vérifier l'absence de problèmes de câblage ou de commutateur de stockage sur le cluster :
`system health alert show -instance`


[listing]
----
storage::*> system health alert show -instance
There are no entries matching your query.
----
. [[step16]]répéter cette procédure pour la FCR sur l'interrupteur st1.
. Si vous avez supprimé la création automatique de cas, réactivez-la en appelant un message AutoSupport :
`system node autosupport invoke -node * -type all -message MAINT=END`




==== Installez le FCR sur un commutateur partagé Cisco Nexus 9336C-FX2

À partir de la version ONTAP 9.9.1, vous pouvez utiliser les commutateurs Cisco Nexus 9336C-FX2 pour combiner les fonctionnalités de stockage et de cluster dans un scénario de commutateur partagé.

.Avant de commencer
* Les commutateurs de cluster doivent fonctionner parfaitement (il ne doit y avoir aucune erreur dans les journaux ou d'autres problèmes similaires).
* Les commutateurs de stockage doivent fonctionner entièrement (il ne doit y avoir aucune erreur dans les journaux ou des problèmes similaires).
* Les noms des deux commutateurs de stockage sont _sh1_ et _sh2_.
* L'exemple utilisé ici charge la FCR partagée sur le nouveau commutateur.


.Étapes
. Copiez le RCF sur le commutateur sh2 sur le commutateur bootflash à l'aide de l'un des protocoles de transfert suivants : FTP, HTTP, TFTP, SFTP ou SCP.
+
Pour plus d'informations sur les commandes Cisco, reportez-vous au guide approprié dans le https://["Guides de référence des commandes Cisco Nexus série 9000 NX-OS"].

+
L'exemple suivant montre que HTTP est utilisé pour copier une FCR dans le bootflash sur le commutateur sh2 :



[listing]
----
sh2# copy http://172.16.10.1//cfg/Nexus_9336C_RCF_v1.7-Cluster-Ha-Storage.txt bootflash: vrf management
% Total % Received % Xferd   Average   Speed  Time   Time   Time
Current
   Dload     Upload  Total Spent   Left
Speed
 100    5143          100     5143      0       0     11300    0 --:--:-- --:--:-- --:--:–
11300
Copy complete, now saving to disk (please wait)...
Copy complete.
sh2#
----
. [[step2]]appliquez la FCR précédemment téléchargée sur le bootflash :
`copy bootflash`.
+
L'exemple suivant montre le fichier RCF `Nexus_9336C_RCF_v1.7-Cluster-HA-Storage.txt ` installé sur le commutateur sh2 :



[listing]
----
sh2# copy Nexus_9336C_RCF_v1.7-Cluster-HA-Storage.txt running-config echo-commands
----
. [[step3]]vérifier que le fichier RCF est la bonne version plus récente :  `show running-config`
+
Lorsque vous vérifiez que la sortie est correcte, vérifiez que les informations suivantes sont correctes :

+
** La bannière RCF
** Les paramètres du nœud et du port
** Personnalisations
+
Le résultat varie en fonction de la configuration de votre site. Vérifiez les paramètres des ports et reportez-vous aux notes de version pour voir si des modifications spécifiques à la FCR que vous avez installée.

+
*Important:* dans la sortie de la bannière du `show banner motd` Commande, vous devez lire et suivre les instructions de la section *NOTES IMPORTANTES *pour assurer la configuration et le fonctionnement corrects du commutateur.





[listing]
----
sh2# show banner motd
******************************************************************************
*NetApp Reference Configuration File (RCF)
*
*Switch : Nexus N9K-C9336C-FX2
*Filename : Nexus_9336C_RCF_v1.7-Cluster-HA-Storage.txt
* Date :  Jan-08-2021
*Version  : v1.7
*
*Port Usage:
*Ports  1-8: 40/100GbE Intra-Cluster/HA Ports, int e1/1-8
*Port     9: 10GbE breakout Intra-Cluster Ports, int e1/9/1-4
*Port    10: 25GbE breakout Intra-Cluster/HA Ports, int e1/10/1-4
*Ports 11-22: First HA-pair Controller and Shelf Storage Ports, int e1/11-22
*Ports 23-34: Second HA-pair Controller and Shelf Storage Ports, int e1/23-34
*Ports 35-36: Intra-Cluster ISL Ports, int e1/35-36
*
* Undo breakout commands and return interfaces to 40/100G configuration in
* config mode:
* no interface breakout module 1 port 9 map 10g-4x
* no interface breakout module 1 port 10 map 25g-4x
* interface Ethernet 1/9-10
* inherit port-profile CLUSTER_HA
* priority-flow-control mode auto
* service-policy type qos input HA_POLICY
* exit
*
*IMPORTANT NOTES*
* In certain conditions, N9K-C9336C-FX2 may not be able to auto-negotiate port
* speed correctly, and port speed must be manually set, in config mode, e.g.
* int e1/1
* speed 40000
* int e1/3
* speed 100000
*
******************************************************************************
sh2#
----
. [[step4]]après avoir vérifié que les versions du logiciel et les paramètres du commutateur sont corrects, copiez le `running-config` fichier dans le fichier startup-config sur le commutateur sh2.
+
Pour plus d'informations sur les commandes Cisco, reportez-vous au guide approprié dans le https://["Guides de référence des commandes Cisco Nexus série 9000 NX-OS"].

+
L'exemple suivant montre le `running-config` le fichier a été copié dans le `startup-config` fichier :



[listing]
----
sh2# copy running-config startup-config
[########################################] 100% Copy complete.
----
. [[step5]]répéter cette procédure pour la FCR sur l'interrupteur sh1.

