---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/components-9336c-shared.html 
keywords: shared storage cluster switch 
summary: 'Identifiez les composants et les numéros de référence des commutateurs partagés Cisco Nexus 9336C-FX2 pour prendre en charge l"installation matérielle et la maintenance continue.' 
---
= Examinez les composants et les références des commutateurs partagés Cisco Nexus 9336C-FX2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Identifiez les composants et les numéros de référence des commutateurs partagés Cisco Nexus 9336C-FX2 pour prendre en charge l'installation matérielle et la maintenance continue.

Le tableau suivant répertorie la référence et la description du commutateur 9336C-FX2, des ventilateurs et des alimentations :

|===
| Numéro de pièce | Description 


| X190200-CS-PE | N9K-9336C-FX2, CS, PTSX, 36PT10/25/40/100GQSFP28 


| X190200-CS-PI | N9K-9336C-FX2, CS, PSIN, 36PT10/25/40/100GQSFP28 


| X190002 | Kit d'accessoires X190001/X190003 


| X-NXA-PAC-1100W-PE2 | Alimentation N9K-9336C AC 1100W - Sortie d'air latérale 


| X-NXA-PAC-1100W-PI2 | Alimentation N9K-9336C AC 1100W - Entrée d'air côté port 


| X-NXA-FAN-65CFM-PE | N9K-9336C 65 CFM, débit d'air d'échappement côté bâbord 


| X-NXA-FAN-65CFM-PI | N9K-9336C 65 CFM, débit d'air d'admission côté bâbord 
|===
.Quelle est la prochaine étape
Une fois que vous avez confirmé vos composants et leurs références, vous pouvez consulter le link:required-documentation-9336c-shared.html["documentation requise"].
