---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/configure-reqs-9336c-shared.html 
keywords: shared storage cluster switch 
summary: 'À partir d" ONTAP 9.9.1, vous pouvez utiliser les commutateurs Cisco Nexus 9336C-FX2 pour combiner les fonctionnalités de stockage et de cluster dans un scénario de commutateur partagé.' 
---
= Configuration requise pour les commutateurs partagés Cisco Nexus 9336C-FX2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour l'installation et la maintenance du commutateur Cisco Nexus 9336C-FX2, assurez-vous de consulter les exigences de configuration et de réseau.



== Prise en charge ONTAP

À partir d' ONTAP 9.9.1, vous pouvez utiliser des commutateurs Cisco Nexus 9336C-FX2 pour combiner les fonctionnalités de stockage et de cluster dans une configuration de commutateur partagée.

Si vous souhaitez créer des clusters ONTAP avec plus de deux nœuds, vous aurez besoin de deux commutateurs réseau compatibles.



== Exigences de configuration

Pour la configuration, vous aurez besoin du nombre et du type appropriés de câbles et de connecteurs de câbles pour vos commutateurs.

Selon le type de commutateur que vous configurez initialement, vous devez vous connecter au port console du commutateur avec le câble console fourni ; vous devez également fournir des informations réseau spécifiques.



== Exigences réseau

Vous avez besoin des informations réseau suivantes pour toutes les configurations de commutateur.

* Sous-réseau IP pour le trafic du réseau de gestion
* Noms d'hôte et adresses IP pour chacun des contrôleurs de système de stockage et tous les commutateurs applicables
* La plupart des contrôleurs de système de stockage sont gérés via l'interface e0M en se connectant au port de service Ethernet (icône de clé). Sur les systèmes AFF A800 et AFF A700s , l'interface e0M utilise un port Ethernet dédié.
* Se référer à https://hwu.netapp.com["Hardware Universe"] pour obtenir les informations les plus récentes.


Pour plus d'informations sur la configuration initiale de votre commutateur, consultez le guide suivant : https://www.cisco.com/c/en/us/td/docs/dcn/hw/nx-os/nexus9000/9336c-fx2-e/cisco-nexus-9336c-fx2-e-nx-os-mode-switch-hardware-installation-guide.html["Guide d'installation et de mise à niveau du Cisco Nexus 9336C-FX2"] .

.Quelle est la prochaine étape
Après avoir examiné les exigences de configuration, vous pouvez confirmer votre link:components-9336c-shared.html["composants et numéros de pièces"].
