---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/install-9336c-shared.html 
keywords:  
summary:  
---
= Installez les commutateurs partagés Cisco Nexus 9336C-FX2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Suivez ces instructions pour configurer les commutateurs partagés Cisco Nexus 9336C-FX2.

.Avant de commencer
Assurez-vous de disposer des éléments suivants :

* Documentation partagée requise sur le commutateur, documentation sur le contrôleur et documentation ONTAP. Voir link:required-documentation-9336c-shared.html["Documentation requise pour les commutateurs partagés Cisco Nexus 9336C-FX2"] et https://docs.netapp.com/us-en/ontap/index.html["Documentation NetApp ONTAP"^].
* Licences applicables, informations sur le réseau et la configuration, et câbles.
* Feuilles de calcul de câblage remplies. Voir link:cable-9336c-shared.html["Complétez la fiche technique de câblage Cisco Nexus 9336C-FX2"]. Pour plus d'informations sur le câblage, reportez-vous au https://hwu.netapp.com["Hardware Universe"].


.Étapes
. Installez les switchs, les contrôleurs et les tiroirs de stockage NVMe NS224.
+
Reportez-vous link:../switch-cisco-9336c-fx2/install-switch-and-passthrough-panel-9336c-cluster.html["Instructions de rayonnage"]au pour savoir comment insérer le commutateur dans une armoire NetApp.

. Mettez les switchs, les contrôleurs et les tiroirs de stockage NVMe NS224 sous tension.


.Et la suite ?
En option, vous pouvezlink:install-switch-and-passthrough-panel-9336c-shared.html["Installez un commutateur Cisco Nexus 9336C-FX2 dans une armoire NetApp"] .  Sinon, allez àlink:setup-and-configure-9336c-shared.html["Configurer le commutateur"] .
