---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/install-9336c-shared.html 
keywords:  
summary:  
---
= Installer des commutateurs partagés Cisco Nexus 9336C-FX2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Suivez ces instructions pour configurer les commutateurs partagés Cisco Nexus 9336C-FX2.

.Avant de commencer
Assurez-vous d'avoir les éléments suivants :

* Documentation requise pour le commutateur partagé, le contrôleur et ONTAP .  Voirlink:required-documentation-9336c-shared.html["Exigences en matière de documentation pour les commutateurs partagés Cisco Nexus 9336C-FX2"] et https://docs.netapp.com/us-en/ontap/index.html["Documentation NetApp ONTAP"^] .
* Licences applicables, informations sur le réseau et la configuration, et câbles.
* Fiches de câblage complétées. Voirlink:cable-9336c-shared.html["Complétez la fiche de câblage Cisco Nexus 9336C-FX2"] .  Pour plus d'informations sur le câblage, reportez-vous au https://hwu.netapp.com["Hardware Universe"] .


.Étapes
. Installez les commutateurs, les contrôleurs et les baies de stockage NVMe NS224.
+
Voir lelink:../switch-cisco-9336c-fx2/install-switch-and-passthrough-panel-9336c-cluster.html["Instructions de mise en rayon"] apprendre comment installer le commutateur dans une armoire NetApp .

. Mettez sous tension les commutateurs, les contrôleurs et les baies de stockage NVMe NS224.


.Quelle est la prochaine étape ?
Vous pouvez, si vous le souhaitez, link:install-switch-and-passthrough-panel-9336c-shared.html["installer un commutateur Cisco Nexus 9336C-FX2 dans une armoire NetApp"]. Sinon, allez à link:setup-and-configure-9336c-shared.html["Configurez le commutateur"].
