---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/migrate-from-switched-configuration-dat-storage.html 
keywords:  
summary:  
---
= Migrer depuis une configuration commutée avec un stockage DAS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez migrer depuis une configuration commutée avec un stockage DAS en ajoutant deux nouveaux commutateurs partagés.

.Commutateurs pris en charge
Les commutateurs suivants sont pris en charge :

* Nexus 9336C-FX2
* Nexus 3232C


Les versions ONTAP et NX-OS prises en charge dans cette procédure se trouvent sur la page des commutateurs Ethernet Cisco. Voir https://["Commutateurs Ethernet Cisco"].

.Ports de connexion
Les switches utilisent les ports suivants pour se connecter aux nœuds :

* Nexus 9336C-FX2 :
+
** Ports 1- 3 : mode d'arrachage (4 x 10 G) ports intra-cluster, int e1/1/1-4, e1/2/1-4, e1/3/1-4
** Ports 4- 6 : mode d'arrachage (4x25G) ports intra-cluster/HA, int e1/4/1-4, e1/5/1-4, e1/6/1-4
** Ports 7-34 : ports intra-clusters/HA 40 GbE, int e1/7-34


* Nexus 3232C :
+
** Ports 1 à 30 : 10 GbE/40/100 GbE


* Les switchs utilisent les ports ISL (Inter-Switch Link) suivants :
+
** Ports int e1/35-36 : Nexus 9336C-FX2
** Ports e1/31-32 : Nexus 3232C




Le https://["Hardware Universe"] le contient des informations sur le câblage pris en charge pour tous les commutateurs de cluster.

.Ce dont vous avez besoin
* Assurez-vous d'avoir effectué les tâches suivantes :
+
** Configuré certains des ports des commutateurs Nexus 9336C-FX2 pour qu'ils fonctionnent à 100 GbE.
** Planification, migration et documentation de la connectivité 100 GbE entre les nœuds et les commutateurs Nexus 9336C-FX2.
** Migration sans interruption des autres commutateurs de cluster Cisco d'un cluster ONTAP vers les commutateurs réseau Cisco Nexus 9336C-FX2.


* Le réseau de commutateurs existant est correctement configuré et opérationnel.
* Tous les ports sont à l'état *up* pour assurer la continuité de l'activité.
* Les commutateurs Nexus 9336C-FX2 sont configurés et fonctionnent sous la version adéquate du système d'exploitation NX-OS installé et le fichier RCF (Reference Configuration File) appliqué.
* La configuration réseau existante comprend les éléments suivants :
+
** Un cluster NetApp redondant et entièrement fonctionnel utilisant les deux anciens commutateurs Cisco.
** Connectivité de gestion et accès à la console aux anciens commutateurs Cisco et aux nouveaux commutateurs.
** Toutes les LIFs de cluster dans l'état *up* avec les LIFs de cluster sont sur leurs ports de base.
** Ports ISL activés et câblés entre les autres commutateurs Cisco et entre les nouveaux commutateurs.




.À propos des exemples
Les exemples de cette procédure utilisent la nomenclature des commutateurs et des nœuds suivante :

* Les switchs de cluster Cisco Nexus 3232C existants sont _c1_ et _c2_.
* Les nouveaux commutateurs Nexus 9336C-FX2 sont _sh1_ et _sh2_.
* Les nœuds sont _node1_ et _node2_.
* Les LIFS du cluster sont respectivement _node1_clum1_ et _node1_clum2_ sur le nœud 1 et _node2_clum1_ et _node2_clum2_ sur le nœud 2.
* Le contacteur c2 est d'abord remplacé par le contacteur sh2, puis le contacteur c1 est remplacé par le contacteur sh1.


.Étapes
. Si AutoSupport est activé sur ce cluster, supprimez la création automatique de dossiers en invoquant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=x h`

+
Où x représente la durée de la fenêtre de maintenance en heures.

. Vérifiez le statut administratif et opérationnel de chaque port du cluster.
. Vérifier que tous les ports du cluster sont défectueux :
+
`network port show –role cluster`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -role cluster*
Node: node1
                                                                   Ignore
                                             Speed(Mbps)  Health   Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Ope    Status   Status
------- --------- ---------------- ---- ---- ------------ -------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                   Ignore
                                             Speed(Mbps) Health    Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Oper  Status    Status
------- --------- ---------------- ---- ---- ----------- --------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
cluster1::*>
----
====


. [[step4]]vérifier que toutes les interfaces de cluster (LIFs) sont sur le port de home Port :
+
`network interface show -role cluster`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical     Status     Network           Current     Current Is
Vserver  Interface   Admin/Oper Address/Mask      Node        Port    Home
-------  ----------- ---------- ----------------- ----------- ------- ----
Cluster
        node1_clus1  up/up      169.254.3.4/23    node1       e3a     true
        node1_clus2  up/up      169.254.3.5/23    node1       e3b     true
        node2_clus1  up/up      169.254.3.8/23    node2       e3a     true
        node2_clus2  up/up      169.254.3.9/23    node2       e3b     true
4 entries were displayed.
cluster1::*>
----
====


. [[step5]]Vérifiez que le cluster affiche les informations des deux commutateurs de cluster :
+
`system cluster-switch show -is-monitoring-enabled-operational true`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                    Type               Address          Model
------------------------- ------------------ ---------------- ------
sh1                       cluster-network    10.233.205.90    N9K-C9336C
     Serial Number: FOCXXXXXXGD
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
sh2                       cluster-network    10.233.205.91    N9K-C9336C
     Serial Number: FOCXXXXXXGS
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
cluster1::*>
----
====


. [[step6]]Désactiver la fonction de restauration automatique sur les LIFs du cluster.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
====


. [[étape7]]Arrêter l'interrupteur c2.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
c2# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c2(config)# *interface ethernet <int range>*
c2(config)# *shutdown*
----
====


. [[step8]]vérifier que les LIFs de cluster ont migré vers les ports hébergés sur le commutateur de cluster sh1 :
+
`network interface show -role cluster`

+
Cette opération peut prendre quelques secondes.

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
          Logical     Status     Network         Current      Current  Is
Vserver   Interface   Admin/Oper Address/Mask    Node         Port     Home
--------- ----------- ---------- --------------- ------------ -------- -----
Cluster
          node1_clus1 up/up      169.254.3.4/23  node1        e3a      true
          node1_clus2 up/up      169.254.3.5/23  node1        e3a      false
          node2_clus1 up/up      169.254.3.8/23  node2        e3a      true
          node2_clus2 up/up      169.254.3.9/23  node2        e3a      false
4 entries were displayed.
cluster1::*>
----
====


. [[étape9]]remplacer le commutateur c2 par le nouveau commutateur sh2 et recouvrez le câble du nouveau commutateur.
. Vérifiez que les ports sont en marche arrière sur le sh2. *Remarque* que les LIFs sont toujours sur le commutateur c1.
. Arrêter le contacteur c1.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
c1# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c1(config)# *interface ethernet <int range>*
c1(config)# *shutdown*
----
====


. [[step12]]vérifier que les LIFs de cluster ont migré vers les ports hébergés sur le commutateur sh2 du cluster. Cette opération peut prendre quelques secondes.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical        Status     Network         Current   Current Is
Vserver  Interface      Admin/Oper Address/Mask    Node      Port    Home
-------- -------------- ---------- --------------- --------- ------- ----
Cluster
         node1_clus1    up/up      169.254.3.4/23  node1     e3a     true
         node1_clus2    up/up      169.254.3.5/23  node1     e3a     false
         node2_clus1    up/up      169.254.3.8/23  node2     e3a     true
         node2_clus2    up/up      169.254.3.9/23  node2     e3a     false
4 entries were displayed.
cluster1::*>
----
====


. [[step13]]remplacer l'interrupteur c1 par le nouvel interrupteur sh1 et recarbler le nouveau contacteur.
. Vérifiez que les ports sont en secours sur le sh1. *Remarque* que les LIFs sont toujours sur le commutateur c2.
. Activer la fonction de revert automatique sur les LIFs du cluster :
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert True*
----
====


. [[step16]]vérifier que le cluster fonctionne correctement :
+
`cluster show`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
cluster1::*>
----
====

