---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/migrate-from-switchless-cluster-dat-storage.html 
keywords:  
summary:  
---
= Migrer depuis un cluster sans commutateur avec stockage à connexion directe
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez migrer depuis un cluster sans commutateur avec stockage à connexion directe en ajoutant deux nouveaux commutateurs partagés.

La procédure à suivre dépend du fait que chaque contrôleur dispose de deux ports réseau de cluster dédiés ou d'un seul port de cluster par contrôleur.  Le processus décrit fonctionne pour tous les nœuds utilisant des ports optiques ou Twinax, mais n'est pas pris en charge sur ce commutateur si les nœuds utilisent des ports RJ45 10Gb BASE-T intégrés pour les ports du réseau de cluster.

La plupart des systèmes nécessitent deux ports réseau dédiés au cluster sur chaque contrôleur. Voir https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Commutateurs Ethernet Cisco"] pour plus d'informations.

Si vous disposez déjà d'un environnement de cluster sans commutateur à deux nœuds, vous pouvez migrer vers un environnement de cluster commuté à deux nœuds à l'aide de commutateurs Cisco Nexus 9336C-FX2 pour vous permettre d'évoluer au-delà de deux nœuds dans le cluster.



== Exigences de révision

Assurez-vous que :

* Pour la configuration sans commutateur à deux nœuds :
+
** La configuration sans commutateur à deux nœuds est correctement mise en place et fonctionne.
** Les nœuds exécutent ONTAP 9.8 et versions ultérieures.
** Tous les ports du cluster sont en état de fonctionnement.
** Toutes les interfaces logiques du cluster (LIF) sont à l'état *actif* et sur leurs ports *domicile*.


* Pour la configuration du commutateur Cisco Nexus 9336C-FX2 :
+
** Les deux commutateurs disposent d'une connectivité au réseau de gestion.
** Il existe un accès console aux commutateurs du cluster.
** Les connexions de commutateur à commutateur et de commutateur à nœud Nexus 9336C-FX2 utilisent des câbles Twinax ou à fibre optique.
** NetApp https://hwu.netapp.com["Hardware Universe"] Contient plus d'informations sur le câblage.
** Les câbles Inter-Switch Link (ISL) sont connectés aux ports 1/35 et 1/36 sur les deux commutateurs 9336C-FX2.


* La personnalisation initiale des commutateurs 9336C-FX2 est terminée.  Afin que :
+
** Les commutateurs 9336C-FX2 exécutent la dernière version du logiciel
** Des fichiers de configuration de référence (RCF) ont été appliqués aux commutateurs
** Toute personnalisation du site, telle que SMTP, SNMP et SSH, est configurée sur les nouveaux commutateurs.






== Déplacer les commutateurs

.À propos des exemples
Les exemples de cette procédure utilisent la nomenclature suivante pour les commutateurs de cluster et les nœuds :

* Les noms des commutateurs 9336C-FX2 sont _cs1_ et _cs2_.
* Les noms des SVM du cluster sont _node1_ et _node2_.
* Les noms des LIF sont _node1_clus1_ et _node1_clus2_ sur le nœud 1, et _node2_clus1_ et _node2_clus2_ sur le nœud 2 respectivement.
* L'invite cluster1::*> indique le nom du cluster.
* Les ports de cluster utilisés dans cette procédure sont _e3a_ et _e3b_, conformément au contrôleur AFF A400 .  Le https://hwu.netapp.com["Hardware Universe"] Contient les informations les plus récentes concernant les ports de cluster actuels pour vos plateformes.




=== Étape 1 : Migration depuis un groupe sans commutateur avec connexion directe

. Si AutoSupport est activé sur ce cluster, supprimez la création automatique de cas en envoyant un message AutoSupport : `system node autosupport invoke -node * -type all -message MAINT=xh` .
+
où x représente la durée de la fenêtre de maintenance en heures.




NOTE: Le message AutoSupport notifie le support technique de cette tâche de maintenance afin que la création automatique de tickets soit désactivée pendant la période de maintenance.

. [[étape 2]]Modifiez le niveau de privilège en avancé, en saisissant « y » lorsque vous êtes invité à continuer :
+
`set -privilege advanced`

+
L'invite avancée (*>) apparaît.

. Désactivez tous les ports orientés vers les nœuds (à l'exception des ports ISL) sur les deux nouveaux commutateurs de cluster cs1 et cs2.  Vous ne devez pas désactiver les ports ISL.
+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre que les ports 1 à 34 orientés vers le nœud sont désactivés sur le commutateur cs1 :

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-34*
cs1(config-if-range)# *shutdown*
----
====


. [[étape 4]]Vérifiez que l'ISL et les ports physiques sur l'ISL entre les deux commutateurs 9336C-FX2 cs1 et cs2 sont actifs sur les ports 1/35 et 1/36 :
+
`show port-channel summary`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre que les ports ISL sont opérationnels sur le commutateur cs1 :

[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
L'exemple suivant montre que les ports ISL sont opérationnels sur le commutateur cs2 :

[listing, subs="+quotes"]
----
       cs2# *show port-channel summary*
        Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
====


. [[étape 5]]Afficher la liste des appareils voisins :
+
`show cdp neighbors`

+
Cette commande fournit des informations sur les périphériques connectés au système.

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant répertorie les périphériques voisins sur le commutateur cs1 :

[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 2
----
L'exemple suivant liste les périphériques voisins sur le commutateur cs2 :

[listing, subs="+quotes"]
----
cs2# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1                Eth1/35        177    R S I s     N9K-C9336C    Eth1/35
cs1           )    Eth1/36        177    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
====


. [[étape 6]]Vérifiez que tous les ports du cluster sont actifs :
+
`network port show - ipspace Cluster`

+
Chaque port doit afficher « actif » pour la liaison et « sain » pour l’état de santé.

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy

Node: node2
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy
4 entries were displayed.
----
====


. [[étape 7]]Vérifiez que tous les LIF du cluster sont opérationnels :
+
`network interface show - vserver Cluster`

+
Chaque LIF de cluster doit afficher vrai pour `Is Home` et avoir un statut Administrateur/Opérateur actif/actif.

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical     Status     Network            Current       Current Is
Vserver     Interface   Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
4 entries were displayed.
----
====


. [[étape 8]]Vérifiez que la restauration automatique est activée sur toutes les LIF du cluster :
+
`network interface show - vserver Cluster -fields auto-revert`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*
       Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
4 entries were displayed.
----
====


. [[étape9]]Débranchez le câble du port de cluster e3a sur le nœud 1, puis connectez e3a au port 1 sur le commutateur de cluster cs1, en utilisant le câblage approprié pris en charge par les commutateurs 9336C-FX2.
+
NetApp https://hwu.netapp.com["Hardware Universe"] Contient plus d'informations sur le câblage. Voir link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["De quelles informations supplémentaires ai-je besoin pour installer mon équipement qui ne figure pas dans HWU ?"^] pour plus d'informations sur les exigences d'installation du commutateur.

. Déconnectez le câble du port de cluster e3a sur node2, puis connectez e3a au port 2 sur le commutateur de cluster cs1, à l'aide du câblage approprié pris en charge par les commutateurs 9336C-FX2.
. Activez tous les ports orientés vers les nœuds sur le commutateur de cluster cs1.
+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre que les ports 1/1 à 1/34 sont activés sur le commutateur cs1 :

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-34*
cs1(config-if-range)# *no shutdown*
----
====


. [[étape 12]]Vérifiez que tous les LIF du cluster sont *actifs*, opérationnels et affichent la valeur « vrai » pour `Is Home` :
+
`network interface show - vserver Cluster`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre que tous les LIF sont *actifs* sur les nœuds 1 et 2 et que `Is Home` Les résultats sont *véridiques* :

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
          Logical      Status     Network            Current     Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node        Port    Home
--------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1       e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1       e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2       e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2       e3b     true
4 entries were displayed.
----
====


. [[étape 13]]Afficher les informations relatives à l'état des nœuds du cluster :
+
`cluster show`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant présente des informations sur l'état et l'éligibilité des nœuds du cluster :

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
====


. [[étape 14]]Débranchez le câble du port de cluster e3b sur le nœud 1, puis connectez e3b au port 1 sur le commutateur de cluster cs2, en utilisant le câblage approprié pris en charge par les commutateurs 9336C-FX2.
. Déconnectez le câble du port de cluster e3b sur node2, puis connectez e3b au port 2 sur le commutateur de cluster cs2, à l'aide du câblage approprié pris en charge par les commutateurs 9336C-FX2.
. Activez tous les ports orientés vers les nœuds sur le commutateur de cluster cs2.
+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre que les ports 1/1 à 1/34 sont activés sur le commutateur cs2 :

[listing, subs="+quotes"]
----
cs2# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs2(config)# *interface e1/1-34*
cs2(config-if-range)# *no shutdown*
----
====


. [[étape 17]]Vérifiez que tous les ports du cluster sont actifs :
+
`network port show - ipspace Cluster`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre que tous les ports du cluster sont opérationnels sur les nœuds 1 et 2 :

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
----
====


. [[étape 18]]Vérifiez que toutes les interfaces affichent « vrai » pour `Is Home` :
+
`network interface show - vserver Cluster`

+

NOTE: Cela peut prendre plusieurs minutes.

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre que tous les LIF sont *actifs* sur les nœuds 1 et 2 et que `Is Home` Les résultats sont exacts :

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e3b     true
4 entries were displayed.
----
====


. [[étape 19]]Vérifiez que chaque nœud possède une connexion à chaque commutateur :
+
`show cdp neighbors`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant illustre les résultats attendus pour les deux commutateurs :

[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3a
node2              Eth1/2         133    H           AFFA400       e3a
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
cs2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3b
node2              Eth1/2         133    H           AFFA400       e3b
cs1                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
----
====


. [[step20]]Afficher les informations sur les périphériques réseau détectés dans votre cluster :
+
`network device-discovery show -protocol cdp`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2       /cdp
            e3a    cs1                       0/2               N9K-C9336C
            e3b    cs2                       0/2               N9K-C9336C

node1       /cdp
            e3a    cs1                       0/1               N9K-C9336C
            e3b    cs2                       0/1               N9K-C9336C
4 entries were displayed.
----
====


. [[étape 21]]Vérifiez que la configuration de stockage de la paire HA 1 (et de la paire HA 2) est correcte et sans erreur :
+
`system switch ethernet show`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address         Model
------------------------- ---------------------- --------------- ----------
sh1
                          storage-network        172.17.227.5    C9336C

       Serial Number: FOC221206C2
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
====


. [[étape 22]]Vérifiez que les paramètres sont désactivés :
+
`network options switchless-cluster show`

+

NOTE: L'exécution de la commande peut prendre plusieurs minutes.  Attendez l'annonce « Durée de vie de 3 minutes expirée ».

+
Le `false` L'exemple suivant montre que les paramètres de configuration sont désactivés :

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network options switchless-cluster show*
Enable Switchless Cluster: false
----
====


. [[étape 23]]Vérifiez l'état des nœuds membres du cluster :
+
`cluster show`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant présente des informations sur l'état et l'éligibilité des nœuds du cluster :

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. Vérifiez la connectivité des interfaces du cluster distant :


[role="tabbed-block"]
====
.ONTAP 9.9.1 et versions ultérieures
--
Vous pouvez utiliser le `network interface check cluster-connectivity` commande permettant de lancer une vérification d'accessibilité pour la connectivité du cluster, puis d'afficher les détails :

`network interface check cluster-connectivity start`et `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*REMARQUE :* Attendez quelques secondes avant d’exécuter le programme. `show` commande pour afficher les détails.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Toutes les versions ONTAP
--
Pour toutes les versions ONTAP , vous pouvez également utiliser `cluster ping-cluster -node <name>` commande pour vérifier la connectivité :

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[étape 25]] Rétablissez le niveau de privilège à administrateur :
+
`set -privilege admin`





=== Étape 2 : Configurer le commutateur partagé

Les exemples de cette procédure utilisent la nomenclature suivante pour les commutateurs et les nœuds :

* Les noms des deux commutateurs partagés sont _sh1_ et _sh2_.
* Les nœuds sont _node1_ et _node2_.



NOTE: La procédure nécessite l'utilisation à la fois des commandes ONTAP et des commandes des commutateurs Cisco Nexus série 9000 ; les commandes ONTAP sont utilisées sauf indication contraire.

. Vérifiez que la configuration de stockage de la paire HA 1 (et de la paire HA 2) est correcte et sans erreur :
+
`system switch ethernet show`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address         Model
------------------------- ---------------------  --------------- -------
sh1
                          storage-network        172.17.227.5    C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
====
. Vérifiez que les ports du nœud de stockage sont sains et opérationnels :
+
`storage port show -port-type ENET`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage          100      enabled  online        30
        e5a     ENET   storage          100      enabled  online        30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage           100      enabled  online        30
        e5a     ENET  storage           100      enabled  online        30
        e5b     ENET  storage           100      enabled  online        30
----
====


. [[étape 3]]Déplacez la paire HA 1, les ports du chemin A du NSM224 vers la plage de ports sh1 11-22.
. Installez un câble de la paire HA 1, nœud 1, chemin A à la plage de ports sh1 11-22.  Par exemple, le chemin du port de stockage A sur un AFF A400 est e0c.
. Installez un câble de la paire HA 1, nœud 2, chemin A à la plage de ports sh1 11-22.
. Vérifiez que les ports du nœud sont sains et opérationnels :
+
`storage port show -port-type ENET`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
====
. Vérifiez qu'il n'y a pas de problèmes de commutateur de stockage ou de câblage avec le cluster :
+
`system health alert show -instance`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system health alert show -instance*
There are no entries matching your query.
----
====
. Déplacez la paire HA 1, les ports du chemin B du NSM224 vers la plage de ports sh2 11-22.
. Installez un câble de la paire HA 1, nœud 1, chemin B à la plage de ports sh2 11-22.  Par exemple, le port de stockage du chemin B sur un AFF A400 est e5b.
. Installez un câble de la paire HA 1, nœud 2, chemin B à la plage de ports sh2 11-22.
. Vérifiez que les ports du nœud sont sains et opérationnels :
+
`storage port show -port-type ENET`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
====
. Vérifiez que la configuration de stockage de la paire HA 1 est correcte et sans erreur :
+
`system switch ethernet show`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address          Model
------------------------- ---------------------- ---------------- ----------
sh1
                          storage-network        172.17.227.5     C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6     C9336C
      Serial Number: FOC220443LZ
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
2 entries were displayed.
storage::*>
----
====
. Reconfigurez les ports de stockage secondaires (contrôleur) inutilisés sur la paire HA 1 de stockage à réseau.  Si plusieurs NS224 étaient connectés directement, certains ports devraient être reconfigurés.
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
storage port modify –node [node name] –port [port name] –mode network
----
====
+
Pour placer les ports de stockage dans un domaine de diffusion :

+
** `network port broadcast-domain create`(pour créer un nouveau domaine, si nécessaire)
** `network port broadcast-domain add-ports`(pour ajouter des ports à un domaine existant)


. Si vous avez désactivé la création automatique de dossiers, réactivez-la en envoyant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.Quelle est la prochaine étape ?
Une fois vos commutateurs migrés, vous pouvez link:../switch-cshm/config-overview.html["configurer la surveillance de l'état du commutateur"].
