---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/migrate-from-switched-configuration-dat-storage.html 
keywords:  
summary:  
---
= Migrer depuis une configuration commutée avec stockage à connexion directe
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez migrer depuis une configuration à commutation avec stockage à connexion directe en ajoutant deux nouveaux commutateurs partagés.

.Commutateurs pris en charge
Les commutateurs suivants sont pris en charge :

* Nexus 9336C-FX2
* Nexus 3232C


Les versions ONTAP et NX-OS prises en charge dans cette procédure sont indiquées sur la page des commutateurs Ethernet Cisco . Voir https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Commutateurs Ethernet Cisco"] .

.ports de connexion
Les commutateurs utilisent les ports suivants pour se connecter aux nœuds :

* Nexus 9336C-FX2 :
+
** Ports 1 à 3 : Mode Breakout (4 x 10 Gbit/s) Ports intra-cluster, int e1/1/1-4, e1/2/1-4, e1/3/1-4
** Ports 4 à 6 : Mode Breakout (4 x 25 Gbit/s) Ports intra-cluster/HA, int e1/4/1-4, e1/5/1-4, e1/6/1-4
** Ports 7-34 : Ports intra-cluster/HA 40/100 GbE, int e1/7-34


* Nexus 3232C :
+
** Ports 1 à 30 : 10/40/100 GbE


* Les commutateurs utilisent les ports de liaison inter-commutateurs (ISL) suivants :
+
** Ports int e1/35-36 : Nexus 9336C-FX2
** Ports e1/31-32 : Nexus 3232C




Le https://hwu.netapp.com["Hardware Universe"] Contient des informations sur le câblage pris en charge pour tous les commutateurs du cluster.

.Ce dont vous aurez besoin
* Assurez-vous d'avoir effectué les tâches suivantes :
+
** J'ai configuré certains ports des commutateurs Nexus 9336C-FX2 pour qu'ils fonctionnent à 100 GbE.
** Planification, migration et documentation de la connectivité 100 GbE des nœuds vers les commutateurs Nexus 9336C-FX2.
** Migration sans interruption d'autres commutateurs de cluster Cisco d'un cluster ONTAP vers des commutateurs réseau Cisco Nexus 9336C-FX2.


* Le réseau de commutation existant est correctement configuré et fonctionnel.
* Tous les ports sont opérationnels afin de garantir un fonctionnement sans interruption.
* Les commutateurs Nexus 9336C-FX2 sont configurés et fonctionnent sous la version appropriée de NX-OS installée et le fichier de configuration de référence (RCF) appliqué.
* La configuration réseau existante est la suivante :
+
** Un cluster NetApp redondant et pleinement fonctionnel utilisant des commutateurs Cisco plus anciens.
** Connectivité de gestion et accès console aux anciens commutateurs Cisco et aux nouveaux commutateurs.
** Toutes les LIF du cluster à l'état *actif* sont sur leurs ports d'origine.
** Les ports ISL sont activés et câblés entre les autres commutateurs Cisco et entre les nouveaux commutateurs.




.À propos des exemples
Les exemples de cette procédure utilisent la nomenclature suivante pour les commutateurs et les nœuds :

* Les commutateurs de cluster Cisco Nexus 3232C existants sont _c1_ et _c2_.
* Les nouveaux commutateurs Nexus 9336C-FX2 sont _sh1_ et _sh2_.
* Les nœuds sont _node1_ et _node2_.
* Les LIF du cluster sont _node1_clus1_ et _node1_clus2_ sur le nœud 1, et _node2_clus1_ et _node2_clus2_ sur le nœud 2 respectivement.
* L'interrupteur c2 est d'abord remplacé par l'interrupteur sh2, puis l'interrupteur c1 est remplacé par l'interrupteur sh1.


.Étapes
. Si AutoSupport est activé sur ce cluster, supprimez la création automatique de cas en envoyant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=x h`

+
Où x représente la durée de la fenêtre de maintenance en heures.

. Vérifiez l'état administratif et opérationnel de chaque port du cluster.
. Vérifiez que tous les ports du cluster sont opérationnels et en bon état :
+
`network port show –role cluster`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -role cluster*
Node: node1
                                                                   Ignore
                                             Speed(Mbps)  Health   Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Ope    Status   Status
------- --------- ---------------- ---- ---- ------------ -------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                   Ignore
                                             Speed(Mbps) Health    Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Oper  Status    Status
------- --------- ---------------- ---- ---- ----------- --------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
cluster1::*>
----
====


. [[étape 4]]Vérifiez que toutes les interfaces du cluster (LIF) sont sur le port principal :
+
`network interface show -role cluster`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical     Status     Network           Current     Current Is
Vserver  Interface   Admin/Oper Address/Mask      Node        Port    Home
-------  ----------- ---------- ----------------- ----------- ------- ----
Cluster
        node1_clus1  up/up      169.254.3.4/23    node1       e3a     true
        node1_clus2  up/up      169.254.3.5/23    node1       e3b     true
        node2_clus1  up/up      169.254.3.8/23    node2       e3a     true
        node2_clus2  up/up      169.254.3.9/23    node2       e3b     true
4 entries were displayed.
cluster1::*>
----
====


. [[étape 5]]Vérifiez que le cluster affiche les informations pour les deux commutateurs du cluster :
+
`system cluster-switch show -is-monitoring-enabled-operational true`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                    Type               Address          Model
------------------------- ------------------ ---------------- ------
sh1                       cluster-network    10.233.205.90    N9K-C9336C
     Serial Number: FOCXXXXXXGD
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
sh2                       cluster-network    10.233.205.91    N9K-C9336C
     Serial Number: FOCXXXXXXGS
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
cluster1::*>
----
====


. [[étape6]]Désactiver la restauration automatique sur les LIF du cluster.
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
====


. [[étape 7]] Fermez l'interrupteur c2.
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
c2# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c2(config)# *interface ethernet <int range>*
c2(config)# *shutdown*
----
====


. [[étape 8]]Vérifiez que les LIF du cluster ont migré vers les ports hébergés sur le commutateur de cluster sh1 :
+
`network interface show -role cluster`

+
Cela peut prendre quelques secondes.

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
          Logical     Status     Network         Current      Current  Is
Vserver   Interface   Admin/Oper Address/Mask    Node         Port     Home
--------- ----------- ---------- --------------- ------------ -------- -----
Cluster
          node1_clus1 up/up      169.254.3.4/23  node1        e3a      true
          node1_clus2 up/up      169.254.3.5/23  node1        e3a      false
          node2_clus1 up/up      169.254.3.8/23  node2        e3a      true
          node2_clus2 up/up      169.254.3.9/23  node2        e3a      false
4 entries were displayed.
cluster1::*>
----
====


. [[étape 9]]Remplacez l'interrupteur c2 par le nouvel interrupteur sh2 et recâblez le nouvel interrupteur.
. Vérifiez que les ports sont de nouveau opérationnels sur sh2.  *Notez* que les LIF sont toujours sur le commutateur c1.
. Coupez l'alimentation de l'interrupteur c1.
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
c1# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c1(config)# *interface ethernet <int range>*
c1(config)# *shutdown*
----
====


. [[étape 12]]Vérifiez que les LIF du cluster ont migré vers les ports hébergés sur le commutateur de cluster sh2. Cela peut prendre quelques secondes.
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical        Status     Network         Current   Current Is
Vserver  Interface      Admin/Oper Address/Mask    Node      Port    Home
-------- -------------- ---------- --------------- --------- ------- ----
Cluster
         node1_clus1    up/up      169.254.3.4/23  node1     e3a     true
         node1_clus2    up/up      169.254.3.5/23  node1     e3a     false
         node2_clus1    up/up      169.254.3.8/23  node2     e3a     true
         node2_clus2    up/up      169.254.3.9/23  node2     e3a     false
4 entries were displayed.
cluster1::*>
----
====


. [[étape 13]]Remplacez l'interrupteur c1 par le nouvel interrupteur sh1 et recâblez le nouvel interrupteur.
. Vérifiez que les ports sont de nouveau opérationnels sur sh1.  *Notez* que les LIF sont toujours sur le commutateur c2.
. Activer la restauration automatique sur les LIF du cluster :
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert True*
----
====


. [[étape 16]]Vérifiez que le cluster est sain :
+
`cluster show`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
cluster1::*>
----
====


.Quelle est la prochaine étape ?
Une fois vos commutateurs migrés, vous pouvez link:../switch-cshm/config-overview.html["configurer la surveillance de l'état du commutateur"].
