---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/replace-9336c-fx2-shared.html 
keywords:  
summary:  
---
= Remplacer un commutateur partagé Cisco Nexus 9336C-FX2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez remplacer un commutateur partagé Nexus 9336C-FX2 défectueux. Il s'agit d'une procédure sans interruption.

.Ce dont vous avez besoin
Avant d'effectuer le remplacement du commutateur, assurez-vous que :

* Dans l'infrastructure réseau et en cluster existante :
+
** Le cluster existant est vérifié entièrement fonctionnel, avec au moins un commutateur de cluster entièrement connecté.
** Tous les ports de cluster sont *up*.
** Toutes les interfaces logiques (LIF) de cluster sont *up* et sur leurs ports de type home.
** La commande ping-cluster -nœud node1 du cluster ONTAP doit indiquer que la connectivité de base et une communication plus importante que la communication PMTU atteignent tous les chemins.


* Pour le commutateur de remplacement Nexus 9336C-FX2 :
+
** La connectivité réseau de gestion sur le commutateur de remplacement est fonctionnelle.
** L'accès à la console au commutateur de remplacement est en place.
** Les ports 1/1 à 1/34 sont les connexions de nœud :
** Tous les ports ISL (Inter-Switch Link) sont désactivés sur les ports 1/35 et 1/36.
** Le fichier RCF souhaité et le commutateur d'image du système d'exploitation NX-OS sont chargés sur ce commutateur.
** Toute personnalisation de site antérieure, telle que STP, SNMP et SSH, doit être copiée sur le nouveau commutateur.




.À propos des exemples
Vous devez exécuter la commande pour migrer une LIF de cluster à partir du nœud sur lequel la LIF de cluster est hébergée.

Les exemples de cette procédure utilisent la nomenclature des commutateurs et des nœuds suivante :

* Les noms des commutateurs Nexus 9336C-FX2 existants sont _sh1_ et _sh2_.
* Le nom des nouveaux commutateurs Nexus 9336C-FX2 est _newsh1_ et _newsh2_.
* Les noms de nœud sont _node1_ et _node2_.
* Les ports de cluster de chaque nœud sont nommés _e3a_ et _e3b_.
* Les noms LIF de cluster sont `node1_clus1` et `node1_clus2` pour le noeud 1, et `node2_clus1` et `node2_clus2` pour le noeud 2.
* Le système invite pour les modifications à tous les nœuds du cluster est cluster1 :*>.
+

NOTE: La procédure suivante est basée sur la topologie réseau suivante :



.Montrer l'exemple de topologie
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.


cluster1::*> *network interface show -vserver Cluster*
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
4 entries were displayed.

cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e3a    sh1                       Eth1/2            N9K-C9336C
            e3b    sh2                       Eth1/2            N9K-C9336C

node1      /cdp
            e3a    sh1                       Eth1/1            N9K-C9336C
            e3b    sh2                       Eth1/1            N9K-C9336C
4 entries were displayed.

sh1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         144    H           FAS2980       e3a
node2              Eth1/2         145    H           FAS2980       e3a
sh2                Eth1/35        176    R S I s     N9K-C9336C    Eth1/35
sh2 (FDO220329V5)   Eth1/36       176    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4

sh2# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         139    H           FAS2980       eb
node2              Eth1/2         124    H           FAS2980       eb
sh1                Eth1/35        178    R S I s     N9K-C9336C    Eth1/35
sh1                Eth1/36        178    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
----
====
.Étapes
. Si AutoSupport est activé sur ce cluster, supprimez la création automatique de dossiers en invoquant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
Où x représente la durée de la fenêtre de maintenance en heures.

. Facultatif : installez la FCR et l'image appropriées sur le commutateur, newsh2, et effectuez les préparations nécessaires du site.
+
.. Si nécessaire, vérifiez, téléchargez et installez les versions appropriées des logiciels RCF et NX-OS pour le nouveau commutateur. Si vous avez vérifié que le nouveau switch est correctement configuré et qu'il n'a pas besoin de mises à jour du logiciel RCF et NX-OS, passez à la <<step3,Étape 3>>.
.. Accédez à la page de description des commutateurs de réseau de gestion et de cluster NetApp sur le site de support NetApp.
.. Cliquez sur le lien correspondant à la matrice de compatibilité du réseau de clusters et du réseau de gestion, puis notez la version du logiciel du commutateur requise.
.. Cliquez sur la flèche vers l'arrière de votre navigateur pour revenir à la page Description, cliquez SUR CONTINUER, acceptez le contrat de licence, puis accédez à la page de téléchargement.
.. Suivez les étapes de la page de téléchargement pour télécharger les fichiers RCF et NX-OS appropriés correspondant à la version du logiciel ONTAP que vous installez.


. [[step3]]]sur le nouveau commutateur, connectez-vous en tant qu'administrateur et arrêtez tous les ports qui seront connectés aux interfaces du cluster de nœuds (ports 1/1 à 1/34). Si le commutateur que vous remplacez ne fonctionne pas et est hors tension, passer à <<step4,Étape 4>>. Les LIFs des nœuds du cluster doivent déjà avoir basculer sur l'autre port du cluster pour chaque nœud.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
newsh2# *config*
Enter configuration commands, one per line. End with CNTL/Z.
newsh2(config)# *interface e1/1-34*
newsh2(config-if-range)# *shutdown*
----
====


. [[step4]]Vérifiez que toutes les LIF de cluster ont activé la fonction de restauration automatique.
+
`network interface show - vserver Cluster -fields auto-revert`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster -fields auto-revert*
             Logical
Vserver      Interface     Auto-revert
------------ ------------- -------------
Cluster      node1_clus1   true
Cluster      node1_clus2   true
Cluster      node2_clus1   true
Cluster      node2_clus2   true
4 entries were displayed.
----
====


. [[step5]]vérifier que toutes les LIFs du cluster peuvent communiquer :
+
`cluster ping-cluster <node name>`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====


. [[step6]]Arrêter les ports ISL 1/35 et 1/36 du commutateur Nexus 9336C-FX2 sh1.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
sh1# *configure*
Enter configuration commands, one per line. End with CNTL/Z.
sh1(config)# *interface e1/35-36*
sh1(config-if-range)# *shutdown*
----
====


. [[étape7]]retirez tous les câbles du commutateur nexus 9336C-FX2 sh2, puis connectez-les aux mêmes ports du commutateur Nexus C9336C-FX2 newsh2.
. Mettez les ports ISL 1/35 et 1/36 entre les commutateurs sh1 et newsh2, puis vérifiez le statut du canal de port.
+
Port-Channel devrait indiquer Po1(SU) et les ports membres devraient indiquer eth1/35(P) et eth1/36(P).

+
.Montrer l'exemple
[%collapsible]
====
Cet exemple active les ports ISL 1/35 et 1/36 et affiche le résumé du canal de port sur le commutateur sh1.

[listing, subs="+quotes"]
----
sh1# *configure*
Enter configuration commands, one per line. End with CNTL/Z.
sh1 (config)# *int e1/35-36*
sh1 (config-if-range)# *no shutdown*
sh1 (config-if-range)# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member       Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)

sh1 (config-if-range)#
----
====


. [[step9]]Vérifiez que le port e3b est actif sur tous les nœuds :
+
`network port show ipspace Cluster`

+
.Montrer l'exemple
[%collapsible]
====
La sortie doit être comme suit :

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                         Ignore
                                                   Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ----- ---------- - - -------- ----
e3a       Cluster      Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                         Ignore
                                                   Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ----- ----------- -  -------- ----
e3a       Cluster      Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster      Cluster          up   9000  auto/auto    -        false
4 entries were displayed.
----
====


. [[step10]]]sur le même nœud que vous avez utilisé lors de l'étape précédente, ne rétablit pas la LIF de cluster associée au port de l'étape précédente à l'aide de la commande network interface revert.
+
Dans cet exemple, LIF node1_clus2 sur le nœud1 est rétablie avec succès si la valeur Home est true et si le port est e3b.

+
Les commandes suivantes renvoient LIF nœud1_clus2 sur le nœud 1 au port d'accueil e3a et affiche des informations sur les LIF sur les deux nœuds. L'ajout du premier nœud a réussi si la colonne is Home est *true* pour les deux interfaces de cluster et ils affichent les affectations de ports correctes, dans cet exemple e3a et e3b sur le noeud 1.

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical      Status     Network            Current    Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node       Port    Home
----------- ------------ ---------- ------------------ ---------- ------- -----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
            node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
            node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
            node2_clus2  up/up      169.254.19.183/16  node2      e3a     false
4 entries were displayed.
----
====


. [[step11]]affiche les informations sur les nœuds d'un cluster :
+
`cluster show`

+
.Montrer l'exemple
[%collapsible]
====
Cet exemple indique que le nœud Health pour les nœuds 1 et 2 de ce cluster est vrai :

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node          Health  Eligibility
------------- ------- ------------
node1         false   true
node2         true    true
----
====


. [[step12]]Vérifiez que tous les ports physiques du cluster sont présents :
+
`network port show ipspace Cluster`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node node1                                                                Ignore
                                                    Speed(Mbps)  Health   Health
Port      IPspace     Broadcast Domain  Link  MTU   Admin/Oper   Status   Status
--------- ----------- ----------------- ----- ----- ------------ -------- ------
e3a       Cluster     Cluster           up    9000  auto/100000  healthy  false
e3b       Cluster     Cluster           up    9000  auto/100000  healthy  false

Node: node2
                                                                          Ignore
                                                    Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link  MTU   Admin/Oper   Status   Status
--------- ------------ ---------------- ----- ----- ------------ -------- ------
e3a       Cluster      Cluster          up    9000  auto/100000  healthy  false
e3b       Cluster      Cluster          up    9000  auto/100000  healthy  false
4 entries were displayed.
----
====


. [[step13]]vérifier que toutes les LIFs du cluster peuvent communiquer :
+
`cluster ping-cluster`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====


. [[step14]]Confirmez la configuration réseau de cluster suivante :
+
`network port show`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                       Speed(Mbps)             Health   Health
Port      IPspace     Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ----------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster     Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster     Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                        Ignore
                                        Speed(Mbps)            Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000 auto/100000  healthy  false
e3b       Cluster      Cluster          up   9000 auto/100000  healthy  false
4 entries were displayed.

cluster1::*> *network interface show -vserver Cluster*
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
4 entries were displayed.

cluster1::> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e3a    sh1    0/2               N9K-C9336C
            e3b    newsh2                    0/2               N9K-C9336C
node1      /cdp
            e3a    sh1                       0/1               N9K-C9336C
            e3b    newsh2                    0/1               N9K-C9336C
4 entries were displayed.

sh1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID            Local Intrfce  Hldtme Capability  Platform      Port ID
node1                Eth1/1         144    H           FAS2980       e3a
node2                Eth1/2         145    H           FAS2980       e3a
newsh2               Eth1/35        176    R S I s     N9K-C9336C    Eth1/35
newsh2               Eth1/36        176    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4

sh2# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         139    H           FAS2980       e3b
node2              Eth1/2         124    H           FAS2980       eb
sh1                Eth1/35        178    R S I s     N9K-C9336C    Eth1/35
sh1                Eth1/36        178    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
----
====


. [[step15]]activez la fonction de collecte des journaux du moniteur d'intégrité des commutateurs Ethernet pour la collecte des fichiers journaux relatifs aux commutateurs, à l'aide des commandes suivantes :
+
** `system switch ethernet log setup password`
** `system switch ethernet log enable-collection`
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*sh1*
*sh2*
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *sh1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*
Enter the password: <enter switch password>
Enter the password again: <enter switch password>
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *sh2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*
Enter the password: <enter switch password>
Enter the password again: <enter switch password>
cluster1::*> system  switch ethernet log enable-collection
Do you want to enable cluster log collection for all nodes in the cluster? y|n}: [n] *y*
Enabling cluster switch log collection.
cluster1::*>
----
====





NOTE: Si l'une de ces commandes renvoie une erreur, contactez le support NetApp.

. [[step16]]déplacez les ports de stockage de l'ancien commutateur sh2 vers le nouveau commutateur newsh2.
. Vérifiez que le stockage connecté à la paire HA 1, commutateur partagé newsh2 est en bon état.
. Vérifiez que le stockage connecté à la paire HA 2, commutateur partagé newsh2 est sain :
+
`storage port show -port-type ENET`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                            VLAN
Node    Port    Type    Mode       (Gb/s)      State     Status       ID
------- ------- ------- ---------- ----------- --------- --------- -----
node1
        e3a     ENET    storage          100   enabled   online       30
        e3b     ENET    storage            0   enabled   offline      30
        e7a     ENET    storage            0   enabled   offline      30
        e7b     ENET    storage          100   enabled   online       30

node2
        e3a     ENET    storage          100   enabled   online       30
        e3b     ENET    storage            0   enabled   offline      30
        e7a     ENET    storage            0   enabled   offline      30
        e7b     ENET    storage          100   enabled   online       30
----
====


. [[step19]]vérifier que les tiroirs sont correctement câblés :
+
`storage shelf port show -fields remote- device,remote-port`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device,remote-port*
shelf id remote-port  remote-device
----- -- ------------ ----------------------------
3.20  0  Ethernet1/13 sh1
3.20  1  Ethernet1/13 newsh2
3.20  2  Ethernet1/14 sh1
3.20  3  Ethernet1/14 newsh2
3.30  0  Ethernet1/15 sh1
3.30  1  Ethernet1/15 newsh2
3.30  2  Ethernet1/16 sh1
3.30  3  Ethernet1/16 newsh2
8 entries were displayed.
----
====


. [[étape20]]retirer l'ancien commutateur sh2.
. Répétez ces étapes pour le commutateur sh1 et le nouveau commutateur newsh1.
. Si vous avez supprimé la création automatique de cas, réactivez-la en appelant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`


