---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/setup-and-configure-9336c-shared.html 
keywords:  
summary:  
---
= Configurez les commutateurs partagés Cisco Nexus 9336C-FX2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Suivez ces instructions pour configurer les commutateurs partagés Cisco Nexus 9336C-FX2.

.Avant de commencer
Assurez-vous de disposer des éléments suivants :

* Documentation partagée requise sur le commutateur, documentation sur le contrôleur et documentation ONTAP. Voir link:required-documentation-9336c-shared.html["Documentation requise pour les commutateurs partagés Cisco Nexus 9336C-FX2"] et https://docs.netapp.com/us-en/ontap/index.html["Documentation NetApp ONTAP"^].
* Licences applicables, informations sur le réseau et la configuration, et câbles.
* Feuilles de calcul de câblage remplies. Voir link:cable-9336c-shared.html["Complétez la fiche technique de câblage Cisco Nexus 9336C-FX2"]. Pour plus d'informations sur le câblage, reportez-vous au https://hwu.netapp.com["Hardware Universe"].


.Étapes
. [[étape3]]effectuer une configuration initiale des commutateurs.
+
Pour la configuration, vous devez disposer du nombre et du type appropriés de câbles et de connecteurs pour vos commutateurs.

+
Selon le type de switch que vous configurez au départ, vous devez vous connecter au port console des commutateurs avec le câble console inclus ; vous devez également fournir des informations réseau spécifiques.

. Démarrez le commutateur.
+
Lors du premier démarrage du commutateur, fournissez les réponses applicables aux questions de configuration initiale suivantes.

+
La politique de sécurité de votre site définit les réponses et les services à activer.

+
.. Abandonner le provisionnement automatique et poursuivre la configuration normale ? (oui/non) ?
+
Répondez par *oui*. La valeur par défaut est non

.. Voulez-vous appliquer une norme de mot de passe sécurisée ? (oui/non) ?
+
Répondez par *oui*. La valeur par défaut est oui.

.. Entrez le mot de passe pour l'administrateur.
+
Le mot de passe par défaut est admin. Vous devez créer un nouveau mot de passe fort.

+
Un mot de passe faible peut être rejeté.

.. Voulez-vous entrer la boîte de dialogue de configuration de base ? (oui/non) ?
+
Répondre par *oui* à la configuration initiale du commutateur.

.. Créer un autre compte de connexion ? (oui/non) ?
+
Votre réponse dépend des stratégies de votre site concernant les administrateurs secondaires. La valeur par défaut est non

.. Configurer la chaîne de communauté SNMP en lecture seule ? (oui/non) ?
+
Répondre par *non*. La valeur par défaut est non

.. Configurer la chaîne de communauté SNMP en lecture-écriture ? (oui/non) ?
+
Répondre par *non*. La valeur par défaut est non

.. Entrez le nom du commutateur.
+
Le nom du commutateur est limité à 63 caractères alphanumériques.

.. Poursuivre la configuration de gestion hors bande (mgmt0) ? (oui/non) ?
+
Répondez par *yes* (par défaut) à cette invite. À l'invite mgmt0 adresse IPv4 :, entrez votre adresse IP : adresse_ip

.. Configurer la passerelle par défaut ? (oui/non) ?
+
Répondez par *oui*. À l'invite Default-Gateway:, saisissez votre passerelle_par_défaut.

.. Configurer les options IP avancées ? (oui/non) ?
+
Répondre par *non*. La valeur par défaut est non

.. Activer le service telnet ? (oui/non) ?
+
Répondre par *non*. La valeur par défaut est non

.. Activer le service SSH ? (oui/non) ?
+
Répondez par *oui*. La valeur par défaut est oui.

+

NOTE: SSH est recommandé lors de l'utilisation du moniteur d'état du commutateur Ethernet (CSHM) pour ses fonctions de collecte de journaux. SSHv2 est également recommandé pour une sécurité améliorée.

.. [[step14]]Entrez le type de clé SSH que vous souhaitez générer (dsa/rsa/rsa1). La valeur par défaut est rsa.
.. Entrez le nombre de bits de clé (1024- 2048).
.. Configurer le serveur NTP ? (oui/non) ?
+
Répondre par *non*. La valeur par défaut est non

.. Configurer la couche d'interface par défaut (L3/L2) :
+
Répondre avec *L2*. La valeur par défaut est L2.

.. Configurer l'état d'interface du port du commutateur par défaut (shutr/nosolt) :
+
Répondre avec *nohut*. La valeur par défaut est nosott.

.. Configuration du profil du système Copp (strict/modéré/ELEDent/dense) :
+
Répondez avec *strict*. La valeur par défaut est stricte.

.. Voulez-vous modifier la configuration ? (oui/non) ?
+
La nouvelle configuration est à présent visible. Vérifiez et apportez les modifications nécessaires à la configuration que vous venez de saisir. Répondez sans à l'invite si vous êtes satisfait de la configuration. Répondez par *yes* si vous souhaitez modifier vos paramètres de configuration.

.. Utilisez cette configuration et enregistrez-la ? (oui/non) ?
+
Répondez avec *yes* pour enregistrer la configuration. Ceci met automatiquement à jour les images kickstart et système.



. Vérifiez les choix de configuration que vous avez effectués à l'écran qui s'affiche à la fin de la configuration et assurez-vous d'enregistrer la configuration.
+

NOTE: Si vous n'enregistrez pas la configuration à ce stade, aucune des modifications ne sera effective lors du prochain redémarrage du commutateur.

. Vérifier la version sur les commutateurs du réseau du cluster et, si nécessaire, télécharger la version prise en charge par NetApp du logiciel sur les commutateurs à partir du https://software.cisco.com/download/home["Téléchargement du logiciel Cisco"^] page.


.Et la suite ?
link:prepare-nxos-rcf-9336c-shared.html["Préparez-vous à installer NX-OS et RCF"].
