---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/setup-and-configure-9336c-shared.html 
keywords:  
summary:  
---
= Configurer les commutateurs partagés Cisco Nexus 9336C-FX2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Suivez ces instructions pour configurer les commutateurs partagés Cisco Nexus 9336C-FX2.

.Avant de commencer
Assurez-vous d'avoir les éléments suivants :

* Documentation requise pour le commutateur partagé, le contrôleur et ONTAP .  Voirlink:required-documentation-9336c-shared.html["Exigences en matière de documentation pour les commutateurs partagés Cisco Nexus 9336C-FX2"] et https://docs.netapp.com/us-en/ontap/index.html["Documentation NetApp ONTAP"^] .
* Licences applicables, informations sur le réseau et la configuration, et câbles.
* Fiches de câblage complétées. Voirlink:cable-9336c-shared.html["Complétez la fiche de câblage Cisco Nexus 9336C-FX2"] .  Pour plus d'informations sur le câblage, reportez-vous au https://hwu.netapp.com["Hardware Universe"] .


.Étapes
. [[étape 3]]Effectuez une configuration initiale des commutateurs.
+
Pour la configuration, vous aurez besoin du nombre et du type appropriés de câbles et de connecteurs de câbles pour vos commutateurs.

+
Selon le type de commutateur que vous configurez initialement, vous devez vous connecter au port console du commutateur avec le câble console fourni ; vous devez également fournir des informations réseau spécifiques.

. Démarrez le commutateur.
+
Veuillez fournir les réponses appropriées aux questions de configuration initiale suivantes lors du premier démarrage du commutateur.

+
La politique de sécurité de votre site définit les réponses et les services à activer.

+
.. Annuler le provisionnement automatique et poursuivre la configuration normale ?  (oui/non)
+
Répondez par *oui*.  La valeur par défaut est non.

.. Souhaitez-vous imposer une norme de mot de passe sécurisé ?  (oui/non)
+
Répondez par *oui*.  La valeur par défaut est oui.

.. Saisissez le mot de passe de l'administrateur.
+
Le mot de passe par défaut est « admin » ; vous devez créer un nouveau mot de passe fort.

+
Un mot de passe faible peut être refusé.

.. Souhaitez-vous accéder à la boîte de dialogue de configuration de base ?  (oui/non)
+
Répondez *oui* lors de la configuration initiale du commutateur.

.. Créer un autre compte de connexion ?  (oui/non)
+
Votre réponse dépend des politiques de votre site concernant les administrateurs alternatifs.  La valeur par défaut est non.

.. Configurer la chaîne de communauté SNMP en lecture seule ?  (oui/non)
+
Répondez par *non*.  La valeur par défaut est non.

.. Configurer la chaîne de communauté SNMP en lecture-écriture ?  (oui/non)
+
Répondez par *non*.  La valeur par défaut est non.

.. Saisissez le nom du commutateur.
+
Le nom du commutateur est limité à 63 caractères alphanumériques.

.. Continuer avec la configuration de gestion hors bande (mgmt0) ?  (oui/non)
+
Répondez par *oui* (par défaut) à cette invite.  À l'invite « Adresse IPv4 mgmt0 », saisissez votre adresse IP : adresse_ip

.. Configurer la passerelle par défaut ?  (oui/non)
+
Répondez par *oui*.  À l'invite « adresse IPv4 de la passerelle par défaut : », saisissez votre passerelle par défaut.

.. Configurer les options IP avancées ?  (oui/non)
+
Répondez par *non*.  La valeur par défaut est non.

.. Activer le service telnet ?  (oui/non)
+
Répondez par *non*.  La valeur par défaut est non.

.. Activer le service SSH ?  (oui/non)
+
Répondez par *oui*.  La valeur par défaut est oui.

+

NOTE: L'utilisation de SSH est recommandée lors de l'utilisation de Ethernet Switch Health Monitor (CSHM) pour ses fonctionnalités de collecte de journaux.  SSHv2 est également recommandé pour une sécurité renforcée.

.. [[étape 14]]Entrez le type de clé SSH que vous souhaitez générer (dsa/rsa/rsa1).  La valeur par défaut est rsa.
.. Entrez le nombre de bits clés (1024- 2048).
.. Configurer le serveur NTP ?  (oui/non)
+
Répondez par *non*.  La valeur par défaut est non.

.. Configurer la couche d'interface par défaut (L3/L2) :
+
Répondez avec *L2*.  La valeur par défaut est L2.

.. Configurer l'état par défaut de l'interface du port de commutation (arrêté/non arrêté) :
+
Répondez par *noshut*.  La valeur par défaut est noshut.

.. Configurer le profil système CoPP (strict/modéré/souple/dense) :
+
Répondez avec *strict*.  Le paramètre par défaut est strict.

.. Souhaitez-vous modifier la configuration ?  (oui/non)
+
Vous devriez voir la nouvelle configuration à ce stade.  Vérifiez et apportez les modifications nécessaires à la configuration que vous venez de saisir.  Répondez « non » à l'invite si la configuration vous convient.  Répondez *oui* si vous souhaitez modifier vos paramètres de configuration.

.. Utilisez cette configuration et enregistrez-la ?  (oui/non)
+
Répondez *oui* pour enregistrer la configuration.  Cela met automatiquement à jour les images Kickstart et système.



. Vérifiez les choix de configuration que vous avez effectués dans l'écran qui apparaît à la fin de l'installation et assurez-vous d'enregistrer la configuration.
+

NOTE: Si vous ne sauvegardez pas la configuration à cette étape, aucune des modifications ne sera prise en compte lors du prochain redémarrage du commutateur.

. Vérifiez la version installée sur les commutateurs du réseau du cluster et, si nécessaire, téléchargez la version du logiciel compatible avec NetApp sur ces commutateurs. https://software.cisco.com/download/home["Téléchargement de logiciels Cisco"^] page.


.Quelle est la prochaine étape ?
Une fois vos commutateurs configurés, vous pouvez link:prepare-nxos-rcf-9336c-shared.html["préparer l'installation de NX-OS et RCF"].
