---
permalink: switch-cisco-9364d-gx2a/configure-install-upgrade-nxos-overview-9364d.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9364d-gx2a 
summary: Installez ou mettez à niveau le NX-OS sur les commutateurs Cisco Nexus 9364D-GX2A pour les systèmes AFX 1K et AFX 2K. 
---
= Découvrez comment installer ou mettre à niveau NX-OS sur le commutateur Cisco Nexus 9364D-GX2A
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Installez ou mettez à niveau le NX-OS sur les commutateurs Cisco Nexus 9364D-GX2A pour les systèmes AFX 1K et AFX 2K.


NOTE: L'installation ou la mise à niveau de NX-OS est indépendante de celle de RCF. Si vous installez ou mettez à niveau à la fois NX-OS et RCF, il est recommandé d'installer ou de mettre à niveau NX-OS en premier.

* link:configure-install-nxos-9364d.html["Installez le système d'exploitation NX-OS"]
+
Vous installez le système d'exploitation NX-OS sur les commutateurs dans le cadre d'une nouvelle installation de système AFX 1K ou AFX 2K, d'un remplacement de commutateur ou d'une réinitialisation du commutateur aux paramètres d'usine par défaut.

* link:configure-upgrade-nxos-9364d.html["Mettez à niveau le NX-OS"]
+
Vous mettez à niveau le NX-OS sur les commutateurs pour prendre en charge un nouveau matériel ou une nouvelle version ONTAP sur votre système AFX 1K ou AFX 2K.


