---
permalink: switch-cisco-9364d-gx2a/configure-verify-ssh-9364d.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9332d-gx2b 
summary: 'Si vous configurez vos commutateurs dans le cadre d"une nouvelle installation de système AFX 1K ou AFX 2K, d"un remplacement de commutateur ou d"une réinitialisation aux paramètres d"usine par défaut, pour utiliser la fonction de collecte des journaux du contrôle de l"état du commutateur Ethernet (CSHM), vous devez vérifier que SSH est activé sur les commutateurs.' 
---
= Vérifiez SSH pour la collecte des journaux - Cisco Nexus 9364D-GX2A
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous configurez vos commutateurs dans le cadre d'une nouvelle installation de système AFX 1K ou AFX 2K, d'un remplacement de commutateur ou d'une réinitialisation aux paramètres d'usine par défaut, pour utiliser la fonction de collecte des journaux du contrôle de l'état du commutateur Ethernet (CSHM), vous devez vérifier que SSH est activé sur les commutateurs.

.Avant de commencer
Vous devez être connecté au commutateur via la console série.

.Étapes
. Vérifiez que SSH est activé :
+
[listing, subs="+quotes"]
----
(switch) *show ssh server*
ssh version 2 is enabled
----
. Vérifiez que les clés SSH sont activées :
+
`show ssh key`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *show ssh key*

rsa Keys generated:Thu May 15 15:09:55 2025

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDCQJPZk7OGhg0j1t0NWKylnI8R8zDpuMpU6KKAjPOCShTFpibeYQqxOPTCAKACkut8dduZmc3bY9DIOle0cKYQ8PgS2mG9ovQ0RJ56RUNhVNPdJuhXM4ckHoiVJxIAbHkbcw8rzawbkT6cNBUiZY3MrOMh0e0CnMRhh9we
MOo/vQ==


bitcount:1024
fingerprint:
SHA256:TMUXFgyRC3EcIZEVbQ/P0elDByBCJizPJ1XKMkIXfPI
**************************************
could not retrieve dsa key information
**************************************
ecdsa Keys generated:Thu May 15 15:12:09 2025


ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBADquZcNSDA/eLAaItXyxVZxsSJSE3u4et9B6+RLq162zTe/3A6JTCyBrkfrMhQt9QMQ7XrMqJGxLSinXhyUClBxwQD/ZbkZueZHiFuYg5hKN97wUYvts+EwpG2mSVonxKKp
atmtgu48BqKfZTc4LZYL5vgdh5uuktJ0Z8mYHt3xKPXsvw==


bitcount:521
fingerprint:
SHA256:K8LDx6L7sJjLFn8iubUhjt66uk8TYmXwnQKWVD04C1o
**************************************

(switch)# *show feature | include scpServer*
scpServer              1          enabled
(switch)# *show feature | include ssh*
sshServer              1          enabled
(switch)#
----
====


.Quelle est la prochaine étape ?
* Après avoir vérifié que SSH est activé pour la collecte des journaux, vous link:../switch-cshm/cshm-overview.html["configurer le contrôle de l'état du commutateur Ethernet"].
+
** Après avoir configuré la surveillance de l'état du commutateur Ethernet, si vous souhaitez profiter de la fonction d'assistance Smart Call Home de Cisco, vous link:configure-smart-call-9364d.html["Configurer Smart Call Home"].


* Si vous avez configuré votre commutateur dans le cadre d'une nouvelle installation de système AFX 1K ou AFX 2K, vous devez link:install-complete-afx-setup-9364d.html["terminer la configuration du système AFX"].

