---
permalink: switch-cisco-9364d-gx2a/configure-review-cabling-config-requirements-9364d.html 
sidebar: sidebar 
keywords: 9364d-gx2a cabling setup, 9364d-gx2a switches configuration, nx-os 
summary: Examinez les exigences de câblage et de configuration pour les commutateurs Cisco Nexus 9364D-GX2A avant de les installer dans le cadre d’un système AFX 1K ou AFX 2K. 
---
= Examinez les exigences de câblage et de configuration pour le commutateur Cisco Nexus 9364D-GX2A
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Examinez les exigences de câblage et de configuration des commutateurs Cisco Nexus 9364D-GX2A avant de les installer dans le cadre d’un nouveau système AFX 1K ou AFX 2K, de remplacer un commutateur ou de réinitialiser un commutateur aux paramètres d’usine par défaut.



[[hard-code-the-speed-on-breakout-ports]]
== Attribuez une vitesse fixe aux ports de breakout

Vous devez configurer manuellement les ports de dérivation du commutateur (4x100GbE) pour 100GbE. Si vous ne configurez pas manuellement la vitesse, les ports ne seront pas opérationnels et seront dans un état désactivé pour cause d'erreur.

Par exemple, pour configurer en dur 100GbE sur les ports de breakout 1 à 13, procédez comme suit en mode configuration. L'exemple montre les commandes appliquées au premier commutateur (cs1). Vous répétez ces commandes pour le second commutateur.

[listing, subs="+quotes"]
----
(cs1)(config)# *interface e1/1/1-4, e1/2/1-4, e1/3/1-4, e1/4/1-4, e1/5/1-4, e1/6/1-4, e1/7/1-4, e1/8/1-4, e1/9/1-4, e1/10/1-4, e1/11/1-4, e1/12/1-4, e1/13/1-4*
(cs1)(config-if)# *speed 100000*
(cs1)(config-if)# *no negotiate auto*
(cs1)(config-if)# *exit*
(cs1)(config)# *exit*
(cs1)# *copy running-config startup-config*
----
.Quelle est la prochaine étape ?
Une fois que vous avez satisfait aux exigences de câblage et de configuration, vous link:configure-install-nxos-9364d.html["installez le système d'exploitation NX-OS"].
