---
permalink: switch-cisco-9364d-gx2a/install-switches-9364d.html 
sidebar: sidebar 
keywords: switches, hardware installation, Cisco Nexus, 9364D-GX2A switches 
summary: Installez les commutateurs Cisco Nexus 9364D-GX2A dans le cadre d’un nouveau système AFX 1K ou AFX 2K, y compris le montage en rack, le câblage vers les contrôleurs et les étagères, ainsi que la mise sous tension. 
---
= Installez des commutateurs Cisco Nexus 9364D-GX2A dans un système AFX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Installez les commutateurs Cisco Nexus 9364D-GX2A dans le cadre d'un nouveau système AFX 1K ou AFX 2K. Cela comprend l'installation des commutateurs dans une baie ou une armoire, leur câblage aux contrôleurs système et aux étagères, ainsi que leur mise sous tension.

.Avant de commencer
Vous devez avoir terminé les étapes de préparation du changement dans link:install-prepare-9364d.html["Préparez-vous à installer les commutateurs"].

.À propos de cette tâche
Vous utilisez le flux de travail d'installation et de configuration du système AFX 1K ou AFX 2K applicable sur le site de documentation du système AFX pour installer et câbler le matériel du système, puis vous mettez les commutateurs sous tension.

Le processus d'installation et de configuration du système comprend des instructions telles que :

* Instructions pour préparer le site, déballer les cartons et comparer le contenu des cartons avec le bordereau d'expédition, et enregistrer le système pour accéder aux avantages de l'assistance.
* Instructions pour l'installation des commutateurs, des contrôleurs et des étagères de stockage dans une NetApp cabinet ou une baie de télécommunications.
* Instructions pour le câblage de votre système, y compris le câblage des contrôleurs aux connexions de commutateur et le câblage des étagères de stockage aux connexions de commutateur.


.Étapes
. Installez les commutateurs dans le cadre de votre flux de travail d'installation et de configuration de système AFX 1K ou AFX 2K :
+
** Pour un système AFX 1K, rendez-vous sur le link:https://docs.netapp.com/us-en/ontap-afx/install-setup/install-setup-workflow.html["Flux de travail d'installation et de configuration d'AFX 1K"^].
** Pour un système AFX 2K, allez à link:https://docs.netapp.com/us-en/ontap-afx/install-afx-2k/install-setup-workflow.html["Flux de travail d'installation et de configuration d'AFX 2K"^].





NOTE: Une fois que vous avez installé les commutateurs, les instructions d'installation et de configuration d'AFX vous redirigent vers cette documentation sur les commutateurs afin de les configurer.

.Quelle est la prochaine étape ?
Après avoir installé, câblé et mis sous tension vos commutateurs dans le cadre de l'installation de votre système AFX 1K ou AFX 2K, vous link:install-configure-switches-in-afx-workflow-9364d.html#configure-switches["configurez vos commutateurs"] puis link:install-configure-switches-in-afx-workflow-9364d.html#complete-afx-system-setup["terminer la configuration du système AFX"].
