= 
:allow-uri-read: 


La version d'ONTAP exécutée sur votre système AFX et la version de NX-OS sur vos commutateurs déterminent les versions de RCF compatibles avec vos commutateurs. Les versions de RCF possèdent des configurations de vitesse de port prédéfinies qui déterminent combien de ports de commutateur sont en mode breakout (4x100GbE) et combien sont en mode non-breakout.

[NOTE]
====
Pour connaître la liste actuelle des versions RCF prises en charge, consultez la link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["NetApp Cisco Commutateurs Ethernet"^] page.

Les informations relatives aux ports du commutateur se trouvent également dans le https://hwu.netapp.com["Hardware Universe NetApp"^].

====
* Si vous possédez un système AFX 1K, RCF 10.0 et versions ultérieures sont prises en charge.
* Si vous possédez un système AFX 2K, RCF 10.1 et versions ultérieures sont prises en charge.
* RCF 10.0 possède un seul fichier et prend en charge les commutateurs partagés, `Cluster-HA-Storage AFX RCF_10.0`.
+
Par exemple, le tableau suivant présente les regroupements prédéfinis des ports du commutateur, leurs vitesses de port et leur utilisation pour ce fichier RCF.

+
[cols="1,2"]
|===
| Groupes de ports de commutateur | Vitesses et utilisation des ports 


 a| 
Ethernet1/1/1-4 vers Ethernet1/30/1-4
 a| 
Mode 4x100GbE pour les connexions cluster, HA et stockage



 a| 
Ethernet1/31, Ethernet1/32
 a| 
ISL 400GbE

|===
* RCF 10.1 propose différents fichiers selon les cas d'utilisation pour AFX 1K et pour AFX 2K. Selon la façon dont vous prévoyez d'utiliser les commutateurs dans la configuration de votre système AFX 1K ou AFX 2K (partagé, stockage uniquement ou cluster et HA uniquement), vous choisissez le fichier RCF applicable.
+
Par exemple, si vous utilisez vos commutateurs comme commutateurs partagés dans un système AFX 2K, vous utilisez le fichier RCF approprié pour ce cas d'utilisation. Le fichier RCF approprié pourrait porter un nom similaire à  `RCF-v10.1-NX9332D-GX2B-CL1-ST1-100GBR15-400G15.txt`. Le tableau suivant présente les groupes prédéfinis de ports de commutateur, leurs vitesses de port et leur utilisation pour ce fichier RCF.

+
[cols="1,2"]
|===
| Groupes de ports de commutateur | Vitesses et utilisation des ports 


 a| 
Ethernet1/1/1-4 vers Ethernet1/15/1-4
 a| 
Mode 4x100GbE pour les connexions intra-cluster, HA et aux baies de stockage



 a| 
Ethernet1/16 à Ethernet1/30
 a| 
Mode 400GbE pour les connexions intra-cluster, HA et de stockage



 a| 
Ethernet1/31, Ethernet1/32
 a| 
Connexions ISL intra-cluster 400GbE

|===

