---
permalink: switch-cisco-9332d-gx2b/configure-verify-ssh-9332d.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9332d-gx2b 
summary: 'Vérifiez que SSH est activé sur les commutateurs Cisco Nexus 9332D-GX2B afin de prendre en charge le contrôle de l"état du commutateur Ethernet (CSHM) et la collecte des journaux.' 
---
= Vérifiez SSH pour la collecte des journaux sur le commutateur Cisco Nexus 9332D-GX2B
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vérifiez que SSH est activé sur les commutateurs Cisco Nexus 9332D-GX2B afin de prendre en charge la fonctionnalité de contrôle de l'état du commutateur Ethernet (CSHM) et la collecte des journaux.

.Avant de commencer
Vous devez être connecté au commutateur via la console série.

.Étapes
. Vérifiez que SSH est activé :
+
[listing, subs="+quotes"]
----
(switch) *show ssh server*
ssh version 2 is enabled
----
. Vérifiez que les clés SSH sont activées :
+
`show ssh key`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *show ssh key*

**************************************
rsa Keys generated:Wed May 14 18:49:37 2025

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCndfdJesautdCwk5Mk/7pKOFl0IeShc9uBtj74F52vbjyf1FHOCXX7Xf3Vopxs6L1hbzgCpFLo9E7pZBd3I+1AoLyQULtR3svzNieGY8mlWZGLtpKf/P2fDCd8JVJaejrwQhm49WUPiC6ziEqBDMOGhJpD2e9++umyDdr6
NbmK8Q==


bitcount:1024
fingerprint:
SHA256:QtNU+Qq2I4ZfYwEfMEB1+z8w7xaKTlantTdsjLBx+OU
**************************************
could not retrieve dsa key information
**************************************
ecdsa Keys generated:Wed May 14 18:50:56 2025


ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAAYnv17T+JlGmH8rg81xiOow0mPmkbkIG0o7h9EchixO3i3KjgQr8AwqkRHNTcQC3lRnizhJFUeMGCwuQTurziRCwE6fAOkWa2MRyXA1DYRKKXjVEOnW9+MvinMipHQ0cCc
YSExhh7j4HvWHIuYv8RmD7e3rmDQFlyyiLwdmpGfas2yaw==


bitcount:521
fingerprint:
SHA256:7cpZ5NGnIq5Iamw67ke+9o4qG9D3xxmGPauVl4X5934
**************************************

(switch)# *show feature | include scpServer*
scpServer              1          enabled
(switch)# *show feature | include ssh*
sshServer              1          enabled
(switch)#
----
====


.Quelle est la prochaine étape ?
* Après avoir vérifié que SSH est activé pour la collecte des journaux, vous link:../switch-cshm/cshm-overview.html["configurer le contrôle de l'état du commutateur Ethernet"].
+
** Après avoir configuré la surveillance de l'état du commutateur Ethernet, si vous souhaitez profiter de la fonction d'assistance Smart Call Home de Cisco, vous link:configure-smart-call-9332d.html["Configurer Smart Call Home"].


* Si vous avez configuré votre commutateur dans le cadre d'une nouvelle installation de système AFX 1K ou AFX 2K, vous devez link:install-complete-afx-setup-9332d.html["terminer la configuration du système AFX"].

