---
permalink: switch-cisco-9332d-gx2b/configure-review-cabling-config-requirements-9332d.html 
sidebar: sidebar 
keywords: 9332d-gx2b cabling setup, 9332d-gx2b switches configuration, nx-os 
summary: 'Si vous installez de nouveaux commutateurs Cisco Nexus 9332D-GX2B dans le cadre d"une nouvelle installation de système AFX 1K ou AFX 2K, du remplacement d"un commutateur ou de la réinitialisation d"un commutateur aux paramètres d"usine par défaut, vous devez examiner les exigences de câblage et de configuration suivantes.' 
---
= Examinez le câblage et les exigences de configuration - Cisco Nexus 9332D-GX2B
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous installez des commutateurs Cisco Nexus 9332D-GX2B dans le cadre d'une nouvelle installation de système AFX 1K ou AFX 2K, du remplacement d'un commutateur ou de la réinitialisation d'un commutateur aux paramètres d'usine par défaut, vous devez examiner les exigences de câblage et de configuration suivantes.



[[hard-code-the-speed-on-breakout-ports]]
== Attribuez une vitesse fixe aux ports de breakout

Vous devez configurer manuellement les ports de dérivation du commutateur (4x100GbE) pour 100GbE. Si vous ne configurez pas manuellement la vitesse, les ports ne seront pas opérationnels et seront dans un état désactivé pour cause d'erreur.

Par exemple, pour configurer en dur 100GbE sur les ports de breakout 1 à 14, procédez comme suit en mode configuration. L'exemple montre les commandes appliquées au premier commutateur (cs1). Vous répétez ces commandes pour le second commutateur.

[listing, subs="+quotes"]
----
(cs1)(config)# *interface e1/1/1-4, e1/2/1-4, e1/3/1-4, e1/4/1-4, e1/5/1-4, e1/6/1-4, e1/7/1-4, e1/8/1-4, e1/9/1-4, e1/10/1-4, e1/11/1-4, e1/12/1-4, e1/13/1-4, e1/14/1-4*
(cs1)(config-if)# *speed 100000*
(cs1)(config-if)# *no negotiate auto*
(cs1)(config-if)# *exit*
(cs1)(config)# *exit*
(cs1)# *copy running-config startup-config*
----
.Quelle est la prochaine étape ?
Une fois que vous avez satisfait aux exigences de câblage et de configuration, vous link:configure-install-nxos-9332d.html["installez le système d'exploitation NX-OS"].
