---
permalink: switch-cisco-9332d-gx2b/maintain-replace-frus-9332d.html 
sidebar: sidebar 
keywords: switches, hardware installation, Cisco Nexus, 9332D-GX2B switches 
summary: 'Remplacez les unités remplaçables sur site (FRU) défectueuses sur les commutateurs Cisco Nexus 9332D-GX2B.' 
---
= Remplacez les FRU dans le commutateur Cisco Nexus 9332D-GX2B
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Remplacez les unités remplaçables sur site (FRU) défectueuses sur les commutateurs Cisco Nexus 9332D-GX2B afin de rétablir la fonctionnalité du commutateur sans remplacer l'ensemble du commutateur.

.À propos de cette tâche
Le commutateur Cisco Nexus 9332D-GX2B possède les FRU suivantes :

* Module de ventilateur (6 au total)
* Module d'alimentation (2 au total)
* Modules émetteurs-récepteurs OSFP/QSFP (32 ports fixes 400GbE)


.Étapes
. Accédez au site Cisco pour le https://www.cisco.com/c/en/us/td/docs/dcn/hw/nx-os/nexus9000/9332d-gx2b/cisco-nexus-9332d-gx2b-nx-os-mode-switch-hardware-installation-guide.html?dtid=osscdc000283&linkclickid=srch&scid=srch-9332d-gx2b-hw-guide#id_111902["Guide d'installation du commutateur Cisco Nexus 9332D-GX2B NX-OS"^].
. Accédez à la section Remplacement des composants pour consulter les procédures FRU.
. Suivez la procédure applicable pour remplacer votre FRU défectueux.


.Quelle est la prochaine étape ?
Une fois la procédure FRU applicable terminée sur le site Cisco, vous pouvez reprendre les opérations normales.
