---
sidebar: sidebar 
permalink: switch-cisco-9332d-gx2b/reference-documentation-9332d.html 
keywords: shared storage cluster switch 
summary: 'Pour l"installation et la configuration du commutateur Cisco Nexus 9332D-GX2B dans le cadre d"un nouveau système AFX 1K ou AFX 2K, ou pour la maintenance des commutateurs existants, vous pouvez consulter la documentation applicable du commutateur Cisco et la documentation des systèmes NetApp.' 
---
= Documentation de référence - Cisco Nexus 9332D-GX2B
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour l'installation et la configuration du commutateur Cisco Nexus 9332D-GX2B dans le cadre d'un nouveau système AFX 1K ou AFX 2K, ou pour la maintenance des commutateurs existants, vous pouvez consulter la documentation applicable du commutateur Cisco et la documentation des systèmes NetApp.


NOTE: Pour obtenir des instructions étape par étape sur l'installation et la configuration de vos commutateurs dans le cadre d'un nouveau système AFX 1K ou AFX 2K, consultez le link:install-configure-switches-in-afx-workflow-9332d.html["Installer et configurer les commutateurs dans un workflow système AFX"].



[[cisco-switch-documentation]]
== Documentation des commutateurs Cisco

Pour installer et configurer vos commutateurs Cisco Nexus 9332D-GX2B dans le cadre d’un nouveau système AFX 1K ou AFX 2K, vous pouvez consulter les documents Cisco suivants afin de vous familiariser avec les notes de version du commutateur, les informations de sécurité, les options d’installation, la configuration logicielle initiale et les références de commandes.

Après avoir installé et configuré vos commutateurs, vous pouvez consulter la documentation Cisco applicable pour assurer leur maintenance.

Tous ces documents sont disponibles sur la page link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Prise en charge des commutateurs Cisco Nexus série 9000"^].

[cols="1,2,3"]
|===
| Type de tâche | Titre du document Cisco | Description 


 a| 
Installer et configurer
 a| 
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-release-notes-list.html["Notes de version de Cisco Nexus série 9000 NX-OS"^](Choisissez les notes correspondant à la version de NX-OS installée sur vos commutateurs)
 a| 
Décrit les fonctionnalités, les bugs et les limitations de la gamme Cisco Nexus 9000.



 a| 
Installer et configurer
 a| 
link:https://www.cisco.com/c/en/us/td/docs/switches/datacenter/mds9000/hw/regulatory/compliance/RCSI.html?dtid=osscdc000283&linkclickid=srch["Informations relatives à la conformité réglementaire et à la sécurité pour la gamme Cisco Nexus 9000"^]
 a| 
Fournit des informations sur la conformité aux normes internationales, la sécurité et les réglementations relatives aux commutateurs de la série Nexus 9000.



 a| 
Installer et configurer
 a| 
link:https://www.cisco.com/c/en/us/td/docs/dcn/hw/nx-os/nexus9000/9332d-gx2b/cisco-nexus-9332d-gx2b-nx-os-mode-switch-hardware-installation-guide.html["Guide d'installation du commutateur Cisco Nexus 9332D-GX2B NX-OS"^]
 a| 
Fournit des informations détaillées sur les exigences du site, les caractéristiques du matériel de commutation et les options d'installation.



 a| 
Installer et configurer
 a| 
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-installation-and-configuration-guides-list.html["Guides de configuration logicielle des commutateurs Cisco Nexus série 9000"^](Choisissez le guide correspondant à la version de NX-OS installée sur vos commutateurs)
 a| 
Fournit les informations de configuration initiale du commutateur dont vous avez besoin avant de pouvoir configurer le commutateur pour un fonctionnement ONTAP .



 a| 
Installer, configurer et maintenir
 a| 
link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/102x/command-reference/config/b_n9k_config_commands_1021.html["Guide de référence des commandes NX-OS Cisco Nexus série 9000"^]
 a| 
Fournit des liens vers les différentes références de commandes fournies par Cisco.



 a| 
Installer et configurer
 a| 
link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/101x/upgrade/cisco-nexus-9000-nx-os-software-upgrade-downgrade-guide-101x.html["Guide de mise à niveau et de rétrogradation du logiciel NX-OS Cisco Nexus série 9000"^](Choisissez le guide correspondant à la version de NX-OS installée sur vos commutateurs)
 a| 
Fournit des informations sur la manière de rétrograder le commutateur vers un logiciel de commutateur compatible ONTAP , si nécessaire.



 a| 
Maintenir
 a| 
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-system-message-guides-list.html["Référence des messages système NX-OS de la série Cisco Nexus 9000"^]
 a| 
Décrit les messages système des commutateurs Cisco Nexus série 9000, ceux qui sont informatifs et ceux qui peuvent aider à diagnostiquer les problèmes liés aux liaisons, au matériel interne ou au logiciel système.

|===


[[netapp-systems-documentation]]
== NetApp documentation système

Pour installer et configurer vos commutateurs Cisco Nexus 9332D-GX2B dans le cadre d’un nouveau système AFX 1K ou AFX 2K, vous pouvez consulter les documents et ressources systèmes NetApp suivants afin de vous familiariser avec les systèmes AFX, les versions ONTAP prises en charge, les configurations matérielles prises en charge et les exigences d’installation du système.

[cols="1,2,3"]
|===
| Type de tâche | Titre du document ONTAP | Description 


 a| 
Installer et configurer
 a| 
link:https://docs.netapp.com/us-en/ontap-afx/index.html["Documentation des systèmes AFX"^]
 a| 
Ce document décrit la procédure d'installation du matériel NetApp .



 a| 
Installer et configurer
 a| 
link:https://docs.netapp.com/us-en/ontap-family/["Documentation ONTAP"^]
 a| 
Fournit des informations détaillées sur tous les aspects des versions ONTAP .



 a| 
Installer et configurer
 a| 
link:https://hwu.netapp.com["Hardware Universe"^]
 a| 
Fournit des informations sur la configuration et la compatibilité du matériel NetApp .



 a| 
Installer et configurer
 a| 
link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["De quelles informations supplémentaires ai-je besoin pour installer mon équipement qui ne figure pas dans HWU ?"^]
 a| 
Fournit des informations supplémentaires sur les exigences d'installation du système de stockage.

|===