---
sidebar: sidebar 
permalink: switch-cisco-9332d-gx2b/required-documentation-9332d-cluster.html 
keywords: shared storage cluster switch 
summary: 'Pour l"installation et la maintenance du commutateur Cisco Nexus 9332D-GX2B, assurez-vous de consulter la documentation spécifique du commutateur et du contrôleur pour configurer vos commutateurs Cisco 9336-FX2 et votre cluster ONTAP .' 
---
= Exigences de documentation pour les commutateurs Cisco Nexus 9332D-GX2B
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour l'installation et la maintenance du commutateur Cisco Nexus 9332D-GX2B, assurez-vous de consulter la documentation spécifique du commutateur et du contrôleur pour configurer vos commutateurs 9332D-GX2B et votre cluster ONTAP .



== Documentation du commutateur

Pour configurer les commutateurs Cisco Nexus 9332D-GX2B, vous avez besoin de la documentation suivante dulink:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Prise en charge des commutateurs Cisco Nexus 9000 Series"^] page:

[cols="1,2"]
|===
| Titre du document | Description 


 a| 
link:https://www.cisco.com/c/en/us/td/docs/dcn/hw/nx-os/nexus9000/9332d-gx2b/cisco-nexus-9332d-gx2b-nx-os-mode-switch-hardware-installation-guide/m_installing-the-switch-chassis-new-1ru-rack-mount.html["Guide d'installation du commutateur Cisco Nexus 9332D-GX2B NX-OS"^]
 a| 
Fournit des informations détaillées sur les exigences du site, les détails du matériel du commutateur et les options d'installation.



 a| 
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-installation-and-configuration-guides-list.html["Guides de configuration du logiciel des commutateurs Cisco Nexus série 9000"^](choisissez le guide de la version NX-OS installée sur vos commutateurs)
 a| 
Fournit les informations de configuration initiale des switchs nécessaires avant de configurer le switch pour le fonctionnement de ONTAP.



 a| 
link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/101x/upgrade/cisco-nexus-9000-nx-os-software-upgrade-downgrade-guide-101x.html["Guide de mise à niveau et de mise à niveau du logiciel Cisco Nexus série 9000 NX-OS"^](choisissez le guide de la version NX-OS installée sur vos commutateurs)
 a| 
Le fournit des informations sur la procédure de rétrogradation du commutateur vers le logiciel de commutation pris en charge par ONTAP, si nécessaire.



 a| 
link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/102x/command-reference/config/b_n9k_config_commands_1021.html["Référence des commandes Cisco Nexus série 9000 NX-OS"^]
 a| 
Fournit des liens vers les différentes références de commande fournies par Cisco.



 a| 
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-system-message-guides-list.html["Référence des messages système NX-OS de la série Cisco Nexus 9000"^]
 a| 
Décrit les messages système relatifs aux commutateurs Cisco Nexus série 9000, à ceux qui sont à titre d'information et autres susceptibles d'aider à diagnostiquer les problèmes de liens, de matériel interne ou de logiciel du système.



 a| 
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-release-notes-list.html["Notes de version de Cisco Nexus 9000 Series NX-OS"^](choisissez les notes pour la version NX-OS installée sur vos commutateurs)
 a| 
Décrit les fonctionnalités, les bugs et les limites de la gamme Cisco Nexus 9000.



 a| 
link:https://www.cisco.com/c/en/us/td/docs/switches/datacenter/mds9000/hw/regulatory/compliance/RCSI.html?dtid=osscdc000283&linkclickid=srch["Conformité réglementaire et informations de sécurité pour Cisco Nexus 9000 Series"^]
 a| 
Fournit des informations réglementaires, de sécurité et de conformité aux organismes internationaux pour les commutateurs de la gamme Nexus 9000.

|===


== Documentation sur les systèmes ONTAP

Pour configurer un système ONTAP , vous avez besoin des documents suivants pour votre version du système d'exploitation du https://docs.netapp.com/ontap-9/index.jsp["Centre de documentation ONTAP 9"^] .

[cols="1,2"]
|===
| Nom | Description 


 a| 
https://docs.netapp.com/us-en/ontap-afx/index.html["Documentation des systèmes AFX"^]
 a| 
Décrit l'installation du matériel NetApp.



 a| 
https://docs.netapp.com/us-en/ontap-family/["Documentation ONTAP"^]
 a| 
Fournit des informations détaillées sur tous les aspects des versions de ONTAP.



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
Fournit des informations sur la compatibilité et la configuration matérielle NetApp.

|===