---
sidebar: sidebar 
permalink: switch-cisco-9332d-gx2b/required-documentation-9332d-cluster.html 
keywords: shared storage cluster switch 
summary: 'Pour l"installation et la maintenance du commutateur Cisco Nexus 9332D-GX2B, assurez-vous de consulter la documentation spécifique du commutateur et du contrôleur pour configurer vos commutateurs Cisco 9336-FX2 et votre cluster ONTAP .' 
---
= Exigences de documentation pour les commutateurs Cisco Nexus 9332D-GX2B
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour l'installation et la maintenance du commutateur Cisco Nexus 9332D-GX2B, assurez-vous de consulter la documentation spécifique du commutateur et du contrôleur pour configurer vos commutateurs 9332D-GX2B et votre cluster ONTAP .



== Documentation Switch

Pour configurer les commutateurs Cisco Nexus 9332D-GX2B, vous aurez besoin de la documentation suivante :link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Prise en charge des commutateurs Cisco Nexus série 9000"^] page:

[cols="1,2"]
|===
| Titre du document | Description 


 a| 
link:https://www.cisco.com/c/en/us/td/docs/dcn/hw/nx-os/nexus9000/9332d-gx2b/cisco-nexus-9332d-gx2b-nx-os-mode-switch-hardware-installation-guide/m_installing-the-switch-chassis-new-1ru-rack-mount.html["Guide d'installation du commutateur Cisco Nexus 9332D-GX2B NX-OS"^]
 a| 
Fournit des informations détaillées sur les exigences du site, les caractéristiques du matériel de commutation et les options d'installation.



 a| 
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-installation-and-configuration-guides-list.html["Guides de configuration logicielle des commutateurs Cisco Nexus série 9000"^](Choisissez le guide correspondant à la version de NX-OS installée sur vos commutateurs)
 a| 
Fournit les informations de configuration initiale du commutateur dont vous avez besoin avant de pouvoir configurer le commutateur pour un fonctionnement ONTAP .



 a| 
link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/101x/upgrade/cisco-nexus-9000-nx-os-software-upgrade-downgrade-guide-101x.html["Guide de mise à niveau et de rétrogradation du logiciel NX-OS Cisco Nexus série 9000"^](Choisissez le guide correspondant à la version de NX-OS installée sur vos commutateurs)
 a| 
Fournit des informations sur la manière de rétrograder le commutateur vers un logiciel de commutateur compatible ONTAP , si nécessaire.



 a| 
link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/102x/command-reference/config/b_n9k_config_commands_1021.html["Guide de référence des commandes NX-OS Cisco Nexus série 9000"^]
 a| 
Fournit des liens vers les différentes références de commandes fournies par Cisco.



 a| 
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-system-message-guides-list.html["Référence des messages système NX-OS de la série Cisco Nexus 9000"^]
 a| 
Décrit les messages système des commutateurs Cisco Nexus série 9000, ceux qui sont informatifs et ceux qui peuvent aider à diagnostiquer les problèmes liés aux liaisons, au matériel interne ou au logiciel système.



 a| 
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-release-notes-list.html["Notes de version de Cisco Nexus série 9000 NX-OS"^](Choisissez les notes correspondant à la version de NX-OS installée sur vos commutateurs)
 a| 
Décrit les fonctionnalités, les bugs et les limitations de la gamme Cisco Nexus 9000.



 a| 
link:https://www.cisco.com/c/en/us/td/docs/switches/datacenter/mds9000/hw/regulatory/compliance/RCSI.html?dtid=osscdc000283&linkclickid=srch["Informations relatives à la conformité réglementaire et à la sécurité pour la gamme Cisco Nexus 9000"^]
 a| 
Fournit des informations sur la conformité aux normes internationales, la sécurité et les réglementations relatives aux commutateurs de la série Nexus 9000.

|===


== Documentation des systèmes ONTAP

Pour configurer un système ONTAP , vous aurez besoin des documents suivants pour votre version du système d'exploitation : https://docs.netapp.com/ontap-9/index.jsp["Centre de documentation ONTAP 9"^] .

[cols="1,2"]
|===
| Nom | Description 


 a| 
https://docs.netapp.com/us-en/ontap-afx/index.html["Documentation des systèmes AFX"^]
 a| 
Ce document décrit la procédure d'installation du matériel NetApp .



 a| 
https://docs.netapp.com/us-en/ontap-family/["Documentation ONTAP"^]
 a| 
Fournit des informations détaillées sur tous les aspects des versions ONTAP .



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
Fournit des informations sur la configuration et la compatibilité du matériel NetApp .

|===