---
permalink: switch-cisco-9332d-gx2b/setup-switch-9332d-cluster.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9332d-gx2b 
summary: Suivez cette procédure pour configurer le commutateur Cisco Nexus 9332D-GX2B. 
---
= Configurer le commutateur 9332D-GX2B
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez cette procédure pour configurer le commutateur Cisco Nexus 9332D-GX2B.

.Avant de commencer
Assurez-vous d'avoir :

* Allumez vos commutateurs.
* Accès à un serveur HTTP, FTP ou TFTP sur le site d'installation pour télécharger les versions NX-OS et de fichier de configuration de référence (RCF) applicables.
* Version NX-OS applicable, téléchargée depuis https://software.cisco.com/download/home["Téléchargement de logiciels Cisco"^] page.


[IMPORTANT]
====
* NX-OS 10.4.2 est la seule version prise en charge pour les commutateurs Cisco Nexus 9332D-GX2B dans un cluster ONTAP .
* Ne mettez pas à niveau ou ne rétrogradez pas votre version NX-OS vers une version non prise en charge ; seule la version 10.4.2 est actuellement prise en charge.


====
* Licences applicables, informations sur le réseau et la configuration, et câbles.
* Fichiers de configuration de réseau partagé et de réseau de gestion NetApp applicables, téléchargeables depuis le site de support NetApp à l'adresse suivante : http://mysupport.netapp.com/["monsupport.netapp.com"^] . Tous les commutateurs de réseau partagé et de réseau de gestion Cisco sont livrés avec la configuration par défaut standard de Cisco . Ces commutateurs disposent également de la version actuelle du logiciel NX-OS mais n'ont pas les RCF chargés.
* link:required-documentation-9332d-cluster.html["Documentation requise pour le commutateur et ONTAP"].


.Étapes
. Effectuez une configuration initiale des commutateurs réseau partagés.
+
Veuillez fournir les réponses appropriées aux questions de configuration initiale suivantes lors du premier démarrage du commutateur.  La politique de sécurité de votre site définit les réponses et les services à activer.

+
[cols="1,2"]
|===
| Rapide | Réponse 


 a| 
Annuler le provisionnement automatique et poursuivre la configuration normale ?  (oui/non)
 a| 
Répondez par *oui*.  La valeur par défaut est non.



 a| 
Souhaitez-vous imposer une norme de mot de passe sécurisé ?  (oui/non)
 a| 
Répondez par *oui*.  La valeur par défaut est oui.



 a| 
Saisissez le mot de passe de l'administrateur.
 a| 
Le mot de passe par défaut est « `admin` » ; vous devez créer un nouveau mot de passe fort.  Un mot de passe faible peut être refusé.



 a| 
Souhaitez-vous accéder à la boîte de dialogue de configuration de base ?  (oui/non)
 a| 
Répondez *oui* lors de la configuration initiale du commutateur.



 a| 
Créer un autre compte de connexion ?  (oui/non)
 a| 
Votre réponse dépend des politiques de votre site concernant les administrateurs alternatifs.  La valeur par défaut est *non*.



 a| 
Configurer la chaîne de communauté SNMP en lecture seule ?  (oui/non)
 a| 
Répondez par *non*.  La valeur par défaut est non.



 a| 
Configurer la chaîne de communauté SNMP en lecture-écriture ?  (oui/non)
 a| 
Répondez par *non*.  La valeur par défaut est non.



 a| 
Saisissez le nom du commutateur.
 a| 
Saisissez le nom du commutateur, qui est limité à 63 caractères alphanumériques.



 a| 
Continuer avec la configuration de gestion hors bande (mgmt0) ?  (oui/non)
 a| 
Répondez par *oui* (par défaut) à cette invite.  À l'invite mgmt0 adresse IPv4 : saisissez votre adresse IP : ip_address.



 a| 
Configurer la passerelle par défaut ?  (oui/non)
 a| 
Répondez par *oui*.  À l'invite « adresse IPv4 de la passerelle par défaut : », saisissez votre passerelle par défaut.



 a| 
Configurer les options IP avancées ?  (oui/non)
 a| 
Répondez par *non*.  La valeur par défaut est non.



 a| 
Activer le service telnet ?  (oui/non)
 a| 
Répondez par *non*.  La valeur par défaut est non.



 a| 
Service SSH activé ?  (oui/non)
 a| 
Répondez par *oui*.  La valeur par défaut est oui.


NOTE: L'utilisation de SSH est recommandée lors de l'utilisation de Ethernet Switch Health Monitor (CSHM) pour ses fonctionnalités de collecte de journaux.  SSHv2 est également recommandé pour une sécurité renforcée.



 a| 
Entrez le type de clé SSH que vous souhaitez générer (dsa/rsa/rsa1).
 a| 
La valeur par défaut est *rsa*.



 a| 
Entrez le nombre de bits clés (1024-2048).
 a| 
Entrez le nombre de bits clés de 1024 à 2048.



 a| 
Configurer le serveur NTP ?  (oui/non)
 a| 
Répondez par *non*.  La valeur par défaut est non.



 a| 
Configurer la couche d'interface par défaut (L3/L2)
 a| 
Répondez avec *L2*.  La valeur par défaut est L2.



 a| 
Configurer l'état par défaut de l'interface du port de commutation (arrêté/non arrêté)
 a| 
Répondez par *noshut*.  La valeur par défaut est noshut.



 a| 
Configurer le profil système CoPP (strict/modéré/souple/dense)
 a| 
Répondez avec *strict*.  Le paramètre par défaut est strict.



 a| 
Souhaitez-vous modifier la configuration ?  (oui/non)
 a| 
Vous devriez voir la nouvelle configuration à ce stade.  Vérifiez et apportez les modifications nécessaires à la configuration que vous venez de saisir.  Répondez *non* à l'invite si la configuration vous convient.  Répondez *oui* si vous souhaitez modifier vos paramètres de configuration.



 a| 
Utilisez cette configuration et enregistrez-la ?  (oui/non)
 a| 
Répondez *oui* pour enregistrer la configuration.  Cela met automatiquement à jour les images Kickstart et système.


NOTE: Si vous ne sauvegardez pas la configuration à cette étape, aucune des modifications ne sera prise en compte lors du prochain redémarrage du commutateur.

|===
. Vérifiez les choix de configuration que vous avez effectués dans l'écran qui apparaît à la fin de l'installation et assurez-vous d'enregistrer la configuration.
. Vérifiez la version installée sur les commutateurs du réseau partagé et, si nécessaire, téléchargez la version du logiciel compatible avec NetApp sur ces commutateurs depuis le site web. https://software.cisco.com/download/home["Téléchargement de logiciels Cisco"^] page.


.Quelle est la prochaine étape ?
Une fois vos commutateurs configurés, vous link:install-nxos-overview-9332d-cluster.html["préparez-vous à installer le logiciel NX-OS et RCF"].
