---
permalink: switch-cisco-9336c-fx2/9336-overview.html 
sidebar: sidebar 
keywords: cisco nexus 9336c-fx2 
summary: Si vous souhaitez créer des clusters ONTAP avec plus de deux nœuds, vous devez prendre en charge deux commutateurs de réseau de clusters. Vous pouvez utiliser des commutateurs de gestion supplémentaires, qui sont facultatifs. 
---
= Présentation du commutateur Cisco 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous souhaitez créer des clusters ONTAP avec plus de deux nœuds, vous devez prendre en charge deux commutateurs de réseau de clusters. Vous pouvez utiliser des commutateurs de gestion supplémentaires, qui sont facultatifs.

Vous pouvez installer le commutateur Cisco Nexus 9336C-FX2 (X190200/X190210) dans une armoire système NetApp ou une armoire tierce avec les supports standard inclus avec le commutateur.

Le tableau suivant répertorie le numéro de référence et la description du commutateur 9336C-FX2, des ventilateurs et des alimentations électriques :

[cols="1,2"]
|===
| Numéro de référence | Description 


 a| 
X190200-CS-PE
 a| 
N9K-9336C-FX2, CS, PTSX, 36PT10/25/40/100GQSFP28



 a| 
X190200-CS-PI
 a| 
N9K-9336C-FX2, CS, PSIN, 36PT10/25/40/100GQSFP28



 a| 
X190210-FE-PE
 a| 
N9K-9336C, FTE, PTSX, 36PT10/25/40/100GQSFP28



 a| 
X190210-FE-PI
 a| 
N9K-9336C, FTE, PSIN, 36PT10/25/40/100GQSFP28



 a| 
X190002
 a| 
Kit d'accessoires X190001/X190003



 a| 
X-NXA-PAC-1100W-PE2
 a| 
N9K-9336C CA 1 100 W PSU - ventilation d'échappement côté port



 a| 
X-NXA-PAC-1100W-PI2
 a| 
N9K-9336C CA 1 100 W PSU - ventilation d'admission côté port



 a| 
X-NXA-FAN-65CFM-PE
 a| 
N9K-9336C 65CFM, débit d'air d'échappement côté port



 a| 
X-NXA-FAN-65CFM-PI
 a| 
N9K-9336C 65CFM, débit d'air d'admission côté port

|===


== Autres commutateurs pris en charge

* Nexus 3232C
+
Vous pouvez installer l'armoire système du switch Cisco Nexus 3232C (X190100) de NetApp avec les supports personnalisés fournis avec le switch, ou l'installer dans un rack avec les supports standard également inclus avec le switch.

* Nexus 3132Q-V
+
Vous pouvez installer le commutateur Cisco Nexus 3132Q-V (X190001) dans une armoire système NetApp ou une armoire tierce avec les supports standard inclus avec le commutateur.



Les commutateurs de cluster suivants ne sont plus disponibles auprès de NetApp, mais ils seront pris en charge par Cisco pendant une durée limitée :

* Nexus 5596UP/5596T
+
Vous pouvez installer le commutateur Cisco Nexus 5596UP (X1967-R6) ou 5596T (X1989-R6) dans une armoire système NetApp avec les supports personnalisés fournis avec le commutateur, ou le installer dans un rack avec les supports standard également inclus avec le commutateur.

+
Le commutateur Nexus 5596UP prend également en charge un ou deux modules d'extension 16 ports (X1988-R6).

+
Le commutateur Nexus 5596T n'est pris en charge qu'en tant que commutateur d'interconnexion de cluster pour le système FAS2520. Il est destiné à effectuer des mises à niveau matérielles sans interruption.

+
http://support.netapp.com/info/communications/ECMP12454150.html["Fin de disponibilité"^] détails.


