---
permalink: switch-cisco-9336c-fx2/cabling-considerations-9336c-fx2.html 
sidebar: sidebar 
keywords: 9336c-fx2 cabling setup, 9336c-fx2 switches configuration, nx-os 
summary: Avant de configurer votre commutateur Cisco 9336C-FX2, consultez les informations suivantes. 
---
= Examiner les considérations relatives au câblage et à la configuration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de configurer vos commutateurs 9336C-FX2 et 9336C-FX2-T, passez en revue les considérations suivantes.



== Prise en charge des ports Ethernet NVIDIA CX6, CX6-DX et CX7

Si vous connectez un port de commutateur à un contrôleur ONTAP en utilisant des ports NIC NVIDIA ConnectX-6 (CX6), ConnectX-6 Dx (CX6-DX) ou ConnectX-7 (CX7), vous devez coder en dur la vitesse du port de commutateur.

[listing, subs="+quotes"]
----
(cs1)(config)# interface Ethernet1/19
*For 100GbE speed:*
(cs1)(config-if)# *speed 100000*
*For 40GbE speed:*
(cs1)(config-if)# *speed 40000*
(cs1)(config-if)# no negotiate auto
(cs1)(config-if)# exit
(cs1)(config)# exit
*Save the changes:*
(cs1)# *copy running-config startup-config*
----
Voir le https://hwu.netapp.com/Switch/Index["Hardware Universe"^] pour plus d'informations sur les ports de commutation.



== Exigences FEC 25GbE



=== Ports FAS2820 e0a/e0b

Les ports FAS2820 e0a et e0b nécessitent des modifications de configuration FEC pour se connecter aux ports de commutation 9336C-FX2 et 9336C-FX2-T. Pour les ports de commutation e0a et e0b, le paramètre fec est défini sur `rs-cons16` .

[listing, subs="+quotes"]
----
(cs1)(config)# interface Ethernet1/8-9
(cs1)(config-if-range)# *fec rs-cons16*
(cs1)(config-if-range)# exit
(cs1)(config)# exit
*Save the changes:*
(cs1)# *copy running-config startup-config*
----


== Les ports ne se connectent pas en raison des ressources TCAM.

Sur les commutateurs 9336C-FX2 et 9336C-FX2-T, les ressources de mémoire adressable de contenu ternaire (TCAM) configurées dans la configuration utilisée par le commutateur sont épuisées.

Consultez l'article de la base de connaissances https://kb.netapp.com/on-prem/Switches/Cisco-KBs/Ports_do_not_link_up_on_Cisco_Nexus_9336C-FX2_due_to_TCAM_resources["Les ports ne se connectent pas sur le Cisco Nexus 9336C-FX2 en raison des ressources TCAM."^] pour plus de détails sur la façon de résoudre ce problème.
