---
permalink: switch-cisco-9336c-fx2/configure-software-overview-9336c-cluster.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch 
summary: Présentation de la configuration logicielle des commutateurs de cluster Cisco Nexus 9336C-FX2 
---
= Workflow d'installation du logiciel pour les commutateurs de cluster Cisco Nexus 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour installer et configurer le logiciel d'un commutateur Cisco Nexus 9336C-FX2 et pour installer ou mettre à niveau le fichier RCF (Reference Configuration File), procédez comme suit :

. link:install-nxos-overview-9336c-cluster.html["Préparez l'installation du logiciel NX-OS et du RCF"].
+
Le logiciel Cisco NX-OS et les fichiers RCF (Reference Configuration File) doivent être installés sur des switchs de cluster Cisco Nexus 9336C-FX2.

. link:install-nxos-software-9336c-cluster.html["Installez ou mettez à niveau le logiciel NX-OS"].
+
Téléchargez et installez ou mettez à niveau le logiciel NX-OS sur le commutateur de cluster Cisco Nexus 9336C-FX2.

. link:install-nxos-rcf-9336c-cluster.html["Installez ou mettez à niveau le RCF"].
+
Installez ou mettez à niveau le RCF après la première configuration du commutateur Cisco Nexus 9336C-FX2. Vous pouvez également utiliser cette procédure pour mettre à niveau votre version RCF.

. link:configure-ssh-keys.html["Générez des clés SSH"].
+
Si vous utilisez le moniteur d'état du commutateur Ethernet (CSHM) et les fonctionnalités de collecte de journaux, générez des clés SSH sur les commutateurs.


