---
permalink: switch-cisco-9336c-fx2/migrate-to-2n-switched-overview.html 
sidebar: sidebar 
keywords: two-node switchless cluster,migrating to a Cisco 9336C-FX2 switch,tnsc 
summary: 'Lors de la migration d"un cluster sans commutateur à deux nœuds sans interruption, vous devez connaître certaines informations de configuration, connexions de ports et exigences de câblage dans un cluster équipé de commutateurs de cluster Cisco Nexus 9336C-FX2. La procédure que vous utilisez dépend de votre présence de deux ports cluster-network dédiés sur chaque contrôleur ou d"un port de cluster unique sur chaque contrôleur. Le processus documenté fonctionne pour tous les nœuds via des ports optiques ou Twinax, mais il n"est pas pris en charge sur ce commutateur si les nœuds utilisent des ports RJ45 10 GbE BASE-T intégrés pour les ports cluster-network.' 
---
= Migrez vers un cluster commuté à deux nœuds avec les commutateurs de cluster Cisco Nexus 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lors de la migration d'un cluster sans commutateur à deux nœuds sans interruption, vous devez connaître certaines informations de configuration, connexions de ports et exigences de câblage dans un cluster équipé de commutateurs de cluster Cisco Nexus 9336C-FX2. La procédure que vous utilisez dépend de votre présence de deux ports cluster-network dédiés sur chaque contrôleur ou d'un port de cluster unique sur chaque contrôleur. Le processus documenté fonctionne pour tous les nœuds via des ports optiques ou Twinax, mais il n'est pas pris en charge sur ce commutateur si les nœuds utilisent des ports RJ45 10 GbE BASE-T intégrés pour les ports cluster-network.

La plupart des systèmes requièrent deux ports dédiés du réseau cluster sur chaque contrôleur. Voir https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Commutateurs Ethernet Cisco"^]
