---
permalink: switch-cisco-9336c-fx2/migrate-cn1610-9336c-cluster.html 
sidebar: sidebar 
keywords: migrate cluster Cisco Nexus 9336C-FX2 cluster switches cn1610 
summary: Vous pouvez migrer sans interruption des commutateurs de cluster NetApp CN1610 pour un cluster ONTAP vers des commutateurs de réseau de cluster Cisco Nexus 9336C-FX2. 
---
= Migration d'un commutateur de cluster NetApp CN1610 vers un commutateur de cluster Cisco 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez migrer les commutateurs de cluster NetApp CN1610 pour un cluster ONTAP vers des commutateurs de cluster Cisco 9336C-FX2. Cette procédure ne fonctionne pas sans interruption.



== Examen des conditions requises

Vous devez connaître certaines informations de configuration, de connexion des ports et de câblage lorsque vous remplacez les commutateurs de cluster NetApp CN1610 par des commutateurs de cluster Cisco 9336C-FX2. Vérifiez également le numéro de série du commutateur pour vous assurer que le bon commutateur est migré.

.Commutateurs pris en charge
Les commutateurs de cluster suivants sont pris en charge :

* NetApp CN1610
* Cisco 9336C-FX2


Pour plus de détails sur les ports pris en charge et leurs configurations, reportez-vous au https://hwu.netapp.com/["Hardware Universe"^].

.Ce dont vous avez besoin
Vérifiez que votre configuration répond aux exigences suivantes :

* Le cluster existant est correctement configuré et fonctionne.
* Tous les ports de cluster sont à l'état *up* pour assurer la continuité de l'activité.
* Les commutateurs de cluster Cisco 9336C-FX2 sont configurés et fonctionnent sous la version NX-OS installée, avec le fichier de configuration de référence (RCF) appliqué.
* La configuration réseau en cluster existante comporte les éléments suivants :
+
** Cluster NetApp redondant et entièrement fonctionnel utilisant des commutateurs NetApp CN1610.
** Connectivité de gestion et accès à la console des commutateurs NetApp CN1610 et des nouveaux commutateurs.
** Toutes les LIFs de cluster à l'état up avec les LIFs de cluster sont sur leurs ports de type home.


* Certains ports sont configurés sur les switchs Cisco 9336C-FX2 pour une exécution à 40 GbE ou 100 GbE.
* Vous avez planifié, migré et documenté la connectivité 40 GbE et 100 GbE depuis des nœuds vers des commutateurs de cluster Cisco 9336C-FX2.




== Migrer les commutateurs

.À propos des exemples
Les exemples de cette procédure utilisent la nomenclature des commutateurs et des nœuds suivante :

* Les commutateurs de cluster CN1610 existants sont _C1_ et _C2_.
* Les nouveaux commutateurs de cluster 9336C-FX2 sont _cs1_ et _cs2_.
* Les nœuds sont _node1_ et _node2_.
* Les LIFS du cluster sont respectivement _node1_clum1_ et _node1_clum2_ sur le nœud 1 et _node2_clum1_ et _node2_clum2_ sur le nœud 2.
* Le `cluster1::*>` l'invite indique le nom du cluster.
* Les ports de cluster utilisés dans cette procédure sont _e3a_ et _e3b_.


.Description de la tâche
Cette procédure couvre le scénario suivant :

* Le commutateur C2 est remplacé en premier par le commutateur cs2.
+
** Arrêtez les ports des nœuds du cluster. Tous les ports doivent être arrêtés simultanément pour éviter l'instabilité du cluster.
** Le câblage entre les nœuds et C2 est ensuite déconnecté de C2 et reconnecté à cs2.


* Le commutateur C1 est remplacé par le commutateur cs1.
+
** Arrêtez les ports des nœuds du cluster. Tous les ports doivent être arrêtés simultanément pour éviter l'instabilité du cluster.
** Le câblage entre les nœuds et C1 est ensuite déconnecté de C1 et reconnecté à cs1.





NOTE: Aucune liaison inter-commutateurs (ISL) opérationnelle n'est nécessaire au cours de cette procédure. Ceci est de par sa conception, car les modifications de version des fichiers RCF peuvent affecter temporairement la connectivité ISL. Pour assurer un fonctionnement sans interruption du cluster, la procédure suivante migre toutes les LIFs du cluster vers le commutateur partenaire opérationnel tout en effectuant les étapes sur le commutateur cible.



=== Étape 1 : préparer la migration

. Si AutoSupport est activé sur ce cluster, supprimez la création automatique de dossiers en invoquant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
où _x_ représente la durée de la fenêtre de maintenance en heures.

. Définissez le niveau de privilège sur avancé, en entrant *y* lorsque vous êtes invité à continuer :
+
`set -privilege advanced`

+
L'invite avancée (*>) apparaît.

. Désactiver la fonction de revert automatique sur les LIFs du cluster :
+
`network interface modify -vserver Cluster -lif * -auto-revert false`





=== Étape 2 : configurer les ports et le câblage

. Détermination du statut administratif ou opérationnel pour chaque interface de cluster
+
Chaque port doit s'afficher pendant `Link` et `healthy` pour `Health Status`.

+
.. Afficher les attributs des ports réseau :
+
`network port show -ipspace Cluster`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
====
.. Afficher des informations sur les LIF et leurs nœuds de base désignés :
+
`network interface show -vserver Cluster`

+
Chaque LIF doit afficher `up/up` pour `Status Admin/Oper` et `true` pour `Is Home`.

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical      Status     Network            Current     Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node        Port    Home
----------- -----------  ---------- ------------------ ----------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1       e3a     true
            node1_clus2  up/up      169.254.49.125/16  node1       e3b     true
            node2_clus1  up/up      169.254.47.194/16  node2       e3a     true
            node2_clus2  up/up      169.254.19.183/16  node2       e3b     true

----
====


. Les ports de cluster de chaque nœud sont connectés aux commutateurs de cluster existants de la manière suivante (du point de vue des nœuds) à l'aide de la commande :
+
`network device-discovery show -protocol`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /cdp
            e3a    C1 (6a:ad:4f:98:3b:3f)    0/1               -
            e3b    C2 (6a:ad:4f:98:4c:a4)    0/1               -
node2      /cdp
            e3a    C1 (6a:ad:4f:98:3b:3f)    0/2               -
            e3b    C2 (6a:ad:4f:98:4c:a4)    0/2               -
----
====
. Les ports et les commutateurs du cluster sont connectés de la manière suivante (du point de vue des commutateurs) à l'aide de la commande :
+
`show cdp neighbors`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
C1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1                 Eth1/1        124    H           AFF-A400         e3a
node2                 Eth1/2        124    H           AFF-A400         e3a
C2                    0/13          179    S I s       CN1610           0/13
C2                    0/14          175    S I s       CN1610           0/14
C2                    0/15          179    S I s       CN1610           0/15
C2                    0/16          175    S I s       CN1610           0/16

C2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute


Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1                 Eth1/1        124    H           AFF-A400         e3b
node2                 Eth1/2        124    H           AFF-A400         e3b
C1                    0/13          175    S I s       CN1610           0/13
C1                    0/14          175    S I s       CN1610           0/14
C1                    0/15          175    S I s       CN1610           0/15
C1                    0/16          175    S I s       CN1610           0/16
----
====
. Vérifiez que le réseau en cluster dispose d'une connectivité complète via la commande :
+
`cluster ping-cluster -node node-name`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*

Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e3a
Cluster node1_clus2 169.254.49.125 node1     e3b
Cluster node2_clus1 169.254.47.194 node2     e3a
Cluster node2_clus2 169.254.19.183 node2     e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====
. Sur le commutateur C2, arrêter les ports connectés aux ports de cluster des nœuds afin de basculer les LIFs du cluster.
+
[listing, subs="+quotes"]
----
(C2)# *configure*
(C2)(Config)# *interface 0/1-0/12*
(C2)(Interface 0/1-0/12)# *shutdown*
(C2)(Interface 0/1-0/12)# *exit*
(C2)(Config)# *exit*
----
. Déplacez les ports de cluster de nœuds de l'ancien commutateur C2 vers le nouveau commutateur cs2, à l'aide du câblage approprié pris en charge par le Cisco 9336C-FX2.
. Afficher les attributs des ports réseau :
+
`network port show -ipspace Cluster`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
====
. Les ports de cluster de chaque nœud sont désormais connectés aux commutateurs de cluster de la façon suivante, du point de vue des nœuds :
+
`network device-discovery show -protocol`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /cdp
            e3a    C1  (6a:ad:4f:98:3b:3f)   0/1               CN1610
            e3b    cs2 (b8:ce:f6:19:1a:7e)   Ethernet1/1/1     N9K-C9336C-FX2
node2      /cdp
            e3a    C1  (6a:ad:4f:98:3b:3f)   0/2               CN1610
            e3b    cs2 (b8:ce:f6:19:1b:96)   Ethernet1/1/2     N9K-C9336C-FX2
----
====
. Sur le commutateur cs2, vérifiez que tous les ports du cluster de nœuds sont activés :
+
`network interface show -vserver Cluster`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current     Current Is
Vserver     Interfac     Admin/Oper Address/Mask       Node        Port    Home
----------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
            node1_clus1  up/up      169.254.3.4/16     node1       e0b     false
            node1_clus2  up/up      169.254.3.5/16     node1       e0b     true
            node2_clus1  up/up      169.254.3.8/16     node2       e0b     false
            node2_clus2  up/up      169.254.3.9/16     node2       e0b     true
----
====
. Sur le commutateur C1, arrêter les ports connectés aux ports de cluster des nœuds afin de basculer les LIFs du cluster.
+
[listing, subs="+quotes"]
----
(C1)# *configure*
(C1)(Config)# *interface 0/1-0/12*
(C1)(Interface 0/1-0/12)# *shutdown*
(C1)(Interface 0/1-0/12)# *exit*
(C1)(Config)# *exit*
----
. Déplacez les ports de cluster de nœuds de l'ancien commutateur C1 vers le nouveau commutateur cs1 à l'aide du câblage approprié pris en charge par le Cisco 9336C-FX2.
. Vérifier la configuration finale du cluster :
+
`network port show -ipspace Cluster`

+
Chaque port doit s'afficher `up` pour `Link` et `healthy` pour `Health Status`.

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
====
. Les ports de cluster de chaque nœud sont désormais connectés aux commutateurs de cluster de la façon suivante, du point de vue des nœuds :
+
`network device-discovery show -protocol`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /cdp
            e3a    cs1 (b8:ce:f6:19:1a:7e)   Ethernet1/1/1   N9K-C9336C-FX2
            e3b    cs2 (b8:ce:f6:19:1b:96)   Ethernet1/1/2   N9K-C9336C-FX2
node2      /cdp
            e3a    cs1 (b8:ce:f6:19:1a:7e)   Ethernet1/1/1   N9K-C9336C-FX2
            e3b    cs2 (b8:ce:f6:19:1b:96)   Ethernet1/1/2   N9K-C9336C-FX2
----
====
. Sur les commutateurs cs1 et cs2, vérifiez que tous les ports de cluster de nœuds sont activés :
+
`network port show -ipspace Cluster`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
. Vérifier que les deux nœuds disposent chacun d'une connexion à chaque commutateur :
+
`network device-discovery show -protocol`

+
.Montrer l'exemple
[%collapsible]
====
L'exemple suivant montre les résultats appropriés pour les deux commutateurs :

[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  --------------
node1      /cdp
            e0a    cs1 (b8:ce:f6:19:1b:42)   Ethernet1/1/1   N9K-C9336C-FX2
            e0b    cs2 (b8:ce:f6:19:1b:96)   Ethernet1/1/2   N9K-C9336C-FX2

node2      /cdp
            e0a    cs1 (b8:ce:f6:19:1b:42)   Ethernet1/1/1   N9K-C9336C-FX2
            e0b    cs2 (b8:ce:f6:19:1b:96)   Ethernet1/1/2   N9K-C9336C-FX2
----
====




=== Étape 3 : réaliser la procédure

. Activer la fonction de revert automatique sur les LIFs du cluster :
+
`cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert true`

. Vérifier que toutes les LIFs du réseau du cluster sont de nouveau sur leurs ports de base :
+
`network interface show`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
----
====
. Pour configurer la collecte des journaux, exécutez la commande suivante pour chaque commutateur. Vous êtes invité à entrer le nom du commutateur, le nom d'utilisateur et le mot de passe pour la collecte des journaux.
+
`system switch ethernet log setup-password`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
====
. Pour démarrer la collecte des journaux, exécutez la commande suivante, en remplaçant le PÉRIPHÉRIQUE par le commutateur utilisé dans la commande précédente. Ceci lance les deux types de collecte de journaux : les journaux détaillés *support* et une collecte horaire de données *périodiques*.
+
`system switch ethernet log modify -device _<switch-name>_ -log-request true`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
cluster1::*>
----
====
+
Attendez 10 minutes, puis vérifiez que la collecte de journaux a réussi à l'aide de la commande :

+
`system switch ethernet log show`

+

NOTE: Si l'une de ces commandes renvoie une erreur, contactez le support NetApp.

. Rétablissez le niveau de privilège sur admin :
+
`set -privilege admin`

. Si vous avez supprimé la création automatique de cas, réactivez-la en appelant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`


