---
permalink: switch-cisco-9336c-fx2/replace-configure-new-switch.html 
sidebar: sidebar 
keywords: Nexus 9336C-FX2 switches initial installation, configure cisco cluster switch 
summary: Vous pouvez configurer un nouveau commutateur Nexus 9336C-FX2 en suivant les étapes décrites dans ce chapitre. 
---
= Configurez un commutateur de cluster Cisco Nexus 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer un nouveau commutateur Nexus 9336C-FX2 en suivant les étapes décrites dans ce chapitre.

L'installation du commutateur Nexus 9336C-FX2 sur les systèmes exécutant ONTAP 9.8 et versions ultérieures commence par la configuration d'une adresse IP et d'une configuration permettant au commutateur de communiquer via l'interface de gestion. Vous pouvez ensuite installer le logiciel NX-OS et le fichier RCF (Reference Configuration File). Cette procédure est destinée à préparer le commutateur Nexus 9336C-FX2 avant l'ajout des contrôleurs.

Les exemples de cette procédure utilisent la nomenclature des commutateurs et des nœuds suivante :

* Les noms des commutateurs Nexus 9336C-FX2 sont cs1 et cs2.
* L'exemple utilisé dans cette procédure lance la mise à niveau sur le second commutateur, _*cs2*._
* Les noms de LIF de cluster sont node1_clude1 et node1_clus2 pour node1, ainsi que node2_clude1 et node2_clus2 pour node2.
* Le nom IPspace est le Cluster.
* Le `cluster1::*>` l'invite indique le nom du cluster.
* les ports de cluster de chaque nœud sont nommés e0a et e0b.
+
Voir la https://hwu.netapp.com["Hardware Universe"^] pour les ports réels de cluster pris en charge sur votre plateforme.

* Les connexions de nœud prises en charge pour les commutateurs Nexus 9336C-FX2 sont les ports 1/1 à 1/34.
* Les liaisons interswitch (ISL) prises en charge par les commutateurs Nexus 9336C-FX2 sont les ports 1/35 et 1/36.
* Les exemples de cette procédure utilisent deux nœuds, mais vous pouvez disposer d'un cluster pouvant atteindre 24 nœuds.

