---
permalink: switch-cisco-9336c-fx2/setup-required-information.html 
sidebar: sidebar 
keywords: configure, cluster, appropriate, number, cable, connector, switch, type, configuring, configure, console, port, network, information, required cluster configuration information - cisco nexus 9336c-fx2 
summary: Pour configurer votre cluster, vous devez disposer du nombre et du type appropriés de câbles et de connecteurs de câbles pour les commutateurs. Selon le type de switch que vous configurez au départ, vous devez vous connecter au port console des commutateurs avec le câble console inclus ; vous devez également fournir des informations réseau spécifiques. 
---
= Informations requises pour la configuration du cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour configurer votre cluster, vous devez disposer du nombre et du type appropriés de câbles et de connecteurs de câbles pour les commutateurs. Selon le type de switch que vous configurez au départ, vous devez vous connecter au port console des commutateurs avec le câble console inclus ; vous devez également fournir des informations réseau spécifiques.

Vous avez besoin des informations réseau suivantes pour toutes les configurations de commutateurs :

* Sous-réseau IP pour le trafic du réseau de gestion
* Noms d'hôte et adresses IP pour chaque contrôleur du système de stockage et tous les commutateurs applicables
* La plupart des contrôleurs de système de stockage sont gérés par l'interface e0M en vous connectant au port de service Ethernet (icône de clé anglaise). Sur les systèmes AFF A800 et AFF A700, l'interface e0M utilise un port Ethernet dédié.


Reportez-vous à la https://hwu.netapp.com["Hardware Universe"^] pour obtenir les informations les plus récentes.



== Informations réseau requises pour les commutateurs Cisco Nexus 9336C-FX2, 92300YC, 3232C, 3132Q-V et 5596UP/5596T

Pour les commutateurs Cisco Nexus 9336C-FX2, 92300YC, 3232C, 3132Q-V et 5596UP/5596T, lors du premier démarrage du commutateur, vous devez fournir les réponses appropriées aux questions de configuration initiale suivantes. La politique de sécurité de votre site définit les réponses et les services à activer.

* Abandonner le provisionnement automatique et poursuivre la configuration normale ? (oui/non) ?
+
Répondez par *oui*. La valeur par défaut est non

* Voulez-vous appliquer une norme de mot de passe sécurisée ? (oui/non) ?
+
Répondez par *oui*. La valeur par défaut est oui.

* Entrez le mot de passe pour admin :
+
Le mot de passe par défaut est ""admin""; vous devez créer un nouveau mot de passe fort. Un mot de passe faible peut être rejeté.

* Voulez-vous entrer la boîte de dialogue de configuration de base ? (oui/non) ?
+
Répondre par *oui* à la configuration initiale du commutateur.

* Créer un autre compte de connexion ? (oui/non) ?
+
Votre réponse dépend des stratégies de votre site concernant les administrateurs secondaires. La valeur par défaut est *non*.

* Configurer la chaîne de communauté SNMP en lecture seule ? (oui/non) ?
+
Répondre par *non*. La valeur par défaut est non

* Configurer la chaîne de communauté SNMP en lecture-écriture ? (oui/non) ?
+
Répondre par *non*. La valeur par défaut est non

* Entrez le nom du commutateur.
+
Le nom du commutateur est limité à 63 caractères alphanumériques.

* Poursuivre la configuration de gestion hors bande (mgmt0) ? (oui/non) ?
+
Répondez par *yes* (par défaut) à cette invite. À l'invite mgmt0 adresse IPv4 :, entrez votre adresse IP : adresse_ip.

* Configurer la passerelle par défaut ? (oui/non) ?
+
Répondez par *oui*. À l'invite Default-Gateway:, saisissez votre passerelle_par_défaut.

* Configurer les options IP avancées ? (oui/non) ?
+
Répondre par *non*. La valeur par défaut est non

* Activer le service telnet ? (oui/non) ?
+
Répondre par *non*. La valeur par défaut est non

* Service SSH activé ? (oui/non) ?
+
Répondez par *oui*. La valeur par défaut est oui.

+

NOTE: SSH est recommandé lors de l'utilisation du moniteur CSHM (Cluster Switch Health Monitor) pour ses fonctions de collecte de journaux. SSHv2 est également recommandé pour une sécurité améliorée.

* Entrez le type de clé SSH que vous souhaitez générer (dsa/rsa/rsa1). La valeur par défaut est *rsa*.
* Entrez le nombre de bits de clé (1024-2048).
* Configurer le serveur NTP ? (oui/non) ?
+
Répondre par *non*. La valeur par défaut est non

* Configurer la couche d'interface par défaut (L3/L2) :
+
Répondre avec *L2*. La valeur par défaut est L2.

* Configurer l'état d'interface du port du commutateur par défaut (shutr/nosolt) :
+
Répondre avec *nohut*. La valeur par défaut est nosott.

* Configuration du profil du système Copp (strict/modéré/ELEDent/dense) :
+
Répondez avec *strict*. La valeur par défaut est stricte.

* Voulez-vous modifier la configuration ? (oui/non) ?
+
La nouvelle configuration est à présent visible. Vérifiez et apportez les modifications nécessaires à la configuration que vous venez de saisir. Répondez par *non* à l'invite si vous êtes satisfait de la configuration. Répondez par *yes* si vous souhaitez modifier vos paramètres de configuration.

* Utilisez cette configuration et enregistrez-la ? (oui/non) ?
+
Répondez avec *yes* pour enregistrer la configuration. Ceci met automatiquement à jour les images kickstart et système.

+

NOTE: Si vous n'enregistrez pas la configuration à ce stade, aucune des modifications ne sera effective lors du prochain redémarrage du commutateur.

+
Pour plus d'informations sur la configuration initiale de votre commutateur, reportez-vous aux guides suivants :

+
https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#InstallandUpgradeGuides["Guides d'installation et de mise à niveau Cisco Nexus 9336C-FX2"^]

+
https://www.cisco.com/c/en/us/support/switches/nexus-92300yc-switch/model.html#InstallandUpgradeGuides["Guides d'installation et de mise à niveau de Cisco Nexus 92300YC"^]

+
https://www.cisco.com/c/en/us/support/switches/nexus-5000-series-switches/products-installation-guides-list.html["Guide d'installation matérielle Cisco Nexus 5000 Series"^]

+
https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Guide d'installation matérielle Cisco Nexus 3000 Series"^]


