---
permalink: switch-cisco-9336c-fx2/setup-worksheet-9336c-cluster.html 
sidebar: sidebar 
keywords: document, support, platform, complete, blank, cabling, worksheet, guide, cisco, nexus, cisco nexus 9336c-fx2 cabling worksheet - cisco nexus 9336-fx2-t 
summary: 'Si vous souhaitez documenter les plateformes prises en charge, vous devez remplir la feuille de câblage vierge en utilisant comme guide l"exemple de feuille de câblage remplie.' 
---
= Complétez la fiche de câblage Cisco Nexus 9336C-FX2 ou 9336C-FX2-T
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous souhaitez documenter les plateformes prises en charge, téléchargez le PDF de cette page et remplissez la fiche de câblage.

La fiche de câblage type fournit des exemples d'affectations de ports recommandées entre les commutateurs et les contrôleurs.  La feuille de calcul vierge fournit un modèle que vous pouvez utiliser pour configurer votre cluster.

* <<Fiche de câblage d'exemple 9336C-FX2>>
* <<Feuille de câblage vierge 9336C-FX2>>
* <<Fiche de câblage d'exemple 9336C-FX2-T (12 ports)>>
* <<Feuille de câblage vierge 9336C-FX2-T (12 ports)>>




== Fiche de câblage d'exemple 9336C-FX2

La définition des ports d'exemple sur chaque paire de commutateurs est la suivante :

[cols="1, 1, 1, 1"]
|===
2+| Commutateur de cluster A 2+| Commutateur de cluster B 


| Port de commutation | Utilisation des nœuds et des ports | Port de commutation | Utilisation des nœuds et des ports 


 a| 
1
 a| 
Nœud 1 4x10GbE
 a| 
1
 a| 
Nœud 1 4x10GbE



 a| 
2
 a| 
Nœud 2 4x10GbE
 a| 
2
 a| 
Nœud 2 4x10GbE



 a| 
3
 a| 
Nœud 3 4x10GbE
 a| 
3
 a| 
Nœud 3 4x10GbE



 a| 
4
 a| 
Nœud 4 x 25 GbE
 a| 
4
 a| 
Nœud 4 x 25 GbE



 a| 
5
 a| 
Nœud 5 4x25GbE
 a| 
5
 a| 
Nœud 5 4x25GbE



 a| 
6
 a| 
Nœud 6 4x25GbE
 a| 
6
 a| 
Nœud 6 4x25GbE



 a| 
7
 a| 
Nœud 7 40/100GbE
 a| 
7
 a| 
Nœud 7 40/100GbE



 a| 
8
 a| 
Nœud 8 40/100GbE
 a| 
8
 a| 
Nœud 8 40/100GbE



 a| 
9
 a| 
Nœud 9 40/100GbE
 a| 
9
 a| 
Nœud 9 40/100GbE



 a| 
10
 a| 
Nœud 10 40/100GbE
 a| 
10
 a| 
Nœud 10 40/100GbE



 a| 
11
 a| 
Nœud 11 40/100GbE
 a| 
11
 a| 
Nœud 11 40/100GbE



 a| 
12
 a| 
Nœud 12 40/100GbE
 a| 
12
 a| 
Nœud 12 40/100GbE



 a| 
13
 a| 
Nœud 13 40/100GbE
 a| 
13
 a| 
Nœud 13 40/100GbE



 a| 
14
 a| 
Nœud 14 40/100GbE
 a| 
14
 a| 
Nœud 14 40/100GbE



 a| 
15
 a| 
Nœud 15 40/100GbE
 a| 
15
 a| 
Nœud 15 40/100GbE



 a| 
16
 a| 
Nœud 16 40/100GbE
 a| 
16
 a| 
Nœud 16 40/100GbE



 a| 
17
 a| 
Nœud 17 40/100GbE
 a| 
17
 a| 
Nœud 17 40/100GbE



 a| 
18
 a| 
Nœud 18 40/100GbE
 a| 
18
 a| 
Nœud 18 40/100GbE



 a| 
19
 a| 
Nœud 40/100GbE 19
 a| 
19
 a| 
Nœud 40/100GbE 19



 a| 
20
 a| 
Nœud 40/100GbE 20
 a| 
20
 a| 
Nœud 40/100GbE 20



 a| 
21
 a| 
Nœud 21 40/100GbE
 a| 
21
 a| 
Nœud 21 40/100GbE



 a| 
22
 a| 
Nœud 22 40/100GbE
 a| 
22
 a| 
Nœud 22 40/100GbE



 a| 
23
 a| 
Nœud 23 40/100GbE
 a| 
23
 a| 
Nœud 23 40/100GbE



 a| 
24
 a| 
Nœud 24 40/100GbE
 a| 
24
 a| 
Nœud 24 40/100GbE



 a| 
25 à 34 ans
 a| 
Réservé
 a| 
25 à 34 ans
 a| 
Réservé



 a| 
35
 a| 
Liaison interconnexion 100 GbE vers le port 35 du commutateur B
 a| 
35
 a| 
Liaison interconnexion 100 GbE vers le port 35 du commutateur A



 a| 
36
 a| 
Liaison interconnexion 100 GbE vers le port 36 du commutateur B
 a| 
36
 a| 
Liaison interconnexion 100 GbE vers le port 36 du commutateur A

|===


== Feuille de câblage vierge 9336C-FX2

Vous pouvez utiliser la feuille de câblage vierge pour documenter les plateformes prises en charge en tant que nœuds dans un cluster.  La section _Connexions de cluster prises en charge_ de https://hwu.netapp.com["Hardware Universe"^] définit les ports du cluster utilisés par la plateforme.

[cols="1, 1, 1, 1"]
|===
2+| Commutateur de cluster A 2+| Commutateur de cluster B 


 a| 
1
 a| 
 a| 
1
 a| 



 a| 
2
 a| 
 a| 
2
 a| 



 a| 
3
 a| 
 a| 
3
 a| 



 a| 
4
 a| 
 a| 
4
 a| 



 a| 
5
 a| 
 a| 
5
 a| 



 a| 
6
 a| 
 a| 
6
 a| 



 a| 
7
 a| 
 a| 
7
 a| 



 a| 
8
 a| 
 a| 
8
 a| 



 a| 
9
 a| 
 a| 
9
 a| 



 a| 
10
 a| 
 a| 
10
 a| 



 a| 
11
 a| 
 a| 
11
 a| 



 a| 
12
 a| 
 a| 
12
 a| 



 a| 
13
 a| 
 a| 
13
 a| 



 a| 
14
 a| 
 a| 
14
 a| 



 a| 
15
 a| 
 a| 
15
 a| 



 a| 
16
 a| 
 a| 
16
 a| 



 a| 
17
 a| 
 a| 
17
 a| 



 a| 
18
 a| 
 a| 
18
 a| 



 a| 
19
 a| 
 a| 
19
 a| 



 a| 
20
 a| 
 a| 
20
 a| 



 a| 
21
 a| 
 a| 
21
 a| 



 a| 
22
 a| 
 a| 
22
 a| 



 a| 
23
 a| 
 a| 
23
 a| 



 a| 
24
 a| 
 a| 
24
 a| 



 a| 
25 à 34 ans
 a| 
Réservé
 a| 
25 à 34 ans
 a| 
Réservé



 a| 
35
 a| 
Liaison interconnexion 100 GbE vers le port 35 du commutateur B
 a| 
35
 a| 
Liaison interconnexion 100 GbE vers le port 35 du commutateur A



 a| 
36
 a| 
Liaison interconnexion 100 GbE vers le port 36 du commutateur B
 a| 
36
 a| 
Liaison interconnexion 100 GbE vers le port 36 du commutateur A

|===


== Fiche de câblage d'exemple 9336C-FX2-T (12 ports)

La définition des ports d'exemple sur chaque paire de commutateurs est la suivante :

[cols="1, 1, 1, 1"]
|===
2+| Commutateur de cluster A 2+| Commutateur de cluster B 


| Port de commutation | Utilisation des nœuds et des ports | Port de commutation | Utilisation des nœuds et des ports 


 a| 
1
 a| 
Nœud 1 4x10GbE
 a| 
1
 a| 
Nœud 1 4x10GbE



 a| 
2
 a| 
Nœud 2 4x10GbE
 a| 
2
 a| 
Nœud 2 4x10GbE



 a| 
3
 a| 
Nœud 3 4x10GbE
 a| 
3
 a| 
Nœud 3 4x10GbE



 a| 
4
 a| 
Nœud 4 x 25 GbE
 a| 
4
 a| 
Nœud 4 x 25 GbE



 a| 
5
 a| 
Nœud 5 4x25GbE
 a| 
5
 a| 
Nœud 5 4x25GbE



 a| 
6
 a| 
Nœud 6 4x25GbE
 a| 
6
 a| 
Nœud 6 4x25GbE



 a| 
7
 a| 
Nœud 7 40/100GbE
 a| 
7
 a| 
Nœud 7 40/100GbE



 a| 
8
 a| 
Nœud 8 40/100GbE
 a| 
8
 a| 
Nœud 8 40/100GbE



 a| 
9
 a| 
Nœud 9 40/100GbE
 a| 
9
 a| 
Nœud 9 40/100GbE



 a| 
10
 a| 
Nœud 10 40/100GbE
 a| 
10
 a| 
Nœud 10 40/100GbE



 a| 
11 à 34
 a| 
Licence requise
 a| 
11 à 34
 a| 
Licence requise



 a| 
35
 a| 
Liaison interconnexion 100 GbE vers le port 35 du commutateur B
 a| 
35
 a| 
Liaison interconnexion 100 GbE vers le port 35 du commutateur A



 a| 
36
 a| 
Liaison interconnexion 100 GbE vers le port 36 du commutateur B
 a| 
36
 a| 
Liaison interconnexion 100 GbE vers le port 36 du commutateur A

|===


== Feuille de câblage vierge 9336C-FX2-T (12 ports)

Vous pouvez utiliser la feuille de câblage vierge pour documenter les plateformes prises en charge en tant que nœuds dans un cluster.  La section _Connexions de cluster prises en charge_ de https://hwu.netapp.com["Hardware Universe"^] définit les ports du cluster utilisés par la plateforme.

[cols="1, 1, 1, 1"]
|===
2+| Commutateur de cluster A 2+| Commutateur de cluster B 


 a| 
1
 a| 
 a| 
1
 a| 



 a| 
2
 a| 
 a| 
2
 a| 



 a| 
3
 a| 
 a| 
3
 a| 



 a| 
4
 a| 
 a| 
4
 a| 



 a| 
5
 a| 
 a| 
5
 a| 



 a| 
6
 a| 
 a| 
6
 a| 



 a| 
7
 a| 
 a| 
7
 a| 



 a| 
8
 a| 
 a| 
8
 a| 



 a| 
9
 a| 
 a| 
9
 a| 



 a| 
10
 a| 
 a| 
10
 a| 



 a| 
11 à 34
 a| 
Licence requise
 a| 
11 à 34
 a| 
Licence requise



 a| 
35
 a| 
Liaison interconnexion 100 GbE vers le port 35 du commutateur B
 a| 
35
 a| 
Liaison interconnexion 100 GbE vers le port 35 du commutateur A



 a| 
36
 a| 
Liaison interconnexion 100 GbE vers le port 36 du commutateur B
 a| 
36
 a| 
Liaison interconnexion 100 GbE vers le port 36 du commutateur A

|===
Voir le https://hwu.netapp.com/Switch/Index["Hardware Universe"] pour plus d'informations sur les ports de commutation.

.Quelle est la prochaine étape
Une fois vos feuilles de travail sur le câblage terminées, vous pouvez link:install-switch-9336c-cluster.html["installer le commutateur"].
