---
permalink: switch-cisco-9336c-fx2/setup-switches.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9336c-fx2 
summary: Si vous ne possédez pas encore la documentation et les informations de configuration requises, vous devez les collecter avant de configurer votre cluster et vos commutateurs de réseau de gestion. 
---
= Configurer les commutateurs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous ne possédez pas encore la documentation et les informations de configuration requises, vous devez les collecter avant de configurer votre cluster et vos commutateurs de réseau de gestion.

* Vous devez avoir accès à un serveur HTTP, FTP ou TFTP sur le site d'installation pour télécharger les versions NX-OS et RCF (Reference Configuration File) applicables.
* Vous devez disposer de la documentation requise sur le réseau de clusters et les commutateurs de réseau de gestion.
+
Voir xref:setup-required-documentation.adoc[Documentation requise] pour en savoir plus.

* Vous devez disposer de la documentation requise sur le contrôleur et de la documentation ONTAP.
+
https://netapp.com/us/documenation/index.aspx["Documentation NetApp"^]

* Vous devez disposer des licences, des informations de réseau et de configuration et des câbles applicables.
* Vous devez avoir rempli les fiches de câblage.
+

NOTE: En raison de la complexité résultant de l'illustration de couches de câblage, ce guide ne fournit pas de graphiques de câblage. Ce guide fournit des exemples de feuilles de calcul contenant des affectations de ports recommandées et des feuilles de calcul vierges que vous pouvez utiliser pour configurer votre cluster.

+

NOTE: Pour plus d'informations, reportez-vous à la https://hwu.netapp.com["Hardware Universe"^].

* Tous les commutateurs de réseau de gestion et de réseau de cluster Cisco sont livrés avec la configuration par défaut standard de Cisco. Ces commutateurs ont également la version actuelle du logiciel NX-OS, mais ils ne sont pas chargés.



NOTE: Vous devez télécharger les RCFs réseau et réseau de gestion de clusters NetApp applicables sur le site de support NetApp à l'adresse http://mysupport.netapp.com/["mysupport.netapp.com"^] pour les commutateurs que vous recevez.

* De plus, vous devrez peut-être installer le fichier de configuration requis pour prendre en charge le moniteur d'intégrité des commutateurs de cluster (CSHM) pour les commutateurs de cluster 92300YC. Voir link:setup_install_cshm_file.md#["Installation du fichier de configuration CSHM (Cluster Switch Health Monitor) pour les commutateurs 92300YC"] pour plus d'informations.


.Étapes
. Installez les commutateurs et les contrôleurs du réseau de gestion et de réseau de cluster.
+
[cols="1,2"]
|===
| Si vous installez... | Alors... 


 a| 
Cisco Nexus 9336C-FX2 dans une armoire système NetApp
 a| 
Pour savoir comment installer le commutateur dans une armoire NetApp, reportez-vous au document _installation d'un panneau de commande et d'un commutateur du cluster Cisco Nexus 9336C-FX2 dans une armoire NetApp_.



 a| 
Cisco Nexus 3232C dans une armoire système NetApp
 a| 
Reportez-vous au _installation d'un commutateur de cluster Cisco Nexus 3232C et d'un panneau de pass-through dans un guide d'armoire NetApp pour obtenir des instructions concernant l'installation du switch dans une armoire NetApp.



 a| 
Cisco Nexus 3132Q-V dans une armoire système NetApp
 a| 
Consultez le document _installation d'un commutateur de cluster Cisco Nexus 3132Q-V et d'un panneau d'intercommunication dans une armoire NetApp_ guide pour obtenir des instructions d'installation du commutateur dans une armoire NetApp.



 a| 
Équipement dans un rack Telco
 a| 
Consultez les procédures fournies dans les guides d'installation du matériel du commutateur et les instructions d'installation et de configuration de NetApp.



 a| 
Cisco Nexus 5596UP/5596T dans une armoire système NetApp
 a| 
Voir le _installation d'un commutateur de cluster Cisco Nexus 5596 et d'un panneau pass-through dans une armoire NetApp_ guide pour obtenir des instructions sur l'installation du commutateur dans une armoire NetApp.

|===
. Reliez les commutateurs du réseau de cluster et du réseau de gestion aux contrôleurs à l'aide des fiches de câblage complétées.
. Mettez le réseau de cluster sous tension, ainsi que les commutateurs et les contrôleurs du réseau de gestion.
. Configurer initiale des commutateurs du réseau du cluster en fonction des informations du xref:setup-required-information.adoc[Informations de configuration requises].
. Vérifiez les choix de configuration que vous avez effectués à l'écran qui s'affiche à la fin de la configuration et assurez-vous d'enregistrer la configuration.
. Vérifier la version des commutateurs du réseau du cluster et, le cas échéant, télécharger la version prise en charge par NetApp du logiciel vers les commutateurs.
+
Si vous téléchargez la version prise en charge par NetApp du logiciel, vous devez également télécharger le _NetApp Cluster Network Switch Reference Configuration File_ et la fusionner avec la configuration enregistrée à l'étape 5. Vous pouvez télécharger le fichier et les instructions à partir du https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Commutateurs Ethernet Cisco"^] page.

. Vérifiez la version logicielle des commutateurs réseau et, le cas échéant, téléchargez la version prise en charge par NetApp des commutateurs. Si vous disposez de vos propres commutateurs, reportez-vous à la https://cisco.com["Site Cisco"^].
+
Si vous téléchargez la version prise en charge par NetApp du logiciel, vous devez également télécharger le _NetApp Management Network Switch Reference Configuration File_ et la fusionner avec la configuration enregistrée à l'étape 5. Vous pouvez télécharger le fichier et les instructions à partir du https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Commutateurs Ethernet Cisco"^] page.



xref:setup-required-information.adoc[Informations requises pour la configuration du cluster]

xref:setup-required-documentation.adoc[Documentation requise]

xref:setup-worksheets-sample-cabling.adoc[Exemple de fiches de câblage vierges]
