---
permalink: switch-cisco-9336c-fx2/setup-considerations-smart-call.html 
sidebar: sidebar 
keywords: cisco smart call,small call home 
summary: 'Smart Call Home surveille le matériel et les composants logiciels de votre réseau afin de générer une notification par e-mail des conditions système critiques. Lorsqu"un événement se produit sur votre terminal, l"appel intelligent affiche une alerte pour tous les destinataires configurés dans votre profil de destination.' 
---
= Considérations relatives à l'utilisation de la fonction d'appel intelligent
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Smart Call Home surveille le matériel et les composants logiciels de votre réseau afin de générer une notification par e-mail des conditions système critiques. Lorsqu'un événement se produit sur votre terminal, l'appel intelligent affiche une alerte pour tous les destinataires configurés dans votre profil de destination.

Vous devez configurer un commutateur réseau de cluster pour communiquer par courrier électronique avec le système d'appel intelligent. Vous pouvez configurer votre commutateur de réseau de cluster pour tirer parti de la fonction de prise en charge intégrée de Smart Call Home de Cisco.

Avant de pouvoir utiliser la fonction d'appel intelligent, vous devez prendre en compte les considérations suivantes :

* Un serveur de messagerie doit être en place.
* Le commutateur doit disposer d'une connexion IP au serveur de messagerie.
* Le nom du contact (contact du serveur SNMP), le numéro de téléphone et l'adresse postale doivent être configurés.
* Ceci est nécessaire pour déterminer l'origine des messages reçus.
* Un CCO ID doit être associé à un contrat Cisco SMARTnet Service approprié pour votre entreprise.
* Le service Cisco SMARTnet doit être en place pour que le périphérique soit enregistré.


Le site d'assistance Cisco contient des informations sur les commandes permettant de configurer Smart Call Home.

http://www.cisco.com/c/en/us/products/switches/index.html["Site d'assistance Cisco"^]
