---
permalink: switch-cisco-9336c-fx2/setup-worksheet-5596.html 
sidebar: sidebar 
keywords: cable worksheet, Cisco NX 5596T 
summary: 'Si vous souhaitez documenter les plates-formes prises en charge, vous devez remplir la fiche de câblage vierge en utilisant l"exemple de fiche de câblage rempli comme guide.' 
---
= Fiche de câblage Cisco Nexus 5596UP et 5596T
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous souhaitez documenter les plates-formes prises en charge, vous devez remplir la fiche de câblage vierge en utilisant l'exemple de fiche de câblage rempli comme guide.



== Exemple de fiche de câblage

Certaines plateformes prennent en charge plusieurs connexions 10GbE à port de cluster par commutateur d'interconnexion de cluster. Pour prendre en charge des connexions de cluster supplémentaires, vous pouvez utiliser les ports 25 à 40, ainsi que les ports 49 à 80 lorsque des modules d'extension sont installés.

L'exemple de définition de port sur chaque paire de commutateurs est le suivant :

[cols="1, 1, 1, 1"]
|===
2+| Commutateur de cluster A 2+| Commutateur de cluster B 


| Port du commutateur | Utilisation du nœud et du port | Port du commutateur | Utilisation du nœud et du port 


 a| 
1
 a| 
Port de nœud 1
 a| 
1
 a| 
Port de nœud 1



 a| 
2
 a| 
Port de nœud 2
 a| 
2
 a| 
Port de nœud 2



 a| 
3
 a| 
Port de nœuds 3
 a| 
3
 a| 
Port de nœuds 3



 a| 
4
 a| 
Port de nœuds 4
 a| 
4
 a| 
Port de nœuds 4



 a| 
5
 a| 
Port de nœuds 5
 a| 
5
 a| 
Port de nœuds 5



 a| 
6
 a| 
Port de nœuds 6
 a| 
6
 a| 
Port de nœuds 6



 a| 
7
 a| 
Port de nœuds 7
 a| 
7
 a| 
Port de nœuds 7



 a| 
8
 a| 
Port de nœuds 8
 a| 
8
 a| 
Port de nœuds 8



 a| 
9
 a| 
Port de nœuds 9
 a| 
9
 a| 
Port de nœuds 9



 a| 
10
 a| 
Port de nœuds 10
 a| 
10
 a| 
Port de nœuds 10



 a| 
11
 a| 
Port de nœuds 11
 a| 
11
 a| 
Port de nœuds 11



 a| 
12
 a| 
Port de nœuds 12
 a| 
12
 a| 
Port de nœuds 12



 a| 
13
 a| 
Port de nœuds 13
 a| 
13
 a| 
Port de nœuds 13



 a| 
14
 a| 
Port de nœuds 14
 a| 
14
 a| 
Port de nœuds 14



 a| 
15
 a| 
Port de nœuds 15
 a| 
15
 a| 
Port de nœuds 15



 a| 
16
 a| 
Port de nœuds 16
 a| 
16
 a| 
Port de nœuds 16



 a| 
17
 a| 
Port de nœuds 17
 a| 
17
 a| 
Port de nœuds 17



 a| 
18
 a| 
Port de nœuds 18
 a| 
18
 a| 
Port de nœuds 18



 a| 
19
 a| 
Port de nœuds 19
 a| 
19
 a| 
Port de nœuds 19



 a| 
20
 a| 
Port de nœuds 20
 a| 
20
 a| 
Port de nœuds 20



 a| 
21
 a| 
Port de nœuds 21
 a| 
21
 a| 
Port de nœuds 21



 a| 
22
 a| 
Port de nœuds 22
 a| 
22
 a| 
Port de nœuds 22



 a| 
23
 a| 
Port de nœuds 23
 a| 
23
 a| 
Port de nœuds 23



 a| 
24
 a| 
Port de nœuds 24
 a| 
24
 a| 
Port de nœuds 24



 a| 
25 à 40
 a| 
Réservé
 a| 
25 à 40
 a| 
Réservé



 a| 
41
 a| 
ISL vers le port B du commutateur 41
 a| 
41
 a| 
ISL pour basculer sur le port A 41



 a| 
42
 a| 
ISL vers le port B du commutateur 42
 a| 
42
 a| 
ISL pour basculer sur le port A 42



 a| 
43
 a| 
ISL vers le port B du commutateur 43
 a| 
43
 a| 
ISL pour basculer sur le port A 43



 a| 
44
 a| 
ISL vers le port B du commutateur 44
 a| 
44
 a| 
ISL pour basculer sur le port A 44



 a| 
45
 a| 
ISL vers le port B du commutateur 45
 a| 
45
 a| 
ISL pour basculer sur le port A 45



 a| 
46
 a| 
ISL vers le port B du commutateur 46
 a| 
46
 a| 
ISL pour basculer sur le port A 46



 a| 
47
 a| 
ISL vers le port B du commutateur 47
 a| 
47
 a| 
ISL pour basculer sur le port A 47



 a| 
48
 a| 
ISL vers le port B du commutateur 48
 a| 
48
 a| 
ISL pour basculer sur le port A 48

|===


== Feuille de câblage vierge

Vous pouvez utiliser la fiche de câblage vide pour documenter les plateformes prises en charge en tant que nœuds dans un cluster. La section _supportées Cluster Connections_ de _Hardware Universe_ définit les ports de cluster utilisés par la plate-forme.


NOTE: Les ports de commutateur 1 à 24 fonctionnent comme des ports 10 GbE. Les ports de commutation 41 à 48 sont réservés aux liaisons interswitch (ISL).

[cols="1, 1, 1, 1"]
|===
2+| Commutateur de cluster A 2+| Commutateur de cluster B 


| Port du commutateur | Utilisation du nœud/port | Port du commutateur | Utilisation du nœud/port 


 a| 
1
 a| 
 a| 
1
 a| 



 a| 
2
 a| 
 a| 
2
 a| 



 a| 
3
 a| 
 a| 
3
 a| 



 a| 
4
 a| 
 a| 
4
 a| 



 a| 
5
 a| 
 a| 
5
 a| 



 a| 
6
 a| 
 a| 
6
 a| 



 a| 
7
 a| 
 a| 
7
 a| 



 a| 
8
 a| 
 a| 
8
 a| 



 a| 
9
 a| 
 a| 
9
 a| 



 a| 
10
 a| 
 a| 
10
 a| 



 a| 
11
 a| 
 a| 
11
 a| 



 a| 
12
 a| 
 a| 
12
 a| 



 a| 
13
 a| 
 a| 
13
 a| 



 a| 
14
 a| 
 a| 
14
 a| 



 a| 
15
 a| 
 a| 
15
 a| 



 a| 
16
 a| 
 a| 
16
 a| 



 a| 
17
 a| 
 a| 
17
 a| 



 a| 
18
 a| 
 a| 
18
 a| 



 a| 
19
 a| 
 a| 
19
 a| 



 a| 
20
 a| 
 a| 
20
 a| 



 a| 
21
 a| 
 a| 
21
 a| 



 a| 
22
 a| 
 a| 
22
 a| 



 a| 
23
 a| 
 a| 
23
 a| 



 a| 
24
 a| 
 a| 
24
 a| 



 a| 
25 à 40
 a| 
Réservé
 a| 
25 à 40
 a| 
Réservé



 a| 
41
 a| 
ISL vers le port B du commutateur 41
 a| 
41
 a| 
ISL pour basculer sur le port A 41



 a| 
42
 a| 
ISL vers le port B du commutateur 42
 a| 
42
 a| 
ISL pour basculer sur le port A 42



 a| 
43
 a| 
ISL vers le port B du commutateur 43
 a| 
43
 a| 
ISL pour basculer sur le port A 43



 a| 
44
 a| 
ISL vers le port B du commutateur 44
 a| 
44
 a| 
ISL pour basculer sur le port A 44



 a| 
45
 a| 
ISL vers le port B du commutateur 45
 a| 
45
 a| 
ISL pour basculer sur le port A 45



 a| 
46
 a| 
ISL vers le port B du commutateur 46
 a| 
46
 a| 
ISL pour basculer sur le port A 46



 a| 
47
 a| 
ISL vers le port B du commutateur 47
 a| 
47
 a| 
ISL pour basculer sur le port A 47



 a| 
48
 a| 
ISL vers le port B du commutateur 48
 a| 
48
 a| 
ISL pour basculer sur le port A 48

|===