---
permalink: switch-cisco-9336c-fx2/smart-call-9336c-cluster.html 
sidebar: sidebar 
keywords: cisco smart call,small call home 
summary: 'Smart Call Home surveille les composants matériels et logiciels de votre réseau afin de générer une notification par e-mail en cas de conditions système critiques.  Lorsqu"un événement se produit sur votre appareil, Smart Call Home envoie une alerte à tous les destinataires configurés dans votre profil de destination.' 
---
= Exigences de Smart Call Home
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour utiliser Smart Call Home, vous devez configurer un commutateur réseau en cluster pour communiquer par courrier électronique avec le système Smart Call Home. De plus, vous pouvez éventuellement configurer votre commutateur réseau en cluster pour profiter de la fonction de prise en charge Smart Call Home intégrée de Cisco.

Le service Smart Call Home de Cisco surveille les composants matériels et logiciels de votre réseau. Lorsqu'une configuration système critique se produit, il génère une notification par e-mail et déclenche une alerte à tous les destinataires configurés dans votre profil de destination.

[NOTE]
====
ONTAP prend en charge la surveillance de l'état des commutateurs Ethernet (CSHM) pour surveiller les commutateurs du cluster AFX, ainsi que la possibilité de collecter les journaux de diagnostic des commutateurs.

La fonction Smart Call Home de Cisco est une option permettant de fournir une assistance proactive et de vous aider à résoudre tout problème pouvant survenir avec les commutateurs.

====
Avant de pouvoir utiliser Smart Call Home, tenez compte des exigences suivantes :

* Un serveur de messagerie doit être installé.
* Le commutateur doit disposer d'une connectivité IP avec le serveur de messagerie.
* Les informations relatives au nom du contact (contact du serveur SNMP), au numéro de téléphone et à l'adresse postale doivent être configurées.  Cela est nécessaire pour déterminer l'origine des messages reçus.
* Un identifiant CCO doit être associé à un contrat de service Cisco SMARTnet approprié pour votre entreprise.
* Le service Cisco SMARTnet doit être installé pour que l'appareil puisse être enregistré.


Le http://www.cisco.com/c/en/us/products/switches/index.html["site d'assistance Cisco"^] Contient des informations sur les commandes permettant de configurer Smart Call Home.

La fonction Smart Call Home peut être configurée lors de l'installation et de la configuration d'un nouveau système ou ultérieurement.
