---
permalink: switch-bes-53248/components-bes53248.html 
sidebar: sidebar 
keywords: cluster-mode,supported versions,switches supported,cluster network,efos 
summary: 'Pour l"installation et la maintenance du commutateur BES-53248, assurez-vous de consulter la liste des composants et des numéros de pièces.' 
---
= Composants et références des commutateurs de groupe BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour l'installation et la maintenance du commutateur BES-53248, assurez-vous de consulter la liste des composants et des numéros de pièces.

Le tableau suivant répertorie le numéro de pièce, la description et les versions minimales EFOS et ONTAP des composants du commutateur de cluster BES-53248, y compris les détails du kit de montage en rack.


NOTE: Une version minimale d'EFOS de *3.10.0.3* est requise pour les numéros de pièces *X190005-B* et *X190005R-B*.

[cols="20,40,20,20"]
|===
| Numéro de pièce | Description | Version minimale d'EFOS | Version minimale ONTAP 


 a| 
X190005-B
 a| 
BES-53248-B/IX8, CLSW, 16PT10/25GB, PTSX (PTSX = Échappement côté bâbord)
 a| 
3.10.0.3
 a| 
9,8



 a| 
X190005R-B
 a| 
BES-53248-B/IX8, CLSW, 16PT10/25 Go, PSIN (PSIN = prise côté port)
 a| 
3.10.0.3
 a| 
9,8



 a| 
X190005
 a| 
BES-53248, CLSW, 16Pt10/25GB, PTSX, BRDCM SUPP
 a| 
3.4.4.6
 a| 
9.5P8



 a| 
X190005R
 a| 
BES-53248, CLSW, 16Pt10/25GB, PSIN, BRDCM SUPP
 a| 
3.4.4.6
 a| 
9.5P8



 a| 
X-RAIL-4POST-190005
 a| 
Kit de rails de montage en rack Ozeki 4 montants 19"
 a| 
S/O
 a| 
S/O

|===

IMPORTANT: Veuillez noter les informations suivantes concernant les types de machines :

[cols="50,50"]
|===
| Type de machine | Version minimale d'EFOS 


 a| 
BES-53248A1
| 3.4.4.6 


 a| 
BES-53248A2
| 3.10.0.3 


 a| 
BES-53248A3
| 3.10.0.3 
|===
Vous pouvez déterminer le type spécifique de votre machine en utilisant la commande : `show version`

.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# *show version*

Switch: cs1

System Description............................. EFOS, 3.10.0.3, Linux 5.4.2-b4581018, 2016.05.00.07
Machine Type................................... *_BES-53248A3_*
Machine Model.................................. BES-53248
Serial Number.................................. QTWCU225xxxxx
Part Number.................................... 1IX8BZxxxxx
Maintenance Level.............................. a3a
Manufacturer................................... QTMC
Burned In MAC Address.......................... C0:18:50:F4:3x:xx
Software Version............................... 3.10.0.3
Operating System............................... Linux 5.4.2-b4581018
Network Processing Device...................... BCM56873_A0
.
.
.
----
====
.Quelle est la prochaine étape
Une fois que vous avez confirmé vos composants et leurs références, vous pouvez consulter le link:required-documentation-bes53248.html["documentation requise"].
