---
permalink: switch-bes-53248/components-bes53248.html 
sidebar: sidebar 
keywords: cluster-mode,supported versions,switches supported,cluster network,efos 
summary: 'Pour l"installation et la maintenance du commutateur BES-53248, veillez à consulter la liste des composants et des références.' 
---
= Composants et références des commutateurs de cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour l'installation et la maintenance du commutateur BES-53248, veillez à consulter la liste des composants et des références.

Le tableau suivant répertorie la référence, la description et les versions minimales de EFOS et de ONTAP pour les composants du commutateur de cluster BES 53248, y compris les détails du kit de rails de montage en rack.


NOTE: Une version EFOS minimale de *3.10.0.3* est requise pour les références *X190005-B* et *X190005R-B*.

[cols="20,40,20,20"]
|===
| Numéro de référence | Description | Version minimale de EFOS | Version minimale de ONTAP 


 a| 
X190005-B.
 a| 
BES-53248-B/IX8, CLSW, 16PT10/25Go, PTSX (PTSX = évacuation côté port)
 a| 
3.10.0.3
 a| 
9.8



 a| 
X190005R-B.
 a| 
BES-53248-B/IX8, CLSW, 16PT10/25 Go, PSIN (PSIN = admission côté port)
 a| 
3.10.0.3
 a| 
9.8



 a| 
X190005
 a| 
BES-53248, CLSW, 16PT10/25GO, PTSX, ASSISTANCE BRDCM
 a| 
3.4.4.6
 a| 
9.5P8



 a| 
X190005R
 a| 
BES-53248, CLSW, 16PT10/25GO, PSIN, ASSISTANCE BRDCM
 a| 
3.4.4.6
 a| 
9.5P8



 a| 
X-RAIL-4POST-190005
 a| 
Kit de rails de montage sur rack Ozeki 4 montants 19"
 a| 
S/O
 a| 
S/O

|===

IMPORTANT: Noter les informations suivantes concernant les types de machine :

[cols="50,50"]
|===
| Type de machine | Version EFOS 


 a| 
BES 53248A1
| 3.4.4.6 


 a| 
BES 53248A2
| 3.10.0.3 


 a| 
BES-53248A3
| 3.10.0.3 
|===
Vous pouvez déterminer votre type de machine spécifique à l'aide de la commande : `show version`

.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# *show version*

Switch: cs1

System Description............................. EFOS, 3.10.0.3, Linux 5.4.2-b4581018, 2016.05.00.07
Machine Type................................... *_BES-53248A3_*
Machine Model.................................. BES-53248
Serial Number.................................. QTWCU225xxxxx
Part Number.................................... 1IX8BZxxxxx
Maintenance Level.............................. a3a
Manufacturer................................... QTMC
Burned In MAC Address.......................... C0:18:50:F4:3x:xx
Software Version............................... 3.10.0.3
Operating System............................... Linux 5.4.2-b4581018
Network Processing Device...................... BCM56873_A0
.
.
.
----
====