---
permalink: switch-bes-53248/configure-reqs-bes53248.html 
sidebar: sidebar 
keywords: bes, cluster, switch, port, assignment, table, configure, bes-53428 cluster switch port assignments - bes-53428 switches 
summary: 'Vous pouvez utiliser la table d"affectation des ports du commutateur de cluster BES-53248 pour configurer votre cluster.' 
---
= Configuration requise pour les commutateurs de cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour l'installation et la maintenance du commutateur BES 53248, vérifiez les exigences de prise en charge et de configuration du système EFOS et du système ONTAP.



== Prise en charge de EFOS et ONTAP

Voir la https://hwu.netapp.com/Switch/Index["NetApp Hardware Universe"^] et https://mysupport.netapp.com/site/info/broadcom-cluster-switch["Matrice de compatibilité des commutateurs Broadcom"^] Pour les informations de compatibilité EFOS et ONTAP avec les commutateurs BES-53248. La prise en charge de l'EFOS et de l'ONTAP peut varier selon le type de machine spécifique du commutateur BES-53248. Pour plus de détails sur tous les types de machines à commutateur BES-52348, voir link:components-bes53248.html["Composants et références des commutateurs de cluster BES-53248"].



== Configuration requise

Pour configurer un cluster, il faut un nombre et un type appropriés de câbles et de connecteurs de câbles pour les commutateurs du cluster. Selon le type de commutateur de cluster que vous configurez au départ, vous devez vous connecter au port console du commutateur avec le câble console inclus.



=== Affectations des ports des commutateurs de cluster

Vous pouvez utiliser le tableau des attributions de ports de commutateur de cluster BES-53248 pris en charge par Broadcom pour configurer votre cluster.

[cols="1,2"]
|===
| Commutateurs | Utilisation des ports 


 a| 
01-16
 a| 
Nœuds de cluster 10 GbE avec port, configuration de base



 a| 
17-48
 a| 
Nœuds de cluster 10 GbE avec licences



 a| 
49-54
 a| 
Ajout de nœuds de port de cluster 40 GbE avec licences, de droite à gauche



 a| 
55-56
 a| 
Ports ISL (Inter-Switch Link) de cluster 100 GbE, configuration de base

|===
Voir la https://hwu.netapp.com/Switch/Index["Hardware Universe"] pour plus d'informations sur les ports de commutateur.



=== Contrainte de vitesse du groupe de ports

* Sur les switchs de cluster BES-53248, les ports 48 10 GbE (SFP28/SFP+) sont combinés en groupes à 12 ports 4-ports comme suit : ports 1-4, 5-8, 9-12, 13-16, 17-20, 21-24, 25-28, 29-32, 33-36, 37-40, 41-44 et 45-48.
* La vitesse des ports SFP28/SFP+ doit être identique (10 GbE ou 25 GbE) sur tous les ports du groupe à 4 ports.




=== Supplémentaires requise

* Si vous achetez des licences supplémentaires, reportez-vous à la section link:configure-licenses.html["Activez les ports de nouvelles licences"] pour plus de détails sur la façon de les activer.
* Si SSH est actif, vous devez le réactiver manuellement après avoir exécuté la commande `erase startup-config` et redémarrage du commutateur.

