---
permalink: switch-bes-53248/configure-software-overview-bes53248.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure new bes-53248 switch 
summary: Passez en revue la présentation du logiciel. 
---
= Workflow d'installation du logiciel pour les commutateurs BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour installer et configurer le logiciel d'un commutateur de cluster BES-53248, procédez comme suit :

. link:configure-efos-software.html["Installez le logiciel EFOS"].
+
Téléchargez et installez le logiciel Ethernet Fabric OS (EFOS) sur le commutateur de cluster BES-53248.

. link:configure-licenses.html["Installez les licences pour les commutateurs de cluster BES-53248"].
+
Vous pouvez également ajouter de nouveaux ports en achetant et en installant des licences supplémentaires. Le modèle de base de switchs est conçu pour 16 ports 10 GbE ou 25 GbE et 2 ports 100 GbE.

. link:configure-install-rcf.html["Installer le fichier RCF (Reference Configuration File)"].
+
Installez ou mettez à niveau le RCF sur le commutateur de cluster BES-53248, puis vérifiez si les ports ne correspondent pas à une licence supplémentaire après l'application du RCF.

. link:configure-ssh.html["Activez SSH sur les commutateurs de cluster BES-53248"].
+
Si vous utilisez le moniteur d'état du commutateur Ethernet (CSHM) et les fonctionnalités de collecte de journaux, activez SSH sur les commutateurs.

. link:reset-switch-bes-53248.html["Réinitialiser le commutateur aux paramètres d'usine"].
+
Effacez les paramètres du commutateur de cluster BES-53248.


