---
permalink: switch-bes-53248/configure-install-rcf.html 
sidebar: sidebar 
keywords: install rcf,setup rcf 
summary: 'Vous pouvez installer la FCR après la première configuration du commutateur de cluster BES-53248 et après la première application de la ou des nouvelles licences. Si vous mettez à niveau une FCR à partir d"une ancienne version, les fichiers sont fusionnés efficacement et vous effectuez les étapes comme indiqué ici.' 
---
= Installer le fichier RCF (Reference Configuration File)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez installer la FCR après la première configuration du commutateur de cluster BES-53248 et après la première application de la ou des nouvelles licences. Si vous mettez à niveau une FCR à partir d'une version antérieure, vous devez réinitialiser les paramètres du commutateur Broadcom et effectuer une configuration de base pour appliquer à nouveau la FCR. Vous devez effectuer cette opération à chaque fois que vous souhaitez mettre à niveau ou modifier une FCR. Voir ci-dessous https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/Error!_in_configuration_script_file_at_line_number_XX_when_applying_a_new_RCF["Article de la base de connaissances"^] pour plus d'informations.

.Étapes
. Connectez le commutateur de cluster au réseau de gestion.
. Utilisez le `ping` Commande pour vérifier la connectivité au serveur hébergeant EFOS, les licences et le RCF.
+
En cas de problème de connectivité, utilisez un réseau non routé et configurez le port de service à l'aide de l'adresse IP 192.168.x ou 172.19.x. Vous pouvez reconfigurer ultérieurement le port de service à l'adresse IP de gestion de production.

+
Cet exemple vérifie que le commutateur est connecté au serveur à l'adresse IP 172.19.2 :

+
[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. Installer le module RCF sur le commutateur de cluster BES-53248 à l'aide du `copy` commande.
+
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://172.19.2.1/tmp/BES-53248_RCF_v1.6-Cluster-HA.txt nvram:script BES-53248_RCF_v1.6-Cluster-HA.scr*

Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... BES-53248_RCF_v1.6-Cluster-HA.txt
Data Type...................................... Config Script
Destination Filename........................... BES-53248_RCF_v1.6-Cluster-HA.scr

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...

File transfer operation completed successfully.
----
+

NOTE: Selon votre environnement, vous devrez peut-être utiliser une barre oblique double dans le `copy` commande, par exemple : `+copy sftp://172.19.2.1//tmp/BES-53248_RCF_v1.6-Cluster-HA.txt nvram:script BES-53248_RCF_v1.6-Cluster-HA.scr+`.

+

NOTE: Le `.scr` l'extension doit être définie comme faisant partie du nom du fichier avant d'appeler le script. Cette extension est l'extension du système d'exploitation EFOS. Le commutateur valide automatiquement le script lorsqu'il est téléchargé sur le commutateur et la sortie est envoyée vers la console. Vous pouvez également modifier le nom du `.scr` pour l'adapter à l'écran de votre console pour faciliter la lisibilité, par exemple : `+copy sftp://172.19.2.1/tmp/BES-53248_RCF_v1.6-Cluster-HA.txt nvram:script RCF_v1.6-Cluster-HA.scr+`.

+

NOTE: Le nom de fichier ne doit pas inclure les symboles `\/:*?"<>|` la longueur maximale autorisée est de 32 caractères.

. Vérifiez que le script a été téléchargé et enregistré dans le nom de fichier que vous lui avez donné :
+
`script list`

+
[listing, subs="+quotes"]
----
(cs2)# *script list*

Configuration Script Name                  Size(Bytes)  Date of Modification
-----------------------------------------  -----------  --------------------
BES-53248_RCF_v1.6-Cluster-HA.scr        2241         2020 09 30 05:41:00

1 configuration script(s) found.
----
. Appliquez le script au commutateur.
+
`script apply`

+
[listing, subs="+quotes"]
----
(cs2)# *script apply BES-53248_RCF_v1.6-Cluster-HA.scr*

Are you sure you want to apply the configuration script? (y/n) *y*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*
Config file 'startup-config' created successfully .
Configuration Saved!

Configuration script 'BES-53248_RCF_v1.6-Cluster-HA.scr' applied.
----
. Vérifier que les ports ne correspondant à aucune licence supplémentaire une fois la FCR appliquée :
+
`show port all | exclude Detach`

+
[listing, subs="+quotes"]
----
(cs2)# *show port all \| exclude Detach*

                 Admin     Physical     Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode         Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Enable    Auto                    Down   Enable  Enable long
0/2              Enable    Auto                    Down   Enable  Enable long
0/3              Enable    Auto                    Down   Enable  Enable long
0/4              Enable    Auto                    Down   Enable  Enable long
0/5              Enable    Auto                    Down   Enable  Enable long
0/6              Enable    Auto                    Down   Enable  Enable long
0/7              Enable    Auto                    Down   Enable  Enable long
0/8              Enable    Auto                    Down   Enable  Enable long
0/9              Enable    Auto                    Down   Enable  Enable long
0/10             Enable    Auto                    Down   Enable  Enable long
0/11             Enable    Auto                    Down   Enable  Enable long
0/12             Enable    Auto                    Down   Enable  Enable long
0/13             Enable    Auto                    Down   Enable  Enable long
0/14             Enable    Auto                    Down   Enable  Enable long
0/15             Enable    Auto                    Down   Enable  Enable long
0/16             Enable    Auto                    Down   Enable  Enable long
0/49             Enable    40G Full                Down   Enable  Enable long
0/50             Enable    40G Full                Down   Enable  Enable long
0/51             Enable    100G Full               Down   Enable  Enable long
0/52             Enable    100G Full               Down   Enable  Enable long
0/53             Enable    100G Full               Down   Enable  Enable long
0/54             Enable    100G Full               Down   Enable  Enable long
0/55             Enable    100G Full               Down   Enable  Enable long
0/56             Enable    100G Full               Down   Enable  Enable long
----
. Vérifiez sur le commutateur que vos modifications ont été effectuées :
+
`show running-config`

+
[listing, subs="+quotes"]
----
(cs2)# *show running-config*
----
. Enregistrez la configuration en cours d'exécution afin qu'elle devienne la configuration de démarrage lorsque vous redémarrez le commutateur :
+
`write memory`

+
[listing, subs="+quotes"]
----
(cs2)# *write memory*
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
. Redémarrez le commutateur et vérifiez que la configuration en cours d'exécution est correcte :
+
`reload`

+
[listing, subs="+quotes"]
----
(cs2)# *reload*

Are you sure you would like to reset the system? (y/n) *y*

System will now restart!
----

