---
permalink: switch-bes-53248/configure-ssh.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, bes, enable ssh on bes-53248 cluster switches - bes-53248 switches 
summary: 'SSH est une condition requise lors de l"utilisation des fonctions de surveillance de l"état du commutateur de cluster \(CSHM\) et de collecte de journaux. Pour activer SSH sur les commutateurs de cluster BES-53248, vous devez d"abord générer les clés SSH, puis activer SSH.' 
---
= Activez SSH sur les commutateurs de cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous utilisez le moniteur d'état du commutateur Ethernet (CSHM) et les fonctionnalités de collecte de journaux, vous devez générer les clés SSH, puis activer SSH sur les commutateurs du cluster.

.Étapes
. Vérifiez que SSH est désactivé :
+
`show ip ssh`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *show ip ssh*

SSH Configuration

Administrative Mode: .......................... Disabled
SSH Port: ..................................... 22
Protocol Level: ............................... Version 2
SSH Sessions Currently Active: ................ 0
Max SSH Sessions Allowed: ..................... 5
SSH Timeout (mins): ........................... 5
Keys Present: ................................. DSA(1024) RSA(1024) ECDSA(521)
Key Generation In Progress: ................... None
SSH Public Key Authentication Mode: ........... Disabled
SCP server Administrative Mode: ............... Disabled
----
====
+
** Si SSH n’est pas désactivé, désactivez-le comme suit :
+
`no ip ssh server enable`

+
`no ip scp server enable`

+
[NOTE]
====
*** Pour EFOS 3.12 et versions ultérieures, l'accès à la console est requis car les sessions SSH actives sont perdues lorsque SSH est désactivé.
*** Pour EFOS 3.11 et les versions antérieures, les sessions SSH actuelles restent ouvertes après la désactivation du serveur SSH.


====
+

WARNING: Assurez-vous de désactiver SSH avant de modifier les clés, sinon, un avertissement est signalé sur le commutateur.



. En mode configuration, générez les clés SSH :
+
`crypto key generate`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *config*

(switch) (Config)# *crypto key generate rsa*

Do you want to overwrite the existing RSA keys? (y/n): *y*


(switch) (Config)# *crypto key generate dsa*

Do you want to overwrite the existing DSA keys? (y/n): *y*


(switch) (Config)# *crypto key generate ecdsa 521*

Do you want to overwrite the existing ECDSA keys? (y/n): *y*
----
====
. En mode de configuration, définissez l'autorisation AAA pour la collecte des journaux ONTAP :
+
`aaa authorization commands "noCmdAuthList" none`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch) (Config)# *aaa authorization commands "noCmdAuthList" none*
(switch) (Config)# *exit*
----
====
. Réactiver SSH/SCP.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *ip ssh server enable*
(switch)# *ip scp server enable*
(switch)# *ip ssh pubkey-auth*
----
====
. Enregistrez ces modifications dans le fichier startup-config :
+
`write memory`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.
Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. Chiffrez les clés SSH (pour *FIPS-mode uniquement*) :
+

CAUTION: En mode FIPS, les clés doivent être chiffrées avec une phrase secrète pour des raisons de sécurité. En l'absence d'une clé chiffrée, l'application ne démarre pas. Les clés sont créées et chiffrées à l'aide des commandes suivantes :

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch) *configure*
(switch) (Config)# *crypto key encrypt write rsa passphrase _<passphase>_*

The key will be encrypted and saved on NVRAM.
This will result in saving all existing configuration also.
Do you want to continue? (y/n): *y*

Config file 'startup-config' created successfully.

(switch) (Config)# *crypto key encrypt write dsa passphrase _<passphase>_*

The key will be encrypted and saved on NVRAM.
This will result in saving all existing configuration also.
Do you want to continue? (y/n): *y*

Config file 'startup-config' created successfully.

(switch)(Config)# *crypto key encrypt write ecdsa passphrase _<passphase>_*

The key will be encrypted and saved on NVRAM.
This will result in saving all existing configuration also.
Do you want to continue? (y/n): *y*

Config file 'startup-config' created successfully.

(switch) (Config)# *end*
(switch)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.
Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. Redémarrez le commutateur :
+
`reload`

. Vérifiez que SSH est activé :
+
`show ip ssh`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *show ip ssh*

SSH Configuration

Administrative Mode: .......................... Enabled
SSH Port: ..................................... 22
Protocol Level: ............................... Version 2
SSH Sessions Currently Active: ................ 0
Max SSH Sessions Allowed: ..................... 5
SSH Timeout (mins): ........................... 5
Keys Present: ................................. DSA(1024) RSA(1024) ECDSA(521)
Key Generation In Progress: ................... None
SSH Public Key Authentication Mode: ........... Enabled
SCP server Administrative Mode: ............... Enabled
----
====


.Et la suite ?
link:../switch-cshm/config-overview.html["Configurer la surveillance de l'état des commutateurs"].
