---
permalink: switch-bes-53248/configure-new-switch.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure new bes-53248 switch 
summary: Vous pouvez configurer un nouveau commutateur de cluster BES-53248 en suivant les étapes décrites dans ce chapitre. 
---
= Configurez un nouveau commutateur de cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer un nouveau commutateur de cluster BES-53248 en suivant les étapes décrites dans ce chapitre.

L'installation du commutateur de cluster BES-53248 sur les systèmes exécutant ONTAP commence par la configuration d'une adresse IP et d'une configuration permettant au commutateur de communiquer via l'interface de gestion. Vous pouvez alors installer le logiciel Ethernet Fabric OS (EFOS), le fichier RCF (Reference Configuration File) et d'autres licences si nécessaire. Cette procédure est destinée à préparer le commutateur BES-53248 avant l'ajout des contrôleurs. De plus, vous devrez peut-être installer le fichier de configuration requis pour prendre en charge le moniteur de santé du commutateur de cluster (CSHM) pour les commutateurs de cluster BES-53248. Voir link:configure-health-monitor.html["Installation du fichier de configuration CSHM (Cluster Switch Health Monitor)"] pour en savoir plus.

Les exemples de cette procédure utilisent la nomenclature des commutateurs et des nœuds suivante :

* Les noms de commutateurs NetApp sont `cs1` et `cs2`.
* L'exemple utilisé dans cette procédure lance la mise à niveau sur le second commutateur, _cs2._
* Les noms LIF de cluster sont `node1_clus1` et `node1_clus2` pour le noeud 1, et `node2_clus1` et `node2_clus2` pour le noeud 2.
* Le nom IPspace est le Cluster.
* Le `cluster1::>` l'invite indique le nom du cluster.
* les ports de cluster de chaque nœud sont nommés e0a et e0b.
+
Voir la https://hwu.netapp.com/Home/Index["NetApp Hardware Universe"^] pour les ports réels de cluster pris en charge sur votre plateforme.

* Les liaisons interswitch (ISL) prises en charge pour les commutateurs NetApp sont les ports 0/55 et 0/56.
* Les connexions de nœuds prises en charge pour les switchs NetApp sont les ports 0/1 à 0/16 avec une licence par défaut.
* Les exemples de cette procédure utilisent deux nœuds, mais vous pouvez disposer d'un cluster pouvant atteindre 24 nœuds.

