---
permalink: switch-bes-53248/configure-log-collection.html 
sidebar: sidebar 
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation 
summary: 'La fonctionnalité de collecte des journaux du contrôle de l"état du commutateur de cluster est utilisée pour collecter les fichiers journaux relatifs aux commutateurs dans ONTAP. Vous devez vous assurer que vous avez configuré votre environnement à l"aide de l"interface de ligne de commande du commutateur de cluster BES-53248 comme détaillé ici.' 
---
= Activez la fonction de collecte de journaux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser la fonction de collecte de journaux pour collecter des fichiers journaux liés aux commutateurs dans ONTAP.


IMPORTANT: Pour activer la fonction de collecte de journaux, vous devez exécuter ONTAP version 9.12.1 et ultérieure et EFOS 3.8.0.2 et versions ultérieures.

Vérifiez que vous avez configuré votre environnement à l'aide du commutateur de cluster BES-53248 *CLI*.

.Étapes
. Créez un mot de passe pour la fonction de collecte du journal du moniteur d'intégrité du commutateur Ethernet :
`system switch ethernet log setup-password`
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *<return>*
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----
====
. Activez la fonction de collecte des journaux du moniteur d'intégrité du commutateur Ethernet.
+
`system switch ethernet log modify -device _<switch-name>_ -log-request true`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
====
+
Attendez 10 minutes, puis vérifiez que la collecte du journal se termine à l'aide de la commande :

+
`system switch ethernet log show`

+

CAUTION: Si l'une de ces commandes renvoie une erreur ou si la collecte des journaux ne se termine pas, contactez le support NetApp.



.Et la suite ?
Si vous mettez le commutateur à niveau, passez à link:replace-verify.html["Vérifiez la configuration de la mise à niveau"].
