---
permalink: switch-bes-53248/configure-install-initial.html 
sidebar: sidebar 
keywords: switches initial setup,initial setup,efos download 
summary: 'Vous pouvez utiliser cette procédure pour effectuer l"installation initiale du commutateur de cluster BES-53248.' 
---
= Configurez le commutateur du cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Procédez comme suit pour effectuer une configuration initiale du commutateur de cluster BES-53248.

.Avant de commencer
* Le matériel est installé, comme décrit à la section link:install-hardware-bes53248.html["Installer le matériel de fixation"].
* Vous avez passé en revue les points suivants :
+
** link:configure-reqs-bes53248.html["Configuration requise"]
** link:components-bes53248.html["Composants et références"]
** link:required-documentation-bes53248.html["Exigences de documentation"]




.À propos des exemples
Les exemples des procédures de configuration utilisent la nomenclature de commutateur et de nœud suivante :

* Les noms de commutateurs NetApp sont `cs1` et `cs2`. La mise à niveau commence sur le second commutateur, _cs2._
* Les noms LIF de cluster sont `node1_clus1` et `node1_clus2` pour le noeud 1, et `node2_clus1` et `node2_clus2` pour le noeud 2.
* Le nom IPspace est le Cluster.
* Le `cluster1::>` l'invite indique le nom du cluster.
* Les ports de cluster de chaque nœud sont nommés `e0a` et `e0b`. Voir la https://hwu.netapp.com/Home/Index["NetApp Hardware Universe"^] pour les ports réels de cluster pris en charge sur votre plateforme.
* Les liaisons interswitch (ISL) prises en charge pour les commutateurs NetApp sont les ports 0/55 et 0/56.
* Les connexions de nœuds prises en charge pour les switchs NetApp sont les ports 0/1 à 0/16 avec une licence par défaut.
* Les exemples utilisent deux nœuds, mais il peut y avoir jusqu'à 24 nœuds dans un cluster.


.Étapes
. Connectez le port série à un hôte ou à un port série.
. Connectez le port de gestion (le port de clé RJ-45 sur le côté gauche du commutateur) au même réseau que celui où se trouve votre serveur TFTP.
. Sur la console, définissez les paramètres série côté hôte :
+
** 115200 bauds
** 8 bits de données (data bits)
** 1 bit de stop
** parité : aucune
** contrôle de flux : aucun


. Connectez-vous au commutateur en tant que `admin` Et appuyez sur *entrée* lorsque vous êtes invité à saisir un mot de passe. Le nom de commutateur par défaut est *routing*. À l'invite, entrez `enable`. Ceci vous donne accès au mode d’exécution privilégié pour la configuration du commutateur.
+
[listing, subs="+quotes"]
----
User: *admin*
Password:
(Routing)> *enable*
Password:
(Routing)#
----
. Définissez le nom du commutateur sur *cs2*.
+
[listing, subs="+quotes"]
----
(Routing)# *hostname cs2*
(cs2)#
----
. Pour définir une adresse de gestion IPv4 ou IPv6 statique pour le port de service du commutateur :


[role="tabbed-block"]
====
.IPv4
--
Le port de service est défini pour utiliser DHCP par défaut. L'adresse IP, le masque de sous-réseau et l'adresse de passerelle par défaut sont attribués automatiquement.

[listing, subs="+quotes"]
----
(cs2)# *serviceport protocol none*
(cs2)# *network protocol none*
(cs2)# *serviceport ip <ip-address> <netmask> <gateway>*
----
--
.IPv6
--
Le port de service est défini pour utiliser DHCP par défaut. L'adresse IP, le masque de sous-réseau et l'adresse de passerelle par défaut sont attribués automatiquement.

[listing, subs="+quotes"]
----
(cs2)# *serviceport protocol none*
(cs2)# *network protocol none*
(cs2)# *serviceport ipv6 <address>*
(cs2)# *serviceport ipv6 <gateway>*
----
--
====
. [[step7]]Vérifiez les résultats à l'aide de la commande :
+
`show serviceport`

+
[listing, subs="+quotes"]
----
(cs2)# *show serviceport*
Interface Status............................... Up
IP Address..................................... 172.19.2.2
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 172.19.2.254
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe71:123c/64
IPv6 Default Router............................ fe80::20b:45ff:fea9:5dc0
Configured IPv4 Protocol....................... DHCP
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:71:12:3C
----
. Configurez le domaine et le serveur de noms :
+
[source, cli]
----
ip domain name <domain_name>
ip name server <server_name>
----
+
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *ip domain name company.com*
(cs2)(Config)# *ip name server 10.10.99.1 10.10.99.2*
(cs2)(Config)# *exit*
(cs2)#
----
. Configurez le serveur NTP.


[role="tabbed-block"]
====
.EFOS 3.10.0.3 et versions ultérieures
--
Configurez le fuseau horaire et la synchronisation de l'heure (NTP) :

[source, cli]
----
sntp server <server_name>
clock
----
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *ntp server 10.99.99.5*
(cs2)(Config)# *clock timezone -7*
(cs2)(Config)# *exit*
(cs2)#
----
--
.EFOS 3.9.0.2 et versions antérieures
--
Configurer le fuseau horaire et la synchronisation de l'heure (SNTP) :

[source, cli]
----
sntp client mode <client_mode>
sntp server <server_name>
clock
----
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *sntp client mode unicast*
(cs2)(Config)# *sntp server 10.99.99.5*
(cs2)(Config)# *clock timezone -7*
(cs2)(Config)# *exit*
(cs2)#
----
--
====
. [[step10]]configurez l'heure manuellement si vous n'avez pas configuré de serveur NTP à l'étape précédente.


[role="tabbed-block"]
====
.EFOS 3.10.0.3 et versions ultérieures
--
Configurez l'heure manuellement.

`clock`

[listing, subs="+quotes"]
----

(cs2)# *configure*
(cs2)(Config)# *clock summer-time recurring 1 sun mar 02:00 1 sun nov 02:00 offset 60 zone EST*
(cs2)(Config)# *clock timezone -5 zone EST*
(cs2)(Config)# *clock set 07:00:00*
(cs2)(Config)# *clock set 10/20/2023*
(cs2)(Config)# *show clock*

07:00:11 EST(UTC-5:00) Oct 20 2023
No time source

(cs2)(Config)# *exit*
(cs2)#
----
--
.EFOS 3.9.0.2 et versions antérieures
--
Configurez l'heure manuellement.

`clock`

[listing, subs="+quotes"]
----

(cs2)# *configure*
(cs2)(Config)# *no sntp client mode*
(cs2)(Config)# *clock summer-time recurring 1 sun mar 02:00 1 sun nov 02:00 offset 60 zone EST*
(cs2)(Config)# *clock timezone -5 zone EST*
(cs2)(Config)# *clock set 07:00:00*
(cs2)(Config)# *clock set 10/20/2023*
(cs2)(Config)# *show clock*

07:00:11 EST(UTC-5:00) Oct 20 2023
No time source

(cs2)(Config)# *exit*
(cs2)#
----
--
====
. [[step11]]Enregistrez la configuration en cours d'exécution dans la configuration de démarrage :
+
`write memory`

+
[listing, subs="+quotes"]
----
(cs2)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----


.Et la suite ?
link:configure-efos-software.html["Installez le logiciel EFOS"]
