---
permalink: switch-bes-53248/configure-log-collection.html 
sidebar: sidebar 
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation 
summary: 'La fonctionnalité de collecte des journaux du contrôle de l"état du commutateur de cluster est utilisée pour collecter les fichiers journaux relatifs aux commutateurs dans ONTAP. Vous devez vous assurer que vous avez configuré votre environnement à l"aide de l"interface de ligne de commande du commutateur de cluster BES-53248 comme détaillé ici.' 
---
= Activez la fonction de collecte de journaux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez activer la fonction de collecte de journaux, qui est utilisée pour collecter des fichiers journaux liés au commutateur dans ONTAP.

Vérifiez que vous avez configuré votre environnement à l'aide de l'interface de ligne de commande du commutateur de cluster BES-53248.



== Pour ONTAP 9.8 et versions ultérieures

Activez la fonction de collecte des journaux à l'aide des commandes suivantes :

`system switch ethernet log setup-password` et `system switch ethernet log enable-collection`

.Étapes
. Entrez : `system switch ethernet log setup-password`
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *cs2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
====
. Entrez : `system switch ethernet log enable-collection`
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*>
----
====




== Pour les versions ONTAP 9.5P15, 9.6P11, 9.7P8 et versions ultérieures des correctifs

Activez la fonction de collecte des journaux à l'aide des commandes suivantes :

`system cluster-switch log setup-password` et `system cluster-switch log enable-collection`

.Étapes
. Entrez : `system cluster-switch log setup-password`
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system cluster-switch log setup-password*

Enter the switch name: *cs1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system cluster-switch log setup-password*

Enter the switch name: *cs2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
====
. Entrez : `system cluster-switch log enable-collection`
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.
----
====



NOTE: La commande de collecte de journal n'est pas disponible pour le moment. Voir link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1225042["Bug 1225042"^] pour plus d'informations.


CAUTION: Si l'une de ces commandes renvoie une erreur, contactez le support NetApp.

.Et la suite ?
Si vous mettez le commutateur à niveau, passez à link:replace-verify.html["Vérifiez la configuration de la mise à niveau"].
