---
permalink: switch-bes-53248/configure-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,installing EFOS software 
summary: 'Procédez comme suit pour installer le logiciel Ethernet Fabric OS (EFOS) sur le commutateur de cluster BES-53248.' 
---
= Installez le logiciel EFOS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Procédez comme suit pour installer le logiciel Ethernet Fabric OS (EFOS) sur le commutateur de cluster BES-53248.

Le logiciel EFOS inclut un ensemble de fonctions et de protocoles réseau avancés pour le développement de systèmes d'infrastructure Ethernet et IP. Cette architecture logicielle convient à tout périphérique d'organisation réseau utilisant des applications nécessitant une inspection ou une séparation complète des paquets.



== Avant l'installation

.Avant de commencer
* Cette procédure convient uniquement aux nouvelles installations.
* Téléchargez le logiciel Broadcom EFOS correspondant à vos commutateurs de cluster à partir du https://www.broadcom.com/support/bes-switch["Prise en charge des commutateurs Ethernet Broadcom"^] le site.
* Assurez-vous que le link:configure-install-initial.html["Le commutateur de cluster BES-53248 est configuré"].




== Installez le logiciel

Utilisez l'une des méthodes suivantes pour installer le logiciel EFOS :

* <<Méthode 1 : installez EFOS>>. Utilisation dans la plupart des cas.
* <<Méthode 2 : installez EFOS en mode ONIE>>. Utilisez si une version de EFOS est conforme à la norme FIPS et que l'autre version de EFOS n'est pas conforme à la norme FIPS.




=== Méthode 1 : installez EFOS

Procédez comme suit pour installer le logiciel EFOS.

.Étapes
. Connectez-vous au port console série du commutateur ou connectez-vous à SSH.
. Utilisez le `ping` Commande pour vérifier la connectivité au serveur hébergeant EFOS, les licences et le fichier RCF.
+
.Montrer l'exemple
[%collapsible]
====
Cet exemple vérifie que le commutateur est connecté au serveur à l'adresse IP 172.19.2 :

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. Téléchargez le fichier image sur le commutateur.
+
Consultez le tableau suivant pour plus d'informations sur les protocoles de copie pris en charge :

+
|===


| *Protocole* | *Prérequis* 


 a| 
Protocole TFTP (Trivial File Transfer Protocol)
 a| 
Aucune



 a| 
Protocole SFTP (SSH File Transfer Protocol)
 a| 
Votre pack logiciel doit prendre en charge la gestion sécurisée



 a| 
FTP
 a| 
Mot de passe requis



 a| 
XMODEM
 a| 
Aucune



 a| 
YMODEM
 a| 
Aucune



 a| 
ZMODEM
 a| 
Aucune



 a| 
SCP (Secure Copy Protocol)
 a| 
Votre pack logiciel doit prendre en charge la gestion sécurisée



 a| 
HTTP
 a| 
Les transferts de fichiers basés sur l'interface de ligne de commande sont pris en charge sur certaines plates-formes lorsqu'un utilitaire WGET natif est disponible



 a| 
HTTPS
 a| 
Les transferts de fichiers basés sur l'interface de ligne de commande sont pris en charge sur certaines plates-formes lorsqu'un utilitaire WGET natif est disponible

|===
+
La copie du fichier image dans l'image active signifie que lors du redémarrage, cette image établit la version en cours d'exécution de EFOS. L'image précédente reste disponible comme sauvegarde.

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk active*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. Afficher les images de démarrage de la configuration active et de sauvegarde :
+
`show bootvar`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.7.0.4     3.7.0.4           3.10.0.3
----
====
. Redémarrez le commutateur :
+
`reload`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .
Configuration Saved!
System will now restart!
----
====
. Reconnectez-vous et vérifiez la nouvelle version du logiciel EFOS :
+
`show version`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. Terminez l'installation.
Pour reconfigurer le commutateur, procédez comme suit :
+
.. link:configure-licenses.html["Installez les licences"]
.. link:configure-install-rcf.html["Installez le fichier RCF"]
.. link:configure-ssh.html["Activez SSH"]
.. link:CSHM_log_collection.html["Activer la collecte de journaux"]
.. link:CSHM_snmpv3.html["Configurer SNMPv3 pour la surveillance"]


. Répétez les étapes 1 à 7 sur le commutateur partenaire.




=== Méthode 2 : installez EFOS en mode ONIE

Vous pouvez effectuer les étapes suivantes si une version de EFOS est conforme à la norme FIPS et que l'autre version de EFOS n'est pas compatible FIPS. Ces étapes peuvent être utilisées pour installer l'image EFOS 3.7.x.x non conforme à la norme FIPS ou à la norme FIPS à partir d'ONIE si le commutateur ne parvient pas à démarrer.

.Étapes
. Se connecter à une console connectée au port série du commutateur.
. Démarrez le commutateur en mode d'installation ONIE.
+
Au cours du démarrage, sélectionnez ONIE lorsque vous voyez l'invite.

+
.Montrer l'exemple
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
Après avoir sélectionné *ONIE*, le commutateur se charge et vous offre plusieurs choix. Sélectionnez *installer OS*.

+
.Montrer l'exemple
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
Le commutateur démarre en mode d'installation ONIE.

. Arrêtez la détection ONIE et configurez l'interface Ethernet.
+
Lorsque le message suivant s'affiche, appuyez sur *entrée* pour appeler la console ONIE :

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: La détection ONIE se poursuit et les messages sont imprimés sur la console.

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. Configurez l'interface Ethernet du port de gestion du commutateur et ajoutez la route à l'aide de `ifconfig eth0 <ipAddress> netmask <netmask> up` et `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. Vérifiez que le serveur hébergeant le fichier d'installation ONIE est accessible :
+
`ping`

+
.Montrer l'exemple
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. Installez le nouveau logiciel du commutateur :
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.Montrer l'exemple
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
Le logiciel installe puis redémarre le commutateur. Laissez le commutateur redémarrer normalement dans la nouvelle version de EFOS.

. Connectez-vous et vérifiez que le nouveau logiciel du commutateur est installé :
+
`show bootvar`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
 1      3.7.0.4     3.7.0.4    3.7.0.4        3.10.0.3
(cs2) #
----
====
. Terminez l'installation.
Le commutateur redémarre sans aucune configuration appliquée et revient aux paramètres d'usine par défaut. Pour reconfigurer le commutateur, procédez comme suit :
+
.. link:configure-install-initial.html["Configurer le commutateur"]
.. link:configure-licenses.html["Installez les licences"]
.. link:configure-install-rcf.html["Installez le fichier RCF"]
.. link:configure-ssh.html["Activez SSH"]
.. link:CSHM_log_collection.html["Activer la collecte de journaux"]
.. link:CSHM_snmpv3.html["Configurer SNMPv3 pour la surveillance"]


. Répétez les étapes 1 à 8 sur le commutateur partenaire.

