---
permalink: switch-bes-53248/configure-licenses.html 
sidebar: sidebar 
keywords: bes, cluster, switch, base, model, license, 10gbe, 25gbe, 100gbe, port, add, purchasing, purchase, install licenses for bes-53248 cluster switches - bes-53248 switches 
summary: Le modèle de base du commutateur de cluster BES-53248 est sous licence pour 16 ports 10GbE ou 25GbE et deux ports 100GbE.  De nouveaux ports peuvent être ajoutés en achetant des licences supplémentaires. 
---
= Installez les licences pour les commutateurs de cluster BES-53248.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le modèle de base du commutateur de cluster BES-53248 est sous licence pour 16 ports 10GbE ou 25GbE et deux ports 100GbE.  Vous pouvez ajouter de nouveaux ports en achetant des licences supplémentaires.


CAUTION: Pour EFOS 3.12 et versions ultérieures, suivez les étapes d'installation décrites danslink:efos-install-rcf-license-file.html["Installez le fichier de configuration de référence (RCF) et le fichier de licence."] .



== Examiner les licences disponibles

Les licences suivantes sont disponibles pour une utilisation sur le commutateur de cluster BES-53248 :

[cols="1,2,3"]
|===
| Type de licence | Détails de la licence | Version du firmware prise en charge 


 a| 
SW-BES-53248A2-8P-2P
 a| 
Clé de licence Broadcom 8PT-10G25G + 2PT-40G100G, X190005/R
 a| 
EFOS 3.4.4.6 et versions ultérieures



 a| 
SW-BES-53248A2-8P-1025G
 a| 
Clé de licence Broadcom 8 ports 10G25G, X190005/R
 a| 
EFOS 3.4.4.6 et versions ultérieures



 a| 
SW-BES53248A2-6P-40-100G
 a| 
Clé de licence Broadcom 6 ports 40G100G, X190005/R
 a| 
EFOS 3.4.4.6 et versions ultérieures

|===

NOTE: Pour échanger une clé de transaction contre un fichier de clé de licence de port, rendez-vous sur lelink:https://support.broadcom.com/web/csg/license-generation["Portail de licences pour les commutateurs Ethernet compatibles Broadcom"^] page. Consultez l'article de la base de connaissanceslink:https://kb.netapp.com/on-prem/Switches/Broadcom-KBs/How_to_add_Additional_Port_Licensing_for_the_Broadcom_BES_53248_Switch["Comment ajouter des licences de port supplémentaires pour le commutateur Broadcom BES-53248"^] pour plus de détails.



== Licences héritées

Le tableau suivant répertorie les licences héritées qui étaient disponibles pour une utilisation sur le commutateur de cluster BES-53248 :

[cols="1,2,3"]
|===
| Type de licence | Détails de la licence | Version du firmware prise en charge 


 a| 
SW-BES-53248A1-G1-8P-LIC
 a| 
Clé de licence Broadcom 8P 10-25,2P40-100, X190005/R
 a| 
EFOS 3.4.3.3 et versions ultérieures



 a| 
SW-BES-53248A1-G1-16P-LIC
 a| 
Clé de licence Broadcom 16P 10-25,4P40-100, X190005/R
 a| 
EFOS 3.4.3.3 et versions ultérieures



 a| 
SW-BES-53248A1-G1-24P-LIC
 a| 
Clé de licence Broadcom 24P 10-25,6P40-100, X190005/R
 a| 
EFOS 3.4.3.3 et versions ultérieures



 a| 
SW-BES54248-40-100G-LIC
 a| 
Clé de licence Broadcom 6 ports 40G/100G, X190005/R
 a| 
EFOS 3.4.4.6 et versions ultérieures



 a| 
SW-BES53248-8P-10G25G-LIC
 a| 
Clé de licence Broadcom 8 ports 10G/25G, X190005/R
 a| 
EFOS 3.4.4.6 et versions ultérieures



 a| 
SW-BES53248-16P-1025G-LIC
 a| 
Clé de licence Broadcom 16 ports 10G/25G, X190005/R
 a| 
EFOS 3.4.4.6 et versions ultérieures



 a| 
SW-BES53248-24P-1025G-LIC
 a| 
Clé de licence Broadcom 24 ports 10G/25G, X190005/R
 a| 
EFOS 3.4.4.6 et versions ultérieures

|===

NOTE: Aucune licence n'est requise pour la configuration de base.



== Installer les fichiers de licence

Suivez ces étapes pour installer les licences des commutateurs de cluster BES-53248.

.Étapes
. Connectez le commutateur de cluster au réseau de gestion.
. Utilisez le `ping` commande permettant de vérifier la connectivité au serveur hébergeant EFOS, les licences et le fichier RCF.
+
.Afficher un exemple
[%collapsible]
====
Cet exemple vérifie que le commutateur est connecté au serveur à l'adresse IP 172.19.2.1 :

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. Vérifiez l'utilisation actuelle des licences sur Switch CS2 :
+
`show license`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*
Reboot needed.................................. No
Number of active licenses...................... 0

License Index  License Type     Status
-------------- ---------------- -----------

No license file found.
----
====
. Installez le fichier de licence.
+
Répétez cette étape pour charger davantage de licences et utiliser des numéros d'index de clé différents.

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant utilise SFTP pour copier un fichier de licence vers un index de clé 1.

[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1/var/lib/tftpboot/license.dat nvram:license-key 1*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... /var/lib/tftpboot/
Filename....................................... license.dat
Data Type...................................... license

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...


License Key transfer operation completed successfully. System reboot is required.
----
====
. Afficher toutes les informations de licence actuelles et noter l'état de la licence avant le redémarrage du commutateur CS2 :
+
`show license`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. Yes
Number of active licenses...................... 0


License Index  License Type      Status
-------------- ----------------- -------------------------------
1              Port              License valid but not applied
----
====
. Afficher tous les ports sous licence :
+
`show port all | exclude Detach`

+
Les ports des fichiers de licence supplémentaires ne sont affichés qu'après le redémarrage du commutateur.

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable   Auto                  Down   Enable  Enable long
0/2              Disable   Auto                  Down   Enable  Enable long
0/3              Disable   Auto                  Down   Enable  Enable long
0/4              Disable   Auto                  Down   Enable  Enable long
0/5              Disable   Auto                  Down   Enable  Enable long
0/6              Disable   Auto                  Down   Enable  Enable long
0/7              Disable   Auto                  Down   Enable  Enable long
0/8              Disable   Auto                  Down   Enable  Enable long
0/9              Disable   Auto                  Down   Enable  Enable long
0/10             Disable   Auto                  Down   Enable  Enable long
0/11             Disable   Auto                  Down   Enable  Enable long
0/12             Disable   Auto                  Down   Enable  Enable long
0/13             Disable   Auto                  Down   Enable  Enable long
0/14             Disable   Auto                  Down   Enable  Enable long
0/15             Disable   Auto                  Down   Enable  Enable long
0/16             Disable   Auto                  Down   Enable  Enable long
0/55             Disable   Auto                  Down   Enable  Enable long
0/56             Disable   Auto                  Down   Enable  Enable long
----
====
. Redémarrez le commutateur :
+
`reload`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .

Configuration Saved!
Are you sure you would like to reset the system? (y/n) *y*
----
====
. Vérifiez que la nouvelle licence est active et notez qu'elle a bien été appliquée :
+
`show license`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. No
Number of installed licenses................... 1
Total Downlink Ports enabled................... 16
Total Uplink Ports enabled..................... 8

License Index  License Type              Status
-------------- ------------------------- -----------------------------------
1              Port                      License applied
----
====
. Vérifiez que tous les nouveaux ports sont disponibles :
+
`show port all | exclude Detach`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable    Auto                 Down   Enable  Enable long
0/2              Disable    Auto                 Down   Enable  Enable long
0/3              Disable    Auto                 Down   Enable  Enable long
0/4              Disable    Auto                 Down   Enable  Enable long
0/5              Disable    Auto                 Down   Enable  Enable long
0/6              Disable    Auto                 Down   Enable  Enable long
0/7              Disable    Auto                 Down   Enable  Enable long
0/8              Disable    Auto                 Down   Enable  Enable long
0/9              Disable    Auto                 Down   Enable  Enable long
0/10             Disable    Auto                 Down   Enable  Enable long
0/11             Disable    Auto                 Down   Enable  Enable long
0/12             Disable    Auto                 Down   Enable  Enable long
0/13             Disable    Auto                 Down   Enable  Enable long
0/14             Disable    Auto                 Down   Enable  Enable long
0/15             Disable    Auto                 Down   Enable  Enable long
0/16             Disable    Auto                 Down   Enable  Enable long
0/49             Disable   100G Full             Down   Enable  Enable long
0/50             Disable   100G Full             Down   Enable  Enable long
0/51             Disable   100G Full             Down   Enable  Enable long
0/52             Disable   100G Full             Down   Enable  Enable long
0/53             Disable   100G Full             Down   Enable  Enable long
0/54             Disable   100G Full             Down   Enable  Enable long
0/55             Disable   100G Full             Down   Enable  Enable long
0/56             Disable   100G Full             Down   Enable  Enable long
----
====



CAUTION: Lors de l'installation de licences supplémentaires, vous devez configurer manuellement les nouvelles interfaces.  Ne pas réappliquer un RCF à un commutateur de production en fonctionnement.



== Résoudre les problèmes d'installation

En cas de problème lors de l'installation d'une licence, exécutez les commandes de débogage suivantes avant d'exécuter le programme. `copy` commandez à nouveau.

Commandes de débogage à utiliser : `debug transfer` et `debug license`

.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *debug transfer*
Debug transfer output is enabled.
(cs2)# *debug license*
Enabled capability licensing debugging.
----
====
Lorsque vous exécutez le `copy` commande avec le `debug transfer` et `debug license` Les options activées, la sortie du journal est renvoyée.

.Afficher un exemple
[%collapsible]
====
[listing]
----
transfer.c(3083):Transfer process  key or certificate file type = 43
transfer.c(3229):Transfer process  key/certificate cmd = cp /mnt/download//license.dat.1 /mnt/fastpath/ >/dev/null 2>&1CAPABILITY LICENSING :
Fri Sep 11 13:41:32 2020: License file with index 1 added.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Validating hash value 29de5e9a8af3e510f1f16764a13e8273922d3537d3f13c9c3d445c72a180a2e6.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Parsing JSON buffer {
  "license": {
    "header": {
      "version": "1.0",
      "license-key": "964B-2D37-4E52-BA14",
      "serial-number": "QTFCU38290012",
      "model": "BES-53248"
  },
  "description": "",
  "ports": "0+6"
  }
}.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: License data does not contain 'features' field.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Serial number QTFCU38290012 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Model BES-53248 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Feature not found in license file with index = 1.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Applying license file 1.
----
====
Vérifiez la présence des éléments suivants dans la sortie de débogage :

* Vérifiez que le numéro de série correspond : `Serial number QTFCU38290012 matched.`
* Vérifiez que le modèle du commutateur correspond : `Model BES-53248 matched.`
* Vérifiez que l'index de licence spécifié n'a pas été utilisé précédemment.  Lorsqu'un index de licence est déjà utilisé, l'erreur suivante est renvoyée : `License file /mnt/download//license.dat.1 already exists.`
* Une licence de port n'est pas une licence de fonctionnalité.  Par conséquent, la déclaration suivante est attendue : `Feature not found in license file with index = 1.`


Utilisez le `copy` commande pour sauvegarder les licences de port sur le serveur :

[listing, subs="+quotes"]
----
(cs2)# *copy nvram:license-key 1 scp://<UserName>@<IP_address>/saved_license_1.dat*
----

CAUTION: Si vous devez revenir à une version antérieure du logiciel du commutateur (3.4.4.6), les licences sont supprimées.  C'est le comportement attendu.

Vous devez installer une licence antérieure appropriée avant de revenir à une version antérieure du logiciel.



== Activer les ports nouvellement autorisés

Pour activer les ports nouvellement autorisés, vous devez modifier la dernière version du RCF et décommenter les détails du port concerné.

La licence par défaut active les ports 0/1 à 0/16 et 0/55 à 0/56 tandis que les ports nouvellement sous licence seront compris entre les ports 0/17 et 0/54 en fonction du type et du nombre de licences disponibles.  Par exemple, pour activer la licence SW-BES54248-40-100G-LIC, vous devez décommenter la section suivante dans le RCF :

.Afficher un exemple
[%collapsible]
====
[listing]
----
.
.
!
! 2-port or 6-port 40/100GbE node port license block
!
interface 0/49
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/50
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/51
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/52
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/53
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/54
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
.
.
----
====

NOTE: Pour les ports à haut débit entre 0/49 et 0/54 inclus, décommentez chaque port mais ne décommentez qu'une seule ligne *speed* dans le RCF pour chacun de ces ports, soit : *speed 100G full-duplex* ou *speed 40G full-duplex* comme indiqué dans l'exemple.  Pour les ports à faible vitesse compris entre 0/17 et 0/48 inclus, décommentez toute la section à 8 ports lorsqu'une licence appropriée a été activée.

.Quelle est la prochaine étape ?
Une fois les licences installées, vous pouvez link:configure-install-rcf.html["installer le fichier de configuration de référence (RCF)"] ou link:upgrade-rcf.html["mise à niveau du RCF"].
