---
permalink: switch-bes-53248/configure-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,installing EFOS software 
summary: 'Suivez ces étapes pour installer le logiciel Ethernet Fabric OS (EFOS) sur le commutateur de cluster BES-53248.' 
---
= Installez le logiciel EFOS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez ces étapes pour installer le logiciel Ethernet Fabric OS (EFOS) sur le commutateur de cluster BES-53248.

Le logiciel EFOS comprend un ensemble de fonctionnalités et de protocoles réseau avancés pour le développement de systèmes d'infrastructure Ethernet et IP.  Cette architecture logicielle convient à tout dispositif d'organisation de réseau utilisant des applications nécessitant une inspection ou une séparation approfondie des paquets.



== Préparer l'installation

.Avant de commencer
* Cette procédure convient uniquement aux nouvelles installations.
* Téléchargez le logiciel Broadcom EFOS adapté à vos commutateurs de cluster depuis le site web. https://www.broadcom.com/support/bes-switch["Prise en charge des commutateurs Ethernet Broadcom"^] site.
* Assurez-vous quelink:configure-install-initial.html["Le commutateur de cluster BES-53248 est configuré"] .




== Installez le logiciel

Utilisez l'une des méthodes suivantes pour installer le logiciel EFOS :

* <<Méthode 1 : Installer EFOS>>. À utiliser dans la plupart des cas.
* <<Méthode 2 : Installer EFOS en mode ONIE>>. À utiliser si une version d'EFOS est conforme à la norme FIPS et l'autre version d'EFOS ne l'est pas.




=== Méthode 1 : Installer EFOS

Suivez les étapes ci-dessous pour installer le logiciel EFOS.

.Étapes
. Connectez-vous au port console série du commutateur ou connectez-vous via SSH.
. Utilisez le `ping` commande permettant de vérifier la connectivité au serveur hébergeant EFOS, les licences et le fichier RCF.
+
.Afficher un exemple
[%collapsible]
====
Cet exemple vérifie que le commutateur est connecté au serveur à l'adresse IP 172.19.2.1 :

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. Téléchargez le fichier image sur le commutateur.
+
Consultez le tableau suivant pour obtenir des informations sur les protocoles de copie pris en charge :

+
|===


| *Protocole* | *Condition préalable* 


 a| 
Protocole de transfert de fichiers trivial (TFTP)
 a| 
Aucune



 a| 
Protocole de transfert de fichiers SSH (SFTP)
 a| 
Votre progiciel doit prendre en charge la gestion sécurisée



 a| 
FTP
 a| 
Mot de passe requis



 a| 
XMODEM
 a| 
Aucune



 a| 
YMODEM
 a| 
Aucune



 a| 
ZMODEM
 a| 
Aucune



 a| 
Protocole de copie sécurisée (SCP)
 a| 
Votre progiciel doit prendre en charge la gestion sécurisée



 a| 
HTTP
 a| 
Les transferts de fichiers via l'interface de ligne de commande sont pris en charge sur certaines plateformes lorsqu'un utilitaire WGET natif est disponible.



 a| 
HTTPS
 a| 
Les transferts de fichiers via l'interface de ligne de commande sont pris en charge sur certaines plateformes lorsqu'un utilitaire WGET natif est disponible.

|===
+
Copier le fichier image sur l'image active signifie qu'au redémarrage, cette image établira la version EFOS en cours d'exécution.  L'image précédente reste disponible à titre de sauvegarde.

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk active*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. Afficher les images de démarrage pour la configuration active et de secours :
+
`show bootvar`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.7.0.4     3.7.0.4           3.10.0.3
----
====
. Redémarrez le commutateur :
+
`reload`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .
Configuration Saved!
System will now restart!
----
====
. Connectez-vous à nouveau et vérifiez la nouvelle version du logiciel EFOS :
+
`show version`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. Terminez l'installation. Suivez ces quatre étapes pour reconfigurer le commutateur :
+
.. link:configure-licenses.html["Licences d'installation"]
.. link:configure-install-rcf.html["Installez le fichier RCF"]
.. link:configure-ssh.html["Activer SSH"]
.. link:../switch-cshm/config-overview.html["Configurer la surveillance de l'état du commutateur"]


. Répétez les étapes 1 à 7 sur l'autre partenaire.




=== Méthode 2 : Installer EFOS en mode ONIE

Vous pouvez effectuer les étapes suivantes si une version d'EFOS est conforme à la norme FIPS et l'autre version d'EFOS ne l'est pas.  Ces étapes peuvent être utilisées pour installer l'image EFOS 3.7.xx non conforme ou conforme à la norme FIPS à partir d'ONIE si le commutateur ne démarre pas.

.Étapes
. Connectez-vous à une console reliée au port série du commutateur.
. Mettez le commutateur en mode d'installation ONIE.
+
Au démarrage, sélectionnez ONIE lorsque l'invite s'affiche.

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
Après avoir sélectionné *ONIE*, le commutateur se charge et vous présente plusieurs choix.  Sélectionnez *Installer le système d'exploitation*.

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
Le commutateur démarre en mode d'installation ONIE.

. Arrêtez la découverte ONIE et configurez l'interface Ethernet.
+
Lorsque le message suivant apparaît, appuyez sur *Entrée* pour ouvrir la console ONIE :

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: La découverte d'ONIE se poursuit et des messages s'affichent sur la console.

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. Configurez l'interface Ethernet du port de gestion du commutateur et ajoutez la route en utilisant `ifconfig eth0 <ipAddress> netmask <netmask> up` et `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. Vérifiez que le serveur hébergeant le fichier d'installation d'ONIE est accessible :
+
`ping`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. Installez le nouveau logiciel du commutateur :
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
Le logiciel s'installe puis redémarre le commutateur.  Laissez le commutateur redémarrer normalement sur la nouvelle version EFOS.

. Connectez-vous et vérifiez que le nouveau logiciel du commutateur est installé :
+
`show bootvar`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
 1      3.7.0.4     3.7.0.4    3.7.0.4        3.10.0.3
(cs2) #
----
====
. Terminez l'installation. Le commutateur redémarre sans aucune configuration appliquée et se réinitialise aux paramètres d'usine. Suivez ces cinq étapes pour reconfigurer le commutateur :
+
.. link:configure-install-initial.html["Configurer le commutateur"]
.. link:configure-licenses.html["Licences d'installation"]
.. link:configure-install-rcf.html["Installez le fichier RCF"]
.. link:configure-ssh.html["Activer SSH"]
.. link:../switch-cshm/config-overview.html["Configurer la surveillance de l'état du commutateur"]


. Répétez les étapes 1 à 8 sur l'autre partenaire.


.Quelle est la prochaine étape
Après avoir installé le logiciel EFOS, vous pouvez link:configure-licenses.html["installez vos licences"].
