---
permalink: switch-bes-53248/configure-install-initial.html 
sidebar: sidebar 
keywords: switches initial setup,initial setup,efos download 
summary: 'Vous pouvez utiliser cette procédure pour effectuer l"installation initiale du commutateur de cluster BES-53248.' 
---
= Configurer le commutateur de cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez ces étapes pour effectuer une configuration initiale du commutateur de cluster BES-53248.

.Avant de commencer
* Le matériel est installé, comme décrit danslink:install-hardware-bes53248.html["Installez le matériel"] .
* Vous avez consulté les éléments suivants :
+
** link:configure-reqs-bes53248.html["Exigences de configuration"]
** link:components-bes53248.html["Composants et références"]
** link:required-documentation-bes53248.html["Exigences en matière de documentation"]




.À propos des exemples
Les exemples des procédures de configuration utilisent la nomenclature suivante pour les commutateurs et les nœuds :

* Les noms des commutateurs NetApp sont `cs1` et `cs2` .  La mise à niveau commence sur le deuxième commutateur, _cs2._
* Les noms LIF du cluster sont `node1_clus1` et `node1_clus2` pour le nœud 1, et `node2_clus1` et `node2_clus2` pour le nœud 2.
* Le nom de l'espace IP est Cluster.
* Le `cluster1::>` L'invite indique le nom du cluster.
* Les ports du cluster sur chaque nœud sont nommés `e0a` et `e0b` .  Voir le https://hwu.netapp.com/Home/Index["Hardware Universe NetApp"^] pour les ports de cluster réellement pris en charge sur votre plateforme.
* Les liaisons inter-commutateurs (ISL) prises en charge pour les commutateurs NetApp sont les ports 0/55 et 0/56.
* Les connexions de nœuds prises en charge pour les commutateurs NetApp sont les ports 0/1 à 0/16 avec licence par défaut.
* Les exemples utilisent deux nœuds, mais un cluster peut comporter jusqu'à 24 nœuds.


.Étapes
. Connectez le port série à un hôte ou à un port série.
. Connectez le port de gestion (le port RJ-45 en forme de clé situé sur le côté gauche du commutateur) au même réseau que celui où se trouve votre serveur TFTP.
. Sur la console, configurez les paramètres série côté hôte :
+
** 115200 baud
** 8 bits de données
** 1 butée
** parité : aucune
** contrôle de flux : aucun


. Connectez-vous à la console en tant que `admin` et appuyez sur *Entrée* lorsque le mot de passe vous est demandé.  Le nom du commutateur par défaut est *routing*.  À l'invite, saisissez `enable` .  Cela vous donne accès au mode EXEC privilégié pour la configuration du commutateur.
+
[listing, subs="+quotes"]
----
User: *admin*
Password:
(Routing)> *enable*
Password:
(Routing)#
----
. Renommez le commutateur en *cs2*.
+
[listing, subs="+quotes"]
----
(Routing)# *hostname cs2*
(cs2)#
----
. Pour définir une adresse de gestion IPv4 ou IPv6 statique pour le port de service du commutateur :


[role="tabbed-block"]
====
.IPv4
--
Le port de service est configuré par défaut pour utiliser le DHCP.  L'adresse IP, le masque de sous-réseau et l'adresse de passerelle par défaut sont attribués automatiquement.

[listing, subs="+quotes"]
----
(cs2)# *serviceport protocol none*
(cs2)# *network protocol none*
(cs2)# *serviceport ip <ip-address> <netmask> <gateway>*
----
--
.IPv6
--
Le port de service est configuré par défaut pour utiliser le DHCP.  L'adresse IP, le masque de sous-réseau et l'adresse de passerelle par défaut sont attribués automatiquement.

[listing, subs="+quotes"]
----
(cs2)# *serviceport protocol none*
(cs2)# *network protocol none*
(cs2)# *serviceport ipv6 <address>*
(cs2)# *serviceport ipv6 <gateway>*
----
--
====
. [[étape 7]]Vérifiez les résultats à l'aide de la commande :
+
`show serviceport`

+
[listing, subs="+quotes"]
----
(cs2)# *show serviceport*
Interface Status............................... Up
IP Address..................................... 172.19.2.2
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 172.19.2.254
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe71:123c/64
IPv6 Default Router............................ fe80::20b:45ff:fea9:5dc0
Configured IPv4 Protocol....................... DHCP
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:71:12:3C
----
. Configurer le domaine et le serveur de noms :
+
[source, cli]
----
ip domain name <domain_name>
ip name server <server_name>
----
+
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *ip domain name company.com*
(cs2)(Config)# *ip name server 10.10.99.1 10.10.99.2*
(cs2)(Config)# *exit*
(cs2)#
----
. Configurer le serveur NTP.


[role="tabbed-block"]
====
.EFOS 3.10.0.3 et versions ultérieures
--
Configurer le fuseau horaire et la synchronisation de l'heure (NTP) :

[source, cli]
----
sntp server <server_name>
clock
----
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *ntp server 10.99.99.5*
(cs2)(Config)# *clock timezone -7*
(cs2)(Config)# *exit*
(cs2)#
----
--
.EFOS 3.9.0.2 et versions antérieures
--
Configurer le fuseau horaire et la synchronisation de l'heure (SNTP) :

[source, cli]
----
sntp client mode <client_mode>
sntp server <server_name>
clock
----
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *sntp client mode unicast*
(cs2)(Config)# *sntp server 10.99.99.5*
(cs2)(Config)# *clock timezone -7*
(cs2)(Config)# *exit*
(cs2)#
----
--
====
. [[étape 10]]Configurez l'heure manuellement si vous n'avez pas configuré de serveur NTP à l'étape précédente.


[role="tabbed-block"]
====
.EFOS 3.10.0.3 et versions ultérieures
--
Configurez l'heure manuellement.

`clock`

[listing, subs="+quotes"]
----

(cs2)# *configure*
(cs2)(Config)# *clock summer-time recurring 1 sun mar 02:00 1 sun nov 02:00 offset 60 zone EST*
(cs2)(Config)# *clock timezone -5 zone EST*
(cs2)(Config)# *clock set 07:00:00*
(cs2)(Config)# *clock set 10/20/2023*
(cs2)(Config)# *show clock*

07:00:11 EST(UTC-5:00) Oct 20 2023
No time source

(cs2)(Config)# *exit*
(cs2)#
----
--
.EFOS 3.9.0.2 et versions antérieures
--
Configurez l'heure manuellement.

`clock`

[listing, subs="+quotes"]
----

(cs2)# *configure*
(cs2)(Config)# *no sntp client mode*
(cs2)(Config)# *clock summer-time recurring 1 sun mar 02:00 1 sun nov 02:00 offset 60 zone EST*
(cs2)(Config)# *clock timezone -5 zone EST*
(cs2)(Config)# *clock set 07:00:00*
(cs2)(Config)# *clock set 10/20/2023*
(cs2)(Config)# *show clock*

07:00:11 EST(UTC-5:00) Oct 20 2023
No time source

(cs2)(Config)# *exit*
(cs2)#
----
--
====
. [[étape 11]]Enregistrez la configuration en cours dans la configuration de démarrage :
+
`write memory`

+
[listing, subs="+quotes"]
----
(cs2)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----


.Quelle est la prochaine étape ?
Une fois vos commutateurs configurés, vous pouvez link:configure-efos-software.html["installer le logiciel EFOS"].
