---
permalink: switch-bes-53248/configure-software-overview-bes53248.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure new bes-53248 switch 
summary: Passez en revue la présentation du logiciel. 
---
= Workflow d'installation du logiciel pour les commutateurs BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour installer et configurer initialement le logiciel pour un commutateur de cluster BES-53248, procédez comme suit :

. link:configure-efos-software.html["Installez le logiciel EFOS"].
+
Téléchargez et installez le logiciel Ethernet Fabric OS (EFOS) sur le commutateur de cluster BES-53248.

. link:configure-licenses.html["Installez les licences pour les commutateurs de cluster BES-53248"].
+
Vous pouvez également ajouter de nouveaux ports en achetant et en installant des licences supplémentaires. Le modèle de base de switchs est conçu pour 16 ports 10 GbE ou 25 GbE et 2 ports 100 GbE.

. link:configure-install-rcf.html["Installer le fichier RCF (Reference Configuration File)"].
+
Installez le FCR sur le commutateur de cluster BES-53248, puis vérifiez les ports pour obtenir une licence supplémentaire après l'application du FCR.

. link:configure-ssh.html["Activez SSH sur les commutateurs de cluster BES-53248"].
+
Si vous utilisez les fonctions CSHM (Cluster Switch Health Monitor) et de collecte de journaux, activez SSH sur les commutateurs.

. link:CSHM_log_collection.html["Activez la fonction de collecte de journaux"].
+
Utilisez les fonctions de collecte de journaux pour collecter des fichiers journaux liés au commutateur dans ONTAP.

. link:CSHM_snmpv3.html["Configurer SNMPv3 pour la surveillance"].
+
Si vous utilisez la fonction CSHM (Cluster Switch Health Monitor), configurez SNMPv3, qui prend en charge la surveillance de l'état du commutateur Ethernet (CSHM).


