---
permalink: switch-bes-53248/CSHM_snmpv3.html 
sidebar: sidebar 
keywords: SNMP,SNMPv3,SNMPv3 setup,BES-53248 Broadcom setup,BES-3248 switches configuration,EFOS 
summary: 'SNMPv3 peut être utilisé avec le moniteur d"état du commutateur Ethernet (CSHM).' 
---
= Configurer SNMPv3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez cette procédure pour configurer SNMPv3, qui prend en charge la surveillance de l'état du commutateur Ethernet (CSHM).

.Description de la tâche
Les commandes suivantes permettent de configurer un nom d'utilisateur SNMPv3 sur les commutateurs Broadcom BES-53248 :

* Pour *pas d'authentification* :
`net add snmp-server username _SNMPv3_USER_ auth-none`
* Pour l'authentification *MD5/SHA* :
`net add snmp-server username _SNMPv3_USER_ [auth-md5|auth-sha] _AUTH-PASSWORD_`
* Pour l'authentification *MD5/SHA avec cryptage AES/DES* :
`net add snmp-server username _SNMPv3_USER_ [auth-md5|auth-sha] _AUTH-PASSWORD_ [encrypt-aes|encrypt-des] _PRIV-PASSWORD_`


La commande suivante configure un nom d'utilisateur SNMPv3 côté ONTAP :
`cluster1::*> security login create -user-or-group-name _SNMPv3_USER_ -application snmp -authentication-method usm -remote-switch-ipaddress _ADDRESS_`

La commande suivante établit le nom d'utilisateur SNMPv3 avec CSHM :
`cluster1::*> system switch ethernet modify -device _DEVICE_ -snmp-version SNMPv3 -community-or-username _SNMPv3_USER_`

.Étapes
. Configurez l'utilisateur SNMPv3 sur le commutateur pour utiliser l'authentification et le cryptage :
+
`net show snmp status`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(sw1)(Config)# *snmp-server user <username> network-admin auth-md5 <password> priv-aes128 <password>*

(cs1)(Config)# *show snmp user snmp*

     Name            Group Name      Auth Priv
                                     Meth Meth    Remote Engine ID
----------------- ------------------ ---- ------ -------------------------
<username>        network-admin      MD5  AES128 8000113d03d8c497710bee
----
====
. Configurez l'utilisateur SNMPv3 sur le côté ONTAP :
+
`security login create -user-or-group-name <username> -application snmp -authentication-method usm -remote-switch-ipaddress 10.231.80.212`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *security login create -user-or-group-name <username> -application snmp -authentication-method usm -remote-switch-ipaddress 10.231.80.212*

Enter the authoritative entity's EngineID [remote EngineID]:

Which authentication protocol do you want to choose (none, md5, sha, sha2-256)
[none]: *md5*

Enter the authentication protocol password (minimum 8 characters long):

Enter the authentication protocol password again:

Which privacy protocol do you want to choose (none, des, aes128) [none]: *aes128*

Enter privacy protocol password (minimum 8 characters long):
Enter privacy protocol password again:
----
====
. Configurez CSHM pour qu'il surveille avec le nouvel utilisateur SNMPv3 :
+
`system switch ethernet show-all -device "sw1" -instance`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show-all -device "sw1 (b8:59:9f:09:7c:22)" -instance*

                                   Device Name: sw1
                                    IP Address: 10.228.136.24
                                  SNMP Version: SNMPv2c
                                 Is Discovered: true
DEPRECATED-Community String or SNMPv3 Username: -
           Community String or SNMPv3 Username: cshm1!
                                  Model Number: BES-53248
                                Switch Network: cluster-network
                              Software Version: 3.9.0.2
                     Reason For Not Monitoring: None  *<---- should display this if SNMP settings are valid*
                      Source Of Switch Version: CDP/ISDP
                                Is Monitored ?: true
                   Serial Number of the Device: QTFCU3826001C
                                   RCF Version: v1.8X2 for Cluster/HA/RDMA

cluster1::*>
cluster1::*> *system switch ethernet modify -device "sw1" -snmp-version SNMPv3 -community-or-username <username>*
----
====
. Vérifiez que le numéro de série à interroger avec l'utilisateur SNMPv3 nouvellement créé est le même que celui décrit à l'étape précédente après la fin de la période d'interrogation CSHM.
+
`system switch ethernet polling-interval show`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet polling-interval show*
         Polling Interval (in minutes): 5

cluster1::*> *system switch ethernet show-all -device "sw1" -instance*
                                   Device Name: sw1
                                    IP Address: 10.228.136.24
                                  SNMP Version: SNMPv3
                                 Is Discovered: true
DEPRECATED-Community String or SNMPv3 Username: -
           Community String or SNMPv3 Username: <username>
                                  Model Number: BES-53248
                                Switch Network: cluster-network
                              Software Version: 3.9.0.2
                     Reason For Not Monitoring: None  *<---- should display this if SNMP settings are valid*
                      Source Of Switch Version: CDP/ISDP
                                Is Monitored ?: true
                   Serial Number of the Device: QTFCU3826001C
                                   RCF Version: v1.8X2 for Cluster/HA/RDMA
----
====

