---
permalink: switch-bes-53248/index.html 
sidebar: sidebar 
keywords: broadcom, support, bes, cluster, switch, broadcam-supported bes-53248 cluster switches 
summary: 'Pour l"installation et la maintenance du commutateur BES-53248, vérifiez la prise en charge du système d"exploitation, les références, les exigences de configuration et les exigences de documentation.' 
---
= Présentation et configuration requise : commutateurs BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour l'installation et la maintenance du commutateur BES-53248, vérifiez la prise en charge du système d'exploitation, les références, les exigences de configuration et les exigences de documentation.



== Systèmes d'exploitation pris en charge

Le commutateur BES-53248 prend en charge les éléments suivants :

* *Micrologiciel EFOS version 3.4.4.6 et ultérieure*. Le commutateur BES-53248 s'exécute sur un système d'exploitation intégré Broadcom appelé Ethernet Fabric OS (EFOS). La prise en charge des ports de cluster 40/100 GbE commence par la version 3.4.4.6 du firmware EFOS et les versions ultérieures.
* *ONTAP 9.5P8 et ultérieure*. Les commutateurs de cluster BES-53248 pris en charge par Broadcom sont conçus pour fonctionner dans des clusters de tailles allant de deux à 24 nœuds dans ONTAP 9.5P8 et versions ultérieures.




== Références des composants du commutateur

Le tableau suivant répertorie le numéro de référence et la description des composants du commutateur de cluster BES-53248, y compris le kit de rails de montage en rack, les ventilateurs et les alimentations.

[cols="1,2"]
|===
| Numéro de référence | Description 


 a| 
X190005
 a| 
BES-53248, CLSW, 16Pt10/25 Gb, PTSX, BRDCM SUPP (PTSX = échappement côté port)



 a| 
X190005R
 a| 
BES-53248, CLSW, 16Pt10/25 Gb, PSIN, SUPPLÉMENT BRDCM (PSIN = admission côté port)



 a| 
X-RAIL-4POST-190005
 a| 
Kit de rails de montage sur rack Ozeki 4 montants 19"



 a| 
X-FAN-190005-R
 a| 
Ventilateur, côté orifice d'admission X190005



 a| 
X-FAN-190005-F
 a| 
Ventilateur, côté orifice d'échappement X190005



 a| 
X-PSU-190005-R
 a| 
Alimentation, prise côté orifice X190005

Air d'admission côté orifice (air inversé) : l'air frais pénètre dans le châssis par l'extrémité de l'orifice dans l'allée froide et s'échappe par les modules de ventilateur et d'alimentation dans l'allée chaude.



 a| 
X-PSU-190005-F
 a| 
Alimentation, côté orifice d'échappement X190005

Flux d'air d'échappement côté port (air standard) : l'air frais pénètre dans le châssis par le ventilateur et les modules d'alimentation dans l'allée froide et s'échappe par l'extrémité du port du châssis dans l'allée chaude. La couleur bleue indique le débit d'air d'échappement côté port. Il s'agit de l'option la plus courante.

|===


== Configuration requise

Pour configurer votre cluster, vous devez disposer du nombre et du type appropriés de câbles et de connecteurs de câbles pour les commutateurs de cluster. Selon le type de commutateur de cluster que vous configurez au départ, vous devez vous connecter au port console des commutateurs avec le câble de console inclus et vous devez disposer d'informations réseau spécifiques.

.Affectations des ports des commutateurs de cluster
Vous pouvez utiliser le tableau des attributions de ports de commutateur de cluster BES-53248 pris en charge par Broadcom pour configurer votre cluster.

[cols="1,2"]
|===
| Commutateurs | Utilisation des ports 


 a| 
01-16
 a| 
Nœuds de cluster 10 GbE avec port, configuration de base



 a| 
17-48
 a| 
Nœuds de cluster 10 GbE avec licences



 a| 
49-54
 a| 
Des nœuds de port de cluster 100 GbE, avec des licences, ajoutés de droite à gauche



 a| 
55-56
 a| 
Ports ISL (Inter-Switch Link) de cluster 100 GbE, configuration de base

|===
.Contrainte de vitesse du groupe de ports
Sur les switchs de cluster BES-53248, les ports 48 10 GbE (SFP28/SFP+) sont combinés en groupes à 12 ports 4-ports comme suit : ports 1-4, 5-8, 9-12, 13-16, 17-20, 21-24, 25-28, 29-32, 33-36, 37-40, 41-44 et 45-48.

La vitesse des ports SFP28/SFP+ doit être identique (10 GbE ou 25 GbE) sur tous les ports du groupe à 4 ports.



== Exigences de documentation

Vous avez besoin de documentation spécifique sur le commutateur et le contrôleur pour configurer le commutateur de cluster BES-53248 et le cluster ONTAP.



=== Documentation Broadcom

Pour configurer le commutateur de cluster BES-53248, vous devez disposer des documents suivants sur le site de support Broadcom : https://www.broadcom.com/support/bes-switch["Gamme de commutateurs Ethernet Broadcom"^]

[cols="1,2"]
|===
| Titre du document | Description 


 a| 
_EFOS Guide de l'administrateur v3.4.3_
 a| 
Fournit des exemples d'utilisation du commutateur BES-53248 dans un réseau standard.



 a| 
_EFOS CLI Command Reference v3.4.3_
 a| 
Le décrit les commandes de l'interface de ligne de commande (CLI) que vous utilisez pour afficher et configurer le logiciel BES-53248.



 a| 
_EFOS Guide de démarrage v3.4.3_
 a| 
Le fournit des informations détaillées sur le commutateur BES-53248.



 a| 
_EFOS SNMP Reference Guide v3.4.3_
 a| 
Fournit des exemples d'utilisation du commutateur BES-53248 dans un réseau standard.



 a| 
_EFOS Scaling Paramètres et valeurs v3.4.3_
 a| 
Le décrit les paramètres de mise à l'échelle par défaut avec lesquels le logiciel EFOS est fourni et validé sur les plateformes prises en charge.



 a| 
_EFOS spécifications fonctionnelles v3.4.3_
 a| 
Le décrit les spécifications du logiciel EFOS sur les plates-formes prises en charge.



 a| 
_EFOS Notes de mise à jour v3.4.3_
 a| 
Fournit des informations spécifiques à la version du logiciel BES-53248.



 a| 
_Matrice de compatibilité réseau et réseau de gestion du cluster_
 a| 
Fournit des informations sur la compatibilité réseau. La matrice est disponible sur le site de téléchargement du commutateur BES-53248 à l'adresse https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Commutateurs de cluster Broadcom"^].

|===


=== Documentation sur les systèmes ONTAP et articles de la base de connaissances

Pour configurer un système ONTAP, vous devez disposer des documents suivants sur le site de support NetApp à l'adresse http://mysupport.netapp.com/["mysupport.netapp.com"^] Ou le site de la base de connaissances à l'adresse https://kb.netapp.com/["kb.netapp.com"^].

[cols="1,2"]
|===
| Nom | Description 


 a| 
https://hwu.netapp.com/Home/Index["NetApp Hardware Universe"^]
 a| 
Décrit les exigences relatives à l'alimentation et au site du matériel NetApp, notamment les armoires système, et fournit des informations sur les connecteurs et les options de câbles pertinents à utiliser avec les références correspondantes.



 a| 
Instructions d'installation et de configuration spécifiques au contrôleur_
 a| 
Décrit l'installation du matériel NetApp.



 a| 
ONTAP 9
 a| 
Fournit des informations détaillées sur tous les aspects de la version ONTAP 9.



 a| 
_Comment ajouter une licence de port supplémentaire pour le commutateur BES-53248 pris en charge par Broadcom_
 a| 
Fournit des informations détaillées sur l'ajout de licences de port. Accédez au https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_add_Additional_Port_Licensing_for_the_Broadcom-Supported_BES-53248_Switch["Article de la base de connaissances"^].

|===