---
permalink: switch-bes-53248/migrate-cn1610.html 
sidebar: sidebar 
keywords: CN1610,CN1610 replacing, migrate from CN1610 
summary: 'Pour remplacer les commutateurs de cluster CN1610 existants d"un cluster par des commutateurs de cluster BES-53248 pris en charge par Broadcom, vous devez effectuer une séquence de tâches spécifique.' 
---
= Comment migrer les commutateurs de cluster CN1610 vers les commutateurs de cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour remplacer les commutateurs de cluster CN1610 existants d'un cluster par des commutateurs de cluster BES-53248 pris en charge par Broadcom, vous devez effectuer une séquence de tâches spécifique.

Les exemples de cette procédure utilisent deux nœuds, chacun déployant deux ports d'interconnexion de cluster 10 GbE : `e0a` et `e0b`.

Les exemples de cette procédure utilisent la nomenclature des commutateurs et des nœuds suivante :

* Les sorties de la commande peuvent varier en fonction des différentes versions du logiciel ONTAP.
* Les commutateurs CN1610 à remplacer sont `CL1` et `CL2`.
* Les commutateurs BES-53248 qui permettent de remplacer les commutateurs CN1610 sont `cs1` et `cs2`.
* Les nœuds sont `node1` et `node2`.
* Le commutateur CL2 est d'abord remplacé par cs2, suivi de CL1 par cs1.
* Les commutateurs BES-53248 sont préchargés avec les versions supportées des fichiers RCF (Reference Configuration File) et Ethernet Fabric OS (EFOS) avec des câbles ISL connectés aux ports 55 et 56.
* Les noms LIF de cluster sont `node1_clus1` et `node1_clus2` pour le noeud 1, et `node2_clus1` et `node2_clus2` pour le noeud 2.


Cette procédure couvre le scénario suivant :

* Le cluster commence avec deux nœuds connectés à deux commutateurs de cluster CN1610.
* Le commutateur CN1610 CL2 est remplacé par le commutateur BES-53248 cs2 :
+
** Déconnectez les câbles de tous les ports du cluster de tous les nœuds connectés à CL2, puis utilisez les câbles pris en charge pour reconnecter les ports au nouveau commutateur cs2 du cluster.
** Déconnectez les câbles entre les ports ISL CL1 et CL2, puis reconnectez les ports de CL1 à cs2 à l'aide des câbles pris en charge.


* Le commutateur CN1610 CL1 est remplacé par le commutateur BES-53248 cs1 :
+
** Déconnectez les câbles de tous les ports du cluster de tous les nœuds connectés à CL1, puis utilisez les câbles pris en charge pour reconnecter les ports au nouveau commutateur cs1 du cluster.
** Déconnectez les câbles entre les ports ISL CL1 et cs2, puis reconnectez les ports de cs1 à cs2 à l'aide de câbles pris en charge.




.Étapes
. Si AutoSupport est activé sur ce cluster, supprimez la création automatique de dossiers en invoquant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
où x représente la durée de la fenêtre de maintenance en heures.

+

NOTE: Le message AutoSupport informe le support technique de cette tâche de maintenance de sorte que la création automatique de dossier soit supprimée lors de la fenêtre de maintenance.

+
La commande suivante supprime la création automatique de dossiers pendant deux heures :

+
[listing]
----
cluster1::*> system node autosupport invoke -node \* -type all -message MAINT=2h
----
. Définissez le niveau de privilège sur avancé, en entrant *y* lorsque vous êtes invité à continuer :
+
`set -privilege advanced`

+
L'invite avancée (*>) apparaît.

. Vérifiez que la fonction de restauration automatique est activée sur l'ensemble des LIFs du cluster :
+
`network interface show -vserver Cluster -fields auto-revert`

+
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
----
. Afficher des informations sur les périphériques de votre configuration :
+
`network device-discovery show -protocol cdp`

+
L'exemple suivant montre combien d'interfaces d'interconnexion de cluster ont été configurées dans chaque nœud pour chaque commutateur d'interconnexion de cluster :

+
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    CL2                       0/2               CN1610
            e0b    CL1                       0/2               CN1610
node1      /cdp
            e0a    CL2                       0/1               CN1610
            e0b    CL1                       0/1               CN1610
----
. Détermination du statut administratif ou opérationnel pour chaque interface de cluster
+
.. Afficher les attributs des ports réseau du cluster :
+
`network port show -ipspace Cluster`

+
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
.. Afficher des informations sur les interfaces logiques :
+
`network interface show -vserver Cluster`

+
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
----


. Vérifiez que les licences de port, RCF et image EFOS appropriées sont installées sur les nouveaux commutateurs BES-53248 si nécessaire. Vous pouvez également personnaliser vos sites selon vos besoins, comme les utilisateurs, les mots de passe, les adresses réseau, etc.
. Exécutez une commande ping sur les interfaces de cluster distantes :
+
`cluster ping-cluster -node node-name`

+
L'exemple suivant montre comment exécuter un commande ping sur les interfaces de cluster distantes :

+
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*

Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69  node1     e0a
Cluster node1_clus2 169.254.49.125  node1     e0b
Cluster node2_clus1 169.254.47.194  node2     e0a
Cluster node2_clus2 169.254.19.183  node2     e0b

Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)

Detected 9000 byte MTU on 4 path(s):
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)

RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
. Arrêter les ports ISL 13 à 16 sur le commutateur CN1610 actif CL1 :
+
`shutdown`

+
L'exemple suivant montre comment arrêter les ports ISL 13 à 16 sur le commutateur CN1610 CL1 :

+
[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface 0/13-0/16*
(CL1)(Interface 0/13-0/16)# *shutdown*
(CL1)(Interface 0/13-0/16)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
. Construire un ISL temporaire entre CN1610 CL1 et le nouveau BES-53248 cs2. L'ISL ne sera défini que sur cs2 car l'ISL existant sur CL1 peut être réutilisé.
+
L'exemple suivant crée un ISL temporaire sur cs2 (ports 13-16) pour être connecté à l'ISL existant sur CL1 (ports 13-16) :

+
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2) (Config)# *port-channel name 1/2 temp-isl-cn1610*
(cs2) (Config)# *interface 0/13-0/16*
(cs2) (Interface 0/13-0/16)# *no spanning-tree edgeport*
(cs2) (Interface 0/13-0/16)# *addport 1/2*
(cs2) (Interface 0/13-0/16)# *exit*
(cs2) (Config)# *interface lag 2*
(cs2) (Interface lag 2)# *mtu 9216*
(cs2) (Interface lag 2)# *port-channel load-balance 7*
(cs2) (Config)# *exit*

(cs2)# *show port-channel 1/2*
Local Interface................................ 1/2
Channel Name................................... temp-isl-cn1610
Link State..................................... Down
Admin Mode..................................... Enabled
Type........................................... Static
Port-channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr     Device/        Port      Port
Ports   Timeout        Speed     Active
------- -------------- --------- -------
0/13    actor/long     10G Full  False
        partner/long
0/14    actor/long     10G Full  False
        partner/long
0/15    actor/long     10G Full  False
        partner/long
0/16    actor/long     10G Full  False
        partner/long
----
. Sur tous les nœuds, retirez les câbles reliés au commutateur CN1610 CL2.
+
Vous devez ensuite reconnecter les ports déconnectés de tous les nœuds au nouveau commutateur BES-53248 cs2. Reportez-vous à la https://hwu.netapp.com/Home/Index["_NetApp Hardware Universe_"^] pour les options de câblage approuvées.

. Retirez quatre câbles ISL des ports 13 à 16 du commutateur CN1610 CL2.
+
Vous devez connecter les ports de câblage approuvés appropriés reliant le port 0/13 à 0/16 du nouveau commutateur BES-53248 cs2 aux ports 13 à 16 du commutateur CN1610 existant CL1.

. Intégrez des liens ISL 13 à 16 sur le commutateur CN1610 actif CL1.
+
L'exemple suivant illustre le processus d'affichage des ports ISL 13 à 16 sur CL1 :

+
[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface 0/13-0/16*
(CL1)(Interface 0/13-0/16,3/1)# *no shutdown*
(CL1)(Interface 0/13-0/16,3/1)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
. Vérifiez que les liens ISL sont *UP* sur le commutateur CN1610 CL1 :
+
`show port-channel`

+
Le `Link State` doit être de `Up`, `Type` doit être de `Static`, et `Port Active` doit être de `True` pour les ports 0/13 à 0/16 :

+
[listing, subs="+quotes"]
----
(CL2)# *show port-channel 3/1*
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7


(Enhanced hashing mode)
Mbr      Device/        Port        Port
Ports    Timeout        Speed       Active
-------- -------------- ----------- --------
0/13     actor/long     10 Gb Full  True
         partner/long
0/14     actor/long     10 Gb Full  True
         partner/long
0/15     actor/long     10 Gb Full  True
         partner/long
0/16     actor/long     10 Gb Full  True
         partner/long
----
. Vérifiez que les ports ISL sont sous tension sur le commutateur BES-53248 :
+
`show port-channel`

+
[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/2*

Local Interface................................ 1/2
Channel Name................................... temp-isl-cn1610
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Port-channel Min-links......................... 1
Load Balance Option............................ 7

(Src/Dest MAC, VLAN, EType, incoming port)

Mbr     Device/       Port      Port
Ports   Timeout       Speed     Active
------- ------------- --------- -------
0/13    actor/long    10G Full  True
        partner/long
0/14    actor/long    10G Full  True
        partner/long
0/15    actor/long    10G Full  True
        partner/long
0/16    actor/long    10G Full  True
        partner/long
----
. Vérifier que tous les ports d'interconnexion de cluster sont restaurés sur leurs ports de base :
+
`network interface show -vserver Cluster`

+
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2         e0b     true
----
. Vérifier que tous les ports du cluster sont connectés :
+
`network port show -ipspace Cluster`

+
L'exemple suivant montre le résultat de la commande précédente, en vérifiant que toutes les interconnexions de cluster sont disponibles :

+
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
. Exécutez une commande ping sur les interfaces de cluster distantes :
+
`cluster ping-cluster -node _node-name_`

+
L'exemple suivant montre comment exécuter un commande ping sur les interfaces de cluster distantes :

+
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69  node1     e0a
Cluster node1_clus2 169.254.49.125  node1     e0b
Cluster node2_clus1 169.254.47.194  node2     e0a
Cluster node2_clus2 169.254.19.183  node2     eob
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
. Sur tous les nœuds, retirez les câbles reliés au commutateur CN1610 CL1.
+
Vous devez ensuite reconnecter les ports déconnectés de tous les nœuds au nouveau commutateur BES-53248 cs1. Reportez-vous à la https://hwu.netapp.com/Home/Index["_NetApp Hardware Universe_"^] pour les options de câblage approuvées.

. Retirer quatre câbles ISL des ports 13 à 16 du commutateur BES-53248 cs2.
. Retirez le canal de port temporaire 2 du cs2.
+
L'exemple suivant supprime le canal de port 2 et copie le fichier de configuration d'exécution dans le fichier de configuration de démarrage :

+
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2) (Config)# *deleteport 1/2 all*
(cs2) (Config)# *interface 0/13-0/16*
(cs2) (Interface 0/13-0/16)# *spanning-tree edgeport*
​​​​​(cs2) (Interface 0/13-0/16)# *exit*
(cs2) (Config)# *exit*
(cs2)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully .
----
. Vérifiez l'état du port du nœud de cluster :
+
`network port show -ipspace Cluster`

+
L'exemple suivant vérifie que tous les ports d'interconnexion de cluster des nœuds 1 et 2 sont `up`:

+
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
. Vérifiez que l'interface est à présent à domicile :
+
`network interface show -vserver Cluster`

+
L'exemple suivant montre le statut des interfaces d'interconnexion de cluster sont `up` et `Is home` pour les nœuds 1 et 2 :

+
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current   Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node      Port    Home
----------- ------------ ---------- ------------------ --------- ------- ------
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1     e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1     e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2     e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2     e0b     true
----
. Exécutez une commande ping sur les interfaces du cluster distant, puis effectuez une procédure à distance. Contrôlez le serveur d'appels :
+
`cluster ping-cluster -node _node-name_`

+
L'exemple suivant montre comment exécuter un commande ping sur les interfaces de cluster distantes :

+
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69  node1     e0a
Cluster node1_clus2 169.254.49.125  node1     e0b
Cluster node2_clus1 169.254.47.194  node2     e0a
Cluster node2_clus2 169.254.19.183  node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
. Affichez les informations relatives aux périphériques de votre configuration :
+
`network device-discovery show -protocol cdp`

+
Les exemples suivants montrent que node1 et node2 ont été migrés de CN1610 CL2 et CL1 vers BES-53248 cs2 et cs1 :

+
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /cdp
            e0a    cs2                       0/1               BES-53248
            e0b    cs1                       0/1               BES-53248
node2      /cdp
            e0a    cs2                       0/2               BES-53248
            e0b    cs1                       0/2               BES-53248
----
. Supprimez les commutateurs CN1610 remplacés s'ils ne sont pas automatiquement supprimés :
+
`system cluster-switch delete -device _device-name_`

+
L'exemple suivant montre comment supprimer les commutateurs CN1610 :

+
[listing, subs="+quotes"]
----
cluster::*> *system cluster-switch delete –device CL2*
cluster::*> *system cluster-switch delete –device CL1*
----
. Si vous avez supprimé la création automatique de cas, réactivez-la en appelant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
[listing, subs="+quotes"]
----
cluster::*> *system node autosupport invoke -node \* -type all -message MAINT=END*
----


Voir link:configure-health-monitor.html["Installez le fichier de configuration CSHM (Cluster Switch Health Monitor)"] et link:configure-log-collection.html["Configurez la fonction de collecte du journal du commutateur de cluster"] pour connaître les étapes requises pour activer la collecte des journaux du commutateur d'intégrité du cluster, utilisée pour collecter les fichiers journaux relatifs au commutateur.

*Informations connexes*

https://hwu.netapp.com["Hardware Universe"^]

link:replace-requirements.html["Configuration et configuration des commutateurs BES-53248 pris en charge par Broadcom"^]
