---
permalink: switch-bes-53248/migrate-cn1610.html 
sidebar: sidebar 
keywords: CN1610, CN1610 replacing, migrate from CN1610 
summary: 'Pour remplacer les commutateurs de cluster CN1610 existants d"un cluster par des commutateurs de cluster BES-53248 pris en charge par Broadcom, vous devez effectuer une séquence de tâches spécifique.' 
---
= Migrez les commutateurs de cluster CN1610 vers les commutateurs de cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour migrer les commutateurs de cluster CN1610 d'un cluster vers des commutateurs de cluster BES-53248 pris en charge par Broadcom, vérifiez les exigences de migration, puis suivez la procédure de migration.

Les commutateurs de cluster suivants sont pris en charge :

* CN1610
* BES-53248




== Examen des conditions requises

Vérifiez que votre configuration répond aux exigences suivantes :

* Certains ports des commutateurs BES-53248 sont configurés pour fonctionner à 10 GbE.
* La connectivité 10 GbE des nœuds aux commutateurs de cluster BES 53248 a été planifiée, migrée et documentée.
* Le cluster fonctionne entièrement (il ne doit y avoir aucune erreur dans les journaux ou d'autres problèmes similaires).
* La personnalisation initiale des commutateurs BES-53248 est terminée, de sorte que :
+
** Les commutateurs BES-53248 exécutent la dernière version recommandée du logiciel EFOS.
** Les fichiers de configuration de référence (RCFs) ont été appliqués aux commutateurs.
** Toute personnalisation de site, telle que DNS, NTP, SMTP, SNMP, Et SSH, sont configurés sur les nouveaux commutateurs.






=== Connexions de nœuds

Les commutateurs du cluster prennent en charge les connexions de nœud suivantes :

* NetApp CN1610 : ports 0/1 à 0/12 (10GbE)
* BES 53248 : ports 0/1-0/16 (10 GbE/25 GbE)
+

NOTE: Des ports supplémentaires peuvent être activés en achetant des licences de ports.





=== Ports ISL

Les commutateurs de cluster utilisent les ports ISL (Inter-switch Link) suivants :

* NetApp CN1610 : ports 0/13 à 0/16 (10GbE)
* BES-53248 : ports 0/55-0/56 (100 GbE)


Le https://hwu.netapp.com/Home/Index["_NetApp Hardware Universe_"^] Contient des informations sur la compatibilité ONTAP, le micrologiciel EFOS pris en charge et le câblage aux commutateurs de cluster BES-53248.



=== Câblage ISL

Le câblage ISL approprié est le suivant :

* *Début :* pour CN1610 à CN1610 (SFP+ à SFP+), quatre câbles fibre optique SFP+ ou cuivre à connexion directe.
* *Final :* pour BES-53248 à BES-53248 (QSFP28 à QSFP28), deux émetteurs-récepteurs optiques QSFP28/fibre ou câbles à connexion directe en cuivre.




== Migrer les commutateurs

Suivez cette procédure pour migrer les commutateurs de cluster CN1610 vers les commutateurs de cluster BES-53248.

.À propos des exemples
Les exemples de cette procédure utilisent la nomenclature des commutateurs et des nœuds suivante :

* Ces exemples utilisent deux nœuds, chacun déployant deux ports d'interconnexion de cluster 10 GbE : `e0a` et `e0b`.
* Les sorties de la commande peuvent varier en fonction des différentes versions du logiciel ONTAP.
* Les commutateurs CN1610 à remplacer sont `CL1` et `CL2`.
* Les commutateurs BES-53248 qui permettent de remplacer les commutateurs CN1610 sont `cs1` et `cs2`.
* Les nœuds sont `node1` et `node2`.
* Le commutateur CL2 est d'abord remplacé par cs2, suivi de CL1 par cs1.
* Les commutateurs BES-53248 sont préchargés avec les versions supportées des fichiers RCF (Reference Configuration File) et Ethernet Fabric OS (EFOS) avec des câbles ISL connectés aux ports 55 et 56.
* Les noms LIF de cluster sont `node1_clus1` et `node1_clus2` pour le noeud 1, et `node2_clus1` et `node2_clus2` pour le noeud 2.


.Description de la tâche
Cette procédure couvre le scénario suivant :

* Le cluster commence avec deux nœuds connectés à deux commutateurs de cluster CN1610.
* Le commutateur CN1610 CL2 est remplacé par le commutateur BES-53248 cs2 :
+
** Arrêtez les ports des nœuds du cluster. Tous les ports doivent être arrêtés simultanément pour éviter l'instabilité du cluster.
** Déconnectez les câbles de tous les ports du cluster de tous les nœuds connectés à CL2, puis utilisez les câbles pris en charge pour reconnecter les ports au nouveau commutateur cs2 du cluster.


* Le commutateur CN1610 CL1 est remplacé par le commutateur BES-53248 cs1 :
+
** Arrêtez les ports des nœuds du cluster. Tous les ports doivent être arrêtés simultanément pour éviter l'instabilité du cluster.
** Déconnectez les câbles de tous les ports du cluster de tous les nœuds connectés à CL1, puis utilisez les câbles pris en charge pour reconnecter les ports au nouveau commutateur cs1 du cluster.





NOTE: Aucune liaison inter-commutateurs (ISL) opérationnelle n'est nécessaire au cours de cette procédure. Ceci est de par sa conception, car les modifications de version des fichiers RCF peuvent affecter temporairement la connectivité ISL. Pour assurer un fonctionnement sans interruption du cluster, la procédure suivante migre toutes les LIFs du cluster vers le commutateur partenaire opérationnel tout en effectuant les étapes sur le commutateur cible.



=== Étape 1 : préparer la migration

. Si AutoSupport est activé sur ce cluster, supprimez la création automatique de dossiers en invoquant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
où x représente la durée de la fenêtre de maintenance en heures.

+

NOTE: Le message AutoSupport informe le support technique de cette tâche de maintenance de sorte que la création automatique de dossier soit supprimée lors de la fenêtre de maintenance.

+
La commande suivante supprime la création automatique de dossiers pendant deux heures :

+
[listing]
----
cluster1::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
. Définissez le niveau de privilège sur avancé, en entrant *y* lorsque vous êtes invité à continuer :
+
`set -privilege advanced`

+
L'invite avancée (*>) apparaît.





=== Étape 2 : configurer les ports et le câblage

. Sur les nouveaux commutateurs, vérifiez que l'ISL est câblé et fonctionne correctement entre les commutateurs cs1 et cs2 :
+
`show port-channel`

+
.Montrer l'exemple
[%collapsible]
====
L'exemple suivant montre que les ports ISL sont *UP* sur le commutateur cs1 :

[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
L'exemple suivant montre que les ports ISL sont *UP* sur le commutateur cs2 :

[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. Afficher les ports de cluster sur chaque nœud connecté aux commutateurs de cluster existants :
+
`network device-discovery show -protocol cdp`

+
.Montrer l'exemple
[%collapsible]
====
L'exemple suivant montre combien d'interfaces d'interconnexion de cluster ont été configurées dans chaque nœud pour chaque commutateur d'interconnexion de cluster :

[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    CL1                       0/2               CN1610
            e0b    CL2                       0/2               CN1610
node1      /cdp
            e0a    CL1                       0/1               CN1610
            e0b    CL2                       0/1               CN1610
----
====
. Détermination du statut administratif ou opérationnel pour chaque interface de cluster
+
.. Vérifiez que tous les ports du cluster sont `up` avec un `healthy` état :
+
`network port show -ipspace Cluster`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
.. Vérifier que toutes les interfaces de cluster (LIFs) se trouvent sur leurs ports de type home :
+
`network interface show -vserver Cluster`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
----
====


. Vérifiez que le cluster affiche les informations relatives aux deux commutateurs de cluster :


[role="tabbed-block"]
====
.ONTAP 9.8 et versions ultérieures
--
Depuis ONTAP 9.8, utilisez la commande : `system switch ethernet show -is-monitoring-enabled-operational true`

[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show -is-monitoring-enabled-operational true*
Switch                        Type             Address       Model
----------------------------- ---------------- ------------- --------
CL1                           cluster-network  10.10.1.101   CN1610
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP

CL2                           cluster-network  10.10.1.102   CN1610
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP
cluster1::*>
----
--
.ONTAP 9.7 et versions antérieures
--
Pour ONTAP 9.7 et les versions antérieures, utilisez la commande : `system cluster-switch show -is-monitoring-enabled-operational true`

[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                        Type             Address       Model
----------------------------- ---------------- ------------- --------
CL1                           cluster-network  10.10.1.101   CN1610
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP

CL2                           cluster-network  10.10.1.102   CN1610
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP
cluster1::*>
----
--
====
. [[step5]]Désactiver la restauration automatique sur les LIFs du cluster.
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
. Sur le commutateur de cluster CL2, arrêter les ports connectés aux ports de cluster des nœuds afin de basculer les LIFs du cluster :
+
[listing, subs="+quotes"]
----
(CL2)# *configure*
(CL2)(Config)# *interface 0/1-0/16*
(CL2)(Interface 0/1-0/16)# *shutdown*
(CL2)(Interface 0/1-0/16)# *exit*
(CL2)(Config)# *exit*
(CL2)#
----
. Vérifiez que les LIFs du cluster ont basculé vers les ports hébergés sur le commutateur de cluster CL1. Cette opération peut prendre quelques secondes.
+
`network interface show -vserver Cluster`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1         e0a     false
            node2_clus1  up/up      169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2         e0a     false
----
====
. Vérifiez que le cluster fonctionne correctement :
+
`cluster show`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node       Health  Eligibility   Epsilon
---------- ------- ------------- -------
node1      true    true          false
node2      true    true          false
----
====
. Déplacez tous les câbles de connexion du nœud de cluster de l'ancien commutateur CL2 vers le nouveau commutateur cs2.
. Vérifiez l'état de santé des connexions réseau déplacées vers cs2 :
+
`network port show -ipspace Cluster`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
+
Tous les ports du cluster déplacés doivent être de `up`.

. Vérifier les informations de voisins sur les ports du cluster :
+
`network device-discovery show -protocol cdp`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    CL1                       0/2               CN1610
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    CL1                       0/1               CN1610
            e0b    cs2                       0/1               BES-53248
----
====
. Vérifiez que les connexions du port du commutateur sont correctes du point de vue du commutateur cs2 :
+
[listing, subs="+quotes"]
----
cs2# *show port all*
cs2# *show isdp neighbors*
----
. Sur le commutateur de cluster CL1, arrêter les ports connectés aux ports de cluster des nœuds afin de basculer les LIFs du cluster :
+
[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface 0/1-0/16*
(CL1)(Interface 0/1-0/16)# *shutdown*
(CL1)(Interface 0/13-0/16)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
+
Toutes les LIFs du cluster basculent sur le commutateur cs2.

. Vérifiez que les LIFs du cluster ont basculé vers les ports hébergés sur le commutateur cs2. Cette opération peut prendre quelques secondes :
+
`network interface show -vserver Cluster`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0b     false
            node1_clus2  up/up      169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2         e0b     false
            node2_clus2  up/up      169.254.19.183/16  node2         e0b     true
----
====
. Vérifiez que le cluster fonctionne correctement :
+
`cluster show`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node       Health  Eligibility   Epsilon
---------- ------- ------------- -------
node1      true    true          false
node2      true    true          false
----
====
. Déplacez les câbles de connexion du nœud de cluster de CL1 vers le nouveau commutateur cs1.
. Vérifiez l'état de santé des connexions réseau déplacées vers cs1 :
+
`network port show -ipspace Cluster`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
+
Tous les ports du cluster déplacés doivent être de `up`.

. Vérifier les informations de voisins sur les ports du cluster :
+
`network device-discovery show`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
----
====
. Vérifiez que les connexions du port du commutateur sont correctes du point de vue du commutateur cs1 :
+
[listing, subs="+quotes"]
----
cs1# *show port all*
cs1# *show isdp neighbors*
----
. Vérifier que l'ISL entre cs1 et cs2 est toujours opérationnel :
+
`show port-channel`

+
.Montrer l'exemple
[%collapsible]
====
L'exemple suivant montre que les ports ISL sont *UP* sur le commutateur cs1 :

[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
L'exemple suivant montre que les ports ISL sont *UP* sur le commutateur cs2 :

[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. Supprimer les commutateurs CN1610 remplacés de la table des commutateurs du cluster, s'ils ne sont pas automatiquement supprimés :


[role="tabbed-block"]
====
.ONTAP 9.8 et versions ultérieures
--
Depuis ONTAP 9.8, utilisez la commande : `system switch ethernet delete -device _device-name_`

[listing]
----
cluster::*> system switch ethernet delete -device CL1
cluster::*> system switch ethernet delete -device CL2
----
--
.ONTAP 9.7 et versions antérieures
--
Pour ONTAP 9.7 et les versions antérieures, utilisez la commande : `system cluster-switch delete -device _device-name_`

[listing]
----
cluster::*> system cluster-switch delete -device CL1
cluster::*> system cluster-switch delete -device CL2
----
--
====


=== Étape 3 : vérifier la configuration

. Activez la fonction de revert automatique sur les LIFs du cluster.
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert true*
----
. Vérifier que les LIFs du cluster sont rétablies sur leurs ports de base (cette opération peut prendre une minute) :
+
`network interface show -vserver Cluster`

+
Si les LIF de cluster n'ont pas été rétablies sur leur port de départ, elles peuvent être revert manuellement :

+
`network interface revert -vserver Cluster -lif *`

. Vérifiez que le cluster fonctionne correctement :
+
`cluster show`

. Exécutez une commande ping sur les interfaces de cluster distantes pour vérifier la connectivité :
+
`cluster ping-cluster -node <name>`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69  node1     e0a
Cluster node1_clus2 169.254.49.125  node1     e0b
Cluster node2_clus1 169.254.47.194  node2     e0a
Cluster node2_clus2 169.254.19.183  node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====
. Pour configurer la collecte des journaux, exécutez la commande suivante pour chaque commutateur. Vous êtes invité à entrer le nom du commutateur, le nom d'utilisateur et le mot de passe pour la collecte des journaux.
+
`system switch ethernet log setup-password`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *<return>*
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----
====
. Pour démarrer la collecte des journaux, exécutez la commande suivante, en remplaçant le PÉRIPHÉRIQUE par le commutateur utilisé dans la commande précédente. Ceci lance les deux types de collecte de journaux : les journaux détaillés *support* et une collecte horaire de données *périodiques*.
+
`system switch ethernet log modify -device _<switch-name>_ -log-request true`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration?
{y|n}: [n] *y*

Enabling cluster switch log collection.
----
====
+
Attendez 10 minutes, puis vérifiez que la collecte des journaux se termine :

+
`system switch ethernet log show`

+

CAUTION: Si l'une de ces commandes renvoie une erreur ou si la collecte des journaux ne se termine pas, contactez le support NetApp.

. Si vous avez supprimé la création automatique de cas, réactivez-la en appelant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
[listing, subs="+quotes"]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----

