---
permalink: switch-bes-53248/migrate-cn1610-overview.html 
sidebar: sidebar 
keywords: BES-53248 switches,replacing with BES-53248 switches, migrate cluster switches 
summary: Vous devez connaître certaines informations de configuration, connexions de ports et exigences de câblage lorsque vous migrez les commutateurs de cluster CN1610 vers des commutateurs de cluster BES-53248 pris en charge par Broadcom. 
---
= Migrez les commutateurs de cluster CN1610 vers les commutateurs de cluster BES-53248 pris en charge par Broadcom
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez connaître certaines informations de configuration, connexions de ports et exigences de câblage lorsque vous migrez les commutateurs de cluster CN1610 vers des commutateurs de cluster BES-53248 pris en charge par Broadcom.

* Les commutateurs de cluster suivants sont pris en charge :
+
** CN1610
** BES-53248


* Les commutateurs du cluster prennent en charge les connexions de nœud suivantes :
+
** NetApp CN1610 : ports 0/1 à 0/12 (10 GbE)
** BES-53248 : ports 0/1-0/16 (10/25 GbE)
+

NOTE: Des ports supplémentaires peuvent être activés en achetant des licences de ports.



* Les commutateurs de cluster utilisent les ports ISL (Inter-switch Link) suivants :
+
** NetApp CN1610 : ports 0/13 à 0/16 (10 GbE)
** BES-53248 : ports 0/55-0/56 (100 GbE)


* Le https://hwu.netapp.com/Home/Index["_NetApp Hardware Universe_"^] Contient des informations sur la compatibilité ONTAP, le micrologiciel EFOS pris en charge et le câblage aux commutateurs de cluster BES-53248.
* Le câblage ISL approprié est le suivant :
+
** *Début :* pour CN1610 à CN1610 (SFP+ à SFP+), quatre câbles fibre optique SFP+ ou cuivre à connexion directe.
** *Interim :* pour CN1610 à BES-53248 (SFP+ à SFP28), quatre câbles à connexion directe en cuivre ou à émetteur-récepteur optique SFP+ 10G.
** *Final :* pour BES-53248 à BES-53248 (QSFP28 à QSFP28), deux émetteurs-récepteurs optiques QSFP28/fibre ou câbles à connexion directe en cuivre.





NOTE: Une fois la migration terminée, vous devrez peut-être installer le fichier de configuration requis pour prendre en charge le Cluster Switch Health Monitor (CSHM) pour les commutateurs de cluster BES-53248.

Voir link:configure-health-monitor.html["Installez le fichier de configuration CSHM (Cluster Switch Health Monitor)"] et link:configure-log-collection.html["Configurez la fonction de collecte du journal du commutateur de cluster"] pour connaître les étapes requises pour activer la collecte des journaux du commutateur d'intégrité du cluster, utilisée pour collecter les fichiers journaux relatifs au commutateur.
