---
permalink: switch-bes-53248/migrate-cn1610.html 
sidebar: sidebar 
keywords: CN1610, CN1610 replacing, migrate from CN1610 
summary: Pour remplacer les commutateurs de cluster CN1610 existants dans un cluster par des commutateurs de cluster BES-53248 pris en charge par Broadcom, vous devez effectuer une séquence de tâches spécifique. 
---
= Migration des commutateurs de cluster CN1610 vers les commutateurs de cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour migrer les commutateurs de cluster CN1610 d'un cluster vers des commutateurs de cluster BES-53248 pris en charge par Broadcom, consultez les exigences de migration puis suivez la procédure de migration.

Les commutateurs de cluster suivants sont pris en charge :

* CN1610
* BES-53248




== Exigences de révision

Vérifiez que votre configuration répond aux exigences suivantes :

* Certains ports des commutateurs BES-53248 sont configurés pour fonctionner à 10GbE.
* La connectivité 10GbE des nœuds aux commutateurs de cluster BES-53248 a été planifiée, migrée et documentée.
* Le cluster est pleinement fonctionnel (il ne devrait y avoir aucune erreur dans les journaux ni aucun problème similaire).
* La personnalisation initiale des commutateurs BES-53248 est terminée, de sorte que :
+
** Les commutateurs BES-53248 exécutent la dernière version recommandée du logiciel EFOS.
** Des fichiers de configuration de référence (RCF) ont été appliqués aux commutateurs.
** Toute personnalisation du site, telle que DNS, NTP, SMTP, SNMP et SSH, est configurée sur les nouveaux commutateurs.






=== Connexions de nœuds

Les commutateurs du cluster prennent en charge les connexions de nœuds suivantes :

* NetApp CN1610 : ports 0/1 à 0/12 (10 GbE)
* BES-53248 : ports 0/1 à 0/16 (10 GbE/25 GbE)
+

NOTE: Des ports supplémentaires peuvent être activés en achetant des licences de port.





=== Ports ISL

Les commutateurs du cluster utilisent les ports de liaison inter-commutateurs (ISL) suivants :

* NetApp CN1610 : ports 0/13 à 0/16 (10 GbE)
* BES-53248 : ports 0/55-0/56 (100 GbE)


Le https://hwu.netapp.com/Home/Index["_L'univers matériel de NetApp_"^] contient des informations sur la compatibilité ONTAP , le firmware EFOS pris en charge et le câblage vers les commutateurs de cluster BES-53248.



=== Câblage ISL

Le câblage ISL approprié est le suivant :

* *Début :* Pour CN1610 à CN1610 (SFP+ à SFP+), quatre câbles à fibre optique ou à connexion directe en cuivre SFP+.
* *Final :* Pour BES-53248 à BES-53248 (QSFP28 à QSFP28), deux émetteurs-récepteurs optiques QSFP28/fibre ou câbles à connexion directe en cuivre.




== Déplacer les commutateurs

Suivez cette procédure pour migrer les commutateurs de cluster CN1610 vers les commutateurs de cluster BES-53248.

.À propos des exemples
Les exemples de cette procédure utilisent la nomenclature suivante pour les commutateurs et les nœuds :

* Les exemples utilisent deux nœuds, chacun déployant deux ports d'interconnexion de cluster 10 GbE : `e0a` et `e0b` .
* Les résultats des commandes peuvent varier en fonction des différentes versions du logiciel ONTAP .
* Les commutateurs CN1610 à remplacer sont `CL1` et `CL2` .
* Les commutateurs BES-53248 destinés à remplacer les commutateurs CN1610 sont `cs1` et `cs2` .
* Les nœuds sont `node1` et `node2` .
* L'interrupteur CL2 est d'abord remplacé par cs2, puis CL1 par cs1.
* Les commutateurs BES-53248 sont préchargés avec les versions prises en charge du fichier de configuration de référence (RCF) et du système d'exploitation Ethernet Fabric (EFOS) avec des câbles ISL connectés sur les ports 55 et 56.
* Les noms LIF du cluster sont `node1_clus1` et `node1_clus2` pour le nœud 1, et `node2_clus1` et `node2_clus2` pour le nœud 2.


.À propos de cette tâche
Cette procédure couvre le scénario suivant :

* Le cluster commence avec deux nœuds connectés à deux commutateurs de cluster CN1610.
* Le commutateur CN1610 CL2 est remplacé par le commutateur BES-53248 cs2 :
+
** Fermez les ports des nœuds du cluster.  Tous les ports doivent être fermés simultanément pour éviter l'instabilité du cluster.
** Débranchez les câbles de tous les ports du cluster sur tous les nœuds connectés à CL2, puis utilisez des câbles compatibles pour reconnecter les ports au nouveau commutateur de cluster cs2.


* Le commutateur CN1610 CL1 est remplacé par le commutateur BES-53248 cs1 :
+
** Fermez les ports des nœuds du cluster.  Tous les ports doivent être fermés simultanément pour éviter l'instabilité du cluster.
** Débranchez les câbles de tous les ports du cluster sur tous les nœuds connectés à CL1, puis utilisez des câbles compatibles pour reconnecter les ports au nouveau commutateur de cluster cs1.





NOTE: Aucune liaison inter-commutateurs opérationnelle (ISL) n'est nécessaire pendant cette procédure. Ceci est intentionnel car les changements de version RCF peuvent affecter temporairement la connectivité ISL. Pour garantir le fonctionnement non perturbateur du cluster, la procédure suivante migre toutes les LIF du cluster vers le commutateur partenaire opérationnel tout en exécutant les étapes sur le commutateur cible.



=== Étape 1 : Préparer la migration

. Si AutoSupport est activé sur ce cluster, supprimez la création automatique de cas en envoyant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
où x représente la durée de la fenêtre de maintenance en heures.

+

NOTE: Le message AutoSupport notifie le support technique de cette tâche de maintenance afin que la création automatique de tickets soit désactivée pendant la période de maintenance.

+
La commande suivante désactive la création automatique de cas pendant deux heures :

+
[listing]
----
cluster1::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
. Passez au niveau de privilège avancé en saisissant *y* lorsque vous êtes invité à continuer :
+
`set -privilege advanced`

+
L'invite avancée (*>) apparaît.





=== Étape 2 : Configurer les ports et le câblage

. Sur les nouveaux commutateurs, vérifiez que la liaison ISL est bien câblée et fonctionnelle entre les commutateurs cs1 et cs2 :
+
`show port-channel`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre que les ports ISL sont *actifs* sur le commutateur cs1 :

[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
L'exemple suivant montre que les ports ISL sont *actifs* sur le commutateur cs2 :

[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. Afficher les ports du cluster sur chaque nœud connecté aux commutateurs du cluster existant :
+
`network device-discovery show -protocol cdp`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant illustre le nombre d'interfaces d'interconnexion de cluster configurées dans chaque nœud pour chaque commutateur d'interconnexion de cluster :

[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    CL1                       0/2               CN1610
            e0b    CL2                       0/2               CN1610
node1      /cdp
            e0a    CL1                       0/1               CN1610
            e0b    CL2                       0/1               CN1610
----
====
. Déterminez l'état administratif ou opérationnel de chaque interface de cluster.
+
.. Vérifiez que tous les ports du cluster sont `up` avec un `healthy` statut:
+
`network port show -ipspace Cluster`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
.. Vérifiez que toutes les interfaces du cluster (LIF) sont connectées à leurs ports d'origine :
+
`network interface show -vserver Cluster`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
----
====


. Vérifiez que le cluster affiche les informations pour les deux commutateurs du cluster :


[role="tabbed-block"]
====
.ONTAP 9.8 et versions ultérieures
--
À partir d' ONTAP 9.8, utilisez la commande : `system switch ethernet show -is-monitoring-enabled-operational true`

[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show -is-monitoring-enabled-operational true*
Switch                        Type             Address       Model
----------------------------- ---------------- ------------- --------
CL1                           cluster-network  10.10.1.101   CN1610
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP

CL2                           cluster-network  10.10.1.102   CN1610
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP
cluster1::*>
----
--
.ONTAP 9.7 et versions antérieures
--
Pour ONTAP 9.7 et versions antérieures, utilisez la commande : `system cluster-switch show -is-monitoring-enabled-operational true`

[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                        Type             Address       Model
----------------------------- ---------------- ------------- --------
CL1                           cluster-network  10.10.1.101   CN1610
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP

CL2                           cluster-network  10.10.1.102   CN1610
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP
cluster1::*>
----
--
====
. [[étape 5]]Désactiver la restauration automatique sur les LIF du cluster.
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
. Sur le commutateur de cluster CL2, désactivez les ports connectés aux ports de cluster des nœuds afin de basculer les LIF du cluster :
+
[listing, subs="+quotes"]
----
(CL2)# *configure*
(CL2)(Config)# *interface 0/1-0/16*
(CL2)(Interface 0/1-0/16)# *shutdown*
(CL2)(Interface 0/1-0/16)# *exit*
(CL2)(Config)# *exit*
(CL2)#
----
. Vérifiez que les LIF du cluster ont basculé vers les ports hébergés sur le commutateur de cluster CL1. Cela peut prendre quelques secondes.
+
`network interface show -vserver Cluster`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1         e0a     false
            node2_clus1  up/up      169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2         e0a     false
----
====
. Vérifiez que le cluster est sain :
+
`cluster show`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node       Health  Eligibility   Epsilon
---------- ------- ------------- -------
node1      true    true          false
node2      true    true          false
----
====
. Déplacez tous les câbles de connexion des nœuds du cluster de l'ancien commutateur CL2 vers le nouveau commutateur cs2.
. Vérifiez l'état des connexions réseau déplacées vers cs2 :
+
`network port show -ipspace Cluster`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
+
Tous les ports du cluster qui ont été déplacés devraient être `up` .

. Vérifiez les informations des voisins sur les ports du cluster :
+
`network device-discovery show -protocol cdp`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    CL1                       0/2               CN1610
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    CL1                       0/1               CN1610
            e0b    cs2                       0/1               BES-53248
----
====
. Vérifiez que les connexions des ports du commutateur sont saines du point de vue du commutateur cs2 :
+
[listing, subs="+quotes"]
----
cs2# *show interface all*
cs2# *show isdp neighbors*
----
. Sur le commutateur de cluster CL1, désactivez les ports connectés aux ports de cluster des nœuds afin de basculer les LIF du cluster :
+
[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface 0/1-0/16*
(CL1)(Interface 0/1-0/16)# *shutdown*
(CL1)(Interface 0/13-0/16)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
+
Toutes les interfaces logiques du cluster basculent vers le commutateur cs2.

. Vérifiez que les LIF du cluster ont basculé vers les ports hébergés sur le commutateur cs2. Cela peut prendre quelques secondes :
+
`network interface show -vserver Cluster`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0b     false
            node1_clus2  up/up      169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2         e0b     false
            node2_clus2  up/up      169.254.19.183/16  node2         e0b     true
----
====
. Vérifiez que le cluster est sain :
+
`cluster show`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node       Health  Eligibility   Epsilon
---------- ------- ------------- -------
node1      true    true          false
node2      true    true          false
----
====
. Déplacez les câbles de connexion du nœud de cluster de CL1 vers le nouveau commutateur cs1.
. Vérifiez l'état des connexions réseau déplacées vers cs1 :
+
`network port show -ipspace Cluster`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
+
Tous les ports du cluster qui ont été déplacés devraient être `up` .

. Vérifiez les informations des voisins sur les ports du cluster :
+
`network device-discovery show`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
----
====
. Vérifiez que les connexions des ports du commutateur sont saines du point de vue du commutateur cs1 :
+
[listing, subs="+quotes"]
----
cs1# *show interface all*
cs1# *show isdp neighbors*
----
. Vérifiez que la liaison inter-commutateurs (ISL) entre cs1 et cs2 est toujours opérationnelle :
+
`show port-channel`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre que les ports ISL sont *actifs* sur le commutateur cs1 :

[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
L'exemple suivant montre que les ports ISL sont *actifs* sur le commutateur cs2 :

[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. Supprimez les commutateurs CN1610 remplacés de la table de commutation du cluster, s'ils ne sont pas supprimés automatiquement :


[role="tabbed-block"]
====
.ONTAP 9.8 et versions ultérieures
--
À partir d' ONTAP 9.8, utilisez la commande : `system switch ethernet delete -device _device-name_`

[listing]
----
cluster::*> system switch ethernet delete -device CL1
cluster::*> system switch ethernet delete -device CL2
----
--
.ONTAP 9.7 et versions antérieures
--
Pour ONTAP 9.7 et versions antérieures, utilisez la commande : `system cluster-switch delete -device _device-name_`

[listing]
----
cluster::*> system cluster-switch delete -device CL1
cluster::*> system cluster-switch delete -device CL2
----
--
====


=== Étape 3 : Vérifier la configuration

. Activer la restauration automatique sur les LIF du cluster.
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert true*
----
. Vérifiez que les LIF du cluster sont revenues à leurs ports d'origine (cela peut prendre une minute) :
+
`network interface show -vserver Cluster`

+
Si les LIF du cluster ne sont pas revenues à leur port d'origine, rétablissez-les manuellement :

+
`network interface revert -vserver Cluster -lif *`

. Vérifiez que le cluster est sain :
+
`cluster show`

. Vérifiez la connectivité des interfaces du cluster distant :


[role="tabbed-block"]
====
.ONTAP 9.9.1 et versions ultérieures
--
Vous pouvez utiliser le `network interface check cluster-connectivity` commande permettant de lancer une vérification d'accessibilité pour la connectivité du cluster, puis d'afficher les détails :

`network interface check cluster-connectivity start`et `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*REMARQUE :* Attendez quelques secondes avant d’exécuter le programme. `show` commande pour afficher les détails.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source          Destination       Packet
Node   Date                       LIF             LIF               Loss
------ -------------------------- --------------- ----------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2_clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none

node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Toutes les versions ONTAP
--
Pour toutes les versions ONTAP , vous pouvez également utiliser `cluster ping-cluster -node <name>` commande pour vérifier la connectivité :

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e0a
Cluster node1_clus2 169.254.49.125 node1     e0b
Cluster node2_clus1 169.254.47.194 node2     e0a
Cluster node2_clus2 169.254.19.183 node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[étape 5]]Si vous avez désactivé la création automatique de dossiers, réactivez-la en envoyant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
[listing, subs="+quotes"]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----


.Quelle est la prochaine étape ?
Une fois vos commutateurs migrés, vous pouvez link:../switch-cshm/config-overview.html["configurer la surveillance de l'état du commutateur"].
