---
permalink: switch-bes-53248/overview-bes53248.html 
sidebar: sidebar 
keywords: cluster-mode,supported versions,switches supported,cluster network,efos 
summary: Les commutateurs de cluster BES-53248 pris en charge par Broadcom sont conçus pour fonctionner dans des clusters de tailles allant de deux à 24 nœuds dans ONTAP 9.5P8 et versions ultérieures. La prise en charge des ports de cluster 40/100 GbE commence par la version 3.4.4.6 du firmware EFOS et les versions ultérieures. 
---
= Présentation des commutateurs de cluster BES-53248 pris en charge par Broadcom
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les commutateurs de cluster BES-53248 pris en charge par Broadcom sont conçus pour fonctionner dans des clusters de tailles allant de deux à 24 nœuds dans ONTAP 9.5P8 et versions ultérieures. La prise en charge des ports de cluster 40/100 GbE commence par la version 3.4.4.6 du firmware EFOS et les versions ultérieures.

BES-53248 est un commutateur qui s'exécute sur un système d'exploitation intégré Broadcom, appelé Ethernet Fabric OS (EFOS).

Le tableau suivant répertorie le numéro de référence et la description du commutateur de cluster BES-53248, du kit de rails de montage en rack, des ventilateurs et des alimentations :

[cols="1,2"]
|===
| Numéro de référence | Description 


 a| 
X190005
 a| 
BES-53248, CLSW, 16Pt10/25 Gb, PTSX, BRDCM SUPP (PTSX = échappement côté port)



 a| 
X190005R
 a| 
BES-53248, CLSW, 16Pt10/25 Gb, PSIN, SUPPLÉMENT BRDCM (PSIN = admission côté port)



 a| 
X-RAIL-4POST-190005
 a| 
Kit de rails de montage sur rack Ozeki 4 montants 19"



 a| 
X-FAN-190005-R
 a| 
Ventilateur, côté orifice d'admission X190005



 a| 
X-FAN-190005-F
 a| 
Ventilateur, côté orifice d'échappement X190005



 a| 
X-PSU-190005-R
 a| 
Alimentation, prise côté orifice X190005



 a| 
X-PSU-190005-F
 a| 
Alimentation, côté orifice d'échappement X190005

|===
Vue d'ensemble du débit d'air en fonction des deux modèles proposés :

* Flux d'air d'échappement côté port (air standard) : l'air frais pénètre dans le châssis par le ventilateur et les modules d'alimentation dans l'allée froide et s'échappe par l'extrémité du port du châssis dans l'allée chaude. La couleur bleue indique le débit d'air d'échappement côté port. Il s'agit de l'option la plus courante.
* Air d'admission côté orifice (air inversé) : l'air frais pénètre dans le châssis par l'extrémité de l'orifice dans l'allée froide et s'échappe par les modules de ventilateur et d'alimentation dans l'allée chaude.


Voir la https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_add_Additional_Port_Licensing_for_the_Broadcom-Supported_BES-53248_Switch["Article de la base de connaissances NetApp : comment ajouter une licence de port supplémentaire pour le commutateur BES-53248 pris en charge par Broadcom"^] pour plus d'informations sur l'ajout de licences de port supplémentaires.

Pour plus d'informations sur les connecteurs et les options de câble à utiliser avec leurs références, reportez-vous au https://hwu.netapp.com/Home/Index["NetApp Hardware Universe"^].

Pour plus d'informations, reportez-vous à la matrice de compatibilité du réseau de clusters et de gestion_ disponible sur le site de téléchargement du commutateur BES-53248 https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Commutateurs de cluster Broadcom"^].
