---
permalink: switch-bes-53248/replace-switch-reqs.html 
sidebar: sidebar 
keywords: replace, replacing, defective, broadcom-supported, bes, cluster, switch, network, nondisruptive, procedure, ndu, replace a broadcom-supported bes-53428 cluster switch - bes-53428 switches 
summary: 'Le remplacement d"un commutateur de cluster BES-53248 défectueux pris en charge par Broadcom sur un réseau en cluster est une procédure sans interruption \(NDU\).' 
---
= Exigences de remplacement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de remplacer le contacteur, s'assurer que les conditions suivantes sont réunies dans l'environnement actuel et sur le commutateur de remplacement.



== Infrastructure réseau et cluster existante

Assurez-vous que :

* Le cluster existant est vérifié entièrement fonctionnel, avec au moins un commutateur de cluster entièrement connecté.
* Tous les ports de cluster sont *up*.
* Toutes les interfaces logiques de cluster (LIFS) sont administrativement et de manière opérationnelle * up* et sur leurs ports de base.
* Le ONTAP `cluster ping-cluster -node node1` la commande doit indiquer que les paramètres, `basic connectivity` et `larger than PMTU communication`, ont réussi sur tous les chemins.




== Commutateur de bloc d'instruments de remplacement BES-53248

Assurez-vous que :

* La connectivité réseau de gestion sur le commutateur de remplacement est fonctionnelle.
* L'accès à la console au commutateur de remplacement est en place.
* Les connexions de nœuds sont les ports 0/1 à 0/16 avec licence par défaut.
* Tous les ports ISL (Inter-Switch Link) sont désactivés sur les ports 0/55 et 0/56.
* Le fichier de configuration de référence (RCF) souhaité et l'image du commutateur du système d'exploitation EFOS sont chargés sur le commutateur.
* La personnalisation initiale du commutateur est terminée, comme indiqué dans link:configure-install-initial.html["Configurez le commutateur du cluster BES-53248"].


Toute personnalisation de site antérieure, telle que STP, SNMP et SSH, est copiée sur le nouveau commutateur.



== Pour en savoir plus

* https://mysupport.netapp.com/["Site de support NetApp"^]
* https://hwu.netapp.com/Home/Index["NetApp Hardware Universe"^]

