---
permalink: switch-bes-53248/replace-requirements.html 
sidebar: sidebar 
keywords: requirements, bes-53428 switches 
summary: 'Pour configurer votre cluster, vous devez disposer du nombre et du type appropriés de câbles et de connecteurs de câbles pour les commutateurs de cluster. Selon le type de commutateur de cluster que vous configurez au départ, vous devez vous connecter au port console des commutateurs avec le câble de console inclus et vous devez disposer d"informations réseau spécifiques.' 
---
= Exigences de configuration du commutateur de cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour configurer votre cluster, vous devez disposer du nombre et du type appropriés de câbles et de connecteurs de câbles pour les commutateurs de cluster. Selon le type de commutateur de cluster que vous configurez au départ, vous devez vous connecter au port console des commutateurs avec le câble de console inclus et vous devez disposer d'informations réseau spécifiques.



== Affectations des ports du commutateur de cluster BES-53248

Vous pouvez utiliser le tableau des attributions de ports de commutateur de cluster BES-53248 pris en charge par Broadcom pour configurer votre cluster.

[cols="1,2"]
|===
| Commutateurs | Utilisation des ports 


 a| 
01-16
 a| 
Nœuds de cluster 10 GbE avec port, configuration de base



 a| 
17-48
 a| 
Nœuds de cluster 10 GbE avec licences



 a| 
49-54
 a| 
Des nœuds de port de cluster 100 GbE, avec des licences, ajoutés de droite à gauche



 a| 
55-56
 a| 
Ports ISL (Inter-Switch Link) de cluster 100 GbE, configuration de base

|===
Sur les switchs de cluster BES-53248, les ports 48 10 GbE (SFP28/SFP+) sont regroupés en groupes à 12 ports 4 comme suit :

* Ports 1-4, 5-8, 9-12, 13-16, 17-20, 21-24, 25-28, 29-32, 33-36, 37-40, 41-44 et 45-48.


La vitesse des ports SFP28/SFP+ doit être identique (10 GbE ou 25 GbE) sur tous les ports du groupe à 4 ports.
