---
permalink: switch-bes-53248/replace-prepare-controller.html 
sidebar: sidebar 
keywords: BES-53248 switches,preparing for upgrade,upgrade bes-53248 switch 
summary: Vous pouvez utiliser cette procédure pour préparer le contrôleur à une mise à niveau du commutateur de cluster BES-53248. 
---
= Préparer le contrôleur à la mise à niveau du commutateur de cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser cette procédure pour préparer le contrôleur à une mise à niveau du commutateur de cluster BES-53248.

.Étapes
. Connectez le commutateur de cluster au réseau de gestion.
. Utilisez la commande ping pour vérifier la connectivité sur le serveur hébergeant EFOS, les licences et le FCR.
+
En cas de problème, utilisez un réseau non routé et configurez le port de service à l'aide de l'adresse IP 192.168.x ou 172.19.x. Vous pouvez reconfigurer ultérieurement le port de service à l'adresse IP de gestion de production.

+
Cet exemple vérifie que le commutateur est connecté au serveur à l'adresse IP 172.19.2 :

+
[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. Vérifier que les ports du cluster sont sains et disposent d'un lien à l'aide de la commande :
+
`network port show -ipspace Cluster`

+
L'exemple suivant montre le type de sortie avec tous les ports possédant un `Link` valeur de up et a `Health Status` de santé:

+
[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
------ ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
-----  ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false
----
. Vérifiez que les LIFs du cluster sont administrativement et sans fonctionnement, et qu'elles résident sur leurs ports de repos, à l'aide de la commande :
+
`network interface show -vserver Cluster`

+
Dans cet exemple, le `-vserver` Paramètre affiche des informations sur les LIFs associées aux ports de cluster. `Status Admin/Oper` doit être up et `Is Home` doit être vrai :

+
[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster*

          Logical      Status     Network             Current       Current Is
Vserver   Interface    Admin/Oper Address/Mask        Node          Port    Home
--------- ----------   ---------- ------------------  ------------- ------- ----
Cluster
          node1_clus1
                       up/up      169.254.217.125/16  node1         e0a     true
          node1_clus2
                       up/up      169.254.205.88/16   node1         e0b     true
          node2_clus1
                       up/up      169.254.252.125/16  node2         e0a     true
          node2_clus2
                       up/up      169.254.110.131/16  node2         e0b     true
----

