---
permalink: switch-bes-53248/replace-switch.html 
sidebar: sidebar 
keywords: replace, replacing, defective, broadcom-supported, bes, cluster, switch, network, nondisruptive, procedure, ndu, replace a broadcom-supported bes-53428 cluster switch - bes-53428 switches 
summary: 'Le remplacement d"un commutateur de cluster BES-53248 défectueux pris en charge par Broadcom sur un réseau en cluster est une procédure sans interruption \(NDU\).' 
---
= Remplacez un commutateur de cluster BES-53248 pris en charge par Broadcom
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le remplacement d'un commutateur de cluster BES-53248 défectueux pris en charge par Broadcom sur un réseau de cluster constitue une procédure sans interruption (NDU, non-Disruptive Procedure).

.Avant de commencer
Les conditions suivantes doivent exister avant d'effectuer le remplacement du commutateur dans l'environnement actuel et sur le commutateur de remplacement.

* Infrastructure réseau et cluster existante :
+
** Le cluster existant doit être vérifié comme entièrement fonctionnel, avec au moins un commutateur de cluster entièrement connecté.
** Tous les ports de cluster doivent être up.
** Toutes les interfaces logiques (LIF) du cluster doivent être administrativement et opérationnelles, et sur leurs ports de base.
** Le ONTAP `cluster ping-cluster -node node1` la commande doit indiquer cela `basic connectivity` et `larger than PMTU communication` ont réussi sur tous les chemins.


* Commutateur de bloc d'instruments de remplacement BES-53248 :
+
** La connectivité réseau de gestion du commutateur de remplacement doit être fonctionnelle.
** L'accès à la console au commutateur de remplacement doit être en place.
** Les connexions de nœuds sont les ports 0/1 à 0/16 avec licence par défaut.
** Tous les ports ISL (Inter-Switch Link) doivent être désactivés sur les ports 0/55 et 0/56.
** Le fichier de configuration de référence (RCF) souhaité et l'image du commutateur du système d'exploitation EFOS doivent être chargés sur le commutateur.
** La personnalisation initiale du commutateur doit être terminée, comme indiqué dans xref:configure-new-switch.adoc[Configuration d'un nouveau commutateur BES-53248 pris en charge par Broadcom].
+
Toute personnalisation de site antérieure, telle que STP, SNMP et SSH, doit être copiée sur le nouveau commutateur.





.Description de la tâche
Les exemples de cette procédure utilisent la nomenclature des commutateurs et des nœuds suivante :

* Les noms des commutateurs BES-53248 existants sont `cs1` et `cs2`.
* Le nom du nouveau commutateur BES-53248 est `newcs2`.
* Les noms de nœud sont `node1` et `node2`.
* Les ports de cluster de chaque nœud sont nommés `e0a` et `e0b`.
* Les noms LIF de cluster sont `node1_clus1` et `node1_clus2` pour le noeud 1, et `node2_clus1` et `node2_clus2` pour le noeud 2.
* Vous êtes invité à modifier tous les nœuds du cluster à `cluster1::>`



NOTE: La procédure suivante est basée sur la topologie réseau de cluster suivante :

[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false


Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false


cluster1::> *network interface show -vserver Cluster*
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true


cluster1::> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
----
[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater

Device ID                Intf      Holdtime  Capability Platform         Port ID
------------------------ --------- --------- ---------- ---------------- ---------
node1                    0/1       175       H          FAS2750          e0a
node2                    0/2       152       H          FAS2750          e0a
cs2                      0/55      179       R          BES-53248        0/55
cs2                      0/56      179       R          BES-53248        0/56


(cs2)# show isdp neighbors

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater

Device ID                Intf      Holdtime  Capability Platform         Port ID
------------------------ --------- --------- ---------- ---------------- ---------
node1                    0/1       129       H          FAS2750          e0b
node2                    0/2       165       H          FAS2750          e0b
cs1                      0/55      179       R          BES-53248        0/55
cs1                      0/56      179       R          BES-53248        0/56
----
.Étapes
. Installez la FCR et l'image appropriées sur le commutateur, newcs2, et effectuez les préparations nécessaires du site.
+
Si nécessaire, vérifiez, téléchargez et installez les versions appropriées des logiciels RCF et EFOS pour le nouveau commutateur. Si vous avez vérifié que le nouveau commutateur est correctement configuré et qu'il n'a pas besoin de mises à jour du logiciel RCF et EFOS, passez à l'étape 2.

+
.. Vous pouvez télécharger le logiciel Broadcom EFOS applicable pour vos commutateurs de cluster à partir du https://www.broadcom.com/support/bes-switch["Prise en charge des commutateurs Ethernet Broadcom"^] le site. Suivez les étapes de la page de téléchargement pour télécharger le fichier EFOS de la version du logiciel ONTAP que vous installez.
.. La FCR appropriée est disponible sur le https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Commutateurs de cluster Broadcom"^] page. Suivez les étapes de la page de téléchargement pour télécharger la FCR appropriée pour la version du logiciel ONTAP que vous installez.


. Sur le nouveau switch, connectez-vous en tant qu'admin et arrêtez tous les ports qui seront connectés aux interfaces du cluster de nœuds (ports 1 à 16).
+

NOTE: Si vous avez acheté des licences supplémentaires pour des ports supplémentaires, arrêtez également ces ports.

+
Si le commutateur que vous remplacez n'est pas fonctionnel et que celui-ci est hors tension, les LIF des nœuds du cluster doivent déjà avoir basculer vers l'autre port de cluster pour chaque nœud.

+

NOTE: Aucun mot de passe n'est requis pour la saisie `enable` mode.

+
[listing, subs="+quotes"]
----
User: *admin*
Password:
(newcs2)> *enable*
(newcs2)# *config*
(newcs2)(config)# *interface 0/1-0/16*
(newcs2)(interface 0/1-0/16)# *shutdown*
(newcs2)(interface 0/1-0/16)# *exit*
(newcs2)(config)# *exit*
(newcs2)#
----
. Vérifier que toutes les LIFs du cluster ont `auto-revert` activé :
+
`network interface show -vserver Cluster -fields auto-revert`

+
[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster -fields auto-revert*

Logical
Vserver   Interface    Auto-revert
--------- ------------ ------------
Cluster   node1_clus1  true
Cluster   node1_clus2  true
Cluster   node2_clus1  true
Cluster   node2_clus2  true

----
. Arrêtez les ports ISL 0/55 et 0/56 sur le commutateur BES-53248 cs1 :
+
[listing, subs="+quotes"]
----
(cs1)# *config*
(cs1)(config)# *interface 0/55-0/56*
(cs1)(interface 0/55-0/56)# *shutdown*
----
. Retirez tous les câbles du commutateur bes-53248 cs2, puis connectez-les aux mêmes ports du commutateur BES-53248 newcs2.
. Mettez les ports ISL 0/55 et 0/56 entre les commutateurs cs1 et newcs2, puis vérifiez le statut du canal du port.
+
L'état de liaison du canal 1/1 doit être activé et tous les ports membres doivent être vrais sous l'en-tête Port actif.

+
Cet exemple active les ports ISL 0/55 et 0/56 et affiche l'état de liaison du port-Channel 1/1 sur le commutateur cs1 :

+
[listing, subs="+quotes"]
----
(cs1)# *config*
(cs1)(config)# *interface 0/55-0/56*
(cs1)(interface 0/55-0/56)# *no shutdown*
(cs1)(interface 0/55-0/56)# *exit*
(cs1)# *show port-channel 1/1*

Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port-channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------- -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
. Sur le nouveau commutateur newcs2, réactivez tous les ports connectés aux interfaces du cluster de nœuds (ports 1 à 16).
+

NOTE: Si vous avez acheté des licences supplémentaires pour des ports supplémentaires, arrêtez également ces ports.

+
[listing, subs="+quotes"]
----
User:admin
Password:
(newcs2)> *enable*
(newcs2)# *config*
(newcs2)(config)# *interface 0/1-0/16*
(newcs2)(interface 0/1-0/16)# *no shutdown*
(newcs2)(interface 0/1-0/16)# *exit*
(newcs2)(config)# *exit*
----
. Vérifiez que le port e0b est bien le port `up`:
+
`network port show -ipspace Cluster`

+
La sortie doit être similaire à ce qui suit :

+
[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                   Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ----- ----------- -------- -------
e0a       Cluster      Cluster          up   9000  auto/10000  healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000  healthy  false

Node: node2
                                                                        Ignore
                                                   Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ----- ----------- -------- -------
e0a       Cluster      Cluster          up   9000  auto/10000  healthy  false
e0b       Cluster      Cluster          up   9000  auto/auto   -        false
----
. Sur le même nœud que vous avez utilisé à l'étape précédente, attendez que la LIF de cluster node 1_clus2 sur le nœud 1 pour qu'elle revert automatiquement.
+
Dans cet exemple, la LIF node1_clus2 sur le nœud 1 est rétablie avec succès si `Is Home` est `true` et le port est e0b.

+
La commande suivante affiche des informations sur les LIF des deux nœuds. L'installation du premier nœud est réussie si `Is Home` est `true` dans cet exemple, pour les deux interfaces de cluster et ils affichent les affectations de ports correctes `e0a` et `e0b` sur le noeud 1.

+
[listing, subs="+quotes"]
----
cluster::> *network interface show -vserver Cluster*

            Logical      Status     Network            Current    Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node       Port    Home
----------- ------------ ---------- ------------------ ---------- ------- -----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2      e0a     false
----
. Affichage des informations relatives aux nœuds dans un cluster : `cluster show`
+
Dans cet exemple, le nœud est associé à `node1` et `node2` dans ce cluster est `true`:

+
[listing, subs="+quotes"]
----
cluster1::> *cluster show*
Node   Health   Eligibility   Epsilon
------ -------- ------------  --------
node1  true     true          true
node2  true     true          true
----
. Vérifiez la configuration suivante du réseau du cluster :
+
`network port show`

+
[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*
Node: node1
                                                                       Ignore
                                       Speed(Mbps)            Health   Health
Port      IPspace     Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ----------- ---------------- ---- ----- ----------- -------- ------
e0a       Cluster     Cluster          up   9000  auto/10000  healthy  false
e0b       Cluster     Cluster          up   9000  auto/10000  healthy  false

Node: node2
                                                                       Ignore
                                        Speed(Mbps)           Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  healthy  false
e0b       Cluster      Cluster          up   9000 auto/10000  healthy  false


cluster1::> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
4 entries were displayed.
----
+
[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID            Local Intrfce  Hldtme Capability  Platform      Port ID
node1                Eth1/1         144    H           FAS2980       e0a
node2                Eth1/2         145    H           FAS2980       e0a
newcs2(FDO296348FU)  Eth1/65        176    R S I s     N9K-C92300YC  Eth1/65
newcs2(FDO296348FU)  Eth1/66        176    R S I s     N9K-C92300YC  Eth1/66


cs2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         139    H           FAS2980       e0b
node2              Eth1/2         124    H           FAS2980       e0b
cs1(FDO220329KU)   Eth1/65        178    R S I s     N9K-C92300YC  Eth1/65
cs1(FDO220329KU)   Eth1/66        178    R S I s     N9K-C92300YC  Eth1/66
----
. Vérifiez que le réseau de clusters fonctionne correctement :
+
`show isdp neighbors`

+
[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
S - Switch, H - Host, I - IGMP, r - Repeater
Device ID    Intf    Holdtime    Capability    Platform    Port ID
---------    ----    --------    ----------    --------    --------
node1        0/1     175         H             FAS2750     e0a
node2        0/2     152         H             FAS2750     e0a
newcs2       0/55    179         R             BES-53248   0/55
newcs2       0/56    179         R             BES-53248   0/56

(newcs2)# *show isdp neighbors*
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
S - Switch, H - Host, I - IGMP, r - Repeater

Device ID    Intf    Holdtime    Capability    Platform    Port ID
---------    ----    --------    ----------    --------    --------
node1        0/1     129         H             FAS2750     e0b
node2        0/2     165         H             FAS2750     e0b
cs1          0/55    179         R             BES-53248   0/55
cs1          0/56    179         R             BES-53248   0/56
----


Voir link:configure-log-collection.html["Configuration de la fonction de collecte du journal du commutateur de cluster"] pour connaître les étapes requises pour activer la collecte des journaux du commutateur d'intégrité du cluster, utilisée pour collecter les fichiers journaux relatifs au commutateur.

*Informations connexes*

https://mysupport.netapp.com/["Site de support NetApp"^]

https://hwu.netapp.com/["NetApp Hardware Universe"^]

link:replace-requirements.html["Configuration et configuration des commutateurs BES-53248 pris en charge par Broadcom"^]
