---
permalink: switch-bes-53248/replace-install-licenses.html 
sidebar: sidebar 
keywords: bes, cluster, switch, base, model, license, install license for bes-53428 cluster switches - bes-53428 switches 
summary: 'Le modèle de base de switch de cluster BES-53248 est disponible avec une licence pour 16 ports 10 GbE ou 25 GbE et deux ports 100 GbE. Vous pouvez ajouter de nouveaux ports en achetant d"autres licences.' 
---
= Installez les licences pour les commutateurs de cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le modèle de base de switch de cluster BES-53248 est disponible avec une licence pour 16 ports 10 GbE ou 25 GbE et deux ports 100 GbE. Vous pouvez ajouter de nouveaux ports en achetant d'autres licences.

Les licences suivantes sont disponibles pour une utilisation sur le commutateur de cluster BES-53248 :

[cols="1,2"]
|===
| Type de licence | Détails de licence 


| Version du firmware prise en charge  a| 
SW-BES-53248A1-G1-8P-LIC



 a| 
Clé de licence Broadcom 8P 10-25,2P40-100, X190005/R
 a| 
EFOS 3.4.3.3 et versions ultérieures



 a| 
SW-BES-53248A1-G1-16P-LIC
 a| 
Clé de licence Broadcom 16P 10-25,4P40-100, X190005/R



 a| 
EFOS 3.4.3.3 et versions ultérieures
 a| 
SW-BES-53248A1-G1-24P-LIC



 a| 
Clé de licence Broadcom 24P 10-25,6P40-100, X190005/R
 a| 
EFOS 3.4.3.3 et versions ultérieures



 a| 
SW-BES54248-40-100G-LIC
 a| 
Clé de licence Broadcom 6Port 40G100G, X190005/R.



 a| 
EFOS 3.4.4.6 et versions ultérieures
 a| 
SW-BES53248-8P-10G25G-LIC



 a| 
Clé de licence Broadcom 8Port 10G25G, X190005/R.
 a| 
EFOS 3.4.4.6 et versions ultérieures



 a| 
SW-BES53248-16P-1025G-LIC
 a| 
Clé de licence 10G25G 16 ports Broadcom, X190005/R.



 a| 
EFOS 3.4.4.6 et versions ultérieures
 a| 
SW-BES53248-24P-1025G-LIC



 a| 
Clé de licence 10G25G 24ports Broadcom, X190005/R.
 a| 
EFOS 3.4.4.6 et versions ultérieures

|===
.Étapes
. Connectez le commutateur de cluster au réseau de gestion.
. Utilisez le `ping` Commande pour vérifier la connectivité au serveur hébergeant EFOS, les licences et le fichier RCF.
+
Cet exemple vérifie que le commutateur est connecté au serveur à l'adresse IP 172.19.2 :

+
[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. Vérifiez l'utilisation actuelle de la licence sur le commutateur cs2 :
+
`show license`

+
[listing, subs="+quotes"]
----
(cs2)# *show license*
Reboot needed.................................. No
Number of active licenses...................... 0

License Index  License Type     Status
-------------- ---------------- -----------

No license file found.
----
. Installez le fichier de licence. L'exemple suivant utilise SFTP pour copier un fichier de licence dans un index de clé 1.
+
Répétez cette étape pour charger plus de licences et utiliser des numéros d'index de clé différents.

+
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1/var/lib/tftpboot/license.dat nvram:license-key 1*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... /var/lib/tftpboot/
Filename....................................... license.dat
Data Type...................................... license


Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...

License Key transfer operation completed successfully. System reboot is required.
----
. Afficher toutes les informations de licence en cours et noter l'état de la licence avant le redémarrage du commutateur cs2 :
+
`show license`

+
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. Yes
Number of active licenses...................... 0


License Index  License Type      Status
-------------- ----------------- -------------------------------
1              Port              License valid but not applied
----
. Afficher tous les ports sous licence :
+
`show port all | exclude Detach`

+
Les ports des fichiers de licence supplémentaires ne sont pas affichés tant que le commutateur n'a pas été redémarré.

+
[listing, subs="+quotes"]
----
(cs2)# *show port all \| exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable   Auto                  Down   Enable  Enable long
0/2              Disable   Auto                  Down   Enable  Enable long
0/3              Disable   Auto                  Down   Enable  Enable long
0/4              Disable   Auto                  Down   Enable  Enable long
0/5              Disable   Auto                  Down   Enable  Enable long
0/6              Disable   Auto                  Down   Enable  Enable long
0/7              Disable   Auto                  Down   Enable  Enable long
0/8              Disable   Auto                  Down   Enable  Enable long
0/9              Disable   Auto                  Down   Enable  Enable long
0/10             Disable   Auto                  Down   Enable  Enable long
0/11             Disable   Auto                  Down   Enable  Enable long
0/12             Disable   Auto                  Down   Enable  Enable long
0/13             Disable   Auto                  Down   Enable  Enable long
0/14             Disable   Auto                  Down   Enable  Enable long
0/15             Disable   Auto                  Down   Enable  Enable long
0/16             Disable   Auto                  Down   Enable  Enable long
0/55             Disable   Auto                  Down   Enable  Enable long
0/56             Disable   Auto                  Down   Enable  Enable long
----
. Redémarrez le commutateur :
+
`reload`

+
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .

Configuration Saved!
Are you sure you would like to reset the system? (y/n) *y*
----
. Vérifiez que la nouvelle licence est active et notez que la licence a été appliquée :
+
`show license`

+
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. No
Number of installed licenses................... 1
Total Downlink Ports enabled................... 16
Total Uplink Ports enabled..................... 8

License Index  License Type              Status
-------------- ------------------------- -----------------------------------
1              Port                      License applied
----
. Vérifier que tous les nouveaux ports sont disponibles :
+
`show port all | exclude Detach`

+
[listing, subs="+quotes"]
----
(cs2)# *show port all \| exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable    Auto                 Down   Enable  Enable long
0/2              Disable    Auto                 Down   Enable  Enable long
0/3              Disable    Auto                 Down   Enable  Enable long
0/4              Disable    Auto                 Down   Enable  Enable long
0/5              Disable    Auto                 Down   Enable  Enable long
0/6              Disable    Auto                 Down   Enable  Enable long
0/7              Disable    Auto                 Down   Enable  Enable long
0/8              Disable    Auto                 Down   Enable  Enable long
0/9              Disable    Auto                 Down   Enable  Enable long
0/10             Disable    Auto                 Down   Enable  Enable long
0/11             Disable    Auto                 Down   Enable  Enable long
0/12             Disable    Auto                 Down   Enable  Enable long
0/13             Disable    Auto                 Down   Enable  Enable long
0/14             Disable    Auto                 Down   Enable  Enable long
0/15             Disable    Auto                 Down   Enable  Enable long
0/16             Disable    Auto                 Down   Enable  Enable long
0/49             Disable   100G Full             Down   Enable  Enable long
0/50             Disable   100G Full             Down   Enable  Enable long
0/51             Disable   100G Full             Down   Enable  Enable long
0/52             Disable   100G Full             Down   Enable  Enable long
0/53             Disable   100G Full             Down   Enable  Enable long
0/54             Disable   100G Full             Down   Enable  Enable long
0/55             Disable   100G Full             Down   Enable  Enable long
0/56             Disable   100G Full             Down   Enable  Enable long
----



CAUTION: Lors de l'installation de licences supplémentaires, vous devez configurer les nouvelles interfaces manuellement. Il est déconseillé de ré-appliquer une FCR à un commutateur de production de travail existant.
