---
permalink: switch-bes-53248/replace-install-rcf.html 
sidebar: sidebar 
keywords: rcf,install rcf,bes-53248 switch 
summary: 'Vous pouvez installer la FCR après la première configuration du commutateur de cluster BES-53248 et après la première application de la ou des nouvelles licences. Si vous mettez à niveau une FCR à partir d"une ancienne version, les fichiers sont fusionnés efficacement et vous effectuez les étapes comme indiqué ici.' 
---
= Installer le fichier RCF (Reference Configuration File)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez installer la FCR après la première configuration du commutateur de cluster BES-53248 et après la première application de la ou des nouvelles licences. Si vous mettez à niveau une FCR à partir d'une version antérieure, vous devez réinitialiser les paramètres du commutateur Broadcom et effectuer une configuration de base pour appliquer à nouveau la FCR. Vous devez effectuer cette opération à chaque fois que vous souhaitez mettre à niveau ou modifier une FCR. Voir ci-dessous https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/Error!_in_configuration_script_file_at_line_number_XX_when_applying_a_new_RCF["Article de la base de connaissances"^] pour plus d'informations.



== Réinitialisez les paramètres par défaut du commutateur IP Broadcom

Avant d'installer une nouvelle version du logiciel de commutation et des RCFs, vous devez effacer les paramètres du commutateur Broadcom et effectuer une configuration de base.

.Description de la tâche
* Vous devez répéter ces étapes sur chacun des commutateurs du cluster.
* Vous devez être connecté au commutateur à l'aide de la console série.
* Cette tâche réinitialise la configuration du réseau de gestion.


.Étapes
. Passez à l'invite de commande surélevée (`#`) : `enable`
+
[listing, subs="+quotes"]
----
(cs2)> *enable*
(cs2)#
----
. Effacez la configuration de démarrage et supprimez la bannière
+
.. Effacez la configuration de démarrage :
+
*`erase startup-config`*

+
[listing, subs="+quotes"]
----
(cs2)# *erase startup-config*
Are you sure you want to clear the configuration? (y/n) *y*
(cs2)#
----
+
Cette commande n'efface pas la bannière.

.. Supprimer la bannière :
+
*`no set clibanner`*

+
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *no set clibanner*
(cs2)(Config)#
----


. Redémarrez le commutateur :*`(cs2) #reload*`
+
[listing, subs="+quotes"]
----
Are you sure you would like to reset the system? (y/n) *y*
----
+

NOTE: Si le système vous demande si vous souhaitez enregistrer la configuration non enregistrée ou modifiée avant de recharger le commutateur, sélectionnez *non*.

. Attendre que le commutateur se recharge, puis se connecter au commutateur.
+
L'utilisateur par défaut est « admin » et aucun mot de passe n'est défini. Une invite similaire à la commande suivante s'affiche :

+
[listing]
----
(Routing)>
----
. Passer à l'invite de commande surélevée :
+
`enable`

+
[listing, subs="+quotes"]
----
Routing)> *enable*
(Routing)#
----
. Définissez le protocole du port de service sur `none`:
+
`serviceport protocol none`

+
[listing, subs="+quotes"]
----
(Routing)# *serviceport protocol none*
Changing protocol mode will reset ip configuration.
Are you sure you want to continue? (y/n) *y*
(Routing) #
----
. Attribuez l'adresse IP au port de service :
+
`serviceport ip _ip-address_ _netmask_ _gateway_`

+
L'exemple suivant montre l'adresse IP 10.10.10.10 attribuée à un port de service avec le sous-réseau 255.255.255.0 et la passerelle 10.10.10.1 :

+
[listing, subs="+quotes"]
----
(Routing)# *serviceport ip 10.10.10.10 255.255.255.0 10.10.10.1*
----
. Vérifiez que le port de service est correctement configuré :
+
`show serviceport`

+
L'exemple suivant indique que le port est activé et que les adresses correctes ont été attribuées :

+
[listing, subs="+quotes"]
----
(Routing)# *show serviceport*
Interface Status............................... Up
IP Address..................................... 10.10.10.10
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 10.10.10.1
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe56:87d7/64
IPv6 Default Router............................ fe80::222:bdff:fef8:19ff
Configured IPv4 Protocol....................... None
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:56:87:D7
(Routing) #
----
. Si vous le souhaitez, configurez le serveur SSH.
+

NOTE: Le fichier RCF désactive le protocole Telnet. Si vous ne configurez pas le serveur SSH, vous pouvez uniquement accéder au pont à l'aide de la connexion du port série.

+
.. Générer des clés RSA.
+
[listing, subs="+quotes"]
----
(Routing)# *configure*
(Routing) (Config)# *crypto key generate rsa*
----
.. Générer des clés DSA (facultatif)
+
[listing, subs="+quotes"]
----
(Routing)# *configure*
(Routing) (Config)# *crypto key generate dsa*
----
.. Si vous utilisez la version conforme FIPS de EFOS, générez les clés ECDSA. L'exemple suivant crée les clés d'une longueur de 256. Les valeurs valides sont 256, 384 ou 521.
+
[listing, subs="+quotes"]
----
(Routing)# *configure*
(Routing) (Config)# *crypto key generate ecdsa 256*
----
.. Activez le serveur SSH.
+
Si nécessaire, quittez le contexte de configuration.

+
[listing, subs="+quotes"]
----
(Routing) (Config)# *end*
(Routing)# *ip ssh server enable*
----
+

NOTE: Si des clés existent déjà, il peut vous être demandé de les remplacer.



. Si vous le souhaitez, configurez le domaine et le serveur de noms :
+
`configure`

+
L'exemple suivant montre le `ip domain` et `ip name server` commandes :

+
[listing, subs="+quotes"]
----
(Routing)# *configure*
(Routing) (Config)# *ip domain name lab.netapp.com*
(Routing) (Config)# *ip name server 10.99.99.1 10.99.99.2*
(Routing) (Config)# *exit*
----
. Si vous le souhaitez, configurez le fuseau horaire et la synchronisation de l'heure (SNTP).
+
L'exemple suivant montre le `sntp` Commandes, en spécifiant l'adresse IP du serveur SNTP et le fuseau horaire relatif.

+
[listing, subs="+quotes"]
----
(Routing)# *configure*
(Routing) (Config)# *sntp client mode unicast*
(Routing) (Config)# *sntp server 10.99.99.5*
(Routing) (Config)# *clock timezone -7*
(Routing) (Config)# *exit*
----
. Configurer le nom du commutateur :
+
`hostname cs2`

+
L'invite du commutateur affiche le nouveau nom :

+
[listing, subs="+quotes"]
----
(Routing)# *hostname cs2*
----
. Enregistrez la configuration :
+
`write memory`

+
Vous recevez des invites et des valeurs de sortie similaires à l'exemple suivant :

+
[listing, subs="+quotes"]
----
(cs2)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----




== Installer le fichier RCF (Reference Configuration File)

.Étapes
. Connectez le commutateur de cluster au réseau de gestion.
. Utilisez la commande ping pour vérifier la connectivité sur le serveur hébergeant EFOS, les licences et le FCR.
+
En cas de problème de connectivité, utilisez un réseau non routé et configurez le port de service à l'aide de l'adresse IP 192.168.x ou 172.19.x. Vous pouvez reconfigurer ultérieurement le port de service à l'adresse IP de gestion de production.

+
Cet exemple vérifie que le commutateur est connecté au serveur à l'adresse IP 172.19.2 :

+
[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. Installez le RCF sur le commutateur de cluster BES-53248 à l'aide de la commande copy.
+
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://172.19.2.1/tmp/BES-53248_RCF_v1.6-Cluster-HA.txt nvram:script BES-53248_RCF_v1.6-Cluster-HA.scr*

Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... BES-53248_RCF_v1.6-Cluster-HA.txt
Data Type...................................... Config Script
Destination Filename........................... BES-53248_RCF_v1.6-Cluster-HA.scr

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...

File transfer operation completed successfully.
----
+

NOTE: Selon votre environnement, vous devrez peut-être utiliser une barre oblique double dans la commande de copie, par exemple : `+copy sftp://172.19.2.1//tmp/BES-53248_RCF_v1.6-Cluster-HA.txt nvram:script BES-53248_RCF_v1.6-Cluster-HA.scr+`.

+

NOTE: Le `.scr` l'extension doit être définie comme faisant partie du nom du fichier avant d'appeler le script. Cette extension est l'extension du système d'exploitation EFOS. Le commutateur valide automatiquement le script lorsqu'il est téléchargé sur le commutateur et la sortie est envoyée vers la console. Vous pouvez également modifier le nom du `.scr` pour l'adapter à l'écran de votre console pour faciliter la lisibilité, par exemple : `+copy sftp://172.19.2.1/tmp/BES-53248_RCF_v1.6-Cluster-HA.txt nvram:script RCF_v1.6-Cluster-HA.scr+`.

+

NOTE: Le nom de fichier ne doit pas inclure les symboles `\/:*?"<>|` la longueur maximale autorisée est de 32 caractères.

. Vérifiez que le script a été téléchargé et enregistré dans le nom de fichier que vous lui avez donné :
+
`script list`

+
[listing, subs="+quotes"]
----
(cs2)# *script list*

Configuration Script Name                  Size(Bytes)  Date of Modification
-----------------------------------------  -----------  --------------------
BES-53248_RCF_v1.6-Cluster-HA.scr          2241         2020 09 30 05:41:00

1 configuration script(s) found.
----
. Appliquez le script au commutateur.
+
`script apply`

+
[listing, subs="+quotes"]
----
(cs2)# *script apply BES-53248_RCF_v1.6-Cluster-HA.scr*

Are you sure you want to apply the configuration script? (y/n) *y*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*
Config file 'startup-config' created successfully.
Configuration Saved!

Configuration script 'BES-53248_RCF_v1.6-Cluster-HA.scr' applied.
----
. Vérifier que les ports ne correspondant à aucune licence supplémentaire une fois la FCR appliquée :
+
`show port all | exclude Detach`

+
[listing, subs="+quotes"]
----
(cs2)# *show port all \| exclude Detach*

                 Admin     Physical     Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode         Status     Status Trap    Mode   Timeout
--------- ------ --------- ------------ ---------- ------ ------- ------ -------
0/1              Enable    Auto                    Down   Enable  Enable long
0/2              Enable    Auto                    Down   Enable  Enable long
0/3              Enable    Auto                    Down   Enable  Enable long
0/4              Enable    Auto                    Down   Enable  Enable long
0/5              Enable    Auto                    Down   Enable  Enable long
0/6              Enable    Auto                    Down   Enable  Enable long
0/7              Enable    Auto                    Down   Enable  Enable long
0/8              Enable    Auto                    Down   Enable  Enable long
0/9              Enable    Auto                    Down   Enable  Enable long
0/10             Enable    Auto                    Down   Enable  Enable long
0/11             Enable    Auto                    Down   Enable  Enable long
0/12             Enable    Auto                    Down   Enable  Enable long
0/13             Enable    Auto                    Down   Enable  Enable long
0/14             Enable    Auto                    Down   Enable  Enable long
0/15             Enable    Auto                    Down   Enable  Enable long
0/16             Enable    Auto                    Down   Enable  Enable long
0/49             Enable    40G Full                Down   Enable  Enable long
0/50             Enable    40G Full                Down   Enable  Enable long
0/51             Enable    100G Full               Down   Enable  Enable long
0/52             Enable    100G Full               Down   Enable  Enable long
0/53             Enable    100G Full               Down   Enable  Enable long
0/54             Enable    100G Full               Down   Enable  Enable long
0/55             Enable    100G Full               Down   Enable  Enable long
0/56             Enable    100G Full               Down   Enable  Enable long
----
. Vérifiez sur le commutateur que vos modifications ont été effectuées :
+
`show running-config`

+
[listing, subs="+quotes"]
----
(cs2)# *show running-config*
----
. Enregistrez la configuration en cours d'exécution afin qu'elle devienne la configuration de démarrage lorsque vous redémarrez le commutateur :
+
`write memory`

+
[listing, subs="+quotes"]
----
(cs2)# *write memory*
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
. Redémarrez le commutateur et vérifiez que la configuration en cours d'exécution est correcte :
+
`reload`

+
[listing, subs="+quotes"]
----
(cs2)# *reload*

Are you sure you would like to reset the system? (y/n) *y*

System will now restart!
----



NOTE: Une fois le FCR installé sur le premier commutateur, répétez ces étapes pour installer le FCR sur le second commutateur de cluster.


CAUTION: Voir ceci link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/BES-53248_communication_issue_after_firmware%2F%2FRCF_upgrade["KO"^] Pour plus d'informations lors de l'installation d'une FCR pour MetroCluster.
