---
permalink: switch-bes-53248/required-documentation-bes53248.html 
sidebar: sidebar 
keywords: documentation requirements, BES-53248 switches,cluster switches 
summary: Vous avez besoin de la documentation spécifique relative aux commutateurs et aux contrôleurs pour configurer votre mode cluster. 
---
= Exigences en matière de documentation pour les commutateurs de cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour l'installation et la maintenance du commutateur BES-53248, assurez-vous de consulter la documentation spécifique du commutateur et du contrôleur.



== Documentation Broadcom

Pour configurer le commutateur de cluster BES-53248, vous aurez besoin des documents suivants, disponibles sur le site d'assistance de Broadcom : https://www.broadcom.com/support/bes-switch["Gamme de commutateurs Ethernet Broadcom"^]

[cols="1,2"]
|===
| Titre du document | Description 


 a| 
_Guide de l'administrateur EFOS v3.4.3_
 a| 
Fournit des exemples d'utilisation du commutateur BES-53248 dans un réseau typique.



 a| 
_Référence des commandes CLI EFOS v3.4.3_
 a| 
Décrit les commandes de l'interface de ligne de commande (CLI) que vous utilisez pour visualiser et configurer le logiciel BES-53248.



 a| 
_Guide de démarrage EFOS v3.4.3_
 a| 
Fournit des informations détaillées sur le commutateur BES-53248.



 a| 
_Guide de référence SNMP EFOS v3.4.3_
 a| 
Fournit des exemples d'utilisation du commutateur BES-53248 dans un réseau typique.



 a| 
_Paramètres et valeurs de mise à l'échelle EFOS v3.4.3_
 a| 
Décrit les paramètres de mise à l'échelle par défaut avec lesquels le logiciel EFOS est livré et validé sur les plateformes prises en charge.



 a| 
_Spécifications fonctionnelles EFOS v3.4.3_
 a| 
Décrit les spécifications du logiciel EFOS sur les plateformes prises en charge.



 a| 
_Notes de version d'EFOS v3.4.3_
 a| 
Fournit des informations spécifiques à la version du logiciel BES-53248.



 a| 
_Matrice de compatibilité entre le réseau de cluster et le réseau de gestion_
 a| 
Fournit des informations sur la compatibilité réseau.  La matrice est disponible sur le site de téléchargement du commutateur BES-53248 à l'adresse suivante : https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Commutateurs de cluster Broadcom"^] .

|===


== Documentation des systèmes ONTAP et articles de la base de connaissances

Pour configurer un système ONTAP , vous aurez besoin des documents suivants disponibles sur le site d'assistance NetApp : http://mysupport.netapp.com/["monsupport.netapp.com"^] ou le site de la base de connaissances (KB) à https://kb.netapp.com/["kb.netapp.com"^] .

[cols="1,2"]
|===
| Nom | Description 


 a| 
https://hwu.netapp.com/Home/Index["Hardware Universe NetApp"^]
 a| 
Ce document décrit les exigences en matière d'alimentation et d'installation pour tout le matériel NetApp , y compris les armoires système, et fournit des informations sur les connecteurs et les options de câbles pertinents à utiliser, ainsi que leurs références.



 a| 
Instructions d'installation et de configuration spécifiques à la manette
 a| 
Ce document décrit la procédure d'installation du matériel NetApp .



 a| 
ONTAP 9
 a| 
Fournit des informations détaillées sur tous les aspects de la version ONTAP 9.



 a| 
_Comment ajouter des licences de port supplémentaires pour le commutateur BES-53248 pris en charge par Broadcom_
 a| 
Fournit des informations détaillées sur l'ajout de licences de port.  Allez à https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_add_Additional_Port_Licensing_for_the_Broadcom-Supported_BES-53248_Switch["Article de la base de connaissances"^] .

|===