---
permalink: switch-bes-53248/required-documentation-bes53248.html 
sidebar: sidebar 
keywords: documentation requirements, BES-53248 switches,cluster switches 
summary: Vous avez besoin de documentation spécifique sur les commutateurs et le contrôleur pour configurer votre configuration Cluster-mode. 
---
= Exigences en matière de documentation pour les commutateurs de cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour l'installation et la maintenance du commutateur BES-53248, veillez à consulter la documentation spécifique du commutateur et du contrôleur.



== Documentation Broadcom

Pour configurer le commutateur de cluster BES-53248, vous devez disposer des documents suivants sur le site de support Broadcom : https://www.broadcom.com/support/bes-switch["Gamme de commutateurs Ethernet Broadcom"^]

[cols="1,2"]
|===
| Titre du document | Description 


 a| 
_EFOS Guide de l'administrateur v3.4.3_
 a| 
Fournit des exemples d'utilisation du commutateur BES-53248 dans un réseau standard.



 a| 
_EFOS CLI Command Reference v3.4.3_
 a| 
Le décrit les commandes de l'interface de ligne de commande (CLI) que vous utilisez pour afficher et configurer le logiciel BES-53248.



 a| 
_EFOS Guide de démarrage v3.4.3_
 a| 
Le fournit des informations détaillées sur le commutateur BES-53248.



 a| 
_EFOS SNMP Reference Guide v3.4.3_
 a| 
Fournit des exemples d'utilisation du commutateur BES-53248 dans un réseau standard.



 a| 
_EFOS Scaling Paramètres et valeurs v3.4.3_
 a| 
Le décrit les paramètres de mise à l'échelle par défaut avec lesquels le logiciel EFOS est fourni et validé sur les plateformes prises en charge.



 a| 
_EFOS spécifications fonctionnelles v3.4.3_
 a| 
Le décrit les spécifications du logiciel EFOS sur les plates-formes prises en charge.



 a| 
_EFOS Notes de mise à jour v3.4.3_
 a| 
Fournit des informations spécifiques à la version du logiciel BES-53248.



 a| 
_Matrice de compatibilité réseau et réseau de gestion du cluster_
 a| 
Fournit des informations sur la compatibilité réseau. La matrice est disponible sur le site de téléchargement du commutateur BES-53248 à l'adresse https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Commutateurs de cluster Broadcom"^].

|===


== Documentation sur les systèmes ONTAP et articles de la base de connaissances

Pour configurer un système ONTAP, vous devez disposer des documents suivants sur le site de support NetApp à l'adresse http://mysupport.netapp.com/["mysupport.netapp.com"^] Ou le site de la base de connaissances à l'adresse https://kb.netapp.com/["kb.netapp.com"^].

[cols="1,2"]
|===
| Nom | Description 


 a| 
https://hwu.netapp.com/Home/Index["NetApp Hardware Universe"^]
 a| 
Décrit les exigences relatives à l'alimentation et au site du matériel NetApp, notamment les armoires système, et fournit des informations sur les connecteurs et les options de câbles pertinents à utiliser avec les références correspondantes.



 a| 
Instructions d'installation et de configuration spécifiques au contrôleur_
 a| 
Décrit l'installation du matériel NetApp.



 a| 
ONTAP 9
 a| 
Fournit des informations détaillées sur tous les aspects de la version ONTAP 9.



 a| 
_Comment ajouter une licence de port supplémentaire pour le commutateur BES-53248 pris en charge par Broadcom_
 a| 
Fournit des informations détaillées sur l'ajout de licences de port. Accédez au https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_add_Additional_Port_Licensing_for_the_Broadcom-Supported_BES-53248_Switch["Article de la base de connaissances"^].

|===