---
permalink: switch-bes-53248/reset-switch-bes-53248.html 
sidebar: sidebar 
keywords: BES-53248 reset switch to factory defaults, BES-53248 switches configuration, efos 
summary: 'Réinitialisez le commutateur de cluster Broadcom BES-53248 aux paramètres d"usine en effaçant la configuration actuelle du commutateur.' 
---
= Réinitialisez le commutateur de cluster Broadcom BES-53248 aux paramètres d'usine
:allow-uri-read: 


[role="lead"]
Réinitialisez le commutateur de cluster Broadcom BES-53248 aux paramètres d'usine en effaçant la configuration actuelle du commutateur et en restaurant le commutateur à ses paramètres d'origine.

.À propos de cette tâche
* Vous devez être connecté au commutateur via la console série.
* Cette tâche réinitialise la configuration du réseau de gestion.


.Étapes
. Passez à l'invite de commandes avec privilèges élevés.
+
[listing, subs="+quotes"]
----
(cs2)> *enable*
(cs2)#
----
. Effacer la configuration de démarrage.
+
`erase startup-config`

+
[listing, subs="+quotes"]
----
(cs2)# *erase startup-config*

Are you sure you want to clear the configuration? (y/n) *y*
----
. Redémarrez le commutateur.
+
[listing, subs="+quotes"]
----
(cs2)# *reload*
Are you sure you would like to reset the system? (y/n) *y*
----



NOTE: Si le système vous demande si vous souhaitez enregistrer la configuration non enregistrée ou modifiée avant de recharger le commutateur, sélectionnez *Non*.

. [[étape 4]] Attendez que le commutateur se recharge, puis connectez-vous au commutateur.
+
L'utilisateur par défaut est « admin » et aucun mot de passe n'est défini.  Un message similaire à celui-ci s'affiche :

+
[listing]
----
(Routing)>
----

