---
permalink: switch-bes-53248/upgrade-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,upgrading EFOS software 
summary: 'Suivez ces étapes pour mettre à niveau le logiciel Ethernet Fabric OS (EFOS) sur le commutateur de cluster BES-53248.' 
---
= Mettez à jour le logiciel EFOS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez ces étapes pour mettre à niveau le logiciel EFOS sur le commutateur de cluster BES-53248.

Le logiciel EFOS comprend un ensemble de fonctionnalités et de protocoles réseau avancés pour le développement de systèmes d'infrastructure Ethernet et IP.  Cette architecture logicielle convient à tout dispositif d'organisation de réseau utilisant des applications nécessitant une inspection ou une séparation approfondie des paquets.



== Préparez-vous à la mise à niveau

.Avant de commencer
* Téléchargez le logiciel Broadcom EFOS adapté à vos commutateurs de cluster depuis le site web. https://www.broadcom.com/support/bes-switch["Prise en charge des commutateurs Ethernet Broadcom"^] site.
* Veuillez consulter les notes suivantes concernant les versions d'EFOS.


[]
====
*Notez ce qui suit :*

* Lors de la mise à niveau d'EFOS 3.4.xx vers EFOS 3.7.xx ou une version ultérieure, le commutateur doit exécuter EFOS 3.4.4.6 (ou une version 3.4.xx ultérieure).  Si vous utilisez une version antérieure, mettez d'abord à niveau le commutateur vers EFOS 3.4.4.6 (ou une version 3.4.xx ultérieure), puis mettez à niveau le commutateur vers EFOS 3.7.xx ou une version ultérieure.
* La configuration pour EFOS 3.4.xx et 3.7.xx ou versions ultérieures est différente.  Pour changer la version EFOS de 3.4.xx à 3.7.xx ou ultérieure, ou inversement, il est nécessaire de réinitialiser le commutateur aux paramètres d'usine et de (ré)appliquer les fichiers RCF de la version EFOS correspondante.  Cette procédure nécessite un accès via le port console série.
* À partir de la version 3.7.xx ou ultérieure d'EFOS, une version non conforme à la norme FIPS et une version conforme à la norme FIPS sont disponibles.  Des étapes différentes s'appliquent lors du passage d'une version non conforme à la norme FIPS à une version conforme à la norme FIPS ou vice versa.  Le passage d'une version EFOS non conforme à la norme FIPS à une version conforme à la norme FIPS, ou inversement, réinitialisera le commutateur aux paramètres d'usine.  Cette procédure nécessite un accès via le port console série.


====
|===


| *Procédure* | *Version actuelle EFOS * | *Nouvelle version EFOS* | *Étapes de haut niveau* 


 a| 
Étapes pour mettre à niveau EFOS entre deux versions (non) conformes à la norme FIPS
 a| 
3.4.x.x
 a| 
3.4.x.x
 a| 
Mettez à niveau la nouvelle image EFOS en utilisant<<Méthode 1 : Mise à niveau de l’EFOS>> .  Les informations de configuration et de licence sont conservées.



 a| 
3.4.4.6 (ou version ultérieure 3.4.xx)
 a| 
3.7.xx ou version ultérieure non conforme à la norme FIPS
 a| 
Mettre à niveau EFOS en utilisant<<Méthode 1 : Mise à niveau de l’EFOS>> .  Réinitialisez le commutateur aux paramètres d'usine et appliquez le fichier RCF pour EFOS 3.7.xx ou version ultérieure.



.2+| 3.7.xx ou version ultérieure non conforme à la norme FIPS  a| 
3.4.4.6 (ou version ultérieure 3.4.xx)
 a| 
Rétrograder EFOS en utilisant<<Méthode 1 : Mise à niveau de l’EFOS>> .  Réinitialisez le commutateur aux paramètres d'usine et appliquez le fichier RCF pour EFOS 3.4.xx



 a| 
3.7.xx ou version ultérieure non conforme à la norme FIPS
 a| 
Mettez à niveau la nouvelle image EFOS en utilisant<<Méthode 1 : Mise à niveau de l’EFOS>> .  Les informations de configuration et de licence sont conservées.



 a| 
Conforme à la norme FIPS 3.7.xx ou ultérieure
 a| 
Conforme à la norme FIPS 3.7.xx ou ultérieure
 a| 
Mettez à niveau la nouvelle image EFOS en utilisant<<Méthode 1 : Mise à niveau de l’EFOS>> .  Les informations de configuration et de licence sont conservées.



 a| 
Étapes pour effectuer une mise à niveau vers/depuis une version EFOS conforme à la norme FIPS
 a| 
Non conforme aux normes FIPS
 a| 
Conforme aux normes FIPS
 a| 
Mise à niveau de l'image EFOS à l'aide de<<Méthode 2 : Mise à niveau d’EFOS à l’aide de l’installation d’ONIE OS>> .  Les informations de configuration et de licence du commutateur seront perdues.



 a| 
Conforme aux normes FIPS
 a| 
Non conforme aux normes FIPS

|===
[IMPORTANT]
====
Pour vérifier si votre version d'EFOS est conforme ou non à la norme FIPS, utilisez le `show fips status` commande.  Dans les exemples suivants, *IP_switch_a1* utilise un EFOS conforme à la norme FIPS et *IP_switch_a2* utilise un EFOS non conforme à la norme FIPS.

* Sur le commutateur IP_switch_a1 (EFOS conforme FIPS) :
+
[listing, subs="+quotes"]
----
IP_switch_a1 # *show fips status*

System running in FIPS mode
----
* Sur le commutateur IP_switch_a2 (EFOS non conforme à la norme FIPS) :
+
[listing, subs="+quotes"]
----
IP_switch_a2 # *show fips status*
                     ^
% Invalid input detected at ^ marker.
----


====


== Mettre à jour le logiciel

Utilisez l'une des méthodes suivantes :

* <<Méthode 1 : Mise à niveau de l’EFOS>>. À utiliser dans la plupart des cas (voir le tableau ci-dessus).
* <<Méthode 2 : Mise à niveau d’EFOS à l’aide de l’installation d’ONIE OS>>. À utiliser si une version d'EFOS est conforme à la norme FIPS et l'autre version d'EFOS ne l'est pas.



NOTE: Mettez à niveau EFOS sur un commutateur à la fois pour assurer le fonctionnement continu du réseau du cluster.



=== Méthode 1 : Mise à niveau de l’EFOS

Pour mettre à jour le logiciel EFOS, procédez comme suit.


IMPORTANT: Notez qu'après la mise à niveau des commutateurs de cluster BES-53248 d'EFOS 3.3.xx ou 3.4.xx vers EFOS 3.7.0.4 ou 3.8.0.2, les liaisons inter-commutateurs (ISL) et les canaux de ports sont marqués dans l'état *Down*.  Il s'agit d'un comportement normal et vous pouvez poursuivre la mise à niveau en toute sécurité, sauf si vous rencontrez des problèmes avec la restauration automatique des LIF.  Consultez l'article de la base de connaissances : https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/BES-53248_Cluster_Switch_NDU_failed_upgrade_to_EFOS_3.7.0.4_and_later["La mise à niveau du commutateur de cluster BES-53248 vers EFOS 3.7.0.4 et versions ultérieures a échoué."^] pour plus de détails.

.Étapes
. Connectez le commutateur de cluster BES-53248 au réseau de gestion.
. Utilisez le `ping` commande permettant de vérifier la connectivité au serveur hébergeant EFOS, les licences et le fichier RCF.
+
Cet exemple vérifie que le commutateur est connecté au serveur à l'adresse IP 172.19.2.1 :

+
[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. Désactiver la restauration automatique sur les LIF du cluster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. Afficher les images de démarrage pour la configuration active et de secours :
+
`show bootvar`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

 Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup        current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.4.4.6              3.7.0.4        3.7.0.4

----
====
. Téléchargez le fichier image sur le commutateur.
+
La copie du fichier image vers l'image de sauvegarde signifie que lorsque vous redémarrez, cette image établit la version EFOS en cours d'exécution, complétant ainsi la mise à jour.

+
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk backup*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... backup

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
. Afficher les images de démarrage pour la configuration active et de secours :
+
`show bootvar`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
------------------------------------------------------------------
 unit      active      backup      current-active    next-active
------------------------------------------------------------------
    1      3.7.0.4    3.7.0.4             3.7.0.4       3.10.0.3
----
====
. Démarrez le système à partir de la configuration de sauvegarde :
+
`boot system backup`

+
[listing, subs="+quotes"]
----
(cs2)# *boot system backup*
Activating image backup ..
----
. Afficher les images de démarrage pour la configuration active et de secours :
+
`show bootvar`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
------------------------------------------------------------------
 unit      active      backup      current-active    next-active
------------------------------------------------------------------
    1    3.10.0.3    3.10.0.3            3.10.0.3       3.10.0.3
----
====
. Enregistrez la configuration en cours dans la configuration de démarrage :
+
`write memory`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *write memory*
This operation may take a few minutes.

Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
----
====
. Redémarrez le commutateur :
+
`reload`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====
. Connectez-vous à nouveau et vérifiez la nouvelle version du logiciel EFOS :
+
`show version`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. Répétez les étapes 5 à 11 sur le commutateur cs1.
. Activer la restauration automatique sur les LIF du cluster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. Vérifiez que les LIF du cluster sont revenues à leur port d'origine :
+
[source, cli]
----
network interface show -role Cluster
----
+
Pour plus de détails, voirlink:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["Rétablir le port d'origine d'une interface réseau locale (LIF)"] .





=== Méthode 2 : Mise à niveau d’EFOS à l’aide de l’installation d’ONIE OS

Vous pouvez effectuer les étapes suivantes si une version d'EFOS est conforme à la norme FIPS et l'autre version d'EFOS ne l'est pas.  Ces étapes peuvent être utilisées pour mettre à niveau l'image EFOS 3.7.xx non conforme ou conforme à la norme FIPS depuis ONIE si le commutateur ne démarre pas.


NOTE: Cette fonctionnalité est uniquement disponible pour EFOS 3.7.xx ou version ultérieure non conforme à la norme FIPS.


CAUTION: Si vous mettez à niveau EFOS en utilisant l'installation d'ONIE OS, la configuration est réinitialisée aux paramètres d'usine et les licences sont supprimées.  Vous devez configurer le commutateur et installer les licences ainsi qu'un RCF compatible pour rétablir le fonctionnement normal du commutateur.

.Étapes
. Désactiver la restauration automatique sur les LIF du cluster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. Mettez le commutateur en mode d'installation ONIE.
+
Au démarrage, sélectionnez ONIE lorsque l'invite s'affiche :

+
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
Après avoir sélectionné *ONIE*, le commutateur se charge et vous présente plusieurs choix.  Sélectionnez *Installer le système d'exploitation*.

+
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
Le commutateur démarre en mode d'installation ONIE.

. Arrêtez la découverte ONIE et configurez l'interface Ethernet.
+
Lorsque le message suivant apparaît, appuyez sur *Entrée* pour ouvrir la console ONIE :

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: La découverte d'ONIE se poursuit et des messages s'affichent sur la console.

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. Configurez l'interface Ethernet et ajoutez la route à l'aide de `ifconfig eth0 <ipAddress> netmask <netmask> up` et `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. Vérifiez que le serveur hébergeant le fichier d'installation d'ONIE est accessible :
+
`ping`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. Installez le nouveau logiciel du commutateur :
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
Le logiciel s'installe puis redémarre le commutateur.  Laissez le commutateur redémarrer normalement sur la nouvelle version EFOS.

. Vérifiez que le nouveau logiciel du commutateur est installé :
+
`show bootvar`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
   1    3.7.0.4     3.7.0.4  3.7.0.4         3.10.0.3
(cs2) #
----
====
. Terminez l'installation.  Le commutateur redémarre sans aucune configuration appliquée et se réinitialise aux paramètres d'usine.  Pour reconfigurer le commutateur, procédez comme suit :
+
.. link:configure-licenses.html["Licences d'installation"]
.. link:configure-install-rcf.html["Installez le RCF"]
.. link:configure-ssh.html["Activer SSH"]
.. link:CSHM_log_collection.html["Activer la collecte des journaux"]
.. link:CSHM_snmpv3.html["Configurer SNMPv3 pour la surveillance"]


. Répétez les étapes 2 à 8 sur le commutateur cs1.
. Activer la restauration automatique sur les LIF du cluster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. Vérifiez que les LIF du cluster sont revenues à leur port d'origine :
+
[source, cli]
----
network interface show -role Cluster
----
+
Pour plus de détails, voirlink:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["Rétablir le port d'origine d'une interface réseau locale (LIF)"] .


