---
permalink: switch-bes-53248/upgrade-switch-overview.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure new bes-53248 switch 
summary: Avant de configurer les commutateurs de cluster BES-53248, consultez un aperçu du processus et de la nomenclature. 
---
= Présentation du processus de mise à niveau des commutateurs de cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Procédez comme suit pour mettre à niveau le logiciel EFOS et les fichiers de configuration de référence (RCF) sur les commutateurs de cluster Broadcom BES-54328, le cas échéant.

. link:upgrade-efos-software.html["Mettez à niveau votre version EFOS"]
+
Téléchargez et installez le logiciel Ethernet Fabric OS (EFOS) sur le commutateur de cluster BES-53248.

. link:upgrade-rcf.html["Mettez à niveau votre version RCF"]
+
Mettez à niveau le FCR sur le commutateur de cluster BES-53248, puis vérifiez les ports pour obtenir une licence supplémentaire après l'application du FCR.

. link:replace-verify.html["Vérifiez le réseau de clusters ONTAP après la mise à niveau"]
+
Vérifiez l'état de santé du réseau de clusters ONTAP après une mise à niveau du logiciel EFOS ou du fichier RCF des commutateurs de cluster BES-53248.


