---
permalink: switch-cisco-3132q-v/cabling-considerations-3132q-v.html 
sidebar: sidebar 
keywords: 3132Q-V cabling setup, 3132Q-V switches configuration, nx-os 
summary: Examinez les considérations relatives au câblage et à la configuration des commutateurs de cluster Cisco Nexus 3132Q-V avant le déploiement. 
---
= Examinez les considérations relatives au câblage et à la configuration pour les commutateurs de cluster Cisco Nexus 3132Q-V
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Examinez les considérations relatives au câblage et à la configuration des commutateurs de cluster Cisco Nexus 3132Q-V avant le déploiement.



[[support-for-nvidia-cx6-cx6-dx-and-cx7-ethernet-ports]]
== Prise en charge des ports Ethernet NVIDIA CX6, CX6-DX et CX7

Si vous connectez un port de commutateur à un contrôleur ONTAP en utilisant des ports NIC NVIDIA ConnectX-6 (CX6), ConnectX-6 Dx (CX6-DX) ou ConnectX-7 (CX7), vous devez coder en dur la vitesse du port de commutateur.

[listing, subs="+quotes"]
----
(cs1)(config)# interface Ethernet1/19
(cs1)(config-if)# *speed 40000*
(cs1)(config-if)# no negotiate auto
(cs1)(config-if)# exit
(cs1)(config)# exit
*Save the changes:*
(cs1)# *copy running-config startup-config*
----
Reportez-vous à link:https://hwu.netapp.com/Switch/Index["Hardware Universe"^] pour plus d'informations sur les ports du commutateur. Reportez-vous à link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["De quelles informations supplémentaires ai-je besoin pour installer mon équipement qui ne figure pas dans HWU ?"^] pour plus d'informations sur les exigences d'installation du commutateur.
