---
permalink: switch-cisco-3132q-v/cn1610-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3132q-v switch, 
summary: Avant de configurer les commutateurs Cisco Nexus 3132q-v, consultez un aperçu du processus et de la nomenclature. 
---
= Exigences de migration
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Les commutateurs Cisco Nexus 3132Q-V peuvent être utilisés comme commutateurs de cluster dans votre cluster AFF ou FAS . Les commutateurs de cluster vous permettent de créer des clusters ONTAP avec plus de deux nœuds.

[NOTE]
====
La procédure nécessite l'utilisation à la fois des commandes ONTAP et des commandes des commutateurs Cisco Nexus série 3000 ; les commandes ONTAP sont utilisées sauf indication contraire.

====
Pour plus d'informations, voir :

* https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["Page de description des modèles NetApp CN1601 et CN1610"^]
* https://mysupport.netapp.com/site/info/cisco-ethernet-switch["page de description du commutateur Ethernet Cisco"^]
* http://hwu.netapp.com["Hardware Universe"^]




== Exigences CN1610

Les commutateurs de cluster suivants sont pris en charge :

* NetApp CN1610
* Cisco Nexus 3132Q-V


Les commutateurs du cluster prennent en charge les connexions de nœuds suivantes :

* NetApp CN1610 : ports 0/1 à 0/12 (10 GbE)
* Cisco Nexus 3132Q-V : ports e1/1-30 (40/100 GbE)


Les commutateurs du cluster utilisent les ports de liaison inter-commutateurs (ISL) suivants :

* NetApp CN1610 : ports 0/13 à 0/16 (10 GbE)
* Cisco Nexus 3132Q-V : ports e1/31-32 (40/100 GbE)
+
Lelink:https://hwu.netapp.com/["Hardware Universe"^] contient des informations sur le câblage pris en charge pour les commutateurs Nexus 3132Q-V :

* Les nœuds dotés de connexions de cluster 10 GbE nécessitent des câbles de dérivation à fibre optique QSFP vers SFP+ ou des câbles de dérivation en cuivre QSFP vers SFP+.
* Les nœuds dotés de connexions de cluster 40/100 GbE nécessitent des modules optiques QSFP/QSFP28 compatibles avec des câbles à fibres optiques ou des câbles à connexion directe en cuivre QSFP/QSFP28.


Le câblage ISL approprié est le suivant :

* Pour les connexions CN1610 à CN1610 (SFP+ à SFP+), quatre câbles SFP+ à fibre optique ou à connexion directe en cuivre.
* Solution provisoire : pour la connexion CN1610 vers Nexus 3132Q-V (adaptateur QSFP vers quatre SFP+), un câble adaptateur fibre optique ou cuivre QSFP vers SFP+.
* Version finale : Pour une connexion Nexus 3132Q-V à Nexus 3132Q-V (QSFP28 à QSFP28), deux câbles à fibre optique ou à connexion directe en cuivre QSFP28


Les câbles twinax NetApp ne sont pas compatibles avec les commutateurs Cisco Nexus 3132Q-V.

Si votre configuration CN1610 actuelle utilise des câbles twinax NetApp pour les connexions nœud de cluster-commutateur ou les connexions ISL et que vous souhaitez continuer à utiliser twinax dans votre environnement, vous devez vous procurer des câbles twinax Cisco .  Vous pouvez également utiliser des câbles à fibres optiques pour les connexions ISL et les connexions entre les nœuds du cluster et le commutateur.

.À propos des exemples utilisés
Les exemples de cette procédure décrivent le remplacement des commutateurs CN1610 par des commutateurs Cisco Nexus 3132Q-V.  Vous pouvez utiliser ces étapes (avec des modifications) pour d'autres commutateurs Cisco plus anciens.

La procédure utilise également la nomenclature suivante pour les commutateurs et les nœuds :

* Les résultats des commandes peuvent varier en fonction des différentes versions d' ONTAP.
* Les commutateurs CN1610 à remplacer sont *CL1* et *CL2*.
* Les commutateurs Nexus 3132Q-V destinés à remplacer les commutateurs CN1610 sont *C1* et *C2*.
* *n1_clus1* est la première interface logique de cluster (LIF) connectée au commutateur de cluster 1 (CL1 ou C1) pour le nœud *n1*.
* *n1_clus2* est le premier LIF de cluster connecté au commutateur de cluster 2 (CL2 ou C2) pour le nœud *n1*.
* *n1_clus3* est la deuxième LIF connectée au commutateur de cluster 2 (CL2 ou C2) pour le nœud *n1*.
* *n1_clus4* est la deuxième LIF connectée au commutateur de cluster 1 (CL1 ou C1) pour le nœud *n1*.
* Le nombre de ports 10 GbE et 40/100 GbE est défini dans les fichiers de configuration de référence (RCF) disponibles sur le https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Téléchargement du fichier de configuration de référence du commutateur réseau en cluster Cisco"^] page.
* Les nœuds sont *n1*, *n2*, *n3* et *n4*.


Les exemples de cette procédure utilisent quatre nœuds :

* Deux nœuds utilisent quatre ports d'interconnexion de cluster 10 GbE : *e0a*, *e0b*, *e0c* et *e0d*.
* Les deux autres nœuds utilisent deux ports d'interconnexion de cluster 40 GbE : *e4a* et *e4e*.
+
Lelink:https://hwu.netapp.com/["Hardware Universe"^] liste les ports de cluster réels sur vos plateformes.



.Quelle est la prochaine étape ?
Après avoir examiné les exigences de migration, vous pouvezlink:cn1610-prepare-to-migrate.html["Préparez-vous à migrer vos commutateurs"] .
