---
permalink: switch-cisco-3132q-v/cn1610-configure-ports.html 
sidebar: sidebar 
keywords: cisco 3132q-v, cluster switches 
summary: Vous pouvez utiliser les commutateurs Cisco Nexus 3132q-v comme commutateurs de cluster dans votre cluster AFF ou FAS . 
---
= Configurez vos ports pour la migration des commutateurs CN1610 vers les commutateurs 3132Q-V.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez ces étapes pour configurer vos ports en vue de la migration des commutateurs CN1610 vers les nouveaux commutateurs Nexus 3132Q-V.

.Étapes
. Sur tous les nœuds, retirez les câbles qui sont connectés au commutateur CN1610 CL2.
+
Avec un câblage compatible, vous devez reconnecter les ports déconnectés sur tous les nœuds au commutateur Nexus 3132Q-V C2.

. Retirez quatre câbles ISL des ports 13 à 16 du commutateur CN1610 CL1.
+
Vous devez connecter les câbles de dérivation Cisco QSFP vers SFP+ appropriés reliant le port 1/24 du nouveau commutateur Cisco 3132Q-V C2 aux ports 13 à 16 du commutateur CN1610 existant CL1.

+

NOTE: Lors du rebranchement de câbles sur le nouveau commutateur Cisco 3132Q-V, vous devez utiliser soit des câbles à fibre optique, soit des câbles twinax Cisco .

. Pour rendre l'ISL dynamique, configurez l'interface ISL 3/1 sur le commutateur CN1610 actif pour désactiver le mode statique : `no port-channel static`
+
Cette configuration correspond à la configuration ISL sur le commutateur 3132Q-V C2 lorsque les ISL sont activés sur les deux commutateurs à l'étape 11.

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant illustre la configuration de l'interface ISL 3/1 utilisant `no port-channel static` commande pour rendre l'ISL dynamique :

[listing]
----
(CL1)# configure
(CL1)(Config)# interface 3/1
(CL1)(Interface 3/1)# no port-channel static
(CL1)(Interface 3/1)# exit
(CL1)(Config)# exit
(CL1)#
----
====
. Activez les ISL 13 à 16 sur le commutateur CN1610 actif CL1.
+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant illustre le processus de mise en service des ports ISL 13 à 16 sur l'interface de canal de port 3/1 :

[listing]
----
(CL1)# configure
(CL1)(Config)# interface 0/13-0/16,3/1
(CL1)(Interface 0/13-0/16,3/1)# no shutdown
(CL1)(Interface 0/13-0/16,3/1)# exit
(CL1)(Config)# exit
(CL1)#
----
====
. Vérifiez que les ISL sont `up` sur le commutateur CN1610 CL1 :
+
`show port-channel`

+
L'« état du lien » devrait être `Up` , « Type » devrait être `Dynamic` et la colonne « Port actif » devrait être `True` pour les ports 0/13 à 0/16 :

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(CL1)# show port-channel 3/1
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port        Port
Ports  Timeout       Speed       Active
------ ------------- ----------  -------
0/13   actor/long    10 Gb Full  True
       partner/long
0/14   actor/long    10 Gb Full  True
       partner/long
0/15   actor/long    10 Gb Full  True
       partner/long
0/16   actor/long    10 Gb Full  True
       partner/long
----
====
. Vérifiez que les ISL sont `up` sur le commutateur 3132Q-V C2 :
+
`show port-channel summary`

+
.Afficher un exemple
[%collapsible]
====
Les ports Eth1/24/1 à Eth1/24/4 doivent indiquer `(P)` , ce qui signifie que les quatre ports ISL sont actifs dans le canal de ports.  Eth1/31 et Eth1/32 devraient indiquer `(D)` car ils ne sont pas connectés :

[listing]
----
C2# show port-channel summary

Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        S - Switched    R - Routed
        U - Up (port-channel)
        M - Not in use. Min-links not met
------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/31(D)   Eth1/32(D)
2     Po2(SU)     Eth      LACP      Eth1/24/1(P) Eth1/24/2(P) Eth1/24/3(P)
                                     Eth1/24/4(P)
----
====
. Activez tous les ports d'interconnexion du cluster connectés au commutateur 3132Q-V C2 sur tous les nœuds :
+
`network port modify`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre comment mettre en service les ports d'interconnexion du cluster connectés au commutateur 3132Q-V C2 :

[listing]
----
cluster::*> network port modify -node n1 -port e0b -up-admin true
cluster::*> network port modify -node n1 -port e0c -up-admin true
cluster::*> network port modify -node n2 -port e0b -up-admin true
cluster::*> network port modify -node n2 -port e0c -up-admin true
----
====
. Rétablir la configuration de toutes les interfaces logiques d'interconnexion de cluster migrées qui sont connectées à C2 sur tous les nœuds :
+
`network interface revert`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n1_clus3
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus3
----
====
. Vérifiez que tous les ports d'interconnexion du cluster sont rétablis à leurs ports d'origine :
+
`network interface show`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre que les LIF du cluster 2 sont rétablies sur leurs ports d'origine et que ce rétablissement est réussi si les ports de la colonne « Port actuel » ont l'état suivant : `true` dans la colonne « Est à la maison ».  Si la valeur de la maison est `false` , alors le LIF n'est pas annulé.

[listing]
----
cluster::*> network interface show -role cluster
       (network interface show)

         Logical    Status      Network        Current  Current  Is
Vserver  Interface  Admin/Oper  Address/Mask   Node     Port     Home
-------- ---------- ----------- -------------- -------- -------- -----
Cluster
         n1_clus1   up/up       10.10.0.1/24   n1       e0a      true
         n1_clus2   up/up       10.10.0.2/24   n1       e0b      true
         n1_clus3   up/up       10.10.0.3/24   n1       e0c      true
         n1_clus4   up/up       10.10.0.4/24   n1       e0d      true
         n2_clus1   up/up       10.10.0.5/24   n2       e0a      true
         n2_clus2   up/up       10.10.0.6/24   n2       e0b      true
         n2_clus3   up/up       10.10.0.7/24   n2       e0c      true
         n2_clus4   up/up       10.10.0.8/24   n2       e0d      true

8 entries were displayed.
----
====
. Vérifiez que tous les ports du cluster sont connectés :
+
`network port show`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant illustre le résultat de l'étape précédente `network port modify` commande, vérifiant que toutes les interconnexions du cluster sont `up` :

[listing]
----
cluster::*> network port show -role Cluster
       (network port show)

Node: n1
                Broadcast               Speed (Mbps) Health   Ignore
Port  IPspace   Domain      Link  MTU   Admin/Open   Status   Health Status
----- --------- ----------- ----- ----- ------------ -------- -------------
e0a   cluster   cluster     up    9000  auto/10000     -        -
e0b   cluster   cluster     up    9000  auto/10000     -        -
e0c   cluster   cluster     up    9000  auto/10000     -        -
e0d   cluster   cluster     up    9000  auto/10000     -        -

Node: n2
                Broadcast               Speed (Mbps) Health   Ignore
Port  IPspace   Domain      Link  MTU   Admin/Open   Status   Health Status
----- --------- ----------- ----- ----- ------------ -------- -------------
e0a   cluster   cluster     up    9000  auto/10000     -        -
e0b   cluster   cluster     up    9000  auto/10000     -        -
e0c   cluster   cluster     up    9000  auto/10000     -        -
e0d   cluster   cluster     up    9000  auto/10000     -        -

8 entries were displayed.
----
====
. Vérifiez la connectivité des interfaces du cluster distant :


[role="tabbed-block"]
====
.ONTAP 9.9.1 et versions ultérieures
--
Vous pouvez utiliser le `network interface check cluster-connectivity` commande permettant de lancer une vérification d'accessibilité pour la connectivité du cluster, puis d'afficher les détails :

`network interface check cluster-connectivity start`et `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*REMARQUE :* Veuillez patienter quelques secondes avant d’exécuter la commande « show » pour afficher les détails.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source      Destination   Packet
Node   Date                       LIF         LIF           Loss
------ -------------------------- ---------- -------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2   n1_clus1       none
       3/5/2022 19:21:20 -06:00   n1_clus2   n2_clus2       none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2   n1_clus1       none
       3/5/2022 19:21:20 -06:00   n2_clus2   n1_clus2       none
----
--
.Toutes les versions ONTAP
--
Pour toutes les versions ONTAP , vous pouvez également utiliser `cluster ping-cluster -node <name>` commande pour vérifier la connectivité :

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node n1*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1       e0a    10.10.0.1
Cluster n1_clus2 n1       e0b    10.10.0.2
Cluster n1_clus3 n1       e0c    10.10.0.3
Cluster n1_clus4 n1       e0d    10.10.0.4
Cluster n2_clus1 n2       e0a    10.10.0.5
Cluster n2_clus2 n2       e0b    10.10.0.6
Cluster n2_clus3 n2       e0c    10.10.0.7
Cluster n2_clus4 n2       e0d    10.10.0.8

Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8

Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
--
====
. [[étape 12]] Sur chaque nœud du cluster, migrez les interfaces associées au premier commutateur CN1610 CL1, à remplacer :
+
`network interface migrate`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre les ports ou LIF en cours de migration sur les nœuds n1 et n2 :

[listing]
----
cluster::*> network interface migrate -vserver Cluster -lif n1_clus1 -destination-node n1 -destination-port e0b
cluster::*> network interface migrate -vserver Cluster -lif n1_clus4 -destination-node n1 -destination-port e0c
cluster::*> network interface migrate -vserver Cluster -lif n2_clus1 -destination-node n2 -destination-port e0b
cluster::*> network interface migrate -vserver Cluster -lif n2_clus4 -destination-node n2 -destination-port e0c
----
====
. Vérifier l'état du cluster :
+
`network interface show`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre que les LIF de cluster requises ont été migrées vers les ports de cluster appropriés hébergés sur le commutateur de cluster C2 :

[listing]
----
cluster::*> network interface show -role Cluster
       (network interface show)

         Logical    Status      Network        Current  Current  Is
Vserver  Interface  Admin/Oper  Address/Mask   Node     Port     Home
-------- ---------- ----------- -------------- -------- -------- -----
Cluster
         n1_clus1   up/up       10.10.0.1/24   n1       e0b      false
         n1_clus2   up/up       10.10.0.2/24   n1       e0b      true
         n1_clus3   up/up       10.10.0.3/24   n1       e0c      true
         n1_clus4   up/up       10.10.0.4/24   n1       e0c      false
         n2_clus1   up/up       10.10.0.5/24   n2       e0b      false
         n2_clus2   up/up       10.10.0.6/24   n2       e0b      true
         n2_clus3   up/up       10.10.0.7/24   n2       e0c      true
         n2_clus4   up/up       10.10.0.8/24   n2       e0c      false

8 entries were displayed.
----
====
. Fermez les ports de nœud connectés à CL1 sur tous les nœuds :
+
`network port modify`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre comment désactiver les ports spécifiés sur les nœuds n1 et n2 :

[listing]
----
cluster::*> network port modify -node n1 -port e0a -up-admin false
cluster::*> network port modify -node n1 -port e0d -up-admin false
cluster::*> network port modify -node n2 -port e0a -up-admin false
cluster::*> network port modify -node n2 -port e0d -up-admin false
----
====
. Désactivez les ports ISL 24, 31 et 32 sur le commutateur actif 3132Q-V C2 :
+
`shutdown`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre comment désactiver les ISL 24, 31 et 32 sur le commutateur actif 3132Q-V C2 :

[listing]
----
C2# configure
C2(config)# interface ethernet 1/24/1-4
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# interface ethernet 1/31-32
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# exit
C2#
----
====
. Retirez les câbles connectés au commutateur CN1610 CL1 sur tous les nœuds.
+
Avec un câblage compatible, vous devez reconnecter les ports déconnectés sur tous les nœuds au commutateur Nexus 3132Q-V C1.

. Retirez les câbles QSFP du port e1/24 du Nexus 3132Q-V C2.
+
Vous devez connecter les ports e1/31 et e1/32 sur C1 aux ports e1/31 et e1/32 sur C2 à l'aide de câbles à fibre optique Cisco QSFP ou de câbles à connexion directe pris en charge.

. Restaurez la configuration sur le port 24 et supprimez le canal de port temporaire 2 sur C2, en copiant le `running-configuration` fichier au `startup-configuration` déposer.
+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant copie le `running-configuration` fichier au `startup-configuration` déposer:

[listing]
----
C2# configure
C2(config)# no interface breakout module 1 port 24 map 10g-4x
C2(config)# no interface port-channel 2
C2(config-if)# interface e1/24
C2(config-if)# description 40GbE Node Port
C2(config-if)# spanning-tree port type edge
C2(config-if)# spanning-tree bpduguard enable
C2(config-if)# mtu 9216
C2(config-if-range)# exit
C2(config)# exit
C2# copy running-config startup-config
[########################################] 100%
Copy Complete.
----
====
. Activez les ports ISL 31 et 32 sur C2, le commutateur 3132Q-V actif :
+
`no shutdown`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre comment activer les ISL 31 et 32 sur le commutateur 3132Q-V C2 :

[listing]
----

C2# configure
C2(config)# interface ethernet 1/31-32
C2(config-if-range)# no shutdown
C2(config-if-range)# exit
C2(config)# exit
C2# copy running-config startup-config
[########################################] 100%
Copy Complete.
----
====


.Quelle est la prochaine étape ?
Une fois vos ports de commutateur configurés, vous pouvezlink:cn1610-complete-migration.html["finalisez votre migration"] .
