---
permalink: switch-cisco-3132q-v/migrate-switchless-to-switched-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3132q-v switch, 
summary: 'Examinez les exigences de migration pour passer d"un cluster sans commutateur à deux nœuds à des commutateurs de cluster Cisco Nexus 3132Q-V.' 
---
= Passez en revue les exigences de migration pour les commutateurs de cluster Cisco Nexus 3132Q-V
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Examinez les exigences relatives à la migration d'un cluster sans commutateur à deux nœuds vers un cluster commuté à l'aide de commutateurs de cluster Cisco Nexus 3132Q-V.

[NOTE]
====
La procédure nécessite l'utilisation à la fois des commandes ONTAP et des commandes des commutateurs Cisco Nexus 3000 Series Switches ; les commandes ONTAP sont utilisées sauf indication contraire.

====
Pour plus d'informations, veuillez consulter

* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 et CN1610"^]
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Commutateur Ethernet Cisco"^]
* link:http://hwu.netapp.com["Hardware Universe"^]


.Connexions de ports et de nœuds
Assurez-vous de bien comprendre les exigences de connexion des ports et des nœuds ainsi que le câblage lorsque vous migrez vers un cluster commuté à deux nœuds avec des commutateurs de cluster Cisco Nexus 3132Q-V.

* Les commutateurs du cluster utilisent les ports de liaison inter-commutateurs (ISL) e1/31-32.
* Le link:https://hwu.netapp.com/["Hardware Universe"^] contient des informations sur le câblage pris en charge pour les commutateurs Nexus 3132Q-V :
+
** Les nœuds dotés de connexions de cluster 10 GbE nécessitent des modules optiques QSFP avec des câbles de dérivation en fibre optique ou des câbles de dérivation en cuivre QSFP vers SFP+.
** Les nœuds dotés de connexions de cluster 40 GbE nécessitent des modules optiques QSFP/QSFP28 compatibles avec des câbles à fibres optiques ou des câbles à connexion directe en cuivre QSFP/QSFP28.
** Les commutateurs du cluster utilisent le câblage ISL approprié : 2x câbles à fibre optique ou en cuivre à connexion directe QSFP28.


* Sur le Nexus 3132Q-V, vous pouvez utiliser les ports QSFP en modes Ethernet 40 Gb ou 4x10 Gb.
+
Par défaut, il y a 32 ports en mode Ethernet 40 Gb. Ces ports Ethernet 40 Gb sont numérotés selon une convention de nommage à 2 éléments. Par exemple, le deuxième port Ethernet 40 Gb est numéroté 1/2. Le processus de changement de configuration d’Ethernet 40 Gb vers Ethernet 10 Gb est appelé _breakout_ et le processus de changement de configuration d’Ethernet 10 Gb vers Ethernet 40 Gb est appelé _breakin_. Lorsque vous divisez un port Ethernet 40 Gb en ports Ethernet 10 Gb, les ports résultants sont numérotés selon une convention de nommage à 3 éléments. Par exemple, les ports issus du breakout du deuxième port Ethernet 40 Gb sont numérotés 1/2/1, 1/2/2, 1/2/3 et 1/2/4.

* Sur le côté gauche du Nexus 3132Q-V se trouve un ensemble de quatre ports SFP+ multiplexés sur le premier port QSFP.
+
Par défaut, le RCF est structuré pour utiliser le premier port QSFP.

+
Vous pouvez activer quatre ports SFP+ au lieu d’un port QSFP pour Nexus 3132Q-V à l’aide de la commande  `hardware profile front portmode sfp-plus`. De même, vous pouvez réinitialiser Nexus 3132Q-V pour utiliser un port QSFP au lieu de quatre ports SFP+ à l’aide de la commande  `hardware profile front portmode qsfp`.

* Assurez-vous d'avoir configuré certains des ports sur le Nexus 3132Q-V pour qu'ils fonctionnent à 10 GbE ou 40 GbE.
+
Vous pouvez configurer les six premiers ports en mode 4x10 GbE à l'aide de la  `interface breakout module 1 port 1-6 map 10g-4x` commande. De même, vous pouvez regrouper les six premiers ports QSFP+ de la configuration de répartition à l'aide de la  `no interface breakout module 1 port 1-6 map 10g-4x` commande.

* Le nombre de ports 10 GbE et 40 GbE est défini dans les fichiers de configuration de référence (RCF) disponibles à link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Téléchargement du fichier de configuration de référence du commutateur réseau en cluster Cisco®"^].


.Avant de commencer
* Configurations correctement mises en place et fonctionnent correctement.
* Nœuds exécutant ONTAP 9.4 ou version ultérieure.
* Tous les ports du cluster dans l'état  `up`.
* Le commutateur de cluster Cisco Nexus 3132Q-V est pris en charge.
* La configuration réseau du cluster existant comprend :
+
** L'infrastructure de cluster Nexus 3132 est redondante et pleinement fonctionnelle sur les deux commutateurs.
** Les dernières versions de RCF et NX-OS sur vos commutateurs.
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Commutateurs Ethernet Cisco"^]contient des informations sur les versions ONTAP et NX-OS prises en charge dans cette procédure.

** Connectivité de gestion sur les deux commutateurs.
** Accès console aux deux commutateurs.
** Toutes les interfaces logiques de cluster (LIF) dans l' `up`état sans avoir été migrées.
** Personnalisation initiale du commutateur.
** Tous les ports ISL sont activés et câblés.




De plus, vous devez planifier, migrer et lire la documentation requise sur la connectivité 10 GbE et 40 GbE des nœuds vers les commutateurs de cluster Nexus 3132Q-V.

.À propos des exemples utilisés
Les exemples de cette procédure utilisent la nomenclature suivante pour les commutateurs et les nœuds :

* Commutateurs de cluster Nexus 3132Q-V, C1 et C2.
* Les nœuds sont n1 et n2.


[NOTE]
====
Les exemples de cette procédure utilisent deux nœuds, chacun utilisant deux ports d'interconnexion de cluster 40 GbE *e4a* et *e4e*. La link:https://hwu.netapp.com/["Hardware Universe"^] contient des informations détaillées sur les ports de cluster de vos plateformes.

====
Cette procédure couvre les scénarios suivants :

* *n1_clus1* est la première interface logique de cluster (LIF) à être connectée au commutateur de cluster C1 pour le nœud *n1*.
* *n1_clus2* est la première LIF de cluster à être connectée au commutateur de cluster C2 pour le nœud *n1*.
* *n2_clus1* est la première interface LIF de cluster à être connectée au commutateur de cluster C1 pour le nœud *n2*.
* *n2_clus2* est la deuxième LIF de cluster à connecter à l'interconnexion de cluster C2 pour le nœud *n2*.
* Le nombre de ports 10 GbE et 40 GbE est défini dans les fichiers de configuration de référence (RCF) disponibles à link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Téléchargement du fichier de configuration de référence du commutateur réseau en cluster Cisco®"^].


[NOTE]
====
La procédure nécessite l'utilisation à la fois des commandes ONTAP et des commandes des commutateurs Cisco Nexus 3000 Series Switches ; les commandes ONTAP sont utilisées sauf indication contraire.

====
* Le cluster démarre avec deux nœuds connectés et fonctionnant dans une configuration de cluster sans commutateur à deux nœuds.
* Le premier port du cluster est déplacé vers C1.
* Le deuxième port du cluster est déplacé vers C2.
* L'option de cluster sans commutateur à deux nœuds est désactivée.


.Quelle est la prochaine étape ?
Après avoir examiné les exigences de migration, vous pouvez link:migrate-switchless-prepare-to-migrate.html["Préparez-vous à migrer vos commutateurs"].
