---
permalink: switch-cisco-3132q-v/required-documentation-3132q.html 
sidebar: sidebar 
keywords: Cisco, 3132Q-V 
summary: 'Pour l"installation et la maintenance du commutateur Cisco Nexus 3132Q-V, assurez-vous de consulter toute la documentation recommandée.' 
---
= Exigences de documentation pour les commutateurs Cisco Nexus 3132Q-V
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour l'installation et la maintenance du commutateur Cisco Nexus 3132Q-V, assurez-vous de consulter toute la documentation recommandée.



== Documentation Switch

Pour configurer les commutateurs Cisco Nexus 3132Q-V, vous aurez besoin de la documentation suivante : https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html["Prise en charge des commutateurs Cisco Nexus série 3000"^] page.

[cols="1,2"]
|===
| Titre du document | Description 


 a| 
_Guide d'installation matérielle de la série Nexus 3000_
 a| 
Fournit des informations détaillées sur les exigences du site, les caractéristiques du matériel de commutation et les options d'installation.



 a| 
_Guides de configuration logicielle des commutateurs Cisco Nexus série 3000_ (choisissez le guide correspondant à la version de NX-OS installée sur vos commutateurs)
 a| 
Fournit les informations de configuration initiale du commutateur dont vous avez besoin avant de pouvoir configurer le commutateur pour un fonctionnement ONTAP .



 a| 
_Guide de mise à niveau et de rétrogradation du logiciel NX-OS pour la série Cisco Nexus 3000_ (choisissez le guide correspondant à la version de NX-OS installée sur vos commutateurs)
 a| 
Fournit des informations sur la manière de rétrograder le commutateur vers un logiciel de commutateur compatible ONTAP , si nécessaire.



 a| 
_Index principal du guide de référence des commandes Cisco Nexus série NX-OS_
 a| 
Fournit des liens vers les différentes références de commandes fournies par Cisco.



 a| 
_Référence des MIB Cisco Nexus 3000_
 a| 
Décrit les fichiers de base d'informations de gestion (MIB) pour les commutateurs Nexus 3000.



 a| 
_Référence des messages système NX-OS série Nexus 3000_
 a| 
Décrit les messages système des commutateurs Cisco Nexus série 3000, ceux qui sont informatifs et ceux qui peuvent aider à diagnostiquer les problèmes liés aux liaisons, au matériel interne ou au logiciel système.



 a| 
_Notes de version de Cisco Nexus série 3000 NX-OS (choisissez les notes correspondant à la version de NX-OS installée sur vos commutateurs)_
 a| 
Décrit les fonctionnalités, les bugs et les limitations de la gamme Cisco Nexus 3000.



 a| 
Informations réglementaires, de conformité et de sécurité pour les gammes Cisco Nexus 6000, Cisco Nexus 5000, Cisco Nexus 3000 et Cisco Nexus 2000
 a| 
Fournit des informations sur la conformité aux normes internationales, la sécurité et les réglementations relatives aux commutateurs de la série Nexus 3000.

|===


== Documentation des systèmes ONTAP

Pour configurer un système ONTAP , vous aurez besoin des documents suivants pour votre version du système d'exploitation : https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9"^] .

[cols="1,2"]
|===
| Nom | Description 


 a| 
Instructions d'installation et de configuration spécifiques à la manette
 a| 
Ce document décrit la procédure d'installation du matériel NetApp .



 a| 
Documentation ONTAP
 a| 
Fournit des informations détaillées sur tous les aspects des versions ONTAP .



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
Fournit des informations sur la configuration et la compatibilité du matériel NetApp .

|===


== documentation du kit de rails et de l'armoire

Pour installer un commutateur Cisco 3132Q-V dans une armoire NetApp , consultez la documentation matérielle suivante.

[cols="1,2"]
|===
| Nom | Description 


 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["Armoire système 42U, guide profond"^]
 a| 
Décrit les FRU associées à l'armoire système 42U et fournit des instructions de maintenance et de remplacement des FRU.



 a| 
link:install-cisco-nexus-3132qv.html["Installer un commutateur Cisco Nexus 3132Q-V dans une armoire NetApp"^]
 a| 
Décrit comment installer un commutateur Cisco Nexus 3132Q-V dans une armoire NetApp à quatre montants.

|===