---
permalink: switch-cisco-3132q-v/reset-switch-3132q-v.html 
sidebar: sidebar 
keywords: 3132Q-V reset switch to factory defaults, 3132Q-V2 switches configuration, efos 
summary: 'Réinitialisez le commutateur de cluster Cisco Nexus 3132Q-V aux paramètres d"usine en effaçant la configuration actuelle du commutateur.' 
---
= Réinitialisez le commutateur de cluster Cisco Nexus 3132Q-V aux paramètres d'usine
:allow-uri-read: 


[role="lead"]
Réinitialisez le commutateur de cluster Cisco Nexus 3132Q-V aux paramètres d'usine par défaut en effaçant la configuration actuelle du commutateur et en restaurant le commutateur à ses paramètres d'origine.

.À propos de cette tâche
* Vous devez être connecté au commutateur via la console série.
* Cette tâche réinitialise la configuration du réseau de gestion.


.Étapes
. Effacer la configuration existante :
+
`write erase`

+
[listing, subs="+quotes"]
----
(cs2)# *write erase*

Warning: This command will erase the startup-configuration.
Do you wish to proceed anyway? (y/n) [n] *y*
----
. Recharger le logiciel du commutateur :
+
`reload`

+
[listing, subs="+quotes"]
----
(cs2)# *reload*

This command will reboot the system. (y/n)? [n] *y*
----
+
Le système redémarre et entre dans l'assistant de configuration. Pendant le démarrage, si vous recevez l'invite « Annuler le provisionnement automatique et continuer avec la configuration normale ? (oui/non)[n]”, vous devez répondre *oui* pour continuer.



.Quelle est la prochaine étape
Après avoir réinitialisé l'interrupteur, vous pouvez link:install-overview-cisco-3132qv.html["reconfigurer"] le configurer selon vos besoins.
