---
permalink: switch-cisco-3132q-v/switch-requirements.html 
sidebar: sidebar 
keywords: replace, cisco nexus 3132q-v cluster switches 
summary: Vous devez prendre en compte certaines informations de configuration, les connexions des ports et les exigences de câblage lors du remplacement des commutateurs de cluster Cisco Nexus 3132Q-V. 
---
= Exigences relatives au remplacement des commutateurs de cluster Cisco Nexus 3132Q-V
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lors du remplacement de commutateurs de cluster, assurez-vous de bien comprendre les exigences de configuration, les connexions des ports et les exigences de câblage.



== Exigences relatives au Cisco Nexus 3132Q-V

* Le commutateur de cluster Cisco Nexus 3132Q-V est pris en charge.
* Le nombre de ports 10 GbE et 40 GbE est défini dans les fichiers de configuration de référence (RCF) disponibles à l'adresse suivante :link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Téléchargement du fichier de configuration de référence du commutateur réseau en cluster Cisco"^] .
* Les commutateurs du cluster utilisent les ports de liaison inter-commutateurs (ISL) e1/31-32.
* Lelink:https://hwu.netapp.com["Hardware Universe"^] contient des informations sur le câblage pris en charge pour les commutateurs Nexus 3132Q-V :
+
** Les nœuds dotés de connexions de cluster 10 GbE nécessitent des modules optiques QSFP avec des câbles de dérivation en fibre optique ou des câbles de dérivation en cuivre QSFP vers SFP+.
** Les nœuds dotés de connexions de cluster 40 GbE nécessitent des modules optiques QSFP/QSFP28 compatibles avec des câbles à fibre optique ou des câbles à connexion directe en cuivre QSFP/QSFP28.
** Les commutateurs du cluster utilisent le câblage ISL approprié : 2 câbles à fibre optique ou en cuivre à connexion directe QSFP28.


* Sur le Nexus 3132Q-V, vous pouvez utiliser les ports QSFP en mode Ethernet 40 Gb ou en mode Ethernet 4x10 Gb.
+
Par défaut, le mode Ethernet 40 Gb comporte 32 ports.  Ces ports Ethernet 40 Gb sont numérotés selon une convention de nommage par paires.  Par exemple, le deuxième port Ethernet 40 Gb est numéroté 1/2.  Le processus de changement de configuration de 40 Gb Ethernet à 10 Gb Ethernet est appelé _breakout_ et le processus de changement de configuration de 10 Gb Ethernet à 40 Gb Ethernet est appelé _breakin_.  Lorsque vous divisez un port Ethernet 40 Gb en ports Ethernet 10 Gb, les ports résultants sont numérotés selon une convention de nommage à 3 éléments.  Par exemple, les ports de dérivation du deuxième port Ethernet 40 Gb sont numérotés 1/2/1, 1/2/2, 1/2/3 et 1/2/4.

* Sur le côté gauche du Nexus 3132Q-V se trouve un ensemble de quatre ports SFP+ multiplexés sur le premier port QSFP.
+
Par défaut, le RCF est configuré pour utiliser le premier port QSFP.

+
Vous pouvez activer quatre ports SFP+ au lieu d'un port QSFP pour le Nexus 3132Q-V en utilisant le `hardware profile front portmode sfp-plus` commande.  De même, vous pouvez réinitialiser le Nexus 3132Q-V pour utiliser un port QSFP au lieu de quatre ports SFP+ en utilisant la méthode suivante : `hardware profile front portmode qsfp` commande.

* Vous devez avoir configuré certains ports du Nexus 3132Q-V pour fonctionner à 10 GbE ou 40 GbE.
+
Vous pouvez configurer les six premiers ports en mode 4x10 GbE en utilisant le `interface breakout module 1 port 1-6 map 10g-4x` commande.  De même, vous pouvez regrouper les six premiers ports QSFP+ de la configuration de dérivation en utilisant le `no interface breakout module 1 port 1-6 map 10g-4x` commande.

* Vous devez avoir effectué la planification, la migration et lu la documentation requise sur la connectivité 10 GbE et 40 GbE des nœuds aux commutateurs de cluster Nexus 3132Q-V.
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Commutateurs Ethernet Cisco"^]contient des informations sur les versions ONTAP et NX-OS prises en charge dans cette procédure.





== Configuration requise Cisco Nexus 5596

* Les commutateurs de cluster suivants sont pris en charge :
+
** Nexus 5596
** Nexus 3132Q-V


* Le nombre de ports 10 GbE et 40 GbE est défini dans les fichiers de configuration de référence (RCF) disponibles à l'adresse suivante :link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Téléchargement du fichier de configuration de référence du commutateur réseau en cluster Cisco"^] .
* Les commutateurs du cluster utilisent les ports suivants pour les connexions aux nœuds :
+
** Ports e1/1-40 (10 GbE) : Nexus 5596
** Ports e1/1-30 (40 GbE) : Nexus 3132Q-V


* Les commutateurs du cluster utilisent les ports de liaison inter-commutateurs (ISL) suivants :
+
** Ports e1/41-48 (10 GbE) : Nexus 5596
** Ports e1/31-32 (40 GbE) : Nexus 3132Q-V


* Lelink:https://hwu.netapp.com/["Hardware Universe"^] contient des informations sur le câblage pris en charge pour les commutateurs Nexus 3132Q-V :
+
** Les nœuds dotés de connexions de cluster 10 GbE nécessitent des câbles de dérivation à fibre optique QSFP vers SFP+ ou des câbles de dérivation en cuivre QSFP vers SFP+.
** Les nœuds dotés de connexions de cluster 40 GbE nécessitent des modules optiques QSFP/QSFP28 compatibles avec des câbles à fibre optique ou des câbles à connexion directe en cuivre QSFP/QSFP28.


* Les commutateurs du cluster utilisent le câblage ISL approprié :
+
** Début : Nexus 5596 vers Nexus 5596 (SFP+ vers SFP+)
+
*** 8 câbles à connexion directe SFP+ fibre ou cuivre


** Solution provisoire : passage du Nexus 5596 au Nexus 3132Q-V (adaptateur QSFP vers 4xSFP+)
+
*** 1 câble de dérivation fibre optique ou cuivre QSFP vers SFP+


** Final : Nexus 3132Q-V vers Nexus 3132Q-V (QSFP28 vers QSFP28)
+
*** 2 câbles à connexion directe QSFP28 en fibre optique ou en cuivre




* Sur les commutateurs Nexus 3132Q-V, vous pouvez utiliser les ports QSFP/QSFP28 en mode Ethernet 40 Gigabit ou en mode Ethernet 4 x 10 Gigabit.
+
Par défaut, le mode Ethernet 40 Gigabit comporte 32 ports.  Ces ports Ethernet 40 Gigabit sont numérotés selon une convention de nommage par paires.  Par exemple, le deuxième port Ethernet 40 Gigabit est numéroté 1/2.  Le processus de changement de configuration de 40 Gigabit Ethernet à 10 Gigabit Ethernet est appelé _breakout_ et le processus de changement de configuration de 10 Gigabit Ethernet à 40 Gigabit Ethernet est appelé _breakin_.  Lorsque vous divisez un port Ethernet 40 Gigabit en ports Ethernet 10 Gigabit, les ports résultants sont numérotés selon une convention de nommage à 3 éléments.  Par exemple, les ports de dérivation du deuxième port Ethernet 40 Gigabit sont numérotés 1/2/1, 1/2/2, 1/2/3 et 1/2/4.

* Sur le côté gauche des commutateurs Nexus 3132Q-V se trouve un ensemble de 4 ports SFP+ multiplexés sur ce port QSFP28.
+
Par défaut, le RCF est configuré pour utiliser le port QSFP28.

+

NOTE: Vous pouvez activer 4 ports SFP+ au lieu d'un port QSFP pour les commutateurs Nexus 3132Q-V en utilisant le `hardware profile front portmode sfp-plus` commande.  De même, vous pouvez réinitialiser les commutateurs Nexus 3132Q-V pour utiliser un port QSFP au lieu de 4 ports SFP+ en utilisant la méthode suivante : `hardware profile front portmode qsfp` commande.

* Vous avez configuré certains ports des commutateurs Nexus 3132Q-V pour fonctionner à 10 GbE ou 40 GbE.
+

NOTE: Vous pouvez configurer les six premiers ports en mode 4x10 GbE en utilisant le `interface breakout module 1 port 1-6 map 10g-4x` commande.  De même, vous pouvez regrouper les six premiers ports QSFP+ de la configuration de dérivation en utilisant le `no interface breakout module 1 port 1-6 map 10g-4x` commande.

* Vous avez effectué la planification, la migration et lu la documentation requise sur la connectivité 10 GbE et 40 GbE des nœuds aux commutateurs de cluster Nexus 3132Q-V.
* Les versions ONTAP et NX-OS prises en charge dans cette procédure sont disponibles à l'adresse suivante :link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Commutateurs Ethernet Cisco"^] .




== Exigences relatives au NetApp CN1610

* Les commutateurs de cluster suivants sont pris en charge :
+
** NetApp CN1610
** Cisco Nexus 3132Q-V


* Les commutateurs du cluster prennent en charge les connexions de nœuds suivantes :
+
** NetApp CN1610 : ports 0/1 à 0/12 (10 GbE)
** Cisco Nexus 3132Q-V : ports e1/1-30 (40 GbE)


* Les commutateurs du cluster utilisent les ports de liaison inter-commutateurs (ISL) suivants :
+
** NetApp CN1610 : ports 0/13 à 0/16 (10 GbE)
** Cisco Nexus 3132Q-V : ports e1/31-32 (40 GbE)


* Lelink:https://hwu.netapp.com/["Hardware Universe"^] contient des informations sur le câblage pris en charge pour les commutateurs Nexus 3132Q-V :
+
** Les nœuds dotés de connexions de cluster 10 GbE nécessitent des câbles de dérivation à fibre optique QSFP vers SFP+ ou des câbles de dérivation en cuivre QSFP vers SFP+.
** Les nœuds dotés de connexions de cluster 40 GbE nécessitent des modules optiques QSFP/QSFP28 compatibles avec des câbles à fibres optiques ou des câbles à connexion directe en cuivre QSFP/QSFP28.


* Le câblage ISL approprié est le suivant :
+
** Pour les connexions CN1610 à CN1610 (SFP+ à SFP+), quatre câbles SFP+ à fibre optique ou à connexion directe en cuivre.
** Solution provisoire : pour la connexion CN1610 vers Nexus 3132Q-V (adaptateur QSFP vers quatre SFP+), un câble adaptateur fibre optique ou cuivre QSFP vers SFP+.
** Version finale : Pour une connexion Nexus 3132Q-V à Nexus 3132Q-V (QSFP28 à QSFP28), deux câbles à fibre optique ou à connexion directe en cuivre QSFP28


* Les câbles twinax NetApp ne sont pas compatibles avec les commutateurs Cisco Nexus 3132Q-V.
+
Si votre configuration CN1610 actuelle utilise des câbles twinax NetApp pour les connexions nœud de cluster-commutateur ou les connexions ISL et que vous souhaitez continuer à utiliser twinax dans votre environnement, vous devez vous procurer des câbles twinax Cisco .  Vous pouvez également utiliser des câbles à fibres optiques pour les connexions ISL et les connexions entre les nœuds du cluster et le commutateur.

* Sur les commutateurs Nexus 3132Q-V, vous pouvez utiliser les ports QSFP/QSFP28 en mode Ethernet 40 Gb ou en mode Ethernet 4x 10 Gb.
+
Par défaut, le mode Ethernet 40 Gb comporte 32 ports.  Ces ports Ethernet 40 Gb sont numérotés selon une convention de nommage par paires.  Par exemple, le deuxième port Ethernet 40 Gb est numéroté 1/2.  Le processus de changement de configuration de 40 Gb Ethernet à 10 Gb Ethernet est appelé _breakout_ et le processus de changement de configuration de 10 Gb Ethernet à 40 Gb Ethernet est appelé _breakin_.  Lorsque vous divisez un port Ethernet 40 Gb en ports Ethernet 10 Gb, les ports résultants sont numérotés selon une convention de nommage à 3 éléments.  Par exemple, les ports de dérivation du deuxième port Ethernet 40 Gb sont numérotés 1/2/1, 1/2/2, 1/2/3 et 1/2/4.

* Sur le côté gauche des commutateurs Nexus 3132Q-V se trouve un ensemble de quatre ports SFP+ multiplexés sur le premier port QSFP.
+
Par défaut, le fichier de configuration de référence (RCF) est structuré pour utiliser le premier port QSFP.

+
Vous pouvez activer quatre ports SFP+ au lieu d'un port QSFP pour les commutateurs Nexus 3132Q-V en utilisant le `hardware profile front portmode sfp-plus` commande.  De même, vous pouvez réinitialiser les commutateurs Nexus 3132Q-V pour utiliser un port QSFP au lieu de quatre ports SFP+ en utilisant la méthode suivante : `hardware profile front portmode qsfp` commande.

+

NOTE: Lorsque vous utilisez les quatre premiers ports SFP+, le premier port QSFP 40GbE sera désactivé.

* Vous devez avoir configuré certains ports des commutateurs Nexus 3132Q-V pour fonctionner à 10 GbE ou 40 GbE.
+
Vous pouvez configurer les six premiers ports en mode 4x10 GbE en utilisant le `interface breakout module 1 port 1-6 map 10g-4x` commande.  De même, vous pouvez regrouper les six premiers ports QSFP+ de la configuration _breakout_ en utilisant le `no interface breakout module 1 port 1-6 map 10g-4x` commande.

* Vous devez avoir effectué la planification, la migration et lu la documentation requise sur la connectivité 10 GbE et 40 GbE des nœuds aux commutateurs de cluster Nexus 3132Q-V.
* Les versions ONTAP et de NX-OS prises en charge par cette procédure sont répertoriées surlink:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Commutateurs Ethernet Cisco"^] .
* Les versions ONTAP et FASTPATH ​​prises en charge par cette procédure sont répertoriées surlink:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["Commutateurs NetApp CN1601 et CN1610"^] .

