---
permalink: switch-cisco-3232c-storage/install-rcf-software-3232c-storage.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 3232c 
summary: 'SSH est une exigence lors de l"utilisation des fonctionnalités de Cluster Switch Health Monitor (CSHM) et de collecte de journaux. Pour activer SSH sur les commutateurs de cluster Cisco 3232c, vous générez d’abord les clés SSH, puis vous activez SSH.' 
---
= Installez le fichier de configuration de référence (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous installez le fichier de configuration de référence (RCF) après avoir configuré les commutateurs Nexus 3232C pour la première fois.

.Avant de commencer
Vérifiez les installations et connexions suivantes :

* Une sauvegarde actuelle de la configuration du commutateur.
* Un cluster parfaitement fonctionnel (aucune erreur dans les journaux ni problème similaire).
* Le RCF actuel.
* Une connexion console au commutateur, ceci est requis lors de l'installation du RCF.


.À propos de cette tâche
La procédure nécessite l'utilisation à la fois des commandes ONTAP et des commandes des commutateurs Cisco Nexus série 3000 ; les commandes ONTAP sont utilisées sauf indication contraire.

Terminez la procédure dans link:prepare-install-cisco-nexus-3232c-storage.html["Préparez-vous à installer NX-OS et RCF"], puis suivez les étapes ci-dessous.



== Étape 1 : Installez le RCF sur les commutateurs

. Connectez-vous au commutateur s2 à l'aide de SSH ou d'une console série.
. Copiez le fichier RCF dans la mémoire bootflash du commutateur s2 en utilisant l'un des protocoles de transfert suivants : FTP, TFTP, SFTP ou SCP. Pour plus d'informations sur les commandes Cisco, consultez le guide approprié dans le https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Guide de référence des commandes NX-OS Cisco Nexus série 3000"^].
+
.Afficher un exemple
[%collapsible]
====
Cet exemple montre TFTP utilisé pour copier un RCF dans la bootflash sur le commutateur s2 :

[listing, subs="+quotes"]
----
s2# *copy tftp: bootflash: vrf management*
Enter source filename: *NX3232C-RCF-v1.13-1-Storage.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. Appliquez le RCF précédemment téléchargé à la mémoire flash de démarrage.
+
Pour plus d'informations sur les commandes Cisco , consultez le guide approprié dans le https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Guide de référence des commandes NX-OS Cisco Nexus série 3000"^] .

+
.Afficher un exemple
[%collapsible]
====
Cet exemple montre le fichier RCF `NX9336C-FX2-RCF-v1.13-1-Storage.txt` en cours d'installation sur le commutateur s2 :

[listing, subs="+quotes"]
----
s2# *copy NX9336C-FX2-RCF-v1.13-1-Storage.txt running-config echo-commands*
----
====
+
[NOTE]
====
Assurez-vous de lire attentivement les sections *Installation notes*, *Important Notes* et *banner* de votre RCF. Vous devez lire et suivre ces instructions pour vérifier la configuration et le fonctionnement corrects du switch.

====
. Examinez la sortie de la bannière à partir de `show banner motd` commande.  Vous devez lire et suivre les instructions figurant dans la section *Remarques importantes* pour assurer la configuration et le fonctionnement corrects du commutateur.
. Vérifiez que le RCF est bien la version la plus récente correcte :
+
`show running-config`

+
Lorsque vous vérifiez le résultat pour vous assurer que vous avez le RCF correct, vérifiez que les informations suivantes sont correctes :

+
** La bannière RCF
** Paramètres du nœud et du port
** Personnalisations
+
Le résultat varie en fonction de la configuration de votre site.  Vérifiez les paramètres du port et consultez les notes de version pour connaître les modifications spécifiques à la version de RCF que vous avez installée.



. Réappliquez les personnalisations précédentes à la configuration du commutateur.
. Après avoir vérifié que les versions RCF et les paramètres du commutateur sont corrects, copiez le `running-config` fichier au `startup-config` déposer.
+
`s2# copy running-config startup-config [########################################] 100% Copy complete`

. Redémarrage du commutateur s2 :
+
`s2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Répétez les étapes 1 à 8 sur le switch s1.
. Connectez les ports de stockage des nœuds et les ports des baies de stockage de tous les nœuds dans le cluster ONTAP aux commutateurs s1 et s2.




== Étape 2 : Vérifier les connexions du commutateur

. Vérifiez que les ports du commutateur sont *up*.
+
`show interface brief`

. Vérifiez que les ports de stockage du nœud et les ports du châssis de stockage se trouvent dans leurs VLAN corrects à l'aide des commandes suivantes :
+
`show vlan brief`

+
`show interface trunk`





== Étape 3 : Configurez votre cluster ONTAP

NetApp recommande d'utiliser System Manager pour configurer de nouveaux clusters.

System Manager fournit un flux de travail simple et facile pour la configuration et l'installation du cluster, y compris l'attribution d'une adresse IP de gestion de nœud, l'initialisation du cluster, la création d'un niveau local, la configuration des protocoles et l'approvisionnement du stockage initial.

Se référer à https://docs.netapp.com/us-en/ontap/task_configure_ontap.html["Configurer ONTAP sur un nouveau cluster avec System Manager"] pour les instructions d'installation.

.Quelle est la prochaine étape ?
Une fois le RCF installé, vous pouvez link:configure-ssh-keys.html["vérifier la configuration SSH"].
