---
permalink: switch-cisco-3232c-storage/smart-call-home-3232c-storage.html 
sidebar: sidebar 
keywords: cisco 3232c, storage switches 
summary: Consultez les exigences et les options de configuration de Smart Call Home pour les commutateurs de stockage Cisco Nexus 3232C. 
---
= Consultez les exigences de la fonction Smart Call Home pour les commutateurs de stockage Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Consultez les exigences de configuration de Smart Call Home sur les commutateurs de stockage Cisco Nexus 3232C pour activer les notifications par e-mail automatisées en cas d'événements système critiques.

Le service Smart Call Home de Cisco surveille les composants matériels et logiciels de votre réseau. Lorsqu'une configuration système critique se produit, il génère une notification par e-mail et déclenche une alerte à tous les destinataires configurés dans votre profil de destination.

[NOTE]
====
ONTAP prend en charge la surveillance de l'état des commutateurs Ethernet (CSHM) pour surveiller les commutateurs du cluster AFX, ainsi que la possibilité de collecter les journaux de diagnostic des commutateurs.

La fonction Smart Call Home de Cisco est une option permettant de fournir une assistance proactive et de vous aider à résoudre tout problème pouvant survenir avec les commutateurs.

====
Avant de pouvoir utiliser Smart Call Home, tenez compte des exigences suivantes :

* Un serveur de messagerie doit être installé.
* Le commutateur doit disposer d'une connectivité IP avec le serveur de messagerie.
* Les informations relatives au nom du contact (contact du serveur SNMP), au numéro de téléphone et à l'adresse postale doivent être configurées.  Cela est nécessaire pour déterminer l'origine des messages reçus.
* Un identifiant CCO doit être associé à un contrat de service Cisco SMARTnet approprié pour votre entreprise.
* Le service Cisco SMARTnet doit être installé pour que l'appareil puisse être enregistré.


Le http://www.cisco.com/c/en/us/products/switches/index.html["site d'assistance Cisco"^] Contient des informations sur les commandes permettant de configurer Smart Call Home.

La fonction Smart Call Home peut être configurée lors de l'installation et de la configuration d'un nouveau système ou ultérieurement.
