---
permalink: switch-cisco-3232c-storage/upgrade-rcf-software-3232c-storage.html 
sidebar: sidebar 
keywords: install rcf, cisco switches 
summary: Vous pouvez utiliser cette procédure pour mettre à niveau votre version RCF. 
---
= Mettez à jour votre fichier de configuration de référence (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous mettez à jour votre version RCF lorsque vous disposez d'une version existante du fichier RCF installée sur vos commutateurs opérationnels.

.Avant de commencer
Assurez-vous d'avoir les éléments suivants :

* Une sauvegarde actuelle de la configuration du commutateur.
* Un cluster parfaitement fonctionnel (aucune erreur dans les journaux ni problème similaire).
* Le RCF actuel.
* Si vous mettez à jour votre version RCF, vous avez besoin d'une configuration de démarrage dans RCF qui reflète les images de démarrage souhaitées.
+
Si vous devez modifier la configuration de démarrage pour qu'elle reflète les images de démarrage actuelles, vous devez le faire avant de réappliquer le RCF afin que la version correcte soit incluse dans les futurs redémarrages.




CAUTION: Avant d'installer une nouvelle version du logiciel du commutateur et des RCF, vous devez effacer les paramètres du commutateur et effectuer une configuration de base.  Vous devez être connecté au commutateur via la console série ou avoir conservé les informations de configuration de base avant d'effacer les paramètres du commutateur.



== Étape 1 : Préparer la mise à niveau

. Si AutoSupport est activé sur ce cluster, supprimez la création automatique de cas en envoyant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
Où _x_ représente la durée de la fenêtre de maintenance en heures.

. Passez au niveau de privilège avancé en saisissant *y* lorsque vous êtes invité à continuer :
+
`set -privilege advanced`

+
L'invite avancée (*>) apparaît.

. Affichez les ports sur chaque nœud qui sont connectés aux commutateurs :
+
[source, cli]
----
network device-discovery show
----
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID) Interface       Platform
----------- ------ ------------------------ --------------- ---------
cluster1-01/cdp
            e5a    s1                       Ethernet1/7     N3K-C3232C
            e3b    s2                       Ethernet1/7     N3K-C3232C
cluster1-02/cdp
            e5a    s1                       Ethernet1/8     N3K-C3232C
            e3b    s2                       Ethernet1/8     N3K-C3232C
.
.
----
====
. Vérifiez l'état administratif ou opérationnel de chaque port de stockage de nœud et de chaque port de baie de stockage.
+
.. Vérifiez que tous les ports de stockage du nœud sont opérationnels et ont un statut sain :
+
[source, cli]
----
storage port show -port-type ENET
----
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
cluster1-01
                   e5a ENET  -         100   enabled  online
                   e3b ENET  -         100   enabled  online
cluster1-02
                   e5a ENET  -         100   enabled  online
                   e3b ENET  -         100   enabled  online
.
.
----
====
.. Vérifiez que tous les ports de l'étagère de stockage sont opérationnels et en bon état :
+
[source, cli]
----
storage shelf port show
----
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. Vérifiez que les commutateurs sont surveillés.
+
[source, cli]
----
system switch ethernet show
----
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show*
  Switch            Type               Address          Model
  ----------------- ------------------ ---------------- ---------------
  s1                storage-network    1.2.3.4          N3K-C3232C
     Serial Number: FFFXXXXXXX1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2                storage-network    2.3.4.5          N3K-C3232C
     Serial Number: FEEXXXXXXX2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====






== Étape 2 : Mise à niveau du RCF

. Connectez-vous au commutateur s2 à l'aide de SSH ou d'une console série.
. Arrêtez les ports connectés à tous les ports des nœuds.
+
[listing, subs="+quotes"]
----
s2> *enable*
s2# *configure*
s2(config)# *interface e1/1-32*
s2(config-if-range)# *shutdown*
s2(config-if-range)# *exit*
s2(config)# *exit*
----
+

CAUTION: Assurez-vous de fermer *tous* les ports connectés pour éviter tout problème de connexion réseau. Consultez l'article de la base de connaissances https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Node_out_of_quorum_when_migrating_cluster_lif_during_switch_OS_upgrade["Nœud hors quorum lors de la migration de l'interface logique du cluster pendant la mise à niveau du système d'exploitation du commutateur"^] pour plus de détails.

. Si vous ne l'avez pas déjà fait, enregistrez une copie de la configuration actuelle du commutateur en copiant le résultat de la commande suivante dans un fichier texte :
+
`show running-config`

+
.. Enregistrez tout ajout personnalisé entre les éléments actuels `running-config` et le fichier RCF utilisé (tel qu'une configuration SNMP pour votre organisation).
.. Pour NX-OS 10.2 et versions ultérieures, utilisez le `show diff running-config` commande permettant de comparer avec le fichier RCF enregistré dans la mémoire flash de démarrage. Sinon, utilisez un outil de comparaison tiers.


. Enregistrez les détails de configuration de base dans le `write_erase.cfg` fichier sur la mémoire flash de démarrage.
+
[NOTE]
====
Assurez-vous de configurer les éléments suivants :

** Nom d'utilisateur et mot de passe
** Adresse IP de gestion
** Passerelle par défaut
** Nom du commutateur


====
+
`s2# show run | section "switchname" > bootflash:write_erase.cfg`

+
`s2# show run | section "hostname" >> bootflash:write_erase.cfg`

+
`s2# show run | i "username admin password" >> bootflash:write_erase.cfg`

+
`s2# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`s2# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

+
Consultez l'article de la base de connaissanceslink:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Comment effacer la configuration d'un commutateur d'interconnexion Cisco tout en conservant la connectivité à distance"^] pour plus de détails.

. Vérifiez que le `write_erase.cfg` Le fichier est rempli comme prévu :
+
`*show file bootflash:write_erase.cfg*`

. Émettre le `write erase` commande pour effacer la configuration enregistrée actuelle :
+
`s2# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. Copiez la configuration de base précédemment enregistrée dans la configuration de démarrage.
+
`s2# *copy bootflash:write_erase.cfg startup-config*`

. Redémarrez le commutateur :
+
`s2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Une fois l'adresse IP de gestion à nouveau accessible, connectez-vous au commutateur via SSH.
+
Vous devrez peut-être mettre à jour les entrées du fichier host relatives aux clés SSH.

. Copiez le RCF dans la bootflash du switch s2 en utilisant l'un des protocoles de transfert suivants : FTP, TFTP, SFTP ou SCP.
+
Pour plus d'informations sur les commandes Cisco, consultez le guide approprié dans le  https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html#CommandReferences["Documentation Cisco Nexus 3000 Series NX-OS"^].

+
.Afficher un exemple
[%collapsible]
====
Cet exemple montre TFTP utilisé pour copier un RCF dans la bootflash sur le commutateur s2 :

[listing, subs="+quotes"]
----
s2# *copy tftp: bootflash: vrf management*
Enter source filename: *NX3232C-RCF-v1.13-1-Storage.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. Appliquez le RCF précédemment téléchargé à la mémoire flash de démarrage.
+
Pour plus d'informations sur les commandes Cisco, consultez le guide approprié dans le https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html["Documentation Cisco Nexus 3000 Series"^].

+
Cet exemple montre le fichier RCF `NX3232C-RCF-v1.13-1-Storage.txt` en cours d'installation sur le commutateur s2 :

+
[listing, subs="+quotes"]
----
s2# *copy NX3232C-RCF-v1.13-1-Storage.txt running-config echo-commands*
----
+
[CAUTION]
====
Assurez-vous de lire attentivement les sections *Notes d'installation*, *Remarques importantes* et *bannière* de votre RCF. Vous devez lire et suivre ces instructions pour garantir la configuration et le fonctionnement corrects du commutateur.

====
. Vérifiez que le fichier RCF est bien la version la plus récente correcte :
+
`show running-config`

+
Lorsque vous vérifiez le résultat pour vous assurer que vous avez le RCF correct, vérifiez que les informations suivantes sont correctes :

+
** La bannière RCF
** Paramètres du nœud et du port
** Personnalisations
+
Le résultat varie en fonction de la configuration de votre site.  Vérifiez les paramètres du port et consultez les notes de version pour connaître les modifications spécifiques à la version de RCF que vous avez installée.



. Réappliquez les personnalisations précédentes à la configuration du commutateur.
. Après avoir vérifié que les versions RCF, les ajouts personnalisés et les paramètres des commutateurs sont corrects, copiez le `running-config` fichier au `startup-config` déposer.
+
Pour plus d'informations sur les commandes Cisco, consultez le guide approprié dans le https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html["Documentation Cisco Nexus 9000 Series"^].

+
`s2# *copy running-config startup-config*`

+
`[########################################] 100% Copy complete`

. Redémarrez le commutateur s2. Vous pouvez ignorer les alertes « `cluster switch health monitor` » et les événements « `cluster ports down` » signalés sur les nœuds pendant le redémarrage du commutateur.
+
`s2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Vérifiez l'état administratif ou opérationnel de chaque port de stockage de nœud et de chaque port de baie de stockage.
+
.. Vérifiez que tous les ports de stockage sont opérationnels et en bon état :
+
[source, cli]
----
storage port show -port-type ENET
----
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
cluster1-01
                   e5a  ENET  -          100 enabled  online
                   e3b  ENET  -          100 enabled  online
cluster1-02
                   e5a  ENET  -          100 enabled  online
                   e3b  ENET  -          100 enabled  online
.
.
----
====
.. Vérifiez que tous les ports de l'étagère de stockage sont opérationnels et en bon état :
+
[source, cli]
----
storage shelf port show
----
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. Vérifiez que les commutateurs sont surveillés :
+
[source, cli]
----
system switch ethernet show
----
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show*
  Switch           Type               Address          Model
  ---------------- ------------------ ---------------- ---------------
  s1               storage-network    1.2.3.4          N3K-C3232C
     Serial Number: FFFXXXXXXX1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2               storage-network    2.3.4.5          N3K-C3232C
     Serial Number: FEEXXXXXXX2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====


. Répétez les étapes 1 à 16 sur le commutateur s1.




== Étape 3 : Vérifier le réseau de stockage

Effectuez les étapes suivantes sur chaque commutateur de stockage pour vérifier que le réseau de stockage fonctionne correctement après la mise à niveau RCF.

. Vérifiez que les ports du commutateur sont *up*.
+
[source, cli]
----
show interface brief
----
. Vérifiez que les ports de stockage du nœud attendus sont toujours connectés :
+
[source, cli]
----
show cdp neighbors
----
. Vérifiez que les ports attendus du compartiment de stockage sont toujours connectés :
+
[source, cli]
----
show lldp neighbors
----
. Vérifiez que les ports de stockage du nœud et les ports du châssis de stockage se trouvent dans leurs VLAN corrects à l'aide des commandes suivantes :
+
[source, cli]
----
show vlan brief
----
+
[source, cli]
----
show interface trunk
----


.Quelle est la prochaine étape ?
Après avoir mis à niveau votre RCF, vous pouvezlink:configure-ssh-keys.html["vérifier la configuration SSH"] .
