---
permalink: switch-cisco-3232c-storage/upgrade-3232c-storage-switches.html 
sidebar: sidebar 
keywords: upgrade, cisco nexus, 3232c storage switch 
summary: 'Le logiciel Cisco NX-OS et les fichiers de configuration de référence (RCF) peuvent être mis à niveau sur les commutateurs de stockage Cisco Nexus 3232C.' 
---
= Mise à niveau d'un commutateur de stockage Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez ces étapes pour mettre à niveau le logiciel Cisco NX-OS et les fichiers de configuration de référence (RCF) sur les commutateurs Cisco Nexus 3232C.



== Exigences de révision

.Avant de commencer
Avant de mettre à niveau le logiciel NX-OS et les RCF sur le commutateur de stockage, assurez-vous que les conditions suivantes sont réunies :

* Le commutateur fonctionne parfaitement (il ne devrait y avoir aucune erreur dans les journaux ni aucun problème similaire).
* Vous avez vérifié ou défini vos variables de démarrage souhaitées dans le RCF pour refléter les images de démarrage souhaitées si vous installez uniquement NX-OS et conservez votre version RCF actuelle.
+
Si vous devez modifier les variables de démarrage pour refléter les images de démarrage actuelles, vous devez le faire avant de réappliquer le RCF afin que la version correcte soit instanciée lors des prochains redémarrages.

* Vous avez consulté les guides logiciels et de mise à niveau appropriés disponibles sur la link:http://www.cisco.com/en/US/products/ps9670/prod_installation_guides_list.html["Commutateurs Cisco Nexus série 3000"^] page pour obtenir une documentation complète sur les procédures de mise à niveau et de rétrogradation du stockage Cisco.
* Le nombre de ports 10 GbE et 40/100 GbE est défini dans les fichiers de configuration de référence (RCF) disponibles sur la page link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Commutateurs Ethernet Cisco"^].




== Remplacez l'interrupteur

.À propos des exemples
Les exemples de cette procédure utilisent la nomenclature suivante pour les commutateurs et les nœuds :

* Les noms des deux commutateurs de stockage sont s1 et s2.
* Les nœuds sont cluster1-01 et cluster1-02.


Les exemples de cette procédure utilisent deux nœuds : cluster1-01 avec deux ports de stockage et cluster1-02 avec deux ports de stockage. Consultez le link:https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] pour vérifier les ports de stockage corrects sur vos plateformes. Consultez link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["De quelles informations supplémentaires ai-je besoin pour installer mon équipement qui ne figure pas dans HWU ?"^] pour plus d'informations sur les exigences d'installation du commutateur.


NOTE: La procédure nécessite l'utilisation à la fois des commandes ONTAP et des commandes des commutateurs Cisco Nexus série 3000 ; les commandes ONTAP sont utilisées sauf indication contraire.  Les résultats des commandes peuvent varier en fonction des différentes versions d' ONTAP.



=== Étape 1 : Vérifier l'état de santé des commutateurs et des ports

. Si AutoSupport est activé, supprimez la création automatique de cas en envoyant un message AutoSupport :
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_ représente la durée de la fenêtre de maintenance en heures.

+

NOTE: Le message AutoSupport notifie le support technique de cette tâche de maintenance afin que la création automatique de tickets soit désactivée pendant la période de maintenance.

. Vérifiez que les commutateurs de stockage sont disponibles :
+
`system switch ethernet show`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                  Type               Address          Model
----------------------- ------------------ ---------------- ---------------
s1
                        storage-network    172.17.227.5     NX3232C
     Serial Number: FOC221206C2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(3)
    Version Source: CDP

s2
                        storage-network    172.17.227.6     NX3232C
     Serial Number: FOC220443LZ
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(3)
    Version Source: CDP

2 entries were displayed.
storage::*>
----
====
. Vérifiez que les ports du nœud sont sains et opérationnels :
+
`storage port show -port-type ENET`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ----------- ----
cluster1-01
                   e5a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
cluster1-02
                   e5a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
.
.
----
====
. Vérifiez qu'il n'y a pas de problèmes au niveau du commutateur de stockage ou du câblage :
+
`system health alert show -instance`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system health alert show -instance*
There are no entries matching your query.
----
====




=== Étape 2 : Copiez le RCF sur le commutateur Cisco s2

. Copiez le RCF sur le commutateur s2 vers la mémoire bootflash du commutateur en utilisant l'un des protocoles de transfert suivants : FTP, HTTP, TFTP, SFTP ou SCP.
+
Pour plus d'informations sur les commandes Cisco, consultez le guide approprié dans le link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Références des commandes NX-OS Cisco Nexus série 3000"^].

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre l'utilisation de HTTP pour copier un RCF dans la bootflash du switch s2 :

[listing, subs="+quotes"]
----
s2# *copy http://172.16.10.1//cfg/Nexus_3232C_RCF_v1.6-Storage.txt bootflash: vrf management*
% Total    % Received % Xferd  Average  Speed   Time    Time     Time                          Current
                               Dload    Upload  Total   Spent    Left                          Speed
  100        3254       100    3254     0       0       8175     0 --:--:-- --:--:-- --:--:-   8301
Copy complete, now saving to disk (please wait)...
Copy complete.
s2#
----
====
. Appliquez le RCF précédemment téléchargé à la mémoire flash de démarrage :
+
`copy bootflash:`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre le fichier RCF `Nexus_3232C_RCF_v1.6-Storage.txt` installé sur le commutateur s2 :

[listing, subs="+quotes"]
----
s2# *copy Nexus_3232C_RCF_v1.6-Storage.txt running-config echo-commands*
----
====
. Vérifiez que le fichier RCF est bien la version la plus récente correcte :
+
`show running-config`

+
Lorsque vous vérifiez le résultat pour vous assurer que vous avez le RCF correct, vérifiez que les informations suivantes sont correctes :

+
** La bannière RCF
** Paramètres du nœud et du port
** Personnalisations
+
Le résultat varie en fonction de la configuration de votre site.  Vérifiez les paramètres du port et consultez les notes de version pour connaître les modifications spécifiques à la version de RCF que vous avez installée.

+
[NOTE]
====
Dans la bannière générée par `show banner motd` Pour utiliser cette commande, vous devez lire et suivre les instructions de la section *REMARQUES IMPORTANTES* afin de garantir la configuration et le fonctionnement corrects du commutateur.

====
+
.Afficher un exemple
[%collapsible]
====
[listing]
----
s2# show banner motd

******************************************************************************
* NetApp Reference Configuration File (RCF)
*
* Switch   : Cisco Nexus 3232C
* Filename : Nexus_3232C_RCF_v1.6-Storage.txt
* Date     : Oct-20-2020
* Version  : v1.6
*
* Port Usage : Storage configuration
* Ports  1-32: Controller and Shelf Storage Ports
* Ports 33-34: Disabled
*
* IMPORTANT NOTES*
* - This RCF utilizes QoS and requires TCAM re-configuration, requiring RCF
*   to be loaded twice with the Storage Switch rebooted in between.
*
* - Perform the following 4 steps to ensure proper RCF installation:
*
*   (1) Apply RCF first time, expect following messages:
*       - Please save config and reload the system...
*       - Edge port type (portfast) should only be enabled on ports...
*       - TCAM region is not configured for feature QoS class IPv4 ingress...
*
*   (2) Save running-configuration and reboot Cluster Switch
*
*   (3) After reboot, apply same RCF second time and expect following messages:
*       - % Invalid command at '^' marker
*       - Syntax error while parsing...
*
*   (4) Save running-configuration again
******************************************************************************
s2#
----
====
+

NOTE: Lors de la première application du RCF, le message *ERREUR : Échec de l’écriture des commandes VSH* est normal et peut être ignoré.



. Après avoir vérifié que les versions du logiciel et les paramètres du commutateur sont corrects, copiez le  `running-config` fichier dans le  `startup-config` fichier sur le commutateur s2.
+
Pour plus d'informations sur les commandes Cisco, consultez le guide approprié dans le link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Références des commandes NX-OS Cisco Nexus série 3000"^].

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant illustre le `running-config` Le fichier a été copié avec succès vers le `startup-config` déposer:

[listing]
----
s2# copy running-config startup-config
[########################################] 100% Copy complete.
----
====




=== Étape 3 : Copiez l’image NX-OS sur le commutateur Cisco s2 et redémarrez-le

. Copiez l'image NX-OS sur le commutateur s2.
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/nxos.9.3.4.bin*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/nxos.9.3.4.bin  /bootflash/nxos.9.3.4.bin
/code/nxos.9.3.4.bin  100% 1261MB   9.3MB/s   02:15
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.

s2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/n9000-epld.9.3.4.img*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/n9000-epld.9.3.4.img  /bootflash/n9000-epld.9.3.4.img
/code/n9000-epld.9.3.4.img  100%  161MB   9.5MB/s   00:16
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.
----
====
. Installez l'image système afin que la nouvelle version soit chargée lors du prochain redémarrage du commutateur S2.
+
Le commutateur redémarrera dans 10 secondes avec la nouvelle image, comme indiqué dans la sortie suivante :

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *install all nxos bootflash:nxos.9.3.4.bin*
Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos.9.3.4.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS

Performing module support checks.
[####################] 100% -- SUCCESS

Notifying services about system upgrade.
[####################] 100% -- SUCCESS


Compatibility check is done:
Module  bootable          Impact  Install-type  Reason
------  --------  --------------  ------------  ------
     1       yes      disruptive         reset  default upgrade is not hitless


Images will be upgraded according to following table:
Module       Image                  Running-Version(pri:alt)           New-Version  Upg-Required
------  ----------  ----------------------------------------  --------------------  ------------
     1        nxos                                    9.3(3)                9.3(4)           yes
     1        bios     v08.37(01/28/2020):v08.23(09/23/2015)    v08.38(05/29/2020)            no


Switch will be reloaded for disruptive upgrade.
Do you want to continue with the installation (y/n)?  [n] *y*
input string too long
Do you want to continue with the installation (y/n)?  [n] *y*

Install is in progress, please wait.

Performing runtime checks.
[####################] 100% -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS


Finishing the upgrade, switch will reboot in 10 seconds.
s2#
----
====
. Enregistrez la configuration.
+
Pour plus d'informations sur les commandes Cisco, consultez le guide approprié dans le link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Références des commandes NX-OS Cisco Nexus série 3000"^].

+
Vous êtes invité à redémarrer le système.

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *copy running-config startup-config*
[########################################] 100% Copy complete.
s2# *reload*
This command will reboot the system. (y/n)?  [n] *y*
----
====
. Vérifiez que le nouveau numéro de version NX-OS est bien indiqué sur le commutateur :
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2020, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 08.38
 NXOS: version 9.3(4)
  BIOS compile time:  05/29/2020
  NXOS image file is: bootflash:///nxos.9.3.4.bin
  NXOS compile time:  4/28/2020 21:00:00 [04/29/2020 02:28:31]


Hardware
  cisco Nexus3000 C3232C Chassis (Nexus 9000 Series)
  Intel(R) Xeon(R) CPU E5-2403 v2 @ 1.80GHz with 8154432 kB of memory.
  Processor Board ID FOC20291J6K

  Device name: S2
  bootflash:   53298520 kB
Kernel uptime is 0 day(s), 0 hour(s), 3 minute(s), 42 second(s)

Last reset at 157524 usecs after Mon Nov  2 18:32:06 2020
  Reason: Reset due to upgrade
  System version: 9.3(3)
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):

s2#
----
====




=== Étape 4 : Revérifiez l’état de santé des commutateurs et des ports

. Vérifiez que les commutateurs de stockage sont disponibles après le redémarrage :
+
`system switch ethernet show`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
s1
                            storage-network    172.17.227.5     NX3232C
     Serial Number: FOC221206C2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(4)
    Version Source: CDP

s2
                            storage-network    172.17.227.6    NX3232C
     Serial Number: FOC220443LZ
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(4)
    Version Source: CDP
----
====
. Vérifiez que les ports du commutateur sont en bon état et opérationnels après le redémarrage :
+
`storage port show -port-type ENET`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ----------- ----
cluster1-01
                   e5a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
cluster1-02
                   e5a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
----
====
. Vérifiez qu'il n'y a pas de problèmes de commutateur de stockage ou de câblage avec le cluster :
+
`system health alert show -instance`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system health alert show -instance*
There are no entries matching your query.
----
====
. Répétez la procédure pour mettre à niveau le logiciel NX-OS et le RCF sur le switch s1.
. Si vous avez désactivé la création automatique de dossiers, réactivez-la en envoyant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.Quelle est la prochaine étape ?
Après avoir mis à jour votre switch, vous pouvez link:../switch-cshm/config-overview.html["configurer la surveillance de l'état du commutateur"].
