---
permalink: switch-netapp-cn1610/install-fastpath-rcf-831.html 
sidebar: sidebar 
keywords: fastpath, software, install, netapp cluster switches, rcfs, ontap 
summary: 'Les étapes d"installation sont les mêmes pour les commutateurs de gestion NetApp CN1601 et les commutateurs de cluster CN1610 exécutant ONTAP 8.3.1 ou une version ultérieure.  Cependant, les deux modèles nécessitent des logiciels et des RCF différents.' 
---
= Installez le logiciel FASTPATH ​​et les RCF pour ONTAP 8.3.1 et versions ultérieures.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez cette procédure pour installer le logiciel FASTPATH ​​et les RCF pour ONTAP 8.3.1 et versions ultérieures.

Les étapes d'installation sont les mêmes pour les commutateurs de gestion NetApp CN1601 et les commutateurs de cluster CN1610 exécutant ONTAP 8.3.1 ou une version ultérieure.  Cependant, les deux modèles nécessitent des logiciels et des RCF différents.



== Exigences de révision

.Avant de commencer
Assurez-vous d'avoir les éléments suivants :

* Une sauvegarde actuelle de la configuration du commutateur.
* Un cluster parfaitement fonctionnel (aucune erreur dans les journaux et aucune carte d'interface réseau (NIC) défectueuse ou problème similaire).
* Connexions de ports entièrement fonctionnelles sur le commutateur de cluster.
* Tous les ports du cluster sont configurés.
* Toutes les interfaces logiques de cluster (LIF) configurées (ne doivent pas avoir été migrées).
* Une voie de communication réussie : ONTAP (privilège : avancé) `cluster ping-cluster -node node1` La commande doit indiquer que `larger than PMTU communication` réussit sur tous les plans.
* Une version prise en charge de FASTPATH, RCF et ONTAP.
+
Assurez-vous de consulter le tableau de compatibilité des commutateurs sur le http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["Commutateurs NetApp CN1601 et CN1610"^] page répertoriant les versions FASTPATH, RCF et ONTAP prises en charge.





== Installez le logiciel FASTPATH

La procédure suivante utilise la syntaxe clusterisée de Data ONTAP 8.2.  Par conséquent, le Vserver du cluster, les noms LIF et la sortie CLI sont différents de ceux de Data ONTAP 8.3.

Il peut exister des dépendances entre la syntaxe des commandes dans les versions RCF et FASTPATH.


NOTE: Dans la version 1.2 de RCF, la prise en charge de Telnet a été explicitement désactivée pour des raisons de sécurité.  Pour éviter les problèmes de connectivité lors de l'installation de RCF 1.2, vérifiez que Secure Shell (SSH) est activé.  Le https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["Guide de l'administrateur du commutateur NetApp CN1610"^] contient plus d'informations sur SSH.

.À propos des exemples
Les exemples de cette procédure utilisent la nomenclature suivante pour les commutateurs et les nœuds :

* Les deux noms de commutateurs NetApp sont cs1 et cs2.
* Les noms des interfaces logiques du cluster (LIF) sont node1_clus1 et node1_clus2 pour le nœud 1, et node2_clus1 et node2_clus2 pour le nœud 2.  (Un cluster peut comporter jusqu'à 24 nœuds.)
* Le nom de la machine virtuelle de stockage (SVM) est Cluster.
* Le `cluster1::*>` L'invite indique le nom du cluster.
* Les ports du cluster sur chaque nœud sont nommés e0a et e0b.
+
https://hwu.netapp.com/["Hardware Universe"^]contient plus d'informations sur les ports de cluster réellement pris en charge sur votre plateforme.

* Les liaisons inter-commutateurs (ISL) prises en charge sont les ports 0/13 à 0/16.
* Les connexions de nœuds prises en charge sont les ports 0/1 à 0/12.




=== Étape 1 : Migrer le cluster

. Afficher les informations relatives aux ports réseau du cluster :
+
`network port show -_ipspace cluster_`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant illustre le type de résultat de la commande :

[listing]
----
cluster1::> network port show -ipspace cluster
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
4 entries were displayed.
----
====
. Afficher les informations relatives aux LIF du cluster :
+
`network interface show -_role cluster_`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant illustre les interfaces logiques du cluster.  Dans cet exemple, `-role` Ce paramètre affiche des informations sur les LIF associées aux ports du cluster :

[listing]
----
cluster1::> network interface show -role cluster
  (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    10.254.66.82/16    node1         e0a     true
            node1_clus2  up/up    10.254.206.128/16  node1         e0b     true
            node2_clus1  up/up    10.254.48.152/16   node2         e0a     true
            node2_clus2  up/up    10.254.42.74/16    node2         e0b     true
4 entries were displayed.
----
====
. Sur chaque nœud respectif, en utilisant un LIF de gestion de nœud, migrez node1_clus2 vers e0a sur node1 et node2_clus2 vers e0a sur node2 :
+
`network interface migrate`

+
Vous devez saisir les commandes sur les consoles de contrôle qui possèdent les LIF de cluster respectives.

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
cluster1::> network interface migrate -vserver Cluster -lif node1_clus2 -destination-node node1 -destination-port e0a
cluster1::> network interface migrate -vserver Cluster -lif node2_clus2 -destination-node node2 -destination-port e0a
----
====
+

NOTE: Pour cette commande, le nom du cluster est sensible à la casse et la commande doit être exécutée sur chaque nœud.  Il n'est pas possible d'exécuter cette commande dans le LIF du cluster général.

. Vérifiez que la migration a bien eu lieu en utilisant le `network interface show` commande sur un nœud.
+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre que clus2 a migré vers le port e0a sur les nœuds node1 et node2 :

[listing]
----
cluster1::> **network interface show -role cluster**
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    10.254.66.82/16   node1          e0a     true
            node1_clus2  up/up    10.254.206.128/16 node1          e0a     false
            node2_clus1  up/up    10.254.48.152/16  node2          e0a     true
            node2_clus2  up/up    10.254.42.74/16   node2          e0a     false
4 entries were displayed.
----
====
. Passez au niveau de privilège avancé en saisissant « y » lorsque vous êtes invité à continuer :
+
`set -privilege advanced`

+
L'invite avancée (*>) apparaît.

. Fermez le port e0b du cluster sur les deux nœuds :
+
`network port modify -node _node_name_ -port _port_name_ -up-admin false`

+
Vous devez saisir les commandes sur les consoles de contrôle qui possèdent les LIF de cluster respectives.

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre les commandes permettant de désactiver le port e0b sur tous les nœuds :

[listing]
----
cluster1::*> network port modify -node node1 -port e0b -up-admin false
cluster1::*> network port modify -node node2 -port e0b -up-admin false
----
====
. Vérifiez que le port e0b est fermé sur les deux nœuds :
+
`network port show`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
cluster1::*> network port show -role cluster

                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          down     9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          down     9000  auto/10000
4 entries were displayed.
----
====
. Fermez les ports de liaison inter-commutateurs (ISL) sur cs1.
+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs1) #configure
(cs1) (Config)#interface 0/13-0/16
(cs1) (Interface 0/13-0/16)#shutdown
(cs1) (Interface 0/13-0/16)#exit
(cs1) (Config)#exit
----
====
. Sauvegardez l'image active actuelle sur cs2.
+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

 Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     1.1.0.5     1.1.0.3            1.1.0.5            1.1.0.5

(cs2) # copy active backup
Copying active to backup
Copy operation successful
----
====




=== Étape 2 : Installez le logiciel FASTPATH et RCF.

. Vérifiez la version du logiciel FASTPATH en cours d'exécution.
+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description............................. NetApp CN1610, 1.1.0.5, Linux
                                                2.6.21.7
Machine Type................................... NetApp CN1610
Machine Model.................................. CN1610
Serial Number.................................. 20211200106
Burned In MAC Address.......................... 00:A0:98:21:83:69
Software Version............................... 1.1.0.5
Operating System............................... Linux 2.6.21.7
Network Processing Device...................... BCM56820_B0
Part Number.................................... 111-00893

--More-- or (q)uit


Additional Packages............................ FASTPATH QOS
                                                FASTPATH IPv6 Management
----
====
. Téléchargez le fichier image sur le commutateur.
+
Copier le fichier image dans l'image active signifie qu'au redémarrage, cette image établira la version FASTPATH en cours d'exécution.  L'image précédente reste disponible à titre de sauvegarde.

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) #copy sftp://root@10.22.201.50//tftpboot/NetApp_CN1610_1.2.0.7.stk active
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 10.22.201.50
Path........................................... /tftpboot/
Filename....................................... NetApp_CN1610_1.2.0.7.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
SFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. Veuillez confirmer les versions actuelles et futures des images de démarrage :
+
`show bootvar`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) #show bootvar

Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     1.1.0.8     1.1.0.8            1.1.0.8            1.2.0.7
----
====
. Installez le fichier RCF compatible avec la nouvelle version d'image sur le commutateur.
+
Si la version RCF est déjà correcte, ouvrez les ports ISL.

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) #copy tftp://10.22.201.50//CN1610_CS_RCF_v1.2.txt nvram:script CN1610_CS_RCF_v1.2.scr

Mode........................................... TFTP
Set Server IP.................................. 10.22.201.50
Path........................................... /
Filename....................................... CN1610_CS_RCF_v1.2.txt
Data Type...................................... Config Script
Destination Filename........................... CN1610_CS_RCF_v1.2.scr

File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.


Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y


Validating configuration script...
[the script is now displayed line by line]

Configuration script validated.
File transfer operation completed successfully.
----
====
+

NOTE: Le `.scr` L'extension doit être définie dans le nom du fichier avant d'exécuter le script.  Cette extension est destinée au système d'exploitation FASTPATH.

+
Le commutateur valide automatiquement le script lors de son téléchargement.  Le résultat s'affiche sur la console.

. Vérifiez que le script a bien été téléchargé et enregistré sous le nom de fichier que vous lui avez indiqué.
+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) #script list

Configuration Script Name        Size(Bytes)
-------------------------------- -----------
CN1610_CS_RCF_v1.2.scr                  2191

1 configuration script(s) found.
2541 Kbytes free.
----
====
. Appliquez le script à l'interrupteur.
+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) #script apply CN1610_CS_RCF_v1.2.scr

Are you sure you want to apply the configuration script? (y/n) y
[the script is now displayed line by line]...

Configuration script 'CN1610_CS_RCF_v1.2.scr' applied.
----
====
. Vérifiez que les modifications ont bien été appliquées au commutateur, puis enregistrez-les :
+
`show running-config`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) #show running-config
----
====
. Enregistrez la configuration en cours afin qu'elle devienne la configuration de démarrage lors du redémarrage du commutateur.
+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) #write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. Redémarrez le commutateur.
+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) #reload

The system has unsaved changes.
Would you like to save them now? (y/n) y

Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====




=== Étape 3 : Valider l’installation

. Connectez-vous à nouveau, puis vérifiez que le commutateur exécute bien la nouvelle version du logiciel FASTPATH.
+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) #show version

Switch: 1

System Description............................. NetApp CN1610, 1.2.0.7,Linux
                                                3.8.13-4ce360e8
Machine Type................................... NetApp CN1610
Machine Model.................................. CN1610
Serial Number.................................. 20211200106
Burned In MAC Address.......................... 00:A0:98:21:83:69
Software Version............................... 1.2.0.7
Operating System............................... Linux 3.8.13-4ce360e8
Network Processing Device...................... BCM56820_B0
Part Number.................................... 111-00893
CPLD version................................... 0x5


Additional Packages............................ FASTPATH QOS
                                                FASTPATH IPv6 Management
----
====
+
Une fois le redémarrage terminé, vous devez vous connecter pour vérifier la version de l'image, consulter la configuration en cours et rechercher la description sur l'interface 3/64, qui est l'étiquette de version pour le RCF.

. Activez les ports ISL sur cs1, le commutateur actif.
+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs1) #configure
(cs1) (Config) #interface 0/13-0/16
(cs1) (Interface 0/13-0/16) #no shutdown
(cs1) (Interface 0/13-0/16) #exit
(cs1) (Config) #exit
----
====
. Vérifiez que les ISL sont opérationnels :
+
`show port-channel 3/1`

+
Le champ État du lien doit indiquer `Up` .

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs1) #show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  False
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. Activez le port de cluster e0b sur tous les nœuds :
+
`network port modify`

+
Vous devez saisir les commandes sur les consoles de contrôle qui possèdent les LIF de cluster respectives.

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre l'activation du port e0b sur les nœuds node1 et node2 :

[listing]
----
cluster1::*> network port modify -node node1 -port e0b -up-admin true
cluster1::*> network port modify -node node2 -port e0b -up-admin true
----
====
. Vérifiez que le port e0b est actif sur tous les nœuds :
+
`network port show -ipspace cluster`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
cluster1::*> network port show -ipspace cluster

                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
4 entries were displayed.
----
====
. Vérifiez que le LIF est maintenant à la maison(`true` ) sur les deux nœuds :
+
`network interface show -_role cluster_`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
cluster1::*> network interface show -role cluster

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.66.82/16   node1         e0a     true
            node1_clus2  up/up    169.254.206.128/16 node1         e0b     true
            node2_clus1  up/up    169.254.48.152/16  node2         e0a     true
            node2_clus2  up/up    169.254.42.74/16   node2         e0b     true
4 entries were displayed.
----
====
. Afficher l'état des membres du nœud :
+
`cluster show`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
cluster1::*> cluster show

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
====
. Retour au niveau de privilège d'administrateur :
+
`set -privilege admin`

. Répétez les étapes précédentes pour installer le logiciel FASTPATH et RCF sur l'autre commutateur, cs1.

