---
permalink: switch-netapp-cn1610/install-fastpath-software.html 
sidebar: sidebar 
keywords: install, fastpath, software 
summary: Lorsque vous installez le logiciel FASTPATH ​​sur vos commutateurs NetApp , vous devez commencer la mise à niveau par le deuxième commutateur, cs2. 
---
= Installez le logiciel FASTPATH
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous installez le logiciel FASTPATH ​​sur vos commutateurs NetApp , vous devez commencer la mise à niveau par le deuxième commutateur, _cs2_.



== Exigences de révision

.Avant de commencer
Assurez-vous d'avoir les éléments suivants :

* Une sauvegarde actuelle de la configuration du commutateur.
* Un cluster parfaitement fonctionnel (aucune erreur dans les journaux et aucune carte d'interface réseau (NIC) défectueuse ou problème similaire).
* Connexions de ports entièrement fonctionnelles sur le commutateur de cluster.
* Tous les ports du cluster sont configurés.
* Toutes les interfaces logiques de cluster (LIF) configurées (ne doivent pas avoir été migrées).
* Une voie de communication réussie : ONTAP (privilège : avancé) `cluster ping-cluster -node node1` La commande doit indiquer que `larger than PMTU communication` réussit sur tous les plans.
* Une version prise en charge de FASTPATH ​​et ONTAP.
+
Assurez-vous de consulter le tableau de compatibilité des commutateurs sur le http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["Commutateurs NetApp CN1601 et CN1610"^] page répertoriant les versions FASTPATH ​​et ONTAP prises en charge.





== Installer FASTPATH

La procédure suivante utilise la syntaxe clusterisée de Data ONTAP 8.2.  Par conséquent, le Vserver du cluster, les noms LIF et la sortie CLI sont différents de ceux de Data ONTAP 8.3.

Il peut exister des dépendances entre la syntaxe des commandes dans les versions RCF et FASTPATH.

.À propos des exemples
Les exemples de cette procédure utilisent la nomenclature suivante pour les commutateurs et les nœuds :

* Les deux commutateurs NetApp sont cs1 et cs2.
* Les deux LIF de cluster sont clus1 et clus2.
* Les serveurs virtuels sont vs1 et vs2.
* Le `cluster::*>` L'invite indique le nom du cluster.
* Les ports du cluster sur chaque nœud sont nommés e1a et e2a.
+
https://hwu.netapp.com/["Hardware Universe"^]contient plus d'informations sur les ports de cluster réellement pris en charge sur votre plateforme.

* Les liaisons inter-commutateurs (ISL) prises en charge sont les ports 0/13 à 0/16.
* Les connexions de nœuds prises en charge sont les ports 0/1 à 0/12.




=== Étape 1 : Migrer le cluster

. Si AutoSupport est activé sur ce cluster, supprimez la création automatique de cas en envoyant un message AutoSupport :
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ représente la durée de la fenêtre de maintenance en heures.

+

NOTE: Le message AutoSupport notifie le support technique de cette tâche de maintenance afin que la création automatique de tickets soit désactivée pendant la période de maintenance.

. Connectez-vous au commutateur en tant qu'administrateur.  Il n'y a pas de mot de passe par défaut.  À `(cs2) #` invite, entrez le `enable` commande.  Là encore, il n'y a pas de mot de passe par défaut.  Cela vous donne accès au mode EXEC privilégié, qui vous permet de configurer l'interface réseau.
+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) # enable
Password (Enter)
(cs2) #
----
====
. Sur la console de chaque nœud, migrez clus2 vers le port e1a :
+
`network interface migrate`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -destnode node1 -dest-port e1a
cluster::*> network interface migrate -vserver vs2 -lif clus2 -destnode node2 -dest-port e1a
----
====
. Sur la console de chaque nœud, vérifiez que la migration a bien eu lieu :
+
`network interface show`

+
L'exemple suivant montre que clus2 a migré vers le port e1a sur les deux nœuds :

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

         Logical    Status     Network        Current  Current  Is
Vserver  Interface  Admin/Open Address/Mask   Node     Port     Home
-------- ---------- ---------- -------------- -------- -------  ----
vs1
         clus1      up/up      10.10.10.1/16  node1    e1a      true
         clus2      up/up      10.10.10.2/16  node1    e1a      false
vs2
         clus1      up/up      10.10.10.1/16  node2    e1a      true
         clus2      up/up      10.10.10.2/16  node2    e1a      false
----
====




=== Étape 2 : Installer le logiciel FASTPATH

. Fermez le port e2a du cluster sur les deux nœuds :
+
`network port modify`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre la fermeture du port e2a sur les deux nœuds :

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. Vérifiez que le port e2a est fermé sur les deux nœuds :
+
`network port show`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                 Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU    Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- -----  ----------  ----------  ------------
node1
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
----
====
. Désactivez les ports de liaison inter-commutateurs (ISL) sur cs1, le commutateur NetApp actif :
+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1)(config) # interface 0/13-0/16
(cs1)(Interface 0/13-0/16) # shutdown
(cs1)(Interface 0/13-0/16) # exit
(cs1)(config) # exit
----
====
. Sauvegardez l'image active actuelle sur cs2.
+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

 Image Descriptions   .

  active:
  backup:

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.1          1.1.0.3           1.1.0.3

(cs2) # copy active backup
Copying active to backup
Copy operation successful

(cs2) #
----
====
. Téléchargez le fichier image sur le commutateur.
+
Copier le fichier image dans l'image active signifie qu'au redémarrage, cette image établira la version FASTPATH en cours d'exécution.  L'image précédente reste disponible à titre de sauvegarde.

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.0.0.1/NetApp_CN1610_1.1.0.5.stk active


Mode...................................... TFTP
Set Server IP............................. 10.0.0.1
Path...................................... ./
Filename.................................. NetApp_CN1610_1.1.0.5.stk
Data Type................................. Code
Destination Filename...................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
TFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. Vérifiez la version du logiciel FASTPATH en cours d'exécution.
+
`show version`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description.................. Broadcom Scorpion 56820
                                     Development System - 16 TENGIG,
                                     1.1.0.3, Linux 2.6.21.7
Machine Type........................ Broadcom Scorpion 56820
                                     Development System - 16TENGIG
Machine Model....................... BCM-56820
Serial Number....................... 10611100004
FRU Number..........................
Part Number......................... BCM56820
Maintenance Level................... A
Manufacturer........................ 0xbc00
Burned In MAC Address............... 00:A0:98:4B:A9:AA
Software Version.................... 1.1.0.3
Operating System.................... Linux 2.6.21.7
Network Processing Device........... BCM56820_B0
Additional Packages................. FASTPATH QOS
                                     FASTPATH IPv6 Management
----
====
. Consultez les images de démarrage pour la configuration active et de secours.
+
`show bootvar`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

Image Descriptions

 active :
 backup :

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.3          1.1.0.3           1.1.0.5
----
====
. Redémarrez le commutateur.
+
`reload`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) # reload

Are you sure you would like to reset the system? (y/n)  y

System will now restart!
----
====




=== Étape 3 : Valider l’installation

. Connectez-vous à nouveau et vérifiez la nouvelle version du logiciel FASTPATH.
+
`show version`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description................... Broadcom Scorpion 56820
                                      Development System - 16 TENGIG,
                                      1.1.0.5, Linux 2.6.21.7
Machine Type......................... Broadcom Scorpion 56820
                                      Development System - 16TENGIG
Machine Model........................ BCM-56820
Serial Number........................ 10611100004
FRU Number...........................
Part Number.......................... BCM56820
Maintenance Level.................... A
Manufacturer......................... 0xbc00
Burned In MAC Address................ 00:A0:98:4B:A9:AA
Software Version..................... 1.1.0.5
Operating System..................... Linux 2.6.21.7
Network Processing Device............ BCM56820_B0
Additional Packages.................. FASTPATH QOS
                                      FASTPATH IPv6 Management
----
====
. Activez les ports ISL sur cs1, le commutateur actif.
+
`configure`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (Interface 0/13-0/16) # no shutdown
(cs1) (Interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====
. Vérifiez que les ISL sont opérationnels :
+
`show port-channel 3/1`

+
Le champ État du lien doit indiquer `Up` .

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. Copiez le `running-config` fichier au `startup-config` Enregistrez le fichier lorsque vous êtes satisfait des versions du logiciel et modifiez les paramètres.
+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) # write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .

Configuration Saved!
----
====
. Activez le deuxième port du cluster, e2a, sur chaque nœud :
+
`network port modify`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> **network port modify -node node2 -port e2a -up-admin true**
----
====
. Rétablir le cluster 2 associé au port e2a :
+
`network interface revert`

+
Le LIF peut se rétablir automatiquement, selon votre version du logiciel ONTAP .

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
====
. Vérifiez que le LIF est maintenant à la maison(`true` ) sur les deux nœuds :
+
`network interface show -_role cluster_`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

          Logical    Status     Network        Current  Current Is
Vserver   Interface  Admin/Oper Address/Mask   Node     Port    Home
--------  ---------- ---------- -------------- -------- ------- ----
vs1
          clus1      up/up      10.10.10.1/24  node1    e1a     true
          clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
          clus1      up/up      10.10.10.1/24  node2    e1a     true
          clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. Consultez l'état des nœuds :
+
`cluster show`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node                 Health  Eligibility
-------------------- ------- ------------
node1                true    true
node2                true    true
----
====
. Répétez les étapes précédentes pour installer le logiciel FASTPATH sur l'autre commutateur, cs1.
. Si vous avez désactivé la création automatique de dossiers, réactivez-la en envoyant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`


