---
permalink: switch-netapp-cn1610/install-rcf-file.html 
sidebar: sidebar 
keywords: reference configuration, file ,install, cn1610, switch, install rcf 
summary: 'Lors de l"installation d"un fichier de configuration de référence (RCF), vous devez d"abord migrer les LIF du cluster hors du commutateur cs2.  Une fois le RCF installé et validé, les LIF peuvent être réimportés.' 
---
= Installez un fichier de configuration de référence sur un commutateur CN1610.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez cette procédure pour installer un fichier de configuration de référence (RCF).

Avant d'installer un RCF, vous devez d'abord migrer les LIF du cluster hors du commutateur cs2.  Une fois le RCF installé et validé, les LIF peuvent être réimportés.



== Exigences de révision

.Avant de commencer
Assurez-vous d'avoir les éléments suivants :

* Une sauvegarde actuelle de la configuration du commutateur.
* Un cluster parfaitement fonctionnel (aucune erreur dans les journaux et aucune carte d'interface réseau (NIC) défectueuse ou problème similaire).
* Connexions de ports entièrement fonctionnelles sur le commutateur de cluster.
* Tous les ports du cluster sont configurés.
* Toutes les interfaces logiques du cluster (LIF) sont configurées.
* Une voie de communication réussie : ONTAP (privilège : avancé) `cluster ping-cluster -node node1` La commande doit indiquer que `larger than PMTU communication` réussit sur tous les plans.
* Une version prise en charge de RCF et ONTAP.
+
Assurez-vous de consulter le tableau de compatibilité des commutateurs sur le http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["Commutateurs NetApp CN1601 et CN1610"^] page pour les versions RCF et ONTAP prises en charge.





== Installez le RCF

La procédure suivante utilise la syntaxe clusterisée de Data ONTAP 8.2.  Par conséquent, le Vserver du cluster, les noms LIF et la sortie CLI sont différents de ceux de Data ONTAP 8.3.

Il peut exister des dépendances entre la syntaxe des commandes dans les versions RCF et FASTPATH.


NOTE: Dans la version 1.2 de RCF, la prise en charge de Telnet a été explicitement désactivée pour des raisons de sécurité.  Pour éviter les problèmes de connectivité lors de l'installation de RCF 1.2, vérifiez que Secure Shell (SSH) est activé.  Le https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["Guide de l'administrateur du commutateur NetApp CN1610"^] contient plus d'informations sur SSH.

.À propos des exemples
Les exemples de cette procédure utilisent la nomenclature suivante pour les commutateurs et les nœuds :

* Les deux commutateurs NetApp sont cs1 et cs2.
* Les deux LIF de cluster sont clus1 et clus2.
* Les serveurs virtuels sont vs1 et vs2.
* Le `cluster::*>` L'invite indique le nom du cluster.
* Les ports du cluster sur chaque nœud sont nommés e1a et e2a.
+
https://hwu.netapp.com/["Hardware Universe"^]contient plus d'informations sur les ports de cluster réellement pris en charge sur votre plateforme.

* Les liaisons inter-commutateurs (ISL) prises en charge sont les ports 0/13 à 0/16.
* Les connexions de nœuds prises en charge sont les ports 0/1 à 0/12.
* Une version prise en charge de FASTPATH, RCF et ONTAP.
+
Assurez-vous de consulter le tableau de compatibilité des commutateurs sur le http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["Commutateurs NetApp CN1601 et CN1610"^] page répertoriant les versions FASTPATH, RCF et ONTAP prises en charge.





=== Étape 1 : Migrer le cluster

. Enregistrez les informations de configuration actuelles de votre commutateur :
+
`write memory`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre comment la configuration actuelle du commutateur est enregistrée dans la configuration de démarrage.(`startup-config` ) fichier sur switch cs2 :

[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. Sur la console de chaque nœud, migrez clus2 vers le port e1a :
+
`network interface migrate`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -source-node node1 -destnode node1 -dest-port e1a

cluster::*> network interface migrate -vserver vs2 -lif clus2 -source-node node2 -destnode node2 -dest-port e1a
----
====
. Sur la console de chaque nœud, vérifiez que la migration a bien eu lieu :
+
`network interface show -role cluster`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre que clus2 a migré vers le port e1a sur les deux nœuds :

[listing]
----
cluster::*> network port show -role cluster
         clus1      up/up      10.10.10.1/16   node2    e1a     true
         clus2      up/up      10.10.10.2/16   node2    e1a     false
----
====
. Fermez le port e2a sur les deux nœuds :
+
`network port modify`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre la fermeture du port e2a sur les deux nœuds :

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. Vérifiez que le port e2a est fermé sur les deux nœuds :
+
`network port show`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                  Auto-Negot  Duplex      Speed (Mbps)
Node   Port   Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ------ -------- ---- ----- ----------- ----------  -----------
node1
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
node2
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
----
====
. Fermez les ports ISL sur cs1, le commutateur NetApp actif.
+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (interface 0/13-0/16) # shutdown
(cs1) (interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====




=== Étape 2 : installer RCF

. Copiez le RCF sur le commutateur.
+

NOTE: Vous devez définir le `.scr` l'extension dans le nom du fichier avant d'exécuter le script.  Cette extension est destinée au système d'exploitation FASTPATH.

+
Le commutateur validera automatiquement le script lors de son téléchargement, et la sortie sera affichée sur la console.

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.10.0.1/CN1610_CS_RCF_v1.1.txt nvram:script CN1610_CS_RCF_v1.1.scr

[the script is now displayed line by line]
Configuration script validated.
File transfer operation completed successfully.
----
====
. Vérifiez que le script a bien été téléchargé et enregistré sous le nom de fichier que vous lui avez attribué.
+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) # script list
Configuration Script Name        Size(Bytes)
-------------------------------- -----------
running-config.scr               6960
CN1610_CS_RCF_v1.1.scr           2199

2 configuration script(s) found.
6038 Kbytes free.
----
====
. Validez le script.
+

NOTE: Le script est validé pendant le téléchargement afin de vérifier que chaque ligne correspond à une ligne de commande switch valide.

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) # script validate CN1610_CS_RCF_v1.1.scr
[the script is now displayed line by line]
Configuration script 'CN1610_CS_RCF_v1.1.scr' validated.
----
====
. Appliquez le script à l'interrupteur.
+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) #script apply CN1610_CS_RCF_v1.1.scr

Are you sure you want to apply the configuration script? (y/n) y
[the script is now displayed line by line]...

Configuration script 'CN1610_CS_RCF_v1.1.scr' applied.
----
====
. Vérifiez que vos modifications ont bien été prises en compte sur le commutateur.
+
[listing]
----
(cs2) # show running-config
----
+
L'exemple affiche le `running-config` fichier sur le commutateur.  Vous devez comparer le fichier au RCF pour vérifier que les paramètres que vous avez définis correspondent à vos attentes.

. Enregistrez les modifications.
. Réglez le `running-config` Le fichier doit être le fichier standard.
+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.
----
====
. Redémarrez le commutateur et vérifiez que le `running-config` Le fichier est correct.
+
Une fois le redémarrage terminé, vous devez vous connecter et consulter le `running-config` fichier, puis recherchez la description sur l'interface 3/64, qui est l'étiquette de version pour le RCF.

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) # reload

The system has unsaved changes.
Would you like to save them now? (y/n) y


Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====
. Activez les ports ISL sur cs1, le commutateur actif.
+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config)# interface 0/13-0/16
(cs1) (Interface 0/13-0/16)# no shutdown
(cs1) (Interface 0/13-0/16)# exit
(cs1) (config)# exit
----
====
. Vérifiez que les ISL sont opérationnels :
+
`show port-channel 3/1`

+
Le champ État du lien doit indiquer `Up` .

+
.Afficher un exemple
[%collapsible]
====
[listing]
----

(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. Activez le port de cluster e2a sur les deux nœuds :
+
`network port modify`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre l'activation du port e2a sur les nœuds node1 et node2 :

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> network port modify -node node2 -port e2a -up-admin true
----
====




=== Étape 3 : Valider l’installation

. Vérifiez que le port e2a est actif sur les deux nœuds :
+
`network port show -_role cluster_`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- ----  ----------- ----------  ------------
node1
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
----
====
. Sur les deux nœuds, rétablissez la configuration du cluster 2 associé au port e2a :
+
`network interface revert`

+
Le LIF peut revenir automatiquement, selon votre version d' ONTAP.

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver node1 -lif clus2
cluster::*> network interface revert -vserver node2 -lif clus2
----
====
. Vérifiez que le LIF est maintenant à la maison(`true` ) sur les deux nœuds :
+
`network interface show -_role cluster_`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

        Logical    Status     Network        Current  Current Is
Vserver Interface  Admin/Oper Address/Mask   Node     Port    Home
------- ---------- ---------- -------------- -------- ------- ----
vs1
        clus1      up/up      10.10.10.1/24  node1    e1a     true
        clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
        clus1      up/up      10.10.10.1/24  node2    e1a     true
        clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. Consultez l'état des membres du nœud :
+
`cluster show`

+
.Afficher un exemple
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node           Health  Eligibility
-------------- ------- ------------
node1
               true    true
node2
               true    true
----
====
. Copiez le `running-config` fichier au `startup-config` Enregistrez le fichier lorsque vous êtes satisfait des versions du logiciel et modifiez les paramètres.
+
.Afficher un exemple
[%collapsible]
====
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. Répétez les étapes précédentes pour installer le RCF sur l'autre commutateur, cs1.


.Quelle est la prochaine étape ?
link:../switch-cshm/config-overview.html["Configurer la surveillance de l'état du commutateur"]
