---
permalink: switch-netapp-cn1610/migrate-overview.html 
sidebar: sidebar 
keywords: migrate, two-node switched cluster, netapp cn1610 
summary: 'Examinez les options de migration pour passer d"un cluster sans commutateur à deux nœuds à un cluster commuté utilisant les commutateurs de cluster NetApp CN1610.' 
---
= Examinez les options de migration pour les commutateurs de cluster NetApp CN1610
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Examinez les options de migration pour passer d'un cluster sans commutateur à deux nœuds à un cluster commuté utilisant les commutateurs de cluster NetApp CN1610. La procédure dépend du fait que vous disposiez de deux ports réseau dédiés au cluster ou d'un seul port de cluster sur chaque contrôleur.

La plupart des systèmes nécessitent deux ports réseau dédiés au cluster sur chaque contrôleur.

Les nœuds FAS22xx permettent un seul port de cluster sur chaque contrôleur.

Deux options de migration sont disponibles :

* link:migrate-switched-netapp-cn1610.html["Migrez d'un cluster sans commutateur vers un environnement de cluster NetApp CN1610 commuté"]
* link:migrate-fas22xx-systems.html["Migrez à partir d’un cluster sans commutateur (systèmes FAS22xx avec une seule connexion réseau de cluster)"]

