---
permalink: switch-netapp-cn1610/migrate-overview.html 
sidebar: sidebar 
keywords: migrate, two-node switched cluster, netapp cn1610 
summary: 'Si vous disposez d"un cluster sans commutateur à deux nœuds, vous pouvez migrer, sans interruption, vers un cluster commuté à deux nœuds comprenant des commutateurs de réseau de cluster NetApp CN1610.' 
---
= Options de migration pour un cluster commuté à deux nœuds avec les commutateurs de cluster NetApp CN1610
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous disposez d'un cluster à deux nœuds sans commutateur, vous pouvez migrer, sans interruption de service, vers un cluster à deux nœuds avec commutateurs réseau NetApp CN1610. La procédure que vous utilisez dépend du fait que vous disposez de deux ports réseau de cluster dédiés sur chaque contrôleur ou d'un seul port de cluster sur chaque contrôleur.

La plupart des systèmes nécessitent deux ports réseau dédiés au cluster sur chaque contrôleur.

Les nœuds FAS22xx permettent un seul port de cluster sur chaque contrôleur.

Deux options de migration sont disponibles :

* link:migrate-switched-netapp-cn1610.html["Migrez d'un cluster sans commutateur vers un environnement de cluster NetApp CN1610 commuté"]
* link:migrate-fas22xx-systems.html["Migrez à partir d’un cluster sans commutateur (systèmes FAS22xx avec une seule connexion réseau de cluster)"]

