---
permalink: switch-netapp-cn1610/replace-cn1610-switch.html 
sidebar: sidebar 
keywords: replace, netapp cn1610, cluster switch 
summary: Vous pouvez remplacer un commutateur de cluster NetApp CN1610 défectueux sans interruption en effectuant une séquence spécifique de tâches. 
---
= Remplacez un commutateur de cluster NetApp CN1610
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La procédure suivante permet de remplacer un commutateur NetApp CN1610 défectueux dans un réseau en cluster. Il s'agit d'une procédure sans interruption.



== Examen des conditions requises

.Ce dont vous avez besoin
Avant d'effectuer le remplacement d'un commutateur, les conditions suivantes doivent être réunies avant d'effectuer le remplacement d'un commutateur dans l'environnement actuel et sur le commutateur de remplacement d'un cluster et d'une infrastructure réseau existants :

* Le cluster existant doit être vérifié comme entièrement fonctionnel, avec au moins un commutateur de cluster entièrement connecté.
* Tous les ports du cluster doivent être *up*.
* Toutes les interfaces logiques (LIF) du cluster doivent être up et n'ont pas dû avoir été migrées.
* Cluster ONTAP `ping-cluster -node node1` La commande doit indiquer que la connectivité de base et la communication plus grande que la communication PMTU ont réussi sur tous les chemins.




== Activer la journalisation de la console

NetApp vous recommande fortement d'activer la journalisation de la console sur les périphériques que vous utilisez et d'effectuer les actions suivantes lors du remplacement de votre commutateur :

* Laissez AutoSupport activé pendant la maintenance.
* Déclencher une AutoSupport de maintenance avant et après la maintenance pour désactiver la création de cas pendant la durée de la maintenance. Consultez cet article de la base de connaissance https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["SU92 : comment supprimer la création automatique de cas pendant les fenêtres de maintenance planifiées"^] pour plus d'informations.
* Activer la journalisation des sessions pour toutes les sessions CLI. Pour obtenir des instructions sur l'activation de la journalisation des sessions, consultez la section « consignation des sorties de session » de cet article de la base de connaissances https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Comment configurer PuTTY pour une connectivité optimale aux systèmes ONTAP"^].




== Remplacer le contacteur

.Description de la tâche
Vous devez exécuter la commande pour migrer une LIF de cluster à partir du nœud sur lequel la LIF de cluster est hébergée.

Les exemples de cette procédure utilisent la nomenclature de commutateurs et de nœuds du cluster suivante :

* Les noms des deux commutateurs de cluster CN1610 sont `cs1` et `cs2`.
* Le nom du commutateur CN1610 à remplacer (le commutateur défectueux) est `old_cs1`.
* Le nom du nouveau commutateur CN1610 (le commutateur de remplacement) est `new_cs1`.
* Le nom du commutateur partenaire qui n'est pas remplacé est `cs2`.


.Étapes
. Vérifiez que le fichier de configuration de démarrage correspond au fichier de configuration en cours d'exécution. Vous devez enregistrer ces fichiers localement pour les utiliser pendant le remplacement.
+
Les commandes de configuration de l'exemple suivant concernent FASTPATH 1.2.0.7:

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1) *>enable*
(old_cs1) *#show running-config*
(old_cs1) *#show startup-config*
----
====
. Créez une copie du fichier de configuration en cours d'exécution.
+
La commande de l'exemple suivant concerne FASTPATH 1.2.0.7:

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1) *#show running-config filename.scr*
Config script created successfully.
----
====



NOTE: Vous pouvez utiliser n'importe quel nom de fichier sauf `CN1610_CS_RCF_v1.2.scr`. Le nom de fichier doit avoir l'extension *.scr*.

. [[step3]]Enregistrez le fichier de configuration en cours d'exécution du commutateur sur un hôte externe en préparation du remplacement.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1) #*copy nvram:script filename.scr scp://<Username>@<remote_IP_address>/path_to_file/filename.scr*
----
====
. Vérifiez que les versions du commutateur et de ONTAP correspondent dans la matrice de compatibilité. Voir la https://mysupport.netapp.com/site/info/netapp-cluster-switch["Commutateurs NetApp CN1601 et CN1610"^] pour plus de détails.
. À partir du https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/downloads-tab["Page de téléchargement de logiciels"^] Sur le site de support NetApp, sélectionnez commutateurs de cluster NetApp pour télécharger les versions RCF et FASTPATH appropriées.
. Configurez un serveur TFTP (Trivial File Transfer Protocol) avec LA CONFIGURATION FASTPATH, RCF et enregistrée `.scr` fichier à utiliser avec le nouveau commutateur.
. Connectez le port série (le connecteur RJ-45 étiqueté “IOIOI” sur le côté droit du commutateur) à un hôte disponible avec émulation de terminal.
. Sur l'hôte, définissez les paramètres de connexion du terminal série :
+
.. 9600 bauds
.. 8 bits de données (data bits)
.. 1 bit de stop
.. parité : aucune
.. contrôle de flux : aucun


. Connectez le port de gestion (le port de clé RJ-45 sur le côté gauche du commutateur) au même réseau que celui où se trouve votre serveur TFTP.
. Préparez-vous à vous connecter au réseau avec le serveur TFTP.
+
Si vous utilisez le protocole DHCP (Dynamic Host Configuration Protocol), il n'est pas nécessaire de configurer une adresse IP pour le commutateur à ce stade. Par défaut, le port de service est configuré pour utiliser DHCP. Le port de gestion réseau est défini sur aucun pour les paramètres des protocoles IPv4 et IPv6. Si votre port de clé USB est connecté à un réseau doté d'un serveur DHCP, les paramètres du serveur sont configurés automatiquement.

+
Pour définir une adresse IP statique, vous devez utiliser le protocole serviceport, le protocole réseau et les commandes serviceport ip.

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1) #*serviceport ip <ipaddr> <netmask> <gateway>*
----
====
. Si le serveur TFTP se trouve sur un ordinateur portable, connectez le commutateur CN1610 à l'ordinateur portable à l'aide d'un câble Ethernet standard, puis configurez son port réseau sur le même réseau avec une autre adresse IP.
+
Vous pouvez utiliser le `ping` pour vérifier l'adresse. Si vous ne parvenez pas à établir la connectivité, vous devez utiliser un réseau non routé et configurer le port de service à l'aide des adresses IP 192.168.x ou 172.16.x. Vous pouvez reconfigurer le port de service sur l'adresse IP de gestion de production à une date ultérieure.

. Vous pouvez également vérifier et installer les versions appropriées du logiciel RCF et FASTPATH pour le nouveau commutateur. Si vous avez vérifié que le nouveau commutateur est correctement configuré et qu'il ne nécessite pas de mise à jour des logiciels RCF et FASTPATH, passez à l'étape 13.
+
.. Vérifiez les nouveaux paramètres du commutateur.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1) >*enable*
(new_cs1) #*show version*
----
====
.. Téléchargez le fichier RCF sur le nouveau commutateur.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1) #*copy tftp://<server_ip_address>/CN1610_CS_RCF_v1.2.txt nvram:script CN1610_CS_RCF_v1.2.scr*
Mode.	TFTP
Set Server IP.	172.22.201.50
Path.	/
Filename....................................... CN1610_CS_RCF_v1.2.txt
Data Type...................................... Config Script
Destination Filename........................... CN1610_CS_RCF_v1.2.scr
File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.

Management access will be blocked for the duration of the transfer Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. please wait...
Validating configuration script...
(the entire script is displayed line by line)
...
description "NetApp CN1610 Cluster Switch RCF v1.2 - 2015-01-13"
...
Configuration script validated.
File transfer operation completed successfully.
----
====
.. Vérifiez que le RCF est téléchargé sur le commutateur.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1) #*script list*
Configuration Script Nam   Size(Bytes)
-------------------------- -----------
CN1610_CS_RCF_v1.1.scr            2191
CN1610_CS_RCF_v1.2.scr            2240
latest_config.scr                 2356

4 configuration script(s) found.
2039 Kbytes free.
----
====


. Appliquez le RCF sur le commutateur CN1610.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1) #*script apply CN1610_CS_RCF_v1.2.scr*
Are you sure you want to apply the configuration script? (y/n) *y*
...
(the entire script is displayed line by line)
...
description "NetApp CN1610 Cluster Switch RCF v1.2 - 2015-01-13"
...
Configuration script 'CN1610_CS_RCF_v1.2.scr' applied. Note that the script output will go to the console.
After the script is applied, those settings will be active in the running-config file. To save them to the startup-config file, you must use the write memory command, or if you used the reload answer yes when asked if you want to save the changes.
----
====
+
.. Enregistrez le fichier de configuration en cours d'exécution pour qu'il devienne le fichier de configuration de démarrage lorsque vous redémarrez le commutateur.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1) #*write memory*
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
.. Téléchargez l'image sur le commutateur CN1610.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1) #*copy tftp://<server_ip_address>/NetApp_CN1610_1.2.0.7.stk active*
Mode.	TFTP
Set Server IP.	tftp_server_ip_address
Path.	/
Filename....................................... NetApp_CN1610_1.2.0.7.stk
Data Type.	Code
Destination Filename.	active

Management access will be blocked for the duration of the transfer

Are you sure you want to start? (y/n) *y*

TFTP Code transfer starting...

File transfer operation completed successfully.
----
====
.. Exécutez la nouvelle image de démarrage active en redémarrant le commutateur.
+
Le commutateur doit être redémarré pour que la commande de l'étape 6 reflète la nouvelle image. Il existe deux vues possibles pour une réponse que vous pouvez voir après avoir entré la commande reload.

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1) #*reload*
The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved! System will now restart!
.
.
.
Cluster Interconnect Infrastructure

User:admin Password: (new_cs1) >*enable*
----
====
.. Copiez le fichier de configuration enregistré de l'ancien commutateur vers le nouveau commutateur.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1) #*copy tftp://<server_ip_address>/<filename>.scr nvram:script <filename>.scr*
----
====
.. Appliquer la configuration précédemment enregistrée au nouveau commutateur.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1) #*script apply <filename>.scr*
Are you sure you want to apply the configuration script? (y/n) *y*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
.. Enregistrez le fichier de configuration en cours d'exécution dans le fichier de configuration de démarrage.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1) #*write memory*
----
====


. Si AutoSupport est activé sur ce cluster, supprimez la création automatique de dossiers en invoquant un message AutoSupport :
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_ représente la durée de la fenêtre de maintenance en heures.

+
[NOTE]
====
Le message AutoSupport informe le support technique de cette tâche de maintenance de sorte que la création automatique de dossier soit supprimée lors de la fenêtre de maintenance.

====
. Sur le nouveau commutateur New_cs1, connectez-vous en tant qu'utilisateur admin et arrêtez tous les ports qui sont connectés aux interfaces du cluster de nœuds (ports 1 à 12).
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
User:*admin*
Password:
(new_cs1) >*enable*
(new_cs1) #

(new_cs1) #*config*
(new_cs1)(config)#*interface 0/1-0/12*
(new_cs1)(interface 0/1-0/12)#*shutdown*
(new_cs1)(interface 0/1-0/12)#*exit*
(new_cs1) #*write memory*
----
====
. Migrer les LIFs du cluster à partir des ports connectés au commutateur Old_cs1.
+
Vous devez migrer chaque LIF de cluster à partir de l'interface de gestion de son nœud actuel.

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *set -privilege advanced*
cluster::> *network interface migrate -vserver <vserver_name> -lif <Cluster_LIF_to_be_moved> - sourcenode <current_node> -dest-node <current_node> -dest-port <cluster_port_that_is_UP>*
----
====
. Vérifiez que toutes les LIFs du cluster ont été déplacées vers le port cluster approprié sur chaque nœud.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *network interface show -role cluster*
----
====
. Arrêtez les ports de cluster connectés au commutateur que vous avez remplacé.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node <node_name> -port <port_to_admin_down> -up-admin false*
----
====
. Vérifiez l'état de santé du cluster.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster show*
----
====
. Vérifiez que les ports ne fonctionnent pas.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node <node_name>*
----
====
. Sur le commutateur cs2, arrêtez les ports ISL 13 à 16.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2) #*config*
(cs2)(config)#*interface 0/13-0/16*
(cs2)(interface 0/13-0/16)#*shutdown*
(cs2) #*show port-channel 3/1*
----
====
. Vérifiez si l'administrateur du stockage est prêt pour le remplacement du commutateur.
. Retirez tous les câbles de l'ancien commutateur_cs1, puis connectez les câbles aux mêmes ports du nouveau commutateur_cs1.
. Sur le commutateur cs2, afficher les ports ISL 13 à 16.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2) #*config*
(cs2)(config)#*interface 0/13-0/16*
(cs2)(interface 0/13-0/16)#*no shutdown*
----
====
. Afficher les ports du nouveau switch qui sont associés aux nœuds du cluster
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2) #*config*
(cs2)(config)#*interface 0/1-0/12*
(cs2)(interface 0/13-0/16)#*no shutdown*
----
====
. Sur un seul nœud, ouvrez le port du nœud de cluster connecté au commutateur remplacé, puis vérifiez que la liaison fonctionne.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node node1 -port <port_to_be_onlined> -up-admin true*
cluster::*> *network port show -role cluster*
----
====
. Ne pas convertir les LIFs cluster associées au port de l'étape 25 sur le même nœud.
+
Dans cet exemple, les LIFs sur le node1 sont restaurées avec succès si la colonne « est Home » est définie sur « true ».

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver node1 -lif <cluster_lif_to_be_reverted>*
cluster::*> *network interface show -role cluster*
----
====
. Si la LIF du cluster du premier nœud est up et qu'elle est rétablie sur son port de rattachement, répétez les étapes 25 et 26 pour rétablir les ports du cluster et les LIF du cluster sur les autres nœuds du cluster.
. Affiche des informations relatives aux nœuds du cluster.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster show*
----
====
. Vérifiez que le fichier de configuration de démarrage et le fichier de configuration en cours d'exécution sont corrects sur le commutateur remplacé. Ce fichier de configuration doit correspondre à la sortie de l'étape 1.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1) >*enable*
(new_cs1) #*show running-config*
(new_cs1) #*show startup-config*
----
====
. Si vous avez supprimé la création automatique de cas, réactivez-la en appelant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`


