---
permalink: switch-netapp-cn1610/required-documentation-cn1610.html 
sidebar: sidebar 
keywords: cn1610, switch, netapp 
summary: 'Pour l"installation et la maintenance des commutateurs NetApp CN1610, veillez à consulter toute la documentation recommandée.' 
---
= Exigences en matière de documentation pour les commutateurs NetApp CN1610
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour l'installation et la maintenance des commutateurs NetApp CN1610, veillez à consulter toute la documentation recommandée.

[cols="1,2"]
|===
| Titre du document | Description 


 a| 
https://["Guide d'installation 1G"^]
 a| 
Présentation des fonctionnalités matérielles et logicielles du commutateur CN1601 et du processus d'installation.



 a| 
https://["Guide d'installation 10G"^]
 a| 
Présentation des fonctions logicielles et matérielles du commutateur CN1610 et décrit les fonctionnalités à installer et à accéder à l'interface de ligne de commande.



 a| 
https://["Guide de configuration et de configuration des commutateurs CN1601 et CN1610"^]
 a| 
Explique comment configurer le matériel et les logiciels du commutateur pour votre environnement de cluster.



 a| 
Guide de l'administrateur des commutateurs CN1601
 a| 
Fournit des exemples d'utilisation du commutateur CN1601 dans un réseau type.

* https://["Guide de l'administrateur"^]
* https://["Guide de l'administrateur, version 1.1.x.x"^]
* https://["Guide de l'administrateur, version 1.2.x.x"^]




 a| 
Référence des commandes CLI du commutateur réseau CN1610
 a| 
Fournit des informations détaillées sur les commandes de l'interface de ligne de commandes que vous utilisez pour configurer le logiciel CN1601.

* https://["Référence de commande"^]
* https://["Référence de commande, version 1.1.x.x"^]
* https://["Référence de commande, version 1.2.x.x"^]


|===