---
permalink: switch-netapp-cn1610/switch-overview-cn1610.html 
sidebar: sidebar 
keywords: install, fastpath, software, rcfs 
summary: Avant de configurer les commutateurs NetApp CN1610, consultez la présentation générale de la procédure. 
---
= Présentation de l'installation et de la configuration des commutateurs NetApp CN1610
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le CN1610 est un commutateur de couche 2 géré à large bande passante qui fournit 16 ports 10-Gigabit Small Form-Factor Pluggable Plus (SFP+).

Ce commutateur intègre des alimentations redondantes et des plateaux de ventilation remplaçables à chaud pour une haute disponibilité. Ce commutateur 1U peut être installé dans une armoire système NetApp standard de 19 pouces 42U ou dans une armoire tierce.

Le commutateur prend en charge la gestion locale via le port console ou la gestion à distance via Telnet ou SSH à travers une connexion réseau. Le CN1610 inclut un port de gestion Ethernet RJ45 1-Gigabit dédié pour la gestion hors bande du commutateur. Vous pouvez gérer le commutateur en saisissant des commandes dans l'interface de ligne de commande (CLI) ou en utilisant un système de gestion de réseau (NMS) basé sur SNMP.
