---
permalink: switch-netapp-cn1610/switch-overview-cn1610.html 
sidebar: sidebar 
keywords: install, fastpath, software, rcfs 
summary: Découvrez le commutateur de cluster NetApp CN1610 et son rôle dans la mise en réseau de cluster ONTAP. 
---
= Découvrez les commutateurs de cluster NetApp CN1610
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le NetApp CN1610 est un commutateur de cluster de couche 2 administrable à large bande passante doté de 16 ports SFP+ 10 Gigabit. Consultez cette page pour en savoir plus sur les fonctionnalités du commutateur et son rôle dans la mise en réseau en cluster ONTAP.

Ce commutateur intègre des alimentations redondantes et des plateaux de ventilation remplaçables à chaud pour une haute disponibilité. Ce commutateur 1U peut être installé dans une armoire système NetApp standard de 19 pouces 42U ou dans une armoire tierce.

Le commutateur prend en charge la gestion locale via le port console ou la gestion à distance via Telnet ou SSH à travers une connexion réseau. Le CN1610 inclut un port de gestion Ethernet RJ45 1-Gigabit dédié pour la gestion hors bande du commutateur. Vous pouvez gérer le commutateur en saisissant des commandes dans l'interface de ligne de commande (CLI) ou en utilisant un système de gestion de réseau (NMS) basé sur SNMP.
