---
permalink: switch-netapp-cn1610/task-migrate-to-a-two-node-switched-cluster-with-netapp-cn1610-cluster-switches.html 
sidebar: sidebar 
keywords: migrate, two-node switched cluster, netapp cn1610 
summary: 'Si vous disposez d"un cluster sans commutateur à deux nœuds, vous pouvez migrer sans interruption vers un cluster à deux nœuds avec commutateur qui inclut des commutateurs du réseau en cluster NetApp CN1610. La procédure que vous utilisez dépend de votre présence de deux ports cluster-network dédiés sur chaque contrôleur ou d"un port de cluster unique sur chaque contrôleur.' 
---
= Migrez vers un cluster à deux nœuds avec commutateurs de cluster NetApp CN1610
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous disposez d'un cluster sans commutateur à deux nœuds, vous pouvez migrer sans interruption vers un cluster à deux nœuds avec commutateur qui inclut des commutateurs du réseau en cluster NetApp CN1610. La procédure que vous utilisez dépend de votre présence de deux ports cluster-network dédiés sur chaque contrôleur ou d'un port de cluster unique sur chaque contrôleur.

.Description de la tâche
La plupart des systèmes requièrent deux ports dédiés du réseau cluster sur chaque contrôleur.

Les nœuds FAS22xx permettent un port de cluster unique sur chaque contrôleur.

Deux options de migration sont disponibles :

* link:task-migrate-from-a-switchless-cluster-to-a-switched-netapp-cn1610-cluster-environment.html["Migrer d'un cluster sans commutateur vers un environnement de cluster NetApp CN1610 commuté"]
* xref:task-migrate-from-a-switchless-cluster-fas22xx-systems-with-a-single-cluster-network-connection.adoc[Migration depuis un cluster sans commutateur (systèmes FAS22xx avec une connexion unique cluster-network)]

