---
permalink: switch-netapp-cn1610/task-migrate-from-a-switchless-cluster-fas22xx-systems-with-a-single-cluster-network-connection.html 
sidebar: sidebar 
keywords: migrate, two-node switched cluster, fas22xx systems, single, network connection 
summary: 'Si vous possédez des systèmes FAS22xx dans un cluster existant sans commutateur à deux nœuds dans lequel chaque module de contrôleur dispose d"une connexion 10 GbE unique et dos à dos pour la connectivité des clusters, vous pouvez utiliser l"option de réseau sans commutateur et remplacer la connectivité directe interne par des connexions de commutateurs.' 
---
= Migrez vers un cluster commuté à deux nœuds sur les systèmes FAS22xx avec une seule connexion cluster-network
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous possédez des systèmes FAS22xx dans un cluster existant sans commutateur à deux nœuds dans lequel chaque module de contrôleur dispose d'une connexion 10 GbE unique et dos à dos pour la connectivité des clusters, vous pouvez utiliser l'option de réseau sans commutateur et remplacer la connectivité directe interne par des connexions de commutateurs.

.Avant de commencer
* Deux connexions de cluster sont nécessaires pour migrer d'une configuration sans commutateur vers une configuration à commutateur.
* Le cluster doit être sain et comporter deux nœuds connectés avec une connectivité dos à dos.
* Les nœuds doivent exécuter ONTAP 8.2 ou une version ultérieure.
* La fonctionnalité de cluster sans commutateur ne peut pas être utilisée avec plus de deux nœuds.
* Tous les ports de cluster doivent être dans le `up` état.


Cette procédure constitue une procédure sans interruption qui supprime la connectivité directe du cluster dans un environnement sans commutateur et remplace chaque connexion au commutateur par une connexion au nœud partenaire.

.Étapes
. Modifiez le niveau de privilège en avancé, en saisissant `y` lorsque vous êtes invité à continuer : `set -privilege advanced`
+
L'invite avancée (`*>`) s'affiche.

. Vérifiez l'état du cluster des nœuds sur la console système de l'un ou l'autre nœuds : `cluster show`
+
L'exemple suivant affiche des informations sur la santé et l'éligibilité des nœuds du cluster :

+
[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
. Vérifier l'état de la paire HA sur la console système de n'importe quel nœud : `storage failover show`
+
L'exemple suivant montre l'état du nœud 1 et du nœud 2 :

+
[listing]
----

Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
node1          node2          true      Connected to node2
node2          node1          true      Connected to node1

2 entries were displayed.
----
. Si AutoSupport est activé sur ce cluster, supprimez la création automatique de dossiers en invoquant un message AutoSupport : `system node autosupport invoke -node * -type all -message MAINT=xh`
+
`x` est la durée de la fenêtre de maintenance en heures.

+

NOTE: Ce message informe le support technique de cette tâche de maintenance de sorte que la création automatique de dossier soit supprimée lors de la fenêtre de maintenance.

+
La commande suivante supprime la création automatique de dossiers pendant deux heures :

+
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
. Vérifiez que l'état actuel du cluster sans commutateur est de `true`, puis désactivez le mode cluster sans commutateur : `network options switchless-cluster modify -enabled false`
. Reprendre le nœud cible : `storage failover takeover -ofnode _target_node_name_`
+
Elle n'a pas d'importance sur le nœud cible. Lorsqu'il est pris en charge, le nœud cible redémarre et affiche automatiquement le `Waiting for giveback...` messagerie.

+
Le nœud actif transmet désormais les données du nœud partenaire (cible) pris en charge.

. Attendre deux minutes après le basculement du nœud douteux pour confirmer que le basculement a été effectué correctement.
. Le nœud cible affichant le `Waiting for giveback...` message, arrêtez-le.
+
La méthode que vous utilisez pour arrêter le nœud dépend si vous utilisez la gestion à distance par l'intermédiaire du processeur de service du nœud.

+
|===
| Si le processeur de service est | Alors... 


 a| 
Est configuré
 a| 
Connectez-vous au nœud SP douteux, puis mettez le système hors tension : `system power off`



 a| 
N'est pas configuré
 a| 
À l'invite du nœud douteux, appuyez sur `Ctrl-C`, puis répondez `y` pour arrêter le nœud.

|===
. Sur chaque module de contrôleur, déconnectez le câble qui connecte le port de cluster 10 GbE au cluster sans commutateur.
. Connectez le port de cluster 10 GbE au commutateur des deux modules de contrôleur.
. Vérifiez que les ports de cluster 10 GbE connectés sur le commutateur sont configurés pour faire partie du même VLAN.
+
Si vous prévoyez de connecter les ports de cluster de chaque module de contrôleur à des commutateurs différents, vous devez vérifier que les ports sur lesquels les ports de cluster sont connectés sur chaque commutateur sont configurés pour le même VLAN et que l'agrégation est correctement configurée sur les deux commutateurs.

. Renvoyer le stockage au nœud cible : `storage failover giveback -ofnode node2`
. Surveiller la progression de l'opération de rétablissement : `storage failover show-giveback`
. Une fois l'opération de rétablissement terminée, vérifiez que la paire HA est saine et que le basculement est possible : `storage failover show`
+
La sortie doit être similaire à ce qui suit :

+
[listing]
----

Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
node1          node2          true      Connected to node2
node2          node1          true      Connected to node1

2 entries were displayed.
----
. Vérifiez que les LIFs de port du cluster fonctionnent correctement : `network interface show -role cluster`
+
L'exemple suivant montre que les LIFs sont `up` Sur les noeuds 1 et node2 et que les résultats de la colonne "est à la maison" sont `true`:

+
[listing]
----

cluster::*> network interface show -role cluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
node1
            clus1        up/up    192.168.177.121/24  node1        e1a     true
node2
            clus1        up/up    192.168.177.123/24  node2        e1a     true

2 entries were displayed.
----
. Vérifiez l'état du cluster des nœuds sur la console système de l'un ou l'autre nœuds : `cluster show`
+
L'exemple suivant affiche des informations sur la santé et l'éligibilité des nœuds du cluster :

+
[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
. Envoyez des requêtes ping aux ports du cluster pour vérifier la connectivité du cluster : `cluster ping-cluster local`
+
Le résultat de la commande doit afficher la connectivité entre tous les ports du cluster.

. Si vous avez supprimé la création automatique de cas, réactivez-la en appelant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----
. Rétablissez le niveau de privilège sur admin : `set -privilege admin`


*Informations connexes*

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["Article 1010449 de la base de connaissances NetApp : comment supprimer la création automatique de dossiers pendant les fenêtres de maintenance planifiées"^]
