---
permalink: switch-netapp-cn1610/task-migrate-from-a-switchless-cluster-to-a-switched-netapp-cn1610-cluster-environment.html 
sidebar: sidebar 
keywords: migrate, switchless cluster environment, switched netapp cn1610 
summary: 'Si vous disposez d"un environnement en cluster sans commutateur à deux nœuds, vous pouvez migrer vers un environnement de cluster avec commutateur à deux nœuds en utilisant des commutateurs du réseau de cluster CN1610 qui vous permettent d"évoluer au-delà de deux nœuds.' 
---
= Migration d'un environnement de cluster sans commutateur vers un environnement de cluster NetApp CN1610 commuté
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous disposez d'un environnement en cluster sans commutateur à deux nœuds, vous pouvez migrer vers un environnement de cluster avec commutateur à deux nœuds en utilisant des commutateurs du réseau de cluster CN1610 qui vous permettent d'évoluer au-delà de deux nœuds.

.Avant de commencer
Configuration sans commutateur à 2 nœuds :

* La configuration sans commutateur à deux nœuds doit être correctement configurée et fonctionnelle.
* Les nœuds doivent exécuter ONTAP 8.2 ou une version ultérieure.
* Tous les ports de cluster doivent être dans le `up` état.
* Toutes les interfaces logiques de cluster (LIF) doivent se trouver dans le `up` état et sur leurs ports d'accueil.


Configuration des commutateurs du cluster CN1610 :

* L'infrastructure du commutateur de cluster CN1610 doit être et entièrement fonctionnelle sur les deux commutateurs.
* Les deux commutateurs doivent disposer d'une connectivité réseau de gestion.
* Il doit y avoir un accès à la console aux commutateurs du cluster.
* Les connexions du commutateur nœud à nœud CN1610 et du commutateur à commutateur doivent utiliser des câbles Twinax ou fibre.
+
Le https://hwu.netapp.com/["Hardware Universe"^] contient plus d'informations sur le câblage.

* Les câbles ISL (Inter-Switch Link) doivent être connectés aux ports 13 à 16 sur les deux commutateurs CN1610.
* La personnalisation initiale des deux commutateurs CN1610 doit être terminée.
+
Toute personnalisation de site précédente, telle que SMTP, SNMP et SSH, doit être copiée sur les nouveaux commutateurs.



.Description de la tâche
Les exemples de cette procédure utilisent la nomenclature de commutateurs et de nœuds du cluster suivante :

* Les noms des commutateurs CN1610 sont cs1 et cs2.
* Les noms des FRV sont conclue1 et conclutif2.
* Les noms des nœuds sont nœud1 et nœud2.
* Le `cluster::*>` l'invite indique le nom du cluster.
* Les ports de cluster utilisés dans cette procédure sont les ports e1a et e2a.
+
Le https://hwu.netapp.com/["Hardware Universe"^] contient les informations les plus récentes sur les ports de cluster réels de vos plates-formes.



.Étapes
. Modifiez le niveau de privilège en avancé, en saisissant `y` lorsque vous êtes invité à continuer : `set -privilege advanced`
+
L'invite avancée (*>) apparaît.

. Si AutoSupport est activé sur ce cluster, supprimez la création automatique de dossiers en invoquant un message AutoSupport : `system node autosupport invoke -node * -type all -message MAINT=xh`
+
_x_ représente la durée de la fenêtre de maintenance en heures.

+

NOTE: Le message AutoSupport informe le support technique de cette tâche de maintenance de sorte que la création automatique de dossier soit supprimée lors de la fenêtre de maintenance.

+
La commande suivante supprime la création automatique de dossiers pendant deux heures :

+
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
. Désactivez tous les ports orientés nœuds (et non les ports ISL) sur les nouveaux commutateurs de cluster cs1 et cs2.
+
Vous ne devez pas désactiver les ports ISL.

+
L'exemple suivant montre que les ports 1 à 12 orientés nœud sont désactivés sur le commutateur cs1 :

+
[listing]
----

(cs1)> enable
(cs1)# configure
(cs1)(Config)# interface 0/1-0/12
(cs1)(Interface 0/1-0/12)# shutdown
(cs1)(Interface 0/1-0/12)# exit
(cs1)(Config)# exit
----
+
L'exemple suivant montre que les ports 1 à 12 orientés nœud sont désactivés sur le commutateur cs2 :

+
[listing]
----

(c2)> enable
(cs2)# configure
(cs2)(Config)# interface 0/1-0/12
(cs2)(Interface 0/1-0/12)# shutdown
(cs2)(Interface 0/1-0/12)# exit
(cs2)(Config)# exit
----
. Vérifiez que l'ISL et les ports physiques de l'ISL entre les deux commutateurs du cluster CN1610 cs1 et cs2 sont `up`: `show port-channel`
+
L'exemple suivant montre que les ports ISL sont `up` sur l'interrupteur cs1 :

+
[listing]
----

(cs1)# show port-channel 3/1
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
+
L'exemple suivant montre que les ports ISL sont `up` sur l'interrupteur cs2 :

+
[listing]
----

(cs2)# show port-channel 3/1
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
. Afficher la liste des périphériques voisins : `show isdp neighbors`
+
Cette commande fournit des informations sur les périphériques connectés au système.

+
L'exemple suivant répertorie les périphériques voisins sur le commutateur cs1 :

+
[listing]
----

(cs1)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
cs2                    0/13         11        S            CN1610    0/13
cs2                    0/14         11        S            CN1610    0/14
cs2                    0/15         11        S            CN1610    0/15
cs2                    0/16         11        S            CN1610    0/16
----
+
L'exemple suivant répertorie les périphériques voisins sur le commutateur cs2 :

+
[listing]
----

(cs2)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
cs1                    0/13         11        S            CN1610    0/13
cs1                    0/14         11        S            CN1610    0/14
cs1                    0/15         11        S            CN1610    0/15
cs1                    0/16         11        S            CN1610    0/16
----
. Afficher la liste des ports du cluster : `network port show`
+
L'exemple suivant montre les ports de cluster disponibles :

+
[listing]
----

cluster::*> network port show -ipspace Cluster
Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0c       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0d       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0c       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0d       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/10000 healthy  false
12 entries were displayed.
----
. Vérifiez que chaque port du cluster est connecté au port correspondant sur le nœud de cluster partenaire : `run * cdpd show-neighbors`
+
L'exemple suivant montre que les ports de cluster e1a et e2a sont connectés au même port sur leur nœud partenaire de cluster :

+
[listing]
----

cluster::*> run * cdpd show-neighbors
2 entries were acted on.

Node: node1
Local  Remote          Remote                 Remote           Hold  Remote
Port   Device          Interface              Platform         Time  Capability
------ --------------- ---------------------- ---------------- ----- ----------
e1a    node2           e1a                    FAS3270           137   H
e2a    node2           e2a                    FAS3270           137   H


Node: node2

Local  Remote          Remote                 Remote           Hold  Remote
Port   Device          Interface              Platform         Time  Capability
------ --------------- ---------------------- ---------------- ----- ----------
e1a    node1           e1a                    FAS3270           161   H
e2a    node1           e2a                    FAS3270           161   H
----
. Vérifier que toutes les LIFs du cluster sont `up` et opérationnel : `network interface show -vserver Cluster`
+
Chaque LIF de cluster doit afficher `true` Dans la colonne « est domicile ».

+
[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up      10.10.10.1/16 node1         e1a     true
            clus2      up/up      10.10.10.2/16 node1         e2a     true
node2
            clus1      up/up      10.10.11.1/16 node2         e1a     true
            clus2      up/up      10.10.11.2/16 node2         e2a     true

4 entries were displayed.
----
+

NOTE: Les commandes de modification et de migration suivantes des étapes 10 à 13 doivent être effectuées à partir du nœud local.

. Vérifier que tous les ports de cluster sont `up`: `network port show -ipspace Cluster`
+
[listing]
----
cluster::*> network port show -ipspace Cluster

                                       Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link  MTU   Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ----- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
. Réglez le `-auto-revert` paramètre à `false` Sur le cluster, les LIF de 1 et de 1:2 sont disponibles sur les deux nœuds : `network interface modify`
+
[listing]
----

cluster::*> network interface modify -vserver node1 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node1 -lif clus2 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus2 -auto-revert false
----
+

NOTE: Pour les versions 8.3 et ultérieures, utiliser la commande suivante : `network interface modify -vserver Cluster -lif * -auto-revert false`

. Envoyez des requêtes ping aux ports du cluster pour vérifier la connectivité du cluster : `cluster ping-cluster local`
+
Le résultat de la commande affiche la connectivité entre tous les ports du cluster.

. Migration de la valeur de clu1 vers le port e2a sur la console de chaque nœud : `network interface migrate`
+
L'exemple suivant montre le processus de migration de clude1 vers le port e2a sur le node1 et le node2 :

+
[listing]
----

cluster::*> network interface migrate -vserver node1 -lif clus1 -source-node node1 -dest-node node1 -dest-port e2a
cluster::*> network interface migrate -vserver node2 -lif clus1 -source-node node2 -dest-node node2 -dest-port e2a
----
+

NOTE: Pour les versions 8.3 et ultérieures, utiliser la commande suivante : `network interface migrate -vserver Cluster -lif clus1 -destination-node node1 -destination-port e2a`

. Vérifiez que la migration a eu lieu : `network interface show -vserver Cluster`
+
L'exemple suivant vérifie que la migration de clude1 vers le port e2a sur les nœuds 1 et 2 :

+
[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e2a     false
            clus2      up/up    10.10.10.2/16   node1         e2a     true
node2
            clus1      up/up    10.10.11.1/16   node2         e2a     false
            clus2      up/up    10.10.11.2/16   node2         e2a     true

4 entries were displayed.
----
. Arrêter le port du cluster e1a sur les deux nœuds : `network port modify`
+
L'exemple suivant montre comment arrêter le port e1a sur le nœud1 et le nœud2 :

+
[listing]
----

cluster::*> network port modify -node node1 -port e1a -up-admin false
cluster::*> network port modify -node node2 -port e1a -up-admin false
----
. Vérifiez le statut des ports : `network port show`
+
L'exemple suivant montre que le port e1a est `down` sur les nœuds 1 et 2 :

+
[listing]
----

cluster::*> network port show -role cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        down  9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        down  9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
. Débranchez le câble du port du cluster e1a sur le nœud 1, puis connectez e1a au port 1 du commutateur du cluster cs1 en utilisant le câblage approprié pris en charge par les commutateurs CN1610.
+
Le link:https://hwu.netapp.com/Switch/Index["Hardware Universe"^] contient plus d'informations sur le câblage.

. Débranchez le câble du port du cluster e1a sur le nœud 2, puis connectez e1a au port 2 du commutateur du cluster cs1, en utilisant le câblage approprié pris en charge par les commutateurs CN1610.
. Activez tous les ports orientés nœud sur le commutateur de cluster cs1.
+
L'exemple suivant montre que les ports 1 à 12 sont activés sur le commutateur cs1 :

+
[listing]
----

(cs1)# configure
(cs1)(Config)# interface 0/1-0/12
(cs1)(Interface 0/1-0/12)# no shutdown
(cs1)(Interface 0/1-0/12)# exit
(cs1)(Config)# exit
----
. Activer le premier port du cluster e1a sur chaque nœud : `network port modify`
+
L'exemple suivant montre comment activer le port e1a sur le nœud1 et le nœud2 :

+
[listing]
----

cluster::*> network port modify -node node1 -port e1a -up-admin true
cluster::*> network port modify -node node2 -port e1a -up-admin true
----
. Vérifier que tous les ports du cluster sont `up`: `network port show -ipspace Cluster`
+
L'exemple suivant montre que tous les ports du cluster sont `up` sur les nœuds 1 et 2 :

+
[listing]
----

cluster::*> network port show -ipspace Cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
. Revert clu1 (qui a été précédemment migré) vers e1a sur les deux nœuds : `network interface revert`
+
L'exemple suivant montre comment rétablir la valeur de clude1 au port e1a sur le nœud1 et nœud2 :

+
[listing]
----

cluster::*> network interface revert -vserver node1 -lif clus1
cluster::*> network interface revert -vserver node2 -lif clus1
----
+

NOTE: Pour les versions 8.3 et ultérieures, utiliser la commande suivante : `network interface revert -vserver Cluster -lif <nodename_clus<N>>`

. Vérifier que toutes les LIFs du cluster sont `up`, opérationnel, et afficher comme `true` Dans la colonne « est domicile » : `network interface show -vserver Cluster`
+
L'exemple suivant montre que toutes les LIFs sont `up` Sur les noeuds 1 et node2 et que les résultats de la colonne "est à la maison" sont `true`:

+
[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e1a     true
            clus2      up/up    10.10.10.2/16   node1         e2a     true
node2
            clus1      up/up    10.10.11.1/16   node2         e1a     true
            clus2      up/up    10.10.11.2/16   node2         e2a     true

4 entries were displayed.
----
. Afficher des informations relatives à l'état des nœuds du cluster : `cluster show`
+
L'exemple suivant affiche des informations sur la santé et l'éligibilité des nœuds du cluster :

+
[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
. Migration du clus2 vers le port e1a sur la console de chaque nœud : `network interface migrate`
+
L'exemple suivant montre le processus de migration de clus2 vers le port e1a sur le nœud1 et nœud2 :

+
[listing]
----

cluster::*> network interface migrate -vserver node1 -lif clus2 -source-node node1 -dest-node node1 -dest-port e1a
cluster::*> network interface migrate -vserver node2 -lif clus2 -source-node node2 -dest-node node2 -dest-port e1a
----
+

NOTE: Pour les versions 8.3 et ultérieures, utiliser la commande suivante : `network interface migrate -vserver Cluster -lif node1_clus2 -dest-node node1 -dest-port e1a`

. Vérifiez que la migration a eu lieu : `network interface show -vserver Cluster`
+
L'exemple suivant vérifie que la migration de clus2 vers le port e1a sur le nœud1 et le nœud2 :

+
[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e1a     true
            clus2      up/up    10.10.10.2/16   node1         e1a     false
node2
            clus1      up/up    10.10.11.1/16   node2         e1a     true
            clus2      up/up    10.10.11.2/16   node2         e1a     false

4 entries were displayed.
----
. Arrêter le port cluster e2a sur les deux nœuds : `network port modify`
+
L'exemple suivant montre comment arrêter le port e2a sur les nœuds 1 et 2 :

+
[listing]
----

cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
. Vérifiez le statut des ports : `network port show`
+
L'exemple suivant montre que le port e2a est `down` sur les nœuds 1 et 2 :

+
[listing]
----

cluster::*> network port show -role cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        down  9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        down  9000  true/true  full/full   auto/10000

4 entries were displayed.
----
. Débranchez le câble du port du cluster e2a sur le nœud 1, puis connectez e2a au port 1 du commutateur de cluster cs2 en utilisant le câblage approprié pris en charge par les commutateurs CN1610.
. Débranchez le câble du port du cluster e2a sur le nœud 2, puis connectez e2a au port 2 du commutateur de cluster cs2 en utilisant le câblage approprié pris en charge par les commutateurs CN1610.
. Activez tous les ports orientés nœud sur le commutateur de cluster cs2.
+
L'exemple suivant montre que les ports 1 à 12 sont activés sur le commutateur cs2 :

+
[listing]
----

(cs2)# configure
(cs2)(Config)# interface 0/1-0/12
(cs2)(Interface 0/1-0/12)# no shutdown
(cs2)(Interface 0/1-0/12)# exit
(cs2)(Config)# exit
----
. Activer le second port cluster e2a sur chaque nœud :
+
L'exemple suivant montre comment activer le port e2a sur les nœuds 1 et 2 :

+
[listing]
----

cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> network port modify -node node2 -port e2a -up-admin true
----
. Vérifier que tous les ports du cluster sont `up`: `network port show -ipspace Cluster`
+
L'exemple suivant montre que tous les ports du cluster sont `up` sur les nœuds 1 et 2 :

+
[listing]
----

cluster::*> network port show -ipspace Cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
. Revert clus2 (qui a déjà été migré) vers e2a sur les deux nœuds : `network interface revert`
+
L'exemple suivant montre comment rétablir la valeur de no2 au port e2a sur le node1 et le node2 :

+
[listing]
----

cluster::*> network interface revert -vserver node1 -lif clus2
cluster::*> network interface revert -vserver node2 -lif clus2
----
+

NOTE: Pour les versions 8.3 et ultérieures, les commandes sont les suivantes :
`cluster::*> network interface revert -vserver Cluster -lif node1_clus2` et
`cluster::*> network interface revert -vserver Cluster -lif node2_clus2`

. Vérifier que toutes les interfaces s'affichent `true` Dans la colonne « est domicile » : `network interface show -vserver Cluster`
+
L'exemple suivant montre que toutes les LIFs sont `up` Sur les noeuds 1 et node2 et que les résultats de la colonne "est à la maison" sont `true`:

+
[listing]
----

cluster::*> network interface show -vserver Cluster

             Logical    Status     Network            Current     Current Is
Vserver      Interface  Admin/Oper Address/Mask       Node        Port    Home
-----------  ---------- ---------- ------------------ ----------- ------- ----
node1
             clus1      up/up      10.10.10.1/16      node1       e1a     true
             clus2      up/up      10.10.10.2/16      node1       e2a     true
node2
             clus1      up/up      10.10.11.1/16      node2       e1a     true
             clus2      up/up      10.10.11.2/16      node2       e2a     true
----
. Envoyez des requêtes ping aux ports du cluster pour vérifier la connectivité du cluster : `cluster ping-cluster local`
+
Le résultat de la commande affiche la connectivité entre tous les ports du cluster.

. Vérifier que les deux nœuds ont deux connexions à chaque commutateur : `show isdp neighbors`
+
L'exemple suivant montre les résultats appropriés pour les deux commutateurs :

+
[listing]
----

(cs1)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
node1                  0/1          132       H            FAS3270   e1a
node2                  0/2          163       H            FAS3270   e1a
cs2                    0/13         11        S            CN1610    0/13
cs2                    0/14         11        S            CN1610    0/14
cs2                    0/15         11        S            CN1610    0/15
cs2                    0/16         11        S            CN1610    0/16

(cs2)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
node1                  0/1          132       H            FAS3270   e2a
node2                  0/2          163       H            FAS3270   e2a
cs1                    0/13         11        S            CN1610    0/13
cs1                    0/14         11        S            CN1610    0/14
cs1                    0/15         11        S            CN1610    0/15
cs1                    0/16         11        S            CN1610    0/16
----
. Afficher des informations sur les périphériques de votre configuration : `network device discovery show`
. Désactivez les paramètres de configuration sans commutateur à deux nœuds sur les deux nœuds à l'aide de la commande Advanced Privilege : `network options detect-switchless modify`
+
L'exemple suivant montre comment désactiver les paramètres de configuration sans commutateur :

+
[listing]
----

cluster::*> network options detect-switchless modify -enabled false
----
+

NOTE: Pour la version 9.2 ou ultérieure, ignorez cette étape car la configuration est automatiquement convertie.

. Vérifiez que les paramètres sont désactivés : `network options detect-switchless-cluster show`
+
Le `false` l'exemple suivant montre que les paramètres de configuration sont désactivés :

+
[listing]
----

cluster::*> network options detect-switchless-cluster show
Enable Switchless Cluster Detection: false
----
+

NOTE: Pour la version 9.2 et ultérieure, attendre jusqu'à `Enable Switchless Cluster` est défini sur false. Cette opération peut prendre jusqu'à trois minutes.

. Configurez les clusters de type 1 et de type 1 pour qu'ils rereviennent automatiquement sur chaque nœud et confirmez que :
+
[listing]
----

cluster::*> network interface modify -vserver node1 -lif clus1 -auto-revert true
cluster::*> network interface modify -vserver node1 -lif clus2 -auto-revert true
cluster::*> network interface modify -vserver node2 -lif clus1 -auto-revert true
cluster::*> network interface modify -vserver node2 -lif clus2 -auto-revert true
----
+

NOTE: Pour les versions 8.3 et ultérieures, utiliser la commande suivante : `network interface modify -vserver Cluster -lif * -auto-revert true` pour activer la fonction de revert automatique sur tous les nœuds du cluster.

. Vérifiez l'état des membres du nœud sur le cluster : `cluster show`
+
L'exemple suivant affiche des informations sur la santé et l'éligibilité des nœuds du cluster :

+
[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
. Si vous avez supprimé la création automatique de cas, réactivez-la en appelant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----
. Rétablissez le niveau de privilège sur admin : `set -privilege admin`


*Informations connexes*

http://hwu.netapp.com["Hardware Universe"^]

http://support.netapp.com/NOW/download/software/cm_switches_ntap/["Page de description NetApp CN1601 et CN1610"^]

https://library.netapp.com/ecm/ecm_download_file/ECMP1118645["Guide de configuration et de configuration des commutateurs CN1601 et CN1610"^]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["Article 1010449 de la base de connaissances NetApp : comment supprimer la création automatique de dossiers pendant les fenêtres de maintenance planifiées"^]
