---
permalink: switch-netapp-cn1610/task-install-fastpath-software-and-rcf-files-on-netapp-cluster-switches.html 
sidebar: sidebar 
keywords: fastpath, software, install, netapp cluster switches, rcfs, ontap 
summary: 'Les étapes d"installation sont les mêmes pour les commutateurs de gestion NetApp CN1601 et les commutateurs de cluster CN1610 qui exécutent ONTAP 8.3.1 ou une version ultérieure. Cependant, les deux modèles nécessitent des logiciels et des RCFs différents.' 
---
= Installez le logiciel FASTPATH et les RCFC sur les commutateurs de cluster NetApp exécutant ONTAP 8.3.1 et versions ultérieures
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les étapes d'installation sont les mêmes pour les commutateurs de gestion NetApp CN1601 et les commutateurs de cluster CN1610 qui exécutent ONTAP 8.3.1 ou une version ultérieure. Cependant, les deux modèles nécessitent des logiciels et des RCFs différents.

.Avant de commencer
* Le cluster doit être un cluster totalement opérationnel.
* Il ne doit pas y avoir de carte réseau de cluster défectueuse, et tous les ports connectés des deux commutateurs de cluster doivent être fonctionnels.
* Tous les ports de cluster doivent être up.
* Toutes les interfaces logiques de cluster (LIF) doivent être active et ne doivent pas avoir été migrées.
* ONTAP (privilège : avancé) `cluster ping-cluster -node node1` la commande doit indiquer cela `larger than PMTU communication` a réussi sur tous les chemins.
* Vous devez utiliser les versions FASTPATH, RCF et ONTAP prises en charge.
+
Les versions RCF et FASTPATH peuvent comporter des dépendances entre la syntaxe de commande. La page de compatibilité des commutateurs répertorie les versions prises en charge. Voir http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["Commutateurs NetApp CN1601 et CN1610"^] pour plus d'informations.



.Description de la tâche
Les exemples de cette procédure utilisent la nomenclature des commutateurs et des nœuds suivante :

* les deux noms de commutateurs NetApp sont cs1 et cs2.
* Les noms d'interface logique (LIF) de cluster sont node1_clude1 et node1_clus2 pour node1, ainsi que node2_clude1 et node2_clus2 pour node2.
* Le nom du serveur virtuel de stockage (SVM) est Cluster.
* Le `cluster1::*>` l'invite indique le nom du cluster.
* les ports de cluster de chaque nœud sont nommés e0a et e0b.
+
Le https://hwu.netapp.com/["Hardware Universe"^] contient les ports réels de cluster pris en charge sur votre plateforme.

* Les liaisons ISL (Inter-Switch Links) prises en charge pour les commutateurs de cluster NetApp sont les ports 0/13 à 0/16.
* Les connexions de nœuds prises en charge pour les commutateurs de cluster NetApp sont les ports 0/1 à 0/12.
* L'exemple de cette procédure commence la mise à niveau sur le second commutateur, _cs2_.
* Les exemples de cette procédure utilisent deux nœuds, mais vous pouvez disposer d'un cluster pouvant atteindre 24 nœuds.
* Les exemples et résultats peuvent varier en fonction des versions FASTPATH, RCF et ONTAP.


.Étapes
. Afficher des informations relatives aux ports réseau sur le cluster :
+
`network port show -_ipspace cluster_`

+
L'exemple suivant montre le type de sortie de la commande :

+
[listing]
----
cluster1::> network port show -ipspace cluster
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
4 entries were displayed.
----
. Afficher les informations relatives aux LIFs sur le cluster :
+
`network interface show -_role cluster_`

+
L'exemple suivant montre les interfaces logiques sur le cluster. Dans cet exemple, le `-role` Paramètre affiche des informations sur les LIFs associées aux ports de cluster :

+
[listing]
----
cluster1::> network interface show -role cluster
  (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    10.254.66.82/16    node1         e0a     true
            node1_clus2  up/up    10.254.206.128/16  node1         e0b     true
            node2_clus1  up/up    10.254.48.152/16   node2         e0a     true
            node2_clus2  up/up    10.254.42.74/16    node2         e0b     true
4 entries were displayed.
----
. Sur chaque nœud respectif, à l'aide d'une LIF de gestion des nœuds, migrer le nœud 1_clus2 vers e0a sur le nœud 1 et le nœud 2_clus2 vers e0a sur le nœud 2 :
+
`network interface migrate`

+
Vous devez saisir les commandes sur les consoles de contrôleur qui possèdent les LIFs de cluster respectives.

+
[listing]
----

cluster1::> network interface migrate -vserver Cluster -lif node1_clus2 -destination-node node1 -destination-port e0a
cluster1::> network interface migrate -vserver Cluster -lif node2_clus2 -destination-node node2 -destination-port e0a
----
+

NOTE: Pour cette commande, le nom du cluster est sensible à la casse et la commande doit être exécutée sur chaque nœud. Il n'est pas possible d'exécuter cette commande dans le cluster LIF en général.

. Vérifiez que la migration a eu lieu à l'aide du `network interface show` commande sur un nœud.
+
L'exemple suivant montre que clus2 a migré vers le port e0a sur les nœuds node1 et node2 :

+
[listing]
----
cluster1::> **network interface show -role cluster**
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    10.254.66.82/16   node1          e0a     true
            node1_clus2  up/up    10.254.206.128/16 node1          e0a     false
            node2_clus1  up/up    10.254.48.152/16  node2          e0a     true
            node2_clus2  up/up    10.254.42.74/16   node2          e0a     false
4 entries were displayed.
----
. Définissez le niveau de privilège sur avancé, en saisissant y lorsque vous êtes invité à continuer :
+
`set -privilege advanced`

+
L'invite avancée (*>) apparaît.

. Arrêtez le port e0b sur les deux nœuds :
+
`network port modify -node _node_name_ -port _port_name_ -up-admin false`

+
Vous devez saisir les commandes sur les consoles de contrôleur qui possèdent les LIFs de cluster respectives.

+
L'exemple suivant montre les commandes pour arrêter le port e0b sur tous les nœuds :

+
[listing]
----
cluster1::*> network port modify -node node1 -port e0b -up-admin false
cluster1::*> network port modify -node node2 -port e0b -up-admin false
----
. Vérifiez que le port e0b est arrêté sur les deux nœuds :
+
`network port show`

+
[listing]
----
cluster1::*> network port show -role cluster

                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          down     9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          down     9000  auto/10000
4 entries were displayed.
----
. Arrêtez les ports ISL (Inter-Switch Link) sur cs1.
+
[listing]
----

(cs1) #configure
(cs1) (Config)#interface 0/13-0/16
(cs1) (Interface 0/13-0/16)#shutdown
(cs1) (Interface 0/13-0/16)#exit
(cs1) (Config)#exit
----
. Sauvegardez l'image active actuelle sur cs2.
+
[listing]
----
(cs2) # show bootvar

 Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     1.1.0.5     1.1.0.3            1.1.0.5            1.1.0.5

(cs2) # copy active backup
Copying active to backup
Copy operation successful
----
. Vérifiez la version en cours d'exécution du logiciel FASTPATH.
+
[listing]
----
(cs2) # show version

Switch: 1

System Description............................. NetApp CN1610, 1.1.0.5, Linux
                                                2.6.21.7
Machine Type................................... NetApp CN1610
Machine Model.................................. CN1610
Serial Number.................................. 20211200106
Burned In MAC Address.......................... 00:A0:98:21:83:69
Software Version............................... 1.1.0.5
Operating System............................... Linux 2.6.21.7
Network Processing Device...................... BCM56820_B0
Part Number.................................... 111-00893

--More-- or (q)uit


Additional Packages............................ FASTPATH QOS
                                                FASTPATH IPv6 Management
----
. Téléchargez le fichier image sur le commutateur.
+
La copie du fichier image sur l'image active signifie que lors du redémarrage, cette image établit la version FastPath en cours d'exécution. L'image précédente reste disponible comme sauvegarde.

+
[listing]
----
(cs2) #copy sftp://root@10.22.201.50//tftpboot/NetApp_CN1610_1.2.0.7.stk active
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 10.22.201.50
Path........................................... /tftpboot/
Filename....................................... NetApp_CN1610_1.2.0.7.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
SFTP Code transfer starting...


File transfer operation completed successfully.
----
. Confirmez les versions actuelles et suivantes de l'image de démarrage active :
+
`show bootvar`

+
[listing]
----
(cs2) #show bootvar

Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     1.1.0.8     1.1.0.8            1.1.0.8            1.2.0.7
----
. Installez la FCR compatible pour la nouvelle version d'image sur le commutateur.
+
Si la version RCF est déjà correcte, passez à l'étape 18 afin d'afficher les ports ISL.

+
[listing]
----
(cs2) #copy tftp://10.22.201.50//CN1610_CS_RCF_v1.2.txt nvram:script CN1610_CS_RCF_v1.2.scr

Mode........................................... TFTP
Set Server IP.................................. 10.22.201.50
Path........................................... /
Filename....................................... CN1610_CS_RCF_v1.2.txt
Data Type...................................... Config Script
Destination Filename........................... CN1610_CS_RCF_v1.2.scr

File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.


Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y


Validating configuration script...
[the script is now displayed line by line]

Configuration script validated.
File transfer operation completed successfully.
----
+

NOTE: Le `.scr` l'extension doit être définie comme faisant partie du nom du fichier avant d'appeler le script. Cette extension concerne le système d'exploitation FASTPATH.

+
Le commutateur valide automatiquement le script lorsqu'il est téléchargé sur le commutateur. La sortie va à la console.

. Vérifiez que le script a été téléchargé et enregistré dans le nom de fichier que vous lui avez donné.
+
[listing]
----
(cs2) #script list

Configuration Script Name        Size(Bytes)
-------------------------------- -----------
CN1610_CS_RCF_v1.2.scr                  2191

1 configuration script(s) found.
2541 Kbytes free.
----
. Appliquez le script au commutateur.
+
[listing]
----
(cs2) #script apply CN1610_CS_RCF_v1.2.scr

Are you sure you want to apply the configuration script? (y/n) y
[the script is now displayed line by line]...

Configuration script 'CN1610_CS_RCF_v1.2.scr' applied.
----
. Vérifiez que les modifications ont été appliquées au commutateur, puis enregistrez-les :
+
`show running-config`

+
[listing]
----
(cs2) #show running-config
----
. Enregistrez la configuration en cours de fonctionnement pour qu'elle devienne la configuration de démarrage lorsque vous redémarrez le commutateur.
+
[listing]
----
(cs2) #write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
. Redémarrez le commutateur.
+
[listing]
----
(cs2) #reload

The system has unsaved changes.
Would you like to save them now? (y/n) y

Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
. Reconnectez-vous, puis vérifiez que le commutateur exécute la nouvelle version du logiciel FASTPATH.
+
[listing]
----
(cs2) #show version

Switch: 1

System Description............................. NetApp CN1610, 1.2.0.7,Linux
                                                3.8.13-4ce360e8
Machine Type................................... NetApp CN1610
Machine Model.................................. CN1610
Serial Number.................................. 20211200106
Burned In MAC Address.......................... 00:A0:98:21:83:69
Software Version............................... 1.2.0.7
Operating System............................... Linux 3.8.13-4ce360e8
Network Processing Device...................... BCM56820_B0
Part Number.................................... 111-00893
CPLD version................................... 0x5


Additional Packages............................ FASTPATH QOS
                                                FASTPATH IPv6 Management
----
+
Une fois le redémarrage terminé, vous devez vous connecter pour vérifier la version d'image, afficher la configuration en cours d'exécution et rechercher la description sur l'interface 3/64, qui est le label de version pour le RCF.

. Mettre les ports ISL sur cs1, le commutateur actif.
+
[listing]
----
(cs1) #configure
(cs1) (Config) #interface 0/13-0/16
(cs1) (Interface 0/13-0/16) #no shutdown
(cs1) (Interface 0/13-0/16) #exit
(cs1) (Config) #exit
----
. Vérifiez que les liens ISL sont opérationnels.
+
`show port-channel 3/1`

+
Le champ État du lien doit indiquer `Up`.

+
[listing]
----
(cs1) #show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  False
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
. Mettez en place le port e0b sur tous les nœuds :
+
`network port modify`

+
Vous devez saisir les commandes sur les consoles de contrôleur qui possèdent les LIFs de cluster respectives.

+
L'exemple suivant montre que le port e0b est pris en charge sur les nœuds de nœuds 1 et de nœuds 2 :

+
[listing]
----
cluster1::*> network port modify -node node1 -port e0b -up-admin true
cluster1::*> network port modify -node node2 -port e0b -up-admin true
----
. Vérifiez que le port e0b est activé sur tous les nœuds :
+
`network port show -ipspace cluster`

+
[listing]
----
cluster1::*> network port show -ipspace cluster

                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
4 entries were displayed.
----
. Vérifier que le LIF est déjà chez lui (`true`) sur les deux nœuds :
+
`network interface show -_role cluster_`

+
[listing]
----
cluster1::*> network interface show -role cluster

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.66.82/16   node1         e0a     true
            node1_clus2  up/up    169.254.206.128/16 node1         e0b     true
            node2_clus1  up/up    169.254.48.152/16  node2         e0a     true
            node2_clus2  up/up    169.254.42.74/16   node2         e0b     true
4 entries were displayed.
----
. Afficher l'état des membres du nœud :
+
`cluster show`

+
[listing]
----
cluster1::*> cluster show

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
. Retour au niveau de privilège admin :
+
`set -privilege admin`

. Répétez les étapes 1 à 18 pour mettre à niveau le logiciel FASTPATH et RCF sur l'autre commutateur, cs1.
+
|===
| Si... | Alors... 


 a| 
Ne pas avoir besoin d'installer la FCR
 a| 
Passez à l'étape 18 pour terminer l'installation.



 a| 
Installation de la FCR nécessaire
 a| 
Passez à l'étape 13.

|===

