---
permalink: other-procedures/transition-to-two-node-switchless-cluster-index.html 
sidebar: sidebar 
keywords: transition, two-node, switchless, cluster, two, node 
summary: 'Vous pouvez passer à un cluster à deux nœuds qui utilise des commutateurs d"interconnexion de cluster à un cluster où deux nœuds sont directement connectés.' 
---
= Présentation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Si vous disposez déjà d'un cluster à deux nœuds avec des commutateurs d'interconnexion de cluster et qu'il exécute ONTAP 9.3 ou une version ultérieure, vous pouvez remplacer les commutateurs par des connexions directes et retour entre les nœuds.

Vous ne pouvez pas utiliser la fonctionnalité d'interconnexion de cluster sans commutateur avec plus de deux nœuds.

La transition vers une configuration de cluster sans commutateur à 2 nœuds n'assure pas de continuité de l'activité. La plupart des systèmes disposent de deux ports d'interconnexion de cluster dédiés sur chaque nœud, mais cette procédure peut également être utilisée pour les systèmes avec un plus grand nombre de ports d'interconnexion de cluster dédiés sur chaque nœud, tels que quatre, six ou huit.

Cette procédure décrit la transition d'un cluster avec un réseau de clusters commuté vers un cluster auquel deux nœuds sont directement connectés pour ONTAP 9.3 et les versions ultérieures.
