---
permalink: switch-cisco-92300/92300-overview.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: Si vous souhaitez créer des clusters ONTAP avec plus de deux nœuds, vous devez prendre en charge deux commutateurs de réseau de clusters. Vous pouvez utiliser des commutateurs de gestion supplémentaires, qui sont facultatifs. 
---
= Présentation du commutateur Cisco Nexus 92300YC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous souhaitez créer des clusters ONTAP avec plus de deux nœuds, vous devez prendre en charge deux commutateurs de réseau de clusters. Vous pouvez utiliser des commutateurs de gestion supplémentaires, qui sont facultatifs.

Vous pouvez installer le commutateur Cisco Nexus 92300YC (X190003/R) dans une armoire système NetApp ou une armoire tierce avec les supports standard inclus avec le commutateur.

Le tableau suivant répertorie le numéro de référence et la description du commutateur 92300YC, des ventilateurs et des alimentations électriques :

[cols="1,2"]
|===
| Numéro de référence | Description 


 a| 
190003
 a| 
Cisco 92300YC, CLSW, 48Pt10/25 Gb, 18Pt100G, PTSX (PTSX = échappement côté port)



 a| 
190003R
 a| 
Cisco 92300YC, CLSW, 48Pt10/25 Gb, 18Pt100G, PSIN (PSIN = admission côté port)



 a| 
X-NXA-FAN-35CFM-B
 a| 
Ventilateur, air d'admission côté orifice N9K de Cisco



 a| 
X-NXA-FAN-35CFM-F
 a| 
Ventilateur, air d'échappement côté port Cisco N9K



 a| 
X-NXA-PAC-650W-B
 a| 
Alimentation, Cisco 650W - prise d'air côté orifice



 a| 
X-NXA-PAC-650W-F
 a| 
Alimentation, échappement côté port Cisco 650W

|===
Détails du débit d'air du commutateur Cisco Nexus 92300YC :

* Flux d'air d'échappement côté port (air standard) - l'air froid pénètre dans le châssis par le ventilateur et les modules d'alimentation dans l'allée froide et s'échappe par l'extrémité du port du châssis dans l'allée chaude. Débit d'air d'échappement côté orifice avec coloration bleue.
* Air d'admission côté orifice (air inversé) - l'air froid pénètre dans le châssis par l'extrémité du port dans l'allée froide et s'échappe par le ventilateur et les modules d'alimentation dans l'allée chaude. Air d'admission côté port avec couleur bordeaux.


.Documentation disponible
Le tableau suivant répertorie la documentation disponible pour les commutateurs Cisco Nexus 92300YC.

|===


| Titre | Description 


 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/install-overview-cisco-92300.html["_Configurer les commutateurs de cluster Cisco® Nexus 92300YC_"^]
 a| 
Décrit comment configurer les commutateurs de cluster Cisco Nexus 92300YC.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/install-nxos-overview.html["_Installer les fichiers NX-OS et de configuration de référence (RCFs)_"^]
 a| 
Décrit l'installation de NX-OS et des fichiers de configuration de référence (RCFs) sur le commutateur de cluster Nexus 92300YC.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/configure-install-initial.html["_Configurer un nouveau commutateur Cisco Nexus 92300YC_"^]
 a| 
Décrit comment migrer des environnements utilisant des commutateurs Cisco plus anciens vers des environnements utilisant des commutateurs Cisco 92300YC.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/migrate-to-92300yc-overview.html["_Migrer d'un ancien commutateur Cisco vers un commutateur Cisco Nexus 92300YC_"^]
 a| 
Décrit la procédure à suivre pour remplacer un ancien commutateur Cisco par un commutateur de cluster Cisco Nexus 92300YC.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/migrate-to-2n-switched.html["_Migrer à partir d'un cluster sans commutateur à deux nœuds_"^]
 a| 
Décrit comment migrer d'un environnement de cluster sans commutateur à deux nœuds vers un environnement à deux nœuds avec commutateur à l'aide des commutateurs de cluster Cisco Nexus 92300YC.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/replace-92300yc.html["_Remplacer un commutateur de cluster Cisco Nexus 92300YC_"^]
 a| 
Décrit la procédure à suivre pour remplacer un commutateur Cisco Nexus 92300YC défectueux dans un cluster et télécharger le système d'exploitation du commutateur et le fichier de configuration de référence.

|===