---
permalink: switch-cisco-92300/components-92300.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: Si vous souhaitez créer des clusters ONTAP avec plus de deux nœuds, vous aurez besoin de deux commutateurs réseau de cluster compatibles.  Vous pouvez utiliser des commutateurs de gestion supplémentaires, qui sont optionnels. 
---
= Composants et références des commutateurs Cisco Nexus 92300YC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour l'installation et la maintenance du commutateur Cisco Nexus 92300YC, assurez-vous de consulter tous les composants du commutateur et leurs numéros de pièces. Voir le https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] pour plus de détails.

Le tableau suivant répertorie la référence et la description du commutateur 92300YC, des ventilateurs et des alimentations :

[cols="1,2"]
|===
| Numéro de pièce | Description 


 a| 
190003
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PTSX (PTSX = Port Side Exhaust)



 a| 
190003R
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PSIN (PSIN = Entrée côté port)



 a| 
X-NXA-FAN-35CFM-B
 a| 
Ventilateur, flux d'air d'entrée d'air côté port Cisco N9K



 a| 
X-NXA-FAN-35CFM-F
 a| 
Ventilateur, flux d'air d'évacuation côté port Cisco N9K



 a| 
X-NXA-PAC-650W-B
 a| 
Alimentation Cisco 650 W - entrée côté port



 a| 
X-NXA-PAC-650W-F
 a| 
Alimentation Cisco 650 W - évacuation côté port

|===
Détails du flux d'air du commutateur Cisco Nexus 92300YC :

* Flux d'air d'échappement côté port (air standard) -- L'air frais entre dans le châssis par le biais du ventilateur et des modules d'alimentation situés dans l'allée froide et s'échappe par l'extrémité du châssis située dans l'allée chaude.  Flux d'air d'échappement côté bâbord de couleur bleue.
* Flux d'air d'admission côté port (air inversé) -- L'air frais entre dans le châssis par l'extrémité du port dans l'allée froide et est évacué par le ventilateur et les modules d'alimentation dans l'allée chaude.  Prise d'air latérale de couleur bordeaux.


.Quelle est la prochaine étape
link:required-documentation-92300.html["Documents requis"].
