---
permalink: switch-cisco-92300/components-92300.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: Si vous souhaitez créer des clusters ONTAP avec plus de deux nœuds, vous aurez besoin de deux commutateurs réseau de cluster compatibles.  Vous pouvez utiliser des commutateurs de gestion supplémentaires, qui sont optionnels. 
---
= Composants et références des commutateurs Cisco Nexus 92300YC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour l'installation et la maintenance du commutateur Cisco Nexus 92300YC, assurez-vous de vérifier tous les composants du commutateur et les numéros de référence. Consultez la link:https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] pour plus de détails. Reportez-vous à link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["De quelles informations supplémentaires ai-je besoin pour installer mon équipement qui ne figure pas dans HWU ?"^] pour plus d'informations sur les exigences d'installation du commutateur.

Le tableau suivant répertorie la référence et la description du commutateur 92300YC, des ventilateurs et des alimentations :

[cols="1,2"]
|===
| Numéro de pièce | Description 


 a| 
190003
 a| 
Cisco 92300YC, CLSW, 48 ports 10/25 Go, 18 ports 100 G, PTSX (PTSX = évacuation côté ports)



 a| 
190003R
 a| 
Cisco 92300YC, CLSW, 48 ports 10/25 Go, 18 ports 100 Go, PSIN (PSIN = aspiration côté ports)



 a| 
X-NXA-FAN-35CFM-B
 a| 
Ventilateur, flux d'air d'admission côté port Cisco N9K



 a| 
X-NXA-FAN-35CFM-F
 a| 
Ventilateur, flux d'air d'évacuation côté port Cisco N9K



 a| 
X-NXA-PAC-650W-B
 a| 
Alimentation, Cisco 650W - entrée côté port



 a| 
X-NXA-PAC-650W-F
 a| 
Alimentation, Cisco 650W - évacuation côté port

|===
Détails du flux d'air du commutateur Cisco Nexus 92300YC :

* Flux d'air d'évacuation côté port (air standard) : l'air frais pénètre dans le châssis par les modules de ventilateur et d'alimentation situés dans l'allée froide et est évacué par l'extrémité port du châssis dans l'allée chaude. Flux d'air d'évacuation côté port avec une coloration bleue.
* Flux d'air d'admission côté port (air inversé) : l'air frais pénètre dans le châssis par l'extrémité des ports dans le couloir froid et est évacué par les modules de ventilateur et d'alimentation dans le couloir chaud. Flux d'air d'admission côté port avec une coloration bordeaux.


.Quelle est la prochaine étape
Une fois que vous avez confirmé vos composants et leurs numéros de pièces, vous pouvez consulter le link:required-documentation-92300.html["documentation requise"].
