---
permalink: switch-cisco-92300/configure-overview.html 
sidebar: sidebar 
keywords: confiure 92300yc cluster switch, cisco 92300yc 
summary: Vous pouvez configurer un nouveau commutateur Nexus 92300YC en suivant les étapes décrites dans ce chapitre. 
---
= Configurez un nouveau commutateur Cisco Nexus 92300YC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer un nouveau commutateur Nexus 92300YC en suivant les étapes décrites dans ce chapitre.

L'installation du commutateur Nexus 92300YC sur les systèmes exécutant ONTAP 9.6 et versions ultérieures commence par la configuration d'une adresse IP et d'une configuration permettant au commutateur de communiquer via l'interface de gestion. Vous pouvez ensuite installer le logiciel NX-OS et le fichier RCF (Reference Configuration File). Cette procédure est destinée à préparer le commutateur Nexus 92300YC avant l'ajout de contrôleurs.

Les exemples de cette procédure utilisent la nomenclature des commutateurs et des nœuds suivante :

* Les noms des commutateurs Nexus 92300YC sont `cs1` et `cs2`.
* L'exemple utilisé dans cette procédure lance la mise à niveau sur le second commutateur, _*cs2*._
* Les noms LIF de cluster sont `node1_clus1` et `node1_clus2` pour le noeud 1, et `node2_clus1` et `node2_clus2` pour le noeud 2.
* Le nom IPspace est `Cluster`.
* Le `cluster1::*>` l'invite indique le nom du cluster.
* Les ports de cluster de chaque nœud sont nommés `e0a` et `e0b`.
+
Voir la link:https://hwu.netapp.com/Home/Index["_Hardware Universe_"^] pour les ports réels de cluster pris en charge sur votre plateforme.

* Les liaisons interswitch (ISL) prises en charge par les commutateurs Nexus 92300YC sont les ports 1/65 et 1/66.
* Les connexions de nœud prises en charge pour les commutateurs Nexus 92300YC sont les ports 1/1 à 1/66.
* Les exemples de cette procédure utilisent deux nœuds, mais vous pouvez disposer d'un cluster pouvant atteindre 24 nœuds.

