---
permalink: switch-cisco-92300/configure-install-initial.html 
sidebar: sidebar 
keywords: install cisco 92300YC cluster switch, cisco nx 92300yc 
summary: 'Vous pouvez utiliser cette procédure pour effectuer l"installation initiale du commutateur Cisco Nexus 92300YC.' 
---
= Configurer le commutateur Cisco Nexus 92300YC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez cette procédure pour installer et configurer le commutateur Cisco Nexus 92300YC.

.Étapes
. Connectez le port série à un hôte ou à un port série.
. Connectez le port de gestion (du côté opposé aux ports du commutateur) au même réseau que celui où se trouve votre serveur SFTP.
. Sur la console, configurez les paramètres série côté hôte :
+
** 9600 baud
** 8 bits de données
** 1 butée
** parité : aucune
** contrôle de flux : aucun


. Lors du premier démarrage ou du redémarrage après effacement de la configuration en cours, le commutateur Nexus 92300YC effectue une boucle de démarrage.  Interrompez ce cycle en tapant *oui* pour annuler la mise sous tension automatique.
+
La configuration du compte d'administrateur système s'affiche.

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
$ VDC-1 %$ %POAP-2-POAP_INFO:   - Abort Power On Auto Provisioning [yes - continue with normal setup, skip - bypass password and basic configuration, no - continue with Power On Auto Provisioning] (yes/skip/no)[no]: *y*
Disabling POAP.......Disabling POAP
2019 Apr 10 00:36:17 switch %$ VDC-1 %$ poap: Rolling back, please wait... (This may take 5-15 minutes)

          ---- System Admin Account Setup ----

Do you want to enforce secure password standard (yes/no) [y]:
----
====
. Tapez *y* pour appliquer la norme de mot de passe sécurisé :
+
[listing, subs="+quotes"]
----
Do you want to enforce secure password standard (yes/no) [y]: *y*
----
. Saisissez et confirmez le mot de passe de l'utilisateur admin :
+
[listing]
----
Enter the password for "admin":
Confirm the password for "admin":
----
. Tapez *oui* pour accéder à la boîte de dialogue Configuration système de base.
+
.Afficher un exemple
[%collapsible]
====
[listing]
----
This setup utility will guide you through the basic configuration of
the system. Setup configures only enough connectivity for management
of the system.

Please register Cisco Nexus9000 Family devices promptly with your
supplier. Failure to register may affect response times for initial
service calls. Nexus9000 devices must be registered to receive
entitled support services.

Press Enter at anytime to skip a dialog. Use ctrl-c at anytime
to skip the remaining dialogs.

Would you like to enter the basic configuration dialog (yes/no):
----
====
. Créer un autre compte de connexion :
+
[listing]
----
Create another login account (yes/no) [n]:
----
. Configurer les chaînes de communauté SNMP en lecture seule et en lecture-écriture :
+
[listing]
----
Configure read-only SNMP community string (yes/no) [n]:

Configure read-write SNMP community string (yes/no) [n]:
----
. Configurer le nom du commutateur de cluster :
+
[listing, subs="+quotes"]
----
Enter the switch name : *cs2*
----
. Configurer l'interface de gestion hors bande :
+
[listing, subs="+quotes"]
----
Continue with Out-of-band (mgmt0) management configuration? (yes/no) [y]: *y*

Mgmt0 IPv4 address : 172.22.133.216

Mgmt0 IPv4 netmask : 255.255.224.0

Configure the default gateway? (yes/no) [y]: *y*

IPv4 address of the default gateway : 172.22.128.1
----
. Configurer les options IP avancées :
+
[listing, subs="+quotes"]
----
Configure advanced IP options? (yes/no) [n]: *n*
----
. Configurer les services Telnet :
+
[listing, subs="+quotes"]
----
Enable the telnet service? (yes/no) [n]: *n*
----
. Configurer les services SSH et les clés SSH :
+
[listing, subs="+quotes"]
----
Enable the ssh service? (yes/no) [y]: *y*

       Type of ssh key you would like to generate (dsa/rsa) [rsa]: *rsa*

       Number of rsa key bits <1024-2048> [1024]: *2048*
----
. Configurer les autres paramètres :
+
[listing, subs="+quotes"]
----
Configure the ntp server? (yes/no) [n]: *n*

  Configure default interface layer (L3/L2) [L2]: *L2*

  Configure default switchport interface state (shut/noshut) [noshut]: *noshut*

  Configure CoPP system profile (strict/moderate/lenient/dense) [strict]: *strict*
----
. Vérifiez les informations du commutateur et enregistrez la configuration :
+
[listing, subs="+quotes"]
----
Would you like to edit the configuration? (yes/no) [n]: *n*

Use this configuration and save it? (yes/no) [y]: *y*

[########################################] 100%
Copy complete, now saving to disk (please wait)...
Copy complete.
----


.Quelle est la prochaine étape ?
link:install-nxos-overview.html["Préparez-vous à installer le logiciel NX-OS et RCF."].
