---
permalink: switch-cisco-92300/index.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: Si vous souhaitez créer des clusters ONTAP avec plus de deux nœuds, vous devez prendre en charge deux commutateurs de réseau de clusters. Vous pouvez utiliser des commutateurs de gestion supplémentaires, qui sont facultatifs. 
---
= Présentation et configuration requise : commutateurs Cisco Nexus 92300YC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour l'installation et la maintenance du commutateur Cisco Nexus 92300YC, vérifiez toutes les conditions requises et la documentation recommandée.

Si vous souhaitez créer des clusters ONTAP avec plus de deux nœuds, vous devez prendre en charge deux commutateurs de réseau de clusters. Vous pouvez utiliser des commutateurs de gestion supplémentaires, qui sont facultatifs.



== Composants du commutateur

Le tableau suivant répertorie le numéro de référence et la description du commutateur 92300YC, des ventilateurs et des alimentations électriques :

[cols="1,2"]
|===
| Numéro de référence | Description 


 a| 
190003
 a| 
Cisco 92300YC, CLSW, 48Pt10/25 Gb, 18Pt100G, PTSX (PTSX = échappement côté port)



 a| 
190003R
 a| 
Cisco 92300YC, CLSW, 48Pt10/25 Gb, 18Pt100G, PSIN (PSIN = admission côté port)



 a| 
X-NXA-FAN-35CFM-B
 a| 
Ventilateur, air d'admission côté orifice N9K de Cisco



 a| 
X-NXA-FAN-35CFM-F
 a| 
Ventilateur, air d'échappement côté port Cisco N9K



 a| 
X-NXA-PAC-650W-B
 a| 
Alimentation, Cisco 650W - prise d'air côté orifice



 a| 
X-NXA-PAC-650W-F
 a| 
Alimentation, échappement côté port Cisco 650W

|===
Détails du débit d'air du commutateur Cisco Nexus 92300YC :

* Flux d'air d'échappement côté port (air standard) -- l'air froid pénètre dans le châssis par le ventilateur et les modules d'alimentation dans l'allée froide et s'échappe par l'extrémité du port du châssis dans l'allée chaude. Débit d'air d'échappement côté orifice avec coloration bleue.
* Air d'admission côté orifice (air inversé) -- l'air froid pénètre dans le châssis par l'extrémité de l'orifice dans l'allée froide et s'échappe par le ventilateur et les modules d'alimentation dans l'allée chaude. Air d'admission côté port avec couleur bordeaux.




== Configuration requise

Pour configurer votre cluster, vous devez disposer du nombre et du type appropriés de câbles et de connecteurs de câbles pour les commutateurs. Selon le type de switch que vous configurez au départ, vous devez vous connecter au port console des commutateurs avec le câble console inclus ; vous devez également fournir des informations réseau spécifiques.



== Exigences liées au réseau

Vous avez besoin des informations réseau suivantes pour toutes les configurations de commutateurs :

* Sous-réseau IP pour le trafic du réseau de gestion
* Noms d'hôte et adresses IP pour chaque contrôleur du système de stockage et tous les commutateurs applicables
* La plupart des contrôleurs de système de stockage sont gérés par l'interface e0M en vous connectant au port de service Ethernet (icône de clé anglaise). Sur les systèmes AFF A800 et AFF A700, l'interface e0M utilise un port Ethernet dédié.


Reportez-vous à la https://hwu.netapp.com["Hardware Universe"^] pour obtenir les informations les plus récentes.



== Configuration requise pour le service d'appel intelligent

Smart Call Home surveille le matériel et les composants logiciels de votre réseau afin de générer une notification par e-mail des conditions système critiques. Lorsqu'un événement se produit sur votre terminal, l'appel intelligent affiche une alerte pour tous les destinataires configurés dans votre profil de destination.

Vous devez configurer un commutateur réseau de cluster pour communiquer par courrier électronique avec le système d'appel intelligent. Vous pouvez configurer votre commutateur de réseau de cluster pour tirer parti de la fonction de prise en charge intégrée de Smart Call Home de Cisco.

Avant de pouvoir utiliser la fonction d'appel intelligent, vous devez prendre en compte les considérations suivantes :

* Un serveur de messagerie doit être en place.
* Le commutateur doit disposer d'une connexion IP au serveur de messagerie.
* Le nom du contact (contact du serveur SNMP), le numéro de téléphone et l'adresse postale doivent être configurés. Ceci est nécessaire pour déterminer l'origine des messages reçus.
* Un CCO ID doit être associé à un contrat Cisco SMARTnet Service approprié pour votre entreprise.
* Le service Cisco SMARTnet doit être en place pour que le périphérique soit enregistré.


Le http://www.cisco.com/c/en/us/products/switches/index.html["Site d'assistance Cisco"^] Contient des informations sur les commandes permettant de configurer l'appel intelligent.



== Exigences de documentation

Vous avez besoin de documentation spécifique sur les commutateurs et les contrôleurs pour configurer les commutateurs Cisco Nexus 92300YC et le cluster ONTAP.



=== Documentation du commutateur

Pour configurer les commutateurs Cisco Nexus 92300YC, vous avez besoin de la documentation suivante du https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Prise en charge des commutateurs Cisco Nexus 9000 Series"^] page :

[cols="1,2"]
|===
| Titre du document | Description 


 a| 
_Nexus 9000 Series - Guide d'installation matérielle_
 a| 
Fournit des informations détaillées sur les exigences du site, les détails du matériel du commutateur et les options d'installation.



 a| 
_Guides de configuration du logiciel des commutateurs Cisco Nexus série 9000_ (choisissez le guide de la version NX-OS installée sur vos commutateurs)
 a| 
Fournit les informations de configuration initiale des switchs nécessaires avant de configurer le switch pour le fonctionnement de ONTAP.



 a| 
_Guide de mise à niveau et de mise à niveau logicielles NX-OS de la gamme Cisco Nexus 9000_ (choisissez le guide de la version NX-OS installée sur vos commutateurs)
 a| 
Le fournit des informations sur la procédure de rétrogradation du commutateur vers le logiciel de commutation pris en charge par ONTAP, si nécessaire.



 a| 
_Index maître de référence des commandes Cisco Nexus série 9000 NX-OS_
 a| 
Fournit des liens vers les différentes références de commande fournies par Cisco.



 a| 
_Cisco Nexus 9000 MIB référence_
 a| 
Décrit les fichiers MIB (Management information base) des commutateurs Nexus 9000.



 a| 
Référence de message du système NX-OS de la gamme Nexus 9000_
 a| 
Décrit les messages système relatifs aux commutateurs Cisco Nexus série 9000, à ceux qui sont à titre d'information et autres susceptibles d'aider à diagnostiquer les problèmes de liens, de matériel interne ou de logiciel du système.



 a| 
_Notes de version de Cisco Nexus 9000 Series NX-OS (Choisissez les notes pour la version NX-OS installée sur vos commutateurs)_
 a| 
Décrit les fonctionnalités, les bugs et les limites de la gamme Cisco Nexus 9000.



 a| 
Conformité réglementaire et informations de sécurité pour Cisco Nexus 9000 Series
 a| 
Fournit des informations réglementaires, de sécurité et de conformité aux organismes internationaux pour les commutateurs de la gamme Nexus 9000.

|===


=== Documentation sur les systèmes ONTAP

Pour configurer un système ONTAP, vous avez besoin des documents suivants pour votre version du système d'exploitation à partir du https://docs.netapp.com/ontap-9/index.jsp["Centre de documentation ONTAP 9"^].

[cols="1,2"]
|===
| Nom | Description 


 a| 
Instructions d'installation et de configuration spécifiques au contrôleur_
 a| 
Décrit l'installation du matériel NetApp.



 a| 
Documentation ONTAP
 a| 
Fournit des informations détaillées sur tous les aspects des versions de ONTAP.



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
Fournit des informations sur la compatibilité et la configuration matérielle NetApp.

|===


=== Documentation du kit de rails et de l'armoire

Pour installer un commutateur Cisco Nexus 92300YC dans une armoire NetApp, consultez la documentation matérielle suivante.

[cols="1,2"]
|===
| Nom | Description 


 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["Armoire système 42U, Guide profond"^]
 a| 
Le décrit les unités remplaçables sur site associées à l'armoire système 42U, et fournit des instructions de maintenance et de remplacement des unités remplaçables sur site.



 a| 
link:install-switch-and-passthrough-panel.html["Installez un commutateur Cisco Nexus 92300YC dans une armoire NetApp"]
 a| 
Décrit l'installation d'un commutateur Cisco Nexus 92300YC dans une armoire NetApp à quatre montants.

|===