---
permalink: switch-cisco-92300/install-switch-92300yc.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 92300YC 
summary: Suivez cette procédure pour installer le commutateur Cisco Nexus 92300YC. 
---
= Installer le commutateur de cluster 92300YC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez cette procédure pour installer et configurer le commutateur Cisco Nexus 92300YC.

.Avant de commencer
Assurez-vous d'avoir les éléments suivants :

* Accès à un serveur HTTP, FTP ou TFTP sur le site d'installation pour télécharger les versions NX-OS et de fichier de configuration de référence (RCF) applicables.
* Version NX-OS applicable, téléchargée depuis https://software.cisco.com/download/home["Téléchargement de logiciels Cisco"^] page.
* Licences applicables, informations sur le réseau et la configuration, et câbles.
* Complétélink:setup-worksheet-92300yc.html["fiches de câblage"] .
* Fichiers de configuration de ressources (RCF) applicables pour les réseaux de cluster et de gestion NetApp, téléchargeables depuis le site de support NetApp . http://mysupport.netapp.com/["monsupport.netapp.com"^] .  Tous les commutateurs de réseau de cluster et de réseau de gestion Cisco sont livrés avec la configuration d'usine standard Cisco . Ces commutateurs disposent également de la version actuelle du logiciel NX-OS mais n'ont pas les RCF chargés.
* link:required-documentation-92300.html["Documentation requise pour le commutateur et ONTAP"].


.Étapes
. Installez le réseau de cluster ainsi que les commutateurs et contrôleurs du réseau de gestion.
+
[cols="1,2"]
|===
| Si vous installez le... | Alors... 


 a| 
Cisco Nexus 92300YC dans une armoire système NetApp
 a| 
Consultez le guide _Installation d'un commutateur de cluster Cisco Nexus 92300YC et d'un panneau de transfert dans une armoire NetApp pour obtenir des instructions sur l'installation du commutateur dans une armoire NetApp .



 a| 
Équipement dans une baie de télécommunications
 a| 
Consultez les procédures fournies dans les guides d'installation du matériel de commutation et les instructions d'installation et de configuration de NetApp .

|===
. Câblez les commutateurs du réseau de cluster et du réseau de gestion aux contrôleurs en utilisant les feuilles de câblage remplies.
. Mise sous tension des commutateurs et contrôleurs du réseau de cluster et du réseau de gestion.


.Quelle est la prochaine étape ?
Vous pouvez, si vous le souhaitez, link:install-switch-netapp-cabinet-92300yc.html["installer un commutateur Cisco Nexus 3223C dans une armoire NetApp"]. Sinon, allez à link:cabling-considerations-92300.html["Vérifier le câblage et la configuration"].
