---
permalink: switch-cisco-92300/migrate-to-92300yc-overview.html 
sidebar: sidebar 
keywords: migrate to cisco nx 92300yc cluster switch,new cluster switch migration 
summary: 'Vous devez connaître certaines informations de configuration, les connexions de ports et les exigences de câblage lorsque vous remplacez d"anciens commutateurs de cluster Cisco Nexus par des commutateurs de cluster Cisco Nexus 92300YC.' 
---
= Migration d'un commutateur Cisco vers un commutateur Cisco Nexus 92300YC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez connaître certaines informations de configuration, les connexions de ports et les exigences de câblage lorsque vous remplacez d'anciens commutateurs de cluster Cisco Nexus par des commutateurs de cluster Cisco Nexus 92300YC.

* Les commutateurs de cluster suivants sont pris en charge :
+
** Nexus 92300YC
** Nexus 5596UP
** Nexus 5020
** Nexus 5010


* Les commutateurs de cluster utilisent les ports suivants pour les connexions aux nœuds :
+
** Ports e1/1-48 (10/25 GbE), e1/49-64 (40/100 GbE) : Nexus 92300YC
** Ports e1/1-40 (10 GbE) : Nexus 5596UP
** Ports e1/1-32 (10 GbE) : Nexus 5020
** Ports e1/1-12, e2/1-6 (10 GbE) : Nexus 5010 avec module d'extension


* Les commutateurs de cluster utilisent les ports ISL (Inter-Switch Link) suivants :
+
** Ports e1/65-66 (100 GbE) : Nexus 92300YC
** Ports e1/41-48 (10 GbE) : Nexus 5596UP
** Ports e1/33-40 (10 GbE) : Nexus 5020
** Ports e1/13-20 (10 GbE) : Nexus 5010


* Le https://hwu.netapp.com/SWITCH/INDEX["_Hardware Universe_"^] le contient des informations sur le câblage pris en charge pour tous les commutateurs de cluster.
* Vous avez configuré certains ports sur les commutateurs Nexus 92300YC pour fonctionner à 10 GbE ou 40 GbE.
* Vous avez planifié, migré et documenté une connectivité 10 GbE et 40 GbE depuis les nœuds vers les commutateurs de cluster Nexus 92300YC.
* Les versions ONTAP et NX-OS prises en charge dans cette procédure se trouvent sur le https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Commutateurs Ethernet Cisco"^] page.
+

NOTE: Une fois la migration terminée, vous devrez peut-être installer le fichier de configuration requis pour prendre en charge le Cluster Switch Health Monitor (CSHM) pour les commutateurs de cluster 92300YC. Voir link:setup-install-cshm-file.html["Installez le fichier de configuration CSHM (Cluster Switch Health Monitor)"] pour plus d'informations.


