---
permalink: switch-cisco-92300/required-documentation-92300.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: 'Pour l"installation et la maintenance du commutateur Cisco Nexus 92300YC, consultez tous les documents recommandés.' 
---
= Documentation requise pour les commutateurs Cisco Nexus 92300YC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour l'installation et la maintenance du commutateur Cisco Nexus 92300YC, consultez tous les documents recommandés.



== Documentation du commutateur

Pour configurer les commutateurs Cisco Nexus 92300YC, vous avez besoin de la documentation suivante du https://www.cisco.com/site/us/en/products/networking/cloud-networking-switches/nexus-9200-series-switches/index.html["Prise en charge des commutateurs Cisco Nexus 9000 Series"^] page:

[cols="1,2"]
|===
| Titre du document | Description 


 a| 
_Nexus 9000 Series - Guide d'installation matérielle_
 a| 
Fournit des informations détaillées sur les exigences du site, les détails du matériel du commutateur et les options d'installation.



 a| 
_Guides de configuration du logiciel des commutateurs Cisco Nexus série 9000_ (choisissez le guide de la version NX-OS installée sur vos commutateurs)
 a| 
Fournit les informations de configuration initiale des switchs nécessaires avant de configurer le switch pour le fonctionnement de ONTAP.



 a| 
_Guide de mise à niveau et de mise à niveau logicielles NX-OS de la gamme Cisco Nexus 9000_ (choisissez le guide de la version NX-OS installée sur vos commutateurs)
 a| 
Le fournit des informations sur la procédure de rétrogradation du commutateur vers le logiciel de commutation pris en charge par ONTAP, si nécessaire.



 a| 
_Index maître de référence des commandes Cisco Nexus série 9000 NX-OS_
 a| 
Fournit des liens vers les différentes références de commande fournies par Cisco.



 a| 
_Cisco Nexus 9000 MIB référence_
 a| 
Décrit les fichiers MIB (Management information base) des commutateurs Nexus 9000.



 a| 
Référence de message du système NX-OS de la gamme Nexus 9000_
 a| 
Décrit les messages système relatifs aux commutateurs Cisco Nexus série 9000, à ceux qui sont à titre d'information et autres susceptibles d'aider à diagnostiquer les problèmes de liens, de matériel interne ou de logiciel du système.



 a| 
_Notes de version de Cisco Nexus 9000 Series NX-OS (Choisissez les notes pour la version NX-OS installée sur vos commutateurs)_
 a| 
Décrit les fonctionnalités, les bugs et les limites de la gamme Cisco Nexus 9000.



 a| 
Conformité réglementaire et informations de sécurité pour Cisco Nexus 9000 Series
 a| 
Fournit des informations réglementaires, de sécurité et de conformité aux organismes internationaux pour les commutateurs de la gamme Nexus 9000.

|===


== Documentation sur les systèmes ONTAP

Pour configurer un système ONTAP, vous avez besoin des documents suivants pour votre version du système d'exploitation de  https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9"^] .

[cols="1,2"]
|===
| Nom | Description 


 a| 
Instructions d'installation et de configuration spécifiques au contrôleur_
 a| 
Décrit l'installation du matériel NetApp.



 a| 
Documentation ONTAP
 a| 
Fournit des informations détaillées sur tous les aspects des versions de ONTAP.



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
Fournit des informations sur la compatibilité et la configuration matérielle NetApp.

|===


== Documentation du kit de rails et de l'armoire

Pour installer un commutateur Cisco Nexus 92300YC dans une armoire NetApp, consultez la documentation matérielle suivante.

[cols="1,2"]
|===
| Nom | Description 


 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["Armoire système 42U, Guide profond"^]
 a| 
Le décrit les unités remplaçables sur site associées à l'armoire système 42U, et fournit des instructions de maintenance et de remplacement des unités remplaçables sur site.



 a| 
link:install-switch-netapp-cabinet-92300yc.html["Installer un commutateur Cisco Nexus 92300YC dans une armoire NetApp"]
 a| 
Décrit l'installation d'un commutateur Cisco Nexus 92300YC dans une armoire NetApp à quatre montants.

|===