---
permalink: switch-cisco-92300/setup-install-cshm-file.html 
sidebar: sidebar 
keywords: 'install, applicable, configuration, file, cluster, switch, health, monitor, nexus, ontap, install the cluster switch health monitor (csm) configuration file for 92300yc switches - cisco nexus 9336c-fx2' 
summary: 'Cette procédure permet d"installer le fichier de configuration applicable pour la surveillance de l"état du commutateur de cluster des commutateurs de cluster Nexus 92300YC.' 
---
= Installez le fichier de configuration CSHM (Cluster Switch Health Monitor)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez cette procédure pour installer le fichier de configuration applicable pour la surveillance de l'état du commutateur de cluster des commutateurs de cluster Nexus 92300YC.

Dans ONTAP versions 9.5P7 et antérieures et 9.6P2 et antérieures, vous devez télécharger séparément le fichier de configuration du moniteur d'intégrité du commutateur de cluster. Dans ONTAP versions 9.5P8 et ultérieures, 9.6P3 et versions ultérieures, et 9.7 et versions ultérieures, le fichier de configuration du moniteur d'état du commutateur de cluster est fourni avec ONTAP.

.Ce dont vous avez besoin
Avant de configurer le moniteur d'état du commutateur pour les commutateurs de cluster 92300YC, assurez-vous que le cluster ONTAP est opérationnel.


NOTE: Vous devez également activer SSH pour utiliser toutes les fonctions disponibles dans CSHM.

.Étapes
. Téléchargez le fichier zip de la configuration du switch de cluster Health Monitor sur la base de la version ONTAP correspondante. Ce fichier est disponible à partir du https://mysupport.netapp.com/NOW/cgi-bin/software/["Téléchargement de logiciels NetApp"^] page.
+
.. Sur la page de téléchargement du logiciel, sélectionnez *changer les fichiers de configuration du moniteur d'intégrité*
.. Sélectionnez plate-forme = *ONTAP* et cliquez sur *Go!*
.. Sur la page changer de fichiers de configuration du moniteur d'intégrité pour ONTAP, cliquez sur *Afficher et télécharger*
.. Sur la page Switch Health Monitor Configuration Files for ONTAP - Description, cliquez sur *Download* pour le modèle de commutateur de cluster applicable, par exemple : *Cisco Nexus 92300YC*
.. Sur la page Contrat de licence utilisateur final, cliquez sur *Accept*
.. Sur la page de téléchargement des fichiers de configuration Switch Health Monitor pour ONTAP, sélectionnez le fichier de configuration approprié, par exemple *Cisco_Nexus_92300YC.zip*


. Chargez le fichier zip applicable sur votre serveur Web interne où l'adresse IP est X.X.X.X.
+
Pour une adresse IP de serveur Web interne de 192.168.2.20 et en supposant qu'il existe un répertoire /usr/download, vous pouvez télécharger votre fichier zip sur votre serveur Web à l'aide de scp:

+
[listing]
----
% scp Cisco_Nexus_92300YC.zip admin@192.168.2.20:/usr/download/Cisco_Nexus_92300YC.zip
----
. Accéder au paramètre de mode avancé à partir de l'un des systèmes ONTAP du cluster, à l'aide de la commande set-Privilege Advanced :
+
[listing]
----
cluster1::> set -privilege advanced
----
. Exécuter la commande de configuration du moniteur d'intégrité des commutateurs, cluster-commutateur configure-Health-Monitor -node * -package-url X. X.T.T.T.T.T.T.T.T., du point_de_télécharger_zip_file :
+
[listing]
----
cluster1::> system cluster-switch configure-health-monitor -node * -package-url 192.168.2.20/usr/download/Cisco_Nexus_92300YC.zip
----
. Vérifiez que la sortie de la commande contient la chaîne de texte « le pack téléchargé a été correctement traité ». En cas d'erreur, contactez le support NetApp.
. Exécutez la commande system cluster-switch show sur le système ONTAP et assurez-vous que les commutateurs du cluster sont détectés avec le champ surveillé défini sur « vrai ».
+
[listing]
----
cluster1::> system cluster-switch show
----
+

NOTE: Si vous restaurez à tout moment une version antérieure de ONTAP, vous devrez réinstaller le fichier de configuration CSHM pour activer la surveillance de l'état du commutateur des commutateurs de cluster 92300YC.


