---
permalink: switch-cshm/config-overview.html 
sidebar: sidebar 
keywords: cshm, cluster, storage, switch logs, debugging, collection 
summary: 'Le contrôle de l"état des commutateurs Ethernet (CSHM) est chargé de garantir le bon fonctionnement des commutateurs réseau de cluster et de stockage et de collecter les journaux des commutateurs à des fins de débogage.' 
---
= Découvrez comment configurer le contrôle de l'état des commutateurs Ethernet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le contrôle de l'état des commutateurs Ethernet (CSHM) est responsable de garantir l'intégrité opérationnelle des commutateurs réseau et de collecter les journaux des commutateurs à des fins de débogage.

Avant de pouvoir utiliser CSHM pour surveiller vos commutateurs réseau, vous devez configurer la collecte des journaux et, éventuellement, configurer SNMPv3 pour une sécurité renforcée. La collecte des journaux est requise pour que CSHM puisse recueillir les journaux des commutateurs et les données de diagnostic. SNMPv3 assure une communication sécurisée entre ONTAP et vos commutateurs.

* link:config-log-collection.html["Configurer la collecte des journaux"]
* link:config-snmpv3.html["Configurer SNMPv3 (facultatif)"]

