---
permalink: switch-cshm/config-log-collection.html 
sidebar: sidebar 
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation 
summary: 'La fonction de collecte des journaux du moniteur d"intégrité des commutateurs Ethernet (CSHM) est utilisée pour collecter les journaux des commutateurs de réseau de cluster ou de stockage dans ONTAP.' 
---
= Configurer la collecte des journaux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le moniteur d'intégrité des commutateurs Ethernet (CSHM) est responsable de garantir l'intégrité opérationnelle des commutateurs réseau de cluster et de stockage et de collecter les journaux de commutation à des fins de débogage.  Cette procédure vous guide tout au long du processus de configuration de la collecte, de la demande de journaux *Support* détaillés et de l'activation d'une collecte horaire de données *Périodiques* collectées par AutoSupport.

*REMARQUE :* Si vous activez le mode FIPS, vous devez effectuer les opérations suivantes :

[NOTE]
====
. Régénérez les clés SSH sur le commutateur en suivant les instructions du fournisseur.
. Régénérer les clés SSH dans ONTAP à l'aide de `debug system regenerate-systemshell-key-pair`
. Réexécutez la routine de configuration de la collecte des journaux en utilisant `system switch ethernet log setup-password` commande


====


== Avant de commencer

* L'utilisateur doit avoir accès à l'interrupteur `show` commandes.  Si ces éléments ne sont pas disponibles, créez un nouvel utilisateur et accordez-lui les autorisations nécessaires.
* La surveillance de l'état du commutateur doit être activée pour celui-ci.  Vérifiez cela en vous assurant que `Is Monitored:` Le champ est défini sur *vrai* dans la sortie de `system switch ethernet show` commande.
* Pour la collecte des journaux avec les commutateurs Broadcom et Cisco :
+
** L'utilisateur local doit disposer de privilèges d'administrateur réseau.
** Un nouvel utilisateur doit être créé sur le commutateur pour chaque configuration de cluster avec collecte de journaux activée.  Ces commutateurs ne prennent pas en charge plusieurs clés SSH pour un même utilisateur.  Toute configuration supplémentaire de collecte de journaux effectuée écrase toutes les clés SSH préexistantes de l'utilisateur.


* Pour la collecte des journaux de support avec les commutateurs NVIDIA , l'utilisateur chargé de la collecte des journaux doit être autorisé à exécuter le programme. `cl-support` commander sans avoir à fournir de mot de passe.  Pour autoriser cette utilisation, exécutez la commande :
+
`echo '_<user>_ ALL = NOPASSWD: /usr/cumulus/bin/cl-support' | sudo EDITOR='tee -a' visudo -f /etc/sudoers.d/cumulus`





== Étapes

[role="tabbed-block"]
====
.ONTAP 9.15.1 et versions ultérieures
--
. Pour configurer la collecte des journaux, exécutez la commande suivante pour chaque commutateur.  Vous êtes invité à saisir le nom du commutateur, le nom d'utilisateur et le mot de passe pour la collecte des journaux.
+
*REMARQUE :* Si vous répondez « oui » à l’invite de spécification de l’utilisateur, assurez-vous que celui-ci dispose des autorisations nécessaires, comme indiqué dans<<Avant de commencer>> .

+
[source, cli]
----
system switch ethernet log setup-password
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*

Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----



NOTE: Pour CL 5.11.1, créez l'utilisateur *cumulus* et répondez *y* à l'invite suivante : Souhaitez-vous spécifier un utilisateur autre que admin pour la collecte des journaux ?  {o|n}: *o*

. [[étape 2]]Activer la collecte périodique des journaux :
+
[source, cli]
----
system switch ethernet log modify -device <switch-name> -periodic-enabled true
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -periodic-enabled true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

*cs1*: Periodic log collection has been scheduled to run every hour.

cluster1::*> *system switch ethernet log modify -device cs2 -periodic-enabled true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

*cs2*: Periodic log collection has been scheduled to run every hour.

cluster1::*> *system switch ethernet log show*
                                          Periodic    Periodic    Support
Switch                                    Log Enabled Log State   Log State

cs1                                       true        scheduled   never-run
cs2                                       true        scheduled   never-run
2 entries were displayed.
----
. Collecte des journaux de support demandée :
+
[source, cli]
----
system switch ethernet log collect-support-log -device <switch-name>
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log collect-support-log -device cs1*

*cs1*: Waiting for the next Ethernet switch polling cycle to begin support collection.

cluster1::*> *system switch ethernet log collect-support-log -device cs2*

*cs2*: Waiting for the next Ethernet switch polling cycle to begin support collection.

cluster1::*> *system switch ethernet log show
                                          Periodic    Periodic    Support
Switch                                    Log Enabled Log State   Log State

cs1                                       false       halted      initiated
cs2                                       true        scheduled   initiated
2 entries were displayed.
----
. Pour consulter tous les détails de la collecte des journaux, y compris l'activation, le message d'état, l'horodatage et le nom de fichier de la collecte périodique précédente, l'état de la requête, le message d'état, ainsi que l'horodatage et le nom de fichier de la collecte de support précédente, utilisez les éléments suivants :
+
[source, cli]
----
system switch ethernet log show -instance
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log show -instance*

                    Switch Name: cs1
           Periodic Log Enabled: true
            Periodic Log Status: Periodic log collection has been scheduled to run every hour.
    Last Periodic Log Timestamp: 3/11/2024 11:02:59
          Periodic Log Filename: cluster1:/mroot/etc/log/shm-cluster-info.tgz
          Support Log Requested: false
             Support Log Status: Successfully gathered support logs - see filename for their location.
     Last Support Log Timestamp: 3/11/2024 11:14:20
           Support Log Filename: cluster1:/mroot/etc/log/shm-cluster-log.tgz

                    Switch Name: cs2
           Periodic Log Enabled: false
            Periodic Log Status: Periodic collection has been halted.
    Last Periodic Log Timestamp: 3/11/2024 11:05:18
          Periodic Log Filename: cluster1:/mroot/etc/log/shm-cluster-info.tgz
          Support Log Requested: false
             Support Log Status: Successfully gathered support logs - see filename for their location.
     Last Support Log Timestamp: 3/11/2024 11:18:54
           Support Log Filename: cluster1:/mroot/etc/log/shm-cluster-log.tgz
2 entries were displayed.
----


--
.ONTAP 9.14.1 et versions antérieures
--
. Pour configurer la collecte des journaux, exécutez la commande suivante pour chaque commutateur.  Vous êtes invité à saisir le nom du commutateur, le nom d'utilisateur et le mot de passe pour la collecte des journaux.
+
*REMARQUE :* Si vous répondez `y` Lors de l'invite de spécification de l'utilisateur, assurez-vous que celui-ci dispose des autorisations nécessaires, comme indiqué dans<<Avant de commencer>> .

+
[source, cli]
----
system switch ethernet log setup-password
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*

Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----



NOTE: Pour CL 5.11.1, créez l'utilisateur *cumulus* et répondez *y* à l'invite suivante : Souhaitez-vous spécifier un utilisateur autre que admin pour la collecte des journaux ?  {o|n}: *o*

. [[étape 2]] Pour demander la collecte des journaux de support et activer la collecte périodique, exécutez la commande suivante.  Cela lance les deux types de collecte de journaux : la collecte détaillée `Support` journaux et une collecte horaire de `Periodic` données.
+
[source, cli]
----
system switch ethernet log modify -device <switch-name> -log-request true
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
+
Attendez 10 minutes, puis vérifiez que la collecte des journaux est terminée :

+
[source, cli]
----
system switch ethernet log show
----


--
====

CAUTION: Si des erreurs sont signalées par la fonction de collecte des journaux (visibles dans la sortie de `system switch ethernet log show` ), voirlink:log-collection-troubleshoot.html["Résolution des problèmes liés à la collecte des journaux"] pour plus de détails.

.Quelle est la prochaine étape ?
link:config-snmpv3.html["Configurer SNMPv3 (facultatif)"].
