---
permalink: switch-cshm/cshm-overview.html 
sidebar: sidebar 
keywords: cshm, cluster, storage, switch logs, debugging, collection 
summary: 'Le contrôle de l"état des commutateurs Ethernet (CSHM) est chargé de garantir le bon fonctionnement des commutateurs réseau de cluster et de stockage et de collecter les journaux des commutateurs à des fins de débogage.' 
---
= contrôle de l'état du commutateur Ethernet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le contrôle de l'état des commutateurs Ethernet (CSHM) est responsable de garantir l'intégrité opérationnelle des commutateurs réseau et de collecter les journaux des commutateurs à des fins de débogage.

CSHM surveille les commutateurs de cluster et de réseau de stockage afin de garantir la fiabilité de l'infrastructure réseau. Le contrôle de l'état détecte automatiquement les problèmes de commutateur, collecte les journaux pour le dépannage et fournit des alertes en cas de problème réseau. CSHM prend en charge plusieurs fournisseurs et modèles de commutateurs, vous aidant à identifier et à résoudre les problèmes de connectivité réseau avant qu'ils n'affectent votre environnement de stockage.
