---
permalink: switch-cshm/cshm-overview.html 
sidebar: sidebar 
keywords: cshm, cluster, storage, switch logs, debugging, collection 
summary: 'Découvrez le contrôle de l"état des commutateurs Ethernet (CSHM) et comment il surveille l"intégrité des commutateurs de réseau de cluster et de stockage dans ONTAP.' 
---
= Découvrez le contrôle de l'état des commutateurs Ethernet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le contrôle de l'état des commutateurs Ethernet (CSHM) surveille de manière proactive l'intégrité des commutateurs de réseau de cluster et de stockage dans ONTAP, en émettant des alertes en cas de défauts détectés et en collectant les journaux des commutateurs pour le débogage.

CSHM surveille les commutateurs de cluster et de réseau de stockage afin de garantir la fiabilité de l'infrastructure réseau. Le contrôle de l'état détecte automatiquement les problèmes de commutateur, collecte les journaux pour le dépannage et fournit des alertes en cas de problème réseau. CSHM prend en charge plusieurs fournisseurs et modèles de commutateurs, vous aidant à identifier et à résoudre les problèmes de connectivité réseau avant qu'ils n'affectent votre environnement de stockage.
