---
permalink: switch-cshm/log-collection-troubleshoot.html 
sidebar: sidebar 
keywords: cshm, cluster, storage, switch logs, debugging, collection 
summary: Vous pouvez utiliser les commandes fournies ici pour… 
---
= Résolution des problèmes liés à la collecte des journaux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous rencontrez l'un des statuts d'erreur suivants signalés par la fonction de collecte des journaux (visibles dans la sortie du `system switch ethernet log show` commande), essayez les étapes de débogage correspondantes :

|===


| *État d'erreur de collecte des journaux* | *Résolution* 


 a| 
*Clés RSA absentes*
 a| 
Régénérer les clés SSH ONTAP .



 a| 
*Erreur de mot de passe Switch*
 a| 
Vérifiez les informations d'identification, testez la connectivité SSH et régénérez les clés SSH ONTAP .  Consultez la documentation du commutateur ou contactez le support NetApp pour obtenir des instructions.



 a| 
*Clés ECDSA absentes pour FIPS*
 a| 
Si le mode FIPS est activé, des clés ECDSA doivent être générées sur le commutateur avant de réessayer.



 a| 
*Journal préexistant trouvé*
 a| 
Supprimez le fichier de journalisation précédent sur le commutateur.



 a| 
*Erreur lors de la génération du journal de vidage du commutateur*
 a| 
Vérifiez que l'utilisateur du commutateur dispose des autorisations de collecte des journaux.  Veuillez vous référer aux prérequis ci-dessus.

|===

NOTE: Si les détails de la solution ne fonctionnent pas, contactez le support NetApp .
