---
permalink: switch-cshm/log-collection-troubleshoot.html 
sidebar: sidebar 
keywords: cshm, cluster, storage, switch logs, debugging, collection 
summary: Vous pouvez utiliser les commandes fournies ici pour... 
---
= Dépannage de la collecte des journaux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous rencontrez l'un des États d'erreur suivants signalés par la fonction de collecte de journaux (visible dans la sortie de la `system switch ethernet log show` commande), essayez les étapes de débogage correspondantes :

|===


| *Etat d'erreur de collecte de journaux* | *Résolution* 


 a| 
*Clés RSA non présentes*
 a| 
Régénérer les clés SSH ONTAP.



 a| 
*Erreur de mot de passe de commutateur*
 a| 
Vérifiez les identifiants, testez la connectivité SSH et régénérez les clés SSH ONTAP. Consultez la documentation du commutateur ou contactez le support NetApp pour obtenir des instructions.



 a| 
*Clés ECDSA non présentes pour FIPS*
 a| 
Si le mode FIPS est activé, les clés ECDSA doivent être générées sur le commutateur avant de réessayer.



 a| 
*Journal préexistant trouvé*
 a| 
Supprimez le fichier de collecte de journaux précédent sur le commutateur.



 a| 
*Erreur du journal de vidage de commutateur*
 a| 
Assurez-vous que l'utilisateur du commutateur dispose des autorisations de collecte de journaux. Reportez-vous aux conditions préalables ci-dessus.

|===

NOTE: Si les détails de la résolution ne fonctionnent pas, contactez le support NetApp.
