---
permalink: switch-cshm/monitor-manage.html 
sidebar: sidebar 
keywords: create, remove, switch, cluster, monitor, health, management 
summary: Découvrez comment créer manuellement, modifier les paramètres de surveillance par défaut et supprimer les commutateurs Ethernet de la surveillance. 
---
= Gérer la surveillance des commutateurs Ethernet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dans la plupart des cas, les commutateurs Ethernet sont automatiquement détectés par ONTAP et surveillés par CSHM. Le fichier de configuration de référence (RCF) appliqué au commutateur, entre autres, active le protocole CDP (Cisco Discovery Protocol) et/ou le protocole LLDP (Link Layer Discovery Protocol). Cependant, vous devrez peut-être ajouter manuellement un commutateur qui n'est pas détecté ou supprimer un commutateur qui n'est plus utilisé. Vous pouvez également arrêter la surveillance active tout en maintenant le commutateur dans la configuration, par exemple pendant la maintenance.



== Créez une entrée de commutateur afin que ONTAP puisse la surveiller

Utilisez `system switch ethernet create` la commande pour configurer et activer manuellement la surveillance d'un commutateur Ethernet spécifié. Ceci est utile si ONTAP n'ajoute pas automatiquement le commutateur, ou si vous avez précédemment supprimé le commutateur et souhaitez le rajouter.

[source, cli]
----
system switch ethernet create -device DeviceName -address 1.2.3.4 -snmp-version SNMPv2c -community-or-username cshm1! -model NX3132V -type cluster-network
----
Un exemple type est l'ajout d'un commutateur nommé [DeviceName], avec l'adresse IP 1.2.3.4, et les informations d'identification SNMPv2c définies sur *cshm1!*. Utilisez `-type storage-network` plutôt que `-type cluster-network` si vous configurez un commutateur de stockage.



== Désactiver la surveillance sans supprimer le commutateur

Si vous souhaitez mettre en pause ou arrêter la surveillance d'un certain commutateur, mais le conserver pour une surveillance future, modifiez son `is-monitoring-enabled-admim` paramètre au lieu de le supprimer.

Par exemple :

[source, cli]
----
system switch ethernet modify -device DeviceName -is-monitoring-enabled-admin false
----
Cela vous permet de préserver les détails et la configuration du commutateur sans générer de nouvelles alertes ou de nouvelles découvertes.



== Retirez un commutateur dont vous n'avez plus besoin

Utiliser `system switch ethernet delete` pour supprimer un commutateur qui a été déconnecté ou n'est plus nécessaire :

[source, cli]
----
system switch ethernet delete -device DeviceName
----
Par défaut, cette commande réussit uniquement si ONTAP ne détecte pas actuellement le commutateur via CDP ou LLDP. Pour supprimer un commutateur découvert, utilisez le `-force` paramètre :

[source, cli]
----
system switch ethernet delete -device DeviceName -force
----
Lorsque `-force` est utilisé, le commutateur peut être ajouté automatiquement si ONTAP le détecte à nouveau.
