---
permalink: switch-cshm/monitor-manage.html 
sidebar: sidebar 
keywords: create, remove, switch, cluster, monitor, health, management 
summary: Apprenez à créer manuellement des commutateurs Ethernet, à modifier leurs paramètres de surveillance par défaut et à les supprimer de la surveillance. 
---
= Gérer la surveillance des commutateurs Ethernet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dans la plupart des cas, les commutateurs Ethernet sont automatiquement détectés par ONTAP et surveillés par CSHM.  Le fichier de configuration de référence (RCF) appliqué au commutateur active, entre autres, le protocole de découverte Cisco (CDP) et/ou le protocole de découverte de couche de liaison (LLDP).  Toutefois, vous pourriez avoir besoin d'ajouter manuellement un commutateur non détecté ou de supprimer un commutateur qui n'est plus utilisé.  Vous pouvez également interrompre la surveillance active tout en conservant le commutateur dans la configuration, par exemple lors d'une opération de maintenance.



== Créez une entrée de commutation pour ONTAP puisse la surveiller.

Utilisez le `system switch ethernet create` commande permettant de configurer et d'activer manuellement la surveillance d'un commutateur Ethernet spécifié.  Cela est utile si ONTAP n'ajoute pas automatiquement le commutateur, ou si vous l'avez précédemment supprimé et souhaitez le rajouter.

[source, cli]
----
system switch ethernet create -device DeviceName -address 1.2.3.4 -snmp-version SNMPv2c -community-or-username cshm1! -model NX3132V -type cluster-network
----
Un exemple typique consiste à ajouter un commutateur nommé [DeviceName], avec l'adresse IP 1.2.3.4 et les informations d'identification SNMPv2c définies sur *cshm1!*.  Utiliser `-type storage-network` au lieu de `-type cluster-network` si vous configurez un commutateur de stockage.



== Désactiver la surveillance sans supprimer le commutateur

Si vous souhaitez suspendre ou arrêter la surveillance d'un commutateur spécifique, tout en le conservant pour une surveillance ultérieure, modifiez ses paramètres. `is-monitoring-enabled-admim` paramètre au lieu de le supprimer.

Par exemple:

[source, cli]
----
system switch ethernet modify -device DeviceName -is-monitoring-enabled-admin false
----
Cela vous permet de préserver les détails et la configuration des commutateurs sans générer de nouvelles alertes ni de nouvelles redécouvertes.



== Retirez un interrupteur dont vous n'avez plus besoin.

Utiliser `system switch ethernet delete` pour supprimer un commutateur qui a été déconnecté ou qui n'est plus nécessaire :

[source, cli]
----
system switch ethernet delete -device DeviceName
----
Par défaut, cette commande ne réussit que si ONTAP ne détecte pas actuellement le commutateur via CDP ou LLDP.  Pour supprimer un commutateur détecté, utilisez le `-force` paramètre:

[source, cli]
----
system switch ethernet delete -device DeviceName -force
----
Quand `-force` Si le commutateur est utilisé, il pourra être rajouté automatiquement si ONTAP le détecte à nouveau.
