---
permalink: switch-cshm/monitor-troubleshoot.html 
sidebar: sidebar 
keywords: cshm, cluster, storage, switch logs, debugging, collection 
summary: 'Résolvez les problèmes liés aux alertes de contrôle de l"état des commutateurs Ethernet générées par CSHM dans votre cluster ONTAP.' 
---
= Dépannez les alertes de surveillance de l'état des commutateurs Ethernet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Résolvez les alertes générées par le contrôle de l'état (CSHM) lorsqu'une panne, un risque ou une condition critique est détectée pour un commutateur réseau dans votre cluster ONTAP.

En cas d'alertes, l'état de santé du système signale un état dégradé pour le cluster.  Les alertes émises contiennent les informations nécessaires pour réagir à une dégradation de l'état du système.

Pour consulter les alertes de surveillance de l'état du commutateur Ethernet disponibles, exécutez la commande : `system health alert definition show -monitor ethernet-switch`

Consultez l'article de la base de connaissances https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Cluster_Switch_Health_Monitor_CSHM_Alert_Resolution_Guide["Guide de résolution des alertes du moniteur d'état du commutateur"^] pour obtenir des informations détaillées sur la résolution avancée des alertes.
