---
permalink: switch-cshm/monitor-verify.html 
sidebar: sidebar 
keywords: verify, monitor, cluster, management, network, switches, heath, monitor 
summary: 'Vérifiez que la surveillance de l"état de vos commutateurs Ethernet est correctement configurée et fonctionne.' 
---
= Vérifiez la configuration du contrôle de l'état du commutateur Ethernet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le contrôle de l'état (CSHM) tente automatiquement de surveiller les commutateurs réseau qu'il détecte ; toutefois, cette surveillance peut ne pas se produire automatiquement si les commutateurs ne sont pas correctement configurés. Vous devez vérifier que le contrôle de l'état est correctement configuré pour surveiller vos commutateurs.



[[confirm-monitoring-of-the-connected-ethernet-switches]]
== Vérifier la surveillance des commutateurs Ethernet connectés

Pour confirmer que les commutateurs Ethernet connectés sont surveillés, exécutez :

[source, cli]
----
system switch ethernet show
----
Si le `Model` La colonne affiche *AUTRE* ou le `IS Monitored` Si le champ affiche *false*, ONTAP ne peut pas surveiller le commutateur.  La valeur *AUTRE* indique généralement ONTAP ne prend pas en charge ce commutateur pour la surveillance de l'état.

Le `IS Monitored` Le champ est défini sur *false* pour la raison spécifiée dans le `Reason` champ.

[NOTE]
====
Si un commutateur n'est pas répertorié dans le résultat de la commande, il est probable ONTAP ne l'ait pas détecté.  Vérifiez que le commutateur est correctement câblé.  Si nécessaire, vous pouvez ajouter l'interrupteur manuellement.  Voirlink:monitor-manage.html["Gérer la surveillance des commutateurs Ethernet"] pour plus de détails.

====


[[confirm-firmware-and-rcf-versions-are-up-to-date]]
== Vérifiez que les versions du firmware et du RCF sont à jour.

Assurez-vous que le commutateur exécute le dernier firmware pris en charge et qu'un fichier de configuration de référence (RCF) compatible a été appliqué.  Plus d'informations sont disponibles sur lehttps://mysupport.netapp.com/site/downloads["Page de téléchargement du support NetApp"^] .

Par défaut, le moniteur d'intégrité utilise SNMPv2c avec la chaîne de communauté *cshm1!* pour la surveillance, mais SNMPv3 peut également être configuré.

Si vous devez modifier la chaîne de communauté SNMPv2c par défaut, assurez-vous que la chaîne de communauté SNMPv2c souhaitée a été configurée sur le commutateur.

[source, cli]
----
system switch ethernet modify -device SwitchA -snmp-version SNMPv2c -community-or-username newCommunity!
----

NOTE: Voirlink:config-snmpv3.html["Facultatif : Configurer SNMPv3"] pour plus de détails sur la configuration de SNMPv3 pour son utilisation.



[[confirm-management-network-connection]]
== Confirmer la connexion au réseau de gestion

Vérifiez que le port de gestion du commutateur est connecté au réseau de gestion.

Une connexion correcte au port de gestion est nécessaire pour ONTAP puisse effectuer des requêtes SNMP et collecter les journaux.
