---
permalink: switch-nvidia-sn2100-storage/configure-software-sn2100-storage.html 
sidebar: sidebar 
keywords: sn2100 SN2100 switches setup, sn2100 SN2100 switches install, cumulus linux 
summary: Présentation du processus de configuration logicielle pour les switchs de stockage NVIDIA SN2100 
---
= Workflow d'installation du logiciel pour les switchs de stockage NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour installer et configurer le logiciel d'un commutateur NVIDIA SN2100, procédez comme suit :

. link:install-cumulus-mode-sn2100-storage.html["Installez Cumulus Linux en mode Cumulus"] ou link:install-onie-mode-sn2100-storage.html["Installez Cumulus Linux en mode ONIE"].
+
Vous pouvez installer le système d'exploitation Cumulus Linux (CL) lorsque le commutateur exécute Cumulus Linux ou ONIE.

. link:install-rcf-sn2100-storage.html["Installez le script du fichier de configuration de référence"].
+
Deux scripts RCF sont disponibles pour les applications de stockage et de mise en cluster.

. link:setup-install-cshm-file.html["Installez le fichier CSHM"].
+
Vous pouvez installer le fichier de configuration applicable pour la surveillance de l'état des commutateurs Ethernet des commutateurs de cluster NVIDIA.


