---
permalink: switch-nvidia-sn2100-storage/configure-overview-sn2100-storage.html 
sidebar: sidebar 
keywords: sn2100 SN2100 switches setup, sn2100 SN2100 switches install, cumulus linux 
summary: Avant de configurer les switchs NVIDIA SN2100, consultez la présentation de la procédure. 
---
= Présentation du processus de configuration des switchs de stockage NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le NVIDIA SN2100 est un commutateur Ethernet qui vous permet de basculer les données entre les contrôleurs et les tiroirs disques.



== Présentation de la configuration initiale

Pour configurer un switch NVIDIA SN2100 sur les systèmes exécutant ONTAP, procédez comme suit :

. link:install-hardware-sn2100-storage.html["Installez le matériel du commutateur NVIDIA SN2100"].
+
Les instructions sont disponibles dans le _NVIDIA Switch installation Guide_.

. link:configure-sn2100-storage.html["Configurer le commutateur"].
+
Des instructions sont disponibles dans la documentation NVIDIA.

. link:cabling-considerations-sn2100-storage.html["Examinez les considérations relatives au câblage et à la configuration"].
+
Consultez les exigences relatives aux connexions optiques, à l'adaptateur QSA et à la vitesse du port de commutation.

. link:install-cable-shelves-sn2100-storage.html["Reliez les tiroirs NS224 au stockage relié au commutateur"].
+
Suivez ces procédures si vous disposez d'un système dans lequel les tiroirs disques du NS224 doivent être câblés en tant que stockage connecté à un commutateur (pas de stockage à connexion directe).

. link:install-cumulus-mode-sn2100-storage.html["Installez Cumulus Linux en mode Cumulus"] ou link:install-onie-mode-sn2100-storage.html["Installez Cumulus Linux en mode ONIE"].
+
Vous pouvez installer le système d'exploitation Cumulus Linux (CL) lorsque le commutateur exécute Cumulus Linux ou ONIE.

. link:install-rcf-sn2100-storage.html["Installez le script du fichier de configuration de référence"].
+
Deux scripts RCF sont disponibles pour les applications de stockage et de mise en cluster.

. link:setup-install-cshm-file.html["Installez le fichier CSHM"].
+
Vous pouvez installer le fichier de configuration applicable pour la surveillance de l'état des commutateurs Ethernet des commutateurs de cluster NVIDIA.





== Informations supplémentaires

Avant de commencer l'installation ou la maintenance, vérifiez les points suivants :

* link:configure-reqs-sn2100-storage.html["Configuration requise"]
* link:components-sn2100-storage.html["Composants et références"]
* link:required-documentation-sn2100-storage.html["Documentation requise"]

