---
permalink: switch-nvidia-sn2100-storage/configure-reqs-sn2100-storage.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: 'Pour l"installation et la maintenance des switchs NVIDIA SN2100, veillez à vérifier toutes les exigences.' 
---
= Configuration requise pour les switchs NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour l'installation et la maintenance des switchs NVIDIA SN2100, veillez à vérifier toutes les exigences.



== Conditions requises pour l'installation

Si vous souhaitez créer des clusters ONTAP avec plus de deux nœuds, vous devez prendre en charge deux commutateurs de réseau de clusters. Vous pouvez utiliser des commutateurs de gestion supplémentaires, qui sont facultatifs.

Vous installez le commutateur NVIDIA SN2100 (X190006/X190106) dans l'armoire de commutation double/simple NVIDIA à l'aide des supports standard fournis avec le commutateur.

Pour les directives de câblage, voirlink:cabling-considerations-sn2100-storage.html["Considérations relatives au câblage et à la configuration"] .



== Prise en charge de ONTAP et Linux

Le commutateur NVIDIA SN2100 est un commutateur Ethernet 10/25/40/100 Go exécutant Cumulus Linux. Le commutateur prend en charge les éléments suivants :

* ONTAP 9.10.1P3. Le commutateur SN2100 sert les applications de stockage et de cluster dans le ONTAP 9.10.1P3 sur différentes paires de commutateurs. À partir de la conférence ONTAP 9.10.1P3, vous pouvez utiliser les switchs NVIDIA SN2100 pour combiner les fonctionnalités de stockage et de cluster dans une configuration de commutateur partagé.
* Cumulus Linux (CL) OS version 4.4.3. Pour plus d'informations sur la compatibilité actuelle, reportez-vous au https://mysupport.netapp.com/site/info/nvidia-cluster-switch["Commutateurs Ethernet NVIDIA"^] page d'informations.
* Vous pouvez installer Cumulus Linux lorsque le commutateur exécute Cumulus Linux ou ONIE.


.Quelle est la prochaine étape
Après avoir examiné les exigences de configuration, vous pouvez confirmer votre link:components-sn2100-storage.html["composants et numéros de pièces"].
