---
permalink: switch-nvidia-sn2100-storage/configure-reqs-sn2100-storage.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: 'Pour l"installation et la maintenance du commutateur NVIDIA SN2100, assurez-vous de consulter toutes les exigences.' 
---
= Configuration requise pour les commutateurs NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour l'installation et la maintenance du commutateur NVIDIA SN2100, assurez-vous de consulter toutes les exigences.



== Conditions d'installation

Si vous souhaitez créer des clusters ONTAP avec plus de deux nœuds, vous aurez besoin de deux commutateurs réseau de cluster compatibles.  Vous pouvez utiliser des commutateurs de gestion supplémentaires, qui sont optionnels.

Vous installez le commutateur NVIDIA SN2100 (X190006/X190106) dans l'armoire à commutateur double/simple NVIDIA avec les supports standard fournis avec le commutateur.

Pour les directives de câblage, reportez-vous à link:cabling-considerations-sn2100-storage.html["Considérations relatives au câblage et à la configuration"].



== Prise en charge ONTAP et de Linux

Le commutateur NVIDIA SN2100 est un commutateur Ethernet 10/25/40/100 Gb fonctionnant sous Cumulus Linux.  Le commutateur prend en charge les éléments suivants :

* ONTAP 9.10.1P3.  Le commutateur SN2100 prend en charge les applications de cluster et de stockage dans ONTAP 9.10.1P3 sur différentes paires de commutateurs.  À partir d' ONTAP 9.10.1P3, vous pouvez utiliser des commutateurs NVIDIA SN2100 pour combiner les fonctionnalités de stockage et de cluster dans une configuration de commutateur partagée.
* Système d'exploitation Cumulus Linux (CL) version 4.4.3. Pour les informations actuelles sur la compatibilité, consultez link:https://mysupport.netapp.com/site/info/nvidia-cluster-switch["Commutateurs Ethernet NVIDIA"^].
* Vous pouvez installer Cumulus Linux lorsque le commutateur exécute Cumulus Linux ou ONIE.


.Quelle est la prochaine étape
Après avoir examiné les exigences de configuration, vous pouvez confirmer votre link:components-sn2100-storage.html["composants et numéros de pièces"].
