---
permalink: switch-nvidia-sn2100-storage/install-cumulus-mode-sn2100-storage.html 
sidebar: sidebar 
keywords: install cumulus mode, sn2100 SN2100 switches setup, cumulus linux, cumulus mode 
summary: 'Le système d"exploitation Cumulus Linux (CL) peut être installé lorsque le commutateur exécute Cumulus Linux ou ONIE.' 
---
= Installez Cumulus Linux en mode Cumulus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivre cette procédure pour installer le système d'exploitation Cumulus Linux (CL) lorsque le commutateur est en mode Cumulus.


NOTE: Le système d'exploitation Cumulus Linux (CL) peut être installé lorsque le commutateur exécute Cumulus Linux ou ONIE (voir link:install-onie-mode-sn2100-storage.html["Installez en mode ONIE"]).

.Ce dont vous avez besoin
* Connaissance Linux de niveau intermédiaire.
* Connaissance de l'édition de texte de base, des autorisations de fichier UNIX et de la surveillance des processus. Plusieurs éditeurs de texte sont pré-installés, y compris `vi` et `nano`.
* Accès à un shell Linux ou UNIX. Si vous utilisez Windows, utilisez un environnement Linux comme outil de ligne de commande pour interagir avec Cumulus Linux.
* Le débit en bauds requis doit être défini sur 115200 sur le commutateur de console série pour l'accès à la console du commutateur NVIDIA SN2100, comme suit :
+
** 115200 bauds
** 8 bits de données (data bits)
** 1 bit de stop
** parité : aucune
** contrôle de flux : aucun




.Description de la tâche
Gardez à l'esprit les points suivants :


NOTE: Chaque fois que Cumulus Linux est installé, l'intégralité de la structure du système de fichiers est effacée et reconstruite.


CAUTION: Le mot de passe par défaut pour le compte utilisateur du umulus est *cumulus*. La première fois que vous vous connectez à Cumulus Linux, vous devez changer ce mot de passe par défaut. Veillez à mettre à jour tous les scripts d'automatisation avant d'installer une nouvelle image. Cumulus Linux propose des options de ligne de commande pour modifier automatiquement le mot de passe par défaut pendant le processus d'installation.

.Étapes
. Connectez-vous au commutateur.
+
La première connexion au commutateur requiert le nom d'utilisateur/mot de passe *cumulus*/*cumulus* avec `sudo` privilèges.

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
====
. Vérifiez la version de Cumulus Linux :
+
`net show system`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show system*
Hostname......... cumulus
Build............ *Cumulus Linux 4.4.3*
Uptime........... 0:08:20.860000
Model............ Mlnx X86
CPU.............. x86_64 Intel Atom C2558 2.40GHz
Memory........... 8GB
Disk............. 14.7GB
ASIC............. Mellanox Spectrum MT52132
Ports............ 16 x 100G-QSFP28
Part Number...... MSN2100-CB2FC
Serial Number.... MT2105T05177
Platform Name.... x86_64-mlnx_x86-r0
Product Name..... MSN2100
ONIE Version..... 2019.11-5.2.0020-115200
Base MAC Address. 04:3F:72:43:92:80
Manufacturer..... Mellanox
----
====
. Configurez le nom d'hôte, l'adresse IP, le masque de sous-réseau et la passerelle par défaut. Le nouveau nom d'hôte ne devient effectif qu'après le redémarrage de la session console/SSH.
+

NOTE: Un commutateur Cumulus Linux fournit au moins un port de gestion Ethernet dédié appelé `eth0`. Cette interface est spécifiquement destinée à la gestion hors bande. Par défaut, l'interface de gestion utilise DHCPv4 pour l'adressage.

+

CAUTION: N'utilisez pas de trait de soulignement (_), d'apostrophe (') ou de caractères non ASCII dans le nom d'hôte.

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net add hostname sw1*
cumulus@cumulus:mgmt:~$ *net add interface eth0 ip address 10.233.204.71*
cumulus@cumulus:mgmt:~$ *net add interface eth0 ip gateway 10.233.204.1*
cumulus@cumulus:mgmt:~$ *net pending*
cumulus@cumulus:mgmt:~$ *net commit*
----
====
+
Cette commande modifie les deux `/etc/hostname` et `/etc/hosts` fichiers.

. Vérifiez que le nom d'hôte, l'adresse IP, le masque de sous-réseau et la passerelle par défaut ont été mis à jour.
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *hostname sw1*
cumulus@sw1:mgmt:~$ *ifconfig eth0*
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet 10.233.204.71  netmask 255.255.254.0  broadcast 10.233.205.255
inet6 fe80::bace:f6ff:fe19:1df6  prefixlen 64  scopeid 0x20<link>
ether b8:ce:f6:19:1d:f6  txqueuelen 1000  (Ethernet)
RX packets 75364  bytes 23013528 (21.9 MiB)
RX errors 0  dropped 7  overruns 0  frame 0
TX packets 4053  bytes 827280 (807.8 KiB)
TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0 device memory 0xdfc00000-dfc1ffff

cumulus@sw1::mgmt:~$ *ip route show vrf mgmt*
default via 10.233.204.1 dev eth0
unreachable default metric 4278198272
10.233.204.0/23 dev eth0 proto kernel scope link src 10.233.204.71
127.0.0.0/8 dev mgmt proto kernel scope link src 127.0.0.1
----
====
. Configurer le fuseau horaire en mode interactif NTP.
+
.. Sur un terminal, lancer la commande suivante :
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo dpkg-reconfigure tzdata*
----
.. Suivez les options du menu à l'écran pour sélectionner la zone géographique et la région.
.. Pour définir le fuseau horaire de tous les services et démons, redémarrez le commutateur.
.. Vérifier que la date et l'heure sur le commutateur sont correctes et mettre à jour si nécessaire.


. Installez Cumulus Linux 4.4.3:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo onie-install -a -i http://_<web-server>/<path>_/cumulus-linux-4.4.3-mlx-amd64.bin*
----
+
Le programme d'installation démarre le téléchargement. Tapez *y* lorsque vous y êtes invité.

. Redémarrez le commutateur NVIDIA SN2100 :
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo reboot*
----
. L'installation démarre automatiquement et les écrans GRUB suivants s'affichent. Effectuer *pas* de sélection :
+
** Cumulus-Linux GNU/Linux
** ONIE : installez le système d'exploitation
** CUMULUS - INSTALLATION
** Cumulus-Linux GNU/Linux


. Répétez les étapes 1 à 4 pour vous connecter.
. Vérifiez que la version de Cumulus Linux est 4.4.3:
+
`net show version`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *net show version*
NCLU_VERSION=1.0-cl4.4.3u0
DISTRIB_ID="Cumulus Linux"
DISTRIB_RELEASE=*4.4.3*
DISTRIB_DESCRIPTION=*"Cumulus Linux 4.4.3"*
----
====
. Créez un nouvel utilisateur et ajoutez cet utilisateur à la `sudo` groupe. Cet utilisateur ne prend effet qu'après le redémarrage de la session console/SSH.
+
`sudo adduser --ingroup netedit admin`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser --ingroup netedit admin*
[sudo] password for cumulus:
Adding user `admin’ ...
Adding new user `admin’ (1001) with group `netedit' ...
Creating home directory `/home/admin’ ...
Copying files from `/etc/skel' ...
New password:
Retype new password:
passwd: password updated successfully
Changing the user information for admin
Enter the new value, or press ENTER for the default
Full Name []:
Room Number []:
Work Phone []:
Home Phone []:
Other []:
Is the information correct? [Y/n] *y*

cumulus@sw1:mgmt:~$ *sudo adduser admin sudo*
[sudo] password for cumulus:
Adding user `admin' to group `sudo' ...
Adding user admin to group sudo
Done.
cumulus@sw1:mgmt:~$ exit
logout
Connection to 10.233.204.71 closed.

[admin@cycrh6svl01 ~]$ ssh admin@10.233.204.71
admin@10.233.204.71's password:
Linux sw1 4.19.0-cl-1-amd64 #1 SMP Cumulus 4.19.206-1+cl4.4.3u1 (2021-09-09) x86_64
Welcome to NVIDIA Cumulus (R) Linux (R)

For support and online technical documentation, visit
http://www.cumulusnetworks.com/support

The registered trademark Linux (R) is used pursuant to a sublicense from LMI, the exclusive licensee of Linus Torvalds, owner of the mark on a world-wide basis.
admin@sw1:mgmt:~$
----
====


.Et la suite ?
link:install-rcf-sn2100-storage.html["Installez le script RCF"].
