---
permalink: switch-nvidia-sn2100-storage/install-onie-mode-sn2100-storage.html 
sidebar: sidebar 
keywords: install cumulus onie mode, sn2100 SN2100 switches setup, cumulus linux, onie mode 
summary: 'Le système d"exploitation Cumulus Linux (CL) peut être installé soit lorsque le commutateur exécute Cumulus Linux, soit ONIE.' 
---
= Installer Cumulus Linux en mode ONIE
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez cette procédure pour installer le système d'exploitation Cumulus Linux (CL) lorsque le commutateur fonctionne en mode ONIE.


NOTE: Le système d'exploitation Cumulus Linux (CL) peut être installé soit lorsque le commutateur exécute Cumulus Linux, soit lorsqu'il exécute ONIE (voirlink:install-cumulus-mode-sn2100-storage.html["Installation en mode Cumulus"] ).

.À propos de cette tâche
Vous pouvez installer Cumulus Linux en utilisant Open Network Install Environment (ONIE) qui permet la découverte automatique d'une image d'installation réseau.  Cela facilite la mise en place d'un modèle système de sécurisation des commutateurs avec un choix de système d'exploitation, tel que Cumulus Linux.  La méthode la plus simple pour installer Cumulus Linux avec ONIE consiste à utiliser la découverte HTTP locale.


NOTE: Si votre hôte est compatible IPv6, assurez-vous qu'il exécute un serveur web.  Si votre hôte est compatible IPv4, assurez-vous qu'il exécute un serveur DHCP en plus d'un serveur web.

Cette procédure explique comment mettre à niveau Cumulus Linux après que l'administrateur a démarré dans ONIE.

.Étapes
. Téléchargez le fichier d'installation de Cumulus Linux dans le répertoire racine du serveur web.  Renommez ce fichier `onie-installer` .
. Connectez votre hôte au port Ethernet de gestion du commutateur à l'aide d'un câble Ethernet.
. Mettez l'interrupteur sous tension.  La console télécharge l'installateur d'image ONIE et démarre.  Une fois l'installation terminée, l'invite de connexion Cumulus Linux apparaît dans la fenêtre du terminal.
+

NOTE: À chaque installation de Cumulus Linux, l'intégralité de la structure du système de fichiers est effacée puis reconstruite.

. Redémarrez le commutateur SN2100 :
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *sudo reboot*
----
. Appuyez sur la touche *Esc* sur l'écran GNU GRUB pour interrompre le processus de démarrage normal, sélectionnez *ONIE* et appuyez sur *Entrée*.
. Sur l'écran suivant, sélectionnez *ONIE : Installer le système d'exploitation*.
. Le processus de découverte du programme d'installation ONIE s'exécute à la recherche de l'installation automatique.  Appuyez sur *Entrée* pour interrompre temporairement le processus.
. Lorsque le processus de découverte est terminé :
+
[listing, subs="+quotes"]
----
ONIE:/ # *onie-stop*
discover: installer mode detected.
Stopping: discover...start-stop-daemon: warning: killing process 427:
No such process done.
----
. Si le service DHCP est activé sur votre réseau, vérifiez que l'adresse IP, le masque de sous-réseau et la passerelle par défaut sont correctement attribués :
+
`ifconfig eth0`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
ONIE:/ # *ifconfig eth0*
eth0   Link encap:Ethernet  HWaddr B8:CE:F6:19:1D:F6
       inet addr:10.233.204.71  Bcast:10.233.205.255  Mask:255.255.254.0
       inet6 addr: fe80::bace:f6ff:fe19:1df6/64 Scope:Link
       UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
       RX packets:21344 errors:0 dropped:2135 overruns:0 frame:0
       TX packets:3500 errors:0 dropped:0 overruns:0 carrier:0
       collisions:0 txqueuelen:1000
       RX bytes:6119398 (5.8 MiB)  TX bytes:472975 (461.8 KiB)
       Memory:dfc00000-dfc1ffff

ONIE:/ # *route*
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface

default         10.233.204.1    0.0.0.0         UG    0      0      0   eth0
10.233.204.0    *               255.255.254.0   U     0      0      0   eth0
----
====
. Si le schéma d'adressage IP est défini manuellement, procédez comme suit :
+
[listing, subs="+quotes"]
----
ONIE:/ # *ifconfig eth0 10.233.204.71 netmask 255.255.254.0*
ONIE:/ # *route add default gw 10.233.204.1*
----
. Répétez l'étape 9 pour vérifier que les informations statiques sont correctement saisies.
. Installer Cumulus Linux :
+
[listing, subs="+quotes"]
----
ONIE:/ # *route*

  Kernel IP routing table

  ONIE:/ # *onie-nos-install http://_<web-server>/<path>_/cumulus-linux-4.4.3-mlx-amd64.bin*

  Stopping: discover... done.
  Info: Attempting http://10.60.132.97/x/eng/testbedN,svl/nic/files/cumulus-linux-4.4.3-mlx-amd64.bin ...
  Connecting to 10.60.132.97 (10.60.132.97:80)
  installer            100% |*******************************|   552M  0:00:00 ETA
  ...
  ...
----
. Une fois l'installation terminée, connectez-vous au commutateur :
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
====
. Vérifiez la version de Cumulus Linux :
+
`net show version`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show version*
NCLU_VERSION=1.0-cl4.4.3u4
DISTRIB_ID="Cumulus Linux"
DISTRIB_RELEASE=*4.4.3*
DISTRIB_DESCRIPTION=*"Cumulus Linux 4.4.3”*
----
====


.Quelle est la prochaine étape ?
Après avoir installé Cumulus Linux en mode ONIE, vous pouvezlink:install-rcf-sn2100-storage.html["installer ou mettre à niveau le script RCF"] .
