---
permalink: switch-nvidia-sn2100-storage/migrate-cisco-storage-switch-sn2100-storage.html 
sidebar: sidebar 
keywords: migrating to a storage switch with NVIDIA SN2100 storage switches, how to migrate 
summary: 'Vous pouvez migrer sans interruption les anciens commutateurs Cisco d"un cluster ONTAP vers des commutateurs de stockage NVIDIA SN2100.' 
---
= Migration d'un commutateur de stockage Cisco vers un commutateur de stockage NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez migrer d'anciens commutateurs Cisco d'un cluster ONTAP vers des commutateurs de stockage NVIDIA SN2100. Il s’agit d’une procédure non perturbatrice.



== Exigences de révision

Les commutateurs de stockage suivants sont pris en charge :

* Cisco Nexus 9336C-FX2
* Cisco Nexus 3232C
* Voir le https://hwu.netapp.com/["Hardware Universe"^] pour plus de détails sur les ports pris en charge et leurs configurations.


.Avant de commencer
Assurez-vous d'avoir les éléments suivants :

* Le cluster existant est correctement configuré et fonctionnel.
* Tous les ports de stockage sont opérationnels afin de garantir un fonctionnement sans interruption.
* Les commutateurs de stockage NVIDIA SN2100 sont configurés et fonctionnent sous la version appropriée de Cumulus Linux installée avec le fichier de configuration de référence (RCF) appliqué.
* La configuration du réseau de stockage existant est la suivante :
+
** Un cluster NetApp redondant et pleinement fonctionnel utilisant des commutateurs Cisco plus anciens.
** Connectivité de gestion et accès console aux anciens commutateurs Cisco et aux nouveaux commutateurs.
** Toutes les interfaces logiques (LIF) du cluster en état opérationnel sont connectées à leurs ports d'origine.
** Les ports ISL sont activés et câblés entre les anciens commutateurs Cisco et entre les nouveaux commutateurs.


* Voir le https://hwu.netapp.com/["Hardware Universe"^] pour plus de détails sur les ports pris en charge et leurs configurations.
* Certains ports sont configurés sur des commutateurs NVIDIA SN2100 pour fonctionner à 100 GbE.
* Vous avez planifié, migré et documenté la connectivité 100 GbE des nœuds vers les commutateurs de stockage NVIDIA SN2100.




== Déplacer les commutateurs

.À propos des exemples
Dans cette procédure, les commutateurs de stockage Cisco Nexus 9336C-FX2 sont utilisés comme exemples de commandes et de sorties.

Les exemples de cette procédure utilisent la nomenclature suivante pour les commutateurs et les nœuds :

* Les commutateurs de stockage Cisco Nexus 9336C-FX2 existants sont _S1_ et _S2_.
* Les nouveaux commutateurs de stockage NVIDIA SN2100 sont _sw1_ et _sw2_.
* Les nœuds sont _node1_ et _node2_.
* Les LIF du cluster sont _node1_clus1_ et _node1_clus2_ sur le nœud 1, et _node2_clus1_ et _node2_clus2_ sur le nœud 2 respectivement.
* Le `cluster1::*>` L'invite indique le nom du cluster.
* Les ports réseau utilisés dans cette procédure sont _e5a_ et _e5b_.
* Les ports de dérivation prennent le format : swp1s0-3.  Par exemple, les quatre ports de dérivation sur swp1 sont _swp1s0_, _swp1s1_, _swp1s2_ et _swp1s3_.
* L'interrupteur S2 est d'abord remplacé par l'interrupteur sw2, puis l'interrupteur S1 est remplacé par l'interrupteur sw1.
+
** Le câblage entre les nœuds et S2 est ensuite déconnecté de S2 et reconnecté à sw2.
** Le câblage entre les nœuds et S1 est ensuite déconnecté de S1 et reconnecté à sw1.






=== Étape 1 : Préparer la migration

. Si AutoSupport est activé, supprimez la création automatique de cas en envoyant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
où _x_ représente la durée de la fenêtre de maintenance en heures.

. Passez au niveau de privilège avancé en saisissant *y* lorsque vous êtes invité à continuer :
+
`set -privilege advanced`

+
L'invite avancée (*>) apparaît.

. Déterminer l'état administratif ou opérationnel de chaque interface de stockage :
+
Chaque port doit afficher « activé » pour `Status` .





=== Étape 2 : Configurer les câbles et les ports

. Afficher les attributs du port réseau :
+
`storage port show`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
node2
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
cluster1::*>
----
====
. Vérifiez que les ports de stockage de chaque nœud sont connectés aux commutateurs de stockage existants de la manière suivante (du point de vue des nœuds) à l'aide de la commande :
+
`network device-discovery show -protocol lldp`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/1           -
            e5b    S2 (7c:ad:4f:98:8e:3c)    Eth1/1           -
node2      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/2           -
            e5b    S2 (7c:ad:4f:98:8e:3c)    Eth1/2           -
----
====
. Sur les commutateurs S1 et S2, assurez-vous que les ports de stockage et les commutateurs sont connectés de la manière suivante (du point de vue des commutateurs) à l'aide de la commande :
+
`show lldp neighbors`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
S1# *show lldp neighbors*

Capability Codes: (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device,
                  (W) WLAN Access Point, (P) Repeater, (S) Station (O) Other

Device-ID             Local Intf     Holdtime    Capability           Port ID
node1                 Eth1/1         121         S                    e0c
node2                 Eth1/2         121         S                    e0c
SHFGD1947000186       Eth1/10        120         S                    e0a         
SHFGD1947000186       Eth1/11        120         S                    e0a         
SHFGB2017000269       Eth1/12        120         S                    e0a         
SHFGB2017000269       Eth1/13        120         S                    e0a

S2# *show lldp neighbors*

Capability Codes: (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device,
                  (W) WLAN Access Point, (P) Repeater, (S) Station (O) Other

Device-ID             Local Intf     Holdtime    Capability          Port ID
node1                 Eth1/1         121         S                   e5b
node2                 Eth1/2         121         S                   e5b
SHFGD1947000186       Eth1/10        120         S                   e0b         
SHFGD1947000186       Eth1/11        120         S                   e0b         
SHFGB2017000269       Eth1/12        120         S                   e0b         
SHFGB2017000269       Eth1/13        120         S                   e0b
----
====
. Sur le commutateur sw2, désactivez les ports connectés aux ports de stockage et aux nœuds des baies de disques.
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net add interface swp1-16 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
====
. Déplacez les ports de stockage du nœud du contrôleur et des baies de disques de l'ancien commutateur S2 vers le nouveau commutateur sw2, en utilisant un câblage approprié pris en charge par NVIDIA SN2100.
. Sur le commutateur sw2, activez les ports connectés aux ports de stockage des nœuds et des baies de disques.
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net del interface swp1-16 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
====
. Vérifiez que les ports de stockage de chaque nœud sont désormais connectés aux commutateurs de la manière suivante, du point de vue des nœuds :
+
`network device-discovery show -protocol lldp`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface      Platform
----------- ------ ------------------------- -------------  ----------------
node1      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/1         -
            e5b    sw2 (b8:ce:f6:19:1a:7e)   swp1           -

node2      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/2         -
            e5b    sw2 (b8:ce:f6:19:1a:7e)   swp2           -
----
====
. Vérifiez les attributs du port réseau :
+
`storage port show`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
node2
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
cluster1::*>
----
====
. Sur le commutateur sw2, vérifiez que tous les ports de stockage des nœuds sont opérationnels :
+
`net show interface`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e5b)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e5b)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
====
. Sur le commutateur sw1, désactivez les ports connectés aux ports de stockage des nœuds et des baies de disques.
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add interface swp1-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
====
. Déplacez les ports de stockage du nœud du contrôleur et les baies de disques de l'ancien commutateur S1 vers le nouveau commutateur sw1, en utilisant un câblage approprié pris en charge par NVIDIA SN2100.
. Sur le commutateur sw1, activez les ports connectés aux ports de stockage des nœuds et des baies de disques.
+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net del interface swp1-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
====
. Vérifiez que les ports de stockage de chaque nœud sont désormais connectés aux commutateurs de la manière suivante, du point de vue des nœuds :
+
`network device-discovery show -protocol lldp`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /lldp
            e0c    sw1 (b8:ce:f6:19:1b:96)   swp1            -
            e5b    sw2 (b8:ce:f6:19:1a:7e)   swp1            -

node2      /lldp
            e0c    sw1  (b8:ce:f6:19:1b:96)  swp2            -
            e5b    sw2  (b8:ce:f6:19:1a:7e)  swp2            -
----
====




=== Étape 3 : Vérifier la configuration

. Vérifiez la configuration finale :
+
`storage port show`

+
Chaque port doit afficher « activé » pour `State` et activé pour `Status` .

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
node2
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
cluster1::*>
----
====
. Sur le commutateur sw2, vérifiez que tous les ports de stockage des nœuds sont opérationnels :
+
`net show interface`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e5b)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e5b)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
====
. Vérifiez que chaque nœud possède une connexion à chaque commutateur :
+
`net show lldp`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant illustre les résultats attendus pour les deux commutateurs :

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*
LocalPort  Speed  Mode      RemoteHost             RemotePort
---------  -----  --------  ---------------------  -----------
...
swp1       100G   Trunk/L2  node1                  e0c
swp2       100G   Trunk/L2  node2                  e0c
swp3       100G   Trunk/L2  SHFFG1826000112        e0a
swp4       100G   Trunk/L2  SHFFG1826000112        e0a
swp5       100G   Trunk/L2  SHFFG1826000102        e0a
swp6       100G   Trunk/L2  SHFFG1826000102        e0a

cumulus@sw2:~$ *net show lldp*
LocalPort  Speed  Mode      RemoteHost             RemotePort
---------  -----  --------  ---------------------  -----------
...
swp1       100G   Trunk/L2  node1                  e5b
swp2       100G   Trunk/L2  node2                  e5b
swp3       100G   Trunk/L2  SHFFG1826000112        e0b
swp4       100G   Trunk/L2  SHFFG1826000112        e0b
swp5       100G   Trunk/L2  SHFFG1826000102        e0b
swp6       100G   Trunk/L2  SHFFG1826000102        e0b
----
====


. Rétablir le niveau de privilège à administrateur :
+
`set -privilege admin`

. Si vous avez désactivé la création automatique de dossiers, réactivez-la en envoyant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.Quelle est la prochaine étape ?
Une fois vos commutateurs migrés, vous pouvez link:../switch-cshm/config-overview.html["configurer la surveillance de l'état du commutateur"].
