---
permalink: switch-nvidia-sn2100/migrate-cisco-sn2100-cluster-switch-storage.html 
sidebar: sidebar 
keywords: migrating to a cluster with NVIDIA SN2100 cluster switches, how to migrate 
summary: 'Vous pouvez migrer d"anciens commutateurs de cluster Cisco sans interruption pour un cluster ONTAP vers des commutateurs de réseau de cluster NVIDIA SN2100.' 
---
= Migrez d'un commutateur de cluster Cisco vers un commutateur de cluster NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez migrer des commutateurs de cluster Cisco sans interruption d'activité pour un cluster ONTAP vers des commutateurs de cluster NVIDIA SN2100. Vous devez connaître certaines informations de configuration, les connexions de ports et les exigences de câblage lorsque vous remplacez d'anciens commutateurs de cluster Cisco par des commutateurs de cluster NVIDIA SN2100.

Les commutateurs de cluster Cisco suivants sont pris en charge :

* Nexus 9336C-FX2
* Nexus 92300YC
* Nexus 5596UP
* Nexus 3232C
* Nexus 3132Q-V


.Avant de commencer
Vous pouvez migrer d'anciens commutateurs de cluster Cisco sans interruption pour un cluster ONTAP vers des commutateurs de cluster NVIDIA SN2100.

* Le cluster existant doit être correctement configuré et opérationnel.
* Tous les ports du cluster doivent être à l'état up pour assurer la continuité de l'activité.
* Les commutateurs de cluster NVIDIA SN2100 doivent être configurés et fonctionnent sous la version appropriée de Cumulus Linux installée dans le fichier RCF (Reference Configuration File) appliqué.
* La configuration réseau en cluster existante doit disposer des éléments suivants :
+
** Un cluster NetApp redondant et entièrement fonctionnel utilisant les deux anciens commutateurs Cisco.
** Connectivité de gestion et accès à la console aux anciens commutateurs Cisco et aux nouveaux commutateurs.
** Toutes les LIFs de cluster à l'état up avec les LIFs de cluster sont sur leurs ports de type home.
** Ports ISL activés et câblés entre les anciens commutateurs Cisco et entre les nouveaux commutateurs.


* Voir la https://hwu.netapp.com/["Hardware Universe"^] pour obtenir des détails complets sur les ports pris en charge et leurs configurations.
* Vous avez configuré certains ports sur les switchs NVIDIA SN2100 pour qu'ils s'exécutent à 40 GbE ou 100 GbE.
* Vous avez planifié, migré et documenté une connectivité 40 GbE et 100 GbE entre les nœuds et les commutateurs de cluster NVIDIA SN2100.
+

NOTE: Dans cette procédure, les switchs de cluster Cisco Nexus 3232C sont utilisés par exemple pour les commandes et les sorties.



.Description de la tâche
Les exemples de cette procédure utilisent la nomenclature des commutateurs et des nœuds suivante :

* Les switchs de cluster Cisco Nexus 3232C existants sont _c1_ et _c2_.
* Les nouveaux commutateurs de cluster NVIDIA SN2100 sont _sw1_ et _sw2_.
* Les nœuds sont _node1_ et _node2_.
* Les LIFS du cluster sont respectivement _node1_clum1_ et _node1_clum2_ sur le nœud 1 et _node2_clum1_ et _node2_clum2_ sur le nœud 2.
* Le `cluster1::*>` l'invite indique le nom du cluster.
* Les ports de cluster utilisés dans cette procédure sont _e3a_ et _e3b_.
* Les ports de dérivation prennent le format suivant : swp[port]s[port de dérivation 0-3]. Par exemple, quatre ports de dérivation sur swp1 sont _swp1s0_, _swp1s1_, _swp1s2_ et _swp13_.
* Le contacteur c2 est d'abord remplacé par le contacteur sw2, puis le contacteur c1 est remplacé par le contacteur sw1.
+
** Le câblage entre les nœuds et c2 est ensuite déconnecté de c2 et reconnecté à sw2.
** Le câblage entre les nœuds et c1 est ensuite déconnecté de c1 et reconnecté à sw1.




.Étapes
. Si AutoSupport est activé sur ce cluster, supprimez la création automatique de dossiers en invoquant un message AutoSupport : `system node autosupport invoke -node * -type all -message MAINT=xh`
+
où _x_ représente la durée de la fenêtre de maintenance en heures.

. Définissez le niveau de privilège sur avancé, en entrant *y* lorsque vous êtes invité à continuer : `set -privilege advanced`
+
L'invite avancée (*>) apparaît.

. Désactiver la fonction de revert automatique sur les LIFs du cluster : `network interface modify -vserver Cluster -lif * -auto-revert false`
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*

Warning: Disabling the auto-revert feature of the cluster logical interface may effect the availability of your cluster network. Are you sure you want to continue? {y|n}: *y*
----
. Déterminer le statut administratif ou opérationnel pour chaque interface de cluster :
+
Chaque port doit s'afficher pendant `Link` et en bonne santé pour `Health Status`.

+
.. Afficher les attributs des ports réseau : `network port show -ipspace Cluster`
+
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
.. Afficher des informations sur les interfaces logiques et les nœuds home désignés : `network interface show -vserver Cluster`
+
Chaque LIF doit afficher son contenu pendant `Status Admin/Oper` et vrai pour `Is Home`.

+
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical      Status     Network            Current     Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node        Port    Home
----------- -----------  ---------- ------------------ ----------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1       e3a     true
            node1_clus2  up/up      169.254.49.125/16  node1       e3b     true
            node2_clus1  up/up      169.254.47.194/16  node2       e3a     true
            node2_clus2  up/up      169.254.19.183/16  node2       e3b     true

----


. Les ports de cluster de chaque nœud sont connectés aux commutateurs de cluster existants de la manière suivante (du point de vue des nœuds) à l'aide de la commande : `network device-discovery show -protocol lldp`
+
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /lldp
            e3a    c1 (6a:ad:4f:98:3b:3f)    Eth1/1            -
            e3b    c2 (6a:ad:4f:98:4c:a4)    Eth1/1            -
node2      /lldp
            e3a    c1 (6a:ad:4f:98:3b:3f)    Eth1/2            -
            e3b    c2 (6a:ad:4f:98:4c:a4)    Eth1/2            -
----
. Les ports et les commutateurs du cluster sont connectés de la manière suivante (du point de vue des commutateurs) à l'aide de la commande : `show cdp neighbors`
+
[listing, subs="+quotes"]
----
c1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1                 Eth1/1         124   H           AFF-A400         e3a
node2                 Eth1/2         124   H           AFF-A400         e3a
c2                    Eth1/31        179   S I s       N3K-C3232C       Eth1/31
c2                    Eth1/32        175   S I s       N3K-C3232C       Eth1/32

c2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute


Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1                 Eth1/1        124    H           AFF-A400         e3b
node2                 Eth1/2        124    H           AFF-A400         e3b
c1                    Eth1/31       175    S I s       N3K-C3232C       Eth1/31
c1                    Eth1/32       175    S I s       N3K-C3232C       Eth1/32
----
. Vérifiez que le réseau en cluster dispose d'une connectivité complète via la commande : `cluster ping-cluster -node node-name`
+
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*

Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e3a
Cluster node1_clus2 169.254.49.125 node1     e3b
Cluster node2_clus1 169.254.47.194 node2     e3a
Cluster node2_clus2 169.254.19.183 node2     e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
. Sur le commutateur c2, arrêtez les ports connectés aux ports du cluster des nœuds.
+
[listing, subs="+quotes"]
----
(c2)# *configure*
Enter configuration commands, one per line. End with CNTL/Z.

(c2)(Config)# *interface*
(c2)(config-if-range)# *shutdown _<interface_list>_*
(c2)(config-if-range)# *exit*
(c2)(Config)# *exit*
(c2)#
----
. Déplacez les ports du cluster de nœuds de l'ancien commutateur c2 vers le nouveau commutateur sw2, à l'aide du câblage approprié pris en charge par NVIDIA SN2100.
. Afficher les attributs des ports réseau : `network port show -ipspace Cluster`
+
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
. Les ports de cluster de chaque nœud sont désormais connectés aux commutateurs de cluster de la façon suivante, du point de vue des nœuds :
+
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /lldp
            e3a    c1  (6a:ad:4f:98:3b:3f)   Eth1/1            -
            e3b    sw2 (b8:ce:f6:19:1a:7e)   swp3              -
node2      /lldp
            e3a    c1  (6a:ad:4f:98:3b:3f)   Eth1/2            -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4              -
----
. Sur le commutateur sw2, vérifier que tous les ports de cluster de nœuds sont en service : `net show interface`
+
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- ----------------------
...
...
UP     swp3         100G  9216   Trunk/L2    e3b               Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2    e3b               Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw1 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)       Master: cluster_isl(UP)
----
. Sur le commutateur c1, arrêtez les ports connectés aux ports du cluster des nœuds.
+
[listing, subs="+quotes"]
----
(c1)# *configure*
Enter configuration commands, one per line. End with CNTL/Z.

(c1)(Config)# *interface*
(c1)(config-if-range)# *shutdown _<interface_list>_*
(c1)(config-if-range)# *exit*
(c1)(Config)# *exit*
(c1)#
----
. Déplacez les ports du cluster de nœuds de l'ancien commutateur c1 vers le nouveau commutateur sw1, à l'aide du câblage approprié pris en charge par NVIDIA SN2100.
. Vérifier la configuration finale du cluster : `network port show -ipspace Cluster`
+
Chaque port doit s'afficher pendant `Link` et en bonne santé pour `Health Status`.

+
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
. Les ports de cluster de chaque nœud sont désormais connectés aux commutateurs de cluster de la façon suivante, du point de vue des nœuds :
+
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp3            -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp3            -
node2      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp4            -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4            -
----
. Sur les commutateurs sw1 et sw2, vérifier que tous les ports de cluster de nœuds sont en service : `net show interface`
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- ----------------------
...
...
UP     swp3         100G  9216   Trunk/L2    e3a               Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2    e3a               Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw2 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw2 (swp16)       Master: cluster_isl(UP)


cumulus@sw2:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- -----------------------
...
...
UP     swp3         100G  9216   Trunk/L2    e3b               Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2    e3b               Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw1 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)       Master: cluster_isl(UP)
----
. Vérifier que les deux nœuds disposent chacun d'une connexion à chaque commutateur : `net show lldp`
+
L'exemple suivant montre les résultats appropriés pour les deux commutateurs :

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost          RemotePort
---------  -----  ----------  ------------------  -----------
swp3       100G   Trunk/L2    node1               e3a
swp4       100G   Trunk/L2    node2               e3a
swp15      100G   BondMember  sw2                 swp15
swp16      100G   BondMember  sw2                 swp16

cumulus@sw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost          RemotePort
---------  -----  ----------  ------------------  -----------
swp3       100G   Trunk/L2    node1               e3b
swp4       100G   Trunk/L2    node2               e3b
swp15      100G   BondMember  sw1                 swp15
swp16      100G   BondMember  sw1                 swp16
----
. Activer la fonction de revert automatique sur les LIFs du cluster : `cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert true`
. Vérifier que toutes les LIFs du réseau du cluster sont de nouveau sur leurs ports de base : `network interface show`
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
----
. Activez la fonction de collecte des journaux du moniteur d'intégrité du commutateur Ethernet pour collecter les fichiers journaux relatifs au commutateur à l'aide des deux commandes suivantes : `system switch ethernet log setup-password` et `system switch ethernet log enable-collection`
+
Entrez : `system switch ethernet log setup-password`

+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*sw1*
*sw2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *sw1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *sw2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
+
Suivi par : `system switch ethernet log enable-collection`

+
[listing, subs="+quotes"]
----
cluster1::*> *system  switch ethernet log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*>
----
+

NOTE: Si l'une de ces commandes renvoie une erreur, contactez le support NetApp.

. Lancez la fonction de collecte du journal du commutateur : `system switch ethernet log collect -device *`
+
Attendez 10 minutes, puis vérifiez que la collecte de journaux a réussi à l'aide de la commande : `system switch ethernet log show`

+
[listing, subs="+quotes"]
----
cluster1::*> system switch ethernet log show
Log Collection Enabled: true

Index  Switch                       Log Timestamp        Status
------ ---------------------------- -------------------  ---------    
1      sw1 (b8:ce:f6:19:1b:42)      4/29/2022 03:05:25   complete   
2      sw2 (b8:ce:f6:19:1b:96)      4/29/2022 03:07:42   complete
----
. Rétablissez le niveau de privilège sur admin : `set -privilege admin`
. Si vous avez supprimé la création automatique de cas, réactivez-la en appelant un message AutoSupport : `system node autosupport invoke -node * -type all -message MAINT=END`

