---
permalink: switch-nvidia-sn2100-storage/migrate-2n-switched-sn2100-storage.html 
sidebar: sidebar 
keywords: two-node switchless cluster environments,migrating to a two-node switched NVIDIA SN2100 cluster environment,switchless cluster environments,NVIDIA SN2100 switches 
summary: 'Si vous disposez d"un environnement de cluster existant à deux nœuds sans commutateur, vous pouvez migrer vers un environnement de cluster à deux nœuds commutés à l"aide de commutateurs NVIDIA SN2100 pour vous permettre d"évoluer au-delà de deux nœuds dans le cluster.' 
---
= Migrer vers un cluster commuté à deux nœuds avec des commutateurs de cluster NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous disposez d'un environnement de cluster existant à deux nœuds sans commutateur, vous pouvez migrer vers un environnement de cluster à deux nœuds commutés à l'aide de commutateurs NVIDIA SN2100 pour vous permettre d'évoluer au-delà de deux nœuds dans le cluster.

La procédure à suivre dépend du fait que chaque contrôleur dispose de deux ports réseau de cluster dédiés ou d'un seul port de cluster par contrôleur.  Le processus décrit fonctionne pour tous les nœuds utilisant des ports optiques ou Twinax, mais n'est pas pris en charge sur ce commutateur si les nœuds utilisent des ports RJ45 10GBASE-T intégrés pour les ports du réseau de cluster.



== Exigences de révision

.Ce dont vous aurez besoin
Pour la configuration sans commutateur à deux nœuds, assurez-vous que :

* La configuration sans commutateur à deux nœuds est correctement mise en place et fonctionne.
* Les nœuds exécutent ONTAP 9.10.1P3 et versions ultérieures.
* Tous les ports du cluster sont opérationnels.
* Toutes les interfaces logiques du cluster (LIF) sont en état actif et sur leurs ports d'origine.


Pour la configuration du commutateur de cluster NVIDIA SN2100, assurez-vous que :

* Les deux commutateurs disposent d'une connectivité au réseau de gestion.
* Il existe un accès console aux commutateurs du cluster.
* Les connexions de nœud à nœud et de commutateur à commutateur du commutateur NVIDIA SN2100 utilisent des câbles Twinax ou à fibre optique.
+

NOTE: Voirlink:cabling-considerations-sn2100-storage.html["Considérations relatives au câblage et à la configuration"] pour les mises en garde et plus de détails.

+
Le https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe - Commutateurs"^] Contient plus d'informations sur le câblage.

* Les câbles Inter-Switch Link (ISL) sont connectés aux ports swp15 et swp16 sur les deux commutateurs NVIDIA SN2100.
* La personnalisation initiale des deux commutateurs SN2100 est terminée, de sorte que :
+
** Les commutateurs SN2100 exécutent la dernière version de Cumulus Linux.
** Des fichiers de configuration de référence (RCF) ont été appliqués aux commutateurs
** Toute personnalisation du site, telle que SMTP, SNMP et SSH, est configurée sur les nouveaux commutateurs.






== Déplacer les commutateurs

.À propos des exemples
Les exemples de cette procédure utilisent la nomenclature suivante pour les commutateurs de cluster et les nœuds :

* Les noms des commutateurs SN2100 sont _sw1_ et _sw2_.
* Les noms des SVM du cluster sont _node1_ et _node2_.
* Les noms des LIF sont _node1_clus1_ et _node1_clus2_ sur le nœud 1, et _node2_clus1_ et _node2_clus2_ sur le nœud 2 respectivement.
* Le `cluster1::*>` L'invite indique le nom du cluster.
* Les ports du cluster utilisés dans cette procédure sont _e3a_ et _e3b_.
* Les ports de dérivation prennent le format : swp[port]s[port de dérivation 0-3].  Par exemple, quatre ports de dérivation sur swp1 sont _swp1s0_, _swp1s1_, _swp1s2_ et _swp1s3_.
+
Le https://hwu.netapp.com["Hardware Universe"^] Contient les informations les plus récentes concernant les ports de cluster actuels pour vos plateformes.





=== Étape 1 : Préparer la migration

. Si AutoSupport est activé sur ce cluster, supprimez la création automatique de cas en envoyant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
où _x_ représente la durée de la fenêtre de maintenance en heures.

. Modifiez le niveau de privilège en avancé, puis saisissez `y` lorsqu'on vous invite à continuer :
+
`set -privilege advanced`

+
L'invite avancée(`*>` ) apparaît.





=== Étape 2 : Configurer les câbles et les ports

. Désactivez tous les ports orientés vers les nœuds (à l'exception des ports ISL) sur les deux nouveaux commutateurs de cluster sw1 et sw2.
+
Vous ne devez pas désactiver les ports ISL.

+
.Afficher un exemple
[%collapsible]
====
Les commandes suivantes désactivent les ports côté nœud sur les commutateurs sw1 et sw2 :

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*

cumulus@sw2:~$ *net add interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
====
. Vérifiez que l'ISL et les ports physiques de l'ISL entre les deux commutateurs SN2100 sw1 et sw2 sont actifs sur les ports swp15 et swp16 :
+
`net show interface`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre que les ports ISL sont actifs sur le commutateur sw1 :

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface*

State  Name       Spd   MTU    Mode        LLDP         Summary
-----  ---------  ----  -----  ----------  -----------  -----------------------
...
...
UP     swp15      100G  9216   BondMember  sw2 (swp15)  Master: cluster_isl(UP)
UP     swp16      100G  9216   BondMember  sw2 (swp16)  Master: cluster_isl(UP)
----
+ L'exemple suivant montre que les ports ISL sont actifs sur le commutateur sw2 :

+

[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name       Spd   MTU    Mode        LLDP         Summary
-----  ---------  ----  -----  ----------  -----------  -----------------------
...
...
UP     swp15      100G  9216   BondMember  sw1 (swp15)  Master: cluster_isl(UP)
UP     swp16      100G  9216   BondMember  sw1 (swp16)  Master: cluster_isl(UP)
----
====
. Vérifiez que tous les ports du cluster sont opérationnels :
+
`network port show`

+
Chaque port devrait s'afficher correctement. `Link` et sain pour `Health Status` .

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show*

Node: node1

                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2

                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

----
====
. Vérifiez que toutes les interfaces réseau du cluster sont opérationnelles :
+
`network interface show`

+
Chaque LIF de cluster doit afficher vrai pour `Is Home` et avoir un `Status Admin/Oper` de haut/haut

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
----
====
. Désactiver la restauration automatique sur les LIF du cluster :
+
`network interface modify -vserver Cluster -lif * -auto-revert false`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   false
          node1_clus2   false
          node2_clus1   false
          node2_clus2   false

----
====
. Déconnectez le câble du port de cluster e3a sur le nœud 3, puis connectez e3a au port 1 sur le commutateur de cluster sw1, à l'aide du câblage approprié pris en charge par les commutateurs SN2100.
+
Le https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe - Commutateurs"^] Contient plus d'informations sur le câblage.

. Déconnectez le câble du port de cluster e3a sur node2, puis connectez e3a au port 4 sur le commutateur de cluster sw1, à l'aide du câblage approprié pris en charge par les commutateurs SN2100.
. Sur le commutateur sw1, activez tous les ports orientés vers le nœud.
+
.Afficher un exemple
[%collapsible]
====
La commande suivante active tous les ports connectés au nœud sur le commutateur sw1 :

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net del interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
====
. Sur le commutateur sw1, vérifiez que tous les ports sont actifs :
+
`net show interface all`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface all*

State  Name      Spd   MTU    Mode       LLDP            Summary
-----  --------- ----  -----  ---------- --------------- --------
...
DN     swp1s0    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s1    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s2    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s3    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s0    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s1    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s2    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s3    25G   9216   Trunk/L2                   Master: br_default(UP)
UP     swp3      100G  9216   Trunk/L2    node1 (e3a)    Master: br_default(UP)
UP     swp4      100G  9216   Trunk/L2    node2 (e3a)    Master: br_default(UP)
...
...
UP     swp15     100G  9216   BondMember  swp15          Master: cluster_isl(UP)
UP     swp16     100G  9216   BondMember  swp16          Master: cluster_isl(UP)
...
----
====
. Vérifiez que tous les ports du cluster sont opérationnels :
+
`network port show -ipspace Cluster`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre que tous les ports du cluster sont opérationnels sur les nœuds 1 et 2 :

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

----
====
. Afficher les informations relatives à l'état des nœuds du cluster :
+
`cluster show`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant présente des informations sur l'état et l'éligibilité des nœuds du cluster :

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

----
====
. Déconnectez le câble du port de cluster e3b sur le nœud 3, puis connectez e3b au port 1 sur le commutateur de cluster sw2, à l'aide du câblage approprié pris en charge par les commutateurs SN2100.
. Déconnectez le câble du port de cluster e3b sur node2, puis connectez e3b au port 4 sur le commutateur de cluster sw2, à l'aide du câblage approprié pris en charge par les commutateurs SN2100.
. Sur le commutateur sw2, activez tous les ports orientés vers le nœud.
+
.Afficher un exemple
[%collapsible]
====
Les commandes suivantes activent les ports côté nœud sur le commutateur sw2 :

[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net del interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
====
. Sur le commutateur sw2, vérifiez que tous les ports sont actifs :
+
`net show interface all`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface all*

State  Name      Spd   MTU    Mode       LLDP            Summary
-----  --------- ----  -----  ---------- --------------- --------
...
DN     swp1s0    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s1    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s2    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s3    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s0    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s1    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s2    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s3    25G   9216   Trunk/L2                   Master: br_default(UP)
UP     swp3      100G  9216   Trunk/L2    node1 (e3b)    Master: br_default(UP)
UP     swp4      100G  9216   Trunk/L2    node2 (e3b)    Master: br_default(UP)
...
...
UP     swp15     100G  9216   BondMember  swp15          Master: cluster_isl(UP)
UP     swp16     100G  9216   BondMember  swp16          Master: cluster_isl(UP)
...
----
====
. Sur les deux commutateurs sw1 et sw2, vérifiez que chaque nœud possède une connexion à chaque commutateur :
+
`net show lldp`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant illustre les résultats attendus pour les deux commutateurs sw1 et sw2 :

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1              e3a
swp4       100G   Trunk/L2    node2              e3a
swp15      100G   BondMember  sw2                swp15
swp16      100G   BondMember  sw2                swp16

cumulus@sw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1              e3b
swp4       100G   Trunk/L2    node2              e3b
swp15      100G   BondMember  sw1                swp15
swp16      100G   BondMember  sw1                swp16
----
====




=== Étape 3 : Terminer la procédure

. Afficher les informations relatives aux périphériques réseau détectés dans votre cluster :
+
`net device-discovery show -protocol lldp`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface     Platform
----------- ------ ------------------------- ------------  ----------------
node1      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp3          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp3          -
node2      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp4          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4          -
----
====
. Vérifiez que tous les ports du cluster sont opérationnels :
+
`network port show -ipspace Cluster`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre que tous les ports du cluster sont opérationnels sur les nœuds 1 et 2 :

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e3a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e3a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/10000 healthy  false

----
====
. Activer la restauration automatique sur tous les LIF du cluster :
+
`net interface modify -vserver Cluster -lif * -auto-revert true`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *net interface modify -vserver Cluster -lif * -auto-revert true*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
----
====
. Vérifiez que toutes les interfaces affichent « vrai » pour `Is Home` :
+
`net interface show -vserver Cluster`

+

NOTE: Cela peut prendre une minute.

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant montre que toutes les LIF sont opérationnelles sur les nœuds 1 et 2 et que `Is Home` Les résultats sont exacts :

[listing, subs="+quotes"]
----
cluster1::*> *net interface show -vserver Cluster*

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e3b     true

----
====
. Vérifiez que les paramètres sont désactivés :
+
`network options switchless-cluster show`

+
.Afficher un exemple
[%collapsible]
====
Le résultat erroné de l'exemple suivant indique que les paramètres de configuration sont désactivés :

[listing, subs="+quotes"]
----
cluster1::*> *network options switchless-cluster show*
Enable Switchless Cluster: *false*
----
====
. Vérifiez l'état des nœuds membres du cluster :
+
`cluster show`

+
.Afficher un exemple
[%collapsible]
====
L'exemple suivant présente des informations sur l'état et l'éligibilité des nœuds du cluster :

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. Vérifiez la connectivité des interfaces du cluster distant :


[role="tabbed-block"]
====
.ONTAP 9.9.1 et versions ultérieures
--
Vous pouvez utiliser le `network interface check cluster-connectivity` commande permettant de lancer une vérification d'accessibilité pour la connectivité du cluster, puis d'afficher les détails :

`network interface check cluster-connectivity start`et `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*REMARQUE :* Attendez quelques secondes avant d’exécuter le programme. `show` commande pour afficher les détails.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Toutes les versions ONTAP
--
Pour toutes les versions ONTAP , vous pouvez également utiliser `cluster ping-cluster -node <name>` commande pour vérifier la connectivité :

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node1
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)

Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[étape 8]] Activez la fonction de collecte des journaux de surveillance de l'état du commutateur Ethernet pour collecter les fichiers journaux relatifs au commutateur, à l'aide des commandes :
+
`system switch ethernet log setup-password`et `system switch ethernet log enable-collection`

+
Entrer: `system switch ethernet log setup-password`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*sw1*
*sw2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *sw1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *sw2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
====
+
Suivi de:

+
`system switch ethernet log enable-collection`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*>
----
====
+

NOTE: Si l'une de ces commandes renvoie une erreur, contactez le support NetApp .

. Lancer la fonction de collecte des journaux de commutation :
+
`system switch ethernet log collect -device *`

+
Attendez 10 minutes, puis vérifiez que la collecte des journaux a réussi à l'aide de la commande :

+
`system switch ethernet log show`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log show*
Log Collection Enabled: true

Index  Switch                       Log Timestamp        Status
------ ---------------------------- -------------------  ---------    
1      sw1 (b8:ce:f6:19:1b:42)      4/29/2022 03:05:25   complete   
2      sw2 (b8:ce:f6:19:1b:96)      4/29/2022 03:07:42   complete
----
====
. Rétablir le niveau de privilège à administrateur :
+
`set -privilege admin`

. Si vous avez désactivé la création automatique de dossiers, réactivez-la en envoyant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`


