---
permalink: switch-nvidia-sn2100-storage/replace-sn2100-switch-storage.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nvidia, switch, cluster, network, nondisruptive, procedure, ndu, replace a nvidia sn2100 cluster switch - nvidia SN2100 
summary: 'Remplacement d"un commutateur de stockage NVIDIA SN2100 défectueux dans le cadre d"une procédure non perturbatrice (NDU).' 
---
= Remplacer un commutateur de stockage NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez remplacer un commutateur de stockage NVIDIA SN2100 défectueux. Il s’agit d’une procédure non perturbatrice.

.Avant de commencer
Avant d'installer le logiciel Cumulus et les RCF sur un commutateur de stockage NVIDIA SN2100, assurez-vous que :

* Votre système peut prendre en charge les commutateurs de stockage NVIDIA SN2100.
* Vous avez téléchargé les RCF applicables.


Le http://hwu.netapp.com["Hardware Universe"^] fournit des informations complètes sur les ports pris en charge et leurs configurations.

La configuration réseau existante doit présenter les caractéristiques suivantes :

* Suivez toutes les étapes de dépannage pour confirmer que vous devez remplacer votre interrupteur.
* Assurez-vous que la connectivité de gestion existe sur les deux commutateurs.
+

NOTE: Assurez-vous que toutes les étapes de dépannage ont été effectuées pour confirmer que votre commutateur doit être remplacé.



Le commutateur de remplacement NVIDIA SN2100 doit présenter les caractéristiques suivantes :

* La connectivité du réseau de gestion est fonctionnelle.
* Vous pouvez accéder au commutateur de remplacement via la console.
* L'image appropriée du système d'exploitation RCF et Cumulus est chargée sur le commutateur.
* La personnalisation initiale du commutateur est terminée.


.Résumé de la procédure
Cette procédure remplace le deuxième commutateur de stockage NVIDIA SN2100 sw2 par le nouveau commutateur NVIDIA SN2100 nsw2.  Les deux nœuds sont le nœud 1 et le nœud 2.

Étapes à suivre :

* Confirmez que l'interrupteur à remplacer est bien le sw2.
* Débranchez les câbles de l'interrupteur sw2.
* Rebranchez les câbles au commutateur nsw2.
* Vérifiez toutes les configurations des périphériques sur le commutateur nsw2.


.Étapes
. Si AutoSupport est activé sur ce cluster, supprimez la création automatique de cas en envoyant un message AutoSupport :
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ représente la durée de la fenêtre de maintenance en heures.

. Passez au niveau de privilège avancé en saisissant *y* lorsque vous êtes invité à continuer :
+
`set -privilege advanced`

. Vérifiez l'état de santé des ports du nœud de stockage pour confirmer la connexion au commutateur de stockage S1 :
+
`storage port show -port-type ENET`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage 100    enabled  online      30
node2
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage 100    enabled  online      30
cluster1::*>
----
====
. Vérifiez que le commutateur de stockage sw1 est disponible :
+
`network device-discovery show -protocol lldp`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1/lldp
            e0M    sw1 (00:ea:bd:68:6a:e8)   Eth1/46           -
            e0b    sw2 (6c:b2:ae:5f:a5:b2)   Ethernet1/16      -
            e0c    SHFFG1827000286 (d0:39:ea:1c:16:92)
                                             e0a               -
            e0e    sw3 (6c:b2:ae:5f:a5:ba)   Ethernet1/18      -
            e0f    SHFFG1827000286 (00:a0:98:fd:e4:a9)
                                             e0b               -
            e0g    sw4 (28:ac:9e:d5:4a:9c)   Ethernet1/11      -
            e0h    sw5 (6c:b2:ae:5f:a5:ca)   Ethernet1/22      -
            e1a    sw6 (00:f6:63:10:be:7c)   Ethernet1/33      -
            e1b    sw7 (00:f6:63:10:be:7d)   Ethernet1/34      -
            e2a    sw8 (b8:ce:f6:91:3d:88)   Ethernet1/35      -
Press <space> to page down, <return> for next line, or 'q' to quit...
10 entries were displayed.
----
====
. Exécutez le `net show interface` Commande à exécuter sur le commutateur fonctionnel pour confirmer que vous pouvez voir les deux nœuds et toutes les étagères :
+
`net show interface`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----

cumulus@sw1:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e3a)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e3a)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
====
. Vérifiez les ports des étagères dans le système de stockage :
+
`storage shelf port show -fields remote-device, remote-port`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device, remote-port*
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   swp3          sw1
3.20    1   -             -
3.20    2   swp4          sw1
3.20    3   -             -
3.30    0   swp5          sw1
3.20    1   -             -
3.30    2   swp6          sw1
3.20    3   -             -
cluster1::*>
----
====
. Retirez tous les câbles connectés au commutateur de stockage sw2.
. Rebranchez tous les câbles au commutateur de remplacement nsw2.
. Revérifiez l'état de santé des ports du nœud de stockage :
+
`storage port show -port-type ENET`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
node1
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage 100    enabled  online      30
node2
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage 100    enabled  online      30
cluster1::*>
----
====
. Vérifiez que les deux commutateurs sont disponibles :
+
`net device-discovery show -protocol lldp`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----

cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1/lldp
            e0M    sw1 (00:ea:bd:68:6a:e8)   Eth1/46           -
            e0b    sw2 (6c:b2:ae:5f:a5:b2)   Ethernet1/16      -
            e0c    SHFFG1827000286 (d0:39:ea:1c:16:92)
                                             e0a               -
            e0e    sw3 (6c:b2:ae:5f:a5:ba)   Ethernet1/18      -
            e0f    SHFFG1827000286 (00:a0:98:fd:e4:a9)
                                             e0b               -
            e0g    sw4 (28:ac:9e:d5:4a:9c)   Ethernet1/11      -
            e0h    sw5 (6c:b2:ae:5f:a5:ca)   Ethernet1/22      -
            e1a    sw6 (00:f6:63:10:be:7c)   Ethernet1/33      -
            e1b    sw7 (00:f6:63:10:be:7d)   Ethernet1/34      -
            e2a    sw8 (b8:ce:f6:91:3d:88)   Ethernet1/35      -
Press <space> to page down, <return> for next line, or 'q' to quit...
10 entries were displayed.
----
====
. Vérifiez les ports des étagères dans le système de stockage :
+
`storage shelf port show -fields remote-device, remote-port`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device, remote-port*
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     swp3            sw1
3.20    1     swp3            nsw2
3.20    2     swp4            sw1
3.20    3     swp4            nsw2
3.30    0     swp5            sw1
3.20    1     swp5            nsw2
3.30    2     swp6            sw1
3.20    3     swp6            nsw2
cluster1::*>
----
====
. Rétablir le niveau de privilège à administrateur :
+
`set -privilege admin`

. Si vous avez désactivé la création automatique de dossiers, réactivez-la en envoyant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.Quelle est la prochaine étape ?
Après avoir remplacé vos interrupteurs, vous pouvez link:../switch-cshm/config-overview.html["configurer la surveillance de l'état du commutateur"].
