---
permalink: switch-nvidia-sn2100-storage/required-documentation-sn2100-storage.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: 'Pour l"installation et la maintenance du commutateur NVIDIA SN2100, assurez-vous de consulter toute la documentation recommandée.' 
---
= Exigences en matière de documentation pour les commutateurs NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour l'installation et la maintenance du commutateur NVIDIA SN2100, assurez-vous de consulter toute la documentation recommandée.

Le tableau suivant répertorie la documentation disponible pour les commutateurs NVIDIA SN2100.

[cols="1,2"]
|===
| Fonction | Description 


 a| 
link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/install-hardware-sn2100-cluster.html["_Configurez et paramétrez vos commutateurs NVIDIA SN2100_"^]
 a| 
Décrit comment installer et configurer vos commutateurs NVIDIA SN2100, y compris l'installation de Cumulus Linux et des RCF applicables.



 a| 
link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100-storage/migrate-cisco-storage-switch-sn2100-storage.html["_Migrer d'un commutateur de stockage Cisco vers un commutateur de stockage NVIDIA SN2100_"^]
 a| 
Décrit comment migrer des environnements qui utilisent des commutateurs de stockage Cisco vers des environnements qui utilisent des commutateurs de stockage NVIDIA SN2100.



 a| 
link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/migrate-2n-switched-sn2100-cluster.html["_Migration vers un cluster commuté à deux nœuds avec des commutateurs de cluster NVIDIA SN2100_"^]
 a| 
Décrit comment migrer vers un environnement commuté à deux nœuds à l'aide de commutateurs de cluster NVIDIA SN2100.



 a| 
link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100-storage/replace-sn2100-switch-storage.html["_Remplacer un commutateur de stockage NVIDIA SN2100_"^]
 a| 
Décrit la procédure de remplacement d'un commutateur de stockage NVIDIA SN2100 défectueux et de téléchargement de Cumulus Linux et du fichier de configuration de référence.

|===