---
permalink: switch-nvidia-sn2100-storage/setup-install-cshm-file.html 
sidebar: sidebar 
keywords: 'install, applicable, configuration, file, cluster, switch, health, monitor, ontap, install the cluster switch health monitor (csm) configuration file for sn2100 switches' 
summary: 'Vous pouvez utiliser cette procédure pour installer le fichier de configuration applicable pour la surveillance de l"état des commutateurs de stockage NVIDIA SN2100.' 
---
= Installez le fichier de configuration du moniteur d'état du commutateur Ethernet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez cette procédure pour installer le fichier de configuration applicable pour la surveillance de l'état du commutateur Ethernet des commutateurs de cluster NVIDIA. Modèles pris en charge :

* MSN2100-CB2FC
* MSN2100-CB2RC
* X190006-PE
* X190006-PI



NOTE: Cette procédure d'installation s'applique à ONTAP 9.10.1 et versions ultérieures.

.Avant de commencer
* Vérifiez que vous devez télécharger le fichier de configuration en exécutant et en `system switch ethernet show` vérifiant si *OTHER* est affiché pour votre modèle.
+
Si votre modèle affiche toujours *OTHER* après avoir appliqué le fichier de configuration, contactez le support NetApp.

* Assurez-vous que le cluster ONTAP est opérationnel.
* Activez SSH pour utiliser toutes les fonctionnalités disponibles dans CSHM.
* Effacez le `/mroot/etc/cshm_nod/nod_sign/` répertoire sur tous les nœuds :
+
.. Entrez le nodeshell :
+
`system node run -node <name>`

.. Passer au privilège avancé :
+
`priv set advanced`

.. Répertoriez les fichiers de configuration dans le `/etc/cshm_nod/nod_sign` répertoire. Si le répertoire existe et contient des fichiers de configuration, il répertorie les noms des fichiers.
+
`ls /etc/cshm_nod/nod_sign`

.. Supprimez tous les fichiers de configuration correspondant à vos modèles de commutateurs connectés.
+
Si vous n'êtes pas sûr, supprimez tous les fichiers de configuration pour les modèles pris en charge répertoriés ci-dessus, puis téléchargez et installez les derniers fichiers de configuration pour ces mêmes modèles.

+
`rm /etc/cshm_nod/nod_sign/<filename>`

.. Vérifiez que les fichiers de configuration supprimés ne se trouvent plus dans le répertoire :
+
`ls /etc/cshm_nod/nod_sign`





.Étapes
. Téléchargez le fichier zip de configuration du moniteur d'état du commutateur Ethernet basé sur la version ONTAP correspondante. Ce fichier est disponible à partir de la https://mysupport.netapp.com/site/info/nvidia-cluster-switch["Switchs Ethernet NVIDIA"^] page.
+
.. Sur la page de téléchargement du logiciel NVIDIA SN2100, sélectionnez *Nvidia CSHM File*.
.. Sur la page attention/doit lire, cochez la case pour accepter.
.. Sur la page Contrat de licence utilisateur final, cochez la case accepter et cliquez sur *accepter et continuer*.
.. Sur la page Nvidia CSHM File - Download, sélectionnez le fichier de configuration applicable. Les fichiers suivants sont disponibles :




[role="tabbed-block"]
====
.ONTAP 9.15.1 et versions ultérieures
--
* MSN2100-CB2FC-v1.4.zip
* MSN2100-CB2RC-v1.4.zip
* X190006-PE-v1.4.zip
* X190006-PI-v1.4.zip


--
.ONTAP 9.11.1 à 9.14.1
--
* MSN2100-CB2FC_PRIOR_R9.15.1-v1.4.zip
* MSN2100-CB2RC_PRIOR_R9.15.1-v1.4.zip
* X190006-PE_PRIOR_9.15.1-v1.4.zip
* X190006-PI_PRIOR_9.15.1-v1.4.zip


--
====
. [[step2]]chargez le fichier zip applicable sur votre serveur Web interne.
. Accédez au paramètre de mode avancé à partir d'un des systèmes ONTAP du cluster.
+
`set -privilege advanced`

. Exécutez la commande switch Health Monitor configure.
+
[listing, subs="+quotes"]
----
cluster1::> *system cluster-switch configure-health-monitor -node * -package-url http://192.168.2.20/usr/download/_[filename.zip]_*
----
. Vérifiez que le résultat de la commande se termine par le texte suivant pour votre version de ONTAP :


[role="tabbed-block"]
====
.ONTAP 9.15.1 et versions ultérieures
--
La surveillance de l'état du commutateur Ethernet a installé le fichier de configuration.

--
.ONTAP 9.11.1 à 9.14.1
--
SHM a installé le fichier de configuration.

--
.ONTAP 9.10.1
--
Le package CSHM téléchargé a été traité avec succès.

--
====
En cas d'erreur, contactez le support NetApp.

. [[step6]]attendez jusqu'à deux fois l'intervalle d'interrogation du moniteur d'état du commutateur Ethernet, détecté en exécutant `system switch ethernet polling-interval show`, avant de terminer l'étape suivante.
. Exécutez la commande `system switch ethernet show` sur le système ONTAP et assurez-vous que les commutateurs de cluster sont détectés avec le champ surveillé défini sur *vrai* et que le champ du numéro de série n'affiche pas *Inconnu*.
+
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet show*
----


.Et la suite ?
Après avoir installé le fichier CSHM, vous link:../switch-cshm/config-overview.html["configurer la surveillance de l'état du commutateur"].
